Repository zulip/zulip, pull requests merged in 2018-02, with the labels that each got.

#8327 webhooks/beeminder/doc.md: Use better macros.
  zerver/webhooks/beeminder/doc.md
Labels: size: S

#8326 doc: Add blog link to CONTRIBUTING.
  CONTRIBUTING.md
Labels: size: S

#8047 vagrant: Use updated box for lxc>=2.1.0.
  Vagrantfile
Labels: needs more work, size: M

#8402 template_parser: Add parsing support for self closing tags as per HTML5.
  static/templates/hotspot_overlay.handlebars
  static/templates/settings/admin-realm-domains-list.handlebars
  static/templates/settings/default-streams-list-admin.handlebars
  static/templates/settings/realm-domains-modal.handlebars
  templates/zerver/emails/missed_message.html
  templates/zerver/hello.html
  tools/lib/template_parser.py
  tools/linter_lib/custom_check.py
  tools/tests/test_template_parser.py
Labels: size: L

#8404 portico: Temporarily fix CSS compilation bug with `calc` property.
  static/styles/portico.css
Labels: size: XS

#8376 Show dark background in popover while avatar loads
  static/styles/dark.css
Labels: size: XS

#8413 Check for OS before patching the lxc-config
  Vagrantfile
Labels: size: M

#8405 landing-page: Change "Help Center" => "Why Zulip".
  templates/zerver/landing_nav.html
Labels: size: XS

#8422 push notifs: For group PMs, identify the users in the group.
  zerver/lib/push_notifications.py
  zerver/tests/test_push_notifications.py
Labels: area: mobile, size: M

#8436 docs: Add VT-X unavailability error
  docs/development/setup-vagrant.md
Labels: size: XS

#8468 slack importer: Change 'total_users' to 'total_channels'.
  zerver/lib/slack_data_to_zulip_data.py
Labels: size: XS

#8443 portico: Highlight active page's title in navbar on why-zulip page.
  templates/zerver/landing_nav.html
Labels: size: XS

#8371 Python dependency upgrade
  requirements/common.in
  requirements/dev.txt
  requirements/prod.txt
  version.py
Labels: area: dependencies, size: S

#8282 queue: Remove missedmessage_email_senders code.
  puppet/zulip/manifests/base.pp
  puppet/zulip_ops/files/nagios3/conf.d/services.cfg
  scripts/nagios/check-rabbitmq-consumers
  tools/test-queue-worker-reload
  zerver/worker/queue_processors.py
Labels: size: M

#8481 copy_and_paste: Fix quirks with some parts of toMarkdown.
  frontend_tests/node_tests/copy_and_paste.js
  static/js/copy_and_paste.js
Labels: size: M

#8505 webhooks/gitlab: Support both "Build Hook" and "Job Hook" events.
  zerver/webhooks/gitlab/tests.py
  zerver/webhooks/gitlab/view.py
Labels: size: M

#8359 Node Unit Tests: Create test for notifications.message_is_notifiable
  frontend_tests/node_tests/notifications.js
  static/js/notifications.js
Labels: size: XL

#8524 integrations: Make minor wording changes to integrations docs.
  zerver/webhooks/beanstalk/doc.md
  zerver/webhooks/bitbucket2/doc.md
  zerver/webhooks/codeship/doc.md
Labels: size: S

#8490 translations: Improve Polish style guide.
  docs/translating/polish.md
Labels: size: XL

#8529 docs: change the dev login image.
  docs/images/zulip-dev.png
Labels: size: XS
