Repository zulip/zulip, pull requests merged in 2018-03, with the labels that each got.

#8338 setting: Fix password label is even shown when email auth is disabled.
  static/templates/settings/account-settings.handlebars
Labels: size: XS

#8561 requirements: Upgrade to virtualenv-clone 0.3.0.
  requirements/common.in
  requirements/dev.txt
  requirements/prod.txt
  version.py
Labels: size: S

#8581 embedded bots: Dispatch all config data on update event.
  zerver/lib/actions.py
Labels: size: XS

#8572 default stream: Fix default stream suggestion do not include private stream.
  frontend_tests/node_tests/stream_data.js
  static/js/stream_data.js
Labels: size: XS

#8594 Fix: broken link zulip/zulipbot
  docs/contributing/zulipbot-usage.md
Labels: size: XS

#8599 popovers: Fix issue with user-info-popover in legacy mention messages.
  static/js/popovers.js
Labels: size: S

#8614 apps: Update desktop app to latest release v1.8.2.
  static/js/portico/landing-page.js
Labels: size: XS

#8621 notifications: Clean and automate global notifications update handler.
  static/js/notifications.js
  static/js/settings_notifications.js
Labels: size: M

#8626 Upgrade moment and moment-timezone
  package.json
  version.py
Labels: size: S

#8611 Fix clipping of stream and topic name in left sidebar
  static/styles/left-sidebar.css
Labels: area: browser-support, area: message view, bug, size: XS

#8638 compose: Don't warn if mentioned stream members form a superset.
  frontend_tests/node_tests/compose.js
  static/js/compose.js
Labels: size: S

#8635 Update yarn.lock for moment and moment-timezone upgrade
  version.py
  yarn.lock
Labels: size: XL

#8657 mypy: Migrate queue_processors.py to python3 annotations & simplify
  zerver/worker/queue_processors.py
Labels: size: XL

#8664 portico: Prevent Firefox from bfcaching the page.
  static/js/portico/landing-page.js
Labels: area: browser-support, area: portico, bug, size: S

#8684 lint: Replace 'return undefined;' with 'return;'.
  .eslintrc.json
  frontend_tests/node_tests/people.js
  frontend_tests/node_tests/people_errors.js
  frontend_tests/node_tests/search_suggestion.js
  frontend_tests/node_tests/topic_generator.js
  package.json
  static/js/blueslip.js
  static/js/common.js
  static/js/compose_fade.js
  static/js/copy_and_paste.js
  static/js/dict.js
  static/js/echo.js
  static/js/hashchange.js
  static/js/localstorage.js
  static/js/markdown.js
  static/js/message_list.js
  static/js/narrow_state.js
  static/js/people.js
  static/js/stream_data.js
  static/js/typing.js
  static/js/user_groups.js
  version.py
  yarn.lock
Labels: area: testing-infrastructure, size: XL

#8693 tools: Ensure mypy is run on .pyi files.
  tools/run-mypy
Labels: size: S

#8681 attachments_ui: Removed exporting of bytes_to_size function
  static/js/attachments_ui.js
Labels: size: S

#8726 Add typing.initialize() to prevent tracebacks.
  static/js/typing.js
  static/js/ui_init.js
Labels: size: M

#8740 subscriptions: Fix broken line wrapping in subscriptions modal.
  frontend_tests/node_tests/subs.js
  static/js/subs.js
  static/styles/subscriptions.css
  static/templates/subscription.handlebars
Labels: area: i18n, area: stream settings, bug, priority: blocker, size: L

#8785 docs: Remove unnecessary lines from oauth docs.
  docs/subsystems/oauth.md
Labels: size: S

#8789 docs: Replace SEND_ALL with ALWAYS_SEND_ALL_HOTSPOTS in hotspots.
  docs/subsystems/hotspots.md
Labels: size: XS

#8794 team page: Add contributions for Zulip Terminal.
  static/js/portico/team.js
  static/styles/portico.css
  templates/zerver/team.html
  tools/update-authors-json
Labels: size: S

#8822 stream create: Clean up handlers and docs link.
  static/js/stream_create.js
  static/js/subs.js
Labels: size: M

#8864 settings: Fix typo.
  static/js/settings_bots.js
Labels: size: XS

#8866 node tests: Add 100% coverage for components.js.
  frontend_tests/node_tests/components.js
  tools/test-js-with-node
Labels: size: XL

#8888 desktop-app: Update app to latest v1.9.0.
  static/js/portico/landing-page.js
Labels: size: XS
