Repository zulip/zulip, pull requests merged in 2018-11, with the labels that each got.

#10751 billing: Make URL hash work in billing page
  static/js/billing/billing.js
  templates/corporate/billing.html
Labels: size: S

#10812 fixes #10809
  docs/tutorials/writing-views.md
Labels: size: XS

#10823 docs: Replaced "MagickMock" with "MagicMock".
  docs/testing/testing-with-django.md
Labels: size: S

#10843 auth: Always force Google to show account chooser
  zerver/views/auth.py
Labels: area: authentication, bug, priority: high, size: XS

#10861 billing: Change plan_interval to plan.interval
  corporate/lib/stripe.py
Labels: size: XS

#10767 webhooks/greenhouse: Update docs to conform to style guide.
  zerver/webhooks/greenhouse/doc.md
Labels: size: S
