Repository zulip/zulip, pull requests merged in 2018-08, with the labels that each got.

#10145 node tests: Consolidate some set_global() calls.
  frontend_tests/node_tests/activity.js
  frontend_tests/node_tests/alert_words.js
  frontend_tests/node_tests/bot_data.js
  frontend_tests/node_tests/buddy_data.js
  frontend_tests/node_tests/channel.js
  frontend_tests/node_tests/common.js
  frontend_tests/node_tests/compose.js
  frontend_tests/node_tests/compose_pm_pill.js
  frontend_tests/node_tests/settings_org.js
Labels: size: XL

#10140 Upgrade django-auth-ldap to 1.6.0.
  requirements/common.in
  requirements/dev.txt
  requirements/prod.txt
  version.py
  zproject/backends.py
  zproject/settings.py
Labels: size: S

#10168 desktop: Update desktop app to v2.3.5.
  static/js/portico/landing-page.js
Labels: size: XS

#10173 portico: Add links to open source section of /hello.
  templates/zerver/hello.html
Labels: size: S

#10174 docs: Fix typos and sentences in caching docs.
  docs/subsystems/caching.md
Labels: size: S

#10180 emails: Show HHMM timezone on new login emails.
  zerver/signals.py
  zerver/tests/test_new_users.py
Labels: bug, priority: high, size: S

#9968 emoji: Add support for animated GIF images.
  mypy.ini
  zerver/lib/upload.py
  zerver/tests/test_upload.py
Labels: area: emoji, size: L

#10201 group pms: Fix unread count not on the same line of text.
  static/styles/right-sidebar.scss
Labels: bug, priority: blocker, size: XS

#10211 droplets: Update code and remove nvm settings from bashrc
  tools/droplets/create.py
Labels: size: XS

#10232 Realm filters: Allow `#`(hash) based URLs in filter patterns.
  zerver/models.py
  zerver/tests/test_realm_filters.py
Labels: area: settings (admin/org), enhancement, size: XS

#10241 test_event_queue: Refactor database property change more readable.
  zerver/tests/test_event_queue.py
Labels: size: M

#10247 Remove "/stats" command for now.
  zerver/lib/actions.py
  zerver/lib/widget.py
Labels: size: S

#10282 email worker: Fix typo in time.sleep call.
  zerver/management/commands/deliver_email.py
Labels: size: XS

#10281 hotkeys: Allow star message while compose box is open.
  static/js/hotkey.js
Labels: size: XS

#10194 stream settings: Fix hide change-sub-type when admin unsubscribe stream.
  static/js/stream_edit.js
Labels: area: real-time sync, area: stream settings, bug, size: XS

#10302 requirements: Upgrade python-zulip-api/zulip to 7dfecf557.
  requirements/common.in
  requirements/dev.txt
  requirements/prod.txt
Labels: size: S

#10308 version: Bump PROVISION_VERSION for Python package updates.
  version.py
Labels: size: XS

#10316 node_tests: Fix node tests for recent changes.
  frontend_tests/node_tests/emoji.js
Labels: size: S

#10183 user docs: Update language in admin-only.
  templates/zerver/help/include/admin-only.md
Labels: size: XS

#10317 requirements: Upgrade python-zulip-api/zulip to 7dfecf557.
  requirements/common.in
  requirements/dev.txt
  requirements/prod.txt
  version.py
Labels: size: S

#10326 settings: Rename emoji settings.
  static/js/settings.js
  templates/zerver/help/display-emoji-as-text.md
  templates/zerver/help/enable-emoticon-translations.md
Labels: size: S

#10325 plans: Remove question about proration.
  templates/zerver/faq.html
Labels: size: S

#10352 pypi: Upgrade to release 0.5.3.
  requirements/common.in
  requirements/dev.txt
  requirements/prod.txt
  version.py
Labels: size: S

#10321 user docs: Update notification docs.
  templates/zerver/help/about-streams-and-topics.md
  templates/zerver/help/configure-desktop-notifications.md
  templates/zerver/help/configure-email-notifications.md
  templates/zerver/help/configure-mobile-notifications.md
  templates/zerver/help/include/sidebar.md
  templates/zerver/help/pm-mention-alert-notifications.md
  templates/zerver/help/set-notifications-for-a-single-stream.md
  templates/zerver/help/stream-notifications.md
  templates/zerver/help/troubleshooting-desktop-notifications.md
Labels: size: XL

#10365 tests: Fully cover server_events_dispatch.js.
  frontend_tests/node_tests/dispatch.js
  tools/test-js-with-node
Labels: size: XL

#10384 templates: Replace &nbsp; with normal spaces.
  static/templates/subscription_type.handlebars
Labels: size: XS

#10380 docs: Update intros to production install pages.
  docs/production/install.md
  docs/production/requirements.md
Labels: size: S

#10392 styles: Fix the oversized search bar on mobile.
  static/styles/media.scss
Labels: size: S

#10394 Remove `code` from JsonableError.__init__.
  tools/test-backend
  zerver/lib/exceptions.py
Labels: size: S

#10404 settings: Fix an error for non-admins on the custom profile fields page.
  static/js/settings_profile_fields.js
Labels: size: S

#10411 node tests: Add more coverage for input pills.
  frontend_tests/node_tests/input_pill.js
Labels: size: L

#10433 muting: Correct agrammatical error message.
  zerver/openapi/zulip.yaml
  zerver/tests/test_muting.py
  zerver/views/muting.py
Labels: size: S

#10445 Adjust the message feed for long messages.
  static/js/compose_actions.js
Labels: size: S

#10443 user settings: Improve style of "Preview profile" btn.
  static/styles/settings.scss
  static/templates/settings/account-settings.handlebars
Labels: size: S

#10447 desktop: Update desktop app to v2.3.6.
  static/js/portico/landing-page.js
Labels: size: XS

#10448 Add more space between compose box and selected message.
  static/js/compose_actions.js
Labels: size: XS

#10390 right-sidebar: Fix keyboard shortcut icon for right night mode coloring.
  static/js/resize.js
  static/js/scroll_bar.js
  static/js/ui_init.js
  static/styles/right-sidebar.scss
  templates/zerver/app/right_sidebar.html
Labels: size: S

#10422 node tests: Add test coverage for input pills.
  static/js/input_pill.js
  static/js/user_pill.js
  tools/test-js-with-node
Labels: size: L
