Repository zulip/zulip, pull requests merged in 2018-04, with the labels that each got.

#8910 style: Give inputs with `type="number"` a dark background in night mode.
  static/styles/night_mode.css
Labels: size: XS

#8940 docs: Correct broken link gsoc-ideas.
  docs/overview/gsoc-ideas.md
Labels: size: XS

#8948 pypi: Upgrade to release 0.4.3.
  requirements/common.in
  requirements/dev.txt
  requirements/prod.txt
  version.py
Labels: size: S

#8967 refactor: Rename mark_message(s)_as_read to notify_server_message(s)_read
  frontend_tests/node_tests/compose_actions.js
  frontend_tests/node_tests/dispatch.js
  static/js/compose_actions.js
  static/js/message_flags.js
  static/js/narrow.js
  static/js/pointer.js
  static/js/unread_ops.js
Labels: area: refactoring, size: M

#8976 Extract add_narrow_conditions().
  zerver/views/messages.py
Labels: size: L

#8983 vagrant: Fix link to testing docs in motd
  Vagrantfile
Labels: size: XS

#8993 Bump provision after clipboard package update.
  version.py
Labels: size: XS

#8999 registration: Catch email validation error and show error message
  templates/zerver/invalid_email.html
  zerver/tests/test_signup.py
  zerver/views/registration.py
Labels: size: M

#9015 Slack importer: Map Slack command for mentions to Zulip's all.
  zerver/lib/slack_message_conversion.py
Labels: size: XS

#9013 Dark-mode: Update rail-y to match dark theme.
  static/styles/night_mode.css
Labels: size: XS

#8719 uploads: Make web app more XSS safe from user uploaded files.
  puppet/zulip/files/nginx/zulip-include-maybe/uploads-route.direct
  puppet/zulip/files/nginx/zulip-include-maybe/uploads-route.internal
Labels: size: XS

#9038 slack importer: User session.get to recycle previous connections.
  zerver/lib/slack_data_to_zulip_data.py
Labels: size: XS

#9053 scripts: Remove the depreciated script 'postgres-reset-sequences'.
  scripts/setup/postgres-reset-sequences
  zerver/management/commands/import.py
Labels: size: S

#9035 slack import: Support Custom profile fields.
  zerver/lib/slack_data_to_zulip_data.py
  zerver/tests/test_slack_importer.py
Labels: size: XL

#9062 browser-support: Add string.prototype.endswith polyfill.
  package.json
  tools/webpack.assets.json
  version.py
  yarn.lock
Labels: size: S

#9067 user-docs subsystem: Fix broken markdown.
  docs/subsystems/user-docs.md
Labels: size: XS

#9069 Fixed typo
  docs/production/install-existing-server.md
Labels: size: XS

#9075 settings: Revert checkmark icon to fontawesome and checkbox-green.
  static/images/icon-checkbox-green.svg
  static/images/icon-checkbox-white.svg
  static/js/settings_ui.js
  static/styles/settings.css
  static/templates/settings/settings-save-discard-widget.handlebars
Labels: area: settings (admin/org), priority: blocker, size: S

#8489 invites ui: fixed rerendering of invites list
  static/js/settings_invites.js
Labels: size: M

#9109 pypi: Upgrade to release 0.4.4.
  requirements/common.in
  requirements/dev.txt
  requirements/prod.txt
  version.py
Labels: size: S

#9112 webhooks/stripe: Update docs to conform to new style guide.
  static/images/integrations/stripe/001.png
  static/images/integrations/stripe/002.png
  static/images/integrations/stripe/003.png
  zerver/webhooks/stripe/doc.md
Labels: size: L

#9114 coverage: Add coverage to estimate_recent_messages.
  tools/test-backend
  zerver/tests/test_messages.py
Labels: size: M

#9145 portico: Add export advertisement to FAQ.
  templates/zerver/faq.html
Labels: size: S

#9158 compose: Refactor compose box from `<table>` to `<div>` structure.
  static/styles/night_mode.css
Labels: area: compose, area: i18n, bug, size: XS

#9171 quick fix: Revert ES6 idiom that istanbul warns about.
  frontend_tests/node_tests/bot_data.js
Labels: size: S

#9192 docs: Make minor fixes to mobile-push-notifications.html.
  docs/production/mobile-push-notifications.md
Labels: size: S

#9215 portico: Update text on confirm_continue_registration.
  static/styles/portico-signin.css
  templates/zerver/confirm_continue_registration.html
  zerver/tests/test_auth_backends.py
Labels: size: S

#9235 settings: Fix escaping of HTML in checkbox labels.
  static/templates/settings/settings_checkbox.handlebars
Labels: area: emoji, area: settings (user), bug, size: XS

#9237 org settings: Fix word-wrapping CSS in "users" section.
  static/styles/settings.css
Labels: area: settings (admin/org), bug, size: XS

#9236 settings: Make bot-settings tabs look better in dark mode.
  static/styles/night_mode.css
Labels: area: settings (user), bug, size: S
