Repository zulip/zulip, pull requests merged in 2018-06, with the labels that each got.

#9626 bug: corrected typo(mispelling of problems) in VagrantFile
  Vagrantfile
Labels: size: XS

#9633 test-api: Test against generic fixtures.
  zerver/lib/api_test_helpers.py
Labels: size: S

#9587 [WIP] Add CircleCI support for Ubuntu Bionic
  .circleci/config.yml
Labels: size: L

#9646 custom fields: Fix buggy behaviour of trash icon in choice type of field.
  static/js/settings_profile_fields.js
Labels: size: XS

#9660 Fix very recent build error w/url coverage for casper.
  zerver/lib/test_helpers.py
Labels: size: XS

#9670 python3 super
  zerver/views/auth.py
  zproject/settings.py
Labels: size: XS

#9672 install-node: Upgrade to yarn 1.7.0.
  scripts/lib/install-node
  version.py
Labels: size: XS

#9701 portico: Restyle blockquotes on Why Zulip.
  static/styles/landing-page.scss
  templates/zerver/why-zulip.md
Labels: size: M

#9694 Update teamcity webhook to include branch name
  zerver/webhooks/teamcity/fixtures/success_branch.json
  zerver/webhooks/teamcity/tests.py
  zerver/webhooks/teamcity/view.py
Labels: size: L

#9707 Fix the autofocus of registration form
  templates/zerver/register.html
Labels: size: S

#9712 message edit: Fix edit author text overflow on images.
  frontend_tests/node_tests/templates.js
  static/styles/zulip.scss
  static/templates/message_edit_history.handlebars
Labels: area: message-editing, bug, size: M

#9718 Fix a typo in search.js
  static/js/search.js
Labels: size: XS

#9720 left-sidebar: Fix opening of compose box on narrowing using hotkeys.
  frontend_tests/node_tests/components.js
  static/js/keydown_util.js
Labels: size: XS

#9717 webhooks/trello: Mention that Trello script can be run from anywhere.
  zerver/webhooks/trello/doc.md
Labels: size: S

#9737 night-mode: Fix incorrectly-colored user profile in mobile view.
  static/styles/night_mode.scss
Labels: size: XS

#9730 features: Standardize width of feature blocks with pseudoelements.
  templates/zerver/features.html
Labels: area: portico, bug, size: XS

#9728 message: Fix opening of compose box on mobile webapp.
  static/js/click_handlers.js
Labels: size: S

#9719 Replace all user-facing references to "invite-only" with "private".
  analytics/management/commands/stream_stats.py
  docs/overview/architecture-overview.md
  docs/production/security-model.md
  docs/testing/manual-testing.md
  frontend_tests/node_tests/templates.js
  static/templates/recipient_row.handlebars
  static/templates/subscription_type.handlebars
  templates/zerver/api/arguments.json
  templates/zerver/api/get-all-streams.md
  templates/zerver/api/get-subscribed-streams.md
  templates/zerver/app/compose.html
  templates/zerver/help/create-a-stream.md
  templates/zerver/integrations/hubot.md
Labels: area: documentation (user), size: M

#9715 provision: close hash file.
  tools/lib/provision.py
Labels: size: S

#9630 docs: Remove the footer, which directed people to help with docs.
  static/styles/portico.scss
  templates/zerver/api/main.html
  templates/zerver/help/main.html
Labels: size: S

#9739 node tests: Improve coverage for settings_bots.js
  frontend_tests/node_tests/settings_bots.js
Labels: size: L

#9741 message_edit: Add coverage for get_deletability function.
  frontend_tests/node_tests/message_edit.js
Labels: size: M

#9758 zcommands: Add zcommand module and separate test module.
  zerver/lib/zcommand.py
  zerver/tests/test_messages.py
  zerver/tests/test_zcommand.py
  zerver/views/messages.py
Labels: size: XL

#9778 night-mode: Remove background from edit topic form.
  static/styles/zulip.scss
Labels: size: XS

#9776 settings: Clean up styling of the Mentor field.
  static/styles/settings.scss
Labels: size: S

#9773 scroll_bar: Initialize scroll_bar in ui_init.js.
  .eslintrc.json
  static/js/scroll_bar.js
  static/js/ui_init.js
Labels: size: S

#9772 notifications: Simplify notification messages for new subscriptions.
  zerver/tests/test_subs.py
  zerver/views/streams.py
Labels: size: M

#9733 matrix/irc: Update docs to conform to style guide.
  templates/zerver/help/include/configure-matrix-bridge.md
  templates/zerver/integrations/irc.md
  templates/zerver/integrations/matrix.md
Labels: size: XL

#9764 emoji: Fix a bug where emoticon translation is not done after a newline.
  zerver/lib/bugdown/__init__.py
  zerver/tests/fixtures/markdown_test_cases.json
Labels: size: S

#9784 tests: Use Set instead of List in import tests.
  zerver/tests/test_import_export.py
Labels: size: XS

#9721 search: Fix "Enter to search" while using an input method.
  static/js/search.js
Labels: area: i18n, area: keyboard UI, bug, priority: high, size: S

#9788 zcommand: Strip the slash in the server side.
  static/js/zcommand.js
  zerver/lib/zcommand.py
  zerver/tests/test_zcommand.py
Labels: size: S

#9799 right sidebar: Expand sidebar block width for greater click area.
  static/styles/right-sidebar.scss
  static/templates/group_pms.handlebars
  static/templates/user_presence_row.handlebars
Labels: area: right-sidebar, bug, size: S

#9796 emoji: Add some edge-casey ordering tests for emoji.
  zerver/tests/fixtures/markdown_test_cases.json
Labels: size: S

#9798 user docs: Update desktop notifications article.
  templates/zerver/help/configure-desktop-notifications.md
Labels: size: M

#9794 search: Add search_pill.js with basic operations.
  .eslintrc.json
  frontend_tests/node_tests/search_pill.js
  static/js/search_pill.js
  tools/test-js-with-node
  zproject/settings.py
Labels: size: XL

#9791 Use assert_json_success instead of assertTrue.
  zerver/tests/test_users.py
Labels: size: XS

#9783 hotkeys: Deactivate control-shift-k and control-shift-s hotkeys.
  frontend_tests/node_tests/hotkey.js
  static/js/hotkey.js
Labels: size: S

#9805 Fix the full_name hidden bug when user has no other account.
  static/js/portico/signup.js
Labels: size: XS

#9836 test flake: Prevent flaky test with less common id.
  zerver/tests/test_bots.py
Labels: size: XS

#9843 settings: Fix focusing of `your-account` prior complete loading.
  templates/zerver/app/settings_overlay.html
Labels: area: settings UI, bug, size: XS

#9826 streams-settings: Fix toggle icon not updating.
  static/js/stream_create.js
Labels: size: XS

#9781 settings: Fix broken setting items in smaller window.
  static/js/click_handlers.js
  static/js/settings_panel_menu.js
Labels: size: S

#9829 user docs: Remove admin-only stream management from member docs.
  templates/zerver/help/include/sidebar.md
Labels: size: XS

#9837 Replace remaining user-facing occurences of the term "invite-only".
  templates/zerver/features.html
  zerver/lib/actions.py
  zerver/tests/test_subs.py
  zerver/views/streams.py
Labels: area: documentation (user), size: S

#9832 widgets: Fix empty message_content of "All messages" widgets.
  static/js/tictactoe_widget.js
  static/js/voting_widget.js
  static/js/widgetize.js
Labels: bug, size: L

#9831 docs: Fix typos in mobile-push-notifications.
  docs/production/mobile-push-notifications.md
Labels: size: XS
