Repository zulip/zulip, pull requests merged in 2018-05, with the labels that each got.

#9292 push_notifications: Format blockquotes properly in text_output.
  zerver/lib/push_notifications.py
  zerver/tests/fixtures/markdown_test_cases.json
Labels: area: notifications (messages), bug, size: S

#9294 portico: Add Slack import to /features.
  templates/zerver/features.html
Labels: size: S

#9299 vagrant: Get vagrant up and running with lxc 3.0.0
  Vagrantfile
Labels: size: XS

#9298 stream-settings: Improve selection behavior around the stream-settings.
  static/styles/subscriptions.scss
Labels: area: stream settings, bug, size: S

#9315 settings: Fix 500 when trying to change email to disposable email
  zerver/lib/actions.py
  zerver/tests/test_settings.py
  zerver/tests/test_signup.py
Labels: area: settings (user), bug, priority: high, size: M

#9321 stream-edit: Fix typo in comment.
  static/js/stream_edit.js
Labels: size: XS

#9363 i18n: Tag missing strings for translation.
  analytics/views.py
  static/templates/subscription_table_body.handlebars
Labels: size: S

#9371 bot-docs: Clean up "Running bot".
  templates/zerver/api/running-bots.md
Labels: size: M

#9435 puppet: Add cron package dependency
  puppet/zulip/manifests/base.pp
Labels: size: XS

#9434 compose: Fix extra space below compose error text.
  templates/zerver/app/compose.html
Labels: size: XS

#9423 push bouncer: Fix instructions in register_server.py.
  zerver/management/commands/register_server.py
Labels: size: S

#9452 mypy: Enable strict optional for check redis management command
  mypy.ini
  zerver/management/commands/check_redis.py
Labels: size: S

#9504 widgets: Prevent traceback for submessage event.
  static/js/widgetize.js
Labels: size: XS

#9505 Fix phantomjs dependency issue on Bionic.
  tools/lib/provision.py
Labels: size: XS

#9518 minor: Add a comment explaining the need of `stopPropagation()`.
  static/js/settings.js
  static/js/settings_account.js
  static/js/settings_invites.js
  static/js/settings_users.js
Labels: size: S

#9523 stream: Deduplicate template code for stream privacy types.
  static/templates/subscription_creation_form.handlebars
Labels: size: M

#9524 messages: Allow "no topic" topics editable indefinitely.
  zerver/tests/test_messages.py
  zerver/views/messages.py
Labels: area: topics, bug, size: S

#9515 docs: Update dev server manual installation instructions.
  docs/development/setup-advanced.md
Labels: size: XS

#9534 desktop: Update app version to v2.3.1.
  static/js/portico/landing-page.js
Labels: size: XS

#9536 linter: Fix issue with check-templates output.
  tools/lib/pretty_print.py
Labels: area: tooling, bug, size: XS

#9541 settings: Remove PRIVATE_STREAM_HISTORY_FOR_SUBSCRIBERS.
  zerver/lib/actions.py
  zerver/tests/test_subs.py
  zproject/settings.py
Labels: size: M

#9542 Fix tracebacks related to direct use of msg_list._items.
  static/js/narrow.js
  static/js/ui_init.js
Labels: size: S

#9530 docs: Update installation instructions for Ubuntu 18.04.
  docs/development/overview.md
  docs/development/setup-advanced.md
Labels: size: S

#9459 user groups: Sanitize pill_container selector to avoid escaped strings.
  frontend_tests/node_tests/settings_user_groups.js
  frontend_tests/node_tests/templates.js
  static/js/settings_user_groups.js
  static/templates/admin_user_group_list.handlebars
  static/templates/non_editable_user_group.handlebars
Labels: area: settings (admin/org), bug, size: S

#9563 Upgrade Django to 1.11.3
  requirements/common.in
  requirements/dev.txt
  requirements/prod.txt
  version.py
Labels: size: S

#9568 api docs: Fix broken link.
  templates/zerver/api/configuring-python-bindings.md
Labels: size: XS

#9566 outgoing webhooks: Change default URL in all tests.
  zerver/tests/test_bots.py
  zilencer/management/commands/populate_db.py
Labels: size: S

#9567 search: Handle pm-with/sender failures better.
  frontend_tests/node_tests/narrow_state.js
  frontend_tests/node_tests/people.js
  frontend_tests/node_tests/pm_list.js
  static/js/narrow_state.js
  static/js/people.js
  static/js/pm_list.js
  static/js/typing_events.js
Labels: area: left-sidebar, area: search, bug, priority: high, size: S

#9591 desktop: Update app version to v2.3.2.
  static/js/portico/landing-page.js
Labels: size: XS

#9594 minor: Turn HTML comment into template comment.
  templates/zerver/base.html
Labels: size: XS

#9601 upload: Add test jpg image with no exif data.
  zerver/lib/upload.py
  zerver/tests/images/img_no_exif.jpg
  zerver/tests/test_upload.py
Labels: size: S

#9598 eslint: Enable "no-whitespace-before-property".
  .eslintrc.json
  static/js/narrow.js
Labels: size: XS

#9602 poll widget: Handle unknown keys.
  static/js/voting_widget.js
Labels: size: S
