Repository zulip/zulip, pull requests merged in 2018-09, with the labels that each got.

#10488 minor: Close buddy list when replying with mention.
  static/js/popovers.js
Labels: size: XS

#10460 import: Change absolute path of downloaded avatars in records.json to relative path.
  zerver/data_import/import_util.py
Labels: size: S

#10499 Add coverage for message_events.update_messages().
  frontend_tests/node_tests/message_events.js
Labels: size: XL

#10507 message-box: Show zoom-in cursor on hovering over images.
  static/styles/zulip.scss
Labels: size: XS

#10508 Prevent clicks from closing user profile modal.
  static/js/click_handlers.js
Labels: size: XS

#10521 rest-endpoints.md: Remove duplicate heading.
  templates/zerver/help/include/rest-endpoints.md
Labels: size: XS

#10522 notification: Add a space in narrow to message content.
  static/js/notifications.js
Labels: size: XS

#10523 developer docs: Refer to 'zulipbot add' instead of 'zulipbot label'.
  docs/contributing/accessibility.md
  docs/contributing/zulipbot-usage.md
Labels: area: documentation (developer), size: S

#10519 stream-settings: Remove unnecessary delete text from button.
  static/templates/subscription_settings.handlebars
Labels: size: XS

#10543 zanitizer_config.pm.sample: keep_file → scrub_filename
  tools/zanitizer_config.pm.sample
Labels: size: XS

#10556 forgot-password: Update the text of reset password button.
  templates/zerver/help/change-your-password.md
  templates/zerver/reset.html
Labels: size: XS

#10561 settings: Fix real-time updation of `full_name` property in page_params.
  static/js/user_events.js
Labels: area: settings UI, bug, size: XS

#10564 right sidebar: Change media cut-off for where we hide the buddy list.
  static/js/message_viewport.js
  static/js/scroll_bar.js
  static/styles/media.scss
  templates/zerver/help/move-the-users-list-to-the-left-sidebar.md
Labels: size: S

#10577 webhooks/trello: Fix indentation and numbering.
  zerver/webhooks/trello/doc.md
Labels: size: S

#10574 settings: Properly align preview profile button.
  static/styles/settings.scss
Labels: size: XS

#10581 desktop: Update desktop app link to v2.3.8.
  static/js/portico/landing-page.js
Labels: size: XS

#10584 bug fix: Handle "Subscribe" button in empty views.
  static/js/stream_edit.js
Labels: size: XS
