Repository zulip/zulip, pull requests merged in 2019-11, with the labels that each got.

#13334 blueslip: Apply ESLint
  .eslintignore
  static/js/blueslip.js
Labels: size: L

#13356 urls: Reorder where the accounts/login/google/ endpoint is defined.
  zerver/openapi/zulip.yaml
  zproject/urls.py
Labels: size: S

#13358 unminify: Update for webpack chunk splitting
  zerver/lib/unminify.py
Labels: size: S

#13368 social_backends: If no icon is to be displayed, set display_icon to None.
  templates/zerver/api/server-settings.md
  zerver/openapi/zulip.yaml
  zproject/backends.py
  zproject/prod_settings_template.py
  zproject/test_settings.py
Labels: size: S

#13371 THIRDPARTY: Correct wrong paths; remove entries for deleted files
  docs/THIRDPARTY
Labels: size: XL

#13382 ldap: Fix development environment configuration.
  zerver/lib/dev_ldap_directory.py
  zerver/tests/test_auth_backends.py
  zproject/dev_settings.py
Labels: size: M

#13400 lint: Run mypy with --no-error-summary
  tools/lint
  tools/run-mypy
Labels: size: S

#13406 for/open-source: Update the repo url of Zulip Archive.
  templates/zerver/for/open-source.md
Labels: size: XS

#13408 export-and-import: Update repo url of Zulip Archive.
  docs/production/export-and-import.md
Labels: size: XS

#13412 integrations: Add missing event handling to Gogs.
  zerver/webhooks/gogs/fixtures/issue_comment__edited.json
  zerver/webhooks/gogs/fixtures/issue_comment__new.json
  zerver/webhooks/gogs/fixtures/issues__assigned.json
  zerver/webhooks/gogs/fixtures/issues__closed.json
  zerver/webhooks/gogs/fixtures/issues__edited.json
  zerver/webhooks/gogs/fixtures/issues__opened.json
  zerver/webhooks/gogs/fixtures/issues__reopened.json
  zerver/webhooks/gogs/fixtures/pull_request__assigned.json
  zerver/webhooks/gogs/fixtures/pull_request__edited.json
  zerver/webhooks/gogs/fixtures/pull_request__reopened.json
  zerver/webhooks/gogs/fixtures/pull_request__synchronized.json
  zerver/webhooks/gogs/tests.py
  zerver/webhooks/gogs/view.py
Labels: size: XL

#13417 test_events: Fix apparent typo
  zerver/tests/test_events.py
Labels: size: XS

#13421 actions: Removed redundant assignment of message['mention_data'].
  zerver/lib/actions.py
Labels: size: XS

#13423 push_notifications: Update link to google's upstream API docs.
  zerver/lib/push_notifications.py
Labels: size: S

#13427 buddy_data: Fix node tests
  frontend_tests/node_tests/activity.js
  frontend_tests/node_tests/pm_list.js
  static/js/buddy_data.js
Labels: size: S

#13428 sidebar: Move the buddy list tooltip content logic to JS.
  frontend_tests/node_tests/buddy_data.js
  frontend_tests/node_tests/templates.js
  static/js/buddy_data.js
  static/templates/buddy_list_tooltip_content.hbs
Labels: area: i18n, bug, priority: high, size: XL

#12145 [WIP] Implement Message Edit Echoing
  docs/subsystems/sending-messages.md
  frontend_tests/casper_tests/08-edit.js
  static/js/echo.js
  static/js/message_edit.js
  static/js/message_events.js
  static/js/message_list_view.js
  static/templates/edited_notice.hbs
Labels: has conflicts, size: XL

#13357 js: Automatically convert var to let and const
  .eslintrc.json
  static/js/buddy_data.js
  static/js/condense.js
  static/js/message_edit.js
  static/js/notifications.js
  static/js/tab_bar.js
  static/js/upload.js
Labels: has conflicts, size: XL

#13419 version: Set ZULIP_VERSION = "2.1.dev+git"
  version.py
Labels: size: XS

#13436 tsconfig: Fix typescript-eslint memory usage disaster
  tsconfig.json
Labels: size: S

#13439 docs: Use ZULIP_VERSION
  docs/conf.py
  docs/subsystems/release-checklist.md
Labels: size: S

#12847 narrow: Fix to show last message in narrow when narrow allows.
  frontend_tests/node_tests/narrow_local.js
  static/js/narrow.js
Labels: size: XL
