Repository zulip/zulip, pull requests merged in 2019-09, with the labels that each got.

#13090 Botserver Docs Updates
  templates/zerver/api/deploying-bots.md
Labels: size: S

#13125 webhooks/papertrail: Requests from Papertrail are not JSON requests.
  zerver/webhooks/papertrail/fixtures/incorrect_post.json
  zerver/webhooks/papertrail/tests.py
  zerver/webhooks/papertrail/view.py
Labels: size: M

#13138 mattermost: Fix test flake in test_convert_channel_data
  zerver/tests/test_mattermost_importer.py
Labels: size: S

#13131 ldap: Fix unintended user deactivation in case of connection failure.
  zerver/tests/test_auth_backends.py
  zproject/backends.py
Labels: size: M

#13129 requirements: Use PyPI fork of line_profiler supporting Python 3.7
  requirements/common.in
  requirements/dev.in
  requirements/dev.txt
  requirements/prod.txt
  version.py
Labels: size: S

#13141 ldap: Fix attempting to sync data for deactivated users.
  zerver/management/commands/sync_ldap_user_data.py
  zerver/tests/test_auth_backends.py
  zproject/backends.py
Labels: size: L

#13145 actions: Remove leftover print statement.
  zerver/lib/actions.py
Labels: size: XS

#13152 Revert "provision: Give concrete NFS error message on older OSX versions."
  tools/setup/generate_zulip_bots_static_files.py
Labels: size: S

#13154 styles: Remove overrides for KaTeX line-height and white-space
  static/styles/rendered_markdown.scss
Labels: size: S

#13150 docs: Fix typo in production/email.md.
  docs/production/email.md
Labels: size: XS

#13177 emails: Add realm name to footer of missed message emails.
  templates/zerver/emails/missed_message.source.html
  templates/zerver/emails/missed_message.txt
  zerver/tests/test_email_notifications.py
Labels: size: S

#13171 pm_list: Bot availability status in pm
  frontend_tests/node_tests/pm_list.js
  static/js/pm_list.js
Labels: area: compose, bug, priority: high, size: L

#13197 nginx: Add CORS, HSTS, and X-Frame-Options headers to error responses
  puppet/zulip/files/nginx/zulip-include-common/api_headers
  puppet/zulip/files/nginx/zulip-include-frontend/app
Labels: size: S

#13194 templates: Move page_params to a <div> at the bottom of <body>
  static/js/page_params.js
  templates/zerver/base.html
  zerver/tests/test_home.py
Labels: size: S

#13202 setup-apt-repo: Add ca-certificates to pre_setup_deps
  scripts/lib/setup-apt-repo
Labels: size: XS

#13200 bulk_get_subscriber_user_ids: Sort each user list by ID
  zerver/lib/actions.py
Labels: size: XS

#13207 vagrant docs: specify restart command
  docs/development/setup-vagrant.md
Labels: size: XS

#13201 restart-server: Warn if the shell’s PWD goes through an updated symlink
  scripts/restart-server
Labels: size: S

#13210 docs: Suggest systemctl unmask docker if Docker isn’t running
  docs/development/setup-vagrant.md
Labels: size: S

#13215 requirements: Downgrade transifex-client so we can upgrade six, urllib3.
  requirements/dev.in
  requirements/dev.txt
  version.py
Labels: size: S

#13199 styles: Add overflow: hidden on .message_content
  static/styles/zulip.scss
Labels: area: message view, bug, size: XS

#13221 run-dev: Disable Tornado response decompression
  tools/run-dev.py
Labels: size: S

#13218 devtools: Order the fixtures dropdown menu alphabetically in the IDP.
  static/js/portico/integrations_dev_panel.js
Labels: size: XS
