Repository zulip/zulip, pull requests merged in 2019-04, with the labels that each got.

#12022 css: Add spacing between info and image on /apps.
  static/styles/landing-page.scss
Labels: area: portico, priority: high, size: S

#12057 commands: Fix handling of keyword arguments in `query_ldap` command.
  zerver/management/commands/query_ldap.py
Labels: area: authentication, priority: high, size: XS

#12062 Remove run-dev-queue-processors
  tools/run-dev-queue-processors
  tools/run-dev.py
Labels: size: S

#11989 Fix typo in gsoc-ideas.md
  docs/overview/gsoc-ideas.md
Labels: size: XS

#12076 docs: Add message box to manual testing docs.
  docs/testing/manual-testing.md
Labels: size: L

#12068 spiders: Set error status for exceptions generated by spider.
  tools/documentation_crawler/documentation_crawler/spiders/common/spiders.py
Labels: size: XS

#12087 Correctly label the shortcut for starting a PM as "(x)" instead of "(c)"
  static/js/compose.js
Labels: size: XS

#12089 circleci: Downgrade back to 2.0
  .circleci/config.yml
Labels: size: S

#12010 backup: Use tar --transform to arrange the tarball instead of symlinks
  scripts/setup/restore-backup
  zerver/management/commands/backup.py
Labels: size: L

#12112 Revert "user-profiles: Lazy load profile pictures when in view."
  static/js/bundles/commons.js
  static/styles/zulip.scss
  static/templates/message_avatar.handlebars
Labels: size: XS

#12023 markdown: Fix unordered list not rendering in blockquote.
  zerver/lib/bugdown/__init__.py
  zerver/tests/fixtures/markdown_test_cases.json
Labels: area: markdown, bug, size: S

#12110 docs: remove repeated 'etc.' word from sending-messages.md
  docs/subsystems/sending-messages.md
Labels: size: XS

#12108 stream-edit: Empty edit stream-name makes the span styling ineffective
  static/styles/subscriptions.scss
Labels: area: stream settings, bug, size: XS

#12127 compose.scss: Fix alignment of "markdown preview" icons.
  static/styles/compose.scss
Labels: size: S

#12129 install-node: Upgrade yarn to 1.15.2.
  scripts/lib/install-node
Labels: size: XS

#12147 scripts: Fix exec invocation for in-process virtualenv activation.
  scripts/lib/setup_path_on_import.py
  tools/lib/provision.py
Labels: area: production, size: XS

#12135 api_docs: Add explicit '-X GET' to curl examples.
  templates/zerver/api/get-all-streams.md
  templates/zerver/api/get-all-users.md
  templates/zerver/api/get-message-history.md
  templates/zerver/api/get-messages.md
  templates/zerver/api/get-org-emoji.md
  templates/zerver/api/get-presence.md
  templates/zerver/api/get-profile.md
  templates/zerver/api/get-raw-message.md
  templates/zerver/api/get-stream-id.md
  templates/zerver/api/get-stream-topics.md
  templates/zerver/api/get-subscribed-streams.md
  templates/zerver/api/get-user-groups.md
Labels: size: M

#12131 navbar: Fix bugs caused by zulip.scss refactor.
  static/styles/night_mode.scss
  static/styles/zulip.scss
Labels: size: XS

#12130 auth: Redirect deactivated user to /login when attempting social login.
  zerver/tests/test_auth_backends.py
  zproject/backends.py
Labels: size: S

#12158 zjquery: Improve on/off handling for events.
  frontend_tests/node_tests/activity.js
  frontend_tests/zjsunit/zjquery.js
Labels: size: XL

#12160 minor: Remove obsolete add_child method.
  frontend_tests/zjsunit/zjquery.js
Labels: size: XS

#12165 list_render: Extend test to verify that list sorting is case insensitive.
  frontend_tests/node_tests/list_render.js
Labels: size: XS

#12177 webpack: Fix node_modules path resolution.
  tools/webpack.config.ts
Labels: size: XS

#12154 render_markdown_path: Convert dicts to dict item tuples for caching.
  zerver/lib/cache.py
  zerver/templatetags/app_filters.py
  zerver/tests/test_decorators.py
Labels: size: XL

#12176 tools/webpack: Run webpack in the foreground
  tools/webpack
Labels: size: S

#12181 package.json: Realphabetize devDependencies.
  package.json
Labels: size: XS

#12164 Revert "Url encoded name of the file should be an ascii."
  zerver/lib/upload.py
  zerver/tests/test_upload.py
  zerver/views/upload.py
Labels: size: L

#12183 terminate-psql-sessions: Only terminate pids on which we have permissions
  scripts/setup/terminate-psql-sessions
Labels: size: S

#12212 docs: Clarify you need to upgrade from git for Zulip Cloud exports.
  docs/production/export-and-import.md
  templates/zerver/help/export-your-organization.md
Labels: size: S

#12220 settings: Fix broken headers in night mode.
  static/styles/night_mode.scss
  static/templates/settings/auth-methods-settings-admin.handlebars
  static/templates/settings/emoji-settings-admin.handlebars
Labels: bug, priority: high, size: S

#12223 Revert "requirements: Upgrade moto from 1.3.7 to 1.3.8."
  requirements/dev.in
  requirements/dev.txt
Labels: size: S

#12216 open graph: Use uploaded realm icon for open graph images.
  templates/zerver/meta_tags.html
  zerver/context_processors.py
  zerver/tests/test_middleware.py
Labels: size: M

#12221 Fixes couple of problems with image pastes on Safari
  frontend_tests/node_tests/upload.js
  static/js/upload.js
  static/third/jquery-filedrop/jquery.filedrop.js
Labels: size: S

#12230 Alignment of first line of text in message view
  static/styles/zulip.scss
Labels: size: XS

#12238 docs: Direct GSoD students to #documentation instead of #GSoC
  docs/contributing/gsod-ideas.md
Labels: size: XS
