Repository zulip/zulip, pull requests merged in 2019-05, with the labels that each got.

#12240 html_to_text: Add delimiters between text from different elements.
  zerver/lib/html_to_text.py
  zerver/lib/realm_description.py
  zerver/tests/test_middleware.py
Labels: size: S

#12256 circleci: Fix redis on Bionic.
  .circleci/config.yml
Labels: size: XS

#12248 management: Don't use sys.exit(1)
  analytics/management/commands/clear_analytics_tables.py
  analytics/management/commands/clear_single_stat.py
  analytics/management/commands/realm_stats.py
  analytics/management/commands/stream_stats.py
  analytics/management/commands/user_stats.py
  zerver/management/commands/add_users_to_mailing_list.py
  zerver/management/commands/check_redis.py
  zerver/management/commands/convert_gitter_data.py
  zerver/management/commands/convert_hipchat_data.py
  zerver/management/commands/convert_slack_data.py
  zerver/management/commands/deactivate_user.py
  zerver/management/commands/delete_old_unclaimed_attachments.py
  zerver/management/commands/email_mirror.py
  zerver/management/commands/fix_unreads.py
  zerver/management/commands/generate_invite_links.py
  zerver/management/commands/generate_realm_creation_link.py
  zerver/management/commands/import.py
  zerver/management/commands/process_queue.py
  zerver/management/commands/rate_limit.py
  zerver/management/commands/realm_domain.py
  zerver/management/commands/realm_filters.py
  zerver/management/commands/send_to_email_mirror.py
  zerver/management/commands/send_webhook_fixture_message.py
  zerver/management/commands/set_message_flags.py
  zerver/management/commands/soft_deactivate_users.py
  zerver/tests/test_management_commands.py
Labels: size: XL

#12254 webhooks/jira: Include issue title in messages.
  zerver/webhooks/jira/tests.py
  zerver/webhooks/jira/view.py
Labels: size: M

#12262 docs: Use systemctl instead of service
  docs/production/maintain-secure-upgrade.md
Labels: size: XS

#12261 docs: Fix upgrade process for Ubuntu 16.04 -> 18.04
  docs/production/maintain-secure-upgrade.md
Labels: size: XS

#12266 Make tests work in reverse order in mattermost_importer
  zerver/tests/test_mattermost_importer.py
Labels: size: M

#12268 mypy: Enable strict_optional for test_outgoing_webhook_interfaces
  mypy.ini
Labels: size: XS

#12269 tools: Remove check-urls linter.
  tools/check-urls
  tools/lint
Labels: size: M

#12231 open graph: Use the complete URL for open graph URLs.
  templates/zerver/meta_tags.html
  zerver/context_processors.py
  zerver/tests/test_middleware.py
Labels: area: portico, bug, size: S

#12278 portico: Updated android screenshot and the associated svg.
  static/images/app-screenshots/android.svg
  static/images/app-screenshots/zulip-android.png
Labels: size: XL

#12028 Cleanup `single_message.handlebars`
  static/styles/drafts.scss
  static/styles/night_mode.scss
  static/styles/zulip.scss
  static/templates/single_message.handlebars
Labels: size: S

#12232 docs: Add numbering to import section of export-and-import.md.
  docs/production/export-and-import.md
Labels: size: S

#12288 custom profile field: Fix styling regression in admin settings.
  static/templates/admin_profile_field_list.handlebars
Labels: size: XS

#12295 css: Remove `display-none` class css entirely.
  static/styles/app_components.scss
  static/styles/portico.scss
  static/templates/admin_user_list.handlebars
  static/templates/edit_bot.handlebars
  static/templates/settings/bot-settings.handlebars
  static/templates/settings/emoji-settings-admin.handlebars
Labels: size: S

#12299 tests: Patch maybe_update_first_visible_message_id properly
  zerver/tests/test_management_commands.py
Labels: size: XS

#12289 ldap: Do not modify self._LDAPUser.attrs in test_query_email_attr.
  zerver/tests/test_auth_backends.py
Labels: area: authentication, area: testing-coverage, bug, priority: high, size: XS

#12296 stream_ui_updates: Add generic `initialize_disable_btn_hint_popover` func.
  static/js/stream_ui_updates.js
  static/styles/popovers.scss
Labels: size: L

#12292 org settings: Change a few references to Jitsi to Jitsi Meet.
  templates/zerver/features.html
  templates/zerver/help/start-a-call.md
  zproject/prod_settings_template.py
  zproject/settings.py
Labels: size: S

#12307 email_mirror: Handle case of unspecified charset in Content-Type header.
  zerver/lib/email_mirror.py
  zerver/tests/test_email_mirror.py
Labels: size: M

#12319 Improve youtube playlist URL previews
  zerver/lib/bugdown/__init__.py
  zerver/tests/test_bugdown.py
Labels: area: markdown, enhancement, size: M

#12326 writing-bots: Use a fenced code block instead of an indented one.
  templates/zerver/api/writing-bots.md
Labels: size: S

#12331 requirements: Downgrade stripe from 2.27.0 to 2.21.0.
  requirements/common.in
  requirements/dev.txt
  requirements/prod.txt
Labels: size: S

#12335 tools: Don't upgrade stripe automatically during dependency upgrade
  tools/upgrade-python-dependencies
Labels: size: M

#12336 navbar: Fix stream + topic jump at 500px.
  static/styles/zulip.scss
Labels: size: XS

#12363 user_profile_modal: Move SimpleBar back to the correct div
  static/templates/user_profile_modal.handlebars
Labels: area: general UI, bug, size: XS

#12361 Revert "gitattributes: Mark yarn.lock as "binary", i.e. suppress diffs."
  .gitattributes
Labels: size: XS

#12373 docs: Update desktop app version to 3.0.0.
  static/js/portico/landing-page.js
Labels: size: XS

#12378 test_retention: Quick fix for the remaining test failure.
  zerver/tests/test_retention.py
Labels: size: XS

#12367 css: Improve SimpleBar scrollbar contrast
  static/styles/components.scss
  static/styles/night_mode.scss
Labels: size: S

#12366 dependencies: Upgrade simplebar to 4.0.0
  package.json
  version.py
  yarn.lock
Labels: area: general UI, bug, size: S

#12396 Move backend and production tests to Ubuntu 16.04 (xenial)
  .circleci/config.yml
  .travis.yml
  docs/testing/continuous-integration.md
  scripts/lib/check-upstart
  tools/ci/production-helper
  tools/ci/setup-production
  tools/ci/success-http-headers.txt
Labels: size: L

#12403 provision: Move apt-get update from retry handler to setup-apt-repo
  scripts/lib/setup-apt-repo
  tools/lib/provision.py
Labels: size: M

#12405 dev-vagrant-docker: Unminimize the minimized Ubuntu cloud image.
  tools/setup/dev-vagrant-docker/Dockerfile
Labels: size: S

#12415 setup-apt-repo: Try to download pre-setup deps before skipping update
  scripts/lib/setup-apt-repo
Labels: area: provision, bug, size: XS

#12418 dev-vagrant-docker: Copy the host user’s uid for the vagrant user
  Vagrantfile
  tools/setup/dev-vagrant-docker/Dockerfile
Labels: size: XS

#12425 Vagrantfile: Add customization to remove log file.
  Vagrantfile
Labels: size: S

#12433 coveragerc: Omit blub
  tools/coveragerc
Labels: area: testing-coverage, size: XS

#12429 Vagrantfile: Restore idempotency to vagrant provision.
  Vagrantfile
Labels: size: XS

#12395 Vagrantfile: Update virtualbox image to bionic
  Vagrantfile
Labels: size: XS

#12437 Vagrantfile: Remove VMmare Fusion provider.
  Vagrantfile
Labels: area: provision, size: S

#12448 Vagrantfile: Update Docker fallback patch for installed but broken case
  Vagrantfile
Labels: size: XS

#12455 Twitter header for Zulip
  static/assets/Twitter Cover/Twitter Cover Zulip.png
  static/assets/Twitter Cover/Twitter Cover Zulip.svg
Labels: size: XL

#12460 webhooks/buildbot: Add missing "skipped" build result code.
  zerver/webhooks/buildbot/fixtures/finished_cancelled.json
  zerver/webhooks/buildbot/tests.py
  zerver/webhooks/buildbot/view.py
Labels: size: S
