Repository zulip/zulip, pull requests merged in 2019-03, with the labels that each got.

#11727 portico: Add ninth logo to /for/open-source testimonial section.
  static/images/landing-page/logos/openshot.png
  static/styles/landing-page.scss
  templates/zerver/for-open-source.html
Labels: size: S

#11735 node tests: Fix recent build break.
  frontend_tests/node_tests/buddy_data.js
Labels: size: XS

#11760 Fix Learn more about mentions link
  templates/zerver/app/home.html
Labels: size: XS

#11790 minor: Fix an artifact of delivery email migration in `populate_analytics_db`.
  analytics/management/commands/populate_analytics_db.py
Labels: size: XS

#11728 Create Wrapper for Rendering Stream Descriptions [Refactor]
  zerver/lib/actions.py
  zerver/lib/bulk_create.py
  zerver/lib/import_realm.py
  zerver/migrations/0206_stream_rendered_description.py
Labels: size: M

#11741 Replace generated U+202A LEFT-TO-RIGHT EMBEDDING with CSS properties
  static/styles/zulip.scss
Labels: size: S

#11883 emoji: Allow users to add emoji or react in mobile browsers.
  static/js/ui_init.js
Labels: area: mobile web, bug, size: S

#11900 Fix the partial visibility of zulip-octopus on landing page.
  static/styles/landing-page.scss
Labels: size: XS

#11957 analytics: Add autofocus to /support input box.
  templates/analytics/support.html
Labels: size: XS

#11968 webhooks/bitbucket: Support empty push payloads with no user info.
  zerver/webhooks/bitbucket/fixtures/force_push_without_user_info.json
  zerver/webhooks/bitbucket/tests.py
  zerver/webhooks/bitbucket/view.py
Labels: size: S

#11971 documentation: Add missing link to upgrade-zulip-from-git doc
  docs/production/export-and-import.md
Labels: size: XS

#11988 portico: Fix trapsarent gradient styling inconsistencies.
  static/styles/landing-page.scss
Labels: size: S

#11993 api_docs/send-message: Specify request command in curl example.
  templates/zerver/api/send-message.md
Labels: size: XS

#11997 coverage: Get Istanbul to recognise typescript modules.
  static/js/dict.ts
  tools/test-js-with-node
Labels: size: S
