Repository zulip/zulip, pull requests merged in 2019-10, with the labels that each got.

#13239 flush-memcached: Respect MEMCACHED_LOCATION; handle errors.
  scripts/setup/flush-memcached
  tools/do-destroy-rebuild-database
  tools/setup/generate-fixtures
  tools/setup/postgres-init-dev-db
Labels: size: M

#13254 typing: Do time math with numbers, not Date objects.
  static/js/typing.js
Labels: size: XS

#13251 setup_venv: Add pkg-config to VENV_DEPENDENCIES
  scripts/lib/setup_venv.py
Labels: size: XS

#13259 node_cache: Preserve symlinks when copying an old node_modules tree
  scripts/lib/node_cache.py
Labels: size: XS

#13260 settings page: Align permission "Discard" option.
  static/styles/settings.scss
  static/templates/settings/settings_save_discard_widget.hbs
Labels: size: S

#13265 docs: add docs/README.md to the exclude_patterns list
  docs/conf.py
Labels: size: XS

#13268 requirements: Upgrade django-sendfile2
  requirements/dev.txt
  requirements/prod.txt
  version.py
  zerver/tests/test_upload.py
Labels: size: S

#13151 provisioning: fix up bash profile creation
  tools/lib/provision_inner.py
Labels: size: M

#13276 test_mattermost_importer: Fix leftover references to message.pub_date.
  zerver/tests/test_mattermost_importer.py
Labels: size: S

#13280 requirements: Add back future
  requirements/dev.txt
  requirements/docs.txt
  requirements/prod.txt
  tools/update-locked-requirements
  version.py
Labels: size: S

#13283 Rename `not_subscribed key` to `not_removed` in users/me/subscriptions.
  templates/zerver/api/remove-subscriptions.md
  zerver/openapi/zulip.yaml
  zerver/tests/test_docs.py
  zerver/tests/test_subs.py
  zerver/views/streams.py
Labels: area: api, area: documentation (api and integrations), priority: high, size: S

#13281 editorconfig: Set JS max_line_length = 100, to match eslintrc
  .editorconfig
Labels: size: XS

#13300 tests: tearDown overrides should call super().tearDown().
  zerver/tests/test_external.py
  zerver/tests/test_i18n.py
  zerver/tests/test_logging_handlers.py
  zerver/tests/test_queue.py
  zerver/tests/test_upload.py
Labels: size: S

#13301 tests: setUp overrides should call super().setUp().
  analytics/tests/test_counts.py
  analytics/tests/test_views.py
  corporate/tests/test_stripe.py
  zerver/lib/test_classes.py
  zerver/tests/test_attachments.py
  zerver/tests/test_auth_backends.py
  zerver/tests/test_bugdown.py
  zerver/tests/test_create_video_call.py
  zerver/tests/test_custom_profile_data.py
  zerver/tests/test_decorators.py
  zerver/tests/test_docs.py
  zerver/tests/test_embedded_bot_system.py
  zerver/tests/test_events.py
  zerver/tests/test_external.py
  zerver/tests/test_hotspots.py
  zerver/tests/test_import_export.py
  zerver/tests/test_logging_handlers.py
  zerver/tests/test_management_commands.py
  zerver/tests/test_narrow.py
  zerver/tests/test_new_users.py
  zerver/tests/test_outgoing_webhook_interfaces.py
  zerver/tests/test_outgoing_webhook_system.py
  zerver/tests/test_push_notifications.py
  zerver/tests/test_reactions.py
  zerver/tests/test_realm.py
  zerver/tests/test_retention.py
  zerver/tests/test_service_bot_system.py
  zerver/tests/test_signup.py
  zerver/tests/test_subs.py
  zerver/tests/test_tutorial.py
  zerver/tests/test_unread.py
  zerver/tests/test_upload.py
  zerver/webhooks/taiga/tests.py
Labels: size: L

#13306 css: Fix azuread-wrapper name.
  static/styles/portico/portico-signin.scss
Labels: size: XS

#13310 test_events: Fix a small typo for test_realm_bots_admin.
  zerver/tests/test_events.py
Labels: size: XS

#13316 hello: Fix carousel indicator buttons
  templates/zerver/hello.html
Labels: size: XS

#13319 version: Only let `git describe` match tags beginning with a digit
  tools/cache-zulip-git-version
  zerver/logging_handlers.py
Labels: size: XS

#13327 docs: Fix formatting of warnings.
  docs/development/setup-advanced.md
  docs/testing/testing.md
Labels: size: S

#13332 test-backend, run-casper: Remove proxy vars instead of setting to ""
  frontend_tests/run-casper
  tools/test-backend
Labels: size: S

#13333 requirements: Upgrade Python requirements
  requirements/dev.txt
  requirements/docs.txt
  requirements/mypy.txt
  requirements/pip.txt
  requirements/prod.txt
  requirements/thumbor-dev.txt
  requirements/thumbor.txt
  version.py
Labels: size: XL

#13335 node_cache: Don’t retry copying node_modules; let yarn do its thing
  scripts/lib/node_cache.py
Labels: size: XS

#13339 docs: Document social_backends in /server_settings.
  templates/zerver/api/server-settings.md
  zerver/openapi/zulip.yaml
Labels: size: L

#13344 pointer: Fix pointer update
  static/js/pointer.js
Labels: size: XS

#13342 nginx: Enable TLS 1.3 if supported
  puppet/zulip/manifests/nginx.pp
  puppet/zulip/templates/nginx.conf.template.erb
Labels: size: S

#13345 eslint: Enable sort-imports rule
  .eslintrc.json
  static/js/portico/landing-page.js
  tools/webpack-helpers.ts
  tools/webpack.config.ts
Labels: size: S

#13343 security: Send SameSite=Lax cookies
  requirements/common.in
  requirements/dev.txt
  requirements/prod.txt
  version.py
  zproject/settings.py
Labels: size: S

#13289 left sidebar: Avoid unnecessary scrollbar.
  static/styles/left-sidebar.scss
  templates/zerver/app/left_sidebar.html
Labels: area: left-sidebar, rust community request, size: S

#13347 docs: Fix typo in gsoc-ideas.md.
  docs/overview/gsoc-ideas.md
Labels: size: XS

#12608 blueslip: Make stacktrace more readable.
  .eslintrc.json
  frontend_tests/node_tests/blueslip_stacktrace.js
  package.json
  static/js/blueslip.js
  static/js/blueslip_stacktrace.ts
  static/js/bundles/app.js
  static/js/click_handlers.js
  static/js/hbs.d.ts
  static/js/tsconfig.json
  static/js/types/stacktrace-gps/index.d.ts
  static/styles/alerts.scss
  static/styles/night_mode.scss
  static/templates/blueslip_stacktrace.hbs
  version.py
  yarn.lock
Labels: size: XL

#13348 docs: Improve SAML development environment docs.
  docs/subsystems/auth.md
Labels: size: S
