Repository zulip/zulip, pull requests merged in 2019-07, with the labels that each got.

#12679 narrow: Fix incorrect method of querying for operands.
  static/js/narrow.js
Labels: size: XS

#12689 provision: Sort system dependencies deterministically
  tools/lib/provision.py
Labels: size: XS

#12706 templates: Fix wrong path to edit-embedded-bot-service template.
  static/js/settings_bots.js
Labels: bug, size: XS

#12703 .editorconfig: Fix invalid brace patterns
  .editorconfig
Labels: size: XS

#12697 bundles: Rename commons.js to common.js
  docs/subsystems/front-end-build-process.md
  static/js/bundles/app.js
  static/js/bundles/common.js
  tools/webpack.assets.json
Labels: size: S

#12696 webhooks/freshdesk/doc.md: Remove unescape_rendered_html kludge
  templates/tests/test_unicode_decimals.html
  templates/zerver/tests/markdown/test_unicode_decimals.md
  zerver/templatetags/app_filters.py
  zerver/tests/test_templates.py
  zerver/views/documentation.py
  zerver/webhooks/freshdesk/doc.md
Labels: size: L

#12717 retention: Split migration deleting and altering ArchivedMessage.
  zerver/migrations/0232_make_archive_transaction_field_not_nullable.py
Labels: size: S

#12719 Mention to update DigitalOcean one click app in release checklist
  docs/subsystems/release-checklist.md
Labels: size: XS

#12732 nginx: Update TLS settings based on Mozilla recommendations 5.0.
  puppet/zulip/files/nginx/nginx.conf
Labels: size: S

#12734 Small line spacing tweaks
  static/styles/zulip.scss
Labels: size: XS

#12745 blueslip: Ignore error events with null error
  static/js/blueslip.js
Labels: size: XS

#12742 activity: Add links to /stats and /activity in /activity/support.
  templates/analytics/support.html
Labels: size: XS

#12749 third: Upgrade spectrum-colorpicker to 1.8.0 from NPM
  docs/THIRDPARTY
  package.json
  static/js/bundles/app.js
  static/styles/popovers.scss
  static/third/spectrum/spectrum.css
  static/third/spectrum/spectrum.js
  tools/webpack-helpers.ts
  tools/webpack.config.ts
  version.py
  yarn.lock
Labels: size: XL

#12763 css: Use SCSS nesting for subscribers' list in subscriptions.scss.
  static/styles/night_mode.scss
  static/styles/subscriptions.scss
Labels: size: XL

#12767 notification bot: Update stream announcement message.
  tools/lib/capitalization.py
  zerver/tests/test_subs.py
  zerver/views/streams.py
Labels: size: S

#12483 url preview: Create a single preview for each URL in a message.
  zerver/lib/bugdown/__init__.py
  zerver/tests/fixtures/markdown_test_cases.json
  zerver/tests/test_bugdown.py
Labels: area: markdown, size: L

#12777 check-templates: Exclude static/icons/fonts/template.hbs.
  tools/check-templates
Labels: size: XS

#12775 message_fetch: Use user IDs for supported operators.
  frontend_tests/node_tests/message_fetch.js
  frontend_tests/node_tests/people.js
  static/js/message_fetch.js
  static/js/people.js
  zerver/views/messages.py
Labels: size: L

#12788 pypi: Upgrade to release 0.6.1.
  requirements/common.in
  requirements/dev.txt
  requirements/prod.txt
  version.py
Labels: size: S

#12792 postgres-create-db: Split into non-pgroonga and pgroonga scripts
  Dockerfile-postgresql
  scripts/setup/create-db.sql
  scripts/setup/create-pgroonga.sql
  scripts/setup/postgres-create-db
  scripts/setup/postgres-init-db
Labels: area: production installer, priority: blocker, size: M

#12817 css: Use SCSS nesting for `.subscriptions-container`.
  static/styles/night_mode.scss
  static/styles/subscriptions.scss
Labels: size: XL

#12830 provision_inner: Remove unused lsb_release run
  tools/lib/provision_inner.py
Labels: size: XS

#12836 codecov: Change threshold to use % syntax.
  .codecov.yml
Labels: size: XS

#12833 bots: Replace remnants of new-user-bot with default-bot@zulip.com.
  frontend_tests/casper_tests/13-user-deactivation.js
  zerver/tests/test_home.py
  zerver/tests/test_presence.py
  zerver/tests/test_subs.py
  zilencer/management/commands/populate_db.py
  zproject/settings.py
Labels: size: M

#12832 echo: Update topic_links when we get messages back from server.
  frontend_tests/node_tests/echo.js
  static/js/echo.js
Labels: size: XS

#12840 dependencies: Upgrade eslint to 6.0.1
  frontend_tests/node_tests/markdown.js
  package.json
  version.py
  yarn.lock
Labels: size: XL

#12841 emails: Remove unsubscribe link from missed message emails.
  templates/zerver/emails/missed_message.source.html
  templates/zerver/emails/missed_message.txt
  zerver/lib/email_notifications.py
  zerver/tests/test_email_notifications.py
Labels: size: L

#12851 version: Document when a dependency upgrade requires a major bump
  version.py
Labels: size: S

#11450 auth: Migrate google oauth to python-social-auth.
  docs/production/authentication-methods.md
  docs/subsystems/auth.md
  requirements/common.in
  requirements/dev.txt
  requirements/prod.txt
  static/js/portico/signup.js
  static/styles/portico/portico-signin.scss
  templates/zerver/accounts_home.html
  templates/zerver/config_error.html
  templates/zerver/google-error.md
  templates/zerver/login.html
  version.py
  zerver/tests/test_auth_backends.py
  zerver/tests/test_docs.py
  zerver/tests/test_events.py
  zerver/views/auth.py
  zproject/backends.py
  zproject/dev_settings.py
  zproject/prod_settings_template.py
  zproject/settings.py
  zproject/test_settings.py
  zproject/urls.py
Labels: size: XL

#12854 css: Fix weird checkbox scrolling bug in Chrome
  static/styles/components.scss
Labels: size: XS

#12864 settings: Update description for unread count setting.
  static/js/settings.js
Labels: size: XS

#12867 setup_venvs: Use system python3
  tools/setup/setup_venvs.py
Labels: size: S

#12870 email_gateway: Use html2text directly.
  zerver/lib/email_notifications.py
  zerver/webhooks/freshdesk/tests.py
Labels: size: S

#12879 docs: Correct CircleCI job name typo
  docs/testing/continuous-integration.md
Labels: size: XS

#12886 docs: Fix a typo in security documentation.
  templates/zerver/security.md
Labels: size: XS

#12885 compose: Do not trigger topic mention if already completed.
  frontend_tests/node_tests/composebox_typeahead.js
  static/js/composebox_typeahead.js
Labels: size: XS

#12891 lint: Do not forbid ES6 const
  tools/linter_lib/custom_check.py
Labels: size: S

#12892 reactions_button: Remove title from reaction button in controls.
  static/templates/message_controls.hbs
Labels: size: XS

#12873 webhooks: Fix small bug in the fixture_to_headers method of bitbucket3.
  zerver/webhooks/bitbucket3/view.py
Labels: size: XS

#12895 css: Fix .message_top_line stealing mouse events from .message_edit_form
  static/styles/zulip.scss
Labels: size: XS

#12914 nginx: Remove invalid extra headers for OPTIONS /api/v1/events.
  puppet/zulip/files/nginx/zulip-include-frontend/app
Labels: area: api, area: production, size: XS

#12915 Prepopulate stream name in compose box if possible.
  frontend_tests/node_tests/compose_actions.js
  static/js/compose_actions.js
Labels: area: compose, area: onboarding, size: L
