Repository zulip/zulip, pull requests merged in 2020-12, with the labels that each got.

#16690 support: Add ability to change subdomain of realms.
  analytics/tests/test_views.py
  analytics/views.py
  static/styles/portico/activity.css
  templates/analytics/realm_details.html
  templates/analytics/support.html
Labels: size: L

#16664 support: Allow user look up through full name search
  analytics/tests/test_views.py
  analytics/views.py
  templates/analytics/support.html
Labels: size: S

#16739 lightbox: Fix images not opening after navigating through back button.
  static/js/overlays.js
Labels: size: XS

#16926 message: Bundle message stripping, validation, and truncation
  zerver/lib/actions.py
  zerver/lib/email_mirror.py
  zerver/lib/message.py
  zerver/tests/test_drafts.py
  zerver/views/drafts.py
  zerver/views/message_edit.py
Labels: size: M

#16930 vagrant: Add a setting to downgrade VirtualBox Guest Additions
  Vagrantfile
  docs/development/setup-vagrant.md
Labels: size: M

#16786 actions: Refactor check_message to return a dataclass instead of Dict.
  zerver/lib/actions.py
  zerver/lib/message.py
  zerver/lib/onboarding.py
  zerver/lib/widget.py
  zerver/management/commands/deliver_scheduled_messages.py
  zerver/tests/test_message_send.py
Labels: size: XL

#16945 js: Convert Object.assign({…}, …) to spread syntax
  frontend_tests/node_tests/typeahead_helper.js
  static/js/admin.js
  static/js/dropdown_list_widget.js
  static/js/popovers.js
  static/js/portico/integrations.js
  static/js/settings_org.js
  tools/message-screenshot.js
Labels: size: XL

#16952 ui_init: Unnest an if statement
  static/js/ui_init.js
Labels: size: S

#16973 requirements: Delete unused pip2.in symlink
  requirements/pip2.in
Labels: size: XS

#16972 alerts: Prevent icons from spilling out of alerts
  static/styles/alerts.css
Labels: area: production, bug, priority: high, size: M
