Repository zulip/zulip, pull requests merged in 2020-05, with the labels that each got.

#14835 regression: Add minimum height to custom user field textbox.
  static/styles/settings.scss
Labels: size: XS

#14767 streams: Remove deactivated stream from default stream groups.
  zerver/lib/actions.py
  zerver/tests/test_subs.py
Labels: size: M

#14843 casper: Increase default timeout to avoid indeterministic CI failure.
  frontend_tests/casper_tests/00-realm-creation.js
Labels: size: XS

#14796 webhooks/sentry: Rewrite the sentry webhook for the latest SDKs.
  static/images/integrations/sentry/001.png
  static/images/integrations/sentry/002.png
  zerver/webhooks/sentry/doc.md
  zerver/webhooks/sentry/fixtures/event_for_exception_golang.json
  zerver/webhooks/sentry/fixtures/event_for_exception_node.json
  zerver/webhooks/sentry/fixtures/event_for_exception_python.json
  zerver/webhooks/sentry/fixtures/event_for_message_golang.json
  zerver/webhooks/sentry/fixtures/event_for_message_node.json
  zerver/webhooks/sentry/fixtures/event_for_message_python.json
  zerver/webhooks/sentry/fixtures/exception_message.json
  zerver/webhooks/sentry/fixtures/issue_assigned_to_individual.json
  zerver/webhooks/sentry/fixtures/issue_assigned_to_team.json
  zerver/webhooks/sentry/fixtures/issue_created_for_exception.json
  zerver/webhooks/sentry/fixtures/issue_created_for_message.json
  zerver/webhooks/sentry/fixtures/issue_ignored.json
  zerver/webhooks/sentry/fixtures/issue_resolved.json
  zerver/webhooks/sentry/tests.py
  zerver/webhooks/sentry/view.py
Labels: size: XL

#14848 logging: Pass format arguments to unconventionally-named loggers too
  corporate/lib/stripe.py
  corporate/views.py
  zproject/backends.py
Labels: size: M

#14821 Use cacheLoader more consistently in webpack compilation
  tools/webpack.config.ts
Labels: area: left-sidebar, design, priority: high, size: M

#14858 retention: Add a daily cron job.
  puppet/zulip/files/cron.d/archive-messages
  puppet/zulip/manifests/app_frontend_once.pp
Labels: size: S

#14866 typeaheads: Show tip text for silent mentions.
  static/js/composebox_typeahead.js
Labels: size: XS

#14837 populate_db: Add option to specify max no of topics to create.
  zerver/lib/generate_test_data.py
  zilencer/management/commands/populate_db.py
Labels: size: M

#14263 Refactor left-sidebar.scss
  static/styles/left-sidebar.scss
Labels: size: L

#14870 docs: Remove unnecessary double-backticks in indented line
  docs/contributing/code-style.md
Labels: size: XS

#14871 Subscribe every user to every stream.
  zerver/data_import/gitter.py
Labels: size: S

#14867 click_handlers: Remove click handler for closing stream settings.
  static/js/click_handlers.js
  static/js/subs.js
Labels: size: S

#14877 todo widget: Downgrade error to warning.
  static/js/todo_widget.js
Labels: size: XS

#14878 widgets: Style buttons properly in night-mode.
  static/styles/night_mode.scss
Labels: size: XS

#14875 docs: Fix typo in message-retention-policy.md.
  templates/zerver/help/message-retention-policy.md
Labels: size: XS

#14883 typeahead: Avoid tracebacks due to navbar changes.
  static/js/search.js
  static/third/bootstrap-typeahead/typeahead.js
Labels: size: S

#14882 desktop-login: Fix window.open invocation
  static/js/portico/desktop-login.js
Labels: size: S

#14884 check-openapi: Improve error handling
  tools/check-openapi
Labels: size: M

#14886 version: Update for Zulip Desktop v5.2.0
  version.py
  zerver/tests/test_compatibility.py
Labels: size: S

#14893 webhooks/sentry: Add back support for the legacy integrations.
  zerver/webhooks/sentry/fixtures/deprecated_exception_message.json
  zerver/webhooks/sentry/tests.py
  zerver/webhooks/sentry/view.py
Labels: size: XL

#14887 version: Update for Zulip Desktop v5.2.0 (for 2.1.x)
  static/js/portico/landing-page.js
  version.py
  zerver/tests/test_compatibility.py
Labels: size: S

#14902 docs: Fix recent regression with server-settings.
  templates/zerver/api/server-settings.md
Labels: size: XS

#14591 topic: Remove 7 days restriction for editing topics.
  zerver/lib/topic.py
Labels: area: message-editing, priority: blocker, size: S

#14911 invite emails: Ensure user-controlled input is always in links.
  templates/zerver/emails/invitation.source.html
  templates/zerver/emails/invitation_reminder.source.html
  version.py
  zerver/tests/test_signup.py
Labels: size: M

#14920 drafts: Rename open_modal -> open_overlay.
  frontend_tests/node_tests/drafts.js
  static/js/drafts.js
Labels: size: S

#14923 org settings: Fix limited plan realm can change message_retention_days.
  zerver/lib/actions.py
  zerver/tests/test_realm.py
  zerver/views/realm.py
  zerver/views/realm_logo.py
Labels: size: M

#14924 uploads: Add support for ".jpe" file extension.
  puppet/zulip/files/nginx/zulip-include-frontend/uploads.types
  zerver/lib/bugdown/__init__.py
Labels: area: uploads, priority: high, size: XS

#14918 desktop-login: Use zulip design styles for desktop-login.
  static/styles/portico/portico.scss
  templates/zerver/desktop_login.html
  templates/zerver/desktop_redirect.html
Labels: area: authentication, priority: blocker, size: M

#14937 docs: Remove duplicate content from deploying-bots.md.
  templates/zerver/api/deploying-bots.md
Labels: size: S

#14940 ci: add configuration for posting to czo whenever CI fails in master.
  .circleci/config.yml
  zerver/webhooks/circleci/view.py
Labels: size: S

#14945 message-edit: Process user groups for mentioned user ids.
  zerver/lib/actions.py
  zerver/tests/test_bugdown.py
Labels: size: M

#14901 billing: Restrict max licenses to 1000 during upgrade via invoice
  corporate/lib/stripe.py
  corporate/tests/test_stripe.py
  corporate/views.py
Labels: size: M

#14898 portico: Add setting to put Google Analytics on selected portico pages
  package.json
  static/js/bundles/portico.js
  static/js/portico/google-analytics.js
  static/js/portico/help.js
  static/js/portico/integrations.js
  static/js/portico/landing-page.js
  version.py
  yarn.lock
  zerver/decorator.py
  zerver/views/documentation.py
  zerver/views/home.py
  zerver/views/portico.py
  zproject/default_settings.py
  zproject/urls.py
Labels: size: XL

#14949 night-mode: Update CSS for navbar separators.
  static/styles/night_mode.scss
Labels: size: S

#14572 markdown: Set default code block language for quotes and latex as well.
  static/js/composebox_typeahead.js
Labels: size: S

#14956 realm_logo: Fix incorrect display of realm logo delete button.
  static/js/realm_logo.js
Labels: size: XS

#14946 stream_settings: Don't remove stream_row if in "All Streams" tab.
  static/js/subs.js
Labels: size: XS

#14957 api: Remove email field from realm_user and realm_bot events.
  templates/zerver/api/changelog.md
  zerver/lib/actions.py
  zerver/lib/events.py
  zerver/tests/test_events.py
  zerver/tests/test_users.py
Labels: size: L

#14968 ci: Disable casper tests in ci due to flaky behaviour.
  tools/ci/frontend
Labels: size: S

#14970 compose.js: Fix compose box didn't collapse.
  static/js/compose.js
Labels: area: compose, bug, size: XS

#14969 dependencies: Move zulip-js to devDependencies
  package.json
Labels: size: XS

#14976 check-rabbitmq-queue: Log queue size in "queue stuck" alert.
  scripts/lib/check_rabbitmq_queue.py
Labels: size: XS

#14980 ci: Correct notify_failure_status in circleci config.
  .circleci/config.yml
Labels: size: XS

#14981 home: Fix furthest read time when user has multiple clients.
  zerver/tests/test_home.py
  zerver/views/messages.py
Labels: size: S

#14964 mailmap: Add Git .mailmap for zulipchat.com → zulip.com
  .mailmap
Labels: size: S

#14979 presence: Optimize performance of mobile_query.
  zerver/lib/presence.py
  zerver/tests/test_events.py
  zerver/tests/test_home.py
Labels: size: M

#14984 subs.js: Change how to check if the subscribed tab is active.
  static/js/subs.js
Labels: size: S

#14985 puppet: Work around memcached SASL configuration path bug
  puppet/zulip/manifests/memcached.pp
  puppet/zulip/manifests/systemd_daemon_reload.pp
Labels: size: S

#14987 Add .mailmap entry for Brock and Me
  .mailmap
Labels: size: XS

#14988 mailmap: Add mailmap entry for Aman Agrawal.
  .mailmap
Labels: size: XS

#15000 api docs: Update 'deactivate_user' and 'update_user' python examples.
  zerver/openapi/python_examples.py
Labels: size: S

#14998 retention: Pass optional realm argument to move_messages_to_archive.
  zerver/lib/actions.py
  zerver/lib/retention.py
  zerver/tests/test_retention.py
Labels: size: M

#14994 message_events:bugfix: Update edited msgs to be rerentered together.
  static/js/message_events.js
Labels: size: XS

#14978 billing: User FREE_TRIAL_DAYS instead of FREE_TRIAL_MONTHS
  corporate/lib/stripe.py
  corporate/tests/test_stripe.py
  corporate/views.py
  templates/corporate/upgrade.html
  templates/zerver/plans.html
  zerver/views/portico.py
  zproject/default_settings.py
  zproject/dev_settings.py
Labels: size: L

#14992 stream: Allow non admins to set stream post policy when creating streams
  static/js/stream_create.js
  static/templates/stream_types.hbs
  zerver/lib/streams.py
  zerver/tests/test_subs.py
Labels: size: XL

#14986 ui: Change style of divider in setting menu.
  static/styles/zulip.scss
Labels: size: XS

#15009 navbar: Use direct child selector to target spans.
  static/styles/zulip.scss
Labels: area: search, bug, design, priority: high, size: XS

#15016 stripe tests: Set the active users explicitly.
  corporate/tests/test_stripe.py
Labels: size: M

#15018 settings_bots: Do not destroy section when switching to users section.
  static/js/settings_users.js
Labels: size: S

#15022 stripe tests: Add back out-of-realm users.
  corporate/tests/test_stripe.py
Labels: size: S

#15023 Avoid running queries to db in a loop.
  zerver/lib/actions.py
  zerver/lib/cache_helpers.py
  zerver/lib/message.py
  zerver/tests/test_messages.py
Labels: size: XL

#15038 auth: Gracefully handle bad http responses from IdP in social auth.
  zerver/tests/test_auth_backends.py
  zproject/backends.py
Labels: size: S

#15035 droplets: Make sure the username is lowercase
  tools/droplets/create.py
Labels: size: S

#15034 feat(travis): display emoji for `Pending` status
  zerver/webhooks/travis/view.py
Labels: size: XS

#15042 openapi: Add tests for checking presence of various attributes.
  zerver/openapi/zulip.yaml
  zerver/tests/test_openapi.py
Labels: size: S

#15046 settings: Fix settings sidebar list bug.
  static/styles/settings.scss
Labels: size: XS

#15056 queue_processors: Log time spent getting data for url in embed_links.
  zerver/worker/queue_processors.py
Labels: size: XS

#15050 markdown: Disable tex, latex for math rendering.
  static/js/fenced_code.js
  zerver/lib/bugdown/fenced_code.py
  zerver/tests/fixtures/markdown_test_cases.json
Labels: size: S

#14974 GitHub Webhook: Support team/edited and more verbose logging for pull_request events
  zerver/webhooks/github/view.py
Labels: size: XS

#15067 test_reactions: Cache stores reactions data after formatting.
  zerver/tests/test_reactions.py
Labels: size: M

#15031 auth: Log when a user tries to login with deactivated account.
  zerver/tests/test_auth_backends.py
  zproject/backends.py
Labels: size: S

#15089 rate_limit: Restrict tornado backend to explicitly specified domains.
  zerver/lib/rate_limiter.py
  zerver/tests/test_rate_limiter.py
  zproject/settings.py
Labels: size: S

#15048 actions: Merge do_change_is_admin and do_change_is_guest.
  analytics/management/commands/populate_analytics_db.py
  zerver/lib/actions.py
  zerver/lib/server_initialization.py
  zerver/management/commands/knight.py
  zerver/tests/test_audit_log.py
  zerver/tests/test_email_notifications.py
  zerver/tests/test_events.py
  zerver/tests/test_messages.py
  zerver/tests/test_realm_domains.py
  zerver/tests/test_signup.py
  zerver/tests/test_subs.py
  zerver/tests/test_users.py
  zerver/views/users.py
  zilencer/management/commands/populate_db.py
Labels: size: XL

#15053 icons: Switch from text-o to code-o for view source / edit topic.
  docs/documentation/user.md
  static/js/ui_init.js
  static/templates/actions_popover_content.hbs
  templates/zerver/help/edit-or-delete-a-message.md
Labels: size: S

#13075 markdown: Process fenced code blocks in blockquotes.
  zerver/lib/bugdown/__init__.py
  zerver/lib/bugdown/fenced_code.py
  zerver/tests/fixtures/markdown_test_cases.json
Labels: area: markdown, area: message view, size: L

#15096 Clean up search tests
  frontend_tests/node_tests/search_suggestion.js
  frontend_tests/node_tests/search_suggestion_legacy.js
Labels: size: XL

#15094 navbar: Remove redundant .emoji styles from scss.
  static/styles/zulip.scss
Labels: size: XS

#15099 people tests: Move test users to top of file.
  frontend_tests/node_tests/people.js
Labels: size: XL

#15098 message view: Show indicator while fetching new messages.
  frontend_tests/node_tests/message_fetch.js
  static/js/message_fetch.js
  static/js/message_scroll.js
  static/styles/night_mode.scss
  static/styles/zulip.scss
  templates/zerver/app/home.html
Labels: area: message view, bug, priority: high, size: L

#14584 Invitations are removed from the list too soon.
  confirmation/models.py
  zerver/lib/actions.py
  zerver/lib/test_classes.py
  zerver/tests/test_signup.py
  zerver/views/registration.py
Labels: size: L

#15106 casper_tests: Adjust for the addition of Desdemona
  frontend_tests/casper_tests/03-narrow.js
  frontend_tests/casper_tests/05-subscriptions.js
Labels: size: S

#15109 buddy_data test: Move huddle_fraction_present test.
  frontend_tests/node_tests/activity.js
  frontend_tests/node_tests/buddy_data.js
Labels: size: XL

#15061 docs: Inter-link documentation mentioning guests.
  templates/zerver/help/invite-new-users.md
  templates/zerver/help/roles-and-permissions.md
  templates/zerver/help/stream-permissions.md
Labels: size: M

#15119 tests: Use do_change_user_role in lint rules and test docs.
  docs/testing/testing-with-django.md
  tools/linter_lib/custom_check.py
Labels: size: S

#15120 styles: Undo calc(x + y) → calc(x - -y) workaround.
  static/styles/compose.scss
  static/styles/portico/portico.scss
  static/styles/settings.scss
  static/styles/subscriptions.scss
  tools/linter_lib/custom_check.py
Labels: size: S

#15117 portico: Use green btn for `call-to-action-button`.
  static/styles/portico/landing-page.scss
  templates/zerver/hello.html
Labels: area: portico, bug, size: S

#14972 bugfix: Fix codecov broken backend coverage upload.
  .circleci/config.yml
  tools/ci/backend
  tools/test-backend
Labels: area: tooling, bug, priority: high, size: M

#15128 docs: Fix typo in testing-with-node.md.
  docs/testing/testing-with-node.md
Labels: size: XS

#15121 minor: Remove outdated comment.
  static/styles/portico/portico.scss
Labels: size: XS

#15125 auth: Make sure that we enforce max_length during password reset.
  zerver/forms.py
Labels: area: authentication, bug, size: S

#15110 fix(travis): fix display emoji for `Pending` status
  zerver/webhooks/travis/view.py
Labels: size: XS

#15114 models: Comment call to python2-esque `iteritems()`.
  zerver/models.py
Labels: size: XS

#15132 bugdown: Revert NamedTuple declarations to old style
  zerver/lib/bugdown/__init__.py
Labels: size: S

#14230 SCSS Refactoring
  static/styles/portico/portico.scss
Labels: size: XL

#15139 presence: Fix "Last active:" in buddy list when last presence is idle.
  frontend_tests/node_tests/presence.js
  static/js/presence.js
Labels: size: L

#15142 Revert "buddy list: Adjust sizing calc for narrow mode."
  static/js/resize.js
Labels: size: S

#15153 populate_db: Reduce 'boring users' threshold.
  zilencer/management/commands/populate_db.py
Labels: size: XS

#15130 Remove old references to "wiki" or "trac"
  puppet/zulip_ops/files/munin/apache.conf
  puppet/zulip_ops/manifests/apache.pp
  puppet/zulip_ops/templates/nagios_apache_site.conf.template.erb
Labels: size: S
