Repository zulip/zulip, pull requests merged in 2020-10, with the labels that each got.

#16457 message_edit: Reorder buttons to match compose.
  static/styles/zulip.css
  static/templates/message_edit_form.hbs
Labels: area: message-editing

#16501 activity: Show server time rather than browser time
  analytics/views.py
  templates/analytics/realm_summary_table.html
Labels: size: S

#16504 email: Remove unused `log_digest_event` function.
  zerver/lib/email_notifications.py
Labels: size: S

#16507 deliver_scheduled_messages: Don’t do_send_messages inside a transaction
  zerver/management/commands/deliver_scheduled_messages.py
Labels: size: S

#16512 create_user: Strip whitespace from initial password file.
  zerver/management/commands/create_user.py
Labels: area: production, size: XS

#16516 api docs: Fix JavaScript example for /streams api endpoint.
  templates/zerver/api/get-streams.md
Labels: size: XS

#16519 docs: Fix typos in events-system.md
  docs/subsystems/events-system.md
Labels: size: XS

#16520 Refactor bulk_add_subscriptions.
  zerver/lib/actions.py
Labels: size: XL

#16522 puppet: Remove misleading motd.
  puppet/zulip_ops/files/motd.lb0
  puppet/zulip_ops/manifests/loadbalancer.pp
Labels: size: S

#16521 puppet: Drop all log2zulip configuration.
  puppet/zulip_ops/files/cron.d/log2zulip
  puppet/zulip_ops/files/log2zulip.conf
  puppet/zulip_ops/files/log2zulip.zuliprc
  puppet/zulip_ops/manifests/app_frontend.pp
  puppet/zulip_ops/manifests/loadbalancer.pp
Labels: size: M

#16513 nginx: Redirect {www.,}zulipchat.com, www.zulip.com to zulip.com
  puppet/zulip_ops/files/nginx/sites-available/loadbalancer
Labels: size: M

#16531 puppet: Move frontend monitoring into its own file.
  puppet/zulip_ops/manifests/app_frontend.pp
  puppet/zulip_ops/manifests/app_frontend_monitoring.pp
Labels: size: M

#16535 requirements: Install PycURL for Thumbor
  requirements/thumbor-dev.txt
  requirements/thumbor.in
  requirements/thumbor.txt
  version.py
Labels: size: S

#16545 dependencies: Use patched source-map with a performance fix
  package.json
  version.py
  yarn.lock
Labels: size: S

#16546 install-aws-server: Force non-interactive dist-upgrade.
  tools/setup/bootstrap-aws-installer
Labels: size: S

#16549 docs: Fix various typos.
  docs/subsystems/sending-messages.md
  docs/tutorials/new-feature-tutorial.md
Labels: size: S

#16540 upgrade-postgres: Catch failed pg_upgradecluster exit code.
  scripts/setup/upgrade-postgres
Labels: size: XS

#16552 puppet: Switch golang and smokescreen to use /srv.
  puppet/zulip_ops/manifests/smokescreen.pp
Labels: size: S

#16563 navbar: Use location.href instead of location.replace.
  static/js/message_view_header.js
Labels: size: XS

#16566 Don't run test queue with run-dev.py.
  tools/ci/production-verify
  tools/test-queue-worker-reload
  zerver/tests/test_queue_worker.py
  zerver/worker/queue_processors.py
Labels: size: S

#16319 markdown: Fix Youtube and Vimeo preview overriding markdown link titles bug. Fixes #16100
  zerver/lib/markdown/__init__.py
  zerver/tests/test_link_embed.py
Labels: area: markdown, bug, size: M

#16573 docs: Drop an out-of-date paragraph that talks of 2017 in the future.
  docs/production/settings.md
Labels: size: XS

#16575 puppet: Fix included monitoring class name.
  puppet/zulip_ops/manifests/app_frontend.pp
Labels: size: XS

#16578 Fix peer_add/peer_remove events.
  zerver/lib/actions.py
  zerver/lib/stream_subscription.py
  zerver/tests/test_subs.py
Labels: size: XL

#16537 shortcuts : Fixed Keyboard shortcuts in Mozilla Firefox
  static/js/message_view_header.js
Labels: size: XS

#16583 docs: Give examples for ugettext_lazy
  docs/translating/internationalization.md
Labels: size: M

#16584 git-docs: Add links to git-scm docs
  docs/git/terminology.md
Labels: size: S

#16587 compilemessages: Sort language list with Unicode Collation Algorithm
  requirements/common.in
  requirements/dev.txt
  requirements/prod.txt
  version.py
  zerver/management/commands/compilemessages.py
Labels: size: S

#16594 subscriber events: Change schema for peer_add/peer_remove.
  frontend_tests/node_tests/dispatch_subs.js
  frontend_tests/node_tests/lib/events.js
  static/js/server_events_dispatch.js
  zerver/lib/actions.py
  zerver/lib/event_schema.py
  zerver/lib/events.py
  zerver/openapi/zulip.yaml
  zerver/tests/test_subs.py
Labels: size: XL

#16591 favicon: Close race condition in Chrome bug workaround
  static/js/favicon.js
Labels: size: M

#16244 events: Update subscriber list on peer_remove event for unsubscribed and never-subscribed streams.
  zerver/lib/events.py
  zerver/tests/test_events.py
Labels: size: M

#16588 favicon: Slightly increase the font size for short numbers
  static/templates/favicon.svg.hbs
Labels: size: S

#16603 puppet: Switch nagios SSH checks to id_ed25519 key.
  puppet/zulip_ops/files/nagios3/commands.cfg
Labels: size: M

#16602 i18n: Fix get_language_translation_data for zh_TW
  zerver/lib/i18n.py
Labels: area: i18n, size: S

#16606 test_message_fetch: Clean up obsolete PGroonga bug workaround
  zerver/tests/test_message_fetch.py
Labels: size: S

#16610 mypy: Correct mistaken *args type annotations
  zerver/lib/test_helpers.py
  zerver/tests/test_slack_importer.py
Labels: size: XS

#16607 markdown: Remove handler for old bug with incompatible twitter library
  zerver/lib/markdown/__init__.py
Labels: size: S

#16604 puppet: Remove non-working apt::source.
  puppet/zulip_ops/manifests/zmirror.pp
Labels: size: S

#16605 puppet: Allow unattended-upgrades for all but servers.
  docs/production/troubleshooting.md
  puppet/zulip_ops/files/apt/apt.conf.d/50unattended-upgrades
Labels: size: XL

#16621 help: Gitter imports do not use a token to fetch latest data.
  templates/zerver/help/import-from-gitter.md
Labels: size: XS

#16627 dependencies: Upgrade JavaScript dependencies
  .eslintrc.json
  frontend_tests/node_tests/emoji_picker.js
  package.json
  version.py
  yarn.lock
Labels: size: XL

#16622 puppet: Configure logrotate for all logger files.
  puppet/zulip/files/logrotate/zulip
  zproject/computed_settings.py
Labels: size: S

#16624 decorator: Unfork redirect_to_login
  zerver/decorator.py
  zerver/views/portico.py
Labels: size: M

#16625 queue: Be more explicit about test/real queue division.
  scripts/lib/queue_workers.py
  zerver/tests/test_queue_worker.py
  zerver/worker/queue_processors.py
Labels: size: L

#16634 docs: Fix name of realm rename function.
  templates/zerver/help/change-organization-url.md
Labels: size: XS

#16636 openapi: Note that a user's `avatar_url` may be missing.
  zerver/openapi/zulip.yaml
Labels: area: documentation (api and integrations), size: S

#16637 docs: Reword pgroonga sections.
  docs/subsystems/full-text-search.md
Labels: size: L

#16643 provisioning: Support non-RSA SSH keys.
  tools/setup/bootstrap-aws-installer
Labels: size: S

#16644 Sentry timeout grouping, bump timeouts
  zerver/worker/queue_processors.py
Labels: size: S

#16648 install-node: Install npm and npx symlinks; upgrade Node.js to 12.19.0 and Yarn to 1.22.10
  scripts/lib/install-node
  version.py
Labels: size: S

#16652 upgrade: Adjust puppet class names even with --skip-puppet.
  scripts/lib/upgrade-zulip-stage-2
Labels: size: M

#16647 export: Only include real, active humans in the displayed count.
  zerver/management/commands/export.py
  zerver/tests/test_management_commands.py
Labels: size: S

#16656 favicon: Invalidate favicon_state.image without a network request
  static/js/favicon.js
Labels: size: S

#16585 i18n: Translate who reacted tooltip message
  frontend_tests/node_tests/reactions.js
  static/js/reactions.js
Labels: size: XL

#16597 popover: Fixed color-picker popover responsiveness.
  static/js/stream_popover.js
  static/styles/popovers.css
Labels: area: mobile web, bug, size: M
