Repository zulip/zulip, pull requests merged in 2020-09, with the labels that each got.

#16205 fixed horizontal scrolling of table when overflow.
  static/styles/rendered_markdown.scss
Labels: size: XS

#16191 message_list: Live update trailing bookend on stream deactivation.
  frontend_tests/node_tests/dispatch.js
  frontend_tests/node_tests/message_list.js
  static/js/message_list.js
  static/js/server_events_dispatch.js
Labels: bug, size: M

#16260 tests: Use real path when getting commands in TestCommandsCanStart.
  zerver/tests/test_management_commands.py
Labels: size: XS

#16255 settings: Don't use css classes starting with `icon`.
  frontend_tests/node_tests/settings_org.js
  static/js/settings_org.js
  static/styles/settings.scss
  static/templates/settings/settings_save_discard_widget.hbs
Labels: area: settings (admin/org), area: settings UI, bug, priority: blocker, size: M

#16264 webhooks: Clean up args to log_exception_to_webhook_logger.
  zerver/decorator.py
Labels: size: S

#16272 node tests: Avoid unnecessary people mocks.
  frontend_tests/node_tests/composebox_typeahead.js
Labels: size: S

#16274 node tests: Prevent theoretical leak from Intl.
  frontend_tests/node_tests/util.js
Labels: size: S

#16271 landing-page: Fix carousel indicators alignment.
  static/styles/portico/landing-page.scss
Labels: size: XS

#16269 isort: Enable black profile
  .isort.cfg
  zerver/lib/email_validation.py
  zerver/tests/test_retention.py
  zerver/webhooks/gitea/view.py
Labels: size: S

#16268 lint: Remove unused ignorelongline and lint:ignore comments
  templates/zerver/help/bots-and-integrations.md
  tools/setup/emoji/emoji_names.py
  tools/setup/emoji/import_emoji_names_from_csv
  zerver/tests/test_push_notifications.py
Labels: size: S

#16267 test_openapi: Drop Python 3.5 code in get_standardized_argument_type
  zerver/tests/test_openapi.py
Labels: size: M

#16266 python: Remove redundant dest for argparse arguments
  puppet/zulip/files/nagios_plugins/zulip_app_frontend/check_send_receive_time
  scripts/lib/email-mirror-postfix
  scripts/lib/queue_workers.py
  scripts/lib/upgrade-zulip-from-git
  scripts/lib/upgrade-zulip-stage-2
  scripts/lib/zulip_tools.py
  scripts/purge-old-deployments
  scripts/restart-server
  scripts/setup/generate_secrets.py
  tools/check-capitalization
  tools/check-frontend-i18n
  tools/check-issue-labels
  tools/droplets/create.py
  tools/lib/provision.py
  tools/lib/provision_inner.py
  tools/test-api
  tools/test-backend
  tools/test-js-with-node
  tools/test-js-with-puppeteer
  tools/test-tools
  tools/webpack
  zerver/lib/management.py
  zerver/management/commands/add_users_to_mailing_list.py
  zerver/management/commands/add_users_to_streams.py
  zerver/management/commands/check_redis.py
  zerver/management/commands/convert_gitter_data.py
  zerver/management/commands/convert_hipchat_data.py
  zerver/management/commands/convert_slack_data.py
  zerver/management/commands/create_default_stream_groups.py
  zerver/management/commands/create_user.py
  zerver/management/commands/deactivate_user.py
  zerver/management/commands/delete_old_unclaimed_attachments.py
  zerver/management/commands/dump_messages.py
  zerver/management/commands/export.py
  zerver/management/commands/export_usermessage_batch.py
  zerver/management/commands/fill_memcached_caches.py
  zerver/management/commands/fix_unreads.py
  zerver/management/commands/generate_invite_links.py
  zerver/management/commands/generate_multiuse_invite_link.py
  zerver/management/commands/get_migration_status.py
  zerver/management/commands/import.py
  zerver/management/commands/knight.py
  zerver/management/commands/list_realms.py
  zerver/management/commands/process_queue.py
  zerver/management/commands/purge_queue.py
  zerver/management/commands/rate_limit.py
  zerver/management/commands/realm_domain.py
  zerver/management/commands/realm_filters.py
  zerver/management/commands/register_server.py
  zerver/management/commands/remove_users_from_stream.py
  zerver/management/commands/restore_messages.py
  zerver/management/commands/send_custom_email.py
  zerver/management/commands/send_to_email_mirror.py
  zerver/management/commands/send_webhook_fixture_message.py
  zerver/management/commands/set_message_flags.py
  zerver/management/commands/soft_deactivate_users.py
  zerver/management/commands/sync_ldap_user_data.py
  zerver/management/commands/transfer_uploads_to_s3.py
  zilencer/management/commands/calculate_first_visible_message_id.py
  zilencer/management/commands/populate_db.py
Labels: size: XL

#16277 eslint: Enable import/no-cycle.
  .eslintrc.json
Labels: size: XS

#16279 Upgrade JavaScript dependencies
  .github/workflows/codeql-analysis.yml
  package.json
  stylelint.config.js
  version.py
  yarn.lock
Labels: size: XL

#16280 populate_analytics_db: Replace intermediate list with generator.
  analytics/management/commands/populate_analytics_db.py
Labels: size: XS

#16282 puppet: Don’t install netcat
  puppet/zulip/manifests/base.pp
  tools/ci/Dockerfile.template
  tools/lib/provision.py
  tools/test-install/prepare-base
Labels: size: S

#16283 update-zuliprc-api-field: Add missing shell quoting
  tools/update-zuliprc-api-field
Labels: size: XS

#16281 tools: Delete tagmessages script
  tools/i18n/tagmessages
  tools/linter_lib/custom_check.py
Labels: size: M

#16291 circleci: Replace process substitution with pipe to close a race
  .circleci/config.yml
Labels: size: XS

#16294 setup_venv: Add missing comma in COMMON_YUM_VENV_DEPENDENCIES
  scripts/lib/setup_venv.py
Labels: size: XS

#16289 onboarding: Move send_welcome_bot_response to onboarding
  zerver/lib/actions.py
  zerver/lib/onboarding.py
Labels: size: M

#16293 python: Convert subprocess.Popen.communicate to run or check_output
  puppet/zulip/files/postgresql/pg_backup_and_purge
  tools/lib/pretty_print.py
  zerver/lib/test_fixtures.py
  zerver/lib/tex.py
Labels: size: M

#16298 tooltip: Fix arrow position.
  static/third/bootstrap-tooltip/tooltip.css
Labels: size: XS

#16039 docs: Add alt text to images
  templates/zerver/api/incoming-webhooks-walkthrough.md
  templates/zerver/help/about-streams-and-topics.md
  templates/zerver/help/format-your-message-using-markdown.md
  templates/zerver/help/saml-authentication.md
  templates/zerver/integrations/asana.md
  templates/zerver/integrations/capistrano.md
  templates/zerver/integrations/codebase.md
  templates/zerver/integrations/discourse.md
  templates/zerver/integrations/errbot.md
  templates/zerver/integrations/git.md
  templates/zerver/integrations/google-calendar.md
  templates/zerver/integrations/hubot.md
  templates/zerver/integrations/irc.md
  templates/zerver/integrations/jenkins.md
  templates/zerver/integrations/jira-plugin.md
  templates/zerver/integrations/mercurial.md
  templates/zerver/integrations/nagios.md
  templates/zerver/integrations/openshift.md
  templates/zerver/integrations/perforce.md
  templates/zerver/integrations/redmine.md
  templates/zerver/integrations/rss.md
  templates/zerver/integrations/svn.md
  templates/zerver/integrations/trac.md
  templates/zerver/integrations/trello-plugin.md
  templates/zerver/integrations/twitter.md
Labels: accessibility, size: XL

#16312 puppeteer: Fix admin test flakes
  frontend_tests/puppeteer_tests/08-admin.js
Labels: size: S

#16309 Reactions_tooltip : Improved responsiveness of reaction tooltip .
  static/js/click_handlers.js
Labels: size: XS

#16302 python: Use standard secrets module to generate random tokens
  confirmation/models.py
  corporate/lib/stripe.py
  scripts/setup/generate_secrets.py
  tools/semgrep.yml
  zerver/data_import/slack.py
  zerver/lib/cache.py
  zerver/lib/email_mirror.py
  zerver/lib/import_realm.py
  zerver/lib/redis_utils.py
  zerver/lib/upload.py
  zerver/lib/utils.py
  zerver/migrations/0260_missed_message_addresses_from_redis_to_db.py
  zerver/models.py
  zerver/tests/test_auth_backends.py
  zerver/tests/test_create_video_call.py
  zerver/tests/test_rate_limiter.py
  zerver/tests/test_redis_utils.py
  zerver/views/auth.py
  zerver/views/home.py
  zerver/views/video_calls.py
Labels: size: XL

#16327 removed typo (two to one dot)
  docs/git/cloning.md
Labels: size: XS

#16316 docs: Add community_topic_editing_limit_seconds value to docs.
  templates/zerver/api/changelog.md
Labels: area: documentation (api and integrations), size: XS

#16247 Perp commits to logged out view.
  zerver/tests/test_decorators.py
  zerver/tests/test_report.py
  zerver/views/report.py
  zproject/urls.py
Labels: size: L

#16329 puppet: Restrict postfix incoming addresses to postmaster and zulip.
  puppet/zulip/files/postfix/access
  puppet/zulip/files/postfix/virtual
  puppet/zulip/manifests/postfix_localmail.pp
  puppet/zulip/templates/postfix/main.cf.erb
Labels: size: M

#16339 front end --> frontend
  docs/tutorials/new-feature-tutorial.md
Labels: size: S

#16337 Added PyCharm to the list of editors
  docs/development/remote.md
Labels: size: XS

#16331 edit_content : Added hide event for clipboard tooltip .
  static/js/click_handlers.js
Labels: size: XS

#16344 migrations: Add case-insensitive unique index on realm and stream name.
  zerver/migrations/0302_case_insensitive_stream_name_index.py
  zerver/models.py
Labels: size: S

#16341 frontend_tests: Fix typo in node_tests/general.js
  frontend_tests/node_tests/general.js
Labels: size: XS

#16350 requirements: Remove django-cookies-samesite
  requirements/common.in
  requirements/dev.txt
  requirements/prod.txt
  version.py
  zproject/computed_settings.py
Labels: size: S

#16352 nagios: Remove an unnecessary path.append.
  scripts/nagios/check-rabbitmq-consumers
Labels: size: XS

#16351 lint: Use prettier --loglevel=warn for quiet output
  tools/lint
Labels: size: S

#16354 puppet: Coerce uwsgi_listen_backlog_limit into an int before doing math.
  puppet/zulip/manifests/app_frontend_base.pp
Labels: size: XS

#16355 [3.x] requirements: Remove django-cookies-samesite
  requirements/common.in
  requirements/dev.txt
  requirements/prod.txt
  version.py
  zproject/computed_settings.py
Labels: size: S

#16357 [3.x] provision: Fix missing <sasl/sasl.h> headers during provision
  scripts/lib/setup_venv.py
Labels: size: XS

#16360 release: Update release process.
  docs/subsystems/release-checklist.md
Labels: size: L

#16362 landing-page: Don't transition all li elements.
  static/styles/portico/landing-page.css
Labels: size: XS

#16366 zulip-icons: Set writeFiles to false
  static/assets/icons/zulip-icons.font.js
Labels: size: XS

#16364 release-checklist: Restore and clarify -dev version/tag for master
  docs/subsystems/release-checklist.md
Labels: size: S

#16369 auth: Remove redundant call to pad_method_dict().
  zproject/backends.py
Labels: size: XS

#16371 tornado: Retry POST requests from Django to Tornado.
  zerver/tornado/django_api.py
Labels: size: XS

#16372 docs: Mention pulling release notes back over.
  docs/subsystems/release-checklist.md
Labels: size: XS

#16374 circleci: Put the branch name into the topic on failure.
  .circleci/config.yml
Labels: size: XS

#16378 css: Don't use `Monaco` font for <code>.
  static/styles/zulip.css
Labels: size: XS

#16375 Add `/settings` slash command to typeahead.
  frontend_tests/node_tests/composebox_typeahead.js
  static/js/composebox_typeahead.js
Labels: size: S

#16379 sentry: Provide more metadata in queue processors.
  zerver/management/commands/process_queue.py
  zerver/worker/queue_processors.py
Labels: size: M

#16385 certbot: Explicitly apt-get update before installing certbot.
  scripts/setup/setup-certbot
Labels: size: XS

#16353 tornado: Move default port to 9800; remove explicit tornado_processes setting
  zerver/tornado/django_api.py
  zerver/tornado/sharding.py
  zilencer/management/commands/populate_db.py
  zproject/computed_settings.py
  zproject/default_settings.py
  zproject/dev_settings.py
  zproject/test_extra_settings.py
Labels: size: M

#16387 linkifiers: Allow tildes in target URLs.
  zerver/models.py
  zerver/tests/test_realm_filters.py
Labels: size: XS

#16392 RealmFilterPattern: Mark converted content as AtomicString.
  zerver/lib/markdown/__init__.py
  zerver/tests/test_markdown.py
Labels: size: M

#16398 js: Use destructuring for require statements
  frontend_tests/node_tests/compose.js
  frontend_tests/node_tests/fold_dict.js
  frontend_tests/node_tests/lazy_set.js
  frontend_tests/node_tests/message_list.js
  frontend_tests/node_tests/stream_edit.js
  frontend_tests/node_tests/typeahead_helper.js
  frontend_tests/node_tests/unread.js
  frontend_tests/puppeteer_lib/common.js
  frontend_tests/puppeteer_tests/00-realm-creation.js
  frontend_tests/puppeteer_tests/01-login.js
  frontend_tests/puppeteer_tests/02-message-basics.js
  frontend_tests/puppeteer_tests/03-compose.js
  frontend_tests/puppeteer_tests/04-subscriptions.js
  frontend_tests/puppeteer_tests/05-stars.js
  frontend_tests/puppeteer_tests/07-navigation.js
  frontend_tests/puppeteer_tests/08-admin.js
  frontend_tests/puppeteer_tests/09-mention.js
  frontend_tests/puppeteer_tests/10-custom-profile.js
  frontend_tests/puppeteer_tests/11-user-deactivation.js
  frontend_tests/puppeteer_tests/12-drafts.js
  frontend_tests/puppeteer_tests/14-copy-and-paste.js
  frontend_tests/puppeteer_tests/15-realm-linkifier.js
  frontend_tests/puppeteer_tests/16-settings.js
  frontend_tests/zjsunit/index.js
  frontend_tests/zjsunit/stub.js
  static/js/muting.js
  static/js/recent_senders.js
  static/js/settings_profile_fields.js
  static/js/stream_data.js
  static/js/stream_topic_history.js
  static/js/ui.js
  static/js/unread.js
  static/js/user_groups.js
Labels: size: L

#16400 emoji_picker: Fix search input length.
  static/styles/reactions.css
  static/templates/emoji_popover_content.hbs
Labels: area: emoji, bug, size: XS

#16404 tests: Rename stream messages tests in test_message_send.py.
  zerver/tests/test_message_send.py
Labels: size: XS

#16417 puppet: Permit outgoing mail from postfix.
  puppet/zulip/templates/postfix/main.cf.erb
Labels: size: XS

#15423 auth: Render config error page on configuration error
  templates/zerver/config_error.html
  zerver/tests/test_auth_backends.py
  zerver/tests/test_urls.py
  zerver/views/auth.py
  zproject/backends.py
  zproject/dev_urls.py
  zproject/urls.py
Labels: size: XL

#16421 puppeteer_tests: Migrate deprecated waitFor call to waitForFunction
  frontend_tests/puppeteer_lib/common.js
Labels: size: XS

#16424 puppeteer: Fix typing issue in settings test.
  frontend_tests/puppeteer_tests/16-settings.js
Labels: size: XS

#16418 browserslist: Drop 0.2% usage threshold to 0.15%
  .browserslistrc
Labels: size: XS

#16428 invite: Fix text of submit-invitation button on completion.
  static/js/invite.js
Labels: size: S
