Repository zulip/zulip, pull requests merged in 2020-08, with the labels that each got.

#16003 timestamp: Remove datetime_to_precise_timestamp for datetime.timestamp
  zerver/lib/timestamp.py
  zerver/models.py
  zerver/tests/test_timestamp.py
Labels: size: S

#16010 find_account: Fix the email search query.
  zerver/tests/test_signup.py
  zerver/views/registration.py
Labels: size: S

#16006 settings_panel_menu: Remove leftover angry debugging assertions.
  static/js/settings_panel_menu.js
Labels: size: S

#16016 github-actions: Fix incorrect hash key in production install job.
  .github/workflows/production-suite.yml
  tools/ci/production-build
Labels: size: XS

#16001 Support nginx_listen_port with http_only
  puppet/zulip/manifests/app_frontend.pp
  puppet/zulip/templates/nginx/zulip-enterprise.template.erb
Labels: size: S

#16025 dev_settings: Add EMAIL_PORT setting in zproject/dev_settings.py.
  docs/subsystems/email.md
  zproject/dev_settings.py
  zproject/email_backends.py
Labels: size: S

#16014 github-actions: Cancel previous runs on pushes to forks and PRs.
  .github/workflows/cancel-previous-runs.yml
Labels: size: M

#15853 Refactor landing-page.scss
  static/styles/portico/landing-page.scss
Labels: size: XL

#16042 auth: Treat emails case-insensitively in ExternalAuthResult.
  zerver/tests/test_auth_backends.py
  zproject/backends.py
Labels: size: S

#16027 stream_edit: Send values of changed settings only to backend.
  static/js/stream_edit.js
Labels: area: stream settings, bug, size: L

#16045 lint: Migrate all custom CSS rules to stylelint.
  stylelint.config.js
  tools/linter_lib/custom_check.py
Labels: size: M

#16059 streams: Send PATCH request for stream name and description only when it is actually changed.
  static/js/stream_edit.js
Labels: size: S

#14925 memcached: Switch from pylibmc to python-binary-memcached
  docs/development/setup-advanced.md
  puppet/zulip/manifests/app_frontend_base.pp
  requirements/common.in
  requirements/dev.txt
  requirements/prod.txt
  scripts/lib/setup-yum-repo
  scripts/lib/setup_venv.py
  scripts/setup/flush-memcached
  tools/ci/Dockerfile.template
  tools/test-install/prepare-base
  version.py
  zilencer/management/commands/populate_db.py
  zproject/computed_settings.py
Labels: size: XL

#16060 js: Use unminified KaTeX (and minifiy it with everything else).
  frontend_tests/node_tests/markdown_katex.js
  static/js/markdown.js
  static/shared/js/fenced_code.js
  tools/webpack.assets.json
Labels: size: S

#16069 setup_venv: Install libyaml-dev
  scripts/lib/setup_venv.py
Labels: size: XS

#16085 loading_indicator_spinner: Add aria-hidden="true" attribute.
  static/js/loading.js
Labels: size: XS

#16070 sentry: Ignore SystemExit exceptions.
  zproject/sentry.py
Labels: size: S

#16067 realm_audit_log: Fix malformed RealmAuditLog entries.
  zerver/lib/actions.py
  zerver/migrations/0298_fix_realmauditlog_format.py
  zerver/tests/test_audit_log.py
  zerver/tests/test_events.py
Labels: bug, priority: high, size: XL

#16093 puppetter: Replace 'visible: false' with 'hidden: true'.
  frontend_tests/puppeteer_tests/03-compose.js
  frontend_tests/puppeteer_tests/16-settings.js
Labels: size: S

#16092 docs: Change Zoom app type to user-managed
  docs/production/zoom-configuration.md
Labels: size: M

#16096 logging: Report stack_info on logging.exception calls.
  corporate/views.py
  zerver/data_import/import_util.py
  zerver/decorator.py
  zerver/lib/actions.py
  zerver/lib/markdown/__init__.py
  zerver/lib/outgoing_webhook.py
  zerver/management/commands/runtornado.py
  zerver/tests/test_decorators.py
  zerver/tests/test_message_send.py
  zerver/tests/test_queue_worker.py
  zerver/tests/test_zephyr.py
  zerver/tornado/event_queue.py
  zerver/tornado/handlers.py
  zerver/views/zephyr.py
  zerver/worker/queue_processors.py
Labels: size: L

#16103 sanity_check: Test for the virtualenv by its path
  tools/lib/sanity_check.py
Labels: size: S

#16108 zulip.yaml: Don’t redundantly escape slashes
  zerver/openapi/zulip.yaml
Labels: size: M

#16115 links: Flatten the set into a list before serializing into the queue.
  zerver/lib/actions.py
  zerver/views/message_edit.py
Labels: size: XS

#16112 sentry: Provide ZULIP_VERSION as "release".
  zproject/sentry.py
Labels: size: XS

#16120 python: Catch JSONDecodeError instead of ValueError when decoding JSON
  tools/generate-integration-docs-screenshot
  zerver/decorator.py
  zerver/lib/outgoing_webhook.py
  zerver/lib/request.py
  zerver/lib/test_classes.py
  zerver/management/commands/send_webhook_fixture_message.py
  zerver/tornado/event_queue.py
  zerver/views/development/integrations.py
  zerver/webhooks/librato/view.py
  zerver/webhooks/slack_incoming/view.py
Labels: size: S

#16020 docs: Don't suggest --audit-fts-indexes for non-3.0 upgrades.
  docs/production/upgrade-or-modify.md
Labels: size: L

#16123 lightbox_canvas: Remove movementX, movementY polyfill.
  static/js/lightbox_canvas.js
Labels: size: S

#16111 sentry: Ignore all SuspiciousOperation loggers.
  zerver/middleware.py
  zproject/sentry.py
Labels: size: S

#16130 puppeteer: Migrate custom profile test from casper.
  frontend_tests/casper_tests/12-custom-profile.js
  frontend_tests/puppeteer_tests/10-custom-profile.js
Labels: size: XL

#16136 stream_creation_form: Remove `optional` from stream description input.
  static/templates/stream_creation_form.hbs
Labels: size: XS

#16137 queue: Remove a no-longer-correct comment.
  zerver/lib/queue.py
Labels: size: XS

#16098 Fix dev setup and add support for macOS 10.15.6
  Vagrantfile
  docs/development/setup-vagrant.md
  tools/webpack
Labels: size: S

#16150 openapi: Add enum for stream role.
  zerver/openapi/zulip.yaml
Labels: size: XS

#16151 node tests: Add has_zoom_token to event.fixtures.
  frontend_tests/node_tests/compose.js
  frontend_tests/node_tests/lib/events.js
Labels: size: S

#16159 Tweak node tests.
  frontend_tests/node_tests/lib/events.js
Labels: size: L

#16157 tests: Add an explicit order_by to prevent flakes.
  zerver/tests/test_transfer.py
Labels: size: XS

#16155 docs: Capitalize proper noun.
  templates/zerver/security.md
Labels: area: documentation (user), size: XS

#16148 docs: Update API-doc-writing docs to use @openapi_test_function.
  docs/documentation/api.md
Labels: size: M

#16153 markdown: Cache Twitter 403 responses that are semi-permanent.
  zerver/lib/markdown/__init__.py
Labels: size: S

#16156 url_preview: Only extract img tags with an `src`.
  zerver/lib/url_preview/parsers/generic.py
  zerver/tests/test_link_embed.py
Labels: size: XS

#16161 minor node stuff
  frontend_tests/node_tests/lib/events.js
Labels: size: XS

#16167 docs: Fix typo in change-organization-url.md
  templates/zerver/help/change-organization-url.md
Labels: size: XS

#16170 create-db.sql: Ensure using en_US.UTF-8 encoding
  scripts/setup/create-db.sql
Labels: size: S

#16169 settings: Adjust documentation and comment references to settings.py.
  docs/contributing/code-style.md
  docs/production/authentication-methods.md
  docs/production/postgres.md
  docs/subsystems/html-css.md
  docs/subsystems/settings.md
  zerver/lib/logging_util.py
  zerver/management/commands/deliver_scheduled_messages.py
Labels: size: M

#16187 requirements: Upgrade zulint.
  requirements/dev.in
  requirements/dev.txt
  version.py
Labels: size: S

#16171 openapi: Fix DELETE /users/me status 200 response description.
  zerver/openapi/zulip.yaml
Labels: area: documentation (api and integrations), size: XS

#16195 navbar_alerts: Fix close button position.
  static/styles/zulip.scss
Labels: size: XS

#16204 i18n: Tag string in "move_topic_to_stream.hbs" for translation.
  static/templates/move_topic_to_stream.hbs
Labels: size: XS

#16192 queue: Use locking to avoid race conditions in missedmessage_emails.
  zerver/tests/test_queue_worker.py
  zerver/worker/queue_processors.py
Labels: size: L

#16213 rate_limit: Handle the case of request.user being a RemoteZulipServer.
  zerver/decorator.py
  zerver/tests/test_decorators.py
Labels: size: M

#16212 i18n: Fix translation bug in stream creation page.
  static/templates/stream_types.hbs
Labels: size: XS

#16226 actions: Invalid flag operation is a user error.
  zerver/lib/actions.py
  zerver/tests/test_message_flags.py
Labels: size: S

#16229 lint: Catch mock asserts whose leading "assert_" is missing.
  tools/linter_lib/custom_check.py
  zerver/tests/test_docs.py
  zerver/tests/test_management_commands.py
Labels: size: S

#16223 sentry: Ignore SuspiciousOperation exceptions themselves.
  zproject/sentry.py
Labels: size: XS

#16241 compose: Restore Tab+Enter sending in Safari.
  static/js/composebox_typeahead.js
Labels: area: compose, bug, size: M

#16242 hotspots: Use ugettext_lazy for i18n.
  zerver/lib/hotspots.py
Labels: area: i18n, bug, size: S

#16249 sentry: When there are multiple stacktraces, take the most recent.
  zerver/webhooks/sentry/view.py
Labels: size: XS

#16250 trello: Simplify logic for ignored card actions.
  zerver/webhooks/trello/view/__init__.py
Labels: size: S

#16128 message_actions: Help user identify quote can be used for forwarding.
  frontend_tests/node_tests/i18n.js
  static/templates/actions_popover_content.hbs
Labels: size: XS

#16251 models: Add comment for Big Blue Button ID placeholder.
  zerver/models.py
Labels: size: XS

#16177 ui: Add loading indicator for message edits.
  static/js/message_edit.js
  static/js/stream_popover.js
  static/styles/zulip.scss
  static/templates/move_topic_to_stream.hbs
Labels: area: message-editing, bug, priority: high, size: M
