Repository zulip/zulip, pull requests merged in 2020-11, with the labels that each got.

#16673 create_stream: Remove no longer required condition.
  static/js/stream_create.js
Labels: size: S

#16470 api_docs: Document the /fetch-api-key endpoint.
  templates/zerver/api/dev-fetch-api-key.md
  templates/zerver/api/fetch-api-key.md
  templates/zerver/help/include/rest-endpoints.md
  zerver/openapi/curl_param_value_generators.py
  zerver/openapi/markdown_extension.py
  zerver/openapi/zulip.yaml
Labels: size: L

#16689 dev_requirements: Upgrade zulint.
  requirements/dev.in
  requirements/dev.txt
  version.py
Labels: size: S

#16613 navbar: clean up :not() selectors
  static/styles/zulip.css
Labels: size: S

#16709 markdown: Remove border colour on inline code links
  static/styles/rendered_markdown.css
Labels: size: XS

#16699 openapi: Fix escaping in curl command generation
  zerver/openapi/curl_param_value_generators.py
  zerver/openapi/markdown_extension.py
  zerver/tests/test_openapi.py
Labels: size: L

#16707 Clean up digest emails.
  zerver/lib/digest.py
  zerver/tests/test_digest.py
Labels: size: L

#16715 billing: Use name selector for overriding the spin button for licenses
  static/styles/portico/billing.css
Labels: size: S

#16717 email digests: Clean up digest code.
  zerver/lib/digest.py
Labels: size: XL

#16727 widgetize: Don't warn for deleted tictactoe widget.
  frontend_tests/node_tests/widgetize.js
  static/js/widgetize.js
Labels: size: S

#14847 actions: Implement do_delete_user.
  zerver/lib/actions.py
  zerver/lib/create_user.py
  zerver/tests/test_users.py
Labels: size: XL

#16611 webhooks/sentry: Support integration configured as webhook.
  zerver/webhooks/sentry/doc.md
  zerver/webhooks/sentry/fixtures/webhook_event_for_exception_python.json
  zerver/webhooks/sentry/tests.py
  zerver/webhooks/sentry/view.py
Labels: size: XL

#16729 python: Convert os.open(…, O_EXCL) to open(…, "x")
  zerver/lib/cache.py
  zerver/management/commands/export.py
Labels: size: S

#16720 docs: Added number of selected participants in gsoc 2020
  CONTRIBUTING.md
Labels: size: XS

#16719 wsl_dev_setup: Warn user about cloning inside windows mounted disk.
  docs/development/setup-advanced.md
Labels: size: S

#16744 puppet: Log the "Host" header and total response time.
  puppet/zulip/templates/nginx.conf.template.erb
Labels: size: XS

#16733 auth: Handle the case of invalid subdomain at /fetch_api_key endpoint.
  zerver/tests/test_auth_backends.py
  zerver/views/auth.py
Labels: size: S

#16742 puppet: Allow unattended upgrades of -updates in addition to -security
  puppet/zulip_ops/files/apt/apt.conf.d/50unattended-upgrades
Labels: size: XS

#16731 added data-placement to settings icon in left-sidebar to fix flickering bug
  templates/zerver/app/left_sidebar.html
Labels: area: general UI, area: left-sidebar, size: XS

#16743 [WIP] webhooks: Update NewRelic webhook for new format
  zerver/webhooks/newrelic/fixtures/alert.txt
  zerver/webhooks/newrelic/fixtures/deployment.txt
  zerver/webhooks/newrelic/fixtures/incident_acknowledged.json
  zerver/webhooks/newrelic/fixtures/incident_closed.json
  zerver/webhooks/newrelic/fixtures/incident_default_fields.json
  zerver/webhooks/newrelic/fixtures/incident_malformatted_time.json
  zerver/webhooks/newrelic/fixtures/incident_missing_current_state.json
  zerver/webhooks/newrelic/fixtures/incident_missing_duration.json
  zerver/webhooks/newrelic/fixtures/incident_missing_timestamp.json
  zerver/webhooks/newrelic/fixtures/incident_opened.json
  zerver/webhooks/newrelic/fixtures/incident_state_not_recognized.json
  zerver/webhooks/newrelic/fixtures/incident_time_too_large.json
  zerver/webhooks/newrelic/tests.py
  zerver/webhooks/newrelic/view.py
Labels: area: integrations, bug, priority: high, size: XL
