Repository zulip/zulip, pull requests merged in 2020-04, with the labels that each got.

#14429 version: Move minimum desktop version configuration to version.py.
  version.py
  zerver/tests/test_compatibility.py
  zerver/views/compatibility.py
Labels: size: M

#14430 validation: Use JsonableError for extractors.
  zerver/lib/actions.py
  zerver/tests/test_messages.py
Labels: size: M

#14442 import: Make sure the internal realm is created before import.
  zerver/lib/import_realm.py
Labels: size: XS

#14366 Link fix
  static/styles/zulip.scss
  static/templates/recipient_row.hbs
Labels: size: S

#14461 message_list: Hide topic edit pencil icon in the edit mode.
  static/js/click_handlers.js
  static/js/message_edit.js
  static/js/message_list.js
Labels: size: S

#14480 night mode: Fix how "x" is displayed on "You have nothing to send!"
  static/styles/night_mode.scss
Labels: size: XS

#14474 left sidebar: Fix exceptions when updating sub data.
  static/js/stream_edit.js
Labels: size: S

#14485 Portico sign in
  static/styles/portico/portico-signin.scss
Labels: size: S

#14494 drafts: Avoid accidental draft deletions.
  static/js/drafts.js
Labels: size: M

#14495 tests: Fix test in test_subs.py.
  zerver/tests/test_subs.py
Labels: size: M

#14189 Add `zcommand` for toggling fluid width mode.
  static/js/composebox_typeahead.js
  static/js/zcommand.js
  zerver/lib/zcommand.py
  zerver/tests/test_zcommand.py
Labels: size: XL

#14496 drafts: Fade the "Draft saved" a little more slowly.
  static/js/drafts.js
Labels: size: XS

#14182 Fix list item indexing in race condition
  static/js/todo_widget.js
  static/templates/widgets/todo_widget_tasks.hbs
Labels: size: S

#14513 Showell todo2
  static/js/todo_widget.js
Labels: size: L

#14525 upload: Set the value of file input element to empty after upload.
  frontend_tests/node_tests/upload.js
  static/js/upload.js
Labels: size: XS

#14520 tornado: Reuse retry_event functions for failures in tornado queues.
  zerver/management/commands/runtornado.py
  zerver/tornado/event_queue.py
Labels: size: S

#14526 linkifiers: Allow non-admins to filter linkifiers in settings.
  static/js/settings_linkifiers.js
Labels: size: XS

#14501 settings: Add option to disable video call in org settings.
  frontend_tests/node_tests/compose.js
  frontend_tests/node_tests/dispatch.js
  frontend_tests/node_tests/ui_init.js
  static/js/compose.js
  static/js/message_edit.js
  static/js/server_events_dispatch.js
  static/js/settings_org.js
  static/templates/message_edit_form.hbs
  templates/zerver/app/compose.html
  zerver/models.py
  zerver/tests/test_realm.py
Labels: area: compose, priority: high, size: XL

#14529 design: Make non-editable text-box more distinguishable.
  static/js/message_edit.js
Labels: size: XS

#14530 static: Serve webpack bundles from the root domain
  puppet/zulip/files/nginx/zulip-include-frontend/app
  static/html/5xx.html
  static/js/page_params.js
  templates/zerver/base.html
  tools/webpack.config.ts
  zerver/tests/test_docs.py
  zerver/tests/test_home.py
  zproject/dev_urls.py
  zproject/jinja2/__init__.py
  zproject/settings.py
  zproject/test_settings.py
Labels: size: L

#14537 casper: Extract 17-realm-linkifier.
  frontend_tests/casper_tests/10-admin.js
  frontend_tests/casper_tests/17-realm-linkifier.js
Labels: size: XL

#14543 run-dev: Automatically set EXTERNAL_HOST for droplet dev servers
  tools/run-dev.py
Labels: size: XS

#14547 node test stuff
  tools/test-js-with-node
Labels: size: M

#14548 url_preview: Discard url in oembed if server returns invalid json.
  zerver/lib/url_preview/oembed.py
  zerver/tests/test_link_embed.py
Labels: size: S

#14546 unreads: Fix mention/message-edit glitch.
  frontend_tests/node_tests/message_events.js
  frontend_tests/node_tests/unread.js
  static/js/message_events.js
  static/js/unread.js
Labels: size: XL

#14554 docs: Fix broken link to WSL 2 doc.
  docs/development/setup-vagrant.md
Labels: size: XS

#14550 messages: Fix 500 on queries with empty string as search operand.
  zerver/tests/test_narrow.py
  zerver/views/messages.py
Labels: area: search, bug, priority: high, size: S

#14556 thumbor: Fix __file__ typo.
  zerver/lib/thumbnail.py
  zthumbor/loaders/helpers.py
Labels: size: XS

#14512 emoji_name: Raise correct exception if emoji_name is missing.
  zerver/lib/emoji.py
  zerver/tests/test_realm_emoji.py
Labels: size: S

#14477 static/js: Fix custom numeric emojis not working in reactions.
  static/js/emoji_picker.js
Labels: size: S

#14562 Revert "list_render: Clean up initialization."
  frontend_tests/node_tests/list_render.js
  static/js/attachments_ui.js
  static/js/list_render.js
  static/js/settings_emoji.js
  static/js/settings_exports.js
  static/js/settings_invites.js
  static/js/settings_linkifiers.js
  static/js/settings_notifications.js
  static/js/settings_org.js
  static/js/settings_streams.js
  static/js/settings_users.js
  static/js/stream_edit.js
Labels: size: XL

#14576 webhook/semaphore: Add only summary line to the notification message.
  zerver/webhooks/semaphore/fixtures/deploy.json
  zerver/webhooks/semaphore/fixtures/push.json
  zerver/webhooks/semaphore/view.py
Labels: size: S

#14091 [WIP] rate_limiter: Optimize performance for get_events queries.
  tools/coveragerc
  tools/test-backend
  zerver/lib/rate_limiter.py
  zerver/tests/test_rate_limiter.py
Labels: has conflicts, size: XL

#14587 Refactor zulip.yaml
  zerver/openapi/zulip.yaml
Labels: size: XL

#14466 settings UI: Make the settings avatar delete/edit UI slicker.
  static/images/tail-spin.svg
  static/js/avatar.js
  static/js/settings_account.js
  static/styles/settings.scss
  static/templates/settings/account_settings.hbs
Labels: area: settings UI, priority: high, size: XL

#14560 upgrade-zulip: Remove tsearch-extras on upgrade.
  scripts/lib/upgrade-zulip-stage-2
Labels: area: production, bug, priority: high, size: S

#14564 default streams: Change add api to use stream_id.
  static/js/settings_streams.js
  zerver/tests/test_subs.py
  zerver/views/streams.py
Labels: size: S

#13910 Translate from_name in account security emails
  zerver/lib/actions.py
  zerver/lib/send_email.py
Labels: size: S

#14577 Improvments to file upload
  frontend_tests/node_tests/upload.js
  static/js/upload.js
Labels: size: XL

#14607 design: Use CSS instead of disabled property for non-editable text.
  static/js/message_edit.js
  static/styles/night_mode.scss
Labels: size: S

#14605 upgrade: Set the default billing period to monthly
  frontend_tests/node_tests/billing_helpers.js
  frontend_tests/node_tests/upgrade.js
  templates/corporate/upgrade.html
Labels: size: S

#14610 alert words: Limit alert word length to 100.
  zerver/views/alert_words.py
Labels: size: XS

#14563 settings: Fix hovering bug in "Uploaded files" settings.
  static/styles/settings.scss
Labels: area: settings UI, area: uploads, bug, size: XS

#14613 Allow /etc/zulip to be a symlink
  puppet/zulip/manifests/base.pp
Labels: size: XS

#14614 openapi: Fix minor error in zulip.yaml
  zerver/openapi/zulip.yaml
Labels: size: XS

#14616 tab_bar: Fix colors stream_count and description in nightmode.
  static/styles/night_mode.scss
Labels: size: S

#14630 base: Fix jinja2.exceptions.UndefinedError on Python ≥ 3.7
  templates/zerver/base.html
Labels: size: XS

#14635 Update WSL Dev Setup Documentation.
  docs/development/setup-advanced.md
Labels: size: S

#14622 templates: Fix invalid self-closing tags
  static/templates/message_reaction.hbs
  static/templates/settings/account_settings.hbs
  static/templates/settings/organization_settings_admin.hbs
  static/templates/typeahead_list_item.hbs
Labels: size: S

#14628 openapi: Pass validation of zulip.yaml on openapi-generator.
  zerver/openapi/zulip.yaml
Labels: size: S

#14620 version control: Add note about paragraph formatting.
  docs/contributing/version-control.md
Labels: size: XS

#14627 Navbar: Improve search_icon related styles.
  static/styles/zulip.scss
Labels: size: M

#14641 styles: Fix code block styling for Python-Markdown upgrade
  static/styles/rendered_markdown.scss
Labels: size: XS

#14126 Remove file upload status texts on failure
  frontend_tests/node_tests/upload.js
  static/js/upload.js
Labels: size: L

#14652 streams settings: Make stream filter to next line.
  frontend_tests/casper_tests/05-subscriptions.js
  static/js/subs.js
  static/styles/subscriptions.scss
  static/templates/subscription_table_body.hbs
Labels: area: onboarding, area: stream settings, size: L

#14650 dependencies: Patch spectrum-colorpicker for jQuery 3.5 compatibility
  package.json
  version.py
  yarn.lock
Labels: size: S

#14414 Add stream sorting widget to subscriptions page
  frontend_tests/node_tests/subs.js
  static/js/stream_data.js
  static/js/subs.js
  static/styles/subscriptions.scss
Labels: size: XL

#14632 upload: Include filename at the end of temporary access URLs.
  zerver/lib/upload.py
  zerver/tests/test_upload.py
  zerver/views/upload.py
  zproject/urls.py
Labels: size: M

#14669 provision: Clean up code related to migrations and digests
  scripts/lib/zulip_tools.py
  tools/lib/provision_inner.py
  zerver/lib/test_fixtures.py
Labels: size: XL

#14128 ui: fix deleted msg color in Message edit history modal
  static/styles/night_mode.scss
  static/styles/rendered_markdown.scss
Labels: design, size: XS

#14655 design: Make copy text button clickable again.
  static/styles/zulip.scss
Labels: size: XS

#14674 docs/wsl: Add recommendations for developing using WSL.
  docs/development/setup-advanced.md
Labels: size: S

#14687 team: Don't remove duplicate commits inside the retry loop
  tools/fetch-contributor-data
Labels: size: S

#14686 api: Refactor get_members_backend to return a single bot's data.
  zerver/tests/test_users.py
  zerver/views/users.py
Labels: size: S

#14538 Add support for configuring which realms use which SAML providers in multi-organization servers
  zerver/tests/test_auth_backends.py
  zproject/backends.py
Labels: area: authentication, difficult, size: S

#14381 check-openapi: Restore functionality after OpenAPI definitions moved
  package.json
  tools/check-openapi
Labels: area: documentation (api and integrations), size: L

#14670 stream settings: Correct alignment of filter streams div
  frontend_tests/node_tests/components.js
  static/js/components.js
  static/js/subs.js
  static/styles/app_components.scss
  static/styles/night_mode.scss
Labels: size: S

#14647 Upgrade libthumbor to latest release.
  requirements/common.in
  requirements/dev.txt
  requirements/prod.txt
  version.py
Labels: size: S

#14698 requirements: Unpin libthumbor version in common.in
  requirements/common.in
Labels: size: XS

#14703 user-popover: Replace bullhorn icon with paper-plane.
  static/templates/user_info_popover_content.hbs
Labels: size: XS

#14678 logging_util: Handle record.status_code missing in skip_200_and_304.
  zerver/lib/logging_util.py
Labels: area: production, bug, priority: high, size: XS

#14710 circleci: Test provision and upgrade error messages on Ubuntu 16.04
  .circleci/config.yml
Labels: size: M

#14708 .editorconfig: Add .scss, .hbs; drop weirder rules
  .editorconfig
Labels: size: S

#14706 styles: Fix code block white-space for Python-Markdown upgrade
  static/styles/rendered_markdown.scss
Labels: size: XS

#14695 install-{sgrep,shellcheck}: Check that we detect the version correctly
  tools/setup/install-sgrep
  tools/setup/install-shellcheck
Labels: size: S

#14696 Navbar search query val behaviour
  static/js/narrow.js
  static/js/tab_bar.js
Labels: size: S

#14712 circleci: Test zulip-puppet-apply on Ubuntu 16.04
  .circleci/config.yml
Labels: size: S

#14688 typeahead: Show only active users in mention typeaheads.
  frontend_tests/node_tests/composebox_typeahead.js
  frontend_tests/node_tests/people.js
  static/js/composebox_typeahead.js
  static/js/people.js
Labels: size: L

#14443 [WIP] Update org settings to differentiate between full members and members.
  zerver/lib/events.py
  zerver/models.py
Labels: has conflicts, size: L

#14724 settings: Set correct hostname for droplets in 18.04.
  zproject/dev_settings.py
Labels: size: S

#14725 styles: Size full-viewport fixed elements as 100%, not 100vw × 100vh
  static/styles/app_components.scss
  static/styles/popovers.scss
  static/styles/subscriptions.scss
Labels: area: mobile web, area: stream settings, bug, size: S

#14726 docs: Bump copyright year
  LICENSE
  docs/conf.py
Labels: size: XS

#14727 nginx: Listen for ACME challenges on port 80 too
  puppet/zulip/templates/nginx/zulip-enterprise.template.erb
Labels: size: S

#14731 circleci: Test parsing PostgreSQL scripts on Ubuntu 16.04
  .circleci/config.yml
Labels: size: XS

#14662 browser_support: Drop support for Internet Explorer.
  static/styles/portico/portico.scss
  templates/zerver/unsupported_browser.html
  zerver/tests/test_home.py
  zerver/views/compatibility.py
  zerver/views/home.py
Labels: size: L

#14741 droplet settings: Fix hostname-related settings.
  tools/run-dev.py
  zproject/dev_settings.py
  zproject/settings.py
Labels: size: S

#14744 nginx: Replace unanchored regexes in location directives
  puppet/zulip/files/nginx/zulip-include-frontend/app
  puppet/zulip_ops/files/nginx/sites-available/loadbalancer
Labels: size: M

#14734 url preview: Use Chrome's user agent instead of a Zulip one.
  zerver/lib/url_preview/preview.py
Labels: size: S

#14514 user profile cards: Fix bug with deactivated user.
  static/js/popovers.js
Labels: area: message view, size: S

#14765 home: Don't use pointer to compute furthest_read_time.
  zerver/models.py
  zerver/tests/test_home.py
  zerver/views/home.py
Labels: size: M

#14766 stream_edit: Remove unnacessary conditionals.
  static/js/stream_edit.js
Labels: size: S

#14773 alert_words: Change test_alert_words to use actions.do_*().
  zerver/tests/test_alert_words.py
Labels: size: S

#14781 test databases: Fix dev/test typo.
  zerver/lib/test_fixtures.py
Labels: size: XS

#14566 narrow: bugfix: Update stream list height after rendering completes.
  frontend_tests/node_tests/narrow.js
  frontend_tests/node_tests/narrow_activate.js
  frontend_tests/node_tests/pm_list.js
  static/js/narrow.js
  static/js/pm_list.js
Labels: size: S

#14788 provision: Run configure_rabbitmq on clean checkouts.
  tools/lib/provision_inner.py
Labels: size: M

#14789 api: Always return zulip_version/zulip_feature_level.
  templates/zerver/api/changelog.md
  zerver/lib/events.py
  zerver/openapi/zulip.yaml
  zerver/tests/test_events.py
Labels: size: M

#14774 night mode: Fix "x" on "You have nothing to send!"
  static/styles/night_mode.scss
Labels: size: XS

#14802 migrations: Add Message indexes on (recipient_id, subject).
  zerver/migrations/0279_message_recipient_subject_indexes.py
Labels: size: S

#14801 api_code_examples: Fix buggy rendering of print statement in python examples.
  zerver/lib/bugdown/api_code_examples.py
Labels: size: XS

#14803 provision: Update migration digest after db rebuild.
  tools/lib/provision_inner.py
  zerver/lib/test_fixtures.py
Labels: size: S

#14806 ci: bugfix: Don't restore emoji cache on prod.
  .circleci/config.yml
Labels: size: XS

#14820 user settings: Correct overflow behaviour of custom user field.
  static/styles/settings.scss
Labels: size: XS

#14822 node tests: Add test_realm_boolean test for default_twenty_four_hour_time.
  frontend_tests/node_tests/dispatch.js
Labels: size: XS
