Repository zulip/zulip, pull requests merged in 2020-07, with the labels that each got.

#15629 tests: Remove slow tests detection
  tools/test-backend
  zerver/lib/test_runner.py
  zerver/tests/test_docs.py
  zerver/tests/test_events.py
  zerver/tests/test_home.py
  zerver/tests/test_import_export.py
  zerver/tests/test_management_commands.py
  zerver/tests/test_markdown.py
  zerver/tests/test_messages.py
  zerver/tests/test_realm.py
  zerver/tests/test_slack_message_conversion.py
  zerver/tests/test_subs.py
  zerver/tests/test_urls.py
Labels: size: XL

#15636 lint: Upgrade zulint and remove run-isort wrapper
  requirements/dev.in
  requirements/dev.txt
  tools/lint
  tools/linter_lib/custom_check.py
  tools/run-isort
  version.py
Labels: size: S

#15645 Update Nginx version in success-http-headers-focal.
  tools/ci/success-http-headers-focal.txt
Labels: size: XS

#15644 minor: Tag a string for translation.
  static/js/drafts.js
Labels: size: XS

#15642 settings: Fix modal out of screen on mobile.
  static/styles/components.scss
  static/styles/settings.scss
  static/templates/settings/account_settings.hbs
Labels: area: mobile web, bug, size: M

#15648 postgres-init-db: Read terminate-psql-sessions script as root
  scripts/setup/postgres-init-db
Labels: area: production installer, bug, priority: blocker, size: XS

#15643 install: Create zulip user only if required
  scripts/lib/install
Labels: size: XS

#15656 settings_panel_menu: Remove "settings-wrapper" class from jquery selectors.
  static/js/settings_panel_menu.js
Labels: size: XS

#15652 emails: Improve handling of timeouts when sending.
  zerver/worker/queue_processors.py
  zproject/computed_settings.py
Labels: size: S

#15663 requirements: Update Python requirements
  requirements/dev.txt
  requirements/docs.txt
  requirements/pip.txt
  requirements/prod.txt
  requirements/thumbor-dev.txt
  requirements/thumbor.txt
  version.py
Labels: size: XL

#15681 remote_server: Fix send_to_push_bouncer type
  zerver/lib/remote_server.py
  zerver/tests/test_push_notifications.py
Labels: size: S

#15684 streams: Format subscriber count according to browser locale.
  static/js/templates.js
  static/templates/subscription_count.hbs
Labels: size: XS

#15685 msg_edit_form: Show checkboxes in separate lines if present.
  static/styles/app_components.scss
  static/styles/zulip.scss
  static/templates/message_edit_form.hbs
Labels: size: S

#15670 refactor: Rename convert to markdown_convert.
  zerver/lib/import_realm.py
  zerver/lib/markdown/__init__.py
  zerver/lib/message.py
  zerver/lib/realm_description.py
  zerver/lib/streams.py
  zerver/tests/test_custom_profile_data.py
  zerver/tests/test_markdown.py
Labels: size: XL

#15665 mark_all_messages_unread: Remove reset of depricated pointer.
  zilencer/management/commands/mark_all_messages_unread.py
Labels: size: XS

#15683 move_topic_to_stream: Apply the event to the fetched state.
  zerver/lib/events.py
  zerver/tests/test_events.py
Labels: area: api, area: message-editing, bug, difficult, size: L

#15703 test-install: Do not install rabbitmq in base install.
  tools/test-install/prepare-base
Labels: size: XS

#15695 docs: Add steps for configuring message retention policy in the docs.
  templates/zerver/help/message-retention-policy.md
Labels: area: documentation (user), priority: high, size: M

#15704 timerender: Make moment() return static date.
  frontend_tests/node_tests/timerender.js
Labels: size: S

#15705 node-tests: Log file name and test label on failure.
  frontend_tests/zjsunit/index.js
Labels: area: testing-infrastructure, size: S

#15669 Substitute Nginx version in success-http-headers.txt based on OS.
  .circleci/config.yml
  tools/ci/production-build
  tools/ci/production-verify
  tools/ci/success-http-headers-focal.txt
  tools/ci/success-http-headers.template.txt
  tools/linter_lib/custom_check.py
Labels: size: L

#15502 compose: Use rendered_markdown.update_elements for previews.
  frontend_tests/node_tests/compose.js
  static/js/compose.js
Labels: area: markdown, bug, size: S

#15720 emoji_picker: Improve emoji picker search results.
  static/js/emoji_picker.js
Labels: area: emoji, enhancement, size: XS

#15717 recent_topics: Set correct container as scrolling container.
  static/styles/recent_topics.scss
Labels: size: XS

#15728 emoji_picker: Fix keys not working if search yields no results.
  static/js/emoji_picker.js
Labels: size: XS

#15737 stream: Fix incorrect dispaly of stream notifications settings.
  static/js/stream_data.js
Labels: size: XS

#15691 message_header: Fix overlap on mobile with flex.
  static/styles/zulip.scss
  static/templates/recipient_row.hbs
Labels: area: mobile web, bug, size: S

#15736 zulip_tools: Replace deprecated mktemp call
  scripts/lib/zulip_tools.py
Labels: size: S

#15744 nagios: Remove check_memcached.
  puppet/zulip_ops/files/nagios3/commands.cfg
  puppet/zulip_ops/files/nagios3/conf.d/services.cfg
Labels: size: S

#15738 requirements: Upgrade Python requirements
  requirements/dev.in
  requirements/dev.txt
  requirements/docs.txt
  requirements/prod.txt
  requirements/thumbor-dev.txt
  requirements/thumbor.in
  requirements/thumbor.txt
  version.py
Labels: size: XL

#15730 puppet: Don't run thumbor services in production.
  puppet/zulip/manifests/dockervoyager.pp
  puppet/zulip/manifests/supervisor.pp
  puppet/zulip/manifests/voyager.pp
Labels: size: S

#15766 scss: Fix broken rules.
  static/styles/zulip.scss
Labels: size: XS

#15771 message send: Update failed message ui on re-send success.
  frontend_tests/node_tests/echo.js
  static/js/echo.js
  static/js/message_store.js
Labels: area: compose, area: message-editing, bug, size: S

#15749 IRC integration: Update doc to include a cd to the IRC dir.
  templates/zerver/integrations/irc.md
Labels: size: S

#15764 docs: Fix typo in using.md
  docs/git/using.md
Labels: size: XS

#15775 message_header: Fix date alignment in PMs.
  static/styles/zulip.scss
Labels: size: XS

#15778 puppet: Add missing trailing commas
  puppet/zulip/manifests/base.pp
  puppet/zulip/manifests/nginx.pp
  puppet/zulip/manifests/postgres_appdb_tuned.pp
  puppet/zulip/manifests/postgres_common.pp
  puppet/zulip/manifests/supervisor.pp
  puppet/zulip_ops/manifests/postgres_appdb.pp
Labels: size: S

#15782 push_notifications: Return if push_notify already active.
  zerver/lib/push_notifications.py
  zerver/tests/test_push_notifications.py
Labels: size: L

#15780 navbar: Fix disappearing left border when search opens.
  static/styles/zulip.scss
Labels: size: XS

#15783 reactions: Add back missing e.stopPropagation().
  static/js/click_handlers.js
Labels: size: XS

#15793 lint: Restore pycodestyle wrapper’s check for empty list of files
  tools/linter_lib/pep8.py
Labels: size: XS

#15795 puppet: Update nagios check_postgres_replication_lag to be on DB hosts
  puppet/zulip/files/nagios_plugins/zulip_postgres_appdb/check_postgres_replication_lag
  puppet/zulip_ops/files/nagios3/commands.cfg
Labels: size: XS

#15794 puppet: Revert PostgreSQL setting of recovery_target_timeline
  puppet/zulip/templates/postgresql/10/postgresql.conf.centos.template.erb
  puppet/zulip/templates/postgresql/10/postgresql.conf.template.erb
  puppet/zulip/templates/postgresql/11/postgresql.conf.template.erb
  puppet/zulip/templates/postgresql/12/postgresql.conf.template.erb
  puppet/zulip/templates/postgresql/9.5/postgresql.conf.template.erb
  puppet/zulip/templates/postgresql/9.6/postgresql.conf.template.erb
Labels: priority: blocker, size: S

#15792 settings: Fix saving indicator glitch.
  static/js/loading.js
  static/styles/settings.scss
Labels: area: settings UI, bug, size: XS

#15804 styles: Make focus outline work reliably.
  static/styles/night_mode.scss
  static/styles/zulip.scss
Labels: UX, bug, design, priority: blocker, size: S

#15803 recent_topics: Update topics post message deletion.
  frontend_tests/node_tests/recent_senders.js
  frontend_tests/node_tests/recent_topics.js
  static/js/recent_senders.js
  static/js/recent_topics.js
  static/js/ui.js
Labels: size: XL

#15812 styles: Hide focus outline for active elements.
  static/styles/night_mode.scss
  static/styles/zulip.scss
Labels: size: XS

#15816 node_tests: Pass correct arguments to needs_subscribe_warning.
  frontend_tests/node_tests/compose.js
Labels: size: M

#15799 search icon code clean up + night_mode regression fix
  frontend_tests/node_tests/ui_init.js
  static/js/tab_bar.js
  static/styles/night_mode.scss
  static/styles/zulip.scss
Labels: size: S

#15821 recent_topics: Patch colors.
  static/styles/night_mode.scss
  static/styles/recent_topics.scss
  static/templates/recent_topics_table.hbs
Labels: size: S

#15822 click_handlers: Don't focus elements on dragstart.
  static/js/click_handlers.js
Labels: size: S

#15823 click_handlers: Don't focus links on middle / right click.
  static/js/click_handlers.js
Labels: size: S

#15835 dead code: Remove legacy reaction actions.
  zerver/lib/actions.py
  zerver/tests/test_events.py
Labels: size: L

#15842 docs: Fix link in 3.0 upgrade docs.
  docs/overview/changelog.md
Labels: size: XS

#15845 Revert "markdown: Remove paragraphs that only contain a tweet link."
  zerver/lib/markdown/__init__.py
  zerver/tests/test_markdown.py
Labels: size: M

#15752 docs: Add information about how desktop app handles certificates
  templates/zerver/help/custom-certificates.md
  templates/zerver/help/desktop-app-install-guide.md
  templates/zerver/help/include/sidebar_index.md
Labels: size: L

#15848 edit: Removed "William Wendling" from the django.po file.
  locale/fr/LC_MESSAGES/django.po
Labels: size: XS

#15852 ui: Fix loading spinner glitch.
  static/js/loading.js
Labels: bug, size: XS

#15839 ldap: Use zulip.ldap logger in ZulipLDAPUserPopulator.
  zproject/backends.py
Labels: size: S

#15627 emoji: Rename :slight_smile: to :smile:.
  frontend_tests/node_tests/markdown.js
  frontend_tests/node_tests/reactions.js
  static/js/emoji.js
  static/shared/js/typeahead.js
  templates/zerver/help/emoji-and-emoticons.md
  templates/zerver/help/enable-emoticon-translations.md
  tools/setup/emoji/emoji_names.py
  tools/setup/emoji/emoji_setup_utils.py
  zerver/tests/fixtures/markdown_test_cases.json
  zerver/tests/test_reactions.py
Labels: area: emoji, post-release, size: L

#15870 ui_util: Fix incorrectly converted focus method call
  static/js/ui_util.js
Labels: size: XS

#15871 js: Fix incorrectly converted blur and click method calls
  static/js/click_handlers.js
  static/js/drafts.js
  static/js/emoji_picker.js
  static/js/hotkey.js
Labels: size: S

#15869 email_mirror: fix exception when getting addresses
  zerver/lib/email_mirror.py
  zerver/tests/test_email_mirror.py
Labels: area: emails, bug, priority: high, size: S

#15884 landing-page: Remove onunload hack, clean up ready callbacks
  static/js/portico/landing-page.js
Labels: size: S

#15883 docs: Document that we use Prettier
  README.md
  docs/contributing/code-style.md
  docs/testing/linters.md
Labels: size: S

#15855 markdown: Inline Youtube previews instead of appending it to the end.
  zerver/lib/markdown/__init__.py
  zerver/tests/test_markdown.py
Labels: size: M

#15714 Create event_schema.py (v2)
  zerver/lib/event_schema.py
  zerver/tests/test_events.py
Labels: size: XL

#15892 message_edit: Fix invisible delete spinner.
  static/styles/zulip.scss
Labels: size: XS

#15886 Fix some failing Casper tests
  frontend_tests/casper_tests/03-narrow.js
  frontend_tests/casper_tests/06-settings.js
  frontend_tests/casper_tests/16-copy-and-paste.js
  tools/setup/generate-test-credentials
Labels: size: L

#15889 subs: Fix set_muted parameter order
  static/js/stream_edit.js
  static/js/subs.js
Labels: size: XS

#15891 upload: Do not open compose box when editing.
  static/js/upload.js
Labels: area: compose, bug, priority: high, size: XS

#15906 test flake fix: Avoid logging leak for webhook tests.
  zerver/tests/test_outgoing_webhook_system.py
Labels: size: S

#15895 event schema: Handle tricky update schemas
  zerver/lib/event_schema.py
  zerver/tests/test_events.py
Labels: size: XL

#15885 recent_topics: Skip non-stream messages in update_topics_of_message_ids
  frontend_tests/node_tests/recent_senders.js
  static/js/recent_senders.js
  static/js/recent_topics.js
Labels: size: S

#15815 provisioning: Use AWS CLI to automate provisioning
  tools/setup/bootstrap-aws-installer
  tools/setup/bootstrap-awscli
  tools/setup/install-aws-server
Labels: size: XL

#15916 activity: Always include realms on standard plan
  analytics/views.py
Labels: size: XS

#15915 analytics: Remove unused analytics management commands.
  analytics/management/commands/analyze_mit.py
  analytics/management/commands/analyze_user_activity.py
  analytics/management/commands/client_activity.py
  analytics/management/commands/realm_stats.py
  analytics/management/commands/user_stats.py
Labels: size: XL

#15887 emoji: Switch to `user_profile.realm` for cross-realm reactions.
  zerver/views/reactions.py
Labels: area: emoji, bug, priority: high, size: XS

#15913 Clean up webhook tests
  zerver/tests/test_outgoing_webhook_system.py
Labels: size: XL

#15930 test: Add order_by in query for RealmAuditLog.
  zerver/tests/test_audit_log.py
Labels: size: XS

#15923 saml: Fix incorrect settings object being passed in get_issuing_idp.
  zproject/backends.py
Labels: area: authentication, bug, size: S

#15925 tools/ci: Fix KeyError when running tools/ci/generate-dockerfiles.
  tools/ci/Dockerfile.template
Labels: size: XS

#15924 mobile sharing: Make emoji.js a shared ES6 module.
  frontend_tests/node_tests/markdown.js
  static/js/markdown.js
  static/js/markdown_config.js
Labels: size: XL

#15908 i18n: Tag strings for translation.
  static/js/ui_init.js
  static/templates/edit_content_button.hbs
Labels: size: M

#15944 middleware: Stop shadowing top-level logger definition on line 33.
  zerver/middleware.py
Labels: size: XS

#15955 node tests: Swap actual/expected in various assert calls.
  frontend_tests/node_tests/markdown.js
  frontend_tests/node_tests/settings_org.js
  frontend_tests/node_tests/timerender.js
  frontend_tests/node_tests/ui.js
Labels: size: L

#15954 webhooks/freshdesk: Remove key checking step.
  zerver/webhooks/freshdesk/tests.py
  zerver/webhooks/freshdesk/view.py
Labels: size: M

#15940 support: Return json_error if the POST request is invalid
  analytics/tests/test_views.py
  analytics/views.py
Labels: size: S

#15959 js: Fix more incorrectly converted trigger calls
  static/js/popovers.js
  static/js/portico/integrations.js
Labels: size: XS

#15960 integrations: Autofocus the search input.
  static/js/portico/integrations.js
  static/styles/portico/integrations.scss
Labels: bug, size: S

#15876 registration: Improve registration form
  frontend_tests/casper_tests/00-realm-creation.js
  frontend_tests/puppeteer_tests/00-realm-creation.js
  static/styles/portico/portico-signin.scss
  static/styles/portico/portico.scss
  templates/zerver/register.html
Labels: size: L

#15917 puppet: Increase backlogged socket count based on uwsgi backlog.
  puppet/zulip/manifests/app_frontend_base.pp
  puppet/zulip/templates/sysctl.d/40-uwsgi.conf.erb
Labels: size: S

#15971 emoji: Make :stuck_out_tongue: have open eyes.
  tools/setup/emoji/emoji_names.py
  version.py
Labels: area: emoji, bug, size: S

#15982 Revert "digest: Support digest of web public streams for guest users."
  zerver/lib/digest.py
  zerver/tests/test_digest.py
Labels: size: M

#15981 styles: Reorder rule to work around weird postcss-nested bug
  static/styles/portico/landing-page.scss
Labels: size: XS

#15980 docs: Replace Digital Ocean with DigitalOcean
  README.md
  docs/development/request-remote.md
  docs/production/install.md
  requirements/dev.in
  templates/zerver/help/gdpr-compliance.md
  tools/droplets/README.md
  tools/droplets/add_mentor.py
  tools/droplets/create.py
Labels: size: M

#15942 Spam removal
  zerver/tests/test_logging_handlers.py
Labels: size: S

#15984 compose: Remove href from the `formatting` button in the compose box.
  templates/zerver/app/compose.html
Labels: size: S

#15987 migrations: Upgrade migrations to remove duplicates in all Count tables.
  analytics/migrations/0015_clear_duplicate_counts.py
Labels: size: M

#15725 tab bar rename
  .eslintrc.json
  frontend_tests/node_tests/narrow_activate.js
  frontend_tests/node_tests/search.js
  frontend_tests/node_tests/search_legacy.js
  frontend_tests/node_tests/stream_events.js
  frontend_tests/node_tests/ui_init.js
  static/js/bundles/app.js
  static/js/floating_recipient_bar.js
  static/js/global.d.ts
  static/js/hotkey.js
  static/js/message_view_header.js
  static/js/narrow.js
  static/js/search.js
  static/js/stream_color.js
  static/js/stream_events.js
  static/js/subs.js
  static/js/ui_init.js
  static/styles/night_mode.scss
  static/styles/zulip.scss
  static/templates/message_view_header.hbs
  templates/zerver/app/index.html
  templates/zerver/app/navbar.html
  tools/check-templates
  tools/test-js-with-node
Labels: size: XL

#15976 puppeteer: Settings test
  frontend_tests/puppeteer_lib/common.js
  frontend_tests/puppeteer_tests/05-settings.js
Labels: size: XL

#15988 requirements: Downgrade pip to 20.1.1 due to pip-tools incompatibility
  requirements/dev.txt
  requirements/pip.in
  requirements/pip.txt
  requirements/prod.txt
  requirements/thumbor-dev.txt
  version.py
Labels: size: M

#15989 markdown: Treat more twitter codes as also permanent failures.
  zerver/lib/markdown/__init__.py
Labels: size: M

#15991 version: Update version for Zulip Desktop v5.4.0 release.
  version.py
Labels: size: XS

#15994 sponsorship: Ensure that all the fields are filled in the form
  frontend_tests/node_tests/upgrade.js
  static/js/billing/upgrade.js
  templates/corporate/upgrade.html
Labels: size: S

#15995 Update the mailmap of major Zulip contributors
  .mailmap
Labels: size: S

#15990 uwsgi: Stop generating IOError and SIGPIPE on client close.
  puppet/zulip/templates/uwsgi.ini.template.erb
Labels: size: XS
