Repository zulip/zulip, pull requests merged in 2020-01, with the labels that each got.

#13607 dependencies: Upgrade vnu-jar
  package.json
  version.py
  yarn.lock
Labels: size: S

#13606 install: Run generate_secrets.py before zulip-puppet-apply
  puppet/zulip/manifests/camo.pp
  scripts/lib/install
  scripts/setup/generate_secrets.py
Labels: size: M

#13617 minor: Avoid recip.user_id defensive fallback.
  static/js/message_store.js
Labels: size: XS

#13623 puppet: Switch double quoted strings to single quoted
  puppet/zulip/manifests/app_frontend_base.pp
Labels: size: XS

#13629 search: Retrofit recent changes to pills code.
  frontend_tests/node_tests/search_suggestion.js
  static/js/search_suggestion.js
Labels: area: search, size: L

#13628 Small StreamRecipientMap optimizations
  zerver/lib/actions.py
  zerver/lib/stream_recipient.py
  zerver/tests/test_events.py
  zerver/tests/test_home.py
  zerver/tests/test_subs.py
Labels: size: L

#13619 docs: link to more-currently-maintained fork of GitX
  docs/git/setup.md
Labels: size: XS

#13648 Convert more stream_ids to ints.
  static/js/stream_color.js
  static/js/stream_popover.js
Labels: size: M

#13649 Fix non-int user_ids in user popovers.
  static/js/popovers.js
Labels: size: S

#13659 puppet: Fix zuli-redis.conf path typo
  puppet/zulip/manifests/redis.pp
Labels: size: M

#13667 org settings: Fix error of wrong type of argument passed to InDict.has().
  static/js/settings_users.js
Labels: size: XS

#13717 Update API docs usage example
  docs/documentation/api.md
Labels: size: S

#13733 install: Reduce the RAM limit to accommodate some definition of "2GB".
  scripts/lib/install
Labels: size: S

#13729 emails: Set alt attribute to empty for leading images
  templates/zerver/emails/confirm_new_email.source.html
  templates/zerver/emails/confirm_registration.source.html
  templates/zerver/emails/custom_email_base.pre.html
  templates/zerver/emails/find_team.source.html
  templates/zerver/emails/followup_day1.source.html
  templates/zerver/emails/followup_day2.source.html
  templates/zerver/emails/invitation.source.html
  templates/zerver/emails/invitation_reminder.source.html
  templates/zerver/emails/notify_change_in_email.source.html
  templates/zerver/emails/notify_new_login.source.html
  templates/zerver/emails/password_reset.source.html
  templates/zerver/emails/realm_reactivation.source.html
  version.py
Labels: size: M

#13735 bots: Remove FEEDBACK_BOT implementation.
  docs/production/troubleshooting.md
  puppet/zulip/manifests/base.pp
  puppet/zulip_ops/files/nagios3/conf.d/services.cfg
  scripts/nagios/check-rabbitmq-consumers
  static/js/click_handlers.js
  static/js/resize.js
  static/styles/right-sidebar.scss
  templates/zerver/app/navbar.html
  templates/zerver/app/right_sidebar.html
  tools/linter_lib/custom_check.py
  tools/test-backend
  zerver/lib/actions.py
  zerver/lib/feedback.py
  zerver/lib/import_realm.py
  zerver/management/commands/initialize_voyager_db.py
  zerver/tests/test_feedback.py
  zerver/views/home.py
  zerver/worker/queue_processors.py
  zproject/default_settings.py
  zproject/prod_settings_template.py
Labels: area: production, priority: high, size: XL

#13721 night_mode: Render the message instead of showing raw `/night` text.
  static/js/zcommand.js
  static/styles/night_mode.scss
Labels: size: S

#13743 int_dict: Fix type errors for user_groups.
  static/js/message_list_view.js
  static/js/settings_user_groups.js
Labels: size: XS

#13753 hotkey: Optimize processing_text.
  static/js/hotkey.js
Labels: size: S

#13757 docs: Update swagger example to suit V3.0.1.
  docs/documentation/openapi.md
Labels: size: S

#13767 Fix pill-container piece of recent hotkey fix.
  static/js/hotkey.js
Labels: size: XS

#13765 email_mirror: Parse encoded From headers with show_sender=True.
  zerver/lib/email_mirror.py
  zerver/tests/test_email_mirror.py
Labels: size: M

#13771 clean_venv_cache: Limit search to .txt requirements files.
  scripts/lib/clean_venv_cache.py
Labels: size: XS

#13775 Email mirror encoded attachment filename parsing
  zerver/lib/email_mirror.py
  zerver/tests/test_email_mirror.py
Labels: size: L

#13741 social_auth: Clear session fields leftover from previous auth attempts.
  zerver/tests/test_auth_backends.py
  zerver/views/auth.py
  zproject/settings.py
  zproject/urls.py
Labels: area: authentication, area: mobile, bug, size: L

#13781 Delete missedmessage_email_senders
  puppet/zulip/manifests/base.pp
  puppet/zulip_ops/files/nagios3/conf.d/services.cfg
  scripts/nagios/check-rabbitmq-consumers
  tools/test-queue-worker-reload
  zerver/worker/queue_processors.py
Labels: size: M

#13705 compose: Improved warning for wildcard mentions.
  frontend_tests/node_tests/general.js
  frontend_tests/node_tests/templates.js
  frontend_tests/node_tests/util.js
  static/js/compose.js
  static/js/util.js
  static/templates/compose_all_everyone.hbs
Labels: area: compose, priority: high, size: L

#13785 register: Ensure future client_capabilities fields are optional.
  zerver/views/events_register.py
Labels: size: XS
