Repository zulip/zulip, pull requests merged in 2021-12, with the labels that each got.

#20405 compose_actions: Add comment about spread syntax overwrite behavior.
  static/js/compose_actions.js
Labels: size: XS

#20414 jobs: Update designer job description.
  templates/corporate/jobs.html
Labels: size: XL

#20391 Replaced pencil with chevron-down #19888
  static/styles/settings.css
  static/styles/zulip.css
  static/templates/settings/dropdown_list_widget.hbs
Labels: size: S

#20412 links: Rename developer-community -> development-community.
  templates/zerver/development-community.html
  templates/zerver/development-community.md
  templates/zerver/faq.html
  templates/zerver/footer.html
  templates/zerver/for-companies.html
  templates/zerver/for-education.html
  templates/zerver/for-events.html
  templates/zerver/for-open-source.html
  templates/zerver/for-research.html
  templates/zerver/for/tum-case-study.md
  templates/zerver/hello.html
  templates/zerver/help/getting-your-organization-started-with-zulip.md
  templates/zerver/help/include/trying-out-zulip.md
  templates/zerver/help/setting-up-zulip-for-a-class.md
  templates/zerver/landing_nav.html
  zerver/tests/test_docs.py
  zproject/urls.py
Labels: size: L

#20411 help center: Remove outdated intro from index page.
  templates/zerver/help/index.md
  zerver/tests/test_middleware.py
Labels: size: S

#20407 #20284 Updated tooltips in left_sidebar
  static/templates/left_sidebar.hbs
Labels: size: S

#20421 onboarding: Replace 'edit profile' with 'profile' in bot command list.
  zerver/lib/onboarding.py
  zerver/tests/test_tutorial.py
Labels: size: S

#20418 requirements: Upgrade Python requirements
  requirements/dev.txt
  requirements/docs.txt
  requirements/mypy.txt
  requirements/pip.txt
  requirements/prod.txt
  tools/upload-release
  version.py
  zerver/tests/test_message_fetch.py
Labels: size: XL

#20424 edit_bot_modal: Fix puppeteer test flake.
  frontend_tests/puppeteer_tests/settings.ts
Labels: size: XS

#20430 semgrep: Enforce use of get_object_from_key for Confirmation fetching.
  tools/semgrep.yml
Labels: size: S

#20268 Removed Unset and Disable buttons when user doesnt have permissions
  static/js/settings_org.js
Labels: size: XS

#20429 Disable `enable_spectator_access` setting in UI when server-level setting is set to False.
  static/js/admin.js
  static/styles/dark_theme.css
  static/styles/settings.css
  static/templates/settings/organization_permissions_admin.hbs
  static/templates/settings/settings_checkbox.hbs
Labels: size: M, area: web public streams

#20432 Replace hardcoded regex with toLocaleString #20416
  static/js/stats/stats.js
Labels: size: XS

#20184 Created new function for fetching medium avatar URLs
  frontend_tests/node_tests/people.js
  frontend_tests/node_tests/popovers.js
  static/js/people.js
  static/js/popovers.js
  static/js/user_profile.js
Labels: size: M

#20433 docs: Secret reading is done using RawConfigParser, not ConfigParser.
  docs/subsystems/settings.md
Labels: size: S

#20089 user-documentation: Add documentation to resize the compose box
  templates/zerver/help/include/sidebar_index.md
  templates/zerver/help/open-the-compose-box.md
  templates/zerver/help/resize-the-compose-box.md
Labels: area: documentation (user), priority: high, size: M, release goal

#20435 Apply dark theme to upgrade tips
  static/styles/dark_theme.css
Labels: size: XS

#20441 test_events: Rename functions to use dark_theme and light_theme.
  zerver/tests/test_events.py
Labels: size: XS

#20453 configure-rabbitmq: Increase startup timeout
  scripts/setup/configure-rabbitmq
Labels: size: XS

#20446 events: Explicitly send empty drafts to spectators.
  zerver/lib/events.py
Labels: size: S, release goal, area: web public streams

#20450 Rewrite template pretty-printer.
  templates/zerver/accounts_send_confirm.html
  templates/zerver/config_error.html
  templates/zerver/development/email_log.html
  templates/zerver/emails/confirm_new_email.source.html
  templates/zerver/features.html
  templates/zerver/pricing_model.html
  tools/lib/pretty_print.py
  tools/lib/template_parser.py
  tools/tests/test_pretty_print.py
Labels: size: XL

#20447 move_topic_to_stream: Fix clipped stream select dropdown.
  static/styles/popovers.css
Labels: size: S

#20448 recent_topics: Extend persistent focus bug to all RT elements.
  static/js/recent_topics_ui.js
Labels: bug, area: keyboard UI, priority: high, size: S, area: recent-topics

#20344 Upgrade wal-g to 1.1.1
  puppet/zulip/manifests/postgresql_backups.pp
Labels: size: M

#20376 user_sidebar: Set personal presence dot based on the user's settings.
  frontend_tests/node_tests/activity.js
  frontend_tests/node_tests/buddy_data.js
  frontend_tests/node_tests/dispatch.js
  frontend_tests/node_tests/presence.js
  static/js/presence.js
  static/js/server_events_dispatch.js
Labels: bug, area: right-sidebar, size: S

#20456 Incorporate feedback on jobs page
  templates/corporate/jobs.html
Labels: size: S

#20474 puppet: Remove unused 'builder' files.
  puppet/zulip/lib/puppet/type/chroot.rb
  puppet/zulip_ops/files/builder/sbuildrc
  puppet/zulip_ops/files/builder/ubuntu-archive-keyring.gpg
Labels: size: L

#20476 message: Check wildcard mention restrictions while editing message.
  zerver/lib/actions.py
  zerver/tests/test_message_edit.py
Labels: size: L

#20461 resize: Hide popover on width change on mobile devices.
  static/js/resize.js
Labels: bug, area: compose, size: S

#20471 saml: Set wantMessagesSigned to True only for processing LogoutRequests.
  zproject/backends.py
  zproject/computed_settings.py
Labels: size: S

#20475 puppet: Do not assume amd64 architecture.
  puppet/zulip/manifests/camo.pp
  puppet/zulip/manifests/golang.pp
  puppet/zulip/manifests/postgresql_backups.pp
  puppet/zulip_ops/manifests/profile/grafana.pp
  puppet/zulip_ops/manifests/profile/prometheus_server.pp
  puppet/zulip_ops/manifests/prometheus/node.pp
Labels: size: S, backport candidate

#20478 git: Suppress diffs by default on giant Stripe API fixtures
  .gitattributes
Labels: area: tooling, size: S, area: billing

#20469 import/export: Refactor S3 code.
  zerver/lib/export.py
Labels: size: XL

#20408 billing: Add do_change_remote_server_plan_type.
  corporate/lib/stripe.py
  corporate/tests/test_stripe.py
  zerver/models.py
  zilencer/migrations/0019_remotezulipserver_plan_type.py
  zilencer/migrations/0020_remotezulipserverauditlog.py
  zilencer/models.py
Labels: size: XL

#20493 exports: Add images for single users.
  zerver/lib/export.py
Labels: size: XL

#20500 documentation: Fix text wrapping and alignment of ordered lists.
  static/styles/portico/markdown.css
Labels: bug, area: documentation (user), size: M

#20496 Clean up import tests.
  zerver/tests/test_import_export.py
Labels: size: XL

#19177 Moved empty narrow messages to handlebar templates.
  frontend_tests/node_tests/narrow.js
  frontend_tests/puppeteer_tests/message-basics.ts
  static/js/narrow_banner.js
  static/js/narrow_error.js
  static/styles/zulip.css
  static/templates/empty_feed_notice.hbs
  templates/zerver/app/message_feed_errors.html
  zerver/tests/test_home.py
Labels: size: XL, release goal

#20473 streams: Add notifications for message retention policy updates.
  static/styles/dark_theme.css
Labels: size: XS

#20395 emoji reactions: Order reactions query results by id.
  zerver/models.py
  zerver/tests/test_reactions.py
Labels: bug, area: emoji, size: M

#20491 onboarding: Remove the intro_reply hotspot.
  static/js/click_handlers.js
  static/js/hotspots.js
  static/styles/dark_theme.css
  static/styles/hotspots.css
  static/templates/intro_reply_hotspot.hbs
  zerver/lib/hotspots.py
  zerver/tests/test_events.py
  zerver/tests/test_hotspots.py
  zerver/tests/test_users.py
Labels: area: settings UI, size: XL

#20510 scripts: Only stop/start existing tornado processes.
  scripts/restart-server
  scripts/stop-server
Labels: size: XS

#20511 export: Fix RealmAuditLog queries (and other cleanup)
  zerver/lib/export.py
Labels: size: XL

#20514 Grafana 8.3.1
  puppet/zulip_ops/files/supervisor/conf.d/grafana.conf
  puppet/zulip_ops/manifests/profile/grafana.pp
  puppet/zulip_ops/templates/supervisor/conf.d/grafana.conf.erb
Labels: size: M

#20515 puppet: Only fetch from running hosts in Grafana ec2 discovery.
  puppet/zulip_ops/files/prometheus/prometheus.yaml
Labels: size: XS

#20518 export: Improve message handling.
  zerver/lib/export.py
Labels: size: L

#19418 portico: Add use case buttons to top & bottom of /why-zulip. [WIP]
  static/styles/portico/landing_page.css
  templates/zerver/hello.html
  templates/zerver/why-zulip.html
  templates/zerver/why-zulip.md
Labels: size: XL

#20251 compose: Fix keyboard UI with new global time widget
  static/js/compose.js
  static/js/composebox_typeahead.js
Labels: size: L

#20517 migrations: Remove disallowed characters from topics.
  zerver/migrations/0371_invalid_characters_in_topics.py
Labels: size: L

#20521 Add MOVED notification when topic or stream changed
  frontend_tests/node_tests/message_list_view.js
  static/js/message_list_view.js
  static/templates/edited_notice.hbs
Labels: size: XL

#20189 settings:Change dropdown option label & position,label of input field.
  static/js/settings_config.ts
  static/templates/settings/notification_settings.hbs
  static/templates/settings/organization_permissions_admin.hbs
Labels: size: L

#20524 external links: Migrate the rest of /developer-community links.
  CONTRIBUTING.md
  README.md
  docs/contributing/code-reviewing.md
  docs/contributing/gsoc-ideas.md
  docs/contributing/summer-with-zulip.md
  docs/development/setup-advanced.md
  docs/development/setup-vagrant.md
  docs/index.md
  docs/overview/release-lifecycle.md
  docs/production/install-existing-server.md
  docs/production/install.md
  docs/production/requirements.md
  docs/production/security-model.md
  docs/production/settings.md
  docs/production/upgrade-or-modify.md
  docs/subsystems/performance.md
  docs/testing/linters.md
  docs/translating/translating.md
  docs/tutorials/new-feature-tutorial.md
  templates/zerver/api/client-libraries.md
  templates/zerver/api/running-bots.md
  templates/zerver/emails/followup_day1.source.html
  templates/zerver/emails/followup_day1.txt
  templates/zerver/for/communities.md
  templates/zerver/help/contact-support.md
Labels: size: L

#20520 Get messages for single-user import.
  zerver/lib/export.py
  zerver/tests/test_import_export.py
Labels: size: XL

#20504 Improve handling of memory issues when upgrading from Git
  scripts/lib/upgrade-zulip-stage-2
Labels: area: production installer, size: S, release goal, backport candidate

#20512 puppet: Use certbot package timer, not our own cron job.
  docs/development/remote.md
  docs/production/deployment.md
  docs/production/ssl-certificates.md
  puppet/zulip/files/cron.d/certbot-renew
  puppet/zulip/files/letsencrypt/nginx-deploy-hook.sh
  puppet/zulip/manifests/nginx.pp
  puppet/zulip/manifests/profile/app_frontend.pp
  scripts/lib/certbot-maybe-renew
  scripts/lib/install
  scripts/setup/setup-certbot
Labels: size: XL, backport candidate

#20525 use_cases: Rename /for/companies to /for/business.
  templates/corporate/jobs.html
  templates/zerver/attribution.html
  templates/zerver/footer.html
  templates/zerver/for-business.html
  templates/zerver/hello.html
  templates/zerver/help/include/trying-out-zulip.md
  templates/zerver/landing_nav.html
  templates/zerver/why-zulip.html
  tools/documentation_crawler/documentation_crawler/spiders/check_help_documentation.py
  tools/linter_lib/custom_check.py
  zerver/tests/test_docs.py
  zproject/urls.py
Labels: size: M

#20527 Export
  zerver/lib/export.py
  zerver/tests/test_import_export.py
Labels: size: XL

#20437 Emoji model requires unique realm and name when activated
  zerver/lib/actions.py
  zerver/migrations/0372_realmemoji_unique_realm_emoji_when_false_deactivated.py
  zerver/models.py
  zerver/tests/test_realm_emoji.py
  zerver/tests/test_transfer.py
Labels: size: L

#20534 tests: Ensure stream senders get a UserMessage row.
  zerver/lib/test_classes.py
  zerver/openapi/curl_param_value_generators.py
  zerver/tests/test_digest.py
  zerver/tests/test_email_notifications.py
  zerver/tests/test_embedded_bot_system.py
  zerver/tests/test_event_queue.py
  zerver/tests/test_link_embed.py
  zerver/tests/test_message_dict.py
  zerver/tests/test_message_edit.py
  zerver/tests/test_message_fetch.py
  zerver/tests/test_message_flags.py
  zerver/tests/test_message_topics.py
  zerver/tests/test_muting_users.py
  zerver/tests/test_push_notifications.py
  zerver/tests/test_reactions.py
  zerver/tests/test_retention.py
  zerver/tests/test_signup.py
  zerver/tests/test_submessage.py
  zerver/tests/test_subs.py
  zerver/tests/test_upload.py
Labels: size: XL

#20537 puppet: Upgrade to Grafana 8.3.2, for CVE-2021-43813.
  puppet/zulip_ops/manifests/profile/grafana.pp
Labels: size: XS

#20539 setup-certbot: Reinstate nginx reload after installation.
  scripts/setup/setup-certbot
Labels: size: S, backport candidate

#20545 test-all: Call documentation tests again.
  tools/test-all
Labels: size: XS

#20548 message_controls: Inherit visibility from `.message_failed`.
  static/styles/zulip.css
Labels: size: XS

#20549 lint: Enforce consistent style of using transaction.atomic decorator.
  confirmation/migrations/0009_confirmation_expiry_date_backfill.py
  tools/linter_lib/custom_check.py
Labels: size: S

#20547 tests: Check more tables for user exports.
  zerver/tests/test_import_export.py
Labels: size: XL

#20554 portico: Update designer job description.
  templates/corporate/jobs.html
Labels: size: M

#20555 ifttt: Ensure topic and body are strings, and not dicts / arrays.
  zerver/webhooks/ifttt/fixtures/invalid_payload_with_dict_content.json
  zerver/webhooks/ifttt/fixtures/invalid_payload_with_dict_topic.json
  zerver/webhooks/ifttt/tests.py
  zerver/webhooks/ifttt/view.py
Labels: size: M

#20557 video_calls: Drop VIDEO_ZOOM_TESTING_ configurations.
  zerver/views/video_calls.py
  zproject/default_settings.py
Labels: size: S

#20568 developer docs: Tweak ToS for push notifications wording.
  docs/production/mobile-push-notifications.md
Labels: size: S

#20567 api: Fix feature level 107 in the API change log.
  templates/zerver/api/changelog.md
Labels: size: XS

#20569 Work around 320-character limit on To addresses
  zerver/lib/send_email.py
  zerver/tests/test_send_email.py
Labels: size: XL

#20570 send_email: Don't abort on an EmailNotDeliveredException.
  zerver/lib/send_email.py
Labels: size: S

#20571 Add support for sending custom emails to self-hoster contacts.
  templates/zerver/emails/custom_email_base.pre.html
  zerver/lib/send_email.py
  zerver/management/commands/send_custom_email.py
  zerver/tests/test_email_notifications.py
Labels: size: L

#20572 puppeteer: Fix edit bot form test flake.
  frontend_tests/puppeteer_tests/settings.ts
Labels: size: S

#20586 Use `transaction.atomic` in `do_create_user` and `do_change_user_role`.
  zerver/lib/actions.py
Labels: size: XL

#20594 mypy: Use object type for checker return values.
  zerver/tests/test_import_export.py
Labels: size: M

#20597 setup-advanced: Remove misleading python3 symlink suggestion
  docs/development/setup-advanced.md
Labels: size: XS

#20598 mypy: Fix content types.
  zerver/tests/test_import_export.py
Labels: size: S

#20591 install: Try apt-get update if the Ubuntu universe check fails
  scripts/lib/install
Labels: size: S

#20601 Manipulate directories more safely in export commands
  zerver/lib/export.py
  zerver/management/commands/export_single_user.py
Labels: size: M

#20603 test_classes: Type kwargs for client_get and friends
  zerver/lib/test_classes.py
  zerver/lib/test_helpers.py
  zerver/openapi/openapi.py
  zerver/tests/test_muting_topics.py
  zerver/tests/test_push_notifications.py
  zerver/webhooks/bitbucket2/tests.py
Labels: size: XL

#20589 production: Create stream in an atomic transaction.
  zerver/lib/streams.py
Labels: bug, area: production, priority: high, size: L

#20619 test-documentation: Suppress Unicode Private Use Area validator warning.
  tools/documentation.vnufilter
Labels: size: XS

#20631 Doc: fix removed repeated words
  docs/subsystems/release-checklist.md
Labels: size: XS

#20634 Fix:Fixed function name
  static/shared/js/fenced_code.js
Labels: size: XS

#20646 Minor puppet supervisor cleanups
  puppet/zulip/manifests/supervisor.pp
Labels: size: M

#20627 performance: Optimize send_subscription_add_events.
  zerver/lib/actions.py
Labels: size: M

#20628 Doc: Fix typo in documentation
  docs/subsystems/client.md
  static/styles/zulip.css
Labels: size: S

#19742 webhooks/jira: Ignore payloads without an explicit event type.
  zerver/decorator.py
  zerver/lib/exceptions.py
  zerver/webhooks/bitbucket2/view.py
  zerver/webhooks/github/view.py
  zerver/webhooks/jira/fixtures/example_anomalous_payload.json
  zerver/webhooks/jira/tests.py
  zerver/webhooks/jira/view.py
  zproject/computed_settings.py
Labels: size: XL

#20608 Use functional parameter destructuring for `opts` in reactions.js
  static/js/reactions.js
Labels: size: L

#20206 invitations: Check invitation from a now-deactivated user.
  zerver/lib/actions.py
  zerver/tests/test_signup.py
Labels: size: M

#20652 settings: Fix code for special case of theme settings subsection.
  static/js/settings_org.js
Labels: size: XS

#20653 requirements: Upgrade Python requirements
  requirements/dev.txt
  requirements/docs.txt
  requirements/mypy.txt
  requirements/prod.txt
  version.py
Labels: size: XL

#20617 Display todo checkboxes properly.
  static/js/todo_widget.js
Labels: size: S

#20651 Fix:removed unnecessary comprehension
  zerver/lib/webhooks/common.py
Labels: size: XS

#20657 Fix:Refractored code and fixed a typo in comment
  static/js/composebox_typeahead.js
Labels: size: M

#20611 tests: Improve testing helper event schema for `update_message`.
  zerver/lib/event_schema.py
Labels: size: M

#20654 install-yarn: Use test -ef in case /srv is a symlink
  puppet/zulip_ops/manifests/profile/postgresql.pp
  scripts/lib/install-yarn
Labels: size: XS

#20665 help: Document that linkifiers use re2.
  templates/zerver/help/add-a-custom-linkifier.md
Labels: area: documentation (user), area: settings (admin/org), size: S, UX, area: markdown (linkifiers)

#20661 remote_server: Improve uuid validation at the server/register endpoint.
  zerver/tests/test_push_notifications.py
  zilencer/views.py
Labels: size: S
