Repository zulip/zulip, pull requests merged in 2021-09, with the labels that each got.

#19650 upgrade-zulip-from-git: Run git fetch with --prune
  scripts/lib/upgrade-zulip-from-git
Labels: size: XS

#19660 [4.x] upgrade-zulip-from-git: Run git fetch with --prune
  scripts/lib/upgrade-zulip-from-git
Labels: size: XS

#19666 queue_processors: Include queue name in the timeout exception.
  zerver/tests/test_queue_worker.py
  zerver/worker/queue_processors.py
Labels: size: S

#19665 notifications: Add safeties to prevent incorrect notifications.
  zerver/lib/email_notifications.py
  zerver/lib/push_notifications.py
Labels: size: S

#19669 push_notifications: Remove redundant APNs retry loop
  zerver/lib/push_notifications.py
  zerver/tests/test_push_notifications.py
Labels: area: mobile, size: XL

#19603 help_docs: Fix improper indentation for ordered lists.
  static/styles/portico/markdown.css
  templates/zerver/help/saml-authentication.md
Labels: size: S

#19400 minor: Refactor CSS for markdown headings.
  static/styles/rendered_markdown.css
Labels: area: markdown, size: M

#19683 login_to_access: Rename module to `spectators`.
  frontend_tests/node_tests/reactions.js
  static/js/compose_actions.js
  static/js/hashchange.js
  static/js/reactions.js
  static/js/spectators.js
  tools/test-js-with-node
Labels: size: S

#19676 settings: Fix live update of notification sound dropdown.
  static/js/settings_notifications.js
Labels: size: XS

#19678 recent_topics: Set focus to filter button after click.
  static/js/click_handlers.js
  static/js/recent_topics_ui.js
Labels: size: XS

#18827 compose: Make the route of message sending through drafts.
  frontend_tests/node_tests/compose.js
  frontend_tests/node_tests/echo.js
  frontend_tests/puppeteer_tests/drafts.ts
  static/js/compose.js
  static/js/drafts.js
  static/js/echo.js
Labels: area: compose, priority: high, size: L

#19684 message_edit: Fix bug when multiple message edit forms are opened.
  static/js/message_edit.js
Labels: bug, area: message-editing, size: XS

#19686 docs: Inline code spans are not blocks
  templates/zerver/help/code-blocks.md
  templates/zerver/help/format-your-message-using-markdown.md
  zerver/lib/markdown/__init__.py
Labels: size: S

#19634 stream settings: Make right pannel title larger.
  static/js/stream_settings_ui.js
  static/styles/subscriptions.css
Labels: size: S

#19415 Add setter and test for realm_owner
  zerver/models.py
  zerver/tests/test_users.py
Labels: size: M

#19692 Add documentation for AzureAD SAML for Zulip Cloud
  static/images/help/azuread_saml_attrs.png
  templates/zerver/help/saml-authentication.md
Labels: size: L

#15240 drafts: Save stream_id along with stream names for drafts.
  frontend_tests/node_tests/drafts.js
  static/js/drafts.js
  static/templates/draft.hbs
Labels: size: M

#19694 docs: Update links for zulip-mobile branch rename
  docs/development/using.md
  static/shared/README.md
Labels: size: XS

#19688 recent_topics: Handle no rows case on `r` keypress.
  static/js/recent_topics_ui.js
Labels: size: S

#19696 models: Make realm.name no longer nullable.
  zerver/migrations/0345_alter_realm_name.py
  zerver/models.py
Labels: size: S

#19516 Whitelist all of HTML spec safelisted schemes.
  zerver/lib/markdown/__init__.py
Labels: size: M

#19689 authentication: Fix placeholder realms for redirects.
  zerver/lib/actions.py
Labels: bug, area: authentication, priority: high, size: XS

#8179 Improve Vagrant troubleshooting.
  Vagrantfile
Labels: size: S

#19611 Rename system group examples and restrict mentioning system user groups.
  zerver/lib/mention.py
  zerver/tests/test_email_notifications.py
  zerver/tests/test_markdown.py
Labels: size: L

#19701 settings: Move check_settings_values to user_settings.py.
  zerver/lib/validator.py
  zerver/views/realm.py
  zerver/views/user_settings.py
Labels: size: L

#19704 Vagrantfile: Fix typo.
  Vagrantfile
Labels: size: XS

#19707 puppeteer: remove test_not_delete_draft_on_sending().
  frontend_tests/puppeteer_tests/drafts.ts
Labels: size: S

#19706 name_restrictions: Reserve ‘mg’ and ‘front-mail’
  zerver/lib/name_restrictions.py
Labels: size: XS

#19245 help: add documentation for Keycloak as SAML identity provider
  docs/production/authentication-methods.md
  templates/zerver/help/saml-authentication.md
  tools/linter_lib/custom_check.py
Labels: size: XL

#19511 node_tests: Run tests parallelly.
  .github/workflows/zulip-ci.yml
  tools/test-js-with-node
Labels: area: testing-infrastructure, priority: high, size: M

#19576 Complete custom email notification batching period feature.
  static/js/settings.js
  static/js/settings_config.ts
  static/js/settings_notifications.js
  static/templates/settings/notification_settings.hbs
Labels: size: L

#19703 docs: Indicate latest Zulip version in installation and upgrade docs.
  docs/conf.py
  docs/production/install.md
  docs/production/upgrade-or-modify.md
Labels: area: documentation (production), size: S

#19716 [4.x] docs: Migrate from recommonmark to MyST-Parser
  docs/conf.py
  docs/development/request-remote.md
  docs/development/setup-advanced.md
  docs/development/setup-vagrant.md
  docs/git/troubleshooting.md
  docs/production/authentication-methods.md
  docs/production/email-gateway.md
  docs/production/expensive-migrations.md
  docs/production/install-existing-server.md
  docs/production/install.md
  docs/production/maintain-secure-upgrade.md
  docs/production/multiple-organizations.md
  docs/production/password-strength.md
  docs/production/troubleshooting.md
  docs/production/upgrade-or-modify.md
  docs/subsystems/performance.md
  docs/testing/linters.md
  docs/testing/manual-testing.md
  docs/translating/translating.md
  requirements/dev.txt
  requirements/docs.in
  requirements/docs.txt
  version.py
Labels: size: XL

#19718 populate_db: Fix naive datetime RuntimeWarning
  zilencer/management/commands/populate_db.py
Labels: size: XS

#19725 Restructure Personal settings > notifications section.
  static/js/settings_config.ts
  static/templates/settings/notification_settings.hbs
Labels: size: L

#19724 Fix alignment of x button in image view menu
  static/styles/lightbox.css
Labels: size: XS

#19736 help: Update notification related help pages as per new UI.
  templates/zerver/help/change-notification-sound.md
  templates/zerver/help/configure-message-notification-emails.md
  templates/zerver/help/disable-new-login-emails.md
  templates/zerver/help/test-mobile-notifications.md
Labels: size: S

#19722 test-js-with-puppeteer: Remove bogus CHROMIUM_EXECUTABLE variable
  tools/test-js-with-puppeteer
Labels: size: XS

#19723 tsconfig: Enable noImplicitOverride
  static/js/blueslip.ts
  tsconfig.json
Labels: size: XS

#19749 settings_overlay: Change privacy icon to a lock
  static/templates/settings_overlay.hbs
Labels: area: settings (user), size: XS

#19750 settings: Use correct object in notification settings template.
  static/templates/settings/notification_settings.hbs
Labels: size: XS

#19746 Vagrantfile: Remove workarounds for ancient Vagrant bugs
  Vagrantfile
Labels: size: M

#19747 Vagrantfile: Move inline provision script to a separate file
  Vagrantfile
  tools/setup/vagrant-provision
Labels: size: XL

#19743 docs: Fix Entity ID values in instructions in saml-authentication.md.
  templates/zerver/help/saml-authentication.md
Labels: size: S

#16649 Upgrade to Webpack 5
  package.json
  tools/debug-require-webpack-plugin.ts
  tools/debug-require.js
  version.py
  webpack.config.ts
  yarn.lock
Labels: size: XL

#19755 saml: Set requestedAuthnContext to False in prod_settings_template.
  zproject/prod_settings_template.py
Labels: size: S

#19753 settings: Fix the sticky behavior of saving indicator.
  static/js/settings_ui.js
Labels: size: XS

#19757 help: Rename about-streams-and-topics to streams-and-topics.
  templates/zerver/features.html
  templates/zerver/for-companies.html
  templates/zerver/for-education.html
  templates/zerver/for-events.html
  templates/zerver/for-research.html
  templates/zerver/help/browse-and-subscribe-to-streams.md
  templates/zerver/help/getting-started-with-zulip.md
  templates/zerver/help/getting-your-organization-started-with-zulip.md
  templates/zerver/help/include/sidebar_index.md
  templates/zerver/help/private-messages.md
  templates/zerver/help/reading-strategies.md
  templates/zerver/help/resolve-a-topic.md
  templates/zerver/help/streams-and-topics.md
  zerver/lib/onboarding.py
  zerver/lib/test_helpers.py
  zproject/urls.py
Labels: size: M

#19763 stream settings: Add whitespace before disabled attribute.
  static/templates/stream_settings/stream_settings_checkbox.hbs
Labels: bug, area: stream settings, size: XS

#19714 user docs: Document message notification email custom batching.
  static/templates/settings/notification_settings.hbs
  templates/zerver/help/configure-message-notification-emails.md
Labels: size: L

#19584 docs: Adjust phrasing of "From your desktop, click on the gear...".
  templates/zerver/help/include/go-to-stream-via-all-streams.md
  zerver/lib/markdown/help_relative_links.py
  zerver/lib/markdown/help_settings_links.py
Labels: size: S

#18965 refactor some signup tests
  zerver/tests/test_signup.py
Labels: size: L

#19758 user docs: Add a bundle of "getting stated" user docs.
  static/styles/portico/markdown.css
  templates/zerver/help/finding-a-topic-to-read.md
  templates/zerver/help/format-your-message-using-markdown.md
  templates/zerver/help/getting-started-with-zulip.md
  templates/zerver/help/include/compose-and-send-message.md
  templates/zerver/help/include/how-to-start-a-new-topic.md
  templates/zerver/help/include/left-sidebar-topics.md
  templates/zerver/help/include/messaging-tips.md
  templates/zerver/help/include/reading-pms.md
  templates/zerver/help/include/reading-topics.md
  templates/zerver/help/include/recent-topics.md
  templates/zerver/help/include/replying-to-messages.md
  templates/zerver/help/include/set-up-your-account.md
  templates/zerver/help/include/sidebar_index.md
  templates/zerver/help/include/starting-a-new-private-thread.md
  templates/zerver/help/include/streams-and-topics.md
  templates/zerver/help/include/when-to-start-a-new-topic.md
  templates/zerver/help/messaging-tips.md
  templates/zerver/help/open-the-compose-box.md
  templates/zerver/help/reading-pms.md
  templates/zerver/help/reading-strategies.md
  templates/zerver/help/reading-topics.md
  templates/zerver/help/recent-topics.md
  templates/zerver/help/replying-to-messages.md
  templates/zerver/help/review-your-settings.md
  templates/zerver/help/set-up-your-account.md
  templates/zerver/help/starting-a-new-private-thread.md
  templates/zerver/help/starting-a-new-topic.md
  templates/zerver/help/streams-and-topics.md
  zerver/lib/markdown/tabbed_sections.py
Labels: size: XL, has conflicts

#19772 user_groups: Hide system user groups from UI.
  frontend_tests/node_tests/composebox_typeahead.js
  frontend_tests/node_tests/user_groups.js
  static/js/user_groups.ts
Labels: size: S

#19771 LDAP: Support alternative attributes to userAccountControl for deactivating users.
  docs/production/authentication-methods.md
  zerver/tests/test_auth_backends.py
  zproject/backends.py
  zproject/prod_settings_template.py
Labels: area: authentication, size: XL

#19766 Guide on using Zulip for a class
  templates/zerver/help/include/sidebar_index.md
  templates/zerver/help/using-zulip-for-a-class.md
Labels: size: L

#19779 favicon: Fix embedded number font for Webpack 5 asset modules
  static/js/favicon.js
Labels: size: XS

#19787 docs: Recommend Docker for all macOS users
  docs/development/setup-vagrant.md
Labels: size: M

#19762 find_team: Send one email per email address, not per organization.
  templates/zerver/emails/find_team.source.html
  templates/zerver/emails/find_team.subject.txt
  templates/zerver/emails/find_team.txt
  version.py
  zerver/tests/test_signup.py
  zerver/views/registration.py
Labels: priority: high, area: emails, size: L

#19795 user docs: Add documentation for configuring new user defaults.
  static/templates/settings/organization_user_settings_defaults.hbs
  templates/zerver/help/configure-default-new-user-settings.md
  templates/zerver/help/customize-settings-for-new-users.md
  templates/zerver/help/include/customize-settings-for-new-users.md
  templates/zerver/help/include/sidebar_index.md
  zerver/lib/markdown/help_settings_links.py
  zerver/openapi/zulip.yaml
Labels: size: L

#19807 user docs: Fix missing tab name on /help/getting-your-organization-started-with-zulip.
  zerver/lib/markdown/tabbed_sections.py
Labels: size: XS

#19814 [4.x] Remove broken legacy-os test
  .github/workflows/legacy-os.yml
Labels: size: S

#19800 webpack: Increase Node.js heap size on low-memory systems
  tools/webpack
Labels: size: S

#19813 help_docs: Reorganize notification docs under three umbrella pages.
  templates/zerver/help/add-an-alert-word.md
  templates/zerver/help/change-notification-sound.md
  templates/zerver/help/configure-default-new-user-settings.md
  templates/zerver/help/desktop-notifications.md
  templates/zerver/help/disable-new-login-emails.md
  templates/zerver/help/email-notifications.md
  templates/zerver/help/hide-message-content-in-emails.md
  templates/zerver/help/include/sidebar_index.md
  templates/zerver/help/mobile-notifications.md
  templates/zerver/help/mute-a-stream.md
  templates/zerver/help/mute-a-topic.md
  templates/zerver/help/pm-mention-alert-notifications.md
  templates/zerver/help/search-for-messages.md
  templates/zerver/help/stream-notifications.md
  templates/zerver/help/test-mobile-notifications.md
  zerver/lib/test_helpers.py
  zerver/openapi/zulip.yaml
  zproject/urls.py
Labels: size: XL

#19809 settings: Migrate twenty_four_hour_time setting to RealmUserDefault.
  frontend_tests/node_tests/dispatch.js
  frontend_tests/node_tests/lib/events.js
  frontend_tests/node_tests/settings_org.js
  static/js/admin.js
  static/js/server_events_dispatch.js
  static/js/settings_display.js
  static/js/settings_org.js
  static/templates/settings/display_settings.hbs
  static/templates/settings/organization_settings_admin.hbs
  templates/zerver/api/changelog.md
  version.py
  zerver/lib/create_user.py
  zerver/lib/event_schema.py
  zerver/migrations/0352_migrate_twenty_four_hour_time_to_realmuserdefault.py
  zerver/migrations/0353_remove_realm_default_twenty_four_hour_time.py
  zerver/models.py
  zerver/openapi/zulip.yaml
  zerver/tests/test_events.py
  zerver/tests/test_home.py
  zerver/tests/test_realm.py
  zerver/tests/test_signup.py
  zerver/views/realm.py
Labels: size: XL

#19784 outgoing webhooks: Fix inconsistencies with Slack's API.
  templates/zerver/api/outgoing-webhooks.md
  zerver/lib/outgoing_webhook.py
  zerver/tests/test_outgoing_webhook_interfaces.py
Labels: area: integrations, size: L

#19823 setup_venv: Skip virtualenv’s automatic download of setuptools
  scripts/lib/setup_venv.py
Labels: size: XS

#19825 [4.x] setup_venv: Skip virtualenv’s automatic download of setuptools
  scripts/lib/setup_venv.py
Labels: size: XS

#19828 topics: Fix translation issue with resolve topic notifications.
  zerver/lib/actions.py
Labels: size: S

#19816 install-node: Stop using NVM
  docs/subsystems/dependencies.md
  scripts/lib/install-node
Labels: size: XL

#19836 find_accounts: Thank the user for their request in the email.
  templates/zerver/emails/find_team.source.html
  templates/zerver/emails/find_team.txt
Labels: size: XS

#19818 markdown: Document built-in preprocessor priorities.
  zerver/lib/markdown/preprocessor_priorities.py
Labels: size: XS

#19805 tooltip: Download tooltip on file.
  frontend_tests/node_tests/util.js
  static/js/util.js
Labels: size: S

#19826 process_fts_updates: Fix docker-zulip support.
  puppet/zulip/files/postgresql/process_fts_updates
Labels: size: M

#19851 Revert "validator: Add generic check_or."
  zerver/lib/validator.py
  zerver/tests/test_decorators.py
Labels: size: M

#19847 request_notes: Set the realm appropriately for the root subdomain.
  zerver/middleware.py
  zerver/tests/test_decorators.py
Labels: size: L

#19819 compose: Collapse compose-box after sending message.
  static/js/compose.js
  static/js/echo.js
Labels: size: S

#19729 UX improvement: display "user not found"
  static/styles/compose.css
Labels: size: XS

#19831 rendered_markdown: Improve headings.
  static/styles/rendered_markdown.css
Labels: area: markdown, size: S

#17853 push_notifs: Log the number of devices notification was sent to.
  zerver/lib/push_notifications.py
  zerver/lib/remote_server.py
  zerver/tests/test_push_notifications.py
  zilencer/views.py
Labels: size: L, has conflicts

#19867 settings: Fix bug of empty subsection heading being visible.
  static/js/settings_notifications.js
  static/js/settings_org.js
Labels: size: S
