Repository zulip/zulip, pull requests merged in 2021-02, with the labels that each got.

#17167 docs: Fix typo in setup-advanced.md
  docs/development/setup-advanced.md
Labels: size: XS

#17188 version: Correct API feature level.
  version.py
Labels: size: XS

#17186 release-checklist: Push dev tags to zulip-internal.git too
  docs/subsystems/release-checklist.md
Labels: size: XS

#17197 push-to-pull-request: Wait for GitHub background update before merge
  tools/push-to-pull-request
Labels: size: S

#17201 blueslip: Pass through the return value in measure_time
  frontend_tests/zjsunit/zblueslip.js
  static/js/blueslip.js
  static/js/stream_create.js
  static/js/subs.js
Labels: size: S

#17199 node_tests: Fix #comepose-textarea typo
  frontend_tests/node_tests/upload.js
Labels: size: S

#17206 node tests: Remove unnecessary zjquery stubs.
  frontend_tests/node_tests/recent_topics.js
Labels: size: M

#17207 docs: Fix typo in 'caching in zulip'.
  docs/subsystems/caching.md
Labels: size: XS

#17191 help: Clarify the number of invites one can send
  templates/zerver/help/invite-new-users.md
Labels: size: S

#17171 bitbucket webhook: Fully deprecate username field.
  zerver/webhooks/bitbucket2/fixtures/commit_comment_created.json
  zerver/webhooks/bitbucket2/fixtures/commit_status_changed.json
  zerver/webhooks/bitbucket2/fixtures/force_push.json
  zerver/webhooks/bitbucket2/fixtures/fork.json
  zerver/webhooks/bitbucket2/fixtures/issue_commented.json
  zerver/webhooks/bitbucket2/fixtures/issue_created.json
  zerver/webhooks/bitbucket2/fixtures/issue_updated.json
  zerver/webhooks/bitbucket2/fixtures/more_than_one_push_event.json
  zerver/webhooks/bitbucket2/fixtures/pull_request_approved_or_unapproved.json
  zerver/webhooks/bitbucket2/fixtures/pull_request_comment_action.json
  zerver/webhooks/bitbucket2/fixtures/pull_request_created_or_updated.json
  zerver/webhooks/bitbucket2/fixtures/pull_request_created_or_updated_without_username.json
  zerver/webhooks/bitbucket2/fixtures/pull_request_fulfilled_or_rejected.json
  zerver/webhooks/bitbucket2/fixtures/push.json
  zerver/webhooks/bitbucket2/fixtures/push_commits_above_limit.json
  zerver/webhooks/bitbucket2/fixtures/push_more_than_one_tag.json
  zerver/webhooks/bitbucket2/fixtures/push_multiple_committers.json
  zerver/webhooks/bitbucket2/fixtures/push_multiple_committers_with_others.json
  zerver/webhooks/bitbucket2/fixtures/push_one_tag.json
  zerver/webhooks/bitbucket2/fixtures/push_remove_tag.json
  zerver/webhooks/bitbucket2/fixtures/push_without_changes.json
  zerver/webhooks/bitbucket2/fixtures/remove_branch.json
  zerver/webhooks/bitbucket2/fixtures/repo_updated.json
  zerver/webhooks/bitbucket2/tests.py
  zerver/webhooks/bitbucket2/view.py
Labels: size: XL

#17213 markdown: Explode config dict
  zerver/lib/markdown/__init__.py
Labels: size: M

#17143 docs: conf.py: Add zulip logo to the sidebar.
  docs/conf.py
  docs/images/zulip-logo.svg
Labels: size: S

#16451 dependencies : Removed moment.js and added date-fns
  frontend_tests/node_tests/people.js
  frontend_tests/node_tests/timerender.js
  package.json
  static/.gitignore
  static/js/composebox_typeahead.js
  static/js/markdown.js
  static/js/people.js
  static/js/popovers.js
  static/js/portico/signup.js
  static/js/reminder.js
  static/js/rendered_markdown.js
  static/js/settings.js
  static/js/settings_data.js
  static/js/timerender.js
  tools/lib/provision_inner.py
  tools/setup/build_timezone_values
  tools/update-prod-static
  version.py
  yarn.lock
Labels: area: dependencies, size: XL

#17217 node_tests: Fixed failing rendered_markdown tests.
  frontend_tests/node_tests/rendered_markdown.js
Labels: size: XS

#17112 users: Rename access_user_by_id to validate_and_access_user.
  zerver/lib/users.py
  zerver/tests/test_users.py
  zerver/views/users.py
Labels: size: L

#17221 subscription_members: Make the help text more clear.
  static/templates/subscription_members.hbs
Labels: size: XS

#17222 components: Allow passing labels as HTML (but explicitly)
  frontend_tests/node_tests/components.js
  static/js/components.js
  static/js/subs.js
Labels: bug, size: M

#17230 actions: Sort available_notification_sounds
  zerver/lib/actions.py
Labels: size: XS

#17219 drafts: Fix racy computation that gets current time twice
  static/js/drafts.js
Labels: size: XS

#17220 dependencies: Remove XDate
  frontend_tests/node_tests/buddy_data.js
  frontend_tests/node_tests/compose.js
  frontend_tests/node_tests/drafts.js
  frontend_tests/node_tests/echo.js
  frontend_tests/node_tests/people.js
  frontend_tests/node_tests/presence.js
  frontend_tests/node_tests/settings_muting.js
  frontend_tests/node_tests/timerender.js
  package.json
  static/js/archive.js
  static/js/attachments_ui.js
  static/js/buddy_data.js
  static/js/drafts.js
  static/js/echo.js
  static/js/floating_recipient_bar.js
  static/js/local_message.js
  static/js/message_edit.js
  static/js/message_edit_history.js
  static/js/message_list_view.js
  static/js/muting.js
  static/js/presence.js
  static/js/recent_topics.js
  static/js/settings_exports.js
  static/js/timerender.js
  static/js/unread_ui.js
  version.py
  yarn.lock
Labels: size: XL

#17246 minor: Clean up code formatting for do_create_user.
  zerver/lib/actions.py
Labels: size: L

#17252 ci: Port xenial-legacy check to GitHub Actions
  .circleci/config.yml
  .github/workflows/legacy-os.yml
Labels: size: M

#17242 Tooltip: edited tooltip string to add consistency in static/js/ui.js.
  static/js/ui.js
Labels: size: XS

#17236 api docs: Fix non-rendering response parameter data types.
  zerver/lib/markdown/api_return_values_table_generator.py
Labels: size: XS

#17218 api docs: Removed duplicacy in CSS.
  static/styles/portico/portico.css
  zerver/lib/markdown/api_arguments_table_generator.py
  zerver/lib/markdown/api_return_values_table_generator.py
Labels: size: S

#17261 people: Modernize CommonJS reference in comment
  static/js/people.js
Labels: size: S

#17266 requirements: Upgrade Python requirements
  requirements/dev.in
  requirements/dev.txt
  requirements/docs.txt
  requirements/pip.txt
  requirements/prod.txt
  requirements/thumbor-dev.txt
  requirements/thumbor.in
  requirements/thumbor.txt
  version.py
Labels: size: XL

#17264 slugs: Fix regex for legacy stream slugs.
  frontend_tests/node_tests/stream_data.js
  static/js/stream_data.js
Labels: size: S

#17269 dependencies: Upgrade JavaScript dependencies
  package.json
  version.py
  yarn.lock
Labels: size: XL

#17279 [3.x] Remove HipChat link from installation guide
  docs/production/install.md
Labels: size: XS

#17055 settings: Move LDAP configuration together, in the same order.
  zproject/default_settings.py
  zproject/prod_settings_template.py
Labels: size: S

#17282 python: Fix string literal concatenation mistakes
  analytics/management/commands/update_analytics_counts.py
  zerver/middleware.py
  zerver/webhooks/pingdom/view.py
Labels: size: S

#17283 puppet: Set APT::Periodic::Unattended-Upgrade in apt config.
  puppet/zulip_ops/files/apt/apt.conf.d/02periodic
Labels: size: XS

#17278 [3.x] requirements: Upgrade Python requirements
  requirements/common.in
  requirements/dev.in
  requirements/dev.txt
  requirements/docs.txt
  requirements/mypy.txt
  requirements/pip.in
  requirements/pip.txt
  requirements/prod.txt
  requirements/thumbor-dev.txt
  requirements/thumbor.txt
  version.py
Labels: size: XL

#17289 docs: Document Black and isort
  README.md
  docs/contributing/code-style.md
  docs/testing/linters.md
Labels: size: M

#17294 minor: Suggest with_field instead of override for non-functions.
  frontend_tests/zjsunit/namespace.js
Labels: size: XS

#17295 node tests: Use override for snapshot_message.
  frontend_tests/node_tests/drafts.js
Labels: size: M

#17287 ui: Fix detection of narrow window.
  static/js/message_viewport.js
Labels: area: mobile web, bug, priority: blocker, size: XS

#17296 node tests: Use override in echo.js.
  frontend_tests/node_tests/echo.js
Labels: size: S

#17291 docs: Add a performance design document.
  docs/production/requirements.md
  docs/subsystems/index.rst
  docs/subsystems/performance.md
Labels: size: XL

#17302 shared: Format our one Flow file with Prettier
  static/shared/js/typing_status.js.flow
  tools/lint
Labels: size: S

#16950 event_queue: Remove internal fields being leaked to the API.
  zerver/openapi/zulip.yaml
  zerver/tests/test_event_queue.py
  zerver/tornado/event_queue.py
Labels: area: api, bug, priority: high, size: XL

#16999 api: Add REST API endpoint for looking up a user by email
  templates/zerver/api/changelog.md
  templates/zerver/api/get-user-by-email.md
  templates/zerver/api/get-users.md
  templates/zerver/help/include/rest-endpoints.md
  version.py
  zerver/openapi/python_examples.py
  zerver/openapi/zulip.yaml
  zerver/tests/test_openapi.py
  zerver/tests/test_users.py
  zerver/views/users.py
  zproject/urls.py
Labels: size: XL

#16883 api docs: Improve readability of code and response blocks.
  static/styles/portico/markdown.css
Labels: size: XS

#17285 message-view: Increase spacing for lists coming after paragraphs.
  static/styles/rendered_markdown.css
Labels: size: XS

#17323 code cleanup: Clean up subs.js code (including tests).
  frontend_tests/node_tests/subs.js
  static/js/subs.js
Labels: size: XL

#17324 docs: Minor edits to scalability article.
  docs/subsystems/performance.md
Labels: size: S

#17317 api docs: Expand condition for deprecated fields.
  zerver/lib/markdown/api_arguments_table_generator.py
  zerver/lib/markdown/api_return_values_table_generator.py
  zerver/openapi/openapi.py
Labels: size: S

#17326 docs: Add minor tweaks to performance doc.
  docs/subsystems/performance.md
Labels: size: S

#17327 desktop-app-install-guide: Update for APT repository move
  templates/zerver/help/desktop-app-install-guide.md
Labels: size: S

#17331 docs: Mention a way to check the running vboxadd version
  docs/development/setup-vagrant.md
Labels: size: S

#17325 puppet: Configure nginx for long keep-alives when behind a loadbalancer.
  puppet/zulip/files/nginx/zulip-include-app.d/keepalive-loadbalancer.conf
  puppet/zulip/manifests/app_frontend_base.pp
Labels: size: S

#17328 wsl_docs: Inform user how to uninstall WSL.
  docs/development/setup-advanced.md
Labels: size: XS

#17335 iptables: Limit smokescreen port 4750, add camo port.
  puppet/zulip_ops/templates/iptables/rules.v4.erb
Labels: size: XS

#16806 notifications: Fix composebox notification escaping
  static/js/notifications.js
  tools/lib/capitalization.py
Labels: size: S

#17337 docs: Writing tweaks to performance.md.
  docs/subsystems/performance.md
Labels: size: M

#17338 lint: Remove custom whitespace rules already enforced by Black
  tools/linter_lib/custom_check.py
Labels: size: S

#17344 puppeteer: Make subscribe/unsubscribe test more robust.
  frontend_tests/puppeteer_tests/04-subscriptions.js
Labels: size: M

#17352 node tests: Use override in buddy tests.
  frontend_tests/node_tests/buddy_data.js
  frontend_tests/node_tests/buddy_list.js
Labels: size: L

#17354 docs: Update author protocol section of the code-reviewing docs.
  docs/contributing/code-reviewing.md
Labels: size: M

#17366 node tests: Clean up pm_list
  frontend_tests/node_tests/pm_list.js
Labels: size: XL

#17368 node tests: Prevent zjquery leaks in activity tests.
  frontend_tests/node_tests/activity.js
Labels: size: XL

#17376 Improve zjquery error message when users uses tag as a selector.
  frontend_tests/zjsunit/zjquery.js
Labels: size: M

#17380 node_tests: Fix misspelled pm_conversation global
  frontend_tests/node_tests/message_store.js
Labels: size: S

#17381 zjsunit: Use clear_zulip_refs as the main way to undo zrequire
  frontend_tests/zjsunit/index.js
  frontend_tests/zjsunit/namespace.js
Labels: size: M

#17358 puppet: Remove puppet_ops configuration for separate loadbalancer host.
  docs/production/deployment.md
  puppet/zulip_ops/files/nginx/sites-available/loadbalancer
  puppet/zulip_ops/manifests/profile/loadbalancer.pp
  puppet/zulip_ops/manifests/profile/nagios.pp
  puppet/zulip_ops/templates/nagios3/hosts.cfg.template.erb
Labels: size: XL

#17356 js: Don't escape "Just now" in timerenderer
  static/js/buddy_data.js
Labels: size: XS

#17382 node_tests: Don’t read page_params from deprecated global variable.
  .eslintrc.json
  frontend_tests/node_tests/activity.js
  frontend_tests/node_tests/billing_helpers.js
  frontend_tests/node_tests/buddy_data.js
  frontend_tests/node_tests/compose.js
  frontend_tests/node_tests/composebox_typeahead.js
  frontend_tests/node_tests/dispatch.js
  frontend_tests/node_tests/echo.js
  frontend_tests/node_tests/filter.js
  frontend_tests/node_tests/hotkey.js
  frontend_tests/node_tests/markdown.js
  frontend_tests/node_tests/message_edit.js
  frontend_tests/node_tests/message_events.js
  frontend_tests/node_tests/message_list_view.js
  frontend_tests/node_tests/muting.js
  frontend_tests/node_tests/notifications.js
  frontend_tests/node_tests/people.js
  frontend_tests/node_tests/rendered_markdown.js
  frontend_tests/node_tests/search_suggestion.js
  frontend_tests/node_tests/search_suggestion_legacy.js
  frontend_tests/node_tests/settings_bots.js
  frontend_tests/node_tests/settings_data.js
  frontend_tests/node_tests/settings_org.js
  frontend_tests/node_tests/settings_profile_fields.js
  frontend_tests/node_tests/settings_user_groups.js
  frontend_tests/node_tests/stream_data.js
  frontend_tests/node_tests/stream_edit.js
  frontend_tests/node_tests/stream_list.js
  frontend_tests/node_tests/timerender.js
  frontend_tests/node_tests/transmit.js
  frontend_tests/node_tests/typeahead_helper.js
  frontend_tests/node_tests/ui_init.js
  frontend_tests/node_tests/unread.js
  frontend_tests/node_tests/upload.js
  frontend_tests/node_tests/user_events.js
  frontend_tests/node_tests/user_pill.js
Labels: size: XL

#17383 zjsunit: Handle exceptions and missing fields correctly in with_field, with_overrides
  frontend_tests/zjsunit/namespace.js
Labels: size: M

#17385 zerver/openapi/python_examples.py: Fix `message_id` type.
  zerver/openapi/python_examples.py
Labels: size: S

#17378 docs: Fix Markdown for links in the authentication in development doc.
  docs/development/authentication.md
Labels: size: S

#17390 node_tests: Revert wrong conversion of some functions to arrows
  frontend_tests/node_tests/compose_ui.js
  frontend_tests/node_tests/composebox_typeahead.js
Labels: size: S

#17391 dependencies: Upgrade Source Sans Pro font to Source Sans 3
  frontend_tests/node_tests/copy_and_paste.js
  package.json
  static/images/why-zulip/slack-unreads.svg
  static/images/why-zulip/zulip-reply-later.svg
  static/images/why-zulip/zulip-topics.svg
  static/js/bundles/common.js
  static/js/favicon.js
  static/js/stats/stats.js
  static/styles/app_components.css
  static/styles/portico/archive.css
  static/styles/portico/billing.css
  static/styles/portico/landing_page.css
  static/styles/portico/markdown.css
  static/styles/portico/portico.css
  static/styles/portico/portico_signin.css
  static/styles/portico/stats.css
  static/styles/zulip.css
  static/templates/favicon.svg.hbs
  version.py
  yarn.lock
Labels: size: XL

#17374 api docs: Fix id and type fields of events and display them.
  zerver/lib/markdown/api_return_values_table_generator.py
  zerver/openapi/zulip.yaml
Labels: size: XL

#17340 Increase opacity when we hover on the "filter user" on the right-sidebar.
  static/styles/right_sidebar.css
Labels: size: XS

#17389 docs: Added reactivate_realm management command.
  docs/production/management-commands.md
Labels: size: XS

#16789 Fix double-escaping usernames in reaction tooltip
  static/js/reactions.js
Labels: size: S

#17395 ui: Remove warning for unsupported old Zulip desktop app
  .eslintrc.json
  frontend_tests/node_tests/compose.js
  frontend_tests/node_tests/upload.js
  static/js/ui.js
Labels: size: S

#17397 docs: Correct some spelling mistakes and add some missing full stops at end of the sentence.
  docs/contributing/gsoc-ideas.md
Labels: size: S

#17399 composebox_typeahead: Increase max typeahead box size
  static/js/composebox_typeahead.js
Labels: size: XS

#17235 api docs: Fix documentation of update-subscription-settings.
  templates/zerver/api/update-subscription-settings.md
  zerver/openapi/zulip.yaml
Labels: size: L

#17406 puppet: Check in defensive restart-camo cron job.
  puppet/zulip_ops/files/cron.d/camo
  puppet/zulip_ops/manifests/camo.pp
  puppet/zulip_ops/manifests/profile/smokescreen.pp
Labels: size: S

#17121 email: Set an envelope-from which may be different from the From: field.
  corporate/tests/test_stripe.py
  templates/zerver/email.html
  zerver/lib/send_email.py
  zerver/lib/test_classes.py
  zerver/tests/test_email_change.py
  zerver/tests/test_email_notifications.py
  zerver/tests/test_management_commands.py
  zerver/tests/test_realm.py
  zerver/tests/test_signup.py
  zproject/email_backends.py
Labels: size: L

#17223 frontend: Fix right margin in stream description
  static/styles/subscriptions.css
Labels: size: XS

#17359 frontend: Fix shifted user invite copy icon
  static/styles/zulip.css
Labels: area: invitations, bug, size: XS

#17413 api docs: Clarify realm_emoji update event returns all custom emoji.
  zerver/openapi/zulip.yaml
Labels: size: XS

#17404 api docs: Add missing ID fields for event responses.
  zerver/openapi/zulip.yaml
Labels: size: XS

#17400 typeahead: Always rank exact string match first.
  frontend_tests/node_tests/typeahead.js
  static/shared/js/typeahead.js
Labels: size: M

#17414 puppet: Add ksplice uptrack for kernel hotpatches.
  puppet/zulip_ops/manifests/ksplice_uptrack.pp
  puppet/zulip_ops/manifests/profile/base.pp
  puppet/zulip_ops/templates/uptrack/uptrack.conf.erb
  scripts/lib/setup-apt-repo-ksplice
  scripts/setup/ksplice.asc
Labels: size: XL

#17416 dependencies: Upgrade clean-css 5.0.1 to 5.1.0
  package.json
  version.py
  yarn.lock
Labels: size: S

#17418 Revert "stream-ui: Change view from 2-column to 1-column at width 992px."
  static/styles/settings.css
  static/styles/subscriptions.css
Labels: accessibility, area: settings UI, size: XS

#17341 api docs: Fix blank line at end of Code Blocks.
  static/styles/portico/markdown.css
Labels: size: XS

#17316 ci: Notify in zulip when a build fails in GitHub Actions.
  .github/workflows/legacy-os.yml
  .github/workflows/production-suite.yml
  .github/workflows/zulip-ci.yml
  tools/ci/production-build
  tools/ci/send-failure-message
Labels: size: M

#17429 Revert "starred_messages: Add support to unstar all messages in a topic."
  static/js/message_flags.js
  static/js/starred_messages.js
  static/js/stream_popover.js
  static/templates/topic_sidebar_actions.hbs
  static/templates/unstar_messages_modal.hbs
Labels: size: L

#17427 api docs: Sort response keys in /get-events.
  zerver/lib/markdown/api_return_values_table_generator.py
Labels: size: XS
