Repository zulip/zulip, pull requests merged in 2021-05, with the labels that each got.

#17677 UI: Show Zulip Version in the app
  static/images/logo/white-zulip-logo-without-text.svg
  static/js/about_zulip.js
  static/js/gear_menu.js
  static/js/hash_util.js
  static/js/hashchange.js
  static/styles/app_components.css
  static/styles/night_mode.css
  static/styles/zulip.css
  templates/zerver/app/about-zulip.html
  templates/zerver/app/index.html
  templates/zerver/app/navbar.html
  tools/test-js-with-node
  zerver/context_processors.py
  zerver/tests/test_context_processors.py
Labels: release goal, size: XL

#18190 help center: Improved formatting for labels in stream permissions table.
  static/styles/portico/markdown.css
  templates/zerver/help/configure-message-editing-and-deletion.md
  templates/zerver/help/stream-permissions.md
Labels: size: S

#18338 Add support for moderators only stream post policy in frontend.
  frontend_tests/node_tests/compose.js
  static/js/compose.js
  static/js/stream_data.js
  static/templates/subscription_type.hbs
Labels: size: L

#18347 upgrade: Use restart-server unless --skip-puppet is used.
  scripts/lib/upgrade-zulip-stage-2
Labels: size: XS

#18343 giphy: Add just space as a content to fool popover library.
  static/js/giphy.js
Labels: size: XS

#16975 populate_db: removed use of deprecated pointer field
  zilencer/management/commands/populate_db.py
Labels: size: S

#16871 message view: Allow unmute a topic from its recipient bar.
  static/js/click_handlers.js
  static/js/message_events.js
  static/js/message_list.js
  static/js/message_list_view.js
  static/js/muting.js
  static/styles/zulip.css
  static/templates/recipient_row.hbs
Labels: size: L

#18349 invites_modal: Replace modal confirmation text to Confirm.
  static/templates/settings/resend_invite_modal.hbs
  static/templates/settings/revoke_invite_modal.hbs
Labels: size: XS

#18334 install: Install procps, for pgrep.
  puppet/zulip/manifests/profile/base.pp
  puppet/zulip/manifests/profile/rabbitmq.pp
Labels: release goal, size: XS

#18158 frontend: Change 'reply' button label to reflect selected message.
  frontend_tests/node_tests/compose_closed_ui.js
  static/js/compose_closed_ui.js
  static/js/ui_init.js
  static/styles/compose.css
  static/styles/night_mode.css
  static/templates/compose.hbs
Labels: size: XL

#18353 locale: Use `C.UTF-8` rather than `en_US.UTF-8`.
  Vagrantfile
  puppet/zulip/templates/postgresql/13/postgresql.conf.template.erb
  puppet/zulip/templates/postgresql/9.3/postgresql.conf.template.erb
  puppet/zulip/templates/postgresql/9.5/postgresql.conf.template.erb
  puppet/zulip/templates/postgresql/9.6/postgresql.conf.template.erb
  puppet/zulip/templates/uwsgi.ini.template.erb
  scripts/lib/install
  scripts/lib/upgrade-zulip-stage-2
  scripts/setup/create-db.sql
  tools/ci/Dockerfile.template
  tools/setup/dev-vagrant-docker/Dockerfile
  tools/test-install/prepare-base
  tools/test-js-with-puppeteer
Labels: area: production installer, bug, priority: high, release goal, size: L

#18129 avatar: show loading animation while deleting profile picture.
  static/js/avatar.js
Labels: size: S

#18362 presence: Disable live presence updates in larger realms.
  zerver/lib/actions.py
  zerver/tests/test_event_system.py
  zproject/default_settings.py
Labels: size: L

#18364 docs: Fix typos in user docs.
  templates/zerver/help/archive-a-stream.md
  templates/zerver/help/change-your-name.md
  templates/zerver/help/deactivate-or-reactivate-a-user.md
  templates/zerver/help/deactivate-your-account.md
  templates/zerver/help/deactivate-your-organization.md
  templates/zerver/help/delete-a-topic.md
  templates/zerver/help/edit-or-delete-a-message.md
Labels: size: S

#18363 settings_users: Fix the sorting of owner and admin in users list.
  static/js/settings_users.js
Labels: size: S

#18360 docs: Replace legacy roadmap.md with release lifecycle page.
  SECURITY.md
  docs/_templates/layout.html
  docs/overview/index.rst
  docs/overview/release-lifecycle.md
  docs/overview/roadmap.md
  docs/translating/translating.md
  templates/zerver/app/navbar_alerts.html
Labels: release goal, size: XL

#18348 Exclude muted users from more UI parts.
  frontend_tests/node_tests/composebox_typeahead.js
  static/js/composebox_typeahead.js
Labels: size: M

#18044 Needed LDAP group imports for automation
  tools/linter_lib/pyflakes.py
  zproject/prod_settings_template.py
Labels: size: XS

#18272 [WIP] Labels for Arrows on Landing Page
  templates/zerver/hello.html
Labels: size: S

#18365 css: Remove grey styling for day theme compose buttons.
  static/styles/compose.css
  static/styles/night_mode.css
Labels: release goal, size: XS

#18289 User Status options now turn blue on hover while in night mode
  static/styles/user_status.css
Labels: size: XS

#18148 docs: Add link to latest when viewing old changelog.
  docs/overview/changelog.md
Labels: release goal, size: S

#18370 docs: Document Sentry in logging docs.
  docs/subsystems/logging.md
Labels: size: S

#17506 lint: Set repository variable in tools/commit-message-lint.
  tools/commit-message-lint
Labels: size: XS

#18376 recent_topics: Don't rerender which topic_data is unchanged.
  frontend_tests/node_tests/example5.js
  static/js/recent_topics.js
Labels: size: S

#18379 js: Remove some pointless IIFEs
  static/js/click_handlers.js
  static/js/components.js
  static/js/input_pill.js
  static/js/narrow.js
  static/js/popovers.js
  static/js/resize.js
  static/js/settings_user_groups.js
  static/js/subs.js
  static/shared/js/fenced_code.js
Labels: size: XL

#18366 navbar_alerts: Add button to hide "Server Upgrade" alert for 7 days.
  frontend_tests/node_tests/panels.js
  static/js/panels.js
  templates/zerver/app/navbar_alerts.html
Labels: size: L

#18368 apps: Link to macOS Apple silicon native build
  static/js/portico/landing-page.js
  static/styles/portico/landing_page.css
  templates/zerver/apps.html
  zerver/lib/github.py
Labels: size: S

#18383 requirements: Remove Thumbor
  .eslintignore
  .github/workflows/production-suite.yml
  .github/workflows/zulip-ci.yml
  .gitignore
  docs/development/setup-advanced.md
  docs/overview/architecture-overview.md
  docs/subsystems/index.rst
  docs/subsystems/thumbnailing.md
  puppet/zulip/files/nginx/zulip-include-app.d/thumbor.conf
  puppet/zulip/files/nginx/zulip-include-frontend/upstreams
  puppet/zulip/files/supervisor/conf.d/thumbor.conf
  puppet/zulip/manifests/profile/thumbor.pp
  requirements/common.in
  requirements/dev.txt
  requirements/prod.txt
  requirements/thumbor-dev.in
  requirements/thumbor-dev.txt
  requirements/thumbor.in
  requirements/thumbor.txt
  scripts/lib/clean_venv_cache.py
  scripts/lib/create-thumbor-venv
  scripts/lib/install
  scripts/lib/setup_venv.py
  scripts/lib/upgrade-zulip-stage-2
  scripts/restart-server
  scripts/setup/generate_secrets.py
  scripts/stop-server
  static/js/lightbox.js
  tools/lib/provision.py
  tools/run-dev.py
  tools/setup/setup_venvs.py
  tools/update-locked-requirements
  version.py
  zerver/lib/test_helpers.py
  zerver/lib/thumbnail.py
  zerver/tests/test_camo.py
  zerver/tests/test_thumbnail.py
  zerver/views/development/camo.py
  zerver/views/thumbnail.py
  zproject/computed_settings.py
  zproject/default_settings.py
  zproject/dev_settings.py
  zproject/dev_urls.py
  zproject/prod_settings_template.py
  zproject/test_extra_settings.py
  zproject/urls.py
  zthumbor/__init__.py
  zthumbor/loaders/__init__.py
  zthumbor/loaders/helpers.py
  zthumbor/loaders/zloader.py
  zthumbor/thumbor_settings.py
Labels: size: XL

#18380 alert_words: Revert back `before_punctuation` regex to stable one.
  static/js/alert_words.js
Labels: size: XS

#18311 models: Fix incorrect on_delete=CASCADE values for deleted streams.
  zerver/migrations/0324_fix_deletion_cascade_behavior.py
  zerver/models.py
Labels: size: L

#18387 node_tests: Update alert words tests to handle a corner case.
  frontend_tests/node_tests/alert_words.js
Labels: size: XS

#18385 node_tests: Add remaining tests for `panels.js`.
  frontend_tests/node_tests/panels.js
  static/js/panels.js
Labels: size: L

#18285 profile postgresql: Fix supervisor service handling during upgrade.
  scripts/lib/zulip_tools.py
  scripts/restart-server
  scripts/stop-server
Labels: size: XL

#18398 send performance: Optimize create_user_messages.
  zerver/lib/actions.py
Labels: size: L

#18399 integrations: Fix bug with github multiple reviews requested on PR.
  zerver/webhooks/github/fixtures/pull_request__review_requested_multiple_reviewers.json
  zerver/webhooks/github/fixtures/pull_request__review_requested_singular_key.json
  zerver/webhooks/github/tests.py
  zerver/webhooks/github/view.py
Labels: area: integrations, bug, priority: high, size: XL

#18408 drafts: Allow vim up and down key to scroll between drafts
  static/js/drafts.js
  static/js/hotkey.js
Labels: area: compose, area: keyboard UI, bug, size: S

#18407 "Schema migrations" documentation updates
  docs/subsystems/schema-migrations.md
Labels: size: S

#18187 shared: Bump version to 0.0.5.
  static/shared/README.md
Labels: size: S

#18100 integrations: Add Uptime Robot integration.
  static/images/integrations/bot_avatars/uptimerobot.png
  static/images/integrations/logos/uptimerobot.svg
  static/images/integrations/uptimerobot/001.png
  zerver/lib/integrations.py
  zerver/webhooks/uptimerobot/__init__.py
  zerver/webhooks/uptimerobot/doc.md
  zerver/webhooks/uptimerobot/fixtures/uptimerobot_invalid_payload_with_missing_data.json
  zerver/webhooks/uptimerobot/fixtures/uptimerobot_monitor_down.json
  zerver/webhooks/uptimerobot/fixtures/uptimerobot_monitor_up.json
  zerver/webhooks/uptimerobot/tests.py
  zerver/webhooks/uptimerobot/view.py
Labels: area: integrations, new feature, size: XL

#18419 realm_playground: Stop using Map incorrectly
  static/js/realm_playground.js
  static/js/settings_playgrounds.js
Labels: size: M

#18423 right-sidebar: Replace invite-link height with shortcut height.
  static/js/resize.js
Labels: size: XS

#18426 markdown: Fix silent wildcard mentions bug.
  zerver/lib/markdown/__init__.py
  zerver/tests/test_markdown.py
Labels: area: notifications (messages), bug, priority: high, size: M

#18430 edit_linkifiers: Show the right command name in help text.
  zerver/management/commands/edit_linkifiers.py
Labels: size: S

#18422 puppeteer_tests: Show filename when failed for quicker debugging.
  tools/test-js-with-puppeteer
Labels: size: S

#18428 retention: Change default behavior of restore_messages command to noop.
  zerver/management/commands/restore_messages.py
Labels: size: S

#18432 Typo Fix ("evailability")
  docs/production/export-and-import.md
Labels: size: XS

#18418 Upgrade JavaScript dependencies
  .eslintrc.json
  frontend_tests/node_tests/upgrade.js
  static/js/emoji_picker.js
  static/js/filter.js
  static/js/hotkey.js
  static/js/input_pill.js
  static/js/lightbox.js
  static/js/lightbox_canvas.js
  static/js/message_edit.js
  static/js/narrow.js
  static/js/rtl.js
  static/js/settings_org.js
Labels: size: XL

#18436 management: Rename the deliver_email command to deliver_scheduled_email.
  docs/subsystems/email.md
  puppet/zulip/files/nagios_plugins/zulip_app_frontend/check_email_deliverer_process
  puppet/zulip/templates/supervisor/zulip.conf.template.erb
  zerver/lib/send_email.py
  zerver/management/commands/deliver_scheduled_emails.py
  zerver/management/commands/print_email_delivery_backlog.py
  zerver/tests/test_signup.py
  zerver/tests/test_users.py
  zproject/computed_settings.py
  zproject/default_settings.py
Labels: size: L

#18444 install: Tell NVM to not change $PATH earlier.
  scripts/lib/install-node
Labels: size: S

#18445 outgoing_webhook: Send response payload to bot owner if it was invalid.
  zerver/lib/outgoing_webhook.py
  zerver/tests/test_outgoing_webhook_system.py
Labels: size: S

#18450 puppet: Adjust thresholds on autovac_freeze.
  puppet/zulip_ops/files/nagios3/conf.d/services.cfg
Labels: size: XS

#18447 send_email: Show more information about messages which failed to send.
  zerver/lib/send_email.py
  zerver/tests/test_send_email.py
Labels: size: L

#18449 Refactor has_message_access to support optimizations
  zerver/lib/message.py
  zerver/tests/test_message_edit.py
Labels: size: XL

#18437 playgrounds: Rename `name` field to `playground_name`.
  frontend_tests/puppeteer_tests/realm-playground.ts
  static/js/settings_playgrounds.js
  static/templates/settings/playground_settings_admin.hbs
Labels: size: S

#18443 performance: Speed up send-message for large streams
  zerver/lib/actions.py
  zerver/lib/stream_subscription.py
  zerver/lib/stream_topic.py
  zerver/tests/test_soft_deactivation.py
  zerver/tests/test_users.py
Labels: size: XL

#18459 recent_topics: Fix annoying flicker on rerendering.
  frontend_tests/node_tests/recent_topics.js
  static/js/recent_topics.js
Labels: size: XL

#18458 performance: Use values_list in message edit code.
  zerver/lib/actions.py
Labels: size: S

#18462 smokescreen: Capitalize Smokescreen in documentation.
  docs/overview/changelog.md
  docs/production/deployment.md
  docs/production/requirements.md
  docs/production/security-model.md
Labels: size: S

#18464 tests: Clean up tests for realm_domain and update_streams endpoint.
  zerver/tests/test_realm_domains.py
  zerver/tests/test_subs.py
Labels: size: S

#18465 smokescreen: Bump version of Go and Smokescreen.
  puppet/zulip/manifests/profile/smokescreen.pp
Labels: size: S

#18466 favicon: Catch exceptions in update_favicon
  static/js/favicon.js
Labels: size: L

#18214 typeahead: Fetch stream topic history from server.
  frontend_tests/node_tests/composebox_typeahead.js
  frontend_tests/node_tests/search_suggestion.js
  frontend_tests/node_tests/search_suggestion_legacy.js
  static/js/composebox_typeahead.js
  static/js/search_suggestion.js
Labels: area: search, size: M

#18467 hotkey: Render default_view via changing hash.
  static/js/hashchange.js
  static/js/hotkey.js
Labels: size: S

#18469 recent_topics: Extend the borders to bottom of window.
  static/styles/recent_topics.css
Labels: size: S

#18474 pm_list: Use "Muted user" placeholder for muted usernames.
  frontend_tests/node_tests/people.js
  static/js/people.js
Labels: size: S

#18476 outgoing_webhook: Treat "" json in response as response_not_required.
  zerver/lib/outgoing_webhook.py
  zerver/tests/test_outgoing_webhook_system.py
Labels: release goal, size: M

#18477 emails: Change logging level of empty gateway pattern.
  zerver/lib/email_mirror.py
Labels: size: S

#18480 recent topics: Fix placement of tooltips in recent topic rows.
  static/templates/recent_topic_row.hbs
Labels: size: S

#18482 node tests: Clear muted users before each test.
  frontend_tests/node_tests/composebox_typeahead.js
  frontend_tests/node_tests/pm_conversations.js
Labels: size: XS

#18484 Message action tooltip
  static/js/tippyjs.js
  static/js/ui.js
  static/templates/edit_content_button.hbs
  static/templates/message_controls.hbs
Labels: size: M

#18487 upgrade-zulip-from-git: Create deployment directories with git worktree
  scripts/lib/upgrade-zulip-from-git
  scripts/purge-old-deployments
Labels: size: S

#18488 recent-topics: Fix tooltip placement and details.
  static/templates/recent_topic_row.hbs
Labels: size: XS

#18483 about-zulip: Clean up about dialog
  templates/zerver/app/about-zulip.html
Labels: release goal, size: S

#18492 message_edit_form: Fix vertical aliments of bottom elements.
  static/styles/zulip.css
Labels: size: XS

#18494 purge-old-deployments: Check /srv/zulip.git existence before pruning it
  scripts/purge-old-deployments
Labels: size: S

#18498 help: Clarify what muting means for the muted user.
  templates/zerver/help/mute-a-user.md
Labels: size: XS

#18506 dropdown_list_widget: Add 'type' attribute to reset button.
  static/templates/settings/dropdown_list_widget.hbs
Labels: size: XS

#18507 docs: Document password hashing change from PBKDF2 to Argon2
  docs/production/security-model.md
Labels: size: XS

#18489 docs: Correct “webapp” to “web app”
  docs/contributing/chat-zulip-org.md
  docs/contributing/gsoc-ideas.md
  docs/development/using.md
  docs/overview/architecture-overview.md
  docs/overview/changelog.md
  docs/overview/release-lifecycle.md
  docs/production/authentication-methods.md
  docs/subsystems/caching.md
  docs/subsystems/dependencies.md
  docs/subsystems/emoji.md
  docs/subsystems/events-system.md
  docs/subsystems/hashchange-system.md
  docs/subsystems/html-css.md
  docs/subsystems/performance.md
  docs/subsystems/presence.md
  docs/subsystems/widgets.md
  docs/testing/philosophy.md
  docs/testing/testing-with-puppeteer.md
  docs/testing/testing.md
  docs/translating/translating.md
  static/js/activity.js
  static/js/echo.js
  static/js/markdown_config.js
  static/js/reload.js
  static/js/util.js
  static/shared/README.md
  static/shared/js/emoji.js
  static/styles/app_components.css
  static/styles/components.css
  templates/corporate/jobs.html
  templates/zerver/api/construct-narrow.md
  templates/zerver/api/get-events.md
  templates/zerver/api/register-queue.md
  templates/zerver/api/writing-bots.md
  templates/zerver/features.html
  templates/zerver/help/change-default-view.md
  templates/zerver/help/gdpr-compliance.md
  tools/documentation_crawler/documentation_crawler/spiders/common/spiders.py
  tools/setup/emoji/build_emoji
  zerver/lib/event_schema.py
  zerver/lib/events.py
  zerver/lib/test_classes.py
  zerver/lib/widget.py
  zerver/models.py
  zerver/openapi/zulip.yaml
  zerver/tests/test_auth_backends.py
  zerver/tests/test_messages.py
  zerver/views/auth.py
  zerver/views/message_fetch.py
  zerver/views/presence.py
  zproject/urls.py
Labels: size: XL

#18500 ci: Unpack installation tarball under /root/.
  .github/workflows/production-suite.yml
  tools/ci/production-build
  tools/ci/production-extract-tarball
  tools/ci/production-install
  tools/ci/production-upgrade-pg
Labels: size: M

#18519 Improve buddy_data coverage
  frontend_tests/node_tests/buddy_data.js
Labels: size: L

#18530 jinja2: Serialize page-params with orjson
  zproject/jinja2/__init__.py
Labels: size: S

#18537 docs: Clarify how to set GIPHY API key in settings.
  docs/production/giphy-gif-integration.md
Labels: size: XS

#18535 Fix typos using codespell.
  frontend_tests/node_tests/panels.js
  frontend_tests/node_tests/typeahead_helper.js
  static/js/hashchange.js
  static/js/vdom.js
  static/styles/user_status.css
  templates/zerver/help/code-blocks.md
  zerver/lib/import_realm.py
  zerver/lib/message.py
Labels: size: S

#18533 devtools: Improve the appearance of dev_panel.
  static/styles/portico/integrations_dev_panel.css
  templates/zerver/development/integrations_dev_panel.html
Labels: size: S

#18514 muted_user_settings: Add table-sticky-headers class to table header.
  static/templates/settings/muted_users_settings.hbs
Labels: size: XS

#18499 billing: Show billing email in /billing page
  corporate/tests/test_stripe.py
  templates/corporate/billing.html
Labels: size: S

#18536 puppeteer_test: Add wait call for linkifier table to get updated.
  frontend_tests/puppeteer_tests/realm-linkifier.ts
Labels: size: S

#18546 node tests: Clean up electron_bridge test.
  frontend_tests/node_tests/activity.js
Labels: size: L

#18547 node tests: Add test wrapper for message_list_view.
  frontend_tests/node_tests/message_list_view.js
Labels: size: S

#18543 tippy: Increase font size from 12 to 13px.
  static/styles/zulip.css
Labels: size: XS

#18544 Fix bugs when Giphy API key is not added.
  static/js/admin.js
  static/templates/settings/organization_settings_admin.hbs
Labels: size: S

#18552 node_tests: Silence KaTeX warning in markdown test
  frontend_tests/node_tests/markdown.js
Labels: size: XS

#18558 pypi: Upgrade zulip/zulip-bots dependencies to version 0.8.0.
  requirements/common.in
  requirements/dev.txt
  requirements/prod.txt
  version.py
Labels: size: S

#18562 templates: Escape some unescaped > and & characters
  static/templates/stream_topic_widget.hbs
  templates/zerver/footer.html
Labels: size: S

#18515 message view: Fix tooltips in message action icons.
  static/js/tippyjs.js
  static/templates/message_controls.hbs
Labels: size: S

#18568 update-prod-static: Ensure that it is run as the zulip user.
  tools/update-prod-static
Labels: size: XS

#18527 refactor: Rename `panels.js` to `navbar_alerts.js` as it better explains it.
  frontend_tests/node_tests/navbar_alerts.js
  static/js/floating_recipient_bar.js
  static/js/navbar_alerts.js
  static/js/recent_topics.js
  static/js/resize.js
  static/js/server_events_dispatch.js
  static/js/ui_init.js
  static/styles/zulip.css
  templates/zerver/app/navbar_alerts.html
  tools/test-js-with-node
Labels: size: L

#18548 fix formatting on key to tables in stream-permissions
  static/styles/portico/markdown.css
  templates/zerver/help/stream-permissions.md
Labels: size: M

#18575 changelog: Fix repetition of feature levels in changelog.md.
  templates/zerver/api/changelog.md
Labels: size: XS

#18386 integrations: Enhance Grafana integration with alert state
  zerver/webhooks/grafana/fixtures/alert_ok.json
  zerver/webhooks/grafana/fixtures/alert_paused.json
  zerver/webhooks/grafana/fixtures/alert_pending.json
  zerver/webhooks/grafana/tests.py
  zerver/webhooks/grafana/view.py
Labels: size: XL

#18570 change-your-name: names to reserved words can be mentioned
  templates/zerver/help/change-your-name.md
Labels: size: XS

#18584 actions: Fix “Fix UserActivityInterval overlap bug” bug.
  zerver/lib/actions.py
Labels: size: S

#18582 rundjangoserver: Filter stdout instead of forking the code
  tools/linter_lib/exclude.py
  zilencer/management/commands/rundjangoserver.py
Labels: size: L

#18593 message view: Show re-hide option in revealed muted user's message only.
  static/js/popovers.js
Labels: size: XS

#18571 setup: Merge multiple setup-apt-repo scripts into one.
  puppet/zulip_ops/manifests/apt_repository_debathena.pp
  puppet/zulip_ops/manifests/ksplice_uptrack.pp
  scripts/lib/setup-apt-repo
  scripts/lib/setup-apt-repo-debathena
  scripts/lib/setup-apt-repo-ksplice
  scripts/setup/apt-repos/ksplice/bionic.list
  scripts/setup/apt-repos/ksplice/focal.list
  scripts/setup/apt-repos/ksplice/ksplice.asc
  scripts/setup/apt-repos/zulip/bionic.list
  scripts/setup/apt-repos/zulip/bullseye.list
  scripts/setup/apt-repos/zulip/buster.list
  scripts/setup/apt-repos/zulip/cosmic.list
  scripts/setup/apt-repos/zulip/custom.sh
  scripts/setup/apt-repos/zulip/disco.list
  scripts/setup/apt-repos/zulip/eoan.list
  scripts/setup/apt-repos/zulip/focal.list
  scripts/setup/apt-repos/zulip/groovy.list
  scripts/setup/apt-repos/zulip/pgdg.asc
  scripts/setup/apt-repos/zulip/pgroonga-packages.groonga.org.asc
  scripts/setup/apt-repos/zulip/pgroonga-ppa.asc
  scripts/setup/apt-repos/zulip_debathena/bionic.list
  scripts/setup/apt-repos/zulip_debathena/debathena-archive.asc
Labels: area: production installer, size: XL

#17847 integrations: Add Lidarr integration.
  static/images/integrations/bot_avatars/lidarr.png
  static/images/integrations/lidarr/001.png
  static/images/integrations/logos/lidarr.svg
  zerver/lib/integrations.py
  zerver/webhooks/lidarr/__init__.py
  zerver/webhooks/lidarr/doc.md
  zerver/webhooks/lidarr/fixtures/lidarr_album_grabbed.json
  zerver/webhooks/lidarr/fixtures/lidarr_test.json
  zerver/webhooks/lidarr/fixtures/lidarr_tracks_imported.json
  zerver/webhooks/lidarr/fixtures/lidarr_tracks_imported_over_limit.json
  zerver/webhooks/lidarr/fixtures/lidarr_tracks_imported_upgrade.json
  zerver/webhooks/lidarr/fixtures/lidarr_tracks_imported_upgrade_over_limit.json
  zerver/webhooks/lidarr/fixtures/lidarr_tracks_renamed.json
  zerver/webhooks/lidarr/fixtures/lidarr_tracks_retagged.json
  zerver/webhooks/lidarr/tests.py
  zerver/webhooks/lidarr/view.py
Labels: size: XL

#17839 integrations: Add Radarr inegration.
  static/images/integrations/bot_avatars/radarr.png
  static/images/integrations/logos/radarr.svg
  static/images/integrations/radarr/001.png
  zerver/lib/integrations.py
  zerver/webhooks/radarr/__init__.py
  zerver/webhooks/radarr/doc.md
  zerver/webhooks/radarr/fixtures/radarr_health_check_error.json
  zerver/webhooks/radarr/fixtures/radarr_health_check_warning.json
  zerver/webhooks/radarr/fixtures/radarr_movie_grabbed.json
  zerver/webhooks/radarr/fixtures/radarr_movie_imported.json
  zerver/webhooks/radarr/fixtures/radarr_movie_imported_upgrade.json
  zerver/webhooks/radarr/fixtures/radarr_movie_renamed.json
  zerver/webhooks/radarr/fixtures/radarr_test.json
  zerver/webhooks/radarr/tests.py
  zerver/webhooks/radarr/view.py
Labels: size: XL

#17831 integrations: Add Sonarr integration
  static/images/integrations/bot_avatars/sonarr.png
  static/images/integrations/logos/sonarr.svg
  static/images/integrations/sonarr/001.png
  zerver/lib/integrations.py
  zerver/webhooks/sonarr/__init__.py
  zerver/webhooks/sonarr/doc.md
  zerver/webhooks/sonarr/fixtures/sonarr_episode_deleted.json
  zerver/webhooks/sonarr/fixtures/sonarr_episode_deleted_upgrade.json
  zerver/webhooks/sonarr/fixtures/sonarr_episode_grabbed.json
  zerver/webhooks/sonarr/fixtures/sonarr_episode_imported.json
  zerver/webhooks/sonarr/fixtures/sonarr_episode_imported_upgrade.json
  zerver/webhooks/sonarr/fixtures/sonarr_episodes_renamed.json
  zerver/webhooks/sonarr/fixtures/sonarr_health_check_error.json
  zerver/webhooks/sonarr/fixtures/sonarr_health_check_warning.json
  zerver/webhooks/sonarr/fixtures/sonarr_series_deleted.json
  zerver/webhooks/sonarr/fixtures/sonarr_test.json
  zerver/webhooks/sonarr/tests.py
  zerver/webhooks/sonarr/view.py
Labels: size: XL

#18620 create-db: Default dbuser and dbname to zulip
  scripts/setup/create-db.sql
Labels: size: XS

#18585 actions: Fix incorrect audit logging in bulk_remove_subscriptions
  zerver/lib/actions.py
Labels: size: XS

#18630 Fix bug of disabling "Add" button used for adding subscribers on live update after subscribing.
  static/js/subs.js
Labels: area: stream settings, bug, priority: high, size: XS

#18625 minor: Fix typo in summary.
  zerver/openapi/zulip.yaml
Labels: size: XS

#18633 docs: Clarify that the Slack app and API token should be removed.
  templates/zerver/help/import-from-slack.md
Labels: size: S

#18636 node_cache: Serialize to structured data before hashing.
  scripts/lib/node_cache.py
Labels: size: S

#18628 registration: Show spinner and disable button while processing request.
  static/js/portico/signup.js
  static/styles/portico/portico_signin.css
  templates/zerver/register.html
Labels: size: S

#16612 uploads: Support non-AWS S3-compatible server.
  zerver/lib/upload.py
Labels: area: export/import, area: uploads, bug, size: L

#18119 integrations: Add Freshstatus webhook integration.
  static/images/integrations/bot_avatars/freshstatus.png
  static/images/integrations/freshstatus/001.png
  static/images/integrations/logos/freshstatus.svg
  zerver/lib/integrations.py
  zerver/webhooks/freshstatus/__init__.py
  zerver/webhooks/freshstatus/doc.md
  zerver/webhooks/freshstatus/fixtures/freshstatus_event_not_supported.json
  zerver/webhooks/freshstatus/fixtures/freshstatus_incident_closed.json
  zerver/webhooks/freshstatus/fixtures/freshstatus_incident_note_created.json
  zerver/webhooks/freshstatus/fixtures/freshstatus_incident_open.json
  zerver/webhooks/freshstatus/fixtures/freshstatus_incident_open_multiple_services.json
  zerver/webhooks/freshstatus/fixtures/freshstatus_incident_open_multiple_services_over_limit.json
  zerver/webhooks/freshstatus/fixtures/freshstatus_invalid_payload_with_missing_data.json
  zerver/webhooks/freshstatus/fixtures/freshstatus_scheduled_maintenance_closed.json
  zerver/webhooks/freshstatus/fixtures/freshstatus_scheduled_maintenance_note_created.json
  zerver/webhooks/freshstatus/fixtures/freshstatus_scheduled_maintenance_planned.json
  zerver/webhooks/freshstatus/fixtures/freshstatus_scheduled_maintenance_planned_multiple_services.json
  zerver/webhooks/freshstatus/fixtures/freshstatus_scheduled_maintenance_planned_multiple_services_over_limit.json
  zerver/webhooks/freshstatus/fixtures/freshstatus_test.json
  zerver/webhooks/freshstatus/tests.py
  zerver/webhooks/freshstatus/view.py
Labels: area: integrations, size: XL

#18638 message_events: Pass correct new stream id to recent_senders.
  static/js/message_events.js
Labels: size: S

#18634 Avoid useless work when switching a modern Zulip server to Pgroonga
  pgroonga/migrations/0001_enable.py
  pgroonga/migrations/0003_v2_api_upgrade.py
Labels: size: L

#18644 draft: Fix incorrectly centered topics in drafts modal
  static/templates/draft.hbs
Labels: size: XS

#18643 giphy: Load Giphy SDK lazily
  static/js/giphy.js
Labels: size: M
