Repository zulip/zulip, pull requests merged in 2021-10, with the labels that each got.

#19882 github: Ignore CodeQL analysis in private repos.
  .github/workflows/codeql-analysis.yml
Labels: size: XS

#19883 copy_code_button: Attach tooltip to body to avoid overlap with parent.
  static/js/tippyjs.js
  static/templates/copy_code_button.hbs
Labels: size: XS

#17066 streams: Split stream creation option in org settings.
  frontend_tests/node_tests/dispatch.js
  frontend_tests/node_tests/hotkey.js
  frontend_tests/node_tests/lib/events.js
  frontend_tests/node_tests/settings_data.js
  frontend_tests/node_tests/settings_org.js
  frontend_tests/puppeteer_tests/admin.ts
  static/js/hotkey.js
  static/js/page_params.ts
  static/js/popover_menus.js
  static/js/server_events_dispatch.js
  static/js/settings_data.ts
  static/js/settings_org.js
  static/js/stream_settings_ui.js
  static/styles/settings.css
  static/templates/settings/organization_permissions_admin.hbs
  static/templates/stream_settings/stream_creation_form.hbs
  templates/zerver/api/changelog.md
  version.py
  zerver/lib/events.py
  zerver/lib/streams.py
  zerver/migrations/0358_split_create_stream_policy.py
  zerver/models.py
  zerver/openapi/zulip.yaml
  zerver/tests/test_events.py
  zerver/tests/test_home.py
  zerver/tests/test_realm.py
  zerver/tests/test_subs.py
  zerver/views/realm.py
Labels: area: settings (admin/org), size: XL

#19868 docs: Document upgrade steps from buster to bullseye.
  docs/production/upgrade-or-modify.md
Labels: size: L

#19744 realm: Change default permissions for education organizations.
  zerver/lib/actions.py
  zerver/tests/test_realm.py
Labels: size: L

#19889 Fix small typographical bugs in API changelog
  templates/zerver/api/changelog.md
  templates/zerver/api/sidebar_index.md
Labels: size: XS

#19858 markdown/tabbed_sections: Raise exception for missing tab name.
  templates/zerver/tests/markdown/test_tabbed_sections_missing_tabs.md
  zerver/lib/markdown/tabbed_sections.py
  zerver/tests/test_templates.py
Labels: size: M

#19864 corporate: Add contact support page.
  corporate/lib/support.py
  corporate/tests/test_stripe.py
  corporate/urls.py
  corporate/views/support.py
  corporate/views/upgrade.py
  static/styles/portico/portico.css
  static/styles/portico/portico_signin.css
  templates/corporate/support_request.html
  templates/corporate/support_request_thanks.html
  templates/zerver/emails/support_request.html
  templates/zerver/emails/support_request.subject.txt
  templates/zerver/emails/support_request.txt
  tools/linter_lib/custom_check.py
Labels: size: XL

#19892 puppeteer: Remove waitFors on deletion spinners.
  frontend_tests/puppeteer_tests/delete-message.ts
Labels: size: S

#19891 openapi: Use more carefully-constructed regexes for markdown extension.
  zerver/openapi/markdown_extension.py
  zerver/openapi/test_curl_examples.py
  zerver/tests/test_openapi.py
Labels: size: XL

#19896 openapi: Fix broken link to documentation.
  zerver/openapi/zulip.yaml
Labels: size: XS

#19897 docs: Document what to do when releases need migrations.
  docs/subsystems/schema-migrations.md
Labels: size: S

#19898 test_events: Test the email event when changing delivery_email.
  zerver/tests/test_events.py
Labels: size: S

#19902 auth: Add login buttons for web public access.
  static/styles/portico/portico_signin.css
  templates/zerver/development/dev_login.html
  templates/zerver/login.html
  zerver/context_processors.py
  zerver/decorator.py
  zerver/lib/test_classes.py
  zerver/tests/test_auth_backends.py
  zerver/tests/test_home.py
  zerver/tests/test_sessions.py
  zerver/tests/test_urls.py
  zerver/views/development/dev_login.py
  zerver/views/home.py
Labels: size: XL

#19904 fix: Hide checkmark if user does not have permission to edit topic
  static/js/message_list_view.js
  static/templates/recipient_row.hbs
Labels: size: S

#20094 modal: Remove focus ring from submit button.
  static/styles/modal.css
Labels: size: S

#20093 settings: Fix css for custom profile fields in edit user form.
  static/styles/settings.css
Labels: size: L

#19441 openapi: Document remove-attachment endpoint.
  templates/zerver/help/include/rest-endpoints.md
  zerver/openapi/curl_param_value_generators.py
  zerver/openapi/python_examples.py
  zerver/openapi/zulip.yaml
  zerver/tests/test_openapi.py
Labels: size: L

#20056 editor: Add `.vscode/extensions.json`.
  .gitignore
  .vscode/extensions.json
Labels: size: M

#20097 deprecated_feature_notice: Migrate modal to dialog_widget.
  frontend_tests/node_tests/deprecated_feature_notice.js
  static/js/deprecated_feature_notice.js
  static/templates/deprecated_feature_notice.hbs
Labels: size: M

#20104 dependencies: Downgrade webpack to avoid caching bug
  package.json
  version.py
  yarn.lock
Labels: size: M

#20070 [WIP] user_settings: Add option to disable escape navigation to default view
  frontend_tests/node_tests/dispatch.js
  frontend_tests/node_tests/lib/events.js
  static/js/hotkey.js
  static/js/info_overlay.js
  static/js/realm_user_settings_defaults.ts
  static/js/server_events_dispatch.js
  static/js/settings_config.ts
  static/js/settings_display.js
  static/js/user_settings.ts
  static/styles/settings.css
  static/templates/keyboard_shortcuts.hbs
  static/templates/settings/display_settings.hbs
  templates/zerver/api/changelog.md
  templates/zerver/help/change-default-view.md
  templates/zerver/help/configure-default-view.md
  templates/zerver/help/include/sidebar_index.md
  templates/zerver/help/keyboard-shortcuts.md
  version.py
  zerver/migrations/0369_add_escnav_default_display_user_setting.py
  zerver/models.py
  zerver/openapi/zulip.yaml
  zerver/views/realm.py
  zerver/views/user_settings.py
Labels: size: XL
