Repository zulip/zulip, pull requests merged in 2021-06, with the labels that each got.

#18648 Tweak SAML doc regarding SP private key generation
  docs/production/authentication-methods.md
Labels: size: S

#18650 recent_topics: Optimize for mobile devices.
  static/styles/recent_topics.css
Labels: size: XS

#18612 docs: Add syntax highlighting in api docs.
  templates/zerver/api/deploying-bots.md
  templates/zerver/api/incoming-webhooks-walkthrough.md
  templates/zerver/api/outgoing-webhooks.md
  templates/zerver/api/writing-bots.md
Labels: size: L

#18663 docs: Update path to nginx.conf, as it is now a template.
  docs/production/install-existing-server.md
Labels: size: S

#18662 Fix the incorrect warning message when unsubscribing from stream.
  static/templates/unsubscribe_private_stream_modal.hbs
Labels: area: stream settings, bug, size: XS

#18666 puppet: Add an explicit class for czo.
  puppet/zulip_ops/manifests/profile/chat_zulip_org.pp
Labels: size: S

#18669 apidocs: Fix description of topic parameter in update_message.
  zerver/openapi/zulip.yaml
Labels: size: M

#18670 Change supported extension type to reflect the latest change in the Pageduty webhook.
  zerver/webhooks/pagerduty/doc.md
Labels: size: XS

#18672 send_test_email: Capture and show SMTP log on errors.
  zerver/management/commands/send_test_email.py
Labels: size: S

#18655 emails: Make it obvious registering creates new org.
  templates/zerver/emails/confirm_registration.source.html
  templates/zerver/emails/confirm_registration.subject.txt
  templates/zerver/emails/confirm_registration.txt
  zerver/lib/test_classes.py
  zerver/tests/test_signup.py
  zerver/views/registration.py
Labels: area: emails, area: onboarding, size: M

#18679 docs: Remove link to 16.04, which can be confusing.
  docs/production/troubleshooting.md
Labels: size: S

#18680 docs: Link to install-existing-server from production/deployment.
  docs/production/deployment.md
Labels: size: S

#18434 styles, portico_signin: Make login-social-button responsive to larger fonts.
  static/styles/portico/portico_signin.css
Labels: size: XS

#18686 puppeteer_test: Add `wait_for_modal_to_close` method to `CommonUtils`.
  frontend_tests/puppeteer_lib/common.ts
  frontend_tests/puppeteer_tests/realm-linkifier.ts
  frontend_tests/puppeteer_tests/settings.ts
Labels: size: S

#18684 frontend tests: Replace incorrect asserts with assert.equal
  frontend_tests/node_tests/billing.js
  frontend_tests/node_tests/dispatch.js
  frontend_tests/node_tests/stream_data.js
  frontend_tests/node_tests/upload.js
  frontend_tests/node_tests/user_events.js
Labels: size: M

#18683 settings: Make `MAX_MESSAGE_LENGTH` a server-level setting.
  zerver/lib/actions.py
  zerver/lib/events.py
  zerver/lib/markdown/__init__.py
  zerver/lib/message.py
  zerver/models.py
  zerver/tests/test_markdown.py
  zerver/tests/test_message_send.py
  zproject/default_settings.py
Labels: size: S

#18682 corporate: Add some basic documentation of the corporate/* models.
  corporate/models.py
Labels: size: M

#18688 docs: Update link to image check script in digitalocean tools repo.
  tools/oneclickapps/README.md
Labels: size: S

#18678 delete_realm: Don't allow deletion of realms with current plans.
  zerver/management/commands/delete_realm.py
Labels: size: S

#18641 markdown: Increase max rendered message length to 1MB.
  zerver/lib/markdown/__init__.py
  zerver/tests/test_markdown.py
Labels: size: S

#18502 recent topics: Display other sender names in tooltip.
  frontend_tests/node_tests/recent_topics.js
  static/js/recent_topics.js
  static/templates/recent_topic_row.hbs
Labels: size: S

#18700 compose: Clarify title for wide reply button.
  static/templates/compose.hbs
Labels: size: XS

#18696 curl_examples: Fix testing with new apidocs template.
  zerver/openapi/test_curl_examples.py
Labels: size: XL

#18703 zjquery: Eliminate css() helper.
  frontend_tests/node_tests/compose_actions.js
  frontend_tests/node_tests/drafts.js
  frontend_tests/node_tests/recent_topics.js
  frontend_tests/node_tests/search.js
  frontend_tests/node_tests/search_legacy.js
  frontend_tests/node_tests/settings_org.js
  frontend_tests/zjsunit/zjquery.js
Labels: size: M

#18701 popovers: Migrate user status indicator tooltip to tippy.
  static/templates/user_info_popover_content.hbs
Labels: size: XS

#18709 Features page
  templates/zerver/features.html
  templates/zerver/help/private-messages.md
  templates/zerver/help/status-and-availability.md
Labels: size: S

#18721 info_overlay: Remove dead code.
  static/js/info_overlay.js
Labels: size: S

#18720 modals: Remove `in` class once modal is hidden.
  static/js/click_handlers.js
Labels: size: XS

#18708 tests: Add test_example.py.
  zerver/tests/test_example.py
Labels: size: XL

#18717 navbar_alerts: Replace HTML template with handlebars architecture.
  static/js/navbar_alerts.js
  static/styles/zulip.css
  static/templates/navbar_alerts/bankruptcy.hbs
  static/templates/navbar_alerts/configure_outgoing_email.hbs
  static/templates/navbar_alerts/desktop_notifications.hbs
  static/templates/navbar_alerts/insecure_desktop_app.hbs
  static/templates/navbar_alerts/navbar_alert_wrapper.hbs
  static/templates/navbar_alerts/profile_incomplete.hbs
  static/templates/navbar_alerts/server_needs_upgrade.hbs
  templates/zerver/app/index.html
  templates/zerver/app/navbar_alerts.html
Labels: size: XL

#18722 node tests: Replace assert with assert.equal in dispatch.js.
  frontend_tests/node_tests/dispatch.js
  frontend_tests/node_tests/lib/events.js
Labels: area: testing-infrastructure, size: XS

#18747 puppet: Add a label to teleport applications, to allow RBAC.
  puppet/zulip_ops/manifests/profile/nagios.pp
  puppet/zulip_ops/manifests/teleport/application.pp
  puppet/zulip_ops/templates/teleport_app.yaml.template.erb
Labels: size: S

#18748 puppet: Turn on "authentication" which defaults to user with all rights.
  puppet/zulip_ops/templates/nagios3/cgi.cfg.template.erb
Labels: size: XS

#18710 subdomains: Extend "static" to include resources hosted on S3.
  zerver/lib/subdomains.py
  zerver/lib/upload.py
  zerver/tests/test_subdomains.py
  zerver/tests/test_upload.py
Labels: size: M

#18749 webpack: Fix CSS source map generation on 1-CPU systems
  webpack.config.ts
Labels: area: production, bug, priority: high, size: S

#18729 puppet: Add a database teleport server.
  puppet/zulip_ops/files/postgresql/pg_hba.conf
  puppet/zulip_ops/files/supervisor/conf.d/teleport_db.conf
  puppet/zulip_ops/manifests/profile/postgresql.pp
  puppet/zulip_ops/manifests/teleport/db.pp
  puppet/zulip_ops/templates/teleport_db.yaml.template.erb
Labels: size: L

#18755 docs: Document how ShellCheck and shfmt are installed
  docs/subsystems/dependencies.md
Labels: size: S

#18739 navbar_alerts: Move bankruptcy loader msg as `step-2` of bankruptcy alert.
  static/js/navbar_alerts.js
  static/templates/navbar_alerts/bankruptcy.hbs
  static/templates/navbar_alerts/navbar_alert_wrapper.hbs
Labels: size: L

#18763 docs: Deemphasize Hubot as an integration bridge
  templates/zerver/api/integrations-overview.md
  templates/zerver/hello.html
  templates/zerver/help/request-an-integration.md
  templates/zerver/integrations/index.html
  zerver/tests/test_docs.py
  zerver/views/documentation.py
Labels: size: S

#18765 [4.x] zulip_tools: Flush ‘set -x’-style messages in run
  scripts/lib/zulip_tools.py
Labels: size: XS

#18766 dependencies: Downgrade @types/css-minimizer-webpack-plugin
  package.json
  version.py
  yarn.lock
Labels: size: XL

#18702 Add Support for PagerDuty v3 webhook API
  zerver/webhooks/pagerduty/doc.md
  zerver/webhooks/pagerduty/fixtures/acknowledged_v3.json
  zerver/webhooks/pagerduty/fixtures/reassigned_v3.json
  zerver/webhooks/pagerduty/fixtures/resolved_v3.json
  zerver/webhooks/pagerduty/fixtures/triggered_v3.json
  zerver/webhooks/pagerduty/fixtures/unacknowledged_v3.json
  zerver/webhooks/pagerduty/fixtures/unsupported_v1.json
  zerver/webhooks/pagerduty/fixtures/unsupported_v2.json
  zerver/webhooks/pagerduty/fixtures/unsupported_v3.json
  zerver/webhooks/pagerduty/tests.py
  zerver/webhooks/pagerduty/view.py
Labels: size: XL

#18759 tippy: Fix reaction tooltip placement when message-fade is active.
  static/js/tippyjs.js
  static/templates/message_reactions.hbs
Labels: size: M

#18767 production-verify: Don’t assume lengths have a decimal point
  tools/ci/production-verify
Labels: size: XS

#18772 dependencies: Move eslint-plugin-unicorn, xvfb to devDependencies
  package.json
Labels: size: XS

#18773 dependencies: Remove script-loader
  package.json
  yarn.lock
Labels: size: S

#18774 dependencies: Move callsites to devDependencies
  package.json
Labels: size: XS

#18769 plans_page: Compute sponsorship link for subdomain pages correctly.
  templates/zerver/faq.html
  zerver/tests/test_docs.py
  zerver/views/portico.py
Labels: size: S

#18744 puppeteer_tests: Replace incorrect assert calls with assert.equal
  frontend_tests/puppeteer_tests/settings.ts
Labels: size: S

#18784 lint: Apply custom_check.js_rules to TypeScript too
  tools/linter_lib/custom_check.py
Labels: size: XS

#18783 layout: Introduce a #compose-content div.
  static/js/click_handlers.js
  static/js/compose.js
  static/js/scroll_bar.js
  static/styles/compose.css
  static/styles/night_mode.css
  static/styles/zulip.css
  static/templates/compose.hbs
  templates/zerver/app/index.html
Labels: size: M

#18787 puppet: Bump grafana version to 8.0.1.
  puppet/zulip_ops/manifests/profile/grafana.pp
Labels: size: XS

#18788 left-sidebar: Hide clear filter text button if topic filter is empty.
  static/js/topic_list.js
Labels: size: S

#18737 Split recent topics module
  frontend_tests/node_tests/compose_actions.js
  frontend_tests/node_tests/compose_closed_ui.js
  frontend_tests/node_tests/example7.js
  frontend_tests/node_tests/hashchange.js
  frontend_tests/node_tests/hotkey.js
  frontend_tests/node_tests/message_fetch.js
  frontend_tests/node_tests/narrow_activate.js
  frontend_tests/node_tests/recent_topics.js
  frontend_tests/node_tests/stream_events.js
  static/js/click_handlers.js
  static/js/compose_actions.js
  static/js/compose_closed_ui.js
  static/js/echo.js
  static/js/hashchange.js
  static/js/hotkey.js
  static/js/message_events.js
  static/js/message_fetch.js
  static/js/message_list_view.js
  static/js/message_scroll.js
  static/js/message_view_header.js
  static/js/muting_ui.js
  static/js/narrow.js
  static/js/recent_topics_data.js
  static/js/recent_topics_ui.js
  static/js/recent_topics_util.js
  static/js/stream_events.js
  static/js/ui_init.js
  static/js/unread_ops.js
  tools/test-js-with-node
Labels: size: XL

#18798 build-release-tarball: Use require_clean_work_tree helper
  tools/build-release-tarball
Labels: size: S

#18793 webpack: Fix run-dev.py --minify
  tools/webpack
  webpack.config.ts
Labels: size: XS

#18804 zjsunit: Undo mock_cjs abstraction violation
  frontend_tests/zjsunit/namespace.js
Labels: size: S

#18816 puppeteer: Fix the selector for opening the message action menu.
  frontend_tests/puppeteer_tests/edit.ts
Labels: size: XS

#18811 test_push_notifications: Use `responses` module to mock HTTP responses.
  zerver/lib/remote_server.py
  zerver/tests/test_push_notifications.py
Labels: size: XL

#18820 zjquery: Split out zjquery_element.js.
  frontend_tests/zjsunit/zjquery.js
  frontend_tests/zjsunit/zjquery_element.js
  frontend_tests/zjsunit/zjquery_event.js
Labels: size: XL

#18824 tippyjs: Fix blueslip error on popover add emoji reaction hover.
  static/js/tippyjs.js
Labels: size: XS

#18825 eslint: Add eslint-plugin-formatjs
  .eslintrc.json
  package.json
  version.py
  yarn.lock
Labels: size: L

#18843 zjsunit: Remove unnecessary Handlebars wrapper function
  frontend_tests/zjsunit/handlebars.js
Labels: size: XS

#18837 lightbox_overlay: Migrate to handlebars.
  static/js/lightbox.js
  static/templates/lightbox_overlay.hbs
  templates/zerver/app/index.html
Labels: size: S

#18815 login: Remove browser show password in IE, edge.
  static/styles/components.css
Labels: size: S

#18647 Add translation policy on API error msg
  docs/translating/translating.md
Labels: size: XS

#18854 Have mock_template optionally exercise actual templates.
  frontend_tests/node_tests/compose.js
  frontend_tests/node_tests/composebox_typeahead.js
  frontend_tests/node_tests/copy_and_paste.js
  frontend_tests/node_tests/i18n.js
  frontend_tests/node_tests/input_pill.js
  frontend_tests/node_tests/recent_topics.js
  frontend_tests/node_tests/templates.js
  frontend_tests/node_tests/util.js
  frontend_tests/zjsunit/index.js
  frontend_tests/zjsunit/namespace.js
Labels: size: XL

#18835 message_history: Migrate to handlebars.
  static/js/message_edit_history.js
  static/js/ui_init.js
  static/templates/message_history.hbs
  templates/zerver/app/home.html
Labels: size: S

#18833 user_status: Migrate to handlebars.
  static/js/click_handlers.js
  static/js/user_status_ui.js
  static/templates/set_status_overlay.hbs
  templates/zerver/app/index.html
Labels: size: L

#18834 about_zulip: Migrate to handlebars.
  static/js/about_zulip.js
  static/js/ui_init.js
  static/templates/about_zulip.hbs
  templates/zerver/app/index.html
  zerver/lib/home.py
  zerver/tests/test_home.py
  zerver/views/home.py
Labels: size: M

#18857 plans_page: Fix broken redirection to /accounts/login/.
  zerver/tests/test_docs.py
  zerver/views/portico.py
Labels: size: XS

#18861 web_public_view: Replace `web_public_visitor` with `spectator`.
  frontend_tests/node_tests/activity.js
  static/js/activity.js
  static/js/server_events.js
  zerver/decorator.py
  zerver/lib/home.py
  zerver/lib/test_classes.py
  zerver/openapi/zulip.yaml
  zerver/tests/test_home.py
  zerver/tests/test_sessions.py
  zerver/views/message_fetch.py
Labels: size: L

#18866 /activity: Rename effective rate column to rate
  templates/analytics/realm_summary_table.html
Labels: size: XS

#18867 context_processors: Add test for `get_apps_page_url`.
  zerver/context_processors.py
  zerver/tests/test_docs.py
Labels: size: S

#18806 apidocs: Migrate admin_config out of templates.
  templates/zerver/api/create-custom-profile-field.md
  templates/zerver/api/create-user.md
  templates/zerver/api/delete-message.md
  templates/zerver/api/reorder-custom-profile-fields.md
  zerver/openapi/markdown_extension.py
  zerver/openapi/openapi.py
  zerver/openapi/zulip.yaml
Labels: size: M

#18873 minor: Remove irrelevant comments in stream_edit.js.
  static/js/stream_edit.js
Labels: size: XS

#16860 linkifiers: Add joint validation for linkifier urls and patterns.
  frontend_tests/puppeteer_tests/realm-linkifier.ts
  zerver/migrations/0330_linkifier_pattern_validator.py
  zerver/models.py
  zerver/tests/test_realm_linkifiers.py
Labels: size: XL

#16670 [WIP] email-mirror-postfix: Choose scheme based on http_only config.
  scripts/lib/email-mirror-postfix
Labels: size: S

#17580 Ignore non-delimiter '--' in email mirror `filter_footer`
  zerver/lib/email_mirror.py
  zerver/tests/test_email_mirror.py
Labels: size: S

#18900 timerender: Render past time till 24 hours before showing yesterday.
  frontend_tests/node_tests/timerender.js
  static/js/timerender.js
Labels: size: S

#18889 models: Update `group_match_regex` to correctly detect parameters in `url_format_string`.
  zerver/models.py
Labels: size: XS

#18842 Allow `clean_unused_cache` to run on `purge-old-deployments`.
  scripts/lib/clean_yarn_cache.py
  scripts/purge-old-deployments
Labels: size: S

#18886 Fix stream list bug in user info modal
  frontend_tests/node_tests/stream_data.js
  static/js/popovers.js
  static/js/stream_data.js
Labels: size: L

#18909 manage: Restore `changepassword` back to documented_commands.
  manage.py
Labels: size: XS

#18808 Add support for resolving a topic
  static/js/stream_popover.js
  static/templates/topic_sidebar_actions.hbs
  zerver/lib/actions.py
  zerver/tests/test_message_edit.py
Labels: size: XL

#18911 templates: Remove form-inline class from stream setting forms.
  static/templates/stream_creation_form.hbs
  static/templates/stream_member_list_entry.hbs
  static/templates/subscription_members.hbs
Labels: size: S

#18913 billing: Move exempt_from_from_license_number_check to Customer model.
  corporate/lib/registration.py
  corporate/migrations/0011_move_exempt_from_from_license_number_check_to_customer_model.py
  corporate/models.py
Labels: size: M

#18908 popovers: Close user popover when clicked on stream name.
  static/js/popovers.js
  static/templates/user_stream_list_item.hbs
Labels: size: S

#18923 lightbox_overlay: Fix `&` not being rendered as desired.
  static/templates/lightbox_overlay.hbs
Labels: size: XS

#18924 github-actions: Ensure cancel previous run job never fails.
  .github/workflows/cancel-previous-runs.yml
Labels: size: XS

#18740 ci: Add production upgrade check.
  .github/workflows/production-suite.yml
  tools/ci/production-build
  tools/ci/production-upgrade
Labels: size: XL

#18930 user_deactivation: Move modal_parent one level up in confirm_dialog.
  static/js/settings_users.js
Labels: area: settings (admin/org), bug, size: XS

#18934 lightbox_overlay: “Pan and Zoom” → “Pan & zoom”
  static/templates/lightbox_overlay.hbs
Labels: size: XS

#18920 upload: Cache the boto client to improve performance.
  zerver/lib/upload.py
Labels: area: performance, area: uploads, bug, priority: critical, size: L

#18864 zjsunit: Undo mock_cjs abstraction violation again
  frontend_tests/zjsunit/namespace.js
Labels: size: M

#18958 js: Export variables instead of setting them on window.
  static/js/blueslip.ts
  static/js/global.d.ts
  static/js/page_params.ts
  static/js/zulip_test.js
Labels: size: S

#18950 queue_processor: Add langauge to the events added to invites queue.
  zerver/lib/actions.py
  zerver/tests/test_queue_worker.py
  zerver/worker/queue_processors.py
Labels: size: M

#18963 import_realm: Fix stream `rendered_description` not being set while importing a realm.
  zerver/lib/import_realm.py
Labels: size: XS

#18964 settings: Use confirm_dialog for deactivating own account modal.
  static/js/settings_account.js
  static/templates/confirm_dialog/confirm_deactivate_own_user.hbs
  static/templates/settings/account_settings.hbs
Labels: size: XL

#18971 tippyjs: Fix traceback on reaction tooltip.
  static/js/tippyjs.js
Labels: size: S

#18918 hashchange: Show default view when the hash is unknown.
  frontend_tests/node_tests/hashchange.js
  static/js/hashchange.js
Labels: size: S

#18972 popovers: Extract user_profile_modal functions in separate module.
  static/js/click_handlers.js
  static/js/popovers.js
  static/js/settings_account.js
  static/js/user_profile.js
  tools/test-js-with-node
Labels: size: XL

#18980 webhooks/slack_incoming: Update regex to correctly convert emphasis.
  zerver/webhooks/slack_incoming/fixtures/actions.json
  zerver/webhooks/slack_incoming/tests.py
  zerver/webhooks/slack_incoming/view.py
Labels: size: S

#18978 settings: Show spinner inside the confirm button for confirm_dialog.
  frontend_tests/puppeteer_tests/delete-message.ts
  static/js/confirm_dialog.js
  static/styles/settings.css
  static/templates/confirm_dialog.hbs
Labels: size: M

#18975 topic_sidebar: Add support to copy topic link to clipboard.
  static/js/stream_popover.js
  static/templates/topic_sidebar_actions.hbs
Labels: area: left-sidebar, size: M

#18983 styles: Fix line-height of delete button of image-upload-widget.
  static/styles/image_upload_widget.css
Labels: size: XS

#18991 ci: Remove superfluous generate-dockerfiles template system
  tools/ci/Dockerfile
  tools/ci/Dockerfile.prod
  tools/ci/build-docker-images
  tools/ci/generate-dockerfiles
  tools/ci/images.yml
Labels: size: L

#18982 compose: Split compose.js - move compose_error outside it.
  frontend_tests/node_tests/compose_error.js
  static/js/compose.js
  static/js/compose_error.js
  static/js/reminder.js
Labels: size: XL

#18997 lint: Add .bash extension for tools/lib/git-tools.bash
  tools/lib/git-tools.bash
  tools/lint
Labels: size: M

#18994 install: Replace wget with curl
  docs/production/install-existing-server.md
  docs/production/install.md
  docs/production/upgrade-or-modify.md
  docs/tutorials/shell-tips.md
  puppet/zulip/manifests/profile/base.pp
  scripts/lib/build-pgroonga
  scripts/lib/install
  scripts/lib/install-node
  scripts/lib/setup-apt-repo
  scripts/setup/apt-repos/zulip/custom.sh
  scripts/setup/sha256-tarball-to
  templates/zerver/help/desktop-app-install-guide.md
  tools/ci/.gitattributes
  tools/ci/Dockerfile.prod
  tools/ci/production-build
  tools/ci/production-verify
  tools/ci/success-http-headers.template.debian.txt
  tools/ci/success-http-headers.template.txt
  tools/lib/provision.py
  tools/linter_lib/custom_check.py
  tools/setup/bootstrap-aws-installer
  tools/setup/bootstrap-awscli
  tools/setup/install-shellcheck
  tools/setup/install-shfmt
  tools/test-install/prepare-base
Labels: size: XL

#19013 js: Simplify more code using default parameters and destructuring
  static/js/loading.js
  static/js/message_viewport.js
  static/js/unread_ops.js
Labels: size: S

#19014 js: Remove ancient IE createTextRange API
  static/js/click_handlers.js
  static/js/subs.js
  static/js/ui_util.js
Labels: size: M

#18999 settings: Remove intentional waiting time in deactivate account request.
  static/js/settings_account.js
Labels: size: L

#19025 node tests: Use mock_template in rendered_markdown.
  frontend_tests/node_tests/rendered_markdown.js
Labels: size: S

#19018 install-yarn: Rewrite Yarn installer
  docs/subsystems/dependencies.md
  scripts/lib/install
  scripts/lib/install-node
  scripts/lib/install-yarn
  scripts/lib/setup_venv.py
  scripts/lib/third/install-yarn.sh
  scripts/lib/upgrade-zulip-stage-2
  tools/lib/provision.py
  tools/linter_lib/exclude.py
Labels: size: XL

#19016 tippy: Clarify how to use `tippy-zulip-tooltip` class.
  static/js/tippyjs.js
Labels: size: S

#19021 info_overlay: Render keyboard shortcuts using info_overlay.
  static/js/info_overlay.js
  static/templates/keyboard_shortcuts.hbs
  templates/zerver/app/index.html
  tools/linter_lib/custom_check.py
  zerver/tests/test_home.py
Labels: size: XL

#19030 Make mock_template more fine-grained.
  frontend_tests/node_tests/activity.js
  frontend_tests/node_tests/alert_words_ui.js
  frontend_tests/node_tests/compose.js
  frontend_tests/node_tests/compose_validate.js
  frontend_tests/node_tests/compose_video.js
  frontend_tests/node_tests/composebox_typeahead.js
  frontend_tests/node_tests/drafts.js
  frontend_tests/node_tests/i18n.js
  frontend_tests/node_tests/input_pill.js
  frontend_tests/node_tests/pill_typeahead.js
  frontend_tests/node_tests/poll_widget.js
  frontend_tests/node_tests/popovers.js
  frontend_tests/node_tests/reactions.js
  frontend_tests/node_tests/recent_topics.js
  frontend_tests/node_tests/rendered_markdown.js
  frontend_tests/node_tests/settings_org.js
  frontend_tests/node_tests/settings_profile_fields.js
  frontend_tests/node_tests/settings_user_groups.js
  frontend_tests/node_tests/stream_edit.js
  frontend_tests/node_tests/stream_list.js
  frontend_tests/node_tests/subs.js
  frontend_tests/node_tests/typeahead_helper.js
  frontend_tests/zjsunit/namespace.js
  frontend_tests/zjsunit/test.js
Labels: size: XL

#19036 quote-and-reply: Add tests for caret position.
  frontend_tests/node_tests/compose_ui.js
Labels: size: L

#18996 bootstrap-awscli: Remove executable bit.
  tools/setup/bootstrap-aws-installer
  tools/setup/bootstrap-awscli.sh
  tools/setup/install-aws-server
Labels: size: S

#19035 buddy list: Always include "me" in the list.
  frontend_tests/node_tests/buddy_data.js
  static/js/buddy_data.js
Labels: size: S

#19043 puppet: Catch when a comma is left out of puppet_classes.
  scripts/zulip-puppet-apply
Labels: size: XS

#18892 billing: Document model fields that are not self explanatory
  corporate/models.py
Labels: size: M

#19037 docs: Remove BETA label for widget docs.
  docs/subsystems/widgets.md
Labels: size: S

#17082 compose-box: Fix compose-box from covering last messages of stream.
  frontend_tests/node_tests/compose_actions.js
  static/js/compose_actions.js
  static/js/resize.js
Labels: area: compose, bug, size: M

#19045 user_status: Fix styling of modal.
  static/styles/user_status.css
Labels: size: S

#19032 hashchange: Don't narrow to default_view on `#reload`.
  frontend_tests/node_tests/hashchange.js
  static/js/hashchange.js
Labels: size: S

#19023 logo: Compute realm-logo url in frontend only.
  static/js/ui_init.js
  templates/zerver/app/navbar.html
  zerver/tests/test_home.py
  zerver/views/home.py
Labels: area: settings (admin/org), area: settings UI, bug, size: L

#18957 Show ignored deactivated users when they are being added to streams.
  frontend_tests/node_tests/stream_edit.js
  static/js/stream_edit.js
  static/templates/stream_subscription_info.hbs
Labels: size: XL

#19020 webhooks: Support configuring destination stream by id.
  zerver/lib/actions.py
  zerver/lib/webhooks/common.py
  zerver/tests/test_webhooks_common.py
Labels: size: L

#19061 stream settings: Rename stream_subscription_info to stream_subscription_request_result for readability.
  frontend_tests/node_tests/stream_edit.js
  static/js/stream_edit.js
  static/styles/subscriptions.css
  static/templates/stream_subscription_request_result.hbs
  static/templates/subscription_members.hbs
Labels: size: M

#19012 Issue#18713: tag redacted message for i18n
  zerver/lib/push_notifications.py
  zerver/tests/test_push_notifications.py
Labels: size: L
