Repository zulip/zulip, pull requests merged in 2022-02, with the labels that each got.

#21009 stream_settings: Fix color of icon of the title in right column.
  static/js/stream_settings_ui.js
  static/templates/stream_settings/selected_stream_title.hbs
Labels: size: S

#21007 docs: Clarify that only issues tagged "help wanted" should be claimed.
  CONTRIBUTING.md
Labels: size: M

#21002 settingsUI: Fix the UI of Authentication settings.
  static/styles/settings.css
  static/templates/settings/admin_auth_methods_list.hbs
Labels: size: S

#20977 resolve topic: Limit unread flag on automated notifications.
  templates/zerver/help/resolve-a-topic.md
  zerver/lib/actions.py
  zerver/lib/message.py
  zerver/tests/test_message_edit.py
Labels: size: L

#20673 compose: Add alert for resolved topic
  frontend_tests/node_tests/compose_validate.js
  static/js/compose.js
  static/js/compose_actions.js
  static/js/compose_validate.js
  static/js/message_events.js
  static/styles/compose.css
  static/templates/compose.hbs
  static/templates/compose_resolved_topic.hbs
Labels: size: XL

#21023 Improve how Zulip displays wordle
  frontend_tests/node_tests/emoji_picker.js
  tools/setup/emoji/emoji_names.py
  zerver/lib/markdown/__init__.py
Labels: size: S

#21022 api_docs: Add check for extra `additionalProperties` in return vals.
  zerver/lib/markdown/api_return_values_table_generator.py
Labels: size: S

#21020 typeahead: Fix typeahead for custom selection triggers.
  static/third/bootstrap-typeahead/typeahead.js
Labels: size: S

#21026 Changes to the jobs page
  templates/corporate/jobs.html
Labels: size: XL

#21028 buddy_data: Remove unused huddle_fraction_present function.
  frontend_tests/node_tests/buddy_data.js
  static/js/buddy_data.js
  static/js/presence.js
Labels: size: L

#21027 markdown: Use built-in hex formatting for unicode_emoji_to_codepoint
  zerver/lib/markdown/__init__.py
Labels: size: XS

#21031 emoji: Make large square emoji names consistent.
  tools/setup/emoji/emoji_names.py
Labels: size: XS

#20757 Fix poll title editing button to place it in the same line
  static/styles/widgets.css
Labels: size: XS

#21021 left-sidebar: Allow upto 2 lines for PMs
  static/styles/left_sidebar.css
Labels: size: S

#21038 scim: Upgrade to django-scim2 0.17.1.
  requirements/dev.txt
  requirements/prod.txt
  version.py
  zerver/lib/scim.py
  zerver/tests/test_scim.py
  zproject/urls.py
Labels: size: XL

#21039 docs: Minor grammar fix in settings.py upgrade docs.
  docs/production/upgrade-or-modify.md
Labels: size: S

#20852 right_sidebar: Add realm description for spectators.
  static/js/ui_init.js
  static/styles/app_components.css
  static/styles/dark_theme.css
  static/styles/right_sidebar.css
  static/templates/right_sidebar.hbs
Labels: size: M

#21060 migrations: Fix typo in 0099 reverse_sql
  zerver/migrations/0099_index_wildcard_mentioned_user_messages.py
Labels: size: XS

#21057 docs: Add missing space to compound verbs “back up”, “log in”, etc.
  docs/documentation/overview.md
  docs/production/authentication-methods.md
  docs/subsystems/billing.md
  scripts/lib/setup_venv.py
  scripts/lib/upgrade-zulip-stage-2
  static/js/message_list_view.js
  static/js/search_suggestion.js
  static/js/spectators.js
  static/js/topic_list.js
  templates/zerver/for-business.html
  templates/zerver/help/code-blocks.md
  templates/zerver/help/include/advantages-of-self-hosting-zulip.md
  templates/zerver/help/saml-authentication.md
  templates/zerver/help/scim.md
  templates/zerver/help/setting-up-zulip-for-a-class.md
  zerver/management/commands/delete_realm.py
  zerver/tests/test_auth_backends.py
  zerver/tests/test_event_system.py
  zerver/tests/test_home.py
  zproject/backends.py
  zproject/prod_settings_template.py
Labels: size: L

#21066 push_notifications: Fix for aioapns 2.1
  zerver/lib/push_notifications.py
  zerver/tests/test_push_notifications.py
Labels: size: M

#21065 puppet: Fix typo in uwsgi exporter dependency.
  puppet/zulip_ops/manifests/prometheus/uwsgi.pp
Labels: size: XS

#21063 push_notifications: Don't open unnecessary APNs connections.
  zerver/lib/push_notifications.py
Labels: size: XS

#20938 modal: Add support for event handler on closing a modal.
  static/js/dialog_widget.js
  static/js/overlays.js
Labels: size: S

#21019 test_message_fetch: Reorganize web-public tests.
  zerver/tests/test_message_fetch.py
Labels: area: testing-coverage, size: XL, release goal, area: web-public streams

#21074 help center: Make it easier to learn that any auth method will work.
  templates/zerver/help/include/how-to-invite-users-to-join.md
Labels: size: S

#21080 puppeteer_tests: Try to fix subscriptions flake.
  frontend_tests/puppeteer_tests/subscriptions.ts
Labels: size: S

#21079 Fix focus behavior when closing stream permissions modal.
  static/templates/stream_settings/stream_settings.hbs
Labels: size: XS

#21078 portico: Update /for/business page title and tagline.
  templates/zerver/for-business.html
Labels: size: S

#21048 drafts: Use simplebar.
  static/styles/drafts.css
  static/templates/draft_table_body.hbs
Labels: size: S

#21054 settings: Fix browser back button not working in settings overlay.
  static/js/hashchange.js
Labels: bug, area: settings UI, size: S, release goal

#21053 Throw an error when EMAIL_HOST_USER is specified but not email_password
  zerver/lib/send_email.py
  zerver/tests/test_send_email.py
Labels: area: production installer, size: M, release goal

#19760 message_editing : Fix topic edit propagate option cut-off
  static/styles/zulip.css
  static/templates/message_edit_form.hbs
Labels: size: M

#21059 topic: Return JsonableError for race condition in topic mute.
  zerver/tests/test_muting_topics.py
  zerver/views/muting.py
Labels: bug, size: S

#21071 stream_color: Fix stream color not updating to default
  static/js/stream_color.js
Labels: size: S

#20579 upload: Add command to reupload all custom emoji.
  tools/semgrep.yml
  zerver/lib/upload.py
  zerver/migrations/0376_set_realmemoji_author_and_reupload_realmemoji.py
  zerver/worker/queue_processors.py
Labels: size: XL

#21104 pgroonga: Disable PGroonga in development to fix CI.
  tools/coveragerc
  zerver/tests/test_message_fetch.py
  zerver/views/message_fetch.py
  zproject/dev_settings.py
Labels: size: S

#21086 timezone: List only canonical timezone identifiers
  tools/setup/build_timezone_values
  version.py
  zerver/lib/actions.py
  zerver/lib/create_user.py
  zerver/lib/events.py
  zerver/lib/validator.py
  zerver/tests/test_settings.py
  zerver/tests/test_signup.py
Labels: size: S

#21111 test_new_users: Select test emails deterministically
  zerver/tests/test_new_users.py
Labels: size: S

#21108 configure-rabbitmq: Use rabbitmqctl ping
  scripts/setup/configure-rabbitmq
Labels: size: S

#21120 api docs: replace `subject` with `topic` for Curl
  templates/zerver/api/send-message.md
Labels: size: XS

#21100 compose_control_buttons: Move GIF button out of the popover.
  static/templates/compose_control_buttons.hbs
  static/templates/compose_control_buttons_in_popover.hbs
Labels: size: XS

#21110 message feed: Don't share headers for non-adjacent messages.
  frontend_tests/node_tests/filter.js
  static/js/filter.js
  static/js/message_list.js
  static/js/narrow.js
Labels: size: L

#21113 tippy: Make background color of tooltips close to black.
  static/styles/zulip.css
Labels: size: M

#21126 message-menu: Add tabindex attribute for anchor tag to allow focus.
  static/templates/actions_popover_content.hbs
  static/templates/gear_menu.hbs
  static/templates/left_sidebar.hbs
  static/templates/more_topics.hbs
  static/templates/navbar.hbs
  static/templates/remind_me_popover_content.hbs
  static/templates/settings/admin_invites_list.hbs
  static/templates/settings/admin_user_list.hbs
  static/templates/stream_settings/new_stream_users.hbs
  static/templates/topic_sidebar_actions.hbs
Labels: size: L, release goal

#21131 provision: Use apt-get --allow-downgrades
  tools/lib/provision.py
Labels: size: XS, backport candidate

#21129 migrations: Don't push events to deferred_work queue if TEST_SUITE.
  zerver/migrations/0376_set_realmemoji_author_and_reupload_realmemoji.py
Labels: size: S

#21139 bots: Do not allow removing owner from UI.
  static/templates/settings/admin_bot_form.hbs
Labels: bug, area: bots, area: settings UI, size: XS, release goal

#21052 typeahead: Ignore mouse position for selection until it's moved.
  frontend_tests/puppeteer_lib/common.ts
  frontend_tests/puppeteer_tests/admin.ts
  static/third/bootstrap-typeahead/typeahead.js
Labels: bug, area: compose, area: search, priority: high, size: M

#21138 stream_settings: Ignore hover on actions column in tables(dark theme)
  static/styles/dark_theme.css
Labels: bug, area: settings (user), area: stream settings, area: settings (admin/org), size: XS

#21162 upgrade: Log the commit hash and directory when upgrading.
  scripts/lib/upgrade-zulip-from-git
Labels: size: S

#21118 UI-Improvement: Wrap longer tooltips.
  static/styles/zulip.css
Labels: size: XS

#21161 auth: Some kwargs fixes
  zerver/views/auth.py
Labels: size: S

#21150 docs: Remove highlight parameters from links
  docs/tutorials/life-of-a-request.md
  docs/tutorials/new-feature-tutorial.md
  zerver/lib/alert_words.py
Labels: size: S

#21172 Make avatars in Recent Topics open user info popover on click.
  static/js/click_handlers.js
  static/styles/recent_topics.css
  static/templates/recent_topic_row.hbs
Labels: size: S, area: recent-topics, UX

#21185 tippy: Only change background color of tooltips with no theme.
  static/styles/zulip.css
Labels: size: XS

#21152 provision: Binary-patch OpenSSL ARM64 assembly bug
  tools/lib/provision.py
Labels: area: provision, size: S

#20989 streams: Update formatting of retention change notification.
  zerver/lib/actions.py
  zerver/tests/test_subs.py
Labels: size: L

#21151 deliver_scheduled_emails: Lock and send emails one-at-a-time.
  zerver/management/commands/deliver_scheduled_emails.py
Labels: area: production, area: emails, size: M

#21186 Change icon of message formatting popover in compose.
  static/styles/compose.css
  static/templates/compose_control_buttons.hbs
  static/templates/compose_control_buttons_in_popover.hbs
Labels: size: S

#21092 Spectator view improvements.
  static/js/click_handlers.js
  static/js/dark_theme.js
  static/js/dark_theme.ts
  static/js/ui_init.js
  static/styles/dark_theme.css
  static/styles/zulip.css
  static/templates/gear_menu.hbs
  tools/test-js-with-node
Labels: size: XL

#19937 message_scroll: Show scroll to bottom button.
  frontend_tests/node_tests/compose.js
  frontend_tests/node_tests/compose_video.js
  static/js/click_handlers.js
  static/js/compose.js
  static/js/compose_ui.js
  static/js/message_scroll.js
  static/js/tippyjs.js
  static/js/ui_init.js
  static/styles/compose.css
  static/styles/dark_theme.css
  static/styles/zulip.css
  static/templates/compose.hbs
Labels: size: XL

#21181 left-sidebar: Align `more-topics` li item with other topic names.
  static/styles/left_sidebar.css
Labels: size: XS

#21189 deliver_scheduled_emails: Sleep 10s.
  zerver/management/commands/deliver_scheduled_emails.py
Labels: size: M

#21191 url_preview: Only return image URLs that validate as URLs.
  zerver/lib/url_preview/parsers/generic.py
  zerver/lib/url_preview/parsers/open_graph.py
  zerver/tests/test_link_embed.py
Labels: size: L

#21202 api docs: Fix generate_api_description copy+paste error
  templates/zerver/api/mark-all-as-read.md
Labels: size: XS

#21200 docs: Update internationalization statement in new feature tutorial.
  docs/tutorials/new-feature-tutorial.md
Labels: size: XS

#21203 Refactor code to get users using email.
  zerver/lib/users.py
  zerver/views/users.py
Labels: size: L

#21199 settings: Show or hide digest weekday option on changing emails setting.
  static/js/settings_org.js
Labels: size: S

#21205 api: Include `realm_web_public_access_enabled` in server settings.
  templates/zerver/api/changelog.md
  version.py
  zerver/openapi/zulip.yaml
  zerver/tests/test_auth_backends.py
  zerver/views/auth.py
Labels: size: S

#21210 help_docs: Document Markdown stream/topic auto-linking feature (update).
  templates/zerver/help/format-your-message-using-markdown.md
  templates/zerver/help/link-to-a-message-or-conversation.md
Labels: area: documentation (user), priority: high, size: L

#21190 popovers: Add "busy" status to default emoji status set.
  frontend_tests/puppeteer_tests/user-status.ts
  static/js/user_status_ui.js
Labels: priority: high, size: S, area: popovers

#21141 Minor improvements to web public.
  zerver/lib/users.py
  zerver/tests/test_home.py
Labels: size: M

#21192 populate_db: Add timezones for some test users.
  version.py
  zerver/tests/test_example.py
  zerver/tests/test_populate_db.py
  zilencer/management/commands/populate_db.py
Labels: size: M

#21219 docs: Use topic actions for move topic to diff. stream.
  templates/zerver/help/move-content-to-another-stream.md
Labels: size: XS

#21221 docs: Use Debian and Ubuntu version numbers over development codenames
  .github/workflows/production-suite.yml
  .github/workflows/zulip-ci.yml
  docs/overview/changelog.md
  docs/production/upgrade-or-modify.md
  puppet/zulip_ops/templates/munin/munin.conf.erb
  tools/ci/Dockerfile.prod
  tools/lib/provision.py
Labels: size: L

#21218 capitalization: Clean up IGNORED_PHRASES
  tools/lib/capitalization.py
  tools/tests/test_capitalization_checker.py
Labels: size: XL

#21235 docs: Add missing space in “time zone”
  analytics/lib/counts.py
  analytics/management/commands/check_analytics_state.py
  analytics/management/commands/update_analytics_counts.py
  analytics/tests/test_counts.py
  corporate/views/billing_page.py
  docs/contributing/code-style.md
  docs/contributing/summer-with-zulip.md
  docs/overview/changelog.md
  frontend_tests/node_tests/composebox_typeahead.js
  requirements/common.in
  static/.gitignore
  static/js/composebox_typeahead.js
  static/js/rendered_markdown.js
  static/js/timerender.ts
  templates/zerver/help/change-your-timezone.md
  templates/zerver/help/format-your-message-using-markdown.md
  templates/zerver/help/include/sidebar_index.md
  templates/zerver/help/using-zulip-for-a-class.md
  templates/zerver/why-zulip.md
  tools/setup/emoji/emoji_names.py
  tools/update-prod-static
  zerver/lib/actions.py
  zerver/lib/create_user.py
  zerver/lib/events.py
  zerver/lib/timestamp.py
  zerver/models.py
  zerver/openapi/zulip.yaml
  zerver/tests/test_message_send.py
  zerver/tests/test_populate_db.py
  zerver/tests/test_signup.py
  zerver/tests/test_timestamp.py
  zilencer/management/commands/populate_db.py
  zproject/computed_settings.py
Labels: size: XL

#21236 docs: Fix list item indentation mistake
  docs/production/deployment.md
Labels: size: S

#20373 Add `Manage this user` option in user-info popover for admins.
  static/js/settings_users.js
  static/templates/settings/admin_human_form.hbs
Labels: size: L

#21240 Add `width` CSS property in filter check icon for recent-topics table
  static/styles/recent_topics.css
Labels: size: XS

#21247 ci: Test upgrades from 4.10.
  .github/workflows/production-suite.yml
  tools/ci/build-docker-images
Labels: size: S

#21169 recent_topics: Show loading indicator before fetching initial messages.
  frontend_tests/node_tests/message_fetch.js
  static/js/message_fetch.js
  static/js/recent_topics_ui.js
  static/styles/dark_theme.css
  static/styles/recent_topics.css
  static/templates/recent_topics_table.hbs
  templates/zerver/app/index.html
Labels: size: L

#19830 recent_topics: Standardize format of last message time.
  frontend_tests/node_tests/recent_topics.js
  frontend_tests/node_tests/timerender.js
  static/js/recent_topics_ui.js
  static/js/timerender.ts
Labels: priority: high, size: XL, area: recent-topics

#20877 left_sidebar: Swap "Recent topics" with "Private messages".
  static/templates/left_sidebar.hbs
Labels: area: left-sidebar, priority: high, size: S, release goal

#21096 drafts: Use simplebar.
  static/js/drafts.js
  static/styles/drafts.css
  static/templates/draft_table_body.hbs
Labels: size: S
