Repository zulip/zulip, pull requests merged in 2022-03, with the labels that each got.

#21269 docs: Fix Git capitalization
  docs/git/setup.md
  docs/git/troubleshooting.md
  docs/git/using.md
  docs/testing/linters.md
  docs/testing/mypy.md
  tools/documentation_crawler/documentation_crawler/spiders/common/spiders.py
  tools/lib/provision_inner.py
Labels: size: M

#21257 documentation: Fix a typo in gSoc.md
  docs/contributing/gsoc.md
Labels: size: XS

#21263 settings: Values retrieve fix when we edit custom external account type custom profile fields.
  static/js/settings_profile_fields.js
Labels: size: S

#21278 icons: Replace fa-globe icon with a custom globe icon.
  static/assets/icons/globe.svg
  static/js/message_view_header.js
  static/styles/compose.css
  static/styles/left_sidebar.css
  static/styles/zulip.css
  static/templates/compose.hbs
  static/templates/navbar_icon_and_title.hbs
  static/templates/recipient_row.hbs
  static/templates/stream_privacy.hbs
  static/templates/stream_settings/stream_privacy_icon.hbs
  static/templates/stream_settings/subscription_setting_icon.hbs
  templates/zerver/help/web-public-streams.md
  templates/zerver/team.html
Labels: size: L

#21287 docs: Fix another case of Git capitalization
  docs/contributing/code-reviewing.md
Labels: size: XS

#21293 tippy: Fix compose box `cancel button` tooltip.
  static/templates/compose.hbs
Labels: size: XS

#21303 ci: Temporarily disable Ubuntu 22.04
  .github/workflows/production-suite.yml
  .github/workflows/zulip-ci.yml
Labels: size: S

#21300 shared: Add flow types for internal_url.
  static/shared/js/internal_url.js.flow
Labels: size: M

#20843 Fix: Hide 'Remove owner' button when there is no owner assigned to the bot.
  frontend_tests/node_tests/dropdown_list_widget.js
  frontend_tests/node_tests/settings_org.js
  static/js/dropdown_list_widget.js
Labels: size: S

#20982 message_feed_ui: Make unread marker line continuous.
  static/styles/zulip.css
Labels: design, priority: high, size: XS, area: message feed UI

#21243 puppeteer flake: Remove call to test_change_password().
  frontend_tests/puppeteer_tests/settings.ts
Labels: size: S

#21301 tippyjs: Avoid unsafe allowHTML API in favor of <template> elements
  frontend_tests/node_tests/rendered_markdown.js
  static/js/click_handlers.js
  static/js/popover_menus.js
  static/js/rendered_markdown.js
  static/js/timerender.ts
  static/js/tippyjs.js
  static/js/ui_util.ts
  static/templates/compose.hbs
  static/templates/compose_control_buttons.hbs
  static/templates/recent_topic_row.hbs
  static/templates/right_sidebar.hbs
  tools/linter_lib/custom_check.py
Labels: size: XL

#21305 puppeteer: Resurrect test_change_password.
  frontend_tests/puppeteer_tests/settings.ts
Labels: size: S

#21227 lightbox: Remove Pan/Zoom enable button.
  static/js/lightbox.js
  static/styles/lightbox.css
  static/templates/lightbox_overlay.hbs
Labels: bug, area: general UI, size: XL

#21315 docs: Add a section on code review communication style.
  docs/contributing/code-reviewing.md
Labels: size: S

#21317 tooling: test-js-with-puppeteer: Accept full relative file path.
  tools/lib/test_script.py
Labels: size: S

#21321 internal_url: Replace all replaceAll with replace.
  static/shared/js/internal_url.js
Labels: size: XS

#21275 css: Fix hover color for "Edit topic" icon in message bar
  static/styles/zulip.css
Labels: size: S

#19984 New landing page about self-hosting Zulip
  README.md
  docs/production/index.md
  docs/production/install.md
Labels: size: XL

#21320 settings: Make list header sections consistent.
  static/styles/settings.css
  static/templates/settings/alert_word_settings.hbs
  static/templates/settings/attachments_settings.hbs
  static/templates/settings/bot_list_admin.hbs
  static/templates/settings/data_exports_admin.hbs
  static/templates/settings/deactivated_users_admin.hbs
  static/templates/settings/default_streams_list_admin.hbs
  static/templates/settings/emoji_settings_admin.hbs
  static/templates/settings/invites_list_admin.hbs
  static/templates/settings/linkifier_settings_admin.hbs
  static/templates/settings/muted_topics_settings.hbs
  static/templates/settings/muted_users_settings.hbs
  static/templates/settings/playground_settings_admin.hbs
  static/templates/settings/profile_field_settings_admin.hbs
  static/templates/settings/user_list_admin.hbs
Labels: size: XL

#21331 install: Desupport Ubuntu 22.04 for now
  docs/development/setup-advanced.md
  docs/development/setup-vagrant.md
  docs/production/requirements.md
  scripts/lib/install
Labels: size: S

#21327 tests: Mark test_migrations as disabled.
  zerver/tests/test_migrations.py
Labels: size: S

#21343 tests: Avoid use of Python internal __unittest_skip__ flag
  zerver/tests/test_auth_backends.py
  zerver/tests/test_rate_limiter.py
Labels: size: M

#21233 stream create: Modernize create-stream add-subscribers UI.
  frontend_tests/node_tests/people.js
  frontend_tests/node_tests/stream_create_subscribers_data.js
  frontend_tests/puppeteer_tests/subscriptions.ts
  static/js/people.js
  static/js/stream_create.js
  static/js/stream_create_subscribers.js
  static/js/stream_create_subscribers_data.js
  static/js/zulip_test.js
  static/styles/subscriptions.css
  static/styles/zulip.css
  static/templates/new_stream_user.hbs
  static/templates/stream_settings/add_subscribers_form.hbs
  static/templates/stream_settings/new_stream_user.hbs
  static/templates/stream_settings/new_stream_users.hbs
  static/templates/stream_settings/stream_creation_form.hbs
  tools/test-js-with-node
Labels: size: XL

#21324 realm field should be unique in RealmUserDefault
  zerver/migrations/0378_alter_realmuserdefault_realm.py
  zerver/models.py
Labels: size: S

#21289 styles: Fix some invalid CSS
  static/styles/dark_theme.css
  static/styles/settings.css
  static/styles/user_circles.css
  static/styles/zulip.css
Labels: size: S

#21362 fixed browser autocomplete in Recent topics filter
  static/templates/recent_topics_table.hbs
Labels: size: XS

#21359 settings_users: Do not allow sorting by email if emails are hidden.
  static/js/admin.js
  static/templates/settings/deactivated_users_admin.hbs
  static/templates/settings/user_list_admin.hbs
Labels: size: XS

#21365 restart-server: Check if service is running before restart, vs start.
  scripts/restart-server
Labels: size: S

#21366 i18n: Remove quote syntax from stream description notification.
  zerver/lib/actions.py
  zerver/tests/test_subs.py
  zerver/views/streams.py
Labels: size: M

#21351 compose: Show topic required error if topic is "(no topic)".
  frontend_tests/node_tests/compose_validate.js
  static/js/compose_validate.js
Labels: bug, area: compose, priority: high, size: S, release goal

#21174 url_preview: Fix 'Edited' notification for url preview events.
  static/js/message_events.js
Labels: size: S

#21370 [4.x] provision: Install non-PGDG PGroonga package in development environment
  tools/lib/provision.py
Labels: size: XS

#21372 unread: Remove unused client parameter.
  analytics/tests/test_counts.py
  zerver/lib/actions.py
  zerver/tests/test_events.py
  zerver/tests/test_push_notifications.py
  zerver/views/message_flags.py
Labels: size: M

#21373 edit_history: Update simulated edit history entries in front end.
  static/js/message_events.js
Labels: size: S

#21075 message_edit: Don't display resolved topics as MOVED.
  frontend_tests/node_tests/message_list_view.js
  static/js/message_events.js
  static/js/message_list_view.js
Labels: bug, area: message-editing, priority: high, size: XL, release goal, area: message feed display

#21371 Update droplet creation
  tools/droplets/create.py
Labels: size: M

#21375 api_docs: Refactor of `MessagesBase` schema.
  zerver/openapi/zulip.yaml
Labels: size: XL

#21377 message flags: Extract create_historical_user_messages.
  zerver/lib/actions.py
  zerver/tests/test_message_flags.py
Labels: size: L

#21337 unread: Improve aggregated message info.
  frontend_tests/node_tests/unread.js
  static/js/unread.js
  templates/zerver/api/changelog.md
  version.py
  zerver/lib/message.py
  zerver/openapi/zulip.yaml
  zerver/tests/test_message_flags.py
Labels: size: L

#21196 compose: Fix saving of drafts on switching to PM.
  static/js/compose_actions.js
Labels: bug, area: compose, size: XS

#21360 compose: Fix the working of 'c' and 'x' hotkeys during composing.
  static/js/hotkey.js
Labels: bug, area: compose, priority: high, size: S, release goal

#21386 portico: Create use cases index page.
  templates/zerver/for/use-cases.md
  templates/zerver/use-cases.html
  zerver/tests/test_docs.py
  zproject/urls.py
Labels: size: L

#21382 settings: Add web-public streams beta subdomain list.
  zerver/lib/events.py
  zerver/models.py
  zerver/tests/test_realm.py
  zproject/default_settings.py
Labels: size: S

#21389 icons: Clean up globe icon
  static/assets/icons/globe.svg
Labels: size: M

#21391 api: Send full message in GET /messages/{message_id} response.
  templates/zerver/api/changelog.md
  templates/zerver/help/include/rest-endpoints.md
  version.py
  zerver/openapi/zulip.yaml
  zerver/tests/test_message_edit.py
  zerver/views/message_edit.py
Labels: size: XL

#21397 shared: Add flow types for typeahead module.
  static/shared/js/typeahead.js.flow
Labels: size: S

#21399 setup-apt-repo: Make hashes file not contain full path.
  scripts/lib/setup-apt-repo
Labels: size: S

#21401 makemessages: Ignore compiled and custom email templates
  zerver/management/commands/makemessages.py
Labels: size: XS

#21411 upgrade: Skip re-checking of new bots on upgrade.
  scripts/lib/upgrade-zulip-stage-2
Labels: size: XS

#21400 configure-rabbitmq: Use rabbitmqctl await_online_nodes
  scripts/setup/configure-rabbitmq
Labels: size: S

#21407 help_docs: Document unsubscribe user from stream via profile.
  templates/zerver/help/add-or-remove-users-from-a-stream.md
Labels: area: documentation (user), size: S, release goal

#21425 Pm list : Refactor code and node tests
  frontend_tests/node_tests/pm_list_data.js
Labels: size: S

#21406 help_docs: Add typing notifications privacy setting to doc.
  templates/zerver/help/status-and-availability.md
Labels: area: documentation (user), size: S, release goal

#21339 forms: Remove incorrect use of mark_safe on some errors.
  zerver/forms.py
Labels: size: L, release goal

#21378 puppet: Support password-based PostgreSQL replication, and ssl_mode verification.
  docs/production/deployment.md
  puppet/zulip/manifests/profile/postgresql.pp
  puppet/zulip/templates/postgresql/12/postgresql.conf.template.erb
  puppet/zulip/templates/postgresql/13/postgresql.conf.template.erb
  puppet/zulip/templates/postgresql/14/postgresql.conf.template.erb
  puppet/zulip/templates/postgresql/recovery.conf.template.erb
Labels: size: M

#21176 Support animated PNGs
  zerver/lib/upload.py
  zerver/tests/images/animated_large_img.png
  zerver/tests/test_upload.py
Labels: size: XL

#21429 ci: Test upgrades from 4.11.
  .github/workflows/production-suite.yml
  tools/ci/build-docker-images
Labels: size: S

#21252 mark-as-unread: Add minimal support for 5.0 release.
  frontend_tests/node_tests/dispatch.js
  frontend_tests/node_tests/lib/events.js
  static/js/message_live_update.js
  static/js/people.js
  static/js/server_events_dispatch.js
  static/js/unread.js
  static/js/unread_ops.js
  templates/zerver/api/changelog.md
  version.py
  zerver/lib/actions.py
  zerver/lib/event_schema.py
  zerver/lib/events.py
  zerver/lib/message.py
  zerver/openapi/zulip.yaml
  zerver/tests/test_events.py
  zerver/tests/test_message_flags.py
Labels: size: XL

#21435 requirements: Upgrade Python requirements
  corporate/tests/test_stripe.py
  requirements/common.in
  requirements/dev.in
  requirements/dev.txt
  requirements/docs.txt
  requirements/mypy.in
  requirements/mypy.txt
  requirements/prod.txt
  version.py
  zerver/views/video_calls.py
Labels: size: XL

#21451 Model field type annotation fixes
  zerver/models.py
Labels: size: S

#21455 settings_account: Fix password quality meter
  static/js/settings_account.js
Labels: size: S

#21448 js: Fix no-jquery/no-parse-html-literal
  .eslintrc.json
  frontend_tests/node_tests/components.js
  frontend_tests/node_tests/compose_validate.js
  frontend_tests/node_tests/drafts.js
  frontend_tests/node_tests/narrow.js
  frontend_tests/node_tests/reactions.js
  frontend_tests/node_tests/settings_org.js
  frontend_tests/node_tests/stream_list.js
  frontend_tests/node_tests/timerender.js
  frontend_tests/node_tests/zjquery.js
  static/js/blueslip_stacktrace.ts
  static/js/components.ts
  static/js/flatpickr.js
  static/js/lightbox.js
  static/js/loading.ts
  static/js/notifications.js
  static/js/portico/integrations.js
  static/js/settings_users.js
  static/js/timerender.ts
  static/js/ui_report.ts
Labels: size: XL

#20808 migrations: Add migration to revoke invites from old deactivated users.
  zerver/migrations/0383_revoke_invitations_from_deactivated_users.py
Labels: size: L, release goal

#21442 help_docs: Update how to access drafts in help center doc.
  templates/zerver/help/view-and-edit-your-message-drafts.md
Labels: size: XS

#21476 Fix sub-related puppeteer flakes.
  frontend_tests/puppeteer_lib/common.ts
  frontend_tests/puppeteer_tests/stream_create.ts
  frontend_tests/puppeteer_tests/subscribe_toggle.ts
Labels: size: XL

#21470 Change realm field to be not null in Attachment
  zerver/migrations/0384_alter_realm_not_null.py
  zerver/models.py
  zerver/tests/test_attachments.py
Labels: size: M

#17031 message_edit: Fix unmute of topic when topic name is edited.
  zerver/lib/actions.py
  zerver/lib/user_topics.py
  zerver/tests/test_message_edit.py
Labels: size: XL, release goal

#21478 help_docs: Update instructions for change stream color.
  templates/zerver/help/change-the-color-of-a-stream.md
Labels: size: S

#21475 settings_users: Help center link in deactivate user confirmation modal.
  static/js/settings_users.js
Labels: size: XS

#21334 typeahead: Update / hide typeahead menu on clicking outside.
  static/third/bootstrap-typeahead/typeahead.js
Labels: bug, area: compose, priority: high, size: S

#21436 popovers: Fix incorrect "Manage this user" link for deactivated users.
  frontend_tests/node_tests/popovers.js
  static/js/popovers.js
  static/js/settings_users.js
  static/templates/confirm_dialog/confirm_reactivate_user.hbs
  static/templates/user_info_popover_content.hbs
Labels: size: L

#20760 settings_config: Rename "Unread count summary" to "Unread count badge".
  static/js/settings_config.ts
  zerver/openapi/zulip.yaml
Labels: size: S

#16580 integration: generate dynamic name and higher security for Big Blue Button video calls.
  frontend_tests/node_tests/compose_video.js
  static/js/compose.js
  zerver/openapi/zulip.yaml
  zerver/tests/test_create_video_call.py
  zerver/views/video_calls.py
Labels: size: XL, release goal

#20255 frontend performance: Recent topics to stream renarrows.
  static/js/recent_topics_ui.js
  static/js/resize.js
  static/js/ui_init.js
Labels: size: M, release goal

#21486 integrations: Fix BigBlueButton password length
  zerver/tests/test_create_video_call.py
  zerver/views/video_calls.py
Labels: size: S

#21495 bitbucket3: Fix docs typo Zuilp -> Zulip
  zerver/webhooks/bitbucket3/doc.md
Labels: size: XS

#21460 recent topics: Close Profile popover while muting user.
  static/js/popovers.js
Labels: size: XS

#21444 puppet: Fix the PostgreSQL paths to recovery.conf / standby.conf.
  puppet/zulip/manifests/profile/postgresql.pp
Labels: size: XS

#20480 Docs: restrict ldap group for login #338
  docs/production/authentication-methods.md
Labels: size: S, release goal

#20731 Harden permissions required to change ownership of a bot with can_create_users permission
  zerver/lib/users.py
  zerver/tests/test_bots.py
Labels: size: M, release goal

#21497 message_edit: Move muted status of the topic when moved between streams.
  zerver/lib/actions.py
  zerver/tests/test_message_edit.py
Labels: size: XL

#21498 settings: Place the saving indicator in the header.
  static/styles/settings.css
  static/templates/settings/account_settings.hbs
  static/templates/settings/bot_list_admin.hbs
  static/templates/settings/deactivated_users_admin.hbs
  static/templates/settings/invites_list_admin.hbs
  static/templates/settings/linkifier_settings_admin.hbs
  static/templates/settings/profile_field_settings_admin.hbs
  static/templates/settings/user_list_admin.hbs
Labels: bug, area: settings UI, priority: high, size: S, release goal

#21501 puppet: Increase download timeout from 5m to 10m.
  puppet/zulip/manifests/sha256_tarball_to.pp
Labels: area: production installer, size: XS, backport candidate

#21206 compose: Minor realignment of compose icons.
  static/styles/compose.css
Labels: size: S

#20801 Fixes #20799 - portico/integration: fixed responsive of integration section.
  static/styles/portico/integrations.css
Labels: size: S

#21380 org_settings: Fix color on hover in the code playgrounds table.
  static/templates/settings/alert_word_settings.hbs
  static/templates/settings/playground_settings_admin.hbs
Labels: size: S

#21330 tippy: Make tooltip visible for elements with '.selected'.
  static/js/stream_settings_ui.js
  static/js/tippyjs.js
Labels: size: M, has conflicts

#21504 recent topics: Revert time format changes for now.
  frontend_tests/node_tests/recent_topics.js
  static/js/recent_topics_ui.js
Labels: size: XS, release goal

#20854 compose: Fix alignment of close buttons in stream invite banners.
  static/styles/compose.css
Labels: size: S

#21225 widgets: Indent multiple line todos to have same alignment as one-line todos.
  static/styles/widgets.css
  static/templates/widgets/todo_widget_tasks.hbs
Labels: size: S

#21353 settings: Improve help icons in settings.
  static/styles/settings.css
Labels: size: S

#21510 settings_users: Display error inside modal(deactivate user).
  static/js/settings_users.js
Labels: size: M

#21500 help_docs: Revise `mute-a-topic` help doc.
  templates/zerver/help/mute-a-topic.md
Labels: size: M

#21361 help_docs: Extend options for getting links to Zulip content.
  templates/zerver/help/link-to-a-message-or-conversation.md
  zerver/lib/markdown/tabbed_sections.py
Labels: size: L

#21517 puppet: Switch from ntp to chrony.
  puppet/zulip/manifests/profile/base.pp
Labels: size: XS

#21416 puppet: Build wal-g from source.
  puppet/zulip/manifests/common.pp
  puppet/zulip/manifests/postgresql_backups.pp
  scripts/lib/build-wal-g
Labels: area: production, size: L, release goal

#21506 markdown: Allow whitespace overlaps in topic linkifiers.
  zerver/lib/markdown/__init__.py
  zerver/tests/test_markdown.py
Labels: bug, priority: high, size: M, release goal, area: markdown (linkifiers)

#21518 Help center: notifications pages
  templates/zerver/help/desktop-notifications.md
  templates/zerver/help/pm-mention-alert-notifications.md
Labels: size: L

#21523 beeminder: Accept float for payload["goal"]["pledge"]
  zerver/webhooks/beeminder/view.py
Labels: size: S

#21068 message_feed_view: fit multiple images horizontally
  static/styles/dark_theme.css
  static/styles/rendered_markdown.css
Labels: size: L

#19636 script: Added python script for combining git shortlogs across multiple repositories
  tools/total-contributions
Labels: size: XL

#21526 help center: Rewrite documentation on moving content
  templates/zerver/help/include/move-content-subset-options.md
  templates/zerver/help/move-content-to-another-stream.md
  templates/zerver/help/move-content-to-another-topic.md
  templates/zerver/help/rename-a-topic.md
Labels: size: XL

#21532 uploads: Skip the outgoing proxy if S3_KEY is unset.
  docs/production/deployment.md
  docs/production/upload-backends.md
  zerver/lib/upload.py
  zproject/default_settings.py
  zproject/prod_settings_template.py
Labels: bug, area: production, area: uploads, size: S

#21538 Youtube play icon centering quick fix
  static/js/ui_init.js
Labels: size: S

#21515 help_docs: Update various help docs for small changes.
  templates/zerver/help/format-your-message-using-markdown.md
  templates/zerver/help/restrict-wildcard-mentions.md
  templates/zerver/help/user-groups.md
  templates/zerver/help/web-public-streams.md
Labels: size: S

#21543 docs: Remove a stray extra word.
  docs/production/upgrade-or-modify.md
Labels: size: XS

#21513 help_docs: Update documentation about permissions.
  templates/zerver/help/configure-who-can-create-streams.md
  templates/zerver/help/restrict-permissions-of-new-members.md
  templates/zerver/help/web-public-streams.md
  zerver/lib/markdown/tabbed_sections.py
Labels: size: L

#21539 help_docs: Update image viewer documentation for changes.
  templates/zerver/help/view-and-browse-images.md
Labels: area: documentation (user), size: S, release goal

#21508 modals: Help center link margin change in confirmation modal.
  static/styles/modal.css
Labels: size: XS

#21490 settings_users: Confirmation modal for "Reactivate" user.
  frontend_tests/puppeteer_tests/user-deactivation.ts
  static/js/settings_users.js
Labels: size: L

#21492 message_scroll: Use fadeOut effect to hide the scroll to bottom button.
  static/js/message_scroll.js
Labels: size: S, release goal

#21530 core_docs: Update translated language count and help center links.
  templates/zerver/compare-education.html
  templates/zerver/for-business.html
  templates/zerver/for-education.html
  templates/zerver/for-events.html
  templates/zerver/for-open-source.html
  templates/zerver/for-research.html
Labels: size: M

#21546 message_edit: Only move muted topic records when moving whole topics.
  templates/zerver/help/move-content-to-another-stream.md
  templates/zerver/help/move-content-to-another-topic.md
  zerver/lib/actions.py
  zerver/tests/test_message_edit.py
Labels: size: XL

#21547 docs: Update release steps.
  docs/subsystems/release-checklist.md
Labels: size: L

#21548 migrations: Adjust related_name settings for ArchivedAttachment.
  zerver/migrations/0386_fix_attachment_caches.py
  zerver/models.py
  zerver/tests/test_retention.py
Labels: size: S

#21552 python: Convert last type comments to annotations
  scripts/lib/hash_reqs.py
  scripts/lib/setup_venv.py
  scripts/lib/zulip_tools.py
  tools/lib/provision.py
Labels: size: S

#21558 modals: Refactor help_link_widget for confirmation modal.
  static/styles/modal.css
  static/templates/help_link_widget.hbs
Labels: size: XS

#21549 black: Bump target-version to py37
  pyproject.toml
Labels: size: XS

#21555 help_docs: Document auto-notifications for general stream changes.
  templates/zerver/help/change-the-privacy-of-a-stream.md
  templates/zerver/help/change-the-stream-description.md
  templates/zerver/help/include/update-stream-auto-notification.md
  templates/zerver/help/message-retention-policy.md
  templates/zerver/help/rename-a-stream.md
  templates/zerver/help/stream-sending-policy.md
Labels: size: S

#21553 Adjust alignment of globe and lock icon.
  static/styles/compose.css
  static/styles/left_sidebar.css
  static/styles/zulip.css
Labels: size: S

#21557 help_docs: Update docs related to message edit history.
  templates/zerver/help/disable-message-edit-history.md
  templates/zerver/help/edit-or-delete-a-message.md
  zerver/tests/test_middleware.py
Labels: size: S

#21563 puppet: Extract the wal-g configuration from the backups.
  puppet/zulip/manifests/postgresql_backups.pp
  puppet/zulip/manifests/wal_g.pp
Labels: size: XL

#21564 puppet: Configure chrony to use AWS-local NTP sources.
  puppet/zulip/manifests/profile/base.pp
  puppet/zulip_ops/files/chrony.conf
  puppet/zulip_ops/manifests/profile/base.pp
Labels: size: M

#21568 portico: Add Asciidoctor case study.
  templates/zerver/asciidoctor-case-study.html
  templates/zerver/footer.html
  templates/zerver/for/asciidoctor-case-study.md
  templates/zerver/for/use-cases.md
  templates/zerver/landing_nav.html
  zerver/tests/test_docs.py
  zproject/urls.py
Labels: size: XL

#21422 docs: Clarify stages of PR review.
  CONTRIBUTING.md
Labels: size: L

#21565 push_notifications: Increase severity of APNs ConnectionError.
  zerver/lib/push_notifications.py
  zerver/tests/test_push_notifications.py
Labels: size: S

#21582 help_docs: Clarify header and text for unmuting topics.
  templates/zerver/help/mute-a-topic.md
Labels: size: XS

#21584 notification_sounds: Add "Chime", the new Zulip sound used on Android
  static/audio/notification_sounds/chime.mp3
  static/audio/notification_sounds/chime.ogg
Labels: area: notifications (messages), size: XS, release goal

#21587 help_docs: Fix help center link on Zulip features page.
  templates/zerver/features.html
Labels: size: XS

#21585 help_docs: Remove last instance of 'Zulips' in help center docs.
  templates/zerver/help/configure-authentication-methods.md
Labels: size: XS

#21583 help_docs: Clarify relative link text for Subscribed streams tab.
  zerver/lib/markdown/help_relative_links.py
  zerver/tests/test_docs.py
Labels: size: XS

#21579 Updated rewrite of help docs for adding and inviting new users.
  static/templates/invitation_failed_error.hbs
  templates/zerver/for-business.html
  templates/zerver/for-open-source.html
  templates/zerver/for-research.html
  templates/zerver/help/allow-anyone-to-join-without-an-invitation.md
  templates/zerver/help/include/customize-organization-settings.md
  templates/zerver/help/include/how-to-invite-users-to-join.md
  templates/zerver/help/include/sidebar_index.md
  templates/zerver/help/invite-new-users.md
  templates/zerver/help/invite-users-to-join.md
  templates/zerver/help/moderating-open-organizations.md
  templates/zerver/help/restrict-account-creation.md
  templates/zerver/help/restrict-permissions-of-new-members.md
  templates/zerver/help/roles-and-permissions.md
  templates/zerver/help/setting-up-zulip-for-a-class.md
  zerver/lib/markdown/tabbed_sections.py
  zerver/openapi/zulip.yaml
Labels: area: documentation (user), size: XL, release goal

#21590 tools: Rework check-contributions to use commits rather than releases.
  tools/total-contributions
Labels: size: L

#21521 portico: Add web-public steams and emoji statuses to /for/X pages.
  templates/zerver/for-business.html
  templates/zerver/for-events.html
  templates/zerver/for-open-source.html
  templates/zerver/for-research.html
Labels: size: L, release goal

#21592 mailmap: Add 15 more entries
  .mailmap
Labels: size: S

#21607 settings: Fix push notifications tooltip being shown incorrectly.
  static/js/admin.js
  static/js/settings.js
  static/templates/settings/notification_settings.hbs
Labels: area: settings UI, size: XS, backport candidate

#21598 puppet: Do not ensure Chrony is running
  puppet/zulip/manifests/profile/base.pp
Labels: size: XS

#21624 changelog: Remove broken link
  docs/overview/changelog.md
Labels: size: XS, backport candidate

#21635 supervisor: 'foo:*' also matches 'foo'.
  scripts/lib/supervisor.py
Labels: size: XS, backport candidate

#21621 data_import: Fix bot email address de-duplication
  zerver/data_import/slack.py
  zerver/tests/test_slack_importer.py
Labels: size: M

#21623 navbar_alerts: Adjust height of recent topics when alert is visible.
  static/js/navbar_alerts.js
Labels: bug, priority: high, size: XS, area: recent-topics
