Repository zulip/zulip, pull requests merged in 2022-10, with the labels that each got.

#23106 help center: Edit "Create your organization profile" info.
  static/images/help/organization-profile-example.png
  templates/zerver/help/create-your-organization-profile.md
  templates/zerver/help/getting-your-organization-started-with-zulip.md
  templates/zerver/help/include/edit-organization-profile.md
  templates/zerver/help/include/organization-profile-intro.md
Labels: size: S, integration review

#23055 Fixes part of #22892: For "Message retention", the "i" is removed
  static/templates/settings/organization_settings_admin.hbs
Labels: size: XS, integration review

#23140 msg_actions_popover: Allow keyboard navigation to mark as unread button.
  static/templates/actions_popover_content.hbs
Labels: size: XS, integration review

#23141 message_fetch: Fix calling pm_list.update_private_messages twice.
  frontend_tests/node_tests/message_fetch.js
  static/js/message_fetch.js
Labels: size: S

#23059 compose: Offer narrow to compose target button when composing a private message.
  frontend_tests/node_tests/compose_state.js
  frontend_tests/node_tests/input_pill.js
  static/js/compose.js
  static/js/compose_actions.js
  static/js/compose_state.js
  static/js/input_pill.js
  static/styles/compose.css
  static/styles/input_pill.css
  static/templates/compose.hbs
Labels: design, area: compose, priority: high, size: L, release goal, chat.zulip.org review

#23156 settings_org: Add missing closing square bracket.
  static/js/settings_org.js
Labels: size: XS, integration review

#23149 models: Remove explicit id fields
  corporate/models.py
  zerver/models.py
Labels: size: M, integration review

#23148 docs: Update mypy documentation on django-stubs
  docs/testing/mypy.md
Labels: size: XL

#23136 popovers: Fix width of message actions popover.
  frontend_tests/node_tests/popovers.js
  static/js/popovers.js
  static/styles/app_components.css
  static/styles/popovers.css
  static/templates/actions_popover_template.hbs
  tools/test-js-with-node
Labels: bug, priority: high, size: M, release goal, area: message feed UI, integration review

#23165 popovers: Hide mark as unread button for spectators.
  static/js/popovers.js
Labels: size: XS

#23164 css: Fix background color of date_row in unread PMs.
  static/styles/dark_theme.css
  static/styles/zulip.css
Labels: size: S

#23109 analytics: Add summary statistic for upload/storage space in use.
  analytics/management/commands/populate_analytics_db.py
  analytics/views/stats.py
  static/js/stats/stats.js
  templates/analytics/stats.html
Labels: size: M

#23086 analytics: Fix cut off legends and range selector in existing charts.
  static/js/stats/stats.js
  static/styles/portico/stats.css
  templates/analytics/stats.html
Labels: bug, area: analytics, size: XL, integration review

#23144 help: Document option to display custom profile fields in profile summary.
  templates/zerver/help/add-custom-profile-fields.md
Labels: area: documentation (user), priority: high, size: M, release goal, integration review

#23120 templates: Update text on 500 error page.
  templates/500.html
Labels: area: misc, area: production, size: M, integration review

#21465 popovers: Design changes for user profile popover.
  frontend_tests/node_tests/hotkey.js
  frontend_tests/node_tests/popovers.js
  static/js/hotkey.js
  static/js/popovers.js
  static/styles/popovers.css
  static/styles/zulip.css
  static/templates/user_info_popover_content.hbs
  static/templates/user_info_popover_manage_menu.hbs
Labels: size: XL, release goal, chat.zulip.org review

#23168 docs: Fix a typo in mypy documentation.
  docs/testing/mypy.md
Labels: size: XS

#23166 misc: Improve app title bar for stream and topic views.
  frontend_tests/puppeteer_tests/drafts.ts
  frontend_tests/puppeteer_tests/message-basics.ts
  static/js/narrow.js
Labels: area: misc, priority: high, size: S, integration review

#23169 help center: Document new "Pronouns" custom profile field type.
  templates/zerver/help/add-custom-profile-fields.md
  templates/zerver/help/include/customize-settings-for-new-users.md
Labels: size: S, integration review

#23176 python: Fix __dict__ mutation abuse
  corporate/tests/test_stripe.py
  zerver/management/commands/list_realms.py
Labels: size: S, integration review

#23175 python: Clean up getattr, setattr, delattr calls with literal names
  zerver/decorator.py
  zerver/lib/create_user.py
  zerver/lib/import_realm.py
  zerver/lib/logging_util.py
  zerver/lib/request.py
  zerver/lib/test_helpers.py
  zerver/lib/transfer.py
  zerver/lib/webhooks/common.py
  zerver/management/commands/makemessages.py
  zerver/middleware.py
  zerver/models.py
  zerver/tests/test_link_embed.py
  zerver/tests/test_logging_handlers.py
  zerver/tests/test_markdown.py
  zerver/tests/test_openapi.py
  zerver/tests/test_signup.py
  zilencer/management/commands/mark_all_messages_unread.py
Labels: size: XL, integration review

#23154 settings: Create a new "Message deletion" section.
  static/templates/settings/organization_permissions_admin.hbs
Labels: size: M

#23193 communities: Add more space between realm rows.
  static/styles/portico/integrations.css
Labels: size: XS, integration review

#23197 slack: Skip files where file_access: access_denied.
  zerver/data_import/slack.py
Labels: size: XS

#22312 Send notifications after topic change
  frontend_tests/puppeteer_tests/edit.ts
  static/js/message_edit.js
  templates/zerver/api/changelog.md
  version.py
  zerver/actions/message_edit.py
  zerver/openapi/zulip.yaml
  zerver/tests/test_message_edit.py
  zerver/views/message_edit.py
Labels: size: XL, integration review

#23208 openapi: Remove documentation for unstable timezones.json path
  zerver/openapi/zulip.yaml
Labels: area: documentation (api and integrations), size: S, integration review

#23201 linkifiers: Support %20 in URLs for topic links.
  zerver/lib/markdown/__init__.py
  zerver/tests/test_markdown.py
Labels: size: M

#23178 settings: Uncheck display_in_profile_summary checkbox if hidden.
  static/js/settings_profile_fields.js
Labels: bug, area: settings (admin/org), size: XS, integration review

#23189 settings_panel_menu: Open first section if hash is invalid.
  static/js/settings_panel_menu.js
Labels: bug, size: S, release goal, integration review

#22965 stream settings: Show stream header in narrow view.
  static/styles/subscriptions.css
Labels: size: XS, integration review

#23221 puppet: Bump Grafana version.
  puppet/zulip/manifests/common.pp
Labels: size: S

#23230 settings: Set min width of role column.
  static/styles/settings.css
  static/templates/settings/admin_user_list.hbs
Labels: bug, area: settings (admin/org), area: settings UI, size: S, release goal

#23231 api-docs: Update examples of `queue_id` for uuid format.
  zerver/openapi/zulip.yaml
  zerver/tests/test_markdown.py
Labels: size: S

#23226 docs: Add commas to list of event types supported by integrations.
  templates/zerver/help/include/event-filtering-instruction.md
Labels: area: documentation (api and integrations), size: XS, release goal

#23190 communities: Include organizations that do not require an invite.
  corporate/views/portico.py
Labels: size: XS, integration review

#23240 test_script: Don’t crash on second Puppeteer run
  tools/lib/test_script.py
Labels: size: XS

#22637 gear menu: Add organization info.
  frontend_tests/node_tests/gear_menu.js
  static/js/gear_menu.js
  static/styles/dark_theme.css
  static/styles/zulip.css
  static/templates/gear_menu.hbs
  tools/lib/capitalization.py
Labels: area: misc, area: settings (admin/org), priority: high, size: XL, release goal, integration review

#23227 Fix spectator view custom profile fields
  static/js/popovers.js
  zerver/lib/events.py
Labels: size: S, integration review

#23228 user_info_popover: Change text of "View private messages to myself" to "View messages with yourself".
  static/templates/user_info_popover_content.hbs
Labels: size: XS

#23244 restart-server: Default to running config and database checks.
  scripts/lib/upgrade-zulip-stage-2
  scripts/lib/zulip_tools.py
  scripts/restart-server
Labels: size: S

#23147 migrations: Fix noop realm filter migration.
  zerver/migrations/0094_realm_filter_url_validator.py
  zerver/migrations/0368_alter_realmfilter_url_format_string.py
Labels: size: S

#23209 compose: Use consistent hover color for buttons in dark mode.
  static/styles/dark_theme.css
Labels: size: S, integration review

#23243 settings: Fix height of left sidebar for short screens.
  static/styles/settings.css
  static/styles/subscriptions.css
Labels: bug, area: settings (admin/org), priority: high, size: S, release goal

#23259 templates: Remove unused `no-slide` class.
  templates/corporate/development-community.html
  templates/corporate/for/business.html
  templates/corporate/for/education.html
  templates/corporate/for/events.html
  templates/corporate/for/open-source.html
  templates/corporate/for/research.html
  templates/corporate/for/use-cases.html
  templates/corporate/history.html
  templates/corporate/jobs.html
  templates/corporate/self-hosting.html
  templates/corporate/team.html
Labels: size: S

#23258 portico_signin: Fix signup text overflowing to icon in Russian.
  static/styles/portico/portico_signin.css
Labels: size: XS

#23239 help: Update message menu documentation.
  templates/zerver/help/configure-notification-bot.md
  templates/zerver/help/edit-or-delete-a-message.md
  templates/zerver/help/emoji-reactions.md
  templates/zerver/help/move-content-to-another-stream.md
  templates/zerver/help/move-content-to-another-topic.md
  templates/zerver/help/quote-and-reply.md
  templates/zerver/help/rename-a-topic.md
  templates/zerver/help/star-a-message.md
  templates/zerver/help/view-the-markdown-source-of-a-message.md
Labels: area: documentation (user), priority: high, size: L, release goal, integration review

#23096 import_realm: Speed up first_message_id calculation.
  zerver/lib/import_realm.py
Labels: size: S, release goal

#23196 analytics: Add summary statistic for guest users in realm.
  analytics/management/commands/populate_analytics_db.py
  analytics/views/stats.py
  corporate/lib/stripe.py
  static/js/stats/stats.js
  templates/analytics/stats.html
Labels: area: analytics, priority: high, size: M, release goal, integration review

#20890 recent_topics: Add Private message to recent_topics.
  frontend_tests/node_tests/example5.js
  frontend_tests/node_tests/recent_topics.js
  frontend_tests/node_tests/unread.js
  static/js/click_handlers.js
  static/js/compose_closed_ui.js
  static/js/recent_topics_data.js
  static/js/recent_topics_ui.js
  static/js/recent_topics_util.js
  static/styles/dark_theme.css
  static/styles/recent_topics.css
  static/templates/recent_topic_row.hbs
  static/templates/recent_topics_filters.hbs
  tools/test-js-with-node
Labels: priority: high, size: XL, area: recent-topics, release goal, chat.zulip.org review

#23253 settings_ui: Change icons in organization settings sidebar.
  static/templates/settings_overlay.hbs
Labels: size: S, integration review

#23256 help: Update documentation on bots.
  templates/zerver/help/add-a-bot-or-integration.md
  templates/zerver/help/bots-and-integrations.md
  templates/zerver/help/deactivate-or-reactivate-a-bot.md
  templates/zerver/help/edit-a-bot.md
  templates/zerver/help/restrict-bot-creation.md
  zerver/lib/markdown/help_settings_links.py
  zerver/lib/markdown/tabbed_sections.py
Labels: size: L, release goal, integration review

#23229 tippy: Don't show an error for a race condition in reaction tooltips.
  static/js/tippyjs.js
Labels: size: S

#23236 Remove text highlighting in compose box
  static/js/compose_actions.js
Labels: size: XS, integration review

#23271 recent_topics: Handle page up/down manually.
  static/js/hotkey.js
  static/js/recent_topics_ui.js
Labels: bug, size: M, area: recent-topics, release goal

#23263 migrations: Remove bugged Recipients in 0419.
  zerver/migrations/0419_backfill_message_realm.py
Labels: size: S

#23252 help: Fix "Reply mentioning user" documentation.
  templates/zerver/help/mention-a-user-or-group.md
Labels: bug, area: documentation (user), priority: high, size: S, integration review

#23260 help center: Clean up documentation on sending messages.
  templates/zerver/help/include/compose-and-send-message.md
  templates/zerver/help/include/how-to-start-a-new-topic.md
  templates/zerver/help/include/replying-to-messages.md
  templates/zerver/help/include/send-group-pm.md
  templates/zerver/help/include/starting-a-new-private-thread.md
  templates/zerver/help/private-messages.md
Labels: size: XL, integration review

#23232 css: Fix color of filter buttons being changed on hover for spectators.
  static/styles/dark_theme.css
Labels: size: S, release goal

#23285 integrations: Increase font size of logo disclaimer.
  static/styles/portico/integrations.css
  templates/zerver/integrations/index.html
Labels: size: S, integration review

#23299 timeout: Correct thread id type passed to PyThreadState_SetAsyncExc
  zerver/lib/timeout.py
Labels: size: XS, backport candidate, integration review

#23293 Misc fixes to recent topics.
  static/js/recent_topics_ui.js
Labels: size: S

#23302 docs: Update Zulip version mentioned and remove extraneous comma.
  docs/translating/translating.md
Labels: size: XS, integration review

#23301 email_validation: Restore case-insensitive domain validation.
  zerver/lib/email_validation.py
  zerver/views/message_send.py
Labels: size: S, integration review

#23306 Reorganize organization settings sidebar.
  static/templates/settings_overlay.hbs
Labels: area: settings (admin/org), priority: high, size: L

#23237 user_profile_modal: Move title and tab switcher to a fixed header.
  static/styles/popovers.css
  static/templates/user_profile_modal.hbs
Labels: size: M

#22943 stream-create: Use simplebar.
  static/styles/subscriptions.css
  static/templates/stream_settings/stream_creation_form.hbs
Labels: size: M

#23245 navbar: Add login and signup buttons for spectators.
  static/js/click_handlers.js
  static/js/tippyjs.js
  static/styles/dark_theme.css
  static/styles/zulip.css
  static/templates/navbar.hbs
  static/templates/right_sidebar.hbs
Labels: size: XL, integration review

#23102 Fix vertical alignment in /me message.
  static/js/message_list.js
  static/styles/zulip.css
Labels: size: S, integration review

#23238 drafts: Update topic when it's renamed and for a going forward change.
  frontend_tests/node_tests/drafts.js
  static/js/drafts.js
  static/js/message_events.js
Labels: size: XL, integration review

#23322 realm_domains: Populate the table only if the modal is open.
  static/js/settings_realm_domains.js
Labels: bug, area: real-time sync, area: settings (admin/org), size: XS, release goal

#23326 test_classes: Improve assert_database_query_count output message.
  zerver/lib/test_classes.py
Labels: size: XS, integration review

#23333 tools: Add missing spaces in concatenated string literals
  tools/lib/provision.py
  tools/linter_lib/custom_check.py
  zerver/tests/test_new_users.py
Labels: size: S

#23281 Add confirmation modal for reactivating a bot in personal settings
  static/js/settings_bots.js
  templates/zerver/help/deactivate-or-reactivate-a-bot.md
Labels: size: S, integration review

#23338 people: Use names in PM urls instead of emails.
  frontend_tests/node_tests/activity.js
  frontend_tests/node_tests/buddy_data.js
  frontend_tests/node_tests/filter.js
  frontend_tests/node_tests/hash_util.js
  frontend_tests/node_tests/hashchange.js
  frontend_tests/node_tests/narrow.js
  frontend_tests/node_tests/people.js
  frontend_tests/node_tests/pm_list_data.js
  frontend_tests/node_tests/popovers.js
  static/js/people.js
Labels: size: L

#23329 recent-topics: Update hash for view to be "#recent".
  frontend_tests/node_tests/hashchange.js
  static/js/hash_util.js
  static/js/hashchange.js
  static/js/hotkey.js
  static/templates/bookend.hbs
  static/templates/left_sidebar.hbs
  zerver/lib/onboarding.py
  zerver/tests/test_tutorial.py
Labels: size: M

#23340 compose-box: Remove reset max-height calculation for preview click.
  frontend_tests/node_tests/compose.js
  static/js/compose.js
  static/js/resize.js
Labels: bug, area: compose, priority: high, size: M, release goal, integration review

#23349 recent_topics: Fix long topic and stream words squeezing other rows.
  static/styles/recent_topics.css
Labels: size: S

#23348 filter: Show stream and topic title for near link narrows.
  static/js/filter.js
Labels: size: XS

#23317 help: Add "View messages sent by user" page.
  templates/zerver/help/include/sidebar_index.md
  templates/zerver/help/search-for-messages.md
  templates/zerver/help/view-messages-sent-by-a-user.md
Labels: area: documentation (user), size: M, integration review

#23272 settings(admin/org): Customize reactivation confirmation modal for bots
  static/js/settings_users.js
  static/templates/confirm_dialog/confirm_reactivate_bot.hbs
  tools/lib/capitalization.py
Labels: size: S, integration review

#23353 recent: Fix unread counts wrappings to next line in long topic names.
  static/styles/recent_topics.css
Labels: size: S

#23343 help center: Update emoji reactions documentation.
  templates/zerver/help/emoji-reactions.md
  templates/zerver/help/mute-a-user.md
Labels: size: L, release goal, integration review

#23364 unread: Extract old_unreads_missing.
  static/js/unread.js
Labels: size: XS

#23319 style: Improve visuals of the dialog_widget disabled buttons while a loading spinner is showing.
  static/js/dialog_widget.js
  static/js/loading.ts
  static/styles/modal.css
Labels: design, area: settings UI, accessibility, priority: high, size: M, release goal

#23363 url_encoding: Use user name instead of email in personal_narrow_url.
  zerver/lib/url_encoding.py
  zerver/tests/test_email_notifications.py
Labels: size: S

#23370 help center: Clearly refer to mobile apps on /help/mobile-notifications.
  templates/zerver/help/mobile-notifications.md
Labels: size: S, integration review

#23347 api-docs: Clarify narrow parameter in `/get-messages` endpoint.
  zerver/openapi/zulip.yaml
Labels: bug, area: api, area: documentation (api and integrations), priority: high, size: L, release goal, integration review

#23357 left_sidebar: Make topics list header sticky.
  static/styles/dark_theme.css
  static/styles/left_sidebar.css
Labels: area: left-sidebar, priority: high, size: M, release goal, integration review

#23383 docs: Copy Zulip development community intro to Contributing guide.
  CONTRIBUTING.md
Labels: size: M, integration review

#23393 docs: Document handling noop migrations.
  docs/subsystems/schema-migrations.md
Labels: size: S

#23392 css: Increase opacity of sidebar titles in dark theme.
  static/styles/dark_theme.css
Labels: size: S, integration review

#23387 recent: Fix alignment of unread count in PM rows.
  static/styles/recent_topics.css
  static/templates/recent_topic_row.hbs
Labels: size: S

#23337 css: fixed search message alert
  static/styles/zulip.css
Labels: size: XS, integration review

#23394 invites: Add atomic() around some invite-revoking blocks.
  zerver/actions/invites.py
Labels: size: S

#23382 help center: Add tip about how to add a link to a stream description.
  templates/zerver/help/change-the-stream-description.md
Labels: size: S, integration review
