Repository zulip/zulip, pull requests merged in 2022-07, with the labels that each got.

#22361 email_notifications: Give absolute path to html2text
  zerver/lib/email_notifications.py
Labels: backport candidate

#22378 log-search: Fix re.Match type annotations
  scripts/log-search
Labels: size: S

#22363 populate_db: Spell “stickiness” correctly
  zilencer/management/commands/populate_db.py
Labels: size: XS

#22380 test_runner: Remove unused addInfo method
  zerver/lib/test_runner.py
Labels: size: S

#22384 mypy: Add types-zxcvbn
  pyproject.toml
  requirements/dev.txt
  requirements/mypy.in
  requirements/mypy.txt
  version.py
Labels: size: S

#22388 migrations: Replace NullBooleanField
  zerver/migrations/0001_initial.py
  zerver/migrations/0048_enter_sends_default_to_false.py
  zerver/migrations/0220_subscription_notification_settings.py
  zerver/migrations/0223_rename_to_is_muted.py
  zerver/migrations/0253_userprofile_wildcard_mentions_notify.py
Labels: size: S

#22382 mypy: Add links to specific mypy bugs
  zerver/actions/realm_settings.py
  zerver/lib/markdown/__init__.py
Labels: size: S

#22381 test_runner: Avoid undocumented writeln method
  zerver/lib/test_runner.py
Labels: size: S

#22397 emoji: Write "original" file before attempting resize.
  zerver/lib/upload.py
Labels: size: XS

#22395 decorator: Remove unused Union.
  zerver/decorator.py
Labels: size: XS

#22385 ci: Avoid duplicate GitHub Actions runs for push, pull_request
  .github/workflows/codeql-analysis.yml
  .github/workflows/production-suite.yml
  .github/workflows/zulip-ci.yml
Labels: size: S

#22402 help center: Move typing notifications documentation to a separate page.
  templates/zerver/features.html
  templates/zerver/help/include/sidebar_index.md
  templates/zerver/help/private-messages.md
  templates/zerver/help/status-and-availability.md
  templates/zerver/help/typing-notifications.md
  zerver/openapi/zulip.yaml
Labels: size: L

#22406 help center: Add a "Configure multi-language search" page.
  docs/subsystems/full-text-search.md
  templates/zerver/help/change-the-default-language-for-your-organization.md
  templates/zerver/help/configure-multi-language-search.md
  templates/zerver/help/include/sidebar_index.md
  templates/zerver/help/search-for-messages.md
Labels: size: M

#22294 docs: Add some basic licensing guidance for contributors (proposed revision)
  CONTRIBUTING.md
Labels: size: S

#22415 ci: Limit CodeQL analysis with the same branches for push, pull_request
  .github/workflows/codeql-analysis.yml
Labels: size: XS

#20160 realm_domains_modal: Migrate modal to dialog_widget.
  frontend_tests/node_tests/dispatch.js
  frontend_tests/node_tests/settings_org.js
  frontend_tests/node_tests/settings_realm_domains.js
  static/js/server_events_dispatch.js
  static/js/settings_org.js
  static/js/settings_realm_domains.js
  static/styles/settings.css
  static/templates/settings/admin_settings_modals.hbs
  static/templates/settings/organization_permissions_admin.hbs
  static/templates/settings/realm_domains_modal.hbs
  tools/test-js-with-node
Labels: size: XL

#22391 help-docs: Document "Delete topic" mobile app feature.
  templates/zerver/help/delete-a-topic.md
Labels: area: documentation (user), size: S, integration review

#22364 help-docs: Update article about message drafts.
  templates/zerver/help/view-and-edit-your-message-drafts.md
Labels: size: M, integration review

#21988 models: Add comment about where to add new user settings.
  zerver/models.py
Labels: size: M

#22330 Render Mac shortcuts with `Fn` key correctly.
  frontend_tests/node_tests/common.js
  static/js/common.ts
  static/js/portico/help.js
Labels: bug, area: documentation (user), size: XL

#22420 babel: Bump configured corejs version
  babel.config.js
  package.json
  yarn.lock
Labels: size: S

#22150 typeahead: Don't match descriptions for streams and user groups.
  frontend_tests/node_tests/composebox_typeahead.js
  static/js/composebox_typeahead.js
  static/js/pill_typeahead.js
Labels: size: M, integration review

#22230 Fix resetting of "Create Stream" form when clicked on header of "Manage Streams"
  static/js/stream_settings_ui.js
Labels: bug, area: stream settings, size: S, integration review

#22416 ldap: Remove unused isinstance check.
  zproject/backends.py
Labels: size: S

#22449 help-docs: Rename "Related topics" to "Related articles".
  templates/zerver/help/add-or-remove-users-from-a-stream.md
  templates/zerver/help/communities-directory.md
  templates/zerver/help/manage-user-stream-subscriptions.md
  templates/zerver/help/mastering-the-compose-box.md
Labels: size: S

#22458 help-docs: Remove `mac-cmd-style` CSS rule.
  frontend_tests/node_tests/common.js
  static/js/common.ts
  static/js/portico/help.js
  static/styles/portico/portico.css
Labels: size: M

#22455 draft: Fix vertical ellipsis color on hover.
  static/styles/dark_theme.css
Labels: size: XS

#22367 emoji: Update emoji validation error messages with more information.
  zerver/lib/emoji.py
  zerver/tests/test_realm_emoji.py
Labels: size: S, integration review

#22459 docs: Remove some outdated references to thumbnailing.md doc.
  zerver/lib/markdown/__init__.py
  zerver/lib/thumbnail.py
  zerver/views/thumbnail.py
Labels: size: XS

#22468 api-docs: Add note to `/update-message` parameters.
  zerver/openapi/zulip.yaml
Labels: size: M

#22436 integrations: Add RhodeCode webhook integration.
  static/images/integrations/bot_avatars/rhodecode.png
  static/images/integrations/logos/rhodecode.svg
  static/images/integrations/rhodecode/001.png
  zerver/lib/integrations.py
  zerver/lib/webhooks/git.py
  zerver/webhooks/rhodecode/__init__.py
  zerver/webhooks/rhodecode/doc.md
  zerver/webhooks/rhodecode/fixtures/push.json
  zerver/webhooks/rhodecode/fixtures/push__commits_more_than_limit.json
  zerver/webhooks/rhodecode/fixtures/push__local_branch_without_commits.json
  zerver/webhooks/rhodecode/fixtures/push__multiple_committers.json
  zerver/webhooks/rhodecode/fixtures/push__multiple_committers_with_others.json
  zerver/webhooks/rhodecode/fixtures/push__remove_branch.json
  zerver/webhooks/rhodecode/tests.py
  zerver/webhooks/rhodecode/view.py
Labels: size: XL

#22414 confirmation: Refactor get_confirmations to accept confirmation objects.
  analytics/views/support.py
Labels: size: S

#22450 node_tests: Remove low-hanging uses of `__Rewire__`
  frontend_tests/node_tests/activity.js
  frontend_tests/node_tests/billing.js
  frontend_tests/node_tests/buddy_data.js
  frontend_tests/node_tests/color_data.js
  frontend_tests/node_tests/common.js
  frontend_tests/node_tests/compose.js
  frontend_tests/node_tests/compose_actions.js
  frontend_tests/node_tests/compose_pm_pill.js
  frontend_tests/node_tests/compose_validate.js
  frontend_tests/node_tests/compose_video.js
  frontend_tests/node_tests/composebox_typeahead.js
  frontend_tests/node_tests/dispatch.js
  frontend_tests/node_tests/dispatch_subs.js
  frontend_tests/node_tests/drafts.js
  frontend_tests/node_tests/example7.js
  frontend_tests/node_tests/example8.js
  frontend_tests/node_tests/filter.js
  frontend_tests/node_tests/hashchange.js
  frontend_tests/node_tests/lightbox.js
  frontend_tests/node_tests/markdown.js
  frontend_tests/node_tests/message_list_data.js
  frontend_tests/node_tests/narrow.js
  frontend_tests/node_tests/notifications.js
  frontend_tests/node_tests/people.js
  frontend_tests/node_tests/people_errors.js
  frontend_tests/node_tests/pm_list_data.js
  frontend_tests/node_tests/popovers.js
  frontend_tests/node_tests/presence.js
  frontend_tests/node_tests/reactions.js
  frontend_tests/node_tests/recent_topics.js
  frontend_tests/node_tests/search_pill.js
  frontend_tests/node_tests/search_suggestion_future.js
  frontend_tests/node_tests/search_suggestion_now.js
  frontend_tests/node_tests/settings_muted_topics.js
  frontend_tests/node_tests/settings_muted_users.js
  frontend_tests/node_tests/settings_org.js
  frontend_tests/node_tests/settings_user_groups.js
  frontend_tests/node_tests/starred_messages.js
  frontend_tests/node_tests/stream_create_subscribers_data.js
  frontend_tests/node_tests/stream_data.js
  frontend_tests/node_tests/stream_events.js
  frontend_tests/node_tests/stream_list.js
  frontend_tests/node_tests/stream_sort.js
  frontend_tests/node_tests/top_left_corner.js
  frontend_tests/node_tests/topic_generator.js
  frontend_tests/node_tests/topic_list_data.js
  frontend_tests/node_tests/transmit.js
  frontend_tests/node_tests/typeahead_helper.js
  frontend_tests/node_tests/typing_events.js
  frontend_tests/node_tests/typing_status.js
  frontend_tests/node_tests/unread.js
  frontend_tests/node_tests/upload.js
  tools/test-js-with-node
Labels: area: testing-infrastructure, size: XL

#22473 landing-page: Remove unused hero-screen class
  static/images/landing-page/macbook-empty.png
  static/js/portico/landing-page.js
  static/styles/portico/landing_page.css
Labels: size: L

#22451 help: Cross link help center docs for managing stream subscriptions.
  templates/zerver/help/manage-user-stream-subscriptions.md
  templates/zerver/help/unsubscribe-from-a-stream.md
Labels: size: XS, integration review

#22470 events_register: Pass spectator set language to client in user_settings.
  zerver/lib/events.py
  zerver/views/events_register.py
Labels: bug, size: S, release goal, area: web-public streams

#22474 register: Correct jquery-validation library name in comment
  templates/zerver/register.html
Labels: size: XS

#22477 emoji: Use path converter for emoji name in URL.
  zerver/tests/test_realm_emoji.py
  zproject/urls.py
Labels: bug, area: emoji, size: S

#22483 Move function declaration out of for loop.
  static/js/pm_list_data.js
Labels: size: L

#22480 Upgrade puppet versions
  puppet/zulip/manifests/common.pp
Labels: size: M

#22481 backend: Migrate `secret` parameter to REQ framework.
  zerver/decorator.py
  zerver/tests/test_decorators.py
  zerver/tests/test_event_system.py
Labels: size: M

#22493 tail-ses: Add IdentityArgsDict.
  tools/tail-ses
Labels: size: S

#22425 message_send: Extract ActiveUserDict for accurate typing.
  zerver/actions/message_send.py
Labels: size: M

#22490 corporate: Fix type annotation for decorated error handler function.
  corporate/lib/stripe_event_handler.py
Labels: size: XS

#22373 docs: Add 'Writing style' section to writing help doc tutorial.
  docs/documentation/helpcenter.md
Labels: size: M, integration review

#22289 message-editing: Immediately show menu.
  static/js/message_edit.js
Labels: area: message-editing, priority: high, size: S, release goal, integration review

#22498 message_send: Remove TypeGuard
  zerver/actions/message_send.py
Labels: size: S

#22499 teleport: Add explicit WebAuthn config, not just U2F.
  puppet/zulip_ops/files/teleport_server.yaml
Labels: size: S

#22520 migrations: Adjust stats size for tsvector to 10k, from 100.
  zerver/migrations/0398_tsvector_statistics.py
Labels: size: M

#22492 message-editing: Reword move message menu.
  static/styles/zulip.css
  static/templates/message_edit_form.hbs
  templates/zerver/help/include/move-content-subset-options.md
  templates/zerver/help/move-content-to-another-stream.md
  templates/zerver/help/move-content-to-another-topic.md
Labels: size: S, integration review

#22530 release: Use the right variable to build predictable tarball path.
  tools/release
Labels: size: S, backport candidate

#22528 queue_processor: Remove unreachable code.
  zerver/worker/queue_processors.py
Labels: size: XS

#22291 api-docs: Changelog audit prep and feature level 1 updates.
  templates/zerver/api/changelog.md
  zerver/openapi/zulip.yaml
Labels: size: XL

#22527 documentation: Fix MarkdownDirectoryView.get.
  zerver/views/documentation.py
Labels: size: S

#22501 puppet: Tell needrestart to not default to restarting core services.
  puppet/zulip_ops/files/needrestart/zulip.conf
  puppet/zulip_ops/manifests/profile/base.pp
Labels: size: S

#22257 grafana: Enable auto-sign-up.
  puppet/zulip_ops/files/grafana/grafana.ini
Labels: size: XS

#22534 docs: Correct path to zulip.yaml
  docs/documentation/openapi.md
Labels: size: XS

#22531 docs: Document that you need to copy slack-data.zip onto the server.
  templates/zerver/help/import-from-slack.md
Labels: size: S

#22466 keyboard-shortcuts: Add class to arrow keys for Mac shortcuts.
  frontend_tests/node_tests/common.js
  static/js/common.ts
Labels: size: S

#22231 Various small improvement to restore-backup
  docs/production/export-and-import.md
  scripts/setup/restore-backup
Labels: size: M

#22536 translation: Translate new user messages to realm's default language.
  zerver/actions/create_user.py
Labels: area: internationalization, size: S

#22515 email-log: Move `forward_address` to `REQ` framework.
  zerver/views/development/email_log.py
Labels: size: S

#22514 decorator: Move tornado notify `data` parameter to REQ framework.
  zerver/tests/test_event_system.py
  zerver/tornado/views.py
Labels: size: S

#22518 cache: Use getattr to access _cache.
  zerver/lib/import_realm.py
  zerver/lib/transfer.py
  zilencer/management/commands/mark_all_messages_unread.py
Labels: size: S

#22539 provision: Avoid distutils; keep PROVISION_VERSION as a tuple
  docs/subsystems/dependencies.md
  tools/diagnose
  tools/lib/provision_inner.py
  tools/lib/test_script.py
  version.py
Labels: size: M

#22541 python: Apply changes from pyupgrade
  scripts/log-search
  zerver/tests/test_subs.py
Labels: size: S

#22547 tests: Remove `FORWARD_ADDRESS_CONFIG_FILE` created in test.
  zerver/tests/test_email_log.py
Labels: size: M

#22559 Release Zulip Server 5.5.
  docs/overview/changelog.md
  version.py
Labels: size: S

#22558 commit-message-lint: Take release branches into account
  tools/commit-message-lint
Labels: size: S, backport candidate

#22511 docs: Fix typo in `hashchange-system.md`.
  docs/subsystems/hashchange-system.md
Labels: size: XS, integration review

#22260 harbor: Update harbor integration based on latest webhook payload for…
  zerver/webhooks/harbor/fixtures/delete_image.json
  zerver/webhooks/harbor/fixtures/push_image.json
  zerver/webhooks/harbor/fixtures/scanning_completed.json
  zerver/webhooks/harbor/fixtures/scanning_completed_no_vulnerability.json
  zerver/webhooks/harbor/tests.py
  zerver/webhooks/harbor/view.py
Labels: size: XL

#22184 footer: Reduce links for self-hosted installations on signup pages.
  static/styles/portico/portico.css
  templates/zerver/footer.html
  zerver/context_processors.py
Labels: design, area: onboarding, priority: high, area: portico, size: L, release goal

#22555 test_urls: Remove legacy hasattr check.
  zerver/tests/test_urls.py
Labels: size: S, integration review

#22553 templates: Use Dict instead of Mapping for the context parameter.
  zerver/lib/templates.py
Labels: size: S, integration review

#22550 integrations: Use TestHttpResponse to type send_webhook_fixture_message.
  zerver/views/development/integrations.py
Labels: size: S, integration review

#22544 user_status: Add UserInfoDict.
  zerver/lib/user_status.py
  zerver/tests/test_user_status.py
Labels: size: M, integration review

#22571 users: Remove default values for add_service.
  zerver/lib/users.py
Labels: size: S, integration review

#19542 minor: Add `z-index` to `message_time` class.
  static/styles/zulip.css
Labels: size: XS, integration review

#22557 registration: Tie PreregistrationUser to the original MultiUseInvite.
  zerver/migrations/0399_preregistrationuser_multiuse_invite.py
  zerver/models.py
  zerver/tests/test_auth_backends.py
  zerver/tests/test_signup.py
  zerver/views/auth.py
  zerver/views/registration.py
Labels: area: authentication, area: invitations, size: M

#22574 zjsunit: Fix mock_esm call site detection
  frontend_tests/zjsunit/namespace.js
Labels: size: S

#22575 message-editing: Change default move option.
  static/templates/message_edit_form.hbs
Labels: size: XS

#22495 user_groups: Add MemberGroupUsersDict.
  zerver/actions/user_groups.py
Labels: size: S, integration review

#22522 muting: Add validation for update options.
  zerver/views/muting.py
Labels: size: S, integration review

#22362 decorator: Type narrow the default login_url.
  zproject/computed_settings.py
  zproject/default_settings.py
  zproject/dev_settings.py
Labels: size: S, integration review

#22508 stream_settings: Use tooltips.
  static/templates/stream_settings/stream_settings.hbs
Labels: size: S, integration review

#22545 realm_audit_log: Explicitly stringify dict before insertion.
  corporate/lib/stripe.py
  zerver/actions/create_realm.py
  zerver/actions/realm_icon.py
  zerver/actions/realm_settings.py
  zerver/actions/user_settings.py
Labels: size: S, integration review

#22554 avatar: Remove unnecessary try...except statement.
  zerver/views/users.py
Labels: size: S, integration review

#22568 exceptions: Guard validation error conversion with message_dict.
  zerver/lib/exceptions.py
Labels: size: XS, integration review

#22581 fonts style and spacing between components changed.
  static/styles/settings.css
Labels: size: M, integration review

#22235 confirm_deactivate_user: Provide additional information about user.
  frontend_tests/node_tests/bot_data.js
  static/js/bot_data.js
  static/js/settings_users.js
  static/templates/confirm_dialog/confirm_deactivate_user.hbs
Labels: area: settings (admin/org), size: L, area: popovers, integration review

#22429 help-docs: Document "Pin to top"/"Unpin from top" mobile app feature.
  templates/zerver/help/include/mobile-stream-settings-menu-tip.md
  templates/zerver/help/pin-a-stream.md
Labels: size: M, integration review

#22594 storage: Use Django 4.0 manifest_storage option
  zerver/lib/storage.py
Labels: size: S

#22532 settings: Make INVITATION_LINK_VALIDITY_MINUTES optional.
  zerver/tests/test_signup.py
  zerver/views/development/email_log.py
  zerver/views/invite.py
  zproject/computed_settings.py
Labels: size: S, integration review

#22570 overlays: Remove unused support for Bootstrap modals
  static/js/click_handlers.js
  static/js/dialog_widget.js
  static/js/overlays.js
  static/js/settings.js
  static/js/settings_account.js
  static/js/spectators.js
  static/js/user_profile.js
  static/styles/modal.css
Labels: size: XL

#22595 help-docs: Fix cross-links to help center pages about linking to Zulip.
  templates/zerver/help/link-to-a-message-or-conversation.md
  templates/zerver/help/linking-to-zulip.md
Labels: area: documentation (user), size: S, integration review

#22526 storage: Fix type annotation for storage
  zerver/lib/storage.py
Labels: size: XS, integration review

#22599 unittests: add a couple of tests for inbound email edge case.
  zerver/tests/test_email_mirror.py
Labels: bug, area: integrations, area: emails, size: L

#22598 2fa: Refactor is_2fa_verified to require type narrowing.
  zerver/decorator.py
  zerver/lib/users.py
  zerver/views/auth.py
Labels: size: S, integration review

#22576 modal: Use font-weight 600 for modal title.
  static/styles/modal.css
Labels: size: XS

#21250 popovers: Add topic auto-complete to "Move topic" menu
  static/js/stream_popover.js
  static/templates/move_topic_to_stream.hbs
Labels: size: M, integration review

#16124 stream: Do not hide stream email on live update after unsubscribing.
  static/js/stream_settings_ui.js
  static/js/stream_ui_updates.js
Labels: size: XS, integration review

#22453 integration: Fix integration with newrelic.
  zerver/webhooks/newrelic/fixtures/incident_acknowledged_new.json
  zerver/webhooks/newrelic/fixtures/incident_acknowledged_old.json
  zerver/webhooks/newrelic/fixtures/incident_active_new.json
  zerver/webhooks/newrelic/fixtures/incident_closed_new.json
  zerver/webhooks/newrelic/fixtures/incident_closed_old.json
  zerver/webhooks/newrelic/fixtures/incident_created_new.json
  zerver/webhooks/newrelic/fixtures/incident_default_fields_new.json
  zerver/webhooks/newrelic/fixtures/incident_default_fields_old.json
  zerver/webhooks/newrelic/fixtures/incident_malformatted_time_new.json
  zerver/webhooks/newrelic/fixtures/incident_malformatted_time_old.json
  zerver/webhooks/newrelic/fixtures/incident_missing_current_state_old.json
  zerver/webhooks/newrelic/fixtures/incident_missing_state_new.json
  zerver/webhooks/newrelic/fixtures/incident_missing_timestamp_new.json
  zerver/webhooks/newrelic/fixtures/incident_missing_timestamp_old.json
  zerver/webhooks/newrelic/fixtures/incident_opened_old.json
  zerver/webhooks/newrelic/fixtures/incident_state_not_recognized_new.json
  zerver/webhooks/newrelic/fixtures/incident_state_not_recognized_old.json
  zerver/webhooks/newrelic/fixtures/incident_time_too_large_new.json
  zerver/webhooks/newrelic/fixtures/incident_time_too_large_old.json
  zerver/webhooks/newrelic/tests.py
  zerver/webhooks/newrelic/view.py
Labels: size: XL

#22403 Update /jobs page
  templates/corporate/jobs.html
Labels: size: XL

#22600 realm_reactivation: Migrate old Confirmations to the new data format.
  zerver/migrations/0401_migrate_old_realm_reactivation_links.py
Labels: size: L

#22610 migration: Tweak migration 0401 to exit early on most servers.
  zerver/migrations/0401_migrate_old_realm_reactivation_links.py
Labels: size: XS

#22614 Fix references to new user and stream announcments.
  static/templates/invite_subscription.hbs
  zerver/openapi/zulip.yaml
Labels: size: S

#22597 settings: Improve delete user group confirmation modal.
  static/js/settings_user_groups.js
  static/templates/confirm_dialog/confirm_delete_user.hbs
Labels: size: S, integration review

#22609 delete message: Updated modal text.
  static/js/message_edit.js
  static/templates/confirm_dialog/confirm_delete_message.hbs
Labels: size: XS

#22003 fix:Checking if file size is too big
  frontend_tests/node_tests/upload.js
  static/js/upload.js
Labels: size: M, integration review

#22615 help-docs: Clarify instructions for setting email notifications.
  templates/zerver/help/using-zulip-via-email.md
Labels: size: XS, integration review

#20382 settings: Remove extraneous banner from settings tabs
  static/js/admin.js
Labels: size: XS, integration review

#22624 test_runner: Remove _destroy_test_db monkey patch
  zerver/lib/test_runner.py
Labels: size: M, integration review

#22620 test_logging_handlers: Fix type errors in test_request.
  zerver/tests/test_logging_handlers.py
Labels: size: M, integration review

#22626 support: Correctly show Unspecified org type at /activity/support.
  analytics/tests/test_support_views.py
  templates/analytics/realm_details.html
Labels: size: M

#22613 email_backends: Improve type annotations for EmailLogBackEnd.
  zproject/email_backends.py
Labels: size: S, integration review

#22604 Use a real parser for email addresses
  frontend_tests/node_tests/filter.js
  package.json
  static/js/people.js
  tools/tail-ses
  version.py
  yarn.lock
  zerver/actions/message_send.py
  zerver/actions/realm_settings.py
  zerver/actions/users.py
  zerver/data_import/slack.py
  zerver/forms.py
  zerver/lib/create_user.py
  zerver/lib/dev_ldap_directory.py
  zerver/lib/email_mirror.py
  zerver/lib/email_validation.py
  zerver/lib/url_encoding.py
  zerver/migrations/0373_fix_deleteduser_dummies.py
  zerver/models.py
  zerver/openapi/python_examples.py
  zerver/tests/test_auth_backends.py
  zerver/tests/test_bots.py
  zerver/tests/test_email_mirror.py
  zerver/tests/test_message_send.py
  zerver/tests/test_realm.py
  zerver/views/auth.py
  zerver/views/message_send.py
  zerver/views/users.py
  zerver/views/zephyr.py
  zerver/webhooks/pagerduty/view.py
  zproject/backends.py
  zproject/default_settings.py
Labels: size: XL, integration review

#22631 message_send: Avoid setting service_queue_events on message objects.
  zerver/actions/message_send.py
  zerver/lib/message.py
Labels: size: S, integration review
