Repository zulip/zulip, pull requests merged in 2022-09, with the labels that each got.

#22838 puppet: Remove nginx configuration for zulip.org
  puppet/zulip_ops/files/nginx/sites-available/zulip-org
Labels: size: M

#22765 message_edit: Use `disabled` instead of `readonly` to disable controls.
  static/js/message_edit.js
Labels: size: S

#22824 portico: Fix title and description for /attribution.
  templates/corporate/attribution.html
Labels: size: XS

#22840 Update README.md
  README.md
  templates/zerver/help/include/advantages-of-self-hosting-zulip.md
Labels: size: S

#21374 left-sidebar: Make the background-color of unread_count consistent on…
  static/styles/dark_theme.css
Labels: area: left-sidebar, priority: high, size: XS

#22507 integrations: Add Azure DevOps webhook integration.
  static/images/integrations/azuredevops/001.png
  static/images/integrations/bot_avatars/azuredevops.png
  static/images/integrations/logos/azuredevops.svg
  zerver/lib/integrations.py
  zerver/webhooks/azuredevops/__init__.py
  zerver/webhooks/azuredevops/doc.md
  zerver/webhooks/azuredevops/fixtures/code_pull_request__merge_attempted.json
  zerver/webhooks/azuredevops/fixtures/code_pull_request__merged.json
  zerver/webhooks/azuredevops/fixtures/code_pull_request__opened.json
  zerver/webhooks/azuredevops/fixtures/code_pull_request__opened_without_description.json
  zerver/webhooks/azuredevops/fixtures/code_pull_request__updated.json
  zerver/webhooks/azuredevops/fixtures/code_push.json
  zerver/webhooks/azuredevops/fixtures/code_push__commits_more_than_limit.json
  zerver/webhooks/azuredevops/fixtures/code_push__local_branch_without_commits.json
  zerver/webhooks/azuredevops/fixtures/code_push__multiple_committers.json
  zerver/webhooks/azuredevops/fixtures/code_push__multiple_committers_with_others.json
  zerver/webhooks/azuredevops/fixtures/code_push__remove_branch.json
  zerver/webhooks/azuredevops/tests.py
  zerver/webhooks/azuredevops/view.py
Labels: size: XL, integration review

#22842 user_status_ui: Add "At the office" option.
  static/js/user_status_ui.js
Labels: size: XS, integration review

#22854 help center: Add warnings/advice to "Import from Slack" page.
  templates/zerver/help/import-from-slack.md
Labels: size: S

#22856 help center: Add question about Free plan to Zulip Cloud Billing page.
  templates/zerver/help/zulip-cloud-billing.md
Labels: size: S, integration review

#22835 settings: Move custom input div inside the main setting div.
  static/styles/settings.css
  static/styles/zulip.css
  static/templates/invite_user.hbs
  static/templates/settings/notification_settings.hbs
  static/templates/settings/organization_permissions_admin.hbs
Labels: size: XL

#22867 timepicker: Fix hours and minutes input getting squeeze in safari.
  static/styles/zulip.css
Labels: bug, area: compose, priority: high, size: XS

#22860 internal_prep_private_message: Remove redundant realm arg.
  zerver/actions/message_send.py
  zerver/tests/test_message_send.py
  zerver/views/streams.py
Labels: size: S

#22874 sentry: Properly stringify a possibly-None result.
  zerver/webhooks/sentry/view.py
Labels: size: XS

#22710 usermessage: Use select for update with order by in bulk usermessage update.
  zerver/actions/message_flags.py
  zerver/lib/push_notifications.py
  zerver/models.py
  zerver/tests/test_message_flags.py
  zerver/worker/queue_processors.py
Labels: size: XL

#22847 help-docs: Rename organization language help center file.
  static/templates/settings/organization_settings_admin.hbs
  templates/zerver/help/change-your-language.md
  templates/zerver/help/configure-multi-language-search.md
  templates/zerver/help/configure-notification-bot.md
  templates/zerver/help/configure-organization-language.md
  templates/zerver/help/include/customize-settings-for-new-users.md
  templates/zerver/help/include/sidebar_index.md
  templates/zerver/help/invite-new-users.md
  zerver/lib/url_redirects.py
  zerver/openapi/zulip.yaml
Labels: area: documentation (user), priority: high, size: S, release goal, integration review

#22656 contributor docs: Clarify instructions for claiming an issue.
  CONTRIBUTING.md
Labels: size: S, integration review

#22870 delete code playground: Add confirmation dialog.
  frontend_tests/puppeteer_tests/realm-playground.ts
  static/js/settings_playgrounds.js
  static/templates/confirm_dialog/confirm_delete_playground.hbs
Labels: size: M, integration review

#22869 delete data exports: Add confirmation dialog.
  static/js/settings_exports.js
  static/templates/confirm_dialog/confirm_delete_data_export.hbs
Labels: size: S, integration review

#22871 delete linkifier: Add confirmation dialog.
  frontend_tests/puppeteer_tests/realm-linkifier.ts
  static/js/settings_linkifiers.js
  static/templates/confirm_dialog/confirm_delete_linkifier.hbs
Labels: size: S, integration review

#21529 webpack: Add a hook to print a compilation successful message.
  webpack.config.ts
Labels: size: S

#22886 Updated tip at the bottom of the? menu "Search operators" tab
  static/templates/search_operators.hbs
Labels: size: XS

#22881 message_fetch: Remove obsolete UnicodeDecodeError handler
  zerver/views/message_fetch.py
Labels: size: S

#22880 requirements: Remove unused mypy.txt lock file
  docs/testing/mypy.md
  requirements/README.md
  requirements/mypy.in
  requirements/mypy.txt
  tools/update-locked-requirements
Labels: size: XL

#22606 Fedora 36 support.
  Vagrantfile
  docs/development/setup-vagrant.md
Labels: size: S, integration review

#22895 stripe: Fix WildValue usage
  zerver/webhooks/stripe/view.py
Labels: size: S

#22897 template_parser: Spell “Handlebars” correctly
  tools/check-templates
  tools/lib/pretty_print.py
  tools/lib/template_parser.py
Labels: size: M

#22901 puppeteer: Fix dropdown click flake in `admin.ts`.
  frontend_tests/puppeteer_tests/admin.ts
Labels: size: S

#22889 help center: Update "SAML authentication" page to follow help center guidelines
  static/images/help/azuread_saml_attrs.png
  static/images/help/onelogin_parameters.png
  templates/zerver/help/import-from-slack.md
  templates/zerver/help/include/cloud-plus-only.md
  templates/zerver/help/include/saml-login-button.md
  templates/zerver/help/include/send-us-info.md
  templates/zerver/help/include/upgrade-to-plus-if-needed.md
  templates/zerver/help/saml-authentication.md
  zerver/lib/markdown/tabbed_sections.py
Labels: size: XL

#21040 Add new right_sidebar_style setting.
  frontend_tests/node_tests/activity.js
  frontend_tests/node_tests/buddy_data.js
  frontend_tests/node_tests/dispatch.js
  frontend_tests/node_tests/lib/events.js
  static/js/admin.js
  static/js/buddy_data.js
  static/js/realm_user_settings_defaults.ts
  static/js/server_events_dispatch.js
  static/js/settings.js
  static/js/settings_config.ts
  static/js/settings_display.js
  static/js/settings_org.js
  static/js/settings_realm_user_settings_defaults.js
  static/js/user_settings.ts
  static/styles/right_sidebar.css
  static/styles/settings.css
  static/templates/presence_row.hbs
  static/templates/settings/display_settings.hbs
  static/templates/settings/organization_user_settings_defaults.hbs
  templates/zerver/api/changelog.md
  version.py
  zerver/migrations/0407_userprofile_user_list_style.py
  zerver/models.py
  zerver/openapi/zulip.yaml
  zerver/tests/test_events.py
  zerver/tests/test_realm.py
  zerver/tests/test_settings.py
  zerver/views/realm.py
  zerver/views/user_settings.py
Labels: size: XL, release goal, chat.zulip.org review

#22546 Rocketchat import fixes
  zerver/data_import/rocketchat.py
  zerver/tests/test_rocketchat_importer.py
Labels: size: XL, integration review

#21839 UI redesign: Change mute icon from bell to speaker in the UI and help docs.
  docs/THIRDPARTY
  static/shared/icons/mute.svg
  static/styles/popovers.css
  static/styles/recent_topics.css
  static/styles/settings.css
  static/styles/zulip.css
  static/templates/recent_topic_row.hbs
  static/templates/recipient_row.hbs
  static/templates/settings/stream_specific_notification_row.hbs
  static/templates/settings_overlay.hbs
  static/templates/stream_sidebar_actions.hbs
  static/templates/topic_sidebar_actions.hbs
  templates/zerver/help/mute-a-topic.md
Labels: area: settings (user), area: documentation (user), size: M, area: message feed UI, redesign, chat.zulip.org review

#22912 puppeteer_tests: Convert now-deprecated waitForXPath, $x methods
  frontend_tests/puppeteer_lib/common.ts
  frontend_tests/puppeteer_tests/admin.ts
  frontend_tests/puppeteer_tests/compose.ts
  frontend_tests/puppeteer_tests/custom-profile.ts
  frontend_tests/puppeteer_tests/mention.ts
  frontend_tests/puppeteer_tests/navigation.ts
  frontend_tests/puppeteer_tests/settings.ts
  frontend_tests/puppeteer_tests/stream_create.ts
Labels: size: L

#22878 read_receipts: Alter translation string in accordance with Transifex.
  static/js/read_receipts.js
Labels: size: S

#22921 puppeteer_tests: Fix compose test trying to click local echoes
  frontend_tests/puppeteer_tests/compose.ts
  frontend_tests/puppeteer_tests/delete-message.ts
  frontend_tests/puppeteer_tests/edit.ts
Labels: size: M

#22922 zilencer: Fix missing decorators on remote_server_dispatch.
  zilencer/auth.py
Labels: size: XS

#22926 templates: Remove prefilled support email content from error pages.
  templates/500.html
  templates/zerver/unsubscribe_link_error.html
Labels: size: XS

#22927 templates: Fix curly-quoted HTML attributes
  templates/zerver/footer.html
  templates/zerver/landing_nav.html
Labels: size: XS

#22930 puppeteer_tests: Skip apparently broken part of message-basics test
  frontend_tests/puppeteer_tests/message-basics.ts
Labels: size: XS

#22925 forms: Update create organization part of registration form.
  static/styles/portico/portico_signin.css
  templates/zerver/register.html
Labels: size: S, integration review

#22918 help center: Fix indendation in saml-authentication.md azuread part.
  templates/zerver/help/saml-authentication.md
Labels: size: XS, integration review

#22924 export: Do not export direct_members and direct_subgroups field.
  zerver/lib/export.py
  zerver/lib/import_realm.py
  zerver/tests/test_import_export.py
Labels: size: M

#22936 org settings: Move invitations required checkbox to the top.
  static/templates/settings/organization_permissions_admin.hbs
Labels: size: S

#22019 fix: move avatar border outside the image in full profile
  static/styles/popovers.css
Labels: bug, good first issue, size: XS, area: popovers, integration review

#22950 refresh-sharding-and-restart: Quote to prevent shell glob expansion
  scripts/refresh-sharding-and-restart
Labels: size: XS

#22953 subdomain: Remove impossible None case from user_matches_subdomain
  zerver/lib/subdomains.py
Labels: size: XS

#22948 populate_analytics_db: Remove unnecessary mock
  analytics/management/commands/populate_analytics_db.py
Labels: size: S

#22932 test_decorators: Remove cachify test cases.
  zerver/tests/test_decorators.py
Labels: size: L, integration review

#22962 edit user: Place deactivate button outside the `form` element in modal.
  static/templates/settings/admin_human_form.hbs
  static/templates/settings/edit_bot_form.hbs
Labels: size: S

#22960 popovers: Align icons and content in middle.
  static/styles/popovers.css
Labels: size: M

#22748 docs: Fix development environment setup on Windows.
  docs/development/index.md
  docs/development/overview.md
  docs/development/remote.md
  docs/development/setup-advanced.md
  docs/development/setup-recommended.md
  docs/git/cloning.md
  docs/git/setup.md
  tools/lib/provision.py
  tools/provision
Labels: area: documentation (developer), priority: high, size: XL, integration review

#22772 help: Document "import personal settings" feature.
  templates/zerver/help/import-your-settings.md
  templates/zerver/help/include/sidebar_index.md
  templates/zerver/help/invite-new-users.md
  templates/zerver/help/join-a-zulip-organization.md
  templates/zerver/help/review-your-settings.md
  templates/zerver/help/switching-between-organizations.md
  templates/zerver/register.html
Labels: area: documentation (user), size: L, integration review

#22919 models: Improve comment documentation around Recipients and Huddles.
  zerver/models.py
Labels: size: L, integration review

#22971 stream_list: Fix another “subscribed” typo
  static/js/stream_list.js
  static/templates/subscribe_to_more_streams.hbs
Labels: size: XS

#22972 landing_nav: Add tabnabbing protection to external target="_blank" link
  templates/zerver/landing_nav.html
Labels: size: XS

#22975 event_queue: Replace sequential queue IDs with UUIDs
  zerver/tornado/event_queue.py
Labels: size: S

#22978 popovers: Align icons and content in middle.
  static/styles/popovers.css
Labels: size: M

#22970 realm_export: Improve estimate of data export size.
  zerver/tests/test_realm_export.py
  zerver/views/realm_export.py
Labels: size: M, integration review

#21229 Adjust limits (expiry, max uses) for missed messages to improve usability
  zerver/lib/email_mirror.py
  zerver/models.py
  zerver/tests/test_email_mirror.py
Labels: size: M, integration review

#22985 modals: Add `data-simplebar` to `login` and `api key` modal.
  static/templates/login_to_access.hbs
  static/templates/settings/api_key_modal.hbs
Labels: size: XS

#22983 corporate: Add request for cover letter to job application instructions.
  templates/corporate/jobs.html
Labels: size: M

#22982 python: Use ‘not in’ for negated membership tests
  scripts/lib/check_rabbitmq_queue.py
  zerver/lib/events.py
Labels: size: XS

#19817 Slack import: Translate to emoji name to codepoint using iamcal data.
  zerver/data_import/slack.py
  zerver/tests/test_slack_importer.py
Labels: size: M, integration review

#22979 bots: Replace some redundant logic with is_cross_realm_bot_email.
  zerver/lib/users.py
  zerver/models.py
Labels: size: S

#22989 stream_edit: Fix warning in confirm dialog modal from sub-unsub modal.
  static/js/stream_settings_ui.js
Labels: size: S

#22999 zilencer: Mark remote_server_dispatch request argument positional-only
  zilencer/auth.py
Labels: size: XS

#22997 streams: Fix can_remove_subscribers_from_stream type
  zerver/lib/streams.py
Labels: size: XS

#22996 buddy-data: Remove unused `get_my_user_status` function.
  frontend_tests/node_tests/activity.js
  frontend_tests/node_tests/buddy_data.js
  static/js/buddy_data.js
Labels: size: M

#23000 models: Tighten type annotation for query_for_ids
  zerver/models.py
Labels: size: S

#22992 view_code_in_playground: Fix tooltip being partially hidden.
  static/js/tippyjs.js
  static/templates/view_code_in_playground.hbs
Labels: size: XS

#22990 forms: Fix another 500 error on realm creation with invalid email
  zerver/forms.py
  zerver/tests/test_signup.py
Labels: size: S

#23002 buddy-data: Remove unimplemented `user_circle_status` description.
  frontend_tests/node_tests/activity.js
  frontend_tests/node_tests/buddy_data.js
  static/js/buddy_data.js
Labels: size: M

#23003 test_runner: Remove monkey-patched SubSuiteList.
  zerver/lib/test_runner.py
Labels: size: M

#22977 i18n: Add translation tags to default external accounts name.
  zerver/lib/events.py
  zerver/lib/external_accounts.py
Labels: size: S

#23006 external_accounts: Make ExternalAccount dataclass to fix typing
  zerver/actions/custom_profile_fields.py
  zerver/lib/external_accounts.py
  zerver/tests/test_custom_profile_data.py
Labels: size: L, integration review

#22987 tornado: Raise the same error for nonexistent and unauthorized queues
  zerver/tests/test_event_queue.py
  zerver/tests/test_event_system.py
  zerver/tornado/event_queue.py
  zerver/tornado/views.py
Labels: size: L, integration review

#23008 timezone: Improve tzdata parser’s compatibility with zic(8)
  zerver/lib/timezone.py
Labels: size: XS, integration review

#23011 tooling: development environment sentence case updates
  templates/zerver/development/dev_login.html
Labels: size: S

#23012 settings: Move display_in_profile_summary checkbox to center.
  static/styles/settings.css
  static/templates/settings/admin_profile_field_list.hbs
Labels: size: S

#22981 Revision pass on #22974 (document how to edit a bot)
  templates/zerver/help/edit-a-bot.md
  templates/zerver/help/include/sidebar_index.md
  templates/zerver/help/view-all-bots-in-your-organization.md
Labels: area: documentation (user), area: bots, size: L, integration review

#23021 rendered_markdown: Fix alignment of icons in code blocks.
  static/styles/rendered_markdown.css
Labels: size: S

#23027 Revert "zulip-puppet-apply: Work around broken Puppet on Ubuntu 22.04."
  scripts/lib/ruby3hack.rb
  scripts/zulip-puppet-apply
Labels: size: S, integration review

#23020 help: Fix "Related articles" in the bots section.
  templates/zerver/help/add-a-bot-or-integration.md
  templates/zerver/help/bots-and-integrations.md
  templates/zerver/help/deactivate-or-reactivate-a-bot.md
  templates/zerver/help/request-an-integration.md
  templates/zerver/help/restrict-bot-creation.md
  templates/zerver/help/view-all-bots-in-your-organization.md
Labels: size: M, integration review

#22931 help: Restructure "Mastering the compose box" article.
  templates/zerver/help/enable-enter-to-send.md
  templates/zerver/help/include/compose-and-send-message.md
  templates/zerver/help/include/set-up-your-account.md
  templates/zerver/help/include/sidebar_index.md
  templates/zerver/help/keyboard-shortcuts.md
  templates/zerver/help/mastering-the-compose-box.md
  zerver/lib/url_redirects.py
  zerver/openapi/zulip.yaml
Labels: size: XL, integration review

#23026 populate_db: Limit user_profiles for private messages to zulip realm.
  zilencer/management/commands/populate_db.py
Labels: size: XS

#23034 slack: Filter out non-.json files for processing.
  zerver/data_import/slack.py
Labels: size: XS

#23015 portico: Fix footer text overflow in different languages.
  static/styles/portico/portico.css
Labels: size: S

#23028 reload: Preserve unused reload tokens for a week.
  frontend_tests/node_tests/reload.js
  static/js/localstorage.js
  static/js/reload.js
Labels: bug, area: misc, priority: high, size: L, release goal

#23037 docs: Fix extra period typo
  docs/development/remote.md
Labels: size: XS

#23038 tornado: Fix Tornado CSRF check with X-Forwarded-Proto
  puppet/zulip/files/nginx/zulip-include-common/proxy
  zerver/management/commands/runtornado.py
Labels: size: XS, backport candidate, integration review

#21477 mark-as-unread: Add webapp UI support for marking messages as unread.
  frontend_tests/node_tests/hotkey.js
  frontend_tests/node_tests/message_flags.js
  frontend_tests/node_tests/popovers.js
  static/js/hotkey.js
  static/js/message_flags.js
  static/js/message_list.js
  static/js/message_list_data.js
  static/js/popovers.js
  static/js/unread_ops.js
  static/js/unread_ui.js
  static/styles/dark_theme.css
  static/styles/popovers.css
  static/templates/actions_popover_content.hbs
  static/templates/keyboard_shortcuts.hbs
  templates/zerver/help/keyboard-shortcuts.md
Labels: size: XL, release goal, chat.zulip.org review

#23041 scim: Downgrade SCIMClient from a model to an ephemeral dataclass
  zerver/lib/export.py
  zerver/management/commands/add_scim_client.py
  zerver/middleware.py
  zerver/migrations/0415_delete_scimclient.py
  zerver/models.py
  zerver/tests/test_scim.py
Labels: size: L, integration review

#23043 style：Fix bug of background color of narrow stream settings
  static/styles/subscriptions.css
Labels: size: XS, integration review

#23058 python: Use ‘not in’ for more negated membership tests
  scripts/nagios/check-rabbitmq-consumers
  tools/test-js-with-node
Labels: size: XS

#23057 analytics: Remove unused click handler in populate messages by client.
  static/js/stats/stats.js
Labels: size: S

#23049 Fix global icon margin in message view header
  static/styles/zulip.css
Labels: size: XS

#23060 messagebox: Undo regression that removed higlights for mentions.
  static/styles/dark_theme.css
  static/styles/zulip.css
Labels: size: S

#23061 scim: Use setattr to set request.user as scim_client
  zerver/middleware.py
Labels: size: XS, integration review

#23073 models: Rename get_huddle to get_or_create_huddle.
  zerver/models.py
  zilencer/management/commands/populate_db.py
Labels: size: S

#23069 templates: Improve footer content on documentation pages.
  templates/zerver/documentation_main.html
  zerver/tests/test_middleware.py
Labels: area: production, area: documentation (user), area: documentation (api and integrations), priority: high, size: S, release goal

#23074 import_util: Make build_message only take kwargs.
  zerver/data_import/gitter.py
  zerver/data_import/import_util.py
  zerver/data_import/slack.py
Labels: size: M

#23070 help: Document upgrading Ubuntu 20.04 to 22.04
  docs/production/upgrade-or-modify.md
Labels: area: documentation (production), size: L, release goal

#22096 events: Ensure spectators don't have streams and subs information.
  templates/zerver/api/changelog.md
  version.py
  zerver/lib/events.py
  zerver/openapi/zulip.yaml
  zerver/tests/test_event_system.py
  zerver/views/events_register.py
Labels: size: XL, integration review

#22894 message_fetch: Move narrowing query builder to zerver.lib.narrow
  zerver/lib/narrow.py
  zerver/tests/test_message_fetch.py
  zerver/views/message_fetch.py
Labels: size: XL

#23091 portico: Minor updates to /for/X pages.
  templates/corporate/for/communities.md
  templates/corporate/for/open-source.html
  templates/corporate/for/research.html
Labels: size: M, integration review

#23082 templates: Use help link widget in invite user modal.
  static/templates/invite_user.hbs
Labels: size: XS

#23081 user_info_popover: Not displaying "Manage this bot" for system bots.
  static/js/popovers.js
Labels: size: XS

#22858 delete attachments: Add confirmation dialog.
  static/js/attachments_ui.js
  static/templates/confirm_dialog/confirm_delete_attachment.hbs
Labels: area: settings (user), size: M, integration review

#22940 settings: Prevent page reload when user presses `Enter` on full name input.
  frontend_tests/puppeteer_tests/settings.ts
  static/js/settings_account.js
  static/styles/settings.css
  static/templates/settings/profile_settings.hbs
Labels: bug, area: settings UI, priority: high, size: S, integration review

#23105 test_runner: Remove empty ParallelTestSuite.__init__ override
  zerver/lib/test_runner.py
Labels: size: S

#23093 scim: Slim down SCIMClient
  zerver/middleware.py
  zerver/tests/test_scim.py
Labels: size: M

#23108 tests: Disable lazy loading of moto
  zerver/lib/test_helpers.py
  zerver/tests/test_transfer.py
Labels: size: XS, integration review

#23104 tornado: Construct Django BaseHandler once, not per-request
  zerver/tornado/application.py
  zerver/tornado/handlers.py
Labels: size: M, integration review

#22976 Open communitie revision
  static/styles/portico/integrations.css
  templates/corporate/communities.html
Labels: size: M, integration review

#23095 contributor docs: Add a page on design discussions.
  .codespellignore
  docs/contributing/design-discussions.md
  docs/contributing/index.md
Labels: size: XL, integration review
