Repository zulip/zulip, pull requests merged in 2022-11, with the labels that each got.

#23386 markdown: Pass realm down into render_stream_description.
  zerver/actions/custom_profile_fields.py
  zerver/actions/streams.py
  zerver/lib/bulk_create.py
  zerver/lib/import_realm.py
  zerver/lib/streams.py
  zerver/migrations/0206_stream_rendered_description.py
  zerver/tests/test_subs.py
Labels: bug, area: stream settings, priority: high, size: S, markdown (embeds/previews)

#23398 help-menu: Update tip at the bottom of search operators tab.
  static/templates/search_operators.hbs
Labels: bug, good first issue, area: documentation (user), size: S, area: popovers

#23404 shared: Bump version to 0.0.15
  static/shared/package.json
Labels: size: XS

#23412 shared: Fix typeahead.js.flow to add Emoji['reaction_type'].
  static/shared/js/typeahead.js.flow
Labels: size: S

#23410 shared: Prescribe atomic push when bumping version.
  static/shared/tools/npm-postversion
Labels: area: tooling, area: mobile, size: XS

#23403 unread: Use unread_topic_counter to get message details.
  static/js/unread.js
Labels: size: L, integration review

#23415 gear_menu: Change sponsored plan name.
  static/templates/gear_menu.hbs
Labels: size: XS

#23417 popovers: Do not show option to mark unread for unsubscribed streams.
  static/js/popovers.js
Labels: size: S

#23397 delete_topic: Use the same timeout pattern as /mark_all_as_read.
  static/js/message_edit.js
  templates/zerver/api/changelog.md
  version.py
  zerver/lib/test_helpers.py
  zerver/openapi/zulip.yaml
  zerver/tests/test_message_flags.py
  zerver/tests/test_message_topics.py
  zerver/views/streams.py
Labels: size: XL, release goal

#23413 shared: Bump version to 0.0.16
  static/shared/package.json
Labels: size: XS

#23418 message: Ignore messages in unsubcribed streams when marking them unread.
  zerver/actions/message_flags.py
  zerver/tests/test_message_flags.py
Labels: size: XL

#23390 stream_settings: link to /help/change-the-stream description from stream settings
  static/templates/stream_settings/change_stream_info_modal.hbs
  static/templates/stream_settings/stream_creation_form.hbs
Labels: size: XS, integration review

#23424 help center: Add a detail to /help/mute-a-stream.
  templates/zerver/help/mute-a-stream.md
Labels: release goal, integration review

#23433 install-node: Silence expected “node: command not found” on first run
  scripts/lib/install-node
  tools/setup/install-shellcheck
  tools/setup/install-shfmt
Labels: size: S, integration review

#23432 import: Narrow the id-window to just the current realm.
  zerver/lib/import_realm.py
Labels: area: export/import, size: S

#23372 help-docs: Update search for messages article about "group-pm-with".
  templates/zerver/help/search-for-messages.md
Labels: size: M, product review

#23434 requirements: Upgrade Python requirements
  requirements/common.in
  requirements/dev.in
  requirements/dev.txt
  requirements/docs.txt
  requirements/mypy.in
  requirements/pip.txt
  requirements/prod.txt
  version.py
  zerver/openapi/zulip.yaml
Labels: size: XL, integration review

#23416 topic_list: Move topic filter out of topics list `ul`.
  frontend_tests/node_tests/stream_list.js
  static/js/stream_list.js
  static/js/topic_list.js
  static/styles/left_sidebar.css
  static/templates/filter_topics.hbs
Labels: size: XL

#23447 help center: Update list of fields in full profile.
  templates/zerver/help/view-someones-profile.md
Labels: size: M, integration review

#23446 build_emoji: Guard mutable default with read-only type
  tools/setup/emoji/build_emoji
Labels: size: S, integration review

#23444 rest: Restrict access to json views via basic auth.
  zerver/lib/rest.py
  zerver/tests/test_event_system.py
  zerver/tests/test_message_send.py
  zerver/tests/test_read_receipts.py
  zerver/tests/test_realm_playgrounds.py
  zerver/tests/test_user_groups.py
Labels: size: L

#23442 docs: Document docker-zulip postgres upgrade requirement.
  docs/overview/changelog.md
Labels: size: S

#23448 docs: Remove ": bool" from Writing a new application feature
  docs/tutorials/new-feature-tutorial.md
Labels: size: S

#23289 search: Check if user is subscribed before requesting stream data.
  static/js/search_suggestion.js
  static/js/stream_data.js
Labels: size: M

#23454 Set correct `max-height ` for left-sidebar blocks.
  static/js/resize.js
Labels: size: S

#23459 css: Fix height issue for stream and user group creation forms.
  static/styles/subscriptions.css
Labels: size: M

#23452 help center: Mention "Scroll to bottom" to mark Topics and PMs as read.
  templates/zerver/help/include/reading-pms.md
  templates/zerver/help/include/reading-topics.md
Labels: area: documentation (user), priority: high, size: S, release goal, integration review

#23426 popovers: Add bottom margin to input.
  static/styles/popovers.css
Labels: bug, good first issue, size: XS, area: popovers, integration review

#23465 slack: Skip emoji skintone variants.
  zerver/data_import/slack.py
Labels: area: emoji, area: export/import, size: S

#23487 Minor ruff configuration tweaks
  pyproject.toml
Labels: size: S

#23481 help center: Drop extraneous Desktop/Web tab from /help/emoji-reactions.
  templates/zerver/help/emoji-reactions.md
Labels: size: XS, integration review

#23473 api-docs: Return 404 for direct `/api-doc-template` call.
  zerver/tests/test_docs.py
  zerver/views/documentation.py
Labels: bug, area: documentation (api and integrations), size: S

#22956 rate_limiting: Document and add interface for admins to override rules.
  docs/production/security-model.md
  zproject/computed_settings.py
  zproject/default_settings.py
  zproject/prod_settings_template.py
Labels: size: XL, integration review

#23483 help center: Document viewing read receipts on mobile.
  templates/zerver/help/include/message-long-press-menu.md
  templates/zerver/help/read-receipts.md
Labels: area: documentation (user), priority: high, size: S, release goal, integration review

#23445 help center: Mention stream section labels.
  templates/zerver/help/manage-inactive-streams.md
  templates/zerver/help/pin-a-stream.md
Labels: area: documentation (user), priority: high, size: S, release goal, integration review

#23490 narrow-banner: Update empty title for "pm-with" multiple users.
  frontend_tests/node_tests/narrow.js
  static/js/narrow_banner.js
Labels: size: XS, integration review

#23381 add: Links to help center articles for notification settings.
  static/templates/settings/notification_settings.hbs
Labels: good first issue, area: settings (user), size: S, integration review

#23463 list_widget: Add functions to modify meta.offset value.
  static/js/list_widget.js
  static/js/recent_topics_ui.js
  tools/test-js-with-node
Labels: size: L

#23500 docs: Update to match current admin.js
  docs/tutorials/new-feature-tutorial.md
Labels: size: S, integration review

#23498 help center: Update documentation on reading private messages.
  templates/zerver/help/include/reading-pms.md
Labels: area: documentation (user), size: S, release goal, integration review

#23488 help center: Document notification triggers.
  templates/zerver/help/desktop-notifications.md
  templates/zerver/help/email-notifications.md
  templates/zerver/help/mobile-notifications.md
Labels: area: documentation (user), size: M, release goal, integration review

#23505 api: Link to new rate-limiting configuration documentation.
  templates/zerver/api/rest-error-handling.md
Labels: size: S

#23511 tools: Upgrade scrapy's settings.py to the latest version.
  tools/documentation_crawler/documentation_crawler/settings.py
Labels: size: M

#23507 tools: Remove obsolete `_set_error_state` method in `UnusedImagesLinterSpider`.
  tools/documentation_crawler/documentation_crawler/spiders/check_help_documentation.py
Labels: size: XS

#23437 middleware: Set the correct options on the django_language cookie
  zerver/middleware.py
  zproject/computed_settings.py
Labels: size: S, integration review

#23495 help center: Document viewing @-mentions.
  static/images/help/mobile-at-sign-icon.svg
  templates/zerver/help/include/sidebar_index.md
  templates/zerver/help/mention-a-user-or-group.md
  templates/zerver/help/pm-mention-alert-notifications.md
  templates/zerver/help/star-a-message.md
  templates/zerver/help/view-your-mentions.md
Labels: area: documentation (user), priority: high, size: L, release goal, integration review

#23514 portico: Add new features to /features page.
  templates/corporate/features.html
Labels: size: S, release goal, integration review

#22859 left_sidebar: Hide stream section separator when there is only one.
  frontend_tests/node_tests/stream_list.js
  static/js/stream_list.js
Labels: size: S

#23504 help center: Improve "analytics" article.
  templates/zerver/help/analytics.md
  templates/zerver/help/include/sidebar_index.md
  templates/zerver/help/public-access-option.md
Labels: area: documentation (user), size: S, release goal, integration review

#23378 help center: Update "Import from Slack/Mattermost/Gitter/Rocket.Chat".
  templates/zerver/help/import-from-slack.md
  templates/zerver/help/include/import-get-your-organization-started.md
  templates/zerver/help/include/import-how-users-will-log-in.md
  templates/zerver/help/include/import-into-a-self-hosted-zulip-server.md
  templates/zerver/help/include/import-into-a-zulip-cloud-organization.md
  templates/zerver/help/include/import-self-hosted-server-tips.md
  templates/zerver/help/include/import-workspace-to-zulip.md
  templates/zerver/help/include/import-your-data-into-zulip.md
  templates/zerver/help/include/import-zulip-cloud-organization-warning.md
Labels: size: XL, integration review

#23513 user_profile_modal: Move presence activity status to modal header.
  static/styles/popovers.css
  static/templates/user_profile_modal.hbs
Labels: size: S, integration review

#23510 mark-unread: Load `mark_as_read_turned_off_banner` immediately.
  static/js/unread_ops.js
Labels: bug, priority: high, size: S, release goal, area: message feed UI

#23523 settings_org: Fix bug of save-discard widget not hiding correctly and refactor code for message retention setting.
  frontend_tests/node_tests/settings_org.js
  static/js/settings_org.js
  static/templates/settings/organization_settings_admin.hbs
Labels: size: XL, integration review

#23499 compose: Use text-area-edit for syntax replacements.
  frontend_tests/node_tests/compose_ui.js
  static/js/compose_ui.js
Labels: size: XL

#23518 settings_user: change audio to audible in settings, notifications hea…
  static/templates/settings/notification_settings.hbs
Labels: good first issue, area: settings (user), size: XS

#23525 register: Not all clients send a User-Agent header.
  zerver/lib/compatibility.py
  zerver/tests/test_event_system.py
  zerver/views/events_register.py
Labels: size: S

#23477 Add a tool to export a subset of messages, for compliance
  zerver/management/commands/export_search.py
Labels: size: XL

#23050 Fix the bug creating duplicate Confirmations for a PreregistrationUser
  zerver/tests/test_auth_backends.py
  zerver/views/auth.py
Labels: size: L, integration review

#22655 do_reactivate_realm: Noop if realm is already active.
  zerver/actions/realm_settings.py
  zerver/tests/test_realm.py
Labels: size: M

#23535 modals: Don't close the modals on selecting something inside the modal.
  static/js/overlays.js
  static/templates/dialog_widget.hbs
  static/templates/login_to_access.hbs
  static/templates/read_receipts_modal.hbs
  static/templates/settings/api_key_modal.hbs
  static/templates/user_profile_modal.hbs
Labels: bug, area: settings (admin/org), size: M, release goal, area: popovers, integration review

#23538 css: Fix hidden unread marker when a user mentioned message is focused.
  static/styles/zulip.css
Labels: size: XS

#23044 Button text not visible in modal
  static/styles/modal.css
Labels: size: XS

#23522 Remove the "Show user list on left sidebar in narrow windows" display option
  docs/testing/manual-testing.md
  frontend_tests/node_tests/dispatch.js
  frontend_tests/node_tests/i18n.js
  frontend_tests/node_tests/lib/events.js
  static/js/message_viewport.js
  static/js/realm_user_settings_defaults.ts
  static/js/resize.js
  static/js/server_events_dispatch.js
  static/js/settings_config.ts
  static/js/settings_display.js
  static/js/stream_popover.js
  static/js/user_settings.ts
  static/styles/compose.css
  static/styles/left_sidebar.css
  static/styles/right_sidebar.css
  static/styles/typing_notifications.css
  static/styles/zulip.css
  templates/zerver/help/include/sidebar_index.md
  templates/zerver/help/move-the-users-list-to-the-left-sidebar.md
  zerver/models.py
Labels: feedback wanted, area: left-sidebar, priority: high, size: XL, release goal, integration review

#23536 hotkey: Handle `enter` keypress on `body` for recent topics.
  static/js/hotkey.js
Labels: size: S, release goal, product review

#23556 help-docs: Update mobile instructions for invisible mode.
  templates/zerver/help/status-and-availability.md
Labels: size: XS, release goal, integration review

#23557 help center: Add use cases to /help/marking-messages-as-unread.
  templates/zerver/help/marking-messages-as-unread.md
Labels: release goal, integration review

#23555 slack: Skip reactions for deleted users.
  zerver/data_import/slack.py
Labels: bug, area: export/import, size: XS

#23569 stream_create: Fix “susbscribing” typo
  static/js/stream_create.js
Labels: size: XS

#23534 message_flags: Avoid relying on redundant messages list in response
  static/js/message_flags.js
Labels: size: S, integration review

#23566 timeout: Correct thread id type passed to PyThreadState_SetAsyncExc.
  zerver/lib/timeout.py
Labels: size: XS

#22882 grafana: Support notifications from Grafana Alerting.
  zerver/webhooks/grafana/fixtures/alert_new.json
  zerver/webhooks/grafana/fixtures/alert_new_multiple.json
  zerver/webhooks/grafana/tests.py
  zerver/webhooks/grafana/view.py
Labels: size: XL

#23571 corporate: Remove Senior Full Stack Engineer opening from /jobs page.
  templates/corporate/jobs.html
Labels: size: L, integration review

#23567 [5.x] Remove RabbitMQ from Docker CI images
  .github/workflows/production-suite.yml
  tools/ci/Dockerfile
  tools/ci/Dockerfile.prod
  tools/ci/production-upgrade
Labels: size: M

#23576 invites: Add defensive assert in do_get_invites_controlled_by_user.
  zerver/actions/invites.py
Labels: size: XS

#23564 [5.x] tornado: Fix Tornado CSRF check with X-Forwarded-Proto.
  puppet/zulip/files/nginx/zulip-include-common/proxy
  zerver/management/commands/runtornado.py
Labels: size: XS

#23572 help center: Document "Mark messages as unread" on mobile.
  templates/zerver/help/marking-messages-as-unread.md
Labels: area: documentation (user), size: S, release goal, integration review

#23582 dark_theme: Re-render realm-logo on prefers-color-scheme changes.
  static/js/realm_logo.js
  static/js/ui_init.js
Labels: bug, area: settings (admin/org), size: S

#23574 Slack import: Cache emoji.json in static/generated/emoji.
  tools/setup/emoji/build_emoji
  zerver/data_import/slack.py
Labels: size: S

#23121 circleci: Rewrite integration to support the new webhook format.
  static/images/integrations/circleci/001.png
  static/images/integrations/circleci/002.png
  zerver/webhooks/circleci/doc.md
  zerver/webhooks/circleci/fixtures/bitbucket_job_completed.json
  zerver/webhooks/circleci/fixtures/bitbucket_manual_workflow_completed.json
  zerver/webhooks/circleci/fixtures/bitbucket_private_repo_pull_request_failure.json
  zerver/webhooks/circleci/fixtures/bitbucket_workflow_completed.json
  zerver/webhooks/circleci/fixtures/github_bionic_backend_frontend_failure.json
  zerver/webhooks/circleci/fixtures/github_bionic_production_build_success_multiple_parties.json
  zerver/webhooks/circleci/fixtures/github_bionic_production_install_cancelled.json
  zerver/webhooks/circleci/fixtures/github_job_completed.json
  zerver/webhooks/circleci/fixtures/github_tag_workflow_completed.json
  zerver/webhooks/circleci/fixtures/github_workflow_completed.json
  zerver/webhooks/circleci/fixtures/gitlab_job_completed.json
  zerver/webhooks/circleci/fixtures/gitlab_workflow_completed.json
  zerver/webhooks/circleci/fixtures/super_minimal_payload.json
  zerver/webhooks/circleci/tests.py
  zerver/webhooks/circleci/view.py
Labels: size: XL, integration review

#23544 message_edit: Handle truncated topic resolution.
  zerver/actions/message_edit.py
  zerver/tests/test_message_edit.py
Labels: bug, area: message-editing, size: XL, difficult

#23587 compatiblity: Delete obsolete compatibility code.
  zerver/tests/test_queue_worker.py
  zerver/worker/queue_processors.py
Labels: size: L

#23029 tornado: Support sharding by user ID
  puppet/zulip/files/nginx/zulip-include-frontend/app
  puppet/zulip/manifests/tornado_sharding.pp
  puppet/zulip/templates/nginx/tornado-upstreams.conf.template.erb
  scripts/lib/sharding.py
  scripts/lib/zulip_tools.py
  zerver/management/commands/runtornado.py
  zerver/tornado/descriptors.py
  zerver/tornado/django_api.py
  zerver/tornado/event_queue.py
  zerver/tornado/sharding.py
  zerver/tornado/views.py
Labels: size: XL

#22811 keydown_util: Add is_enter_event check for IME edge cases.
  static/third/bootstrap-typeahead/typeahead.js
Labels: bug, area: compose, priority: high, size: M, release goal

#23581 slack: Merge same-base emoji reactions, and deduplicate resulting userlists
  zerver/data_import/slack.py
Labels: area: emoji, area: export/import, size: S, release goal

#23592 left_sidebar: Fix extra space between stream header and PM header.
  static/styles/left_sidebar.css
Labels: bug, size: XS, release goal, integration review

#23594 Release step updates
  docs/subsystems/release-checklist.md
Labels: size: M

#23597 mailmap: Add entry for rht.
  .mailmap
Labels: size: XS

#23602 compose_ui: Revert changes for replace_syntax done in 1ca4566eb2.
  frontend_tests/node_tests/compose_ui.js
  static/js/compose_ui.js
Labels: size: XL

#23603 recent-conversations: Update logic for processing messages.
  static/js/recent_topics_data.js
  static/js/recent_topics_ui.js
Labels: size: S

#23596 recent: Remove participant avatars from PM rows.
  static/js/recent_topics_ui.js
  static/templates/recent_topic_row.hbs
Labels: bug, size: S, area: recent-conversations, release goal

#23593 narrow: Show empty narrow when all stream topics muted.
  static/js/message_fetch.js
Labels: size: S

#23605 Mark all as read final bug fixes
  static/js/unread_ops.js
Labels: size: M

#23607 Release Zulip Server 6.0.
  docs/overview/changelog.md
  templates/zerver/api/changelog.md
  version.py
Labels: size: L

#23611 Update version following 6.0 release.
  docs/overview/changelog.md
  templates/zerver/api/changelog.md
  version.py
Labels: size: M

#23612 Minor custom_check cleanup
  tools/linter_lib/custom_check.py
Labels: size: S

#23619 Improve AWS bucket documentation
  docs/production/upload-backends.md
Labels: area: documentation (production), size: L, backport candidate

#23622 oneclick: Wait in a loop until the image build droplet gets an IP.
  tools/oneclickapps/prepare_digital_ocean_one_click_app_release.py
Labels: size: S

#23613 recent: Don't modify `row_focus` if table is not focused.
  static/js/recent_topics_ui.js
Labels: size: S

#23617 recent-conversations: Check for data change when processing message.
  static/js/recent_topics_data.js
  static/js/recent_topics_ui.js
Labels: size: M, backport candidate

#23633 user_groups: Remove unused remove_user_from_user_group.
  zerver/lib/user_groups.py
  zerver/tests/test_event_queue.py
Labels: size: S

#23646 narrow-banner: Fix empty narrow banner titles with user's full name.
  frontend_tests/node_tests/narrow.js
  static/js/narrow_banner.js
Labels: size: S, backport candidate

#23599 updated location of `provision` script in setup-advanced.md
  docs/development/setup-advanced.md
Labels: size: S

#23485 removed-word-to-alert-confirmation
  frontend_tests/node_tests/alert_words_ui.js
  frontend_tests/puppeteer_tests/settings.ts
  static/js/alert_words_ui.js
  static/templates/settings/alert_word_settings.hbs
Labels: size: S, integration review

#23540 left_sidebar: Fix section divider not shown when all streams are muted.
  static/js/stream_list.js
Labels: bug, area: left-sidebar, priority: high, size: S, backport candidate, integration review

#23384 Issue solved: Hide "Deactivated users" from collapsed settings sidebar.
  static/templates/settings_overlay.hbs
Labels: size: XS, integration review

#23640 people: Verify `utcToZonedTime` returns a `Date` before formatting it.
  frontend_tests/node_tests/people.js
  static/js/people.js
Labels: size: M, backport candidate

#23650 message-fetch: Update empty narrow check to include opts message list.
  static/js/message_fetch.js
Labels: size: S

#23663 help center: Document @everyone and @stream mentions.
  templates/zerver/help/mention-a-user-or-group.md
Labels: integration review

#23662 contributor docs: Add links to more info about GSoC with Zulip.
  docs/outreach/overview.md
Labels: size: S, integration review

#23660 portico: Add Zulip Server 6.0 release to /history.
  templates/corporate/history.md
Labels: size: XS, integration review

#23659 people: Fix misleading comments and tests for utcToZonedTime
  frontend_tests/node_tests/people.js
  static/js/people.js
Labels: size: S, backport candidate, integration review

#23675 settings: Fix custom input for user email-notification-batching setting.
  static/js/settings_org.js
Labels: size: S

#23661 help center: Document message actions.
  static/images/help/message-actions.png
  templates/zerver/help/include/sidebar_index.md
  templates/zerver/help/message-actions.md
  templates/zerver/help/user-cards.md
Labels: size: S, integration review

#23683 docs: Fix link to "Custom profile fields".
  docs/production/authentication-methods.md
Labels: size: XS, integration review

#23689 ci: Test upgrades from Zulip Server 6.0.
  .github/workflows/production-suite.yml
Labels: size: XS

#23643 help center: Update "Message a stream by email" to reflect new UI.
  templates/zerver/help/message-a-stream-by-email.md
Labels: area: documentation (user), priority: high, size: M, integration review

#23669 migrations: Fix Python-looped SQL in 0376; don’t crash if no user found.
  zerver/migrations/0376_set_realmemoji_author_and_reupload_realmemoji.py
Labels: size: S, backport candidate, integration review

#23688 left_sidebar: Add border radius to selected stream list items.
  static/styles/left_sidebar.css
Labels: size: XS, integration review

#23697 integrations-docs: Remove images of bot type dropdown menus.
  static/images/integrations/bot_types_generic.png
  static/images/integrations/bot_types_incoming_webhook.png
  templates/zerver/help/include/create-a-generic-bot.md
  templates/zerver/help/include/create-an-incoming-webhook.md
Labels: size: S

#23682 streams: Pass max-length parameters to stream info modal.
  static/js/stream_edit.js
Labels: size: XS, integration review

#23698 integrations-docs: Update text in `create-bot-construct-url.md`.
  templates/zerver/help/include/create-bot-construct-url.md
Labels: size: S, integration review

#23704 emoji: Remove commas from emoji names.
  tools/setup/emoji/emoji_names.py
  tools/setup/emoji/generate_emoji_names
Labels: size: L, integration review

#23703 Fix a couple small bugs with slack_incoming webhooks
  zerver/webhooks/slack_incoming/fixtures/attachment_fields.json
  zerver/webhooks/slack_incoming/tests.py
  zerver/webhooks/slack_incoming/view.py
Labels: size: M

#23676 left_sidebar: Add login link to left sidebar for logged-out users.
  static/styles/left_sidebar.css
  static/templates/left_sidebar.hbs
Labels: area: left-sidebar, priority: high, size: S, area: public access, integration review

#23621 cache: Decline to store querysets, with an error.
  zerver/lib/cache.py
Labels: size: S

#23708 grafana: Upgrade to 9.3.0.
  puppet/zulip/manifests/common.pp
Labels: size: S
