Repository zulip/zulip, pull requests merged in 2022-04, with the labels that each got.

#21644 Stop server after puppet, and before migrations.
  scripts/lib/upgrade-zulip-stage-2
Labels: size: S, backport candidate

#21572 settings (user): Replace "Delete bot" with "Deactivate bot".
  static/js/settings_bots.js
  static/templates/settings/bot_avatar_row.hbs
Labels: size: S

#21647 migrations: Repeat part of migration 0376.
  tools/semgrep.yml
  zerver/migrations/0387_reupload_realmemoji_again.py
Labels: bug, area: emoji, size: M, backport candidate

#21656 check-database-compatibility: Ignore squashed and renamed migrations.
  scripts/lib/check-database-compatibility.py
Labels: size: M

#21658 migrations: Remove the possibly-duplicated emoji re-uploading.
  tools/semgrep.yml
  zerver/migrations/0376_set_realmemoji_author_and_reupload_realmemoji.py
  zerver/migrations/0387_reupload_realmemoji_again.py
Labels: size: M

#21675 message_send: Move `sender` parameter to REQ.
  zerver/tests/test_mirror_users.py
  zerver/views/message_send.py
Labels: size: L

#21660 message_edit: Fix false sub/unsub bookend on using a `near` link.
  zerver/tests/test_message_edit.py
  zerver/views/message_edit.py
Labels: size: XS

#21664 settings(admin/org) : Fix URL maximum input characters
  static/js/settings_account.js
  static/templates/settings/custom_user_profile_field.hbs
Labels: bug, area: settings (admin/org), size: XS

#21650 Add Finnish translation guidelines to documentation as new
  docs/translating/finnish.md
  docs/translating/index.md
  docs/translating/translating.md
Labels: size: XL

#21615 api_docs: Add roles and permissions page to API documentation.
  templates/zerver/api/roles-and-permissions.md
  templates/zerver/api/sidebar_index.md
  zerver/openapi/zulip.yaml
Labels: size: XL

#21620 shared: Add flow types for emoji typeahead funcs.
  static/shared/js/typeahead.js.flow
Labels: size: S

#21697 apps: Link to release page for Android, rather than directly to APK.
  static/js/portico/landing-page.js
Labels: area: portico, area: mobile, size: XS

#21698 Collations order in upgrades
  docs/production/upgrade-or-modify.md
Labels: size: M

#21701 check-database-compatibility: Sort and prettify output.
  scripts/lib/check-database-compatibility.py
Labels: size: XS

#21679 shared: Match literal emoji in typeahead.
  frontend_tests/node_tests/typeahead.js
  static/shared/js/typeahead.js
Labels: size: S

#21672 overlays: Add `is_modal_open` check along with `is_active` check.
  frontend_tests/node_tests/hotkey.js
  static/js/hotkey.js
  static/js/message_viewport.js
  static/js/overlays.js
  static/js/recent_topics_util.js
  static/js/stream_muting.js
  static/js/ui_init.js
Labels: size: S

#21704 api_docs: Clean uses of shared emoji schemas in OpenAPI.
  zerver/openapi/zulip.yaml
Labels: size: M

#21708 fixed expand/close compose box buttons too low when PM addresses text…
  static/styles/compose.css
Labels: size: XS

#21715 portico: Update /features.
  templates/zerver/features.html
Labels: size: XL

#21723 shared: Do not throw exception in parse unicode.
  frontend_tests/node_tests/typeahead.js
  static/shared/js/typeahead.js
Labels: size: S

#21706 middleware: Add `client` REQ parameter to `parse_client`.
  zerver/middleware.py
  zerver/tests/test_decorators.py
Labels: size: L

#21737 shared: Bump version to 0.0.13.
  static/shared/package.json
Labels: size: XS

#21736 puppet: Remove memcached SASL workaround.
  puppet/zulip/manifests/profile/memcached.pp
Labels: size: S

#21710 bug: time-zone picker corrected
  static/js/flatpickr.js
Labels: size: XS

#21661 ci: Test upgrades from 3.x, 4.x and 5.x.
  .github/workflows/production-suite.yml
  tools/ci/build-docker-images
Labels: size: XS

#21255 docs: Rewrite code review documentation.
  .github/pull_request_template.md
Labels: size: M

#21772 help_docs: Add 'About Zulip' to relative help links.
  zerver/lib/markdown/help_relative_links.py
Labels: size: XS

#21775 send_email: Only warn if EMAIL_HOST_PASSWORD is unset, not "".
  zerver/lib/send_email.py
  zerver/tests/test_send_email.py
Labels: size: S

#21774 puppet: Upgrade Grafana to 8.4.6.
  puppet/zulip/manifests/common.pp
Labels: size: S

#21762 docs: Update broken link in gsoc.md.
  docs/contributing/gsoc.md
Labels: size: XS

#21764 docs: Add "View Zulip version" help center page.
  templates/zerver/help/desktop-app-install-guide.md
  templates/zerver/help/include/sidebar_index.md
  templates/zerver/help/view-zulip-version.md
Labels: size: L

#21793 docs: Fix incorrect path to SAML certs in SAML Keycloak instructions.
  docs/production/authentication-methods.md
Labels: size: XS

#21792 scim: Temporarily stop running SCIM change operations atomically.
  zerver/lib/scim.py
Labels: size: M

#21790 docs: Link to chat.zulip.org from /help/web-public streams.
  templates/zerver/help/include/web-public-streams-intro.md
Labels: size: XS

#21718 compose: Fix wildcard mentions typeahead in PMs.
  frontend_tests/node_tests/composebox_typeahead.js
  static/js/composebox_typeahead.js
Labels: bug, area: compose, size: M

#21765 Revert "shared: Match literal emoji in typeahead."
  frontend_tests/node_tests/typeahead.js
  static/shared/js/typeahead.js
Labels: size: M

#21777 Stats: Improve consistency of Zulip app names
  analytics/tests/test_stats_views.py
  analytics/views/stats.py
Labels: size: S

#21740 invite: Bookkeep UserProfile with PreregistrationUser
  zerver/lib/actions.py
  zerver/migrations/0388_preregistrationuser_created_user.py
  zerver/models.py
  zerver/tests/test_signup.py
Labels: area: authentication, area: invitations, size: XL

#21822 Skip digest emails to deactivated users
  zerver/lib/digest.py
  zerver/tests/test_digest.py
Labels: size: M

#21830 models: Reserve a RealmAuditLog.USER_DELETED_PRESERVING_MESSAGES number.
  zerver/models.py
Labels: size: XS

#21831 tests: Add test coverage for email_notifications.py
  zerver/tests/test_email_notifications.py
Labels: size: S

#21728 streams: Fix behvior of announce-stream checkbox in stream creation form.
  static/js/stream_create.js
Labels: question, area: stream settings, size: M

#21808 sync_ldap_user_data: Show a proper error if no relevant users exist.
  zerver/management/commands/sync_ldap_user_data.py
Labels: size: S

#21684 help_docs: Update link in `restrict-private-messages`.
  templates/zerver/help/restrict-private-messages.md
Labels: size: S

#21824 configure-rabbitmq: Remove use of sudo
  docs/production/export-and-import.md
  scripts/setup/configure-rabbitmq
  tools/lib/provision_inner.py
  tools/linter_lib/custom_check.py
Labels: size: M

#21802 popovers: Disable "Confirm" button in Move topic menu when origin and destination are the same.
  static/js/stream_popover.js
Labels: size: M

#21836 update_message: Use `rendering_only` flag for notifications logic.
  zerver/tornado/event_queue.py
Labels: bug, area: api, priority: high, size: L

#21866 settings_bots: Fix incorrect title of "Edit bot" button.
  static/templates/settings/admin_user_list.hbs
Labels: size: XS

#21877 puppet: Upgrade external dependencies.
  puppet/zulip/manifests/common.pp
Labels: size: S

#21797 recent_topics: Disable filter buttons for spectator.
  frontend_tests/node_tests/recent_topics.js
  static/js/click_handlers.js
  static/js/recent_topics_ui.js
  static/styles/recent_topics.css
  static/templates/recent_topics_filters.hbs
Labels: priority: high, size: M, area: recent-topics, area: web-public streams

#21678 populate_db: Add support for creating messages older than 5 days ago.
  zerver/tests/test_populate_db.py
  zilencer/management/commands/populate_db.py
Labels: area: provision, size: M

#21434 message_feed_ui: Remove mute/unmute from message actions menu.
  static/js/popovers.js
  static/templates/actions_popover_content.hbs
Labels: priority: high, size: M, area: message feed UI

#21703 subscriptions: Fix web-public icon vertical alignment.
  static/styles/subscriptions.css
Labels: size: S

#21144 recent_topics: Hover effect on recent topics table.
  static/styles/dark_theme.css
  static/styles/recent_topics.css
Labels: size: S

#20703 compose: Improve icon for closing compose box (Fixes #20403)
  static/styles/compose.css
  static/templates/compose.hbs
Labels: area: compose, size: S

#21918 Updated reording of user / cross-realm bot properties in OpenAPI.
  zerver/openapi/zulip.yaml
Labels: size: XL

#21919 puppet: Only include "app_service" section if there are apps.
  puppet/zulip_ops/files/teleport_app.yaml
  puppet/zulip_ops/files/teleport_node.yaml
  puppet/zulip_ops/manifests/teleport/application.pp
  puppet/zulip_ops/manifests/teleport/application_top.pp
Labels: size: S

#21915 shared: Check variable in release scripts, avoiding shellcheck disable
  static/shared/tools/npm-postversion
  static/shared/tools/npm-version
Labels: size: S

#21659 ci: Only run documentation/link tests on a single job.
  .github/workflows/zulip-ci.yml
  docs/testing/continuous-integration.md
Labels: size: S

#21259 Upgrade docker-postgresql to v14
  Dockerfile-postgresql
Labels: size: S

#21924 test-backend: Respect --parallel=N when running specific tests
  tools/test-backend
Labels: size: S

#21847 node_tests: Mock classes with classes
  frontend_tests/node_tests/compose.js
  frontend_tests/node_tests/compose_video.js
  frontend_tests/node_tests/copy_and_paste.js
  frontend_tests/node_tests/list_widget.js
  frontend_tests/node_tests/narrow_activate.js
  frontend_tests/node_tests/popovers.js
  frontend_tests/node_tests/settings_org.js
Labels: size: XL

#21934 puppet: Check that certbot certs are in use before fixing them.
  puppet/zulip/manifests/profile/app_frontend.pp
Labels: size: S, backport candidate

#21578 avatar: Add rate limit similar to attachments on medium avatars.
  zerver/tests/test_upload.py
  zerver/views/users.py
Labels: size: S

#21937 openapi: Mention that `profile_data` will be missing for bots.
  zerver/openapi/zulip.yaml
Labels: size: XS

#21938 Correctly hyphenate “web-public” and “non-”
  frontend_tests/node_tests/message_flags.js
  frontend_tests/node_tests/narrow.js
  frontend_tests/node_tests/recent_topics.js
  zerver/lib/markdown/__init__.py
  zerver/tests/test_message_edit.py
  zerver/tests/test_message_fetch.py
  zerver/tests/test_subs.py
  zerver/tests/test_thumbnail.py
  zerver/tests/test_upload.py
  zerver/tests/test_widgets.py
  zerver/views/message_fetch.py
  zerver/webhooks/opencollective/view.py
Labels: size: M

#21942 web_public_view: Redirect to current narrow after login.
  static/js/click_handlers.js
  static/js/hash_util.js
  static/js/spectators.js
  static/templates/right_sidebar.hbs
  tools/test-js-with-node
Labels: size: M

#21943 workers: Log the exception if the export fails.
  zerver/tests/test_events.py
  zerver/worker/queue_processors.py
Labels: size: S

#21945 Fix quotes in prod_settings_template
  zproject/prod_settings_template.py
Labels: size: L

#21912 compose: Fix sorting of wildcard mentions in case of PMs.
  frontend_tests/node_tests/composebox_typeahead.js
  frontend_tests/node_tests/typeahead_helper.js
  static/js/typeahead_helper.js
Labels: bug, area: compose, size: L

#21908 slack_incoming: Process request payload directly in view.py
  zerver/webhooks/slack_incoming/tests.py
  zerver/webhooks/slack_incoming/view.py
Labels: size: M

#21951 import: Default the S3 metadata user of emoji to the first owner.
  zerver/lib/import_realm.py
Labels: size: M

#21955 openapi: Fix reference link in `/register-queue` documentation.
  zerver/openapi/zulip.yaml
Labels: size: XS

#21956 ci: Remove actions/cache@v2 steps.
  .github/workflows/production-suite.yml
  .github/workflows/zulip-ci.yml
Labels: size: L

#21964 Revert "ci: Remove actions/cache@v2 steps from run due to failures."
  .github/workflows/production-suite.yml
  .github/workflows/zulip-ci.yml
Labels: size: L

#21966 build-pgroonga: Update PGroonga to 2.3.6
  scripts/lib/build-pgroonga
  tools/lib/provision.py
Labels: size: S

#21967 puppet: Remove quotes for enumerable values
  puppet/zulip/manifests/apache_sso.pp
  puppet/zulip/manifests/app_frontend_base.pp
  puppet/zulip/manifests/camo.pp
  puppet/zulip/manifests/nginx.pp
  puppet/zulip/manifests/postfix_localmail.pp
  puppet/zulip/manifests/postgresql_base.pp
  puppet/zulip/manifests/postgresql_common.pp
  puppet/zulip/manifests/process_fts_updates.pp
  puppet/zulip/manifests/profile/app_frontend.pp
  puppet/zulip/manifests/profile/base.pp
  puppet/zulip/manifests/profile/memcached.pp
  puppet/zulip/manifests/profile/rabbitmq.pp
  puppet/zulip/manifests/profile/redis.pp
  puppet/zulip/manifests/sasl_modules.pp
  puppet/zulip/manifests/snakeoil.pp
  puppet/zulip/manifests/static_asset_compiler.pp
  puppet/zulip/manifests/supervisor.pp
  puppet/zulip/manifests/tornado_sharding.pp
  puppet/zulip/manifests/wal_g.pp
  puppet/zulip_ops/manifests/apache.pp
  puppet/zulip_ops/manifests/app_frontend.pp
  puppet/zulip_ops/manifests/ksplice_uptrack.pp
  puppet/zulip_ops/manifests/munin_node.pp
  puppet/zulip_ops/manifests/munin_plugin.pp
  puppet/zulip_ops/manifests/profile/base.pp
  puppet/zulip_ops/manifests/profile/munin_server.pp
  puppet/zulip_ops/manifests/profile/nagios.pp
  puppet/zulip_ops/manifests/profile/postgresql.pp
  puppet/zulip_ops/manifests/profile/prod_app_frontend.pp
  puppet/zulip_ops/manifests/profile/prometheus_server.pp
  puppet/zulip_ops/manifests/profile/staging_app_frontend.pp
  puppet/zulip_ops/manifests/profile/zmirror.pp
  puppet/zulip_ops/manifests/profile/zmirror_personals.pp
Labels: size: XL
