Repository zulip/zulip, pull requests merged in 2022-05, with the labels that each got.

#21960 message_view_header: Add divider after stream name for spectator.
  static/styles/zulip.css
  static/templates/message_view_header.hbs
Labels: size: S

#21982 puppet: Fix non-replicated PostgreSQL 10 and 11 configuration.
  puppet/zulip/templates/postgresql/10/postgresql.conf.centos.template.erb
  puppet/zulip/templates/postgresql/10/postgresql.conf.template.erb
  puppet/zulip/templates/postgresql/11/postgresql.conf.template.erb
Labels: area: production, size: S, backport candidate

#21985 Remove zulip-ec2-configure-interfaces
  docs/THIRDPARTY
  puppet/zulip_ops/files/zulip-ec2-configure-interfaces
  puppet/zulip_ops/files/zulip-ec2-configure-interfaces_if-up.d.sh
  puppet/zulip_ops/manifests/profile/base.pp
  pyproject.toml
Labels: size: XL

#21972 testing: Support concurrent backend testing for generate_emails.
  zerver/tests/test_email_log.py
  zerver/tests/test_example.py
  zproject/email_backends.py
Labels: size: M

#21986 resize: Don't use `visible` selector to find element states.
  static/js/resize.js
Labels: size: S

#21990 tools/lib/provision.py: Add missing ENDC to avoid colouring all output
  tools/lib/provision.py
Labels: size: XS

#21994 puppet: Add a redis exporter.
  puppet/zulip/manifests/common.pp
  puppet/zulip_ops/manifests/profile/chat_zulip_org.pp
  puppet/zulip_ops/manifests/profile/redis.pp
  puppet/zulip_ops/manifests/prometheus/redis.pp
  puppet/zulip_ops/templates/supervisor/conf.d/prometheus_redis_exporter.conf.template.erb
Labels: size: M

#22000 ci: Update upgrade test to 5.2, from 5.1.
  .github/workflows/production-suite.yml
  tools/ci/build-docker-images
Labels: size: S

#21571 stream_settings: Replace non-standard tooltip for "Announce stream" hint.
  static/js/stream_create.js
  static/templates/stream_settings/stream_types.hbs
Labels: area: stream settings, size: M

#21605 Improve error message regarding use of data-tippy-allowHTML attribute.
  tools/linter_lib/custom_check.py
Labels: size: XS

#21689 user_groups: Convert inline form to modal.
  frontend_tests/node_tests/settings_user_groups.js
  static/js/settings_user_groups.js
  static/styles/settings.css
  static/templates/settings/add_user_group_modal.hbs
  static/templates/settings/user_groups_admin.hbs
  templates/zerver/help/include/how-to-create-a-user-group.md
  tools/test-js-with-node
Labels: size: XL

#22005 help-center: Reword self-host warning to enable web-public streams.
  templates/zerver/help/public-access-option.md
Labels: size: S

#22004 api-docs: Fix formatting and spacing errors in api changelog.
  templates/zerver/api/changelog.md
Labels: size: S

#21895 popovers: Do not show "Send private message" option when user does not have PM permissions.
  frontend_tests/node_tests/popovers.js
  static/js/popovers.js
  static/templates/user_info_popover_content.hbs
Labels: bug, area: settings (admin/org), size: S, area: popovers, integration review

#22007 portico: Add Recurse Center case study.
  templates/zerver/footer.html
  templates/zerver/for-communities.html
  templates/zerver/for-education.html
  templates/zerver/for-events.html
  templates/zerver/for-open-source.html
  templates/zerver/for/communities.md
  templates/zerver/for/recurse-center-case-study.md
  templates/zerver/for/use-cases.md
  templates/zerver/landing_nav.html
  templates/zerver/recurse-center-case-study.html
  zerver/tests/test_docs.py
  zproject/urls.py
Labels: size: XL

#20063 search: Fix x icon overlap in search and filter inputs
  static/styles/app_components.css
  static/styles/left_sidebar.css
  static/styles/popovers.css
  static/styles/recent_topics.css
  static/styles/right_sidebar.css
  static/styles/subscriptions.css
  static/styles/zulip.css
Labels: bug, area: search, size: L

#21809 popovers: New function for hiding all user info popovers.
  static/js/popovers.js
Labels: size: S

#22013 open-api [nfc]: Fix inconsistencies in OpenAPI error documentation.
  zerver/openapi/zulip.yaml
Labels: size: S

#22010 portico: Fix quotation marks in Recurse Center case study.
  templates/zerver/for/recurse-center-case-study.md
Labels: size: S

#22008 More options and bugfixes for scripts/log-search
  scripts/log-search
Labels: size: XL

#22018 requirements: Require boto3-stubs packages only in development
  requirements/common.in
  requirements/dev.txt
  requirements/mypy.in
  requirements/mypy.txt
  requirements/prod.txt
Labels: size: L

#22029 docs: Clarify nginx extension points.
  docs/production/upgrade-or-modify.md
Labels: size: S

#22028 docs: Document the ./scripts/log-search tool.
  docs/production/troubleshooting.md
  docs/subsystems/logging.md
Labels: size: L

#22040 middleware: Fix URL encoding of next parameter
  zerver/middleware.py
  zerver/tests/test_decorators.py
  zerver/tests/test_docs.py
  zerver/views/portico.py
Labels: size: S

#22037 freshdesk: Remove unsafe TicketDict class
  zerver/webhooks/freshdesk/view.py
Labels: size: L

#22042 streams: Mark messages as read only for unsubscribed streams.
  zerver/actions/streams.py
  zerver/tests/test_subs.py
Labels: size: S

#22043 puppet: Each worker should chdir after forking.
  puppet/zulip/templates/uwsgi.ini.template.erb
Labels: size: XS

#22047 message_flags: Short-circuit if no messages changed.
  zerver/actions/message_flags.py
  zerver/tests/test_events.py
  zerver/tests/test_subs.py
Labels: size: M

#22048 email_mirror: Handle invalid `charset="..."` values.
  zerver/lib/email_mirror.py
  zerver/tests/test_email_mirror.py
Labels: size: M

#22065 Revert "settings: Add web-public streams beta subdomain list."
  zerver/lib/events.py
  zerver/models.py
  zerver/tests/test_realm.py
  zproject/default_settings.py
Labels: size: S

#22049 puppet: Remove typo'd cron job.
  puppet/zulip/manifests/app_frontend_base.pp
  zerver/decorator.py
Labels: size: S

#22064 help docs: Fix a wrong link in create-a-stream doc
  templates/zerver/help/create-a-stream.md
Labels: size: XS

#22044 oneclick: Do not use a stale Zulip client, fail if fab fails
  tools/oneclickapps/prepare_digital_ocean_one_click_app_release.py
Labels: size: S

#22061 testing: 100% test coverage for zerver/lib/outgoing_webhook.py
  tools/test-backend
  zerver/tests/test_outgoing_webhook_system.py
Labels: size: L

#22079 name_restrictions: Add your-org.zulipchat.com as a reserved name.
  zerver/lib/name_restrictions.py
Labels: size: XS

#22030 puppet: Include the OS-enabled nginx module configurations.
  puppet/zulip/templates/nginx.conf.template.erb
Labels: size: XS

#22035 puppet: Only fix certbot certificates if https is enabled.
  puppet/zulip/manifests/profile/app_frontend.pp
Labels: size: S

#22055 Revert "apt-repos: Downgrade PostgreSQL to dodge PGroonga regression."
  scripts/lib/install
  scripts/lib/upgrade-zulip-stage-2
  scripts/setup/apt-repos/zulip/bullseye.list
  scripts/setup/apt-repos/zulip/focal.list
  scripts/setup/apt-repos/zulip/zulip.pref
Labels: size: M

#22050 streams: Save one DB query in bulk_remove_susbcriptions.
  zerver/actions/streams.py
  zerver/tests/test_subs.py
Labels: size: M

#22090 ci: Stop rabbitmq when making CI images.
  tools/ci/Dockerfile.prod
Labels: size: XS

#22089 api-docs: Add `create_web_public_stream_policy` to realm update.
  templates/zerver/api/changelog.md
  zerver/openapi/zulip.yaml
Labels: size: S

#22095 requirements: Remove importlib-resources
  requirements/common.in
  requirements/dev.txt
  requirements/prod.txt
Labels: size: S

#22093 Upgrade grafana, smokescreen, wal-g deps
  puppet/zulip/manifests/common.pp
Labels: size: S

#22086 Add a new endpoint to get a stream by id.
  templates/zerver/api/changelog.md
  templates/zerver/help/include/rest-endpoints.md
  version.py
  zerver/openapi/zulip.yaml
  zerver/tests/test_decorators.py
  zerver/tests/test_subs.py
  zerver/views/streams.py
  zproject/urls.py
Labels: area: stream settings, area: api, size: XL

#22098 api-docs: Add changelog for `stream_id` param to `mute-topic`.
  templates/zerver/api/changelog.md
  zerver/openapi/zulip.yaml
Labels: size: M

#22111 github: Accept null for issue and pull request body
  zerver/webhooks/github/view.py
Labels: size: S

#22101 api-docs: Update `/set-typing-status` endpoint documentation.
  zerver/openapi/zulip.yaml
Labels: size: M

#22116 apt-repos: Remove now-unneeded Ubuntu 21.10 repository on 22.04
  scripts/setup/apt-repos/zulip/jammy.list
Labels: area: provision, size: S, backport candidate

#22122 [5.x] apt-repos: Remove now-unneeded Ubuntu 21.10 repository on 22.04
  scripts/setup/apt-repos/zulip/jammy.list
Labels: size: S

#22103 openapi: Say custom_profile_field.value can be null in update-user event
  zerver/openapi/zulip.yaml
Labels: size: XS

#22130 help: Clarify potentially confusing wording.
  templates/zerver/help/restrict-permissions-of-new-members.md
Labels: size: XS

#22134 email: Attempt to suppress email auto-replies.
  zerver/lib/send_email.py
Labels: priority: high, area: emails, area: notifications (messages), size: S

#22133 response: Replace response.asynchronous attribute with new class
  zerver/lib/response.py
  zerver/middleware.py
  zerver/tornado/handlers.py
  zerver/tornado/views.py
Labels: size: M

#22128 recent_topics: Don't restore filters for spectators.
  static/js/recent_topics_ui.js
Labels: size: S

#22123 types: Better types for API fields
  zerver/actions/default_streams.py
  zerver/actions/streams.py
  zerver/lib/streams.py
  zerver/lib/types.py
  zerver/models.py
  zerver/tests/test_subs.py
Labels: size: XL

#22140 portico: Make minor updates to Senior Mobile Engineer job listing.
  templates/corporate/jobs.html
Labels: size: S

#22115 frontend: Update when communities directory checkbox is disabled.
  static/js/admin.js
  templates/zerver/help/communities-directory.md
Labels: size: M

#22152 typing: Access url via key "Location" instead of attribute "url".
  corporate/tests/test_stripe.py
  zerver/tests/test_auth_backends.py
  zerver/tests/test_create_video_call.py
  zerver/tests/test_home.py
  zerver/tests/test_signup.py
  zerver/tests/test_thumbnail.py
Labels: size: XL

#22126 typing: Apply trivial fixes to adjust edge cases in typing.
  tools/lib/provision_inner.py
  zerver/actions/realm_linkifiers.py
  zerver/actions/streams.py
  zerver/context_processors.py
  zerver/data_import/rocketchat.py
  zerver/lib/streams.py
  zerver/models.py
  zerver/tests/test_auth_backends.py
  zerver/tests/test_import_export.py
  zerver/tests/test_message_send.py
Labels: size: M
