Repository zulip/zulip, pull requests merged in 2022-06, with the labels that each got.

#22163 stream_create: Fix crash on stream creation error
  static/js/stream_create.js
Labels: area: stream settings, size: XS, backport candidate

#22167 puppet: Switch to checking time against the AWS timeserver.
  puppet/zulip_ops/files/nagios4/commands.cfg
Labels: size: XS

#22168 [5.x] stream_create: Fix crash on stream creation error
  static/js/stream_create.js
Labels: size: XS

#22173 Add a "Mastering the compose box" help center aricle
  templates/zerver/help/format-your-message-using-markdown.md
  templates/zerver/help/include/sidebar_index.md
  templates/zerver/help/mastering-the-compose-box.md
  templates/zerver/help/preview-your-message-before-sending.md
  templates/zerver/help/resize-the-compose-box.md
Labels: area: documentation (user), priority: high, size: M, release goal

#21980 help-docs: Add manage a user's stream subscriptions article.
  templates/zerver/help/add-or-remove-users-from-a-stream.md
  templates/zerver/help/include/right-sidebar-view-full-profile.md
  templates/zerver/help/include/sidebar_index.md
  templates/zerver/help/manage-user-stream-subscriptions.md
  templates/zerver/help/view-someones-profile.md
Labels: area: documentation (user), size: L, integration review

#22011 api-docs: Expand use of `SimpleSuccess` response schema.
  zerver/openapi/zulip.yaml
Labels: size: XL

#22084 api-docs: Add changelog entry for user/stream ID narrow options.
  templates/zerver/api/changelog.md
  zerver/openapi/zulip.yaml
Labels: area: compose, area: api, area: documentation (api and integrations), priority: high, size: S

#21989 help-docs: Extend notification bot documentation.
  templates/zerver/help/configure-notification-bot.md
Labels: size: L

#21981 help_docs: Document subscribing a user to stream via @-mention.
  templates/zerver/help/add-or-remove-users-from-a-stream.md
Labels: area: documentation (user), size: S, integration review

#22023 settings: Allow customizing HOME_NOT_LOGGED_IN.
  zproject/computed_settings.py
  zproject/default_settings.py
  zproject/dev_settings.py
Labels: size: S

#22046 upgrade-zulip-from-git: Stop mirroring the remote.
  scripts/lib/upgrade-zulip-from-git
Labels: area: production, priority: high, size: L, backport candidate

#22076 testing: 100% coverage for zerver/tests/test_digest.py.
  tools/test-backend
  zerver/tests/test_digest.py
Labels: size: M

#22017 docs: Correct and clarify wal-g backup documentation.
  docs/production/deployment.md
  docs/production/export-and-import.md
Labels: bug, area: production, area: uploads, size: S

#22114 help-docs: Update accessing private messages information.
  templates/zerver/help/private-messages.md
Labels: size: S

#22177 docs: Fix typo in gitlab callback url in dev setup instructions.
  docs/development/authentication.md
Labels: size: XS

#22056 populate_db: Add users to initial private stream in mit and lear realm.
  zilencer/management/commands/populate_db.py
Labels: size: S

#22181 gitlab: Fix event_name -> object_kind defaulting.
  zerver/webhooks/gitlab/fixtures/repository_update.json
  zerver/webhooks/gitlab/view.py
Labels: size: M

#22187 test_counts: Rename confusing assertCountEquals helper
  analytics/tests/test_counts.py
Labels: size: S

#22183 logging: Pass more format arguments to logging
  puppet/zulip/files/postgresql/process_fts_updates
  tools/check-templates
  tools/semgrep.yml
  zerver/management/commands/process_queue.py
  zerver/tornado/event_queue.py
  zerver/tornado/handlers.py
Labels: size: L

#22108 Update invite new users help center page
  templates/zerver/help/include/how-to-invite-users-to-join.md
  templates/zerver/help/invite-new-users.md
  templates/zerver/help/restrict-account-creation.md
Labels: size: M, integration review

#22191 emojisets: Use Google modern for emoji picker with text theme
  static/js/emojisets.js
Labels: area: emoji, size: XS

#22185 django-stubs: Fix HttpResponse missing attribute error.
  analytics/tests/test_stats_views.py
  corporate/tests/test_stripe.py
  zerver/tests/test_alert_words.py
  zerver/tests/test_attachments.py
  zerver/tests/test_auth_backends.py
  zerver/tests/test_bots.py
  zerver/tests/test_create_video_call.py
  zerver/tests/test_custom_profile_data.py
  zerver/tests/test_email_change.py
  zerver/tests/test_event_queue.py
  zerver/tests/test_event_system.py
  zerver/tests/test_events.py
  zerver/tests/test_markdown.py
  zerver/tests/test_message_edit.py
  zerver/tests/test_message_fetch.py
  zerver/tests/test_message_topics.py
  zerver/tests/test_muting_users.py
  zerver/tests/test_presence.py
  zerver/tests/test_push_notifications.py
  zerver/tests/test_reactions.py
  zerver/tests/test_realm_domains.py
  zerver/tests/test_realm_emoji.py
  zerver/tests/test_realm_export.py
  zerver/tests/test_realm_linkifiers.py
  zerver/tests/test_scim.py
  zerver/tests/test_service_bot_system.py
  zerver/tests/test_settings.py
  zerver/tests/test_signup.py
  zerver/tests/test_subs.py
  zerver/tests/test_upload.py
  zerver/tests/test_user_groups.py
  zerver/tests/test_users.py
  zerver/tests/test_zcommand.py
Labels: size: XL

#22200 cache: Remove needless monkey patching
  zerver/lib/cache.py
Labels: size: S

#22208 portico: Update Recurse Center link on /plans to point to case study.
  templates/zerver/faq.html
Labels: size: XS

#22211 docs: Update documentation of max number of thumbnails per message.
  templates/zerver/help/share-and-upload-files.md
Labels: size: XS

#22209 django-stubs: Replace `HttpResponse` with `_MonkeyPatchedWSGIResponse.`
  analytics/tests/test_support_views.py
  corporate/tests/test_stripe.py
  zerver/lib/test_classes.py
  zerver/lib/test_helpers.py
  zerver/tests/test_auth_backends.py
  zerver/tests/test_decorators.py
  zerver/tests/test_docs.py
  zerver/tests/test_email_mirror.py
  zerver/tests/test_external.py
  zerver/tests/test_home.py
  zerver/tests/test_i18n.py
  zerver/tests/test_message_edit.py
  zerver/tests/test_message_fetch.py
  zerver/tests/test_message_flags.py
  zerver/tests/test_message_send.py
  zerver/tests/test_reactions.py
  zerver/tests/test_scim.py
  zerver/tests/test_settings.py
  zerver/tests/test_signup.py
  zerver/tests/test_subs.py
  zerver/tests/test_widgets.py
  zerver/tests/test_zephyr.py
Labels: size: XL

#22186 app-loading: Add a 3s delay before showing the reload message.
  templates/zerver/app/index.html
Labels: area: misc, priority: high, size: S, integration review

#22224 Stop making a working copy in /srv/zulip.git, edge cases in de-mirror'ing
  scripts/lib/upgrade-zulip-from-git
Labels: size: S, backport candidate

#22275 nginx: Add Cache-Control headers for Django-hashed static files
  puppet/zulip/files/nginx/zulip-include-frontend/app
Labels: size: S

#22276 ci: Update upgrade test to 5.3, from 5.2.
  .github/workflows/production-suite.yml
  tools/ci/build-docker-images
Labels: size: S

#22293 portico: Remove Senior Infrastructure Engineer position from /jobs.
  templates/corporate/jobs.html
Labels: size: XL

#22288 wordpress: Fix nonsense tests
  zerver/webhooks/wordpress/tests.py
Labels: size: S

#22283 compilemessages: Use a consistent ordering for the languages list.
  zerver/management/commands/compilemessages.py
Labels: size: XS, backport candidate

#22295 help-docs: Update Homebrew instructions for the latest release on macOS.
  templates/zerver/help/desktop-app-install-guide.md
Labels: area: documentation (user), size: S

#22297 middleware: Pass unhandled API exceptions through to the test suite
  zerver/lib/test_classes.py
  zerver/middleware.py
  zerver/tests/test_integrations_dev_panel.py
  zerver/tests/test_logging_handlers.py
  zerver/webhooks/travis/tests.py
Labels: size: M

#22286 upload-release: Only copy full releases to zulip-server-latest.tar.gz.
  tools/upload-release
Labels: size: S

#22309 Make changelog entries consistent
  docs/overview/changelog.md
Labels: size: S

#22302 decorator: Only URL-decode application/x-www-form-urlencoded requests
  zerver/decorator.py
  zerver/lib/rest.py
  zerver/lib/test_classes.py
  zerver/views/development/email_log.py
Labels: size: S

#22305 test_push_notifications: Simplify with Python 3.8 AsyncMock
  zerver/tests/test_push_notifications.py
Labels: size: M

#22299 Add the ability to skip redirects for renamed realms
  zerver/actions/create_realm.py
  zerver/management/commands/change_realm_subdomain.py
  zerver/tests/test_signup.py
Labels: size: L

#22313 check-thirdparty: License under GPLv2+
  docs/THIRDPARTY
  tools/check-thirdparty
Labels: size: M, backport candidate

#22316 templates: Fix Python-Markdown extension type
  zerver/lib/templates.py
Labels: size: XS

#22317 python: Unquote some unnecessarily quoted type annotations
  scripts/lib/upgrade-zulip-stage-2
  tools/lib/provision.py
  zerver/lib/request.py
  zerver/lib/streams.py
  zerver/lib/topic.py
  zerver/lib/user_groups.py
  zerver/lib/users.py
  zerver/lib/validator.py
  zerver/views/message_fetch.py
Labels: size: L

#22320 python: Simplify unnecessary getattr calls
  tools/run-dev.py
  zerver/tests/test_decorators.py
  zerver/tests/test_logging_handlers.py
  zerver/tests/test_realm.py
Labels: size: S

#22321 run-dev: Remove unnecessary finish calls
  tools/run-dev.py
Labels: size: XS

#22322 tornado: Send request_started signal in Django thread
  zerver/tornado/handlers.py
Labels: size: S

#22326 integrations-docs: Add line break in GitLab integration doc.
  zerver/webhooks/gitlab/doc.md
Labels: size: XS

#22319 decorator: Type cache_info, cache_clear for ignore_unhashable_lru_cache
  zerver/lib/cache.py
  zerver/tests/test_decorators.py
Labels: size: XL

#22332 docs: Capitalize Handlebars consistently
  docs/overview/changelog.md
  docs/testing/linters.md
  docs/translating/internationalization.md
  frontend_tests/node_tests/example8.js
  frontend_tests/zjsunit/namespace.js
  static/js/message_edit.js
  static/js/notifications.js
  static/js/templates.js
  static/js/ui_init.js
  tools/check-frontend-i18n
  tools/linter_lib/custom_check.py
Labels: size: S

#22327 integrations-docs: Remove `zulip-config.md`.
  docs/documentation/integrations.md
  templates/zerver/help/include/zulip-config.md
Labels: size: S

#22331 integrations: Satisfy Python-Markdown’s archaic 4-space requirement
  templates/zerver/integrations/jenkins.md
  zerver/webhooks/beanstalk/doc.md
  zerver/webhooks/gitea/doc.md
  zerver/webhooks/github/doc.md
  zerver/webhooks/gogs/doc.md
Labels: area: documentation (api and integrations), size: S, backport candidate

#22335 markdown: Parse included blocks in a new parser state
  zerver/lib/markdown/include.py
Labels: area: documentation (api and integrations), size: XS, backport candidate

#22337 nginx: Remove legacy X-XSS-Protection header
  puppet/zulip/files/nginx/zulip-include-common/headers
  tools/ci/success-http-headers.template.txt
Labels: size: XS

#22329 docs: Document that loadbalancer.ips can be CIDR ranges.
  docs/production/deployment.md
Labels: size: S, backport candidate

#22250 stream: Change the color of remove button in subscribers tab.
  static/templates/stream_settings/new_stream_user.hbs
Labels: good first issue, area: stream settings, size: XS, integration review

#22340 test_classes: Check responses in ZulipTestCase.register
  zerver/lib/test_classes.py
Labels: size: S

#22303 docs: Update WIP PR convention to GitHub draft PRs
  CONTRIBUTING.md
  docs/git/overview.md
  docs/git/pull-requests.md
  templates/zerver/api/incoming-webhooks-walkthrough.md
  templates/zerver/development-community.md
Labels: area: documentation (developer), size: M

#22251 streams: Disable subscribers tab when user does not have permission to see subscribers.
  static/js/stream_settings_ui.js
  static/js/stream_ui_updates.js
Labels: bug, good first issue, area: stream settings, size: S, integration review

#22226 stream_settings: Modify the message of the "Announce stream" hint tooltip.
  static/templates/announce_stream_docs.hbs
Labels: size: XS, integration review

#22012 Change default option
  static/js/message_edit.js
Labels: size: XS, integration review

#22137 compose: Make compose box tooltips consitent.
  static/templates/compose.hbs
  static/templates/narrow_to_compose_recipients_tooltip.hbs
Labels: design, area: compose, priority: high, size: XS, integration review

#22149 added:keyboard shortcut to Drafts link tooltip
  static/templates/compose_control_buttons.hbs
Labels: size: XS, integration review

#21652 recent_topics: Link timestamp to latest message.
  frontend_tests/node_tests/recent_topics.js
  static/js/recent_topics_ui.js
  static/templates/recent_topic_row.hbs
Labels: priority: high, size: S, area: recent-topics, integration review

#22348 Fix a log-search bug, add a minor feature
  scripts/log-search
Labels: size: M

#22345 retention: Guarantee type-safeness when calling move_rows.
  zerver/lib/retention.py
Labels: size: XS

#22349 uwsgi: Increase request buffer size to 64k, from 8k default.
  docs/production/deployment.md
  puppet/zulip/manifests/app_frontend_base.pp
  puppet/zulip/templates/uwsgi.ini.template.erb
Labels: size: S

#22263 realms: refactor do_set_realm_stream().
  zerver/actions/realm_settings.py
Labels: size: L

#22356 docs: Specify which CPU architectures are supported.
  docs/production/requirements.md
Labels: area: documentation (production), size: XS, backport candidate

#22359 docs: Remove CSS padding rule for multi-paragraph ordered lists.
  static/styles/portico/markdown.css
Labels: size: S

#22358 zephyr: Write out unix timestamp in check, as check_cron_file expects.
  puppet/zulip_ops/files/nagios_plugins/zulip_zephyr_mirror/check_user_zephyr_mirror_liveness
Labels: size: XS

#22354 manage: Remove ineffective Python 2 check
  manage.py
Labels: size: S

#22300 help-docs: Document "Copy link to stream" mobile app feature.
  templates/zerver/help/include/stream-long-press-menu-tip.md
  templates/zerver/help/include/stream-long-press-menu.md
  templates/zerver/help/link-to-a-message-or-conversation.md
Labels: area: documentation (user), size: S, integration review

#22357 templates: Simplify nested Handlebars conditionals using {{else if}}
  frontend_tests/node_tests/composebox_typeahead.js
  static/templates/edited_notice.hbs
  static/templates/emoji_popover_emoji.hbs
  static/templates/message_reaction.hbs
  static/templates/recipient_row.hbs
  static/templates/set_status_overlay.hbs
  static/templates/settings/emoji_settings_tip.hbs
  static/templates/settings_overlay.hbs
  static/templates/status_emoji_selector.hbs
  static/templates/stream_settings/stream_settings_checkbox.hbs
  static/templates/typeahead_list_item.hbs
  static/templates/user_info_popover_content.hbs
  static/templates/user_profile_modal.hbs
Labels: size: XL

#22256 help-docs: Document "Resolve/Unresolve topic" mobile app feature.
  templates/zerver/help/include/topic-long-press-menu.md
  templates/zerver/help/resolve-a-topic.md
Labels: area: documentation (user), size: M, integration review
