Repository zulip/zulip, pull requests merged in 2023-11, with the labels that each got.

#27462 recent_view: Fix error when user has no messages.
  web/src/recent_view_ui.js
Labels: size: XS, integration review

#27461 message_fetch: opts.msg_list can be undefined.
  web/src/message_fetch.js
Labels: size: S, integration review

#27446 analytics: Use `activity_details_template.html` for installation activity page.
  analytics/views/installation_activity.py
  templates/analytics/activity.html
  templates/analytics/realm_summary_table.html
Labels: area: analytics, size: S

#27333 ts: Migrate ‘user_sort.js’ to TypeScript.
  tools/test-js-with-node
  web/src/people.ts
  web/src/user_sort.ts
Labels: size: S

#27472 analytics: Use `realm_str` to generate per realm URL.
  analytics/views/activity_common.py
Labels: size: S

#27470 integrations: Use stream ID for incoming webhook URL generated in modal.
  web/src/integration_url_modal.js
Labels: size: S

#27473 sentry: Circuit-break on 429s and 500s from Sentry.
  zerver/views/sentry.py
Labels: size: S

#27481 send_test_push_notification_api: Fixes to the API endpoint doc.
  zerver/openapi/zulip.yaml
Labels: size: S

#27468 hotkey: Add 'narrow to next unread followed topic' hotkey.
  help/include/reading-conversations.md
  help/keyboard-shortcuts.md
  web/src/hotkey.js
  web/src/narrow.js
  web/src/topic_generator.js
  web/templates/keyboard_shortcuts.hbs
  web/tests/hotkey.test.js
  web/tests/topic_generator.test.js
Labels: size: L, integration review

#27490 gitlab: Description can be none.
  zerver/webhooks/gitlab/view.py
Labels: size: XS

#27493 test-backend: Fix testing via shortcuts outside zerver/.
  tools/test-backend
Labels: size: M

#27484 sidebar_ui: Move initializing functions to module file.
  web/src/sidebar_ui.js
  web/src/ui_init.js
Labels: size: XL

#27417 help: Document option to paste URL to create a named link.
  help/insert-a-link.md
  zerver/lib/markdown/tabbed_sections.py
Labels: area: documentation (user), size: S, integration review

#27425 help: Document font configuration for unsupported languages.
  help/change-your-language.md
Labels: area: internationalization, area: documentation (user), size: S, integration review

#27301 help: Document "Start new conversation" button.
  help/direct-messages.md
  help/include/how-to-start-a-new-topic.md
  help/include/send-group-dm.md
  help/open-the-compose-box.md
Labels: area: documentation (user), priority: high, size: L, integration review

#27307 stream_edit: Enable notification settings for muted streams.
  web/src/stream_edit.js
  web/styles/subscriptions.css
  web/templates/settings/notification_settings.hbs
  web/templates/stream_settings/stream_settings.hbs
  web/templates/stream_settings/stream_settings_checkbox.hbs
Labels: size: S, integration review

#27502 compose: Disallow hotkeys when dropdowns (like stream pickers) are open.
  web/src/hotkey.js
Labels: size: XS

#27506 push_notifs: In dev, automatically use dev APNs cert if provided
  .gitignore
  zproject/dev_settings.py
Labels: area: provision, area: notifications (messages), area: mobile, size: S, integration review

#27423 populate_realm_db: Add script to add various types of realms.
  zerver/models.py
  zilencer/management/commands/populate_billing_realms.py
Labels: size: XL

#27514 emoji_picker: Stop propagating enter keypress to message.
  web/src/emoji_picker.js
Labels: size: XS

#27513 user_card_popover: Fix reactivate user button not working.
  web/src/user_card_popover.js
Labels: bug, priority: high, size: XS, area: popovers

#27520 left_sidebar: Display dark-mode condensed unreads without alpha.
  web/styles/left_sidebar.css
  web/styles/zulip.css
Labels: size: S, maintainer review, area: left sidebar (ui), area: left sidebar (display)

#27519 compose_tooltips: Don't show tooltip on focus.
  web/src/compose_tooltips.js
Labels: bug, area: compose (misc), priority: high, size: XS

#27518 scroll_bar: Hook to window resize event instead of ResizeObserver.
  web/src/resize_handler.js
  web/src/scroll_bar.ts
Labels: size: S

#27515 mention_dataset: Add query to mention cross realm bots as pill.
  zerver/lib/mention.py
Labels: bug, size: XS, area: message feed display, integration review

#27527 help: Add instructions to check whether push notifications are configured.
  help/mobile-notifications.md
Labels: size: M, integration review

#27533 compose: Fix bug where pasted content would only go to the compose box.
  web/src/copy_and_paste.js
Labels: size: XS

#27534 populate_billing_realms: Add next_invoice_date to CustomerPlans.
  zilencer/management/commands/populate_billing_realms.py
Labels: size: S

#27538 Handle topics_widget being undefined.
  web/src/recent_view_ui.js
Labels: size: XS, priority integration review

#27536 help: Document ability to drag-and-drop anywhere to upload a file.
  help/share-and-upload-files.md
  zerver/lib/markdown/tabbed_sections.py
Labels: area: documentation (user), size: S, integration review

#27537 left_sidebar: Align no-alpha variable for light mode unreads.
  web/styles/zulip.css
Labels: bug, size: XS, integration review, area: left sidebar (ui), area: left sidebar (display)

#27556 file_upload_error: Fix re-upload of files when upload fails.
  web/src/upload.js
Labels: bug, priority: high, size: XS, area: compose (uploads)

#27553 compose: Remove formatting enclosing entire selection when pasting.
  web/src/copy_and_paste.js
  web/tests/copy_and_paste.test.js
Labels: size: M

#27320 css: Improve the css of popover used to change visibility policy.
  web/styles/dark_theme.css
  web/styles/popovers.css
  web/templates/popovers/change_visibility_policy_popover.hbs
Labels: size: XL, integration review

#27582 puppet: Fix buggy media-src Content-Security-Policy.
  puppet/zulip/files/nginx/zulip-include-frontend/uploads-internal.conf
Labels: size: XS

#27580 docs: Update German style guide: Gender-inclusive language, direct messages, some cleanup
  docs/translating/german.md
Labels: size: L, integration review

#27595 Fix cannot open left sidebar menu if on top of compose box.
  web/src/popover_menus.js
Labels: size: S

#27598 typing_notifications: Don't notify long_term_idle subscribers.
  zerver/actions/typing.py
  zerver/lib/test_classes.py
  zerver/tests/test_typing.py
Labels: size: L

#27542 email_notification: Include prior message context only when mentioned.
  zerver/lib/email_notifications.py
  zerver/models.py
  zerver/tests/test_message_notification_emails.py
Labels: priority: high, area: emails, area: notifications (messages), size: XL

#27593 corporate: Fix downgrade small realms test realm generation.
  corporate/tests/test_stripe.py
Labels: size: M, area: billing

#27480 alerts: Fix improper copied tooltip location in About Zulip Modal.
  web/src/about_zulip.ts
  web/templates/about_zulip.hbs
Labels: size: S

#27452 compose_ui: Use Intl.ListFormat rather than .join(", "). #27353
  web/src/compose_ui.js
  web/tests/compose_ui.test.js
Labels: size: S

#27578 actions_popover: Fix copy link not working on `enter` keypress.
  web/src/popover_menus.js
  web/templates/popovers/actions_popover.hbs
Labels: size: S

#27531 settings_notifications: Allow users to modify notification settings of muted streams from "Personal settings"
  web/src/settings_notifications.js
  web/templates/settings/notification_settings_checkboxes.hbs
  web/templates/settings/stream_specific_notification_row.hbs
Labels: area: settings (user), priority: high, area: notifications (messages), size: S, integration review

#27611 popovers: Fix topic visibility popover in sticky header not working.
  web/src/popover_menus.js
Labels: bug, priority: high, size: S, integration review

#27261 counts: Add function compute_max_monthly_messages for remote servers.
  analytics/tests/test_support_views.py
  analytics/views/support.py
  corporate/tests/test_remote_counts.py
  templates/analytics/remote_server_support.html
  zilencer/lib/remote_counts.py
Labels: size: XL, integration review

#27606 message edit: Use a default error message for failed edits.
  web/src/message_edit.js
Labels: size: S

#27541 user_mention: Fix mentions of deactivated users.
  zerver/lib/markdown/__init__.py
  zerver/lib/mention.py
  zerver/tests/test_markdown.py
Labels: size: L, area: message feed display, integration review

#27610 compose: Always retain link formatting when pasting just a link.
  web/src/copy_and_paste.js
  web/tests/copy_and_paste.test.js
Labels: size: S

#27617 left_sidebar: Register mark-all-as-read handlers on home views.
  web/src/left_sidebar_navigation_area_popovers.js
Labels: bug, size: M, maintainer review, area: left sidebar (popovers)

#27469 lightbox_view: Fix media title update on change in title.
  web/src/lightbox.js
Labels: bug, area: message-editing, size: S, integration review, area: message feed embeds

#27386 help: Document new help menu.
  help/format-your-message-using-markdown.md
  help/keyboard-shortcuts.md
  help/search-for-messages.md
  zerver/lib/markdown/help_relative_links.py
Labels: area: documentation (user), priority: high, size: L, integration review

#27630 emoji_names: Rebuild with CLDR 44
  tools/setup/emoji/emoji_names.py
Labels: area: emoji, size: S, integration review

#27612 help: Document "Load more" recent conversations.
  help/recent-conversations.md
Labels: size: S, integration review

#27640 queue: Increase paging thresholds for deferred_work queue.
  scripts/lib/check_rabbitmq_queue.py
Labels: size: XS

#27647 stripe: Move `setup_upgrade_checkout_session_and...` to BillingSession.
  corporate/lib/stripe.py
  corporate/tests/test_stripe.py
  corporate/views/upgrade.py
Labels: size: XL

#27642 compose_banner: Display time for messages with < 5 mins scheduled time.
  web/src/scheduled_messages.js
  web/tests/scheduled_messages.test.js
Labels: bug, priority: high, size: M, integration review, area: compose (banners & validation)

#27636 corporate: Make `process_initial_upgrade` not reliant on customer with realm.
  corporate/lib/stripe.py
  corporate/lib/stripe_event_handler.py
  corporate/tests/test_stripe.py
  corporate/views/upgrade.py
Labels: size: L, area: billing

#27213 compose: Automatically change @ mentions to silent mentions in 1:1 DMs.
  web/src/compose_validate.js
  web/src/composebox_typeahead.js
  web/tests/composebox_typeahead.test.js
Labels: good first issue, size: M, integration review, area: compose (banners & validation)

#27650 hotkey: Give feedback when no unreads left in followed topics.
  web/src/feedback_widget.ts
  web/src/narrow.js
  web/templates/feedback_container.hbs
Labels: priority: high, size: S, area: popovers

#27597 counts: Add new mobile_pushes_sent::day LoggingCountStat and mobile_pushes_...::day RemoteRealmCounts
  analytics/lib/counts.py
  analytics/management/commands/check_analytics_state.py
  analytics/management/commands/clear_single_stat.py
  analytics/management/commands/update_analytics_counts.py
  analytics/tests/test_counts.py
  zerver/lib/push_notifications.py
  zerver/tests/test_push_notifications.py
  zilencer/migrations/0035_remoterealmcount_remote_realm_and_more.py
  zilencer/models.py
  zilencer/views.py
Labels: size: XL

#27653 search: Remove "All messages" typeahead
  web/src/search_suggestion.js
  web/tests/search_suggestion.test.js
Labels: area: search, priority: high, size: S, integration review

#27269 ts: Convert `activity.js` module to TypeScript.
  web/src/activity.ts
  web/src/global.d.ts
  web/src/presence.ts
  web/tests/activity.test.js
Labels: size: L, maintainer review, area: typescript migration

#27659 inbox: Fix search icon position on narrow widths.
  web/styles/inbox.css
  web/templates/inbox_view/inbox_view.hbs
Labels: priority: high, size: S, integration review

#27676 invite: Use ICU plural syntax for invite success message.
  web/src/invite.ts
Labels: size: S

#27670 refactor: Rename `is_search` to `is_keyword_search` for clarity.
  web/src/filter.js
  web/src/message_feed_top_notices.js
  web/src/message_list.js
  web/src/message_list_data.js
  web/src/message_list_view.js
  web/src/narrow_state.js
  web/src/search.js
  web/tests/filter.test.js
  web/tests/message_list_data.test.js
  web/tests/search.test.js
Labels: size: M

#27675 stripe: Move `process_initial_upgrade` to BillingSession.
  corporate/lib/stripe.py
  corporate/lib/stripe_event_handler.py
  corporate/tests/test_stripe.py
  corporate/views/upgrade.py
Labels: size: XL

#27679 left_sidebar: Set shared right margin on DM section.
  web/styles/left_sidebar.css
Labels: integration review, area: left sidebar (display)

#27680 left_sidebar: Explicitly handle clicks on collapsible Views targets.
  web/src/left_sidebar_navigation_area.js
Labels: size: S, integration review, area: left sidebar (ui)

#27672 Unset `is_web_public` field on attachments when deactivating stream.
  zerver/actions/streams.py
Labels: bug, area: stream settings, priority: high, size: M

#27697 stripe: Add 'do_upgrade' method to the 'BillingSession' class.
  corporate/lib/stripe.py
  corporate/views/upgrade.py
Labels: size: XL

#27693 typeahead: Fix '@topic' not present when stream wildcard suggested.
  web/src/typeahead_helper.js
  web/tests/composebox_typeahead.test.js
Labels: size: S

#27687 Backport https://github.com/zulip/zulip/pull/27160 to 7.x branch.
  zerver/management/commands/backup.py
Labels: size: S

#27669 sort_emojis: Prioritize perfect matches above all
  web/shared/src/typeahead.ts
  web/tests/typeahead.test.js
Labels: size: M, integration review

#27485 stream_color: Increase contrast of stream icon color and background.
  web/src/stream_color.ts
  web/tests/drafts.test.js
Labels: size: S, integration review, chat.zulip.org review

#27703 compose_box: Better align and maintain alignment of topic marker.
  web/styles/compose.css
Labels: area: compose (misc), size: XS, integration review, area: compose (UI & widgets)

#27695 Bunch of bug fixes where stream id had to be passed into `compose_actions.start` instead of stream name.
  web/src/scheduled_messages_ui.js
Labels: size: XS, integration review

#27707 left_sidebar: Keep all DM container rows to same right margin.
  web/styles/left_sidebar.css
Labels: size: S, integration review, area: left sidebar (display)

#27691 bililng: Fix incorrect price per license on billing page.
  corporate/lib/stripe.py
  corporate/tests/stripe_fixtures/free_trial_upgrade_by_card--Customer.retrieve.4.json
  corporate/tests/test_stripe.py
  corporate/views/billing_page.py
  web/src/billing/helpers.ts
Labels: size: XL

#27710 typeahead: Include wildcard mentions in typeahead for small streams.
  web/src/compose_validate.js
  web/tests/compose_validate.test.js
Labels: bug, priority: high, size: M, integration review, area: compose (typeahead)

#27714 compose box: Message-preview fixes.
  web/styles/compose.css
Labels: area: compose (misc), size: S, integration review

#27716 recent_view: Correct icon alignment within rows.
  web/styles/recent_view.css
Labels: bug, size: S, area: recent-conversations, integration review

#27678 stripe: Move `make_end_of_cycle_updates_if_needed` to BillingSession.
  analytics/views/support.py
  corporate/lib/stripe.py
  corporate/tests/test_stripe.py
  corporate/views/billing_page.py
Labels: size: XL

#27712 typing: Limit typing notifications in large streams.
  help/typing-notifications.md
  zerver/actions/typing.py
  zerver/tests/test_typing.py
  zproject/default_settings.py
Labels: size: L

#27719 docs: Update server roadmap documentation.
  docs/overview/release-lifecycle.md
Labels: size: L, integration review

#27722 compose_box: Set auto height on textarea in full screen.
  web/styles/compose.css
Labels: bug, size: S, integration review, area: compose (UI & widgets)

#27720 compose_ui: Fall back to comma join when `Intl.ListFormat` is missing
  web/src/compose_ui.js
Labels: size: S, integration review

#27724 openapi: Remove unnecessary cast
  zerver/openapi/openapi.py
Labels: size: S

#27729 management: Allow changing is_billing_admin using change_user_role.
  corporate/lib/stripe.py
  corporate/views/upgrade.py
  zerver/actions/users.py
  zerver/management/commands/change_user_role.py
  zerver/tests/test_events.py
Labels: size: M

#27728 help: Document changing home view from left sidebar.
  help/configure-home-view.md
Labels: area: documentation (user), size: S, integration review

#27732 docs: Update Spanish translation for "Narrow to".
  docs/translating/spanish.md
Labels: size: S, integration review

#27737 left_sidebar: Preserve DM layout when zoomed into more conversations.
  web/styles/left_sidebar.css
Labels: size: S, integration review, area: left sidebar (ui), area: left sidebar (display)

#27736 stripe: Add `get_billing_page_context` method to 'BillingSession'.
  corporate/lib/stripe.py
  corporate/tests/test_stripe.py
  corporate/views/billing_page.py
Labels: size: XL

#27739 help: Define "participate" for automatically following topics.
  help/follow-a-topic.md
Labels: bug, area: topics, size: XS, integration review

#27738 help: Document @ topic mentions.
  help/dm-mention-alert-notifications.md
  help/include/mentions-examples.md
  help/include/mentions-intro.md
  help/mention-a-user-or-group.md
  static/images/help/markdown-mentions.png
Labels: area: documentation (user), priority: high, size: M, integration review, documentation review

#27742 rest-endpoints: Add new /api/get-stream-email-address endpoint.
  api_docs/include/rest-endpoints.md
Labels: size: XS, backport candidate

#27745 openapi: Use SuccessDescription in new get-stream-email-address.
  zerver/openapi/zulip.yaml
Labels: size: XS

#27689 zulip_ops: Configure stats to be pushed to status.zulip.com.
  puppet/zulip_ops/files/statuspage-pusher
  puppet/zulip_ops/manifests/profile/prometheus_server.pp
  puppet/zulip_ops/manifests/statuspage.pp
  puppet/zulip_ops/templates/supervisor/conf.d/statuspage-pusher.conf.template.erb
Labels: size: XL

#27747 analytics: Regenerate partial indexes due to Django bug.
  analytics/migrations/0017_regenerate_partial_indexes.py
Labels: size: XL

#27750 help: Document that pronouns are now shown in @-mention typeahead.
  help/custom-profile-fields.md
Labels: size: XS, integration review

#27749 docs: Update changelog to cover changes staged for 8.0.
  docs/overview/changelog.md
Labels: size: L

#27751 tippyjs: Convert module to TypeScript
  tools/test-js-with-node
  web/src/tippyjs.ts
Labels: size: L, integration review, area: typescript migration

#27756 drafts: Update some stale docstrings regarding draft data validation.
  zerver/lib/drafts.py
Labels: size: S

#27757 api_docs: Clarify found_oldest/newest descriptions.
  zerver/openapi/zulip.yaml
Labels: size: S

#27759 Rename "Manage streams" -> "Stream settings".
  docs/testing/manual-testing.md
  docs/translating/translating.md
  help/keyboard-shortcuts.md
  help/unsubscribe-from-a-stream.md
  web/src/add_stream_options_popover.js
  web/src/gear_menu.js
  web/src/stream_settings_ui.js
  web/templates/gear_menu_popover.hbs
  web/templates/keyboard_shortcuts.hbs
  zerver/lib/markdown/help_relative_links.py
  zerver/tests/test_docs.py
Labels: size: M, integration review

#27761 help: Fix copy-paste bug in wildcard mention documentation.
  help/mention-a-user-or-group.md
Labels: size: XS, integration review

#27764 compose: Fix bug where extra line breaks were pasted between blocks.
  web/src/copy_and_paste.js
  web/tests/copy_and_paste.test.js
Labels: size: S, integration review

#27651 compose: Disable send button when upload/s are in progress.
  web/src/compose_recipient.js
  web/src/compose_tooltips.js
  web/src/compose_validate.js
  web/src/upload.js
  web/tests/compose_validate.test.js
  web/tests/upload.test.js
Labels: priority: high, size: L, integration review, area: compose (uploads)

#27546 style: Fix overflow of text.
  web/styles/zulip.css
Labels: bug, area: right-sidebar, size: XS, integration review, area: left sidebar (popovers)

#27770 help: Document how to change font size with zoom.
  help/font-size.md
  help/include/sidebar_index.md
Labels: size: S, integration review

#27768 api_docs: Add missing followed topic visibility policy.
  api_docs/changelog.md
  zerver/openapi/zulip.yaml
Labels: size: S

#27763 settings: Add option for followed topics to unread count badge setting.
  api_docs/changelog.md
  version.py
  web/src/settings_config.ts
  web/src/unread.js
  web/tests/unread.test.js
  zerver/migrations/0490_renumber_options_desktop_icon_count_display.py
  zerver/models.py
  zerver/openapi/zulip.yaml
Labels: area: settings (user), priority: high, size: XL

#27116 ldap: Realms not listed in access control setting should not be affected by it.
  docs/overview/changelog.md
  docs/production/authentication-methods.md
  zerver/tests/test_auth_backends.py
  zproject/backends.py
Labels: area: authentication, size: M, integration review

#27666 message_view_header: Add tooltip to stream name in top navbar.
  web/src/message_view_header.js
  web/templates/message_view_header.hbs
Labels: priority: high, size: S, area: popovers, integration review, area: navbar

#27772 help: Improve unread count badge documentation.
  help/desktop-notifications.md
  help/follow-a-topic.md
Labels: size: M, integration review, documentation review

#27790 watchdog: Handle exception in `callback`.
  web/src/watchdog.ts
  web/tests/watchdog.test.js
Labels: bug, area: misc, size: M

#27798 stripe: Add 'do_initial_upgrade' method to the 'BillingSession' class.
  corporate/lib/stripe.py
  corporate/tests/test_stripe.py
  corporate/views/upgrade.py
Labels: size: XL

#27783 realm_inline_image_preview: Use it to toggle video previews too.
  help/allow-image-link-previews.md
  web/src/admin.js
  zerver/lib/markdown/__init__.py
Labels: size: S

#27797 narrow: Fix `near:ID` narrows with invalid stream name in hash.
  web/src/narrow.js
Labels: bug, area: misc, priority: high, size: S

#27800 email_notification: Fix bad rendering of math formulas.
  zerver/lib/email_notifications.py
  zerver/tests/test_message_notification_emails.py
Labels: size: M

#27805 zilencer: Store the last-reported server version when storing analytics.
  zerver/tests/test_push_notifications.py
  zilencer/migrations/0036_remotezulipserver_last_version.py
  zilencer/models.py
  zilencer/views.py
Labels: size: M

#27807 buddy list: Rename sel variables to selector to avoid abbreviations.
  web/src/buddy_list.js
  web/src/list_cursor.ts
  web/src/stream_list.js
  web/tests/buddy_list.test.js
  web/tests/list_cursor.test.js
  web/tests/user_search.test.js
Labels: size: M

#27808 padded widget: Use padding_selector instead of padding_sel.
  web/src/padded_widget.ts
Labels: size: XS

#27806 timerender: Avoid dateStyle option missing in Safari < 14.1
  web/src/message_edit_history.js
  web/src/timerender.ts
Labels: size: S, integration review

#27760 popovers: Reduce avatar width such that it fits inside its container.
  web/styles/popovers.css
Labels: size: S

#27792 views: Set focus back to views after closing compose box.
  web/src/inbox_ui.js
  web/src/recent_view_ui.js
Labels: bug, area: compose (misc), size: S, area: recent-conversations, integration review

#27193 popovers: Insert silent mentions for deactivated users.
  web/src/user_card_popover.js
Labels: size: XS

#27831 migrations: Fix revert migration to not lose all preferences.
  zerver/migrations/0490_renumber_options_desktop_icon_count_display.py
Labels: size: S

#27832 migrations: Keep the existing constraints until the new ones are made.
  zilencer/migrations/0037_alter_remoteinstallationcount_unique_together_and_more.py
Labels: size: S

#27316 message-editing: Make default "Move messages" form context-dependent.
  web/src/message_edit.js
  web/src/stream_popover.js
  web/templates/move_topic_to_stream.hbs
Labels: size: XL, chat.zulip.org review

#27833 hotkey: Fix emoji popover not triggered in a narrow width range.
  web/src/hotkey.js
  web/tests/hotkey.test.js
Labels: size: S

#27834 stripe: Use 'get_price_per_license' in 'get_initial_upgrade_context'.
  corporate/lib/stripe.py
  corporate/views/upgrade.py
  web/src/billing/page_params.ts
  web/src/billing/upgrade.ts
Labels: size: S

#27842 Free trial billing page remove onboarding flow and minor text changes.
  corporate/lib/stripe.py
  corporate/tests/stripe_fixtures/free_trial_upgrade_by_card_from_onboarding_page--Charge.list.1.json
  corporate/tests/stripe_fixtures/free_trial_upgrade_by_card_from_onboarding_page--Customer.create.1.json
  corporate/tests/stripe_fixtures/free_trial_upgrade_by_card_from_onboarding_page--Customer.modify.1.json
  corporate/tests/stripe_fixtures/free_trial_upgrade_by_card_from_onboarding_page--Customer.retrieve.1.json
  corporate/tests/stripe_fixtures/free_trial_upgrade_by_card_from_onboarding_page--Customer.retrieve.2.json
  corporate/tests/stripe_fixtures/free_trial_upgrade_by_card_from_onboarding_page--Customer.retrieve.3.json
  corporate/tests/stripe_fixtures/free_trial_upgrade_by_card_from_onboarding_page--Customer.retrieve.4.json
  corporate/tests/stripe_fixtures/free_trial_upgrade_by_card_from_onboarding_page--Event.list.1.json
  corporate/tests/stripe_fixtures/free_trial_upgrade_by_card_from_onboarding_page--Invoice.list.1.json
  corporate/tests/stripe_fixtures/free_trial_upgrade_by_card_from_onboarding_page--Invoice.list.2.json
  corporate/tests/stripe_fixtures/free_trial_upgrade_by_card_from_onboarding_page--SetupIntent.create.1.json
  corporate/tests/stripe_fixtures/free_trial_upgrade_by_card_from_onboarding_page--SetupIntent.list.1.json
  corporate/tests/stripe_fixtures/free_trial_upgrade_by_card_from_onboarding_page--SetupIntent.retrieve.1.json
  corporate/tests/stripe_fixtures/free_trial_upgrade_by_card_from_onboarding_page--checkout.Session.create.1.json
  corporate/tests/stripe_fixtures/free_trial_upgrade_by_card_from_onboarding_page--checkout.Session.list.1.json
  corporate/tests/test_stripe.py
  corporate/views/billing_page.py
  corporate/views/upgrade.py
  templates/corporate/billing.html
  templates/corporate/upgrade.html
  web/styles/portico/billing.css
  zerver/tests/test_signup.py
  zerver/views/auth.py
Labels: size: XL, area: billing, integration review

#27809 help: Document "Manage a user".
  help/change-a-users-name.md
  help/change-a-users-role.md
  help/deactivate-or-reactivate-a-user.md
  help/include/sidebar_index.md
  help/manage-a-user.md
Labels: area: documentation (user), size: M, integration review

#27464 invite: Add setup tips to user invite modal.
  web/src/invite.ts
  web/src/page_params.ts
  web/templates/invite_user_modal.hbs
  web/templates/modal_banner/invite_tips_banner.hbs
  web/templates/modal_banner/modal_banner.hbs
Labels: size: L, integration review

#27853 realm: Allow setting notification settings to unsubscribed private streams.
  zerver/tests/test_realm.py
  zerver/views/realm.py
Labels: integration review

#27856 message_view_header: Update tooltip over stream name in top bar.
  web/templates/message_view_header.hbs
Labels: size: S, integration review

#27829 help: Document modal to generate bot URL.
  help/add-a-bot-or-integration.md
  help/bots-and-integrations.md
  help/generate-integration-url.md
  help/include/sidebar_index.md
  templates/zerver/integrations/include/generate-integration-url.md
Labels: area: documentation (user), area: documentation (api and integrations), size: L, integration review

#27859 help: Add intro to "Generate URL for an integration" page.
  help/generate-integration-url.md
Labels: size: S, integration review, documentation review

#27575 Prototype for authentication flow for web management UI on the push bouncer
  corporate/urls.py
  corporate/views/remote_billing_page.py
  templates/corporate/remote_billing.html
  tools/test-backend
  web/src/popover_menus_data.js
  web/templates/gear_menu_popover.hbs
  zerver/decorator.py
  zerver/lib/exceptions.py
  zerver/lib/home.py
  zerver/lib/remote_server.py
  zerver/lib/test_helpers.py
  zerver/tests/test_home.py
  zerver/views/push_notifications.py
  zilencer/urls.py
  zproject/urls.py
Labels: size: XL

#27865 help: Document compose box UI changes.
  help/include/compose-and-send-message.md
  help/include/replying-to-messages.md
  help/mastering-the-compose-box.md
  help/schedule-a-message.md
Labels: area: documentation (user), priority: high, size: M, integration review

#27869 left_sidebar: Preserve views collapsed / expanded state.
  web/src/left_sidebar_navigation_area.js
Labels: priority: high, size: S, area: left sidebar (ui)

#27836 css: Set tippy-arrow color same as background in light theme.
  web/styles/compose.css
  web/styles/dark_theme.css
  web/styles/popovers.css
  web/styles/zulip.css
Labels: size: L, integration review

#27873 Add support to update `can_access_all_users_group` setting in dev environment.
  web/src/settings_components.js
  web/src/settings_org.js
  web/src/types.ts
  web/src/user_groups.ts
  web/styles/settings.css
  web/templates/settings/organization_permissions_admin.hbs
  web/tests/user_groups.test.js
  zerver/models.py
  zerver/tests/test_realm.py
  zerver/views/realm.py
Labels: size: XL

#27880 help: Document updated setting to restrict wildcard mentions.
  help/restrict-wildcard-mentions.md
Labels: size: M, integration review, documentation review

#27765 mention: Fix mention highlighting in unsubscribed streams.
  web/src/message_list_view.js
  web/src/rendered_markdown.js
  web/styles/rendered_markdown.css
  web/tests/rendered_markdown.test.js
Labels: bug, priority: high, size: XL, area: message feed display, integration review

#27884 tests: Add test for nocoverage userAccountControl case in ldap auth.
  zerver/tests/test_auth_backends.py
  zproject/backends.py
Labels: size: S

#27909 recent_view: Show checkbox icon for unread filter.
  web/src/recent_view_ui.js
  web/tests/recent_view.test.js
Labels: size: S

#27871 message_feed_ui: Fix focus when clicking on message feed buttons.
  web/src/click_handlers.js
  web/src/emoji_picker.js
  web/src/user_card_popover.js
Labels: priority: high, size: S, area: message feed UI, integration review

#27885 keyboard_shortcut: Add feedback for N/P shortcut after no more message.
  web/src/narrow.js
Labels: size: S, integration review
