Repository zulip/zulip, pull requests merged in 2023-08, with the labels that each got.

#26407 ruff: Fix UP032 Use f-string instead of `format` call
  scripts/lib/unpack-zulip
  tools/droplets/add_mentor.py
  tools/droplets/create.py
  tools/generate-integration-docs-screenshot
  zerver/lib/bot_config.py
  zerver/lib/zcommand.py
  zerver/management/commands/send_webhook_fixture_message.py
  zerver/tests/test_auth_backends.py
  zerver/tests/test_markdown.py
  zerver/tests/test_message_send.py
  zerver/tests/test_retention.py
  zerver/tests/test_signup.py
  zerver/tests/test_upload.py
  zerver/webhooks/front/view.py
Labels: size: XL

#26361 mailmap: Add evy@zulip.com.
  .mailmap
Labels: size: XS, maintainer review

#26378 mailmap: Put sorted list back in order
  .mailmap
  tools/lint
Labels: size: M

#26401 people: Revert to using `ignore_missing` parameter.
  web/src/people.ts
  web/src/presence.js
  web/src/rendered_markdown.js
  web/tests/presence.test.js
Labels: size: S

#26390 users: Fix TypedDict name for get_accounts_for_email return
  zerver/lib/users.py
  zerver/tests/test_users.py
Labels: size: S

#26410 ruff: Collapse short multi-line import statements
  pyproject.toml
  zerver/actions/message_send.py
  zerver/lib/cache_helpers.py
  zerver/lib/events.py
  zerver/lib/users.py
  zerver/tests/test_invite.py
  zerver/tests/test_signup.py
  zerver/tests/test_upload_local.py
  zerver/tests/test_upload_s3.py
  zerver/tests/test_user_topics.py
  zerver/views/message_send.py
  zerver/views/report.py
  zerver/views/sentry.py
  zproject/urls.py
Labels: size: L

#26411 event_schema: Remove useless “force vertical” comments
  zerver/lib/event_schema.py
Labels: size: M

#26335 ts: Migrate `alert_words.js` to TypeScript.
  web/src/alert_words.ts
Labels: size: M, mentor review, area: typescript migration

#26414 tests: Correct the spelling of 'caret'.
  web/tests/compose_ui.test.js
Labels: area: testing-coverage, size: S, integration review

#26420 namespace: Clean up template_path manipulation
  web/tests/lib/namespace.js
  web/tests/recent_topics.test.js
  web/tests/stream_list.test.js
Labels: size: M

#26403 puppet: Rename and generalize Tornado process exporter.
  puppet/zulip_ops/files/process_exporter.yaml
  puppet/zulip_ops/files/tornado_process_exporter.yaml
  puppet/zulip_ops/manifests/prometheus/process.pp
  puppet/zulip_ops/templates/supervisor/conf.d/prometheus_process_exporter.conf.template.erb
Labels: size: M, integration review

#26372 user_groups: Update code for changing group level settings.
  zerver/views/user_groups.py
Labels: size: XS, integration review

#26337 settings: Add a saving-saved indicator to the 'SETTINGS/TOPICS' UI.
  web/src/settings_user_topics.js
  web/src/user_topics.js
  web/templates/settings/user_topics_settings.hbs
  web/tests/settings_user_topics.test.js
Labels: size: M, integration review, buddy review, mentor review

#26423 dropdown_widget: Show disabled if value not in options.
  web/src/dropdown_widget.js
  web/src/settings_org.js
Labels: size: S

#26321 scheduled messages: Allow user to reschedule quickly from edit window.
  web/src/compose.js
  web/src/scheduled_messages.js
Labels: area: compose, size: S, maintainer review

#26398 streams: Add stream traffic data to `Stream` objects.
  api_docs/changelog.md
  version.py
  web/tests/lib/events.js
  zerver/actions/streams.py
  zerver/lib/default_streams.py
  zerver/lib/event_schema.py
  zerver/lib/events.py
  zerver/lib/streams.py
  zerver/lib/types.py
  zerver/models.py
  zerver/openapi/zulip.yaml
  zerver/tests/test_event_system.py
  zerver/tests/test_events.py
  zerver/tests/test_subs.py
  zerver/views/streams.py
Labels: size: XL

#26416 puppeteer: Use `stream_name` instead of `stream` for clarity.
  web/e2e-tests/compose.test.ts
  web/e2e-tests/copy-and-paste.test.ts
  web/e2e-tests/drafts.test.ts
  web/e2e-tests/edit.test.ts
  web/e2e-tests/lib/common.ts
  web/e2e-tests/message-basics.test.ts
  web/e2e-tests/stars.test.ts
Labels: size: L, maintainer review

#26404 test_users: Use 'do_change_user_setting' instead of '.save()'.
  zerver/tests/test_users.py
Labels: size: L, integration review, mentor review

#26406 hashchange: Remove hiding of recent topics.
  web/src/hashchange.js
Labels: size: XS, maintainer review

#26400 test_event_queue: Set the notification settings explicitly.
  zerver/tests/test_event_queue.py
Labels: size: S, integration review, mentor review

#26387 events: Add test for removing custom profile field data.
  zerver/lib/event_schema.py
  zerver/lib/events.py
  zerver/tests/test_events.py
Labels: area: testing-coverage, area: settings (user), size: L, integration review

#26351 help: Add gear menu icons to relative links.
  zerver/lib/markdown/help_relative_links.py
  zerver/tests/test_docs.py
Labels: size: M, integration review

#26439 setup-recommended: Fix typographical issues
  docs/development/setup-recommended.md
Labels: size: M

#26393 emoji: Run generate_emoji_names with up-to-date data.
  tools/setup/emoji/emoji_names.py
  tools/setup/emoji/generate_emoji_names
Labels: size: L, integration review

#26389 ruff: Fix FLY002 Consider f"…" instead of string join
  pyproject.toml
  tools/webpack
  zerver/lib/request.py
  zerver/lib/upload/local.py
  zerver/lib/upload/s3.py
  zerver/migrations/0149_realm_emoji_drop_unique_constraint.py
  zerver/tests/test_invite.py
  zerver/tests/test_message_fetch.py
Labels: size: M, integration review

#26384 ts: Migrate `pm_conversations` module to typescript.
  web/src/pm_conversations.ts
Labels: size: M, integration review

#26433 Message Feed: Fix collapsed messages for highlighted texts.
  web/styles/message_row.css
  web/styles/zulip.css
Labels: bug, design, size: L, area: message feed display, integration review

#26440 tests: Disable flaky test_edit_bot_form test.
  web/e2e-tests/settings.test.ts
Labels: size: XS

#26457 print: Hide closing X on search bar.
  web/styles/print.css
Labels: area: search, size: XS, area: message feed display, integration review

#23429 ci: Move backend tests further late in the queue.
  .github/workflows/zulip-ci.yml
Labels: size: L, has conflicts

#26386 docs: Document printable conversations.
  help/include/sidebar_index.md
  help/printing-messages.md
Labels: area: documentation (user), size: M, area: message feed display, maintainer review, documentation review

#26462 changelog: Fix incorrect documentation link.
  api_docs/changelog.md
Labels: size: XS, integration review

#26465 generate_emoji_names: Fix use of stale aliases variable
  tools/setup/emoji/generate_emoji_names
Labels: size: XS

#26469 tests: Defer writing coverage report.
  tools/test-backend
Labels: size: S

#26475 caching docs: Tweak a few things.
  docs/subsystems/caching.md
Labels: size: S

#26476 tests: Remove spurious nocoverage directive.
  zerver/lib/test_helpers.py
Labels: size: XS

#26467 docs: Add `multiple-organizations.md` to production section of RTD table of contents.
  docs/production/index.md
  docs/production/multiple-organizations.md
Labels: area: documentation (production), size: XS, documentation review

#26452 help: Add heading on linking to messages in "Writing messages" section.
  help/include/sidebar_index.md
Labels: size: XS, integration review

#26455 dropdown-list-widget: Remove "dropdown-list-body" class and reference.
  web/src/ui_init.js
  web/styles/settings.css
Labels: area: misc, size: M, integration review

#26443 condense: Focus on the message after condensing/expanding it.
  web/src/condense.js
Labels: size: S, area: message feed display, integration review

#26460 stream settings: Warn users before locking them out of a stream.
  web/src/settings_org.js
  web/src/stream_edit.js
  web/templates/stream_settings/stream_settings.hbs
Labels: area: stream settings, area: documentation (user), area: settings (admin/org), size: L

#24091 docs: Update .html links pointing to "Upgrade Zulip" or "Modify Zulip".
  SECURITY.md
  docs/_templates/layout.html
  help/include/advantages-of-self-hosting-zulip.md
  help/setting-up-zulip-for-a-class.md
  help/view-zulip-version.md
  scripts/lib/check-database-compatibility
  scripts/lib/upgrade-zulip-stage-2
  templates/corporate/for/business.html
  templates/corporate/for/open-source.html
  templates/corporate/pricing_model.html
  templates/corporate/self-hosting.html
  templates/zerver/footer.html
  templates/zerver/landing_nav.html
  web/templates/gear_menu.hbs
Labels: size: M, integration review

#26491 topic: Set a max batch_size on bulk_upate call.
  zerver/lib/topic.py
Labels: size: XS, backport candidate

#26481 test_openapi: Use subtests for arguments test.
  zerver/tests/test_openapi.py
Labels: size: XL

#26315 ts: Migrate `bot_data.js` to TypeScript
  web/src/bot_data.js
  web/src/bot_data.ts
  web/tests/bot_data.test.js
  web/tests/settings_bots.test.js
Labels: size: XL, integration review, area: typescript migration

#26499 test-openapi: Add coverage for documented fetch API key endpoints.
  zerver/tests/test_openapi.py
Labels: area: testing-coverage, area: api, size: S

#26486 topic_popover: Add a 'Default' option and Show 'Unmute' option conditionally.
  web/shared/icons/follow.svg
  web/shared/icons/inherit.svg
  web/shared/icons/mute-new.svg
  web/shared/icons/unmute-new.svg
  web/templates/topic_sidebar_actions.hbs
Labels: size: M, integration review, mentor review

#26434 uploads: Fix double negation in do_claim_attachments comment.
  zerver/actions/uploads.py
Labels: size: XS, integration review

#26501 version: Bump API feature level.
  version.py
Labels: size: XS

#26429 Refactor: Use `add_narrow_conditions` in `messages_in_narrow_backend`.
  zerver/tests/test_message_fetch.py
  zerver/views/message_fetch.py
Labels: size: L

#26418 ts: Migrate `settings_ui.js` to TypeScript.
  tools/test-js-with-node
  web/src/settings_ui.ts
Labels: size: M

#25818 narrow: Fix topic highlighting issue with apostrophes in search results.
  zerver/lib/narrow.py
  zerver/tests/test_message_fetch.py
  zerver/views/message_fetch.py
Labels: bug, area: search, size: L, area: message feed UI, buddy review, mentor review

#26392 analytics: Do not reseed the global random generator
  analytics/lib/fixtures.py
Labels: size: S, integration review

#26473 docs: Avoid exception in scrollToHash()
  web/src/portico/help.js
Labels: area: portico, size: S, integration review

#26494 recent_topics: Move is_in_focus to UI module.
  web/src/hotkey.js
  web/src/recent_topics_ui.js
  web/src/recent_topics_util.js
  web/tests/hotkey.test.js
Labels: size: M

#26500 dialog_widget: Add horizontal padding to the modal content.
  web/styles/modal.css
Labels: size: XS

#26503 portico_signin: Fix back to login button alignment.
  web/styles/portico/portico_signin.css
Labels: size: S, integration review

#26488 ts: Migrate `presence.js` module to typescript.
  web/src/page_params.ts
  web/src/presence.ts
Labels: size: L, integration review, area: typescript migration

#26512 api-docs: Fix documentation of `realm_emoji` in register response.
  zerver/openapi/zulip.yaml
  zerver/tests/test_event_system.py
Labels: area: testing-coverage, area: documentation (api and integrations), size: S, api docs review

#26041 upload: Support drag and dropping files anywhere on message viewport.
  web/src/compose.js
  web/src/message_edit.js
  web/src/ui_init.js
  web/src/upload.js
  web/tests/upload.test.js
Labels: area: compose, priority: high, size: XL, UX, integration review, buddy review

#23116 migration: Migrate from TextField to JSONField for audit log models.
  corporate/lib/stripe.py
  corporate/tests/test_stripe.py
  zerver/actions/bots.py
  zerver/actions/create_realm.py
  zerver/actions/create_user.py
  zerver/actions/muted_users.py
  zerver/actions/realm_domains.py
  zerver/actions/realm_emoji.py
  zerver/actions/realm_export.py
  zerver/actions/realm_icon.py
  zerver/actions/realm_linkifiers.py
  zerver/actions/realm_playgrounds.py
  zerver/actions/realm_settings.py
  zerver/actions/streams.py
  zerver/actions/user_groups.py
  zerver/actions/user_settings.py
  zerver/actions/users.py
  zerver/lib/export.py
  zerver/lib/user_groups.py
  zerver/migrations/0467_rename_extradata_realmauditlog_extra_data_json.py
  zerver/models.py
  zerver/tests/test_audit_log.py
  zerver/tests/test_events.py
  zerver/tests/test_muted_users.py
  zerver/tests/test_push_notifications.py
  zerver/tests/test_realm.py
  zerver/tests/test_realm_export.py
  zerver/tests/test_realm_linkifiers.py
  zerver/tests/test_subs.py
  zerver/views/realm_export.py
  zerver/worker/queue_processors.py
  zilencer/migrations/0028_rename_extradatajson_remoteauditlog_extra_data.py
  zilencer/views.py
Labels: size: XL, maintainer review

#26516 api-docs: Remove incorrect error response from `/api/subscribe`.
  zerver/openapi/zulip.yaml
Labels: area: documentation (api and integrations), size: M, api docs review

#26518 middleware: Allow HTTP from localhost, not through a reverse proxy.
  zerver/middleware.py
Labels: size: S, backport candidate, integration review

#26408 message scroll: Check message feed visibility instead of recent topics.
  web/src/message_scroll.js
Labels: size: XS, maintainer review

#26530 requirements: Upgrade Python requirements
  requirements/dev.txt
  requirements/pip.txt
  requirements/prod.txt
  version.py
Labels: size: M, backport candidate

#26535 navbar: Hide right arrow displayed by Safari on summary elements.
  web/styles/portico/navbar.css
Labels: size: XS, integration review

#26492 unread_count: Remove letter spacing for better horizontal alignment.
  web/styles/app_components.css
Labels: area: left-sidebar, size: XS, integration review

#26544 bot_data: Fix `owner_id` field to allow null value.
  web/src/bot_data.ts
Labels: size: S

#26546 Add provision support for Fedora 38
  docs/development/setup-advanced.md
  scripts/lib/build-groonga
  tools/lib/provision.py
Labels: area: provision, size: M

#26545 narrow: Fix by_topic and by_recipient for stream and message ID.
  web/src/narrow.js
Labels: size: XS, priority integration review

#26543 portico: Remove Senior Flutter Engineer position from jobs page.
  templates/corporate/jobs.html
Labels: size: XL

#26522 docs: Consistently say "18 months" on compatibility, no specific version numbers.
  docs/overview/release-lifecycle.md
Labels: area: documentation (production), area: mobile, size: S, backport candidate, integration review

#26548 time: Revert to Source Sans lnum, tnum defaults.
  web/styles/zulip.css
Labels: area: message feed display, maintainer review

#26539 send_email: Use a consistent order when sending custom emails to users.
  zerver/lib/send_email.py
Labels: size: XS, integration review

#26451 narrow: Save blue box position and restore on navigation.
  tools/test-js-with-node
  web/src/hashchange.js
  web/src/narrow.js
  web/src/narrow_history.js
  web/src/ui_init.js
  web/tests/narrow_activate.test.js
Labels: priority: high, size: L, area: message feed UI

#26555 ci: Restore commented `clean_unused_caches.py` invocation
  .github/workflows/zulip-ci.yml
Labels: size: XS

#26477 typing: Add typing constants to the post register api response.
  api_docs/changelog.md
  version.py
  web/shared/src/typing_status.ts
  web/src/typing.js
  web/src/typing_events.js
  web/tests/typing_status.test.js
  zerver/lib/events.py
  zerver/openapi/zulip.yaml
  zerver/tests/test_home.py
  zproject/default_settings.py
Labels: size: XL, integration review

#26554 typing: Update main typing notifications protocol documentation.
  docs/subsystems/typing-indicators.md
  zerver/openapi/zulip.yaml
Labels: area: documentation (developer), area: documentation (api and integrations), size: XL, api docs review

#26561 check-database-compatibility: Ignore twofactor typo
  scripts/lib/check-database-compatibility
Labels: size: XS, backport candidate

#26562 requirements: Fix transitively replaced two_factor migrations
  requirements/common.in
  requirements/dev.txt
  requirements/prod.txt
  version.py
Labels: size: S, backport candidate

#26564 stats: Add stats `page_params` to `webpack.assets.json`.
  web/webpack.assets.json
Labels: area: analytics, size: XS, priority integration review

#26559 lightbox: Fix + and - zoom shortcuts to be inverses of each other
  web/src/lightbox.js
Labels: size: S, integration review

#26551 help: Document "Browse and subscribe to streams" mobile feature.
  help/browse-and-subscribe-to-streams.md
  help/include/mobile-all-streams-view.md
  static/images/help/mobile-plus-icon.svg
Labels: size: M, integration review

#25922 compose: Add functionality for audio call.
  web/src/compose.js
  web/src/message_edit.js
  web/src/server_events_dispatch.js
  web/templates/compose_control_buttons.hbs
  web/tests/compose_video.test.js
Labels: area: integrations, area: compose, priority: high, size: XL, new feature, integration review

#26048 user groups: Fix race conditions in user group membership changes
  .github/workflows/zulip-ci.yml
  tools/linter_lib/custom_check.py
  zerver/actions/user_groups.py
  zerver/lib/test_classes.py
  zerver/lib/test_helpers.py
  zerver/lib/user_groups.py
  zerver/tests/test_events.py
  zerver/tests/test_user_groups.py
  zerver/transaction_tests/test_user_groups.py
  zerver/views/development/user_groups.py
  zerver/views/user_groups.py
  zproject/dev_urls.py
Labels: size: XL, integration review

#26572 compose: Render Mac Cmd button and Return at compose bottom.
  web/src/ui_init.js
Labels: area: compose, size: XS, backport candidate, integration review

#26591 nginx: Do not forward X-amz-cf-id header to S3.
  puppet/zulip/files/nginx/zulip-include-frontend/uploads-internal.conf
Labels: backport candidate

#26590 api-docs: Fix documentation of `unread_msgs` object in `POST /register` response.
  zerver/openapi/zulip.yaml
Labels: area: documentation (api and integrations), api docs review

#26302 docs: Update help center links to "Edit a message" and "Delete a message".
  templates/corporate/features.html
  templates/corporate/for/business.html
  templates/corporate/for/events.html
  templates/corporate/for/open-source.html
  templates/corporate/for/research.html
  web/src/message_edit.js
  web/templates/settings/organization_permissions_admin.hbs
  zerver/openapi/zulip.yaml
Labels: size: S, integration review

#26588 compose: Add support for Zoom audio call
  api_docs/changelog.md
  version.py
  web/src/compose.js
  web/tests/compose_video.test.js
  zerver/tests/test_create_video_call.py
  zerver/views/video_calls.py
Labels: size: L

#26595 compose: Verify request payload in Zoom meeting creation test
  zerver/tests/test_create_video_call.py
Labels: size: S

#26596 api-changelog: Update feature level 119 entry for clarity.
  api_docs/changelog.md
Labels: area: documentation (api and integrations), api docs review

#26602 corporate: We have switched to DMs, from PMs.
  templates/corporate/development-community.md
Labels: size: XS

#26600 scroll: Correct element checks before activation.
  web/src/messages_overlay_ui.ts
Labels: area: keyboard UI, size: XS, integration review

#26468 left_sidebar: Fix the layout for filter names that are long.
  web/styles/left_sidebar.css
  web/templates/left_sidebar.hbs
Labels: area: left-sidebar, size: M, backport candidate, integration review

#26532 fenced_code: Enable code-highlighting without language markers.
  zerver/lib/markdown/fenced_code.py
  zerver/tests/fixtures/markdown_test_cases.json
Labels: area: compose, size: S, integration review

#26568 help: Add mobile instructions to "Unsubscribe from a stream".
  help/unsubscribe-from-a-stream.md
  static/images/help/mobile-check-icon.svg
Labels: size: L, integration review

#26614 push_notifications: Fix logging.exception misuse
  zerver/lib/push_notifications.py
Labels: size: XS

#26612 iptables: Stop logging on dropped packets.
  puppet/zulip_ops/files/iptables/header.v4
  puppet/zulip_ops/files/iptables/header.v6
  puppet/zulip_ops/files/iptables/trailer.v4
  puppet/zulip_ops/files/iptables/trailer.v6
Labels: size: S

#26556 compose: Prevent undesired link-pasting behavior.
  web/src/copy_and_paste.js
Labels: area: compose, size: M, integration review

#26611 api-docs: Fix endpoint formatting in API changelog and feature levels 11 and 12 changes/entries.
  api_docs/changelog.md
  zerver/openapi/zulip.yaml
Labels: area: documentation (api and integrations), size: L, api docs review

#26617 requirements: Downgrade orjson to 3.9.2.
  requirements/common.in
  requirements/dev.txt
  requirements/prod.txt
  version.py
Labels: size: XL

#26618 api-docs: Update feature level 205 changelog entry and changes notes.
  api_docs/changelog.md
  zerver/openapi/zulip.yaml
Labels: area: documentation (api and integrations), size: M, api docs review

#26610 icons: Fix the 'Unmute' topic icon.
  web/shared/icons/unmute-new.svg
Labels: size: XS, integration review

#26603 settings: Play button alignment.
  web/styles/settings.css
  web/templates/settings/notification_settings.hbs
Labels: area: notifications (other), area: settings (user), area: settings (admin/org), area: settings UI, size: M, maintainer review, QA needed

#26606 ui_report: Reuse `channel.xhr_error_message` function in `error` method.
  web/src/channel.ts
  web/src/message_edit.js
  web/src/ui_report.ts
  web/tests/channel.test.js
Labels: size: S

#26601 subscribe-unsubscribe: Improve error response for unexpected users.
  api_docs/changelog.md
  version.py
  zerver/openapi/zulip.yaml
  zerver/tests/test_subs.py
  zerver/views/streams.py
Labels: area: api, priority: high, size: XL
