Repository zulip/zulip, pull requests merged in 2023-07, with the labels that each got.

#26161 message_feed: Fix edited notice to appear for disabled edit_history.
  web/src/message_list_view.js
Labels: bug, area: message-editing, size: S, area: message feed UI, integration review

#25939 templates: Improve email confirmation page.
  templates/zerver/accounts_send_confirm.html
  web/styles/portico/portico_signin.css
  zerver/tests/test_invite.py
  zerver/tests/test_management_commands.py
  zerver/tests/test_signup.py
Labels: area: onboarding, priority: high, size: L, maintainer review, QA needed

#26154 eslint: Expand no-unused-vars check to all function parameters
  .eslintrc.json
  tools/check-openapi
  web/babel.config.js
  web/src/buddy_list.js
  web/src/compose_ui.js
  web/src/copy_and_paste.js
  web/src/flatpickr.js
  web/src/giphy.js
  web/src/hotkey.js
  web/src/info_overlay.js
  web/src/markdown.js
  web/src/message_fetch.js
  web/src/message_list_view.js
  web/src/messages_overlay_ui.js
  web/src/search_suggestion.js
  web/src/settings_toggle.js
  web/src/stream_edit.js
  web/src/stream_settings_ui.js
  web/src/todo_widget.js
  web/src/ui_init.js
  web/src/upload.js
  web/src/user_group_edit.js
  web/src/user_profile.js
  web/tests/activity.test.js
  web/tests/alert_words_ui.test.js
  web/tests/compose.test.js
  web/tests/compose_actions.test.js
  web/tests/compose_ui.test.js
  web/tests/example8.test.js
  web/tests/hashchange.test.js
  web/tests/lib/index.js
  web/tests/list_widget.test.js
  web/tests/narrow.test.js
  web/tests/notifications.test.js
  web/tests/recent_topics.test.js
  web/tests/rendered_markdown.test.js
  web/tests/settings_muted_users.test.js
  web/tests/settings_realm_domains.test.js
  web/tests/settings_user_topics.test.js
  web/tests/topic_generator.test.js
  web/tests/typing_events.test.js
  web/tests/upload.test.js
Labels: size: XL

#26165 test-backend: Enable single-threaded profiling when thread count is unspecified.
  tools/test-backend
Labels: size: S

#26042 Prep commits for `people.js` typescript migration.
  web/src/buddy_data.js
  web/src/compose_validate.js
  web/src/message_helper.js
  web/src/message_store.js
  web/src/peer_data.js
  web/src/people.js
  web/src/popovers.js
  web/src/presence.js
  web/src/rendered_markdown.js
  web/src/settings_bots.js
  web/src/settings_emoji.js
  web/src/settings_users.js
  web/src/stream_create_subscribers_data.js
  web/src/user_events.js
  web/src/user_group_create_members_data.js
  web/tests/buddy_data.test.js
  web/tests/compose_validate.test.js
  web/tests/message_store.test.js
  web/tests/peer_data.test.js
  web/tests/people.test.js
  web/tests/people_errors.test.js
  web/tests/presence.test.js
  web/tests/user_events.test.js
Labels: size: XL, integration review

#26168 theme: Change recipient bar color and theme in the same paint.
  web/src/click_handlers.js
  web/src/server_events_dispatch.js
  web/src/zcommand.js
  web/tests/dispatch.test.js
Labels: area: general UI, size: M, integration review

#26171 compose_pm_pill: Fix `compose_recipient` being mocked but not used.
  web/tests/compose_pm_pill.test.js
Labels: size: S, integration review

#26172 portico: Define variable for modal background color.
  web/styles/portico/portico.css
Labels: bug, area: portico, size: XS, integration review

#26175 blueslip: Simplify expectOne error message.
  web/src/setup.js
Labels: area: production, size: XS, integration review

#26176 message_edit: Suppress message controls popover in edit views.
  web/src/popover_menus.js
Labels: area: message-editing, size: XS, integration review

#26177 upload: Provide a default upload file name, rather than 500.
  zerver/lib/upload/base.py
  zerver/tests/test_upload.py
Labels: area: uploads, size: S, integration review

#25978 mention: Replace 'wildcards' with 'stream_wildcards'.
  templates/zerver/emails/missed_message.html
  templates/zerver/emails/missed_message.txt
  zerver/actions/message_edit.py
  zerver/actions/message_send.py
  zerver/lib/email_notifications.py
  zerver/lib/markdown/__init__.py
  zerver/lib/mention.py
  zerver/lib/message.py
  zerver/lib/notification_data.py
  zerver/lib/push_notifications.py
  zerver/lib/soft_deactivation.py
  zerver/lib/stream_subscription.py
  zerver/lib/test_classes.py
  zerver/migrations/0331_scheduledmessagenotificationemail.py
  zerver/migrations/0457_backfill_scheduledmessagenotificationemail_trigger.py
  zerver/models.py
  zerver/tests/test_email_notifications.py
  zerver/tests/test_event_queue.py
  zerver/tests/test_events.py
  zerver/tests/test_markdown.py
  zerver/tests/test_message_edit.py
  zerver/tests/test_message_edit_notifications.py
  zerver/tests/test_message_send.py
  zerver/tests/test_notification_data.py
  zerver/tests/test_push_notifications.py
  zerver/tests/test_soft_deactivation.py
  zerver/tests/test_users.py
  zerver/tornado/event_queue.py
Labels: size: XL, integration review, buddy review

#25981 unread_banner: Update all unread banners to an info/notice banner.
  web/templates/unread_banner/mark_as_read_turned_off_banner.hbs
Labels: size: XS, area: message feed UI, integration review

#26189 docs: Update SCIM doc to not mention add_scim_client.
  docs/production/scim.md
Labels: area: documentation (production), size: S, integration review

#25676 Migrate giphy popover to tippy.
  web/src/compose_tooltips.js
  web/src/giphy.js
  web/src/popovers.js
  web/styles/compose.css
  web/styles/popovers.css
  web/templates/compose_control_buttons.hbs
  web/templates/giphy_picker.hbs
Labels: size: XL, area: popovers, integration review

#26191 docs: Reference PostgreSQL version in "Restoring backups" section.
  docs/production/export-and-import.md
Labels: area: documentation (production), size: S, backport candidate, documentation review

#25888 tools: Copy "assets" subdirectory of bots to "static/generated/bots/".
  tools/setup/generate_zulip_bots_static_files.py
Labels: area: bots, size: M, maintainer review

#26192 stream_ui_updates: Check if sub/unsub button is rendered.
  web/src/stream_ui_updates.js
Labels: size: S, integration review

#25920 uploads: Improve file not found message.
  zerver/tests/test_upload.py
  zerver/views/upload.py
Labels: area: uploads, size: XS, integration review, maintainer review

#26203 popovers: Fix giphy being mocked but not used.
  web/tests/popovers.test.js
Labels: size: XS

#26178 test_classes: Do not necessary wrap test cases in a transaction.
  tools/test-backend
  zerver/lib/test_classes.py
  zerver/transaction_tests/__init__.py
Labels: size: XL, maintainer review

#26111 streams: Warn when archiving a notification stream.
  web/src/stream_edit.js
  web/styles/modal.css
  web/templates/confirm_dialog/confirm_deactivate_stream.hbs
Labels: area: stream settings, area: settings (admin/org), size: M, integration review

#26193 Polish UI for portico pages copy-codeblock button
  web/src/portico/help.js
  web/styles/portico/markdown.css
Labels: area: portico, size: M, integration review

#26090 compose: Show wildcard mentions according to policy.
  web/src/composebox_typeahead.js
  web/tests/composebox_typeahead.test.js
Labels: size: S, integration review, area: compose typeahead

#25925 tests: Improve automated tests for submessages.
  zerver/openapi/zulip.yaml
  zerver/tests/test_submessage.py
Labels: area: testing-coverage, area: documentation (api and integrations), size: M, area: widgets, integration review

#26117 upload: Append file markdown to textarea when placeholder is missing.
  web/src/compose_ui.js
  web/src/upload.js
  web/tests/upload.test.js
Labels: area: compose, area: uploads, size: S, integration review

#26208 markdown: Only attempt to adjust /wiki/File: paths on Wikipedia.
  zerver/lib/markdown/__init__.py
  zerver/tests/test_markdown.py
Labels: size: S

#26200 markdown-processor: Check for inline image classes as substrings.
  zerver/lib/markdown/__init__.py
  zerver/tests/test_markdown.py
Labels: bug, size: S, area: markdown (embeds/previews)

#26224 sentry-webhook: Revise documentation page to be clearer.
  zerver/webhooks/sentry/doc.md
Labels: area: documentation (api and integrations), size: L, documentation review

#26230 sentry: Reduce http timeout.
  zerver/views/sentry.py
Labels: size: XS

#26050 message_view_header: Fix bad rendering of stream links in description.
  web/e2e-tests/navigation.test.ts
  web/styles/zulip.css
  web/templates/message_view_header.hbs
Labels: bug, area: search, priority: high, size: S, integration review

#24983 webhooks: Ignore unknown events from updown.io.
  zerver/decorator.py
  zerver/lib/exceptions.py
  zerver/lib/response.py
  zerver/tests/test_decorators.py
  zerver/webhooks/github/tests.py
  zerver/webhooks/github/view.py
  zerver/webhooks/pagerduty/tests.py
  zerver/webhooks/updown/fixtures/unknown_event.json
  zerver/webhooks/updown/tests.py
Labels: bug, area: integrations, size: L, maintainer review

#26143 message-list-view: Update sticky header in rerender_messages.
  web/src/message_list_view.js
Labels: area: message view, size: S, maintainer review

#26242 docs: Mention the PostgreSQL upgrade in the release upgrade section.
  docs/production/upgrade.md
Labels: size: XS, backport candidate

#25883 message_feed: Improve edited/moved tooltip.
  web/src/message_list_tooltips.js
  web/src/message_list_view.js
  web/templates/edited_notice.hbs
  web/templates/message_edit_notice_tooltip.hbs
Labels: priority: high, size: L, area: message feed UI, integration review

#26218 tests: Use time_machine for testing scheduled message delivery.
  zerver/tests/test_scheduled_messages.py
Labels: size: XL, integration review

#26174 scheduled_messages: Update datatype from array to dictionary
  web/src/scheduled_messages.js
  web/src/scheduled_messages_overlay_ui.js
Labels: area: general UI, size: L, integration review

#25539 ts: Migrate people.js to TypeScript.
  web/src/page_params.ts
  web/src/people.ts
  web/src/types.ts
  web/tests/dispatch_subs.test.js
  web/tests/narrow.test.js
  web/tests/people.test.js
  web/tests/people_errors.test.js
Labels: size: XL, integration review, area: typescript migration

#26222 compose: Allow flatpickr to automatically choose the direction.
  web/src/compose.js
Labels: area: compose, size: XS, integration review

#26110 settings(user): Display Setting changed to Preferences.
  docs/documentation/helpcenter.md
  docs/testing/manual-testing.md
  help/change-the-time-format.md
  help/change-your-language.md
  help/configure-default-new-user-settings.md
  help/configure-default-view.md
  help/configure-emoticon-translations.md
  help/dark-theme.md
  help/emoji-and-emoticons.md
  help/emoji-reactions.md
  help/enable-full-width-display.md
  help/high-contrast-mode.md
  help/import-your-settings.md
  help/include/set-up-your-account.md
  help/include/sidebar_index.md
  help/manage-inactive-streams.md
  help/marking-messages-as-read.md
  help/review-your-settings.md
  help/star-a-message.md
  help/status-and-availability.md
  web/e2e-tests/settings.test.ts
  web/src/hashchange.js
  web/src/settings_display.js
  web/src/settings_sections.js
  web/templates/settings/user_display_settings.hbs
  web/templates/settings_overlay.hbs
  web/templates/unread_banner/mark_as_read_disabled_banner.hbs
  web/templates/unread_banner/mark_as_read_only_in_conversation_view.hbs
  web/tests/hash_util.test.js
  zerver/lib/markdown/help_settings_links.py
  zerver/lib/onboarding.py
  zerver/tests/test_docs.py
  zerver/tests/test_tutorial.py
Labels: area: settings (user), area: documentation (user), priority: high, size: XL, integration review

#25984 models: Convert deprecated index_together option to indexes
  analytics/migrations/0008_add_count_indexes.py
  analytics/models.py
  zerver/migrations/0268_add_userpresence_realm_timestamp_index.py
  zerver/migrations/0343_alter_useractivityinterval_index_together.py
  zerver/migrations/0443_userpresence_new_table_schema.py
  zerver/models.py
  zilencer/migrations/0016_remote_counts.py
  zilencer/migrations/0017_installationcount_indexes.py
  zilencer/models.py
Labels: size: XL, integration review

#26089 narrow: Hide inconsequential buttons while renaming topic.
  web/src/message_list.js
Labels: size: S, area: message feed UI, integration review

#25802 message_formatting: Improve the message formatting tips table.
  web/src/info_overlay.js
Labels: area: documentation (user), priority: high, size: L, integration review

#26240 Use List instead of QuerySet
  zerver/lib/soft_deactivation.py
  zerver/management/commands/soft_deactivate_users.py
Labels: size: S

#26241 onboarding: Backfill a month of messages for new users.
  zerver/actions/create_user.py
Labels: size: S

#26257 onboarding: Rename variable to cutoff_date.
  zerver/actions/create_user.py
Labels: size: XS

#26256 puppet: Upgrade Teleport to the 13.x series.
  scripts/setup/apt-repos/teleport/focal.list
  scripts/setup/apt-repos/teleport/jammy.list
Labels: size: XS, integration review

#26233 log-search: Prevent BrokenPipeError exceptions when run with `head`.
  scripts/log-search
Labels: size: S, integration review

#26260 message_grid: Refactor row grid for readability.
  web/styles/message_row.css
Labels: area: refactoring, area: message view, size: S, integration review

#26160 streams: Send stream creation events when subscribing guests.
  api_docs/changelog.md
  version.py
  zerver/actions/streams.py
  zerver/openapi/zulip.yaml
  zerver/tests/test_events.py
  zerver/tests/test_subs.py
Labels: size: L

#26066 integrations: Update documentation for Grafana Integration.
  zerver/webhooks/grafana/doc.md
Labels: area: integrations, size: S, documentation review

#25932 migration: Backfill extra_data_json for audit log entries.
  zerver/lib/test_classes.py
  zerver/migrations/0460_backfill_realmauditlog_extradata_to_json_field.py
  zerver/tests/test_migrations.py
  zilencer/migrations/0027_backfill_remote_realmauditlog_extradata_to_json_field.py
Labels: size: XL, integration review

#26265 me_message: Center first line with center of avatar.
  web/styles/message_row.css
  web/styles/zulip.css
Labels: area: message view, size: S, maintainer review

#26244 integrations: Replace use of 'subject' to 'topic'
  zerver/webhooks/airbrake/view.py
  zerver/webhooks/ansibletower/view.py
  zerver/webhooks/appveyor/view.py
  zerver/webhooks/basecamp/view.py
  zerver/webhooks/beanstalk/view.py
  zerver/webhooks/bitbucket/view.py
  zerver/webhooks/bitbucket2/view.py
  zerver/webhooks/bitbucket3/view.py
  zerver/webhooks/circleci/view.py
  zerver/webhooks/codeship/view.py
  zerver/webhooks/crashlytics/view.py
  zerver/webhooks/errbit/view.py
  zerver/webhooks/freshdesk/view.py
  zerver/webhooks/freshping/view.py
  zerver/webhooks/freshstatus/view.py
  zerver/webhooks/gci/view.py
  zerver/webhooks/github/view.py
  zerver/webhooks/gitlab/view.py
  zerver/webhooks/jira/view.py
  zerver/webhooks/json/view.py
  zerver/webhooks/lidarr/view.py
  zerver/webhooks/opbeat/view.py
  zerver/webhooks/pagerduty/view.py
  zerver/webhooks/pingdom/view.py
  zerver/webhooks/pivotal/view.py
  zerver/webhooks/radarr/view.py
  zerver/webhooks/rundeck/view.py
  zerver/webhooks/semaphore/view.py
  zerver/webhooks/sentry/view.py
  zerver/webhooks/slack/view.py
  zerver/webhooks/sonarr/view.py
  zerver/webhooks/transifex/view.py
  zerver/webhooks/trello/view/__init__.py
  zerver/webhooks/trello/view/board_actions.py
  zerver/webhooks/trello/view/card_actions.py
  zerver/webhooks/updown/view.py
  zerver/webhooks/uptimerobot/view.py
  zerver/webhooks/zabbix/view.py
  zerver/webhooks/zendesk/view.py
Labels: area: integrations, size: XL, integration review

#26216 ts: Migrate `peer_data.js` module to TypeScript.
  web/src/peer_data.ts
  web/tests/peer_data.test.js
Labels: size: L, integration review, area: typescript migration

#25873 search: Link messages in search results to near view.
  web/src/click_handlers.js
  web/src/hotkey.js
Labels: area: search, size: M, integration review

#26277 puppet: Remove unused zulip notification contact.
  puppet/zulip_ops/templates/nagios4/contacts.cfg.template.erb
Labels: size: XS

#26266 message_edit: Lock the Message row in check_update_message.
  zerver/actions/message_edit.py
Labels: size: S

#25948 ts: Convert `stream_settings_containers.js` to TypeScript.
  tools/test-js-with-node
  web/src/stream_settings_containers.js
  web/src/stream_settings_containers.ts
Labels: size: S, integration review, area: typescript migration

#26236 management: Add a reactivate-stream command.
  zerver/actions/streams.py
  zerver/management/commands/reactivate_stream.py
  zerver/tests/test_subs.py
Labels: size: XL, backport candidate, integration review

#26284 python: Remove unused arguments for translated format strings
  corporate/views/billing_page.py
  zerver/forms.py
Labels: size: S

#26282 python: Convert translated positional {} fields to {named} fields.
  analytics/views/stats.py
  corporate/lib/stripe.py
  tools/semgrep.yml
  zerver/actions/default_streams.py
  zerver/actions/message_flags.py
  zerver/actions/typing.py
  zerver/actions/user_groups.py
  zerver/forms.py
  zerver/lib/addressee.py
  zerver/lib/emoji.py
  zerver/lib/narrow.py
  zerver/lib/push_notifications.py
  zerver/lib/remote_server.py
  zerver/lib/request.py
  zerver/lib/streams.py
  zerver/lib/string_validation.py
  zerver/lib/user_groups.py
  zerver/lib/users.py
  zerver/lib/validator.py
  zerver/lib/webhooks/common.py
  zerver/lib/zcommand.py
  zerver/models.py
  zerver/views/events_register.py
  zerver/views/hotspots.py
  zerver/views/invite.py
  zerver/views/message_fetch.py
  zerver/views/message_flags.py
  zerver/views/presence.py
  zerver/views/realm.py
  zerver/views/realm_domains.py
  zerver/views/realm_emoji.py
  zerver/views/realm_icon.py
  zerver/views/realm_logo.py
  zerver/views/streams.py
  zerver/views/upload.py
  zerver/views/user_groups.py
  zerver/views/user_settings.py
  zerver/views/users.py
  zerver/webhooks/wordpress/view.py
  zilencer/views.py
Labels: size: XL, integration review

#26288 utils: Remove make_safe_digest wrapper
  docs/subsystems/caching.md
  zerver/data_import/rocketchat.py
  zerver/lib/avatar_hash.py
  zerver/lib/cache.py
  zerver/lib/utils.py
  zerver/migrations/0032_verify_all_medium_avatar_images.py
  zerver/models.py
Labels: size: L, integration review

#26289 wal-g: Support alternate S3 storage classes.
  docs/production/deployment.md
  puppet/zulip/files/postgresql/env-wal-g
Labels: size: S

#26296 recent_topics: Fix clear search button misaligned.
  web/styles/recent_topics.css
Labels: size: XS, integration review

#26227 upgrade: Check PostgreSQL versions after venv setup.
  scripts/lib/check-database-compatibility
  scripts/lib/upgrade-zulip-stage-2
Labels: size: XL, backport candidate, integration review

#26300 wal-g: Use "start_time" field, not "time" which is S3 modified-at.
  puppet/zulip/files/postgresql/wal-g-exporter
Labels: size: XS, integration review

#26290 uploads: Allow uploads to set storage class.
  docs/production/upload-backends.md
  zerver/lib/transfer.py
  zerver/lib/upload/s3.py
  zproject/default_settings.py
  zproject/prod_settings_template.py
Labels: size: L, integration review

#26261 puppet: Allow access to smokescreen metrics on CZO.
  puppet/zulip_ops/manifests/profile/chat_zulip_org.pp
Labels: size: XS, integration review

#26309 api-changelog: Add entry for feature level 193 updates.
  api_docs/changelog.md
  zerver/openapi/zulip.yaml
Labels: area: documentation (api and integrations), size: L, api docs review

#26293 poll_data: Revert to using "canned" instead of -1.
  web/shared/src/poll_data.ts
Labels: bug, size: S, area: widgets, integration review

#26310 nginx: Remove gzip_disable "msie6"
  puppet/zulip/templates/nginx.conf.template.erb
Labels: size: XS

#26020 narrow: Support string and integer encoding "id" operator.
  api_docs/changelog.md
  api_docs/construct-narrow.md
  version.py
  web/src/message_fetch.js
  zerver/lib/narrow.py
  zerver/tests/test_message_fetch.py
Labels: area: api, area: documentation (api and integrations), size: L, api docs review

#26311 [7.x] error_notify: Remove custom email error reporting handler
  docs/production/troubleshooting.md
  docs/subsystems/logging.md
  puppet/zulip/manifests/app_frontend_base.pp
  puppet/zulip_ops/files/nagios4/conf.d/services.cfg
  scripts/lib/check_rabbitmq_queue.py
  tools/test-backend
  zerver/filters.py
  zerver/lib/error_notify.py
  zerver/lib/logging_util.py
  zerver/logging_handlers.py
  zerver/tests/test_logging_handlers.py
  zerver/worker/queue_processors.py
  zproject/computed_settings.py
  zproject/test_extra_settings.py
Labels: size: XL

#26275 realm-settings: Update default_code_block_language for default empty string.
  api_docs/changelog.md
  version.py
  web/src/composebox_typeahead.js
  zerver/lib/event_schema.py
  zerver/migrations/0461_alter_realm_default_code_block_language.py
  zerver/models.py
  zerver/openapi/zulip.yaml
  zerver/tests/test_markdown.py
  zerver/views/realm.py
Labels: area: api, area: documentation (api and integrations), area: settings (admin/org), size: L, api docs review

#26312 message view: Don't mark message as read in mentions view.
  web/src/filter.js
  web/tests/filter.test.js
Labels: area: message view, size: S

#26316 gitea: Support missing head/base refs.
  zerver/webhooks/gitea/view.py
Labels: size: S

#26320 topic generator test: Use strings for stream name instead of numbers.
  web/tests/topic_generator.test.js
Labels: size: S

#26318 narrow: Add hotkey trigger for navigation to new topic/direct message.
  web/src/hotkey.js
  web/src/narrow.js
Labels: area: keyboard UI, area: misc, size: S, integration review

#26314 migrations: Fix migration to set default of can_mention_group.
  zerver/migrations/0455_set_default_for_can_mention_group.py
Labels: size: L

#26325 ruff: Fix UP032 Use f-string instead of `format` call
  tools/droplets/create.py
  zerver/webhooks/json/tests.py
Labels: size: M

#26327 ruff: Fix PLR1714 Consider merging multiple comparisons
  analytics/views/user_activity.py
  scripts/zulip-puppet-apply
  tools/lib/sanity_check.py
  tools/test-backend
  zerver/actions/create_realm.py
  zerver/actions/custom_profile_fields.py
  zerver/lib/logging_util.py
  zerver/lib/onboarding.py
  zerver/migrations/0460_backfill_realmauditlog_extradata_to_json_field.py
  zerver/models.py
  zerver/views/custom_profile_fields.py
  zerver/webhooks/clubhouse/view.py
  zerver/webhooks/github/view.py
  zerver/webhooks/gitlab/view.py
  zerver/webhooks/pagerduty/view.py
  zerver/webhooks/raygun/view.py
  zerver/webhooks/sonarr/view.py
  zerver/webhooks/wordpress/view.py
  zilencer/migrations/0027_backfill_remote_realmauditlog_extradata_to_json_field.py
Labels: size: L

#26285 search: Rename search_arrows to search_input.
  web/styles/dark_theme.css
  web/styles/search.css
  web/templates/navbar.hbs
Labels: area: search, size: S, integration review

#26332 ruff: Fix SIM118 Use `k not in d` instead of `k not in d.keys()`
  zerver/lib/event_schema.py
  zerver/lib/external_accounts.py
  zerver/openapi/openapi.py
  zerver/webhooks/opbeat/view.py
Labels: size: S

#26334 open-source: Convert deleted tweet into a quote.
  templates/corporate/for/communities.md
  templates/corporate/for/open-source.html
Labels: size: S

#26339 notifications: Remove the stray notification trigger strings.
  zerver/actions/message_send.py
  zerver/lib/email_notifications.py
  zerver/lib/notification_data.py
  zerver/lib/soft_deactivation.py
  zerver/tests/test_email_notifications.py
  zerver/tests/test_message_edit_notifications.py
  zerver/tests/test_notification_data.py
  zerver/tests/test_outgoing_webhook_interfaces.py
  zerver/tests/test_push_notifications.py
  zerver/tests/test_service_bot_system.py
Labels: size: XL, mentor review

#26340 styles: Remove Firefox override for dropdown appearance
  web/images/dropdown.png
  web/styles/settings.css
Labels: size: S

#26206 popup: Add tippy tip that says "Copied" when you copy/paste stuff fro…
  web/src/settings_bots.js
  web/src/stream_edit.js
  web/tests/settings_bots.test.js
Labels: good first issue, area: settings UI, size: M, integration review

#26341 dark_theme: Remove Firefox override for dropdown appearance
  web/styles/dark_theme.css
Labels: size: S

#26344 ts: Migrate `huddle_data.js` to TypeScript.
  web/src/huddle_data.ts
Labels: size: S, integration review, area: typescript migration

#26342 grid: Remove unnecessary mobile-scale padding.
  web/styles/zulip.css
Labels: bug, area: message feed display, integration review

#26272 ts: Migrate `vdom.js` to TypeScript
  web/src/vdom.ts
Labels: size: M, integration review

#26155 message feed: Change color of zulip logo at top of feed.
  web/src/message_feed_loading.ts
  web/styles/dark_theme.css
  web/styles/zulip.css
Labels: size: M, redesign, integration review

#25787 message view: Redesign the more-less message interaction.
  docs/testing/manual-testing.md
  help/collapse-a-message.md
  web/src/click_handlers.js
  web/src/condense.js
  web/src/resize.js
  web/styles/zulip.css
  web/templates/message_body.hbs
Labels: size: L, area: message feed UI, redesign, integration review

#26184 compose: Don't select compose input field after focus.
  web/src/compose_ui.js
Labels: area: compose, accessibility, priority: high, size: XS, integration review

#26352 missed-message: Add a try-catch to prevent killing background thread.
  zerver/worker/queue_processors.py
Labels: size: XL

#26348 replace the variable `$http_host` to `$host` in nginx conf example
  docs/production/deployment.md
  scripts/lib/sharding.py
Labels: size: XS

#26358 print: Add print styles targeted at topics.
  web/src/bundles/app.ts
  web/styles/print.css
Labels: area: message view, size: L, area: message feed display, maintainer review

#26324 build-pgroonga: Upgrade PGroonga from 3.0.3 to 3.1.0
  scripts/lib/build-pgroonga
  scripts/setup/apt-repos/zulip/apache-arrow-keyring.gpg
  scripts/setup/apt-repos/zulip/custom.sh
  tools/ci/build-docker-images
Labels: size: S, integration review

#26359 i18n: Update translation data from Transifex.
  locale/be/LC_MESSAGES/django.po
  locale/be/translations.json
  locale/bqi/LC_MESSAGES/django.po
  locale/bqi/translations.json
  locale/cs/LC_MESSAGES/django.po
  locale/da/LC_MESSAGES/django.po
  locale/da/translations.json
  locale/de/LC_MESSAGES/django.po
  locale/en_GB/LC_MESSAGES/django.po
  locale/en_GB/translations.json
  locale/eo/LC_MESSAGES/django.po
  locale/eo/translations.json
  locale/fr/LC_MESSAGES/django.po
  locale/gl/LC_MESSAGES/django.po
  locale/gl/translations.json
  locale/ja/translations.json
  locale/lv/LC_MESSAGES/django.po
  locale/lv/translations.json
  locale/ml/LC_MESSAGES/django.po
  locale/mobile_info.json
  locale/no/LC_MESSAGES/django.po
  locale/no/translations.json
  locale/pt_BR/LC_MESSAGES/django.po
  locale/pt_BR/translations.json
  locale/pt_PT/LC_MESSAGES/django.po
  locale/pt_PT/translations.json
  locale/si/LC_MESSAGES/django.po
  locale/sr/LC_MESSAGES/django.po
  locale/ta/LC_MESSAGES/django.po
  locale/tr/LC_MESSAGES/django.po
  locale/tr/translations.json
Labels: size: XL

#26356 compose: Return focus to DM input after pill selection.
  web/src/compose_pm_pill.js
Labels: area: compose, size: XS, integration review

#26370 settings_profile_fields: Simplify convoluted sort algorithm to max
  web/src/settings_profile_fields.js
Labels: size: S

#26388 runtornado: Fix COM818 Trailing comma on bare tuple prohibited
  pyproject.toml
  zerver/management/commands/runtornado.py
Labels: size: S
