Repository zulip/zulip, pull requests merged in 2023-03, with the labels that each got.

#24522 demo-orgs: Fix link to help center in Welcome bot message.
  zerver/lib/onboarding.py
Labels: size: XS, integration review

#24495 portico: Fix portico footer broken on mobile widths.
  web/styles/portico/portico.css
Labels: size: XS, integration review

#24511 poll_widget: Make the poll-vote button the top layer.
  web/styles/widgets.css
Labels: bug, priority: high, size: XS, area: widgets, integration review

#24520 templates: Convert config errors to HTML.
  templates/zerver/apple-error.md
  templates/zerver/authentication_backends/apple-error.html
  templates/zerver/authentication_backends/dev-not-supported-error.html
  templates/zerver/authentication_backends/github-error.html
  templates/zerver/authentication_backends/gitlab-error.html
  templates/zerver/authentication_backends/google-error.html
  templates/zerver/config_error.html
  templates/zerver/dev-not-supported-error.md
  templates/zerver/github-error.md
  templates/zerver/gitlab-error.md
  templates/zerver/google-error.md
  zerver/views/auth.py
Labels: area: markdown, size: XL, integration review

#22213 Add notes on how archive cleaning works and add cronjob to run delete_old_unclaimed_attachments
  puppet/zulip/files/cron.d/delete-old-unclaimed-attachments
  puppet/zulip/manifests/app_frontend_once.pp
Labels: size: S, integration review

#24532 api-docs: Fix changelog formatting for feature level 166.
  api_docs/changelog.md
Labels: size: S

#24524 invites: Limit invites per day as a function of current users.
  zerver/actions/invites.py
Labels: size: L

#24514 Fix: Long stream names abbreviated too early in stream settings.
  web/styles/subscriptions.css
Labels: bug, good first issue, area: stream settings, size: S, integration review

#24494 popovers: Close user popovers on button click.
  web/src/settings_users.js
Labels: size: S

#24328 settings: Drop less important columns from settings on narrow screen.
  web/styles/settings.css
  web/templates/muted_topic_ui_row.hbs
  web/templates/settings/admin_user_list.hbs
  web/templates/settings/bot_list_admin.hbs
  web/templates/settings/muted_topics_settings.hbs
Labels: area: settings (user), size: S, integration review

#24459 tippy: Add more delay to compose and message control button tooltips.
  web/src/tippyjs.js
Labels: size: M, integration review

#24493 streams: Allow sorting of stream members.
  web/src/settings_users.js
  web/src/stream_create_subscribers.js
  web/src/stream_edit_subscribers.js
  web/templates/stream_settings/new_stream_users.hbs
  web/templates/stream_settings/stream_members.hbs
Labels: area: stream settings, area: settings (admin/org), size: M, integration review

#24540 help: Expand introduction on /help/support-zulip-project.
  help/support-zulip-project.md
Labels: size: M, integration review

#24542 muted_topics_ui: Rename mute_topic parameter to fix shadowing bug
  web/src/muted_topics_ui.js
Labels: size: XS, integration review

#24546 server_events_dispatch: Update bots list only if needed.
  web/src/people.js
  web/src/server_events_dispatch.js
  web/tests/dispatch.test.js
  web/tests/example4.test.js
  web/tests/lib/events.js
Labels: size: L

#24548 docs: Fix update correct path for stats file
  docs/subsystems/analytics.md
Labels: size: S

#24496 integrations: Fix error on Asana integration documentation.
  static/images/integrations/asana/001.png
  static/images/integrations/asana/002.png
  static/images/integrations/asana/003.png
  static/images/integrations/asana/004.png
  static/images/integrations/asana/005.png
  static/images/integrations/asana/006.png
  static/images/integrations/asana/007.png
  static/images/integrations/asana/008.png
  templates/zerver/integrations/asana.md
  zerver/webhooks/zapier/doc.md
Labels: size: S

#24556 user groups: Enabled sorting of subscribers.
  web/src/user_group_create_members.js
  web/src/user_group_edit_members.js
  web/templates/user_group_settings/new_user_group_users.hbs
  web/templates/user_group_settings/user_group_members.hbs
Labels: size: M

#24492 streams: Align stream type icons in "Archive stream" modal.
  web/src/stream_edit.js
  web/styles/app_components.css
  web/styles/subscriptions.css
  web/templates/confirm_dialog/confirm_deactivate_stream.hbs
  web/templates/inline_decorated_stream_name.hbs
Labels: size: M, integration review

#24555 popovers: Remove background when hovering Github username.
  web/styles/popovers.css
Labels: size: XS

#24566 templates: Add `rendered_markdown` class to confirm emoji warning.
  web/templates/confirm_dialog/confirm_emoji_settings_warning.hbs
Labels: size: S

#24565 css: Move `pre code` to be in `rendered_markdown` class block.
  web/styles/rendered_markdown.css
Labels: size: S

#24527 help: Add open link icon in "Add a custom linkifier".
  help/add-a-custom-linkifier.md
Labels: size: XS, integration review

#24576 docs: Move homepage link to TOC tree
  docs/_static/theme_overrides.css
  docs/_templates/layout.html
  docs/index.md
  tools/check-templates
Labels: size: M

#24578 docs: Add missing link to outreach TOC
  docs/index.md
Labels: size: XS

#24591 docs: Remove bad advice about pinning versions
  docs/subsystems/html-css.md
Labels: size: S

#24232 gear_menu: Update 'Support Zulip' link. [ Dont merge before #ac63c79 ]
  web/templates/gear_menu.hbs
Labels: priority: high, size: XS, integration review

#24595 tests: Remove ignored `realm_str` parameter from message send test.
  zerver/tests/test_message_send.py
Labels: size: XS

#24596 puppeteer: Fix small logging copy and paste error in `admin.test.ts`.
  web/e2e-tests/admin.test.ts
Labels: size: XS

#24547 ts: Convert linkifiers.js to TypeScript.
  web/src/linkifiers.ts
Labels: size: S

#24472 message feed ui: added new approach to mark message as unread
  web/src/message_live_update.js
  web/src/unread_ops.js
Labels: size: S

#24600 tests: Set LOCAL_AVATARS_DIR / LOCAL_FILES_DIR in tests.
  zproject/test_extra_settings.py
Labels: size: XS

#24385 message_feed: Hide compose banner when unsubbing from stream.
  web/src/stream_events.js
  web/tests/stream_events.test.js
Labels: size: S

#24579 popovers: Make primary action button in modals look disabled in light theme.
  web/styles/modal.css
Labels: bug, priority: high, size: XS, area: popovers, integration review

#24609 help: Add context/motivation to Support the Zulip project help page.
  help/support-zulip-project.md
Labels: size: M, integration review

#24398 help: Document "Who can unsubscribe others from this stream?" setting.
  help/add-or-remove-users-from-a-stream.md
  help/create-a-stream.md
  help/stream-permissions.md
Labels: area: documentation (user), size: M, integration review

#19975 help: Add article for supported browsers
  help/include/set-up-your-account.md
  help/include/sidebar_index.md
  help/supported-browsers.md
  templates/corporate/apps.html
  templates/zerver/unsupported_browser.html
Labels: area: documentation (user), size: M, difficult, integration review

#20928 api_docs: Add page documenting HTTP headers in the api docs.
  api_docs/http-headers.md
  api_docs/rest-error-handling.md
  api_docs/rest.md
  api_docs/sidebar_index.md
  zerver/openapi/zulip.yaml
Labels: size: XL, integration review

#24616 Sentry portico
  web/src/sentry.ts
  zerver/context_processors.py
Labels: size: M

#24617 test_classes: Provide path to test-backend for ease of copy/paste.
  zerver/lib/test_classes.py
Labels: size: XS

#24491 openapi: Add links to email_address_visibility help documentation.
  zerver/openapi/zulip.yaml
Labels: size: S

#24590 stream_settings: Fix bug save changes button show on screen width< 575px.
  web/styles/subscriptions.css
Labels: bug, area: stream settings, size: XS

#24611 hashchange: Ensure no duplicate entries in browser history.
  web/src/hashchange.js
Labels: bug, area: keyboard UI, size: XS

#24610 docs: Update documentation for tips when writing pull request comments.
  docs/contributing/reviewable-prs.md
  docs/git/pull-requests.md
  docs/images/zulip-open-pr.png
Labels: size: XL

#24437 recent_senders: Fix twice sent user ids in PM to self case.
  web/src/people.js
  web/src/recent_senders.js
  web/tests/recent_senders.test.js
Labels: size: M, backport candidate, integration review

#24419 css: Fix search bar width in right sidebar.
  web/styles/right_sidebar.css
Labels: size: S

#24602 drafts: Space draft message content from restore draft button by 5px.
  web/styles/drafts.css
Labels: size: XS, integration review

#24471 google_analytics: Track realm registration separately from user signup.
  templates/confirmation/confirm_preregistrationuser.html
  zerver/tests/test_management_commands.py
  zerver/tests/test_signup.py
  zerver/views/registration.py
  zproject/urls.py
Labels: size: M, integration review

#24607 landing-pages: Add section on chat.zulip.org custom linkifiers.
  templates/corporate/development-community.md
Labels: size: S, integration review

#24447 help: Add “Configure how links open” page.
  help/configure-how-links-open.md
  help/include/sidebar_index.md
Labels: size: S, integration review

#24530 settings : Refactor "Show API key" modal for improved wording.
  api_docs/api-keys.md
  web/templates/settings/api_key_modal.hbs
Labels: good first issue, area: settings UI, size: S, area: popovers, integration review

#24627 zulip_tools: Improve error for `run` subprocess killed by signal
  scripts/lib/zulip_tools.py
Labels: size: S

#24628 overlays: Fix dependency cycle between popover.js and overlays.js.
  web/src/overlays.js
  web/src/popovers.js
  web/src/ui_init.js
Labels: size: M

#24632 ci: Run generate-failure-message from the right path
  .github/workflows/production-suite.yml
Labels: size: XS

#24633 help: Move "Configure how links open" to the Apps section.
  help/configure-how-links-open.md
  help/include/sidebar_index.md
Labels: size: XS, integration review

#24509 help: Add instructions for viewing status.
  help/include/mobile-view-user-profile-tip.md
  help/status-and-availability.md
  help/view-someones-profile.md
Labels: size: M, integration review

#24636 help: Tweak documentation on migrating from other chat tools.
  help/include/migrating-from-other-chat-tools.md
Labels: area: documentation (user), size: S, integration review

#24562 bots: Improve bots permission banner.
  web/src/admin.js
  web/src/settings.js
  web/src/settings_bots.js
  web/templates/settings/bot_list_admin.hbs
  web/templates/settings/bot_settings.hbs
  web/templates/settings/bot_settings_tip.hbs
Labels: good first issue, area: bots, size: L, integration review

#24630 ts: Convert css_variables.js to TypeScript.
  tools/test-js-with-node
  web/src/css_variables.js
  web/src/css_variables.ts
Labels: size: L

#23957 frontend: Add stream symbol to unsubscribe confirmation modal
  web/src/stream_edit_subscribers.js
  web/src/stream_settings_ui.js
Labels: good first issue, size: S, area: popovers, integration review

#24629 UserTopic: Refactor 'do_set_user_topic_visibility_policy'.
  zerver/actions/user_topics.py
  zerver/lib/user_topics.py
Labels: size: L, integration review

#24638 styles: Fix layout shifting for highlighted help sidebar link
  web/styles/portico/portico.css
Labels: size: S, integration review

#24648 docs: Change extension from .js to .ts for some filenames.
  docs/subsystems/html-css.md
  docs/subsystems/logging.md
  docs/subsystems/typing-indicators.md
  docs/translating/internationalization.md
  web/tests/example1.test.js
  web/tests/i18n.test.js
Labels: size: S

#24662 create-user: Remove notifications sent to admin realm.
  zerver/actions/create_user.py
  zerver/tests/test_new_users.py
  zerver/tests/test_signup.py
  zerver/tests/test_users.py
Labels: size: L

#24655 ts: Convert portico/tabbed-instructions.js to TypeScript.
  web/src/portico/tabbed-instructions.ts
Labels: size: S, integration review

#24674 help: Update broken link in `import from slack`.
  help/import-from-slack.md
Labels: size: XS

#24675 docs: Update mobile/desktop apps' compatability threshold to 4.0, from 3.0
  docs/overview/release-lifecycle.md
Labels: size: XS

#24497 Fix width of select elements in settings.
  web/styles/app_components.css
  web/styles/settings.css
  web/styles/subscriptions.css
Labels: size: L, integration review

#24557 reactions: Prevent multiple simultaneous requests for reaction update.
  web/src/reactions.js
  web/tests/reactions.test.js
Labels: size: M, integration review

#24266 keyboard_ui: Add a new keyboard shortcut '='
  web/src/hotkey.js
  web/tests/hotkey.test.js
Labels: area: keyboard UI, area: emoji, priority: high, size: S, UX, integration review

#24642 popovers: Add a confirmation modal for marking all messages as read.
  web/src/stream_popover.js
  web/src/unread_ops.js
  web/templates/confirm_dialog/confirm_mark_all_as_read.hbs
Labels: size: S, area: popovers, integration review

#24693 API changelog: Fix an omission and clarify individual endpoint documentation is more detailed
  api_docs/changelog.md
Labels: size: S

#24665 puppet: Switch teleport to running under systemd, not supervisord.
  puppet/zulip_ops/files/supervisor/conf.d/teleport_db.conf
  puppet/zulip_ops/files/supervisor/conf.d/teleport_node.conf
  puppet/zulip_ops/files/supervisor/conf.d/teleport_server.conf
  puppet/zulip_ops/manifests/profile/teleport.pp
  puppet/zulip_ops/manifests/teleport/base.pp
  puppet/zulip_ops/manifests/teleport/db.pp
  puppet/zulip_ops/manifests/teleport/node.pp
  puppet/zulip_ops/manifests/teleport/part.pp
  puppet/zulip_ops/templates/teleport.service.template.erb
Labels: size: XL

#24702 help: Improve "Deactivate your account" help page.
  help/deactivate-your-account.md
  zerver/tests/test_middleware.py
Labels: size: L, integration review

#24708 integrations: Add a link to GitHub webhooks documentation.
  zerver/webhooks/github/doc.md
Labels: size: XS

#24713 templates: Fix &nbsp; syntax
  web/templates/message_reaction.hbs
  web/templates/set_status_overlay.hbs
  web/templates/status_emoji.hbs
  web/templates/status_emoji_selector.hbs
  web/templates/user_info_popover_content.hbs
Labels: size: S

#24714 help: Update 'Include organization name in subject line' documentation.
  help/email-notifications.md
Labels: area: documentation (user), size: S, integration review

#24690 UserTopic: Don't raise errors on duplicate requests.
  api_docs/changelog.md
  zerver/actions/message_edit.py
  zerver/actions/user_topics.py
  zerver/lib/user_topics.py
  zerver/openapi/zulip.yaml
  zerver/tests/test_message_edit.py
  zerver/tests/test_user_topics.py
Labels: size: XL

#24673 integration: Remove branch names on pull request events.
  zerver/webhooks/github/tests.py
  zerver/webhooks/github/view.py
Labels: area: integrations, priority: high, size: S

#24727 install-node: Upgrade Node.js from 18.14.1 to 18.15.0
  scripts/lib/install-node
  version.py
  web/tests/drafts.test.js
  web/tests/rendered_markdown.test.js
  web/tests/timerender.test.js
Labels: size: L

#24736 message_row: Fix rewrapping message lines after receiving ack.
  web/styles/message_row.css
  web/templates/message_body.hbs
Labels: size: S

#24732 puppet: Enable sentry hooks for production and staging.
  puppet/zulip_ops/manifests/app_frontend.pp
Labels: size: XS

#24728 cache: Use QuerySetAny for isinstance check.
  requirements/dev.txt
  requirements/prod.txt
  version.py
  zerver/lib/cache.py
Labels: size: S

#24639 markdown: Fix use of pure_markdown for non-pure markdown rendering.
  templates/zerver/documentation_main.html
  zerver/lib/markdown/fenced_code.py
  zerver/lib/templates.py
  zerver/tests/test_email_notifications.py
Labels: size: L

#24745 web: Remove inappropriate $ prefix from HTML variables
  web/src/compose_validate.js
  web/src/narrow_error.js
  web/src/upload.js
Labels: size: S

#24747 install-transifex-cli: Upgrade Transifex CLI from 1.6.4 to 1.6.5
  tools/setup/install-transifex-cli
  version.py
Labels: size: S

#24755 help: Fix import-self-hosted-server-tips indentation
  help/import-from-gitter.md
  help/import-from-mattermost.md
  help/import-from-rocketchat.md
  help/import-from-slack.md
  help/include/import-self-hosted-server-tips.md
Labels: size: S

#24746 integrations_dev_panel: Fix unsafe use of innerHTML
  web/src/portico/integrations_dev_panel.js
Labels: size: S, integration review

#24754 bootstrap: Remove CSS hacks for IE
  web/third/bootstrap-tooltip/tooltip.css
  web/third/bootstrap/css/bootstrap-btn.css
  web/third/bootstrap/css/bootstrap.css
Labels: size: L, integration review

#24770 Move QOS configuration into connection, not queue verification.
  zerver/lib/queue.py
Labels: size: XS

#24769 docs: Change python code snippet to the existing one.
  api_docs/incoming-webhooks-walkthrough.md
Labels: size: XS

#24752 docs: Add tip about cross-linking between GitHub and dev community.
  docs/contributing/reviewable-prs.md
Labels: size: S, integration review

#24749 webhooks: Handle explicit null context_line in Sentry.
  zerver/webhooks/sentry/view.py
Labels: size: S

#24771 invite: Be more fair about the no-messages-sent warning flag.
  zerver/actions/invites.py
Labels: size: S

#24734 styles: Extend help sidebar heading links like list links
  web/styles/portico/portico.css
Labels: size: S, integration review

#24733 integration: Add branch names to Azure Devops merged PR event.
  zerver/webhooks/azuredevops/tests.py
  zerver/webhooks/azuredevops/view.py
Labels: size: S

#24775 narrow: Use dict to map operator to `by_*` method in `NarrowBuilder`.
  zerver/lib/narrow.py
Labels: size: S

#23627 compose: Add hint text to topic typeahead dropdown
  web/src/composebox_typeahead.js
  web/templates/topic_typeahead_hint.hbs
Labels: area: compose, priority: high, size: XS, UI experiment

#24667 docs: Update "How it works" section in writing REST API documentation.
  docs/documentation/api.md
Labels: area: documentation (api and integrations), size: XL

#24774 portico: Use jQuery better to select the first integration.
  web/src/portico/integrations.js
Labels: size: S

#24570 narrow_banner: Display title only for empty is-operator narrow search.
  web/src/narrow_banner.js
  web/tests/narrow.test.js
Labels: size: M, integration review

#24800 management: Add a command to send initial welcome bot messages.
  zerver/management/commands/send_welcome_bot_message.py
Labels: size: S

#24801 README: Update Ruff badge
  README.md
Labels: size: XS

#24785 test_classes: Don’t spew BAN_CONSOLE_OUTPUT errors over failed tests
  zerver/lib/test_classes.py
Labels: size: XS

#24763 popovers: Fix tooltip partially hidden by recipient bar when selected.
  web/styles/zulip.css
Labels: size: S

#24519 message_list: Fix duplicate date headers at the top of message feed.
  web/src/message_list_view.js
  web/styles/zulip.css
  web/templates/recipient_row.hbs
Labels: size: M, chat.zulip.org review

#24807 help: Clarify alert words documentation.
  help/dm-mention-alert-notifications.md
  help/search-for-messages.md
Labels: size: S, integration review

#24798 create_realm: Tag import string for translation.
  templates/zerver/create_realm.html
Labels: size: XS

#24809 node_cache: Work around pnpm install issue in Docker for Mac
  scripts/lib/node_cache.py
Labels: size: S

#24817 log-search: Support HTTP method limits.
  scripts/log-search
Labels: size: S

#24784 semgrep: Detect some unsafe uses of markupsafe.Markup
  analytics/views/activity_common.py
  analytics/views/installation_activity.py
  tools/semgrep.yml
  zerver/forms.py
  zerver/lib/upload/base.py
  zerver/views/auth.py
Labels: size: L, integration review

#24812 typeahead: Fix stream typeahead flashing before topic typeahead.
  web/third/bootstrap-typeahead/typeahead.js
Labels: size: XS

#24789 notifications: Handle exception when trying to play audio.
  web/src/notifications.js
  web/src/settings_notifications.js
  web/src/ui_util.ts
Labels: size: S

#24643 create-realm: Update notification message sent to admin realm.
  zerver/actions/create_realm.py
  zerver/tests/test_signup.py
Labels: size: L, integration review

#24837 puppet: Update dependencies.
  puppet/deps.yaml
  puppet/zulip/manifests/common.pp
Labels: size: L

#24631 help: Merge two similar sections in `marking messages as read`.
  help/marking-messages-as-read.md
Labels: size: S, integration review

#24840 integration: Modify branch names for Gitlab MR events.
  zerver/webhooks/gitlab/tests.py
  zerver/webhooks/gitlab/view.py
Labels: size: S

#24839 recent_topics_row: Remove unused dataset attributes from template
  web/src/recent_topics_ui.js
  web/templates/recent_topic_row.hbs
  web/tests/recent_topics.test.js
Labels: size: L

#24849 sentry: Drop HttpClientIntegration.
  web/src/sentry.ts
Labels: size: XS

#24848 emojiset: Promise reject calls want an error, not an event.
  web/src/emojisets.js
Labels: size: S

#24847 emoji: Remove parens and apostrophes from emoji names.
  tools/setup/emoji/emoji_names.py
  tools/setup/emoji/generate_emoji_names
Labels: size: S, integration review

#24846 puppet: Decrease default nginx worker_connections.
  docs/production/deployment.md
  puppet/zulip/manifests/nginx.pp
  puppet/zulip/templates/nginx.conf.template.erb
Labels: size: S, backport candidate

#24777 localstorage: Accesses can fail randomly; make best-effort.
  web/src/localstorage.js
Labels: size: M

#24853 narrow: Support underscore version of "pm-with" and "group-pm-with".
  zerver/lib/narrow.py
  zerver/tests/test_message_fetch.py
Labels: size: S

#24856 click_handlers: Ensure typeahead clicks do not collapse compose box.
  web/src/click_handlers.js
Labels: size: XS

#24852 bootstrap-aws-installer: Update the github.com SSH key.
  tools/setup/bootstrap-aws-installer
Labels: size: XS

#24857 portico-header: Tag all links for translation.
  templates/zerver/portico-header.html
Labels: size: XS

#24835 message_controls: Fix "undefined" tooltip content.
  web/src/tippyjs.js
Labels: size: XS

#24735 docs: Add a Japanese translation style guide.
  docs/translating/index.md
  docs/translating/japanese.md
  docs/translating/translating.md
Labels: size: S

#24842 portico: Rewrite "Why Zulip?" landing page.
  templates/corporate/why-zulip.html
  templates/corporate/why-zulip.md
Labels: size: XL, integration review

#24855 sentry: Provide a server-side tunnel.
  tools/lib/capitalization.py
  tools/test-backend
  web/src/sentry.ts
  zerver/views/sentry.py
  zproject/urls.py
Labels: size: M

#24753 help: Add a dedicated page on how to format lists.
  help/bulleted-and-numbered-lists.md
  help/format-your-message-using-markdown.md
  help/include/format-lists.md
  help/include/sidebar_index.md
  static/images/help/markdown-numbered-lists.png
Labels: size: L, integration review

#24863 message_list_view: Initialize status_message even for hidden messages
  web/src/message_list_view.js
Labels: integration review

#24780 styles: Use modern color notation
  stylelint.config.js
  web/styles/alerts.css
  web/styles/app_components.css
  web/styles/components.css
  web/styles/compose.css
  web/styles/dark_theme.css
  web/styles/drafts.css
  web/styles/hotspots.css
  web/styles/image_upload_widget.css
  web/styles/informational_overlays.css
  web/styles/input_pill.css
  web/styles/left_sidebar.css
  web/styles/lightbox.css
  web/styles/message_edit_history.css
  web/styles/modal.css
  web/styles/popovers.css
  web/styles/portico/activity.css
  web/styles/portico/billing.css
  web/styles/portico/email_log.css
  web/styles/portico/footer.css
  web/styles/portico/integrations.css
  web/styles/portico/integrations_dev_panel.css
  web/styles/portico/landing_page.css
  web/styles/portico/markdown.css
  web/styles/portico/portico.css
  web/styles/portico/portico_signin.css
  web/styles/portico/stats.css
  web/styles/pygments.css
  web/styles/reactions.css
  web/styles/recent_topics.css
  web/styles/rendered_markdown.css
  web/styles/right_sidebar.css
  web/styles/search.css
  web/styles/settings.css
  web/styles/subscriptions.css
  web/styles/tooltips.css
  web/styles/typing_notifications.css
  web/styles/user_circles.css
  web/styles/user_status.css
  web/styles/widgets.css
  web/styles/zulip.css
Labels: size: XL

#24788 stream_settings: Fix stream description overflow in stream settings.
  web/styles/subscriptions.css
Labels: size: XS, integration review

#24865 eslint: Loosen no-use-before-define for TS like we do for JS
  .eslintrc.json
Labels: size: XS

#24866 dependencies: Add Zod and typing dependencies
  package.json
  pnpm-lock.yaml
  version.py
Labels: size: M

#24883 server_events_dispatch: Fix live-update of email_address_visibility.
  web/src/server_events_dispatch.js
  web/tests/dispatch.test.js
  web/tests/lib/events.js
Labels: size: S, integration review

#24528 bots: Disable edit button for system bots.
  web/src/settings_users.js
  web/templates/settings/admin_user_list.hbs
Labels: area: settings (admin/org), size: S, integration review

#22944 bots: Disable `Save changes` button until user makes some changes.
  web/src/settings_bots.js
Labels: bug, good first issue, area: settings (admin/org), size: S, area: popovers, integration review

#23318 bots: Change logic for Notification bot after moved message
  zerver/actions/message_edit.py
  zerver/tests/test_message_edit.py
Labels: area: message-editing, area: bots, priority: high, size: XL, integration review

#24861 integration: Modify branch names for Bitbucket 2 events.
  zerver/webhooks/bitbucket2/tests.py
  zerver/webhooks/bitbucket2/view.py
Labels: size: S

#24851 typeahead: Fix bug where typeahead showed momentarily on shift + tab.
  web/third/bootstrap-typeahead/typeahead.js
Labels: bug, priority: high, size: S, integration review, area: compose typeahead

#24304 image_upload_widget: Refactor style of upload_widget's preview_image.
  web/src/upload_widget.ts
  web/styles/image_upload_widget.css
  web/styles/settings.css
Labels: size: S, integration review

#24886 nagios: Remove swap check.
  puppet/zulip_ops/files/nagios4/commands.cfg
  puppet/zulip_ops/files/nagios4/conf.d/services.cfg
Labels: size: S

#24187 compose: Have at least 2 new lines before and after a quoted message.
  web/src/compose_actions.js
  web/src/compose_ui.js
  web/tests/compose_actions.test.js
  web/tests/compose_ui.test.js
Labels: good first issue, area: compose, size: XL, integration review

#24756 copy_message_button: Use `div` HTML tag instead of `button`.
  web/styles/zulip.css
  web/templates/copy_message_button.hbs
Labels: size: S

#24737 python: Update tuple handling pattern; returned by a delete() query.
  zerver/lib/retention.py
  zilencer/views.py
Labels: size: S

#24891 help: Drop deprecated "Organize the streams sidebar" page.
  help/organize-the-streams-sidebar.md
Labels: size: L, integration review

#24892 stripe: Fix non-translatable computed string
  corporate/lib/stripe.py
Labels: size: S
