Repository zulip/zulip, pull requests merged in 2023-02, with the labels that each got.

#24205 import: Add the UTF-8 flag on file entries in zipfiles from Slack.
  zerver/data_import/slack.py
  zerver/tests/fixtures/slack_fixtures/test_unicode_slack_importer.zip
  zerver/tests/fixtures/slack_fixtures/unicode_team_info.json
  zerver/tests/fixtures/slack_fixtures/unicode_user_data.json
  zerver/tests/test_slack_importer.py
Labels: bug, area: export/import, size: XL, integration review

#24102 emoji: Fix regex expression for valid emoji names
  zerver/lib/emoji.py
  zerver/tests/test_realm_emoji.py
Labels: size: S

#24251 help: Add URL redirect for `help/configure-default-view`.
  zerver/lib/url_redirects.py
Labels: size: XS

#24233 portico_signin: Wrap long email names to next line.
  static/styles/portico/portico_signin.css
  templates/zerver/accounts_send_confirm.html
Labels: size: S, integration review

#24257 upgrade-postgresql: Also upgrade postgresql-client.
  scripts/setup/upgrade-postgresql
Labels: question, area: production installer, size: XS, backport candidate

#24182 settings: Clean up of tooltips for disabled personal and org settings.
  frontend_tests/node_tests/settings_org.js
  static/js/settings_account.js
  static/js/settings_org.js
  static/js/tippyjs.js
  static/styles/settings.css
  static/templates/settings/account_settings.hbs
  static/templates/settings/organization_profile_admin.hbs
  static/templates/settings/profile_settings.hbs
Labels: size: L, integration review

#24255 settings: Override bottom margin for inputs.
  static/styles/settings.css
Labels: size: S

#24250 css: Move `bootstrap-focus-style` from id to class
  static/templates/invite_user.hbs
Labels: size: XS

#24253 settings: Remove 'bootstrap-focus-style' from div element.
  static/templates/settings/notification_settings.hbs
Labels: size: XS

#24220 left_sidebar: Space topic / stream names from any icons on right by 3px.
  static/styles/left_sidebar.css
Labels: size: S, integration review

#24135 popovers: Link subscribed users to user cards.
  static/js/popovers.js
  static/templates/stream_settings/stream_member_list_entry.hbs
Labels: size: S, integration review

#24276 Minor bugfixes for tail-ses
  tools/tail-ses
Labels: size: S

#24279 emails: Improve followup_day1 (registration confirmation) email.
  templates/zerver/emails/followup_day1.source.html
  templates/zerver/emails/followup_day1.txt
  zerver/lib/email_notifications.py
  zerver/tests/test_email_notifications.py
  zerver/tests/test_i18n.py
Labels: size: XL, integration review

#23846 compose: Increase click target area around banner close button.
  static/styles/compose.css
  static/templates/compose_banner/compose_banner.hbs
Labels: size: S, integration review

#24282 index: use z-logo as inline svg.
  templates/zerver/app/index.html
Labels: size: XS

#24277 index: Remove `Loading...` text from the app loading overlay.
  templates/zerver/app/index.html
  zerver/tests/test_home.py
Labels: size: S

#24292 semgrep: Remove typing.Text rule superseded by Ruff UP019
  tools/semgrep.yml
Labels: size: S

#24289 markdown: Replace deprecated UnescapePostprocessor
  zerver/lib/markdown/__init__.py
Labels: size: XS, integration review

#24211 popovers: Add top margin to avatar in user profile
  static/styles/popovers.css
Labels: bug, good first issue, size: XS, area: popovers

#24133 compose dropdown prep commits
  static/js/click_handlers.js
Labels: size: S

#24248 registration: Track create organization page in GA.
  confirmation/models.py
  zerver/views/auth.py
  zerver/views/registration.py
Labels: size: M

#24206 message_list: Reorder and document properties of key classes.
  static/js/message_list.js
  static/js/message_list_data.js
  static/js/message_list_view.js
Labels: size: XL

#24170 settings: Improve permissions banners on Invitations panel.
  frontend_tests/node_tests/dispatch.js
  static/js/admin.js
  static/js/server_events_dispatch.js
  static/js/settings_invites.js
  static/templates/settings/invites_list_admin.hbs
Labels: size: L, integration review

#24134 help: Improve relative settings links for documentation on bots.
  zerver/lib/markdown/help_settings_links.py
Labels: size: M, integration review

#24306 docs: Update project ideas list for GSoC 2023.
  docs/outreach/gsoc.md
Labels: size: XL, integration review

#24285 docs: Add note to LDAP docs about Zulip not tracking user email changes.
  docs/production/authentication-methods.md
Labels: size: M, backport candidate

#24296 compose: Remove remaining instances of compose-send-status.
  frontend_tests/node_tests/compose.js
  frontend_tests/node_tests/compose_validate.js
  static/js/click_handlers.js
  static/js/compose.js
  static/js/compose_actions.js
  static/js/hotkey.js
  static/styles/compose.css
  static/styles/dark_theme.css
  static/templates/compose.hbs
Labels: size: L, integration review

#24316 missed_messages: Include messages from topic which differ by case.
  zerver/lib/email_notifications.py
  zerver/models.py
  zerver/tests/test_email_notifications.py
Labels: size: S

#24315 css: Remove focus outline on simplebar wrapper elements.
  static/styles/zulip.css
Labels: size: S

#23969 settings: Improve column widths in settings > uploaded files.
  static/styles/app_components.css
  static/styles/settings.css
  static/templates/settings/attachments_settings.hbs
  static/templates/settings/uploaded_files_list.hbs
Labels: area: settings (user), area: settings UI, size: S, integration review

#24194 css: Fix long name overflow in user profile modal.
  static/styles/modal.css
  static/templates/user_profile_modal.hbs
Labels: bug, priority: high, size: S, area: popovers, integration review

#24087 unread: Show unread count for only non bot messages for user list icon.
  static/js/unread.js
  static/js/unread_ui.js
Labels: size: S, integration review

#24267 compose: Show Topic Resolved warning banner only once
  frontend_tests/node_tests/compose.js
  frontend_tests/node_tests/compose_validate.js
  static/js/compose.js
  static/js/compose_state.js
  static/js/compose_validate.js
Labels: size: M, integration review

#23900 floating_recipient_bar: Replace with sticky header.
  frontend_tests/node_tests/hashchange.js
  frontend_tests/puppeteer_tests/message-basics.ts
  static/js/compose_fade.js
  static/js/floating_recipient_bar.js
  static/js/hashchange.js
  static/js/message_list_view.js
  static/js/message_scroll.js
  static/js/message_viewport.js
  static/js/navbar_alerts.js
  static/js/overlays.js
  static/js/recent_topics_ui.js
  static/js/scroll_bar.js
  static/js/stream_color.js
  static/js/ui_init.js
  static/styles/dark_theme.css
  static/styles/zulip.css
  templates/zerver/app/index.html
  tools/test-js-with-node
Labels: size: XL, chat.zulip.org review

#24322 stripe: Change realm.plan_type when upgrading a realm to Plus plan.
  corporate/lib/stripe.py
  corporate/tests/test_stripe.py
Labels: size: S

#24303 compose: Clean code to fix `up` hotkey to edit previous message.
  static/js/compose_state.js
  static/js/hotkey.js
Labels: size: M, integration review

#24326 tooltips: Fix hotkey-hint CSS class reuse.
  frontend_tests/node_tests/templates.js
  frontend_tests/node_tests/templates/hotkey_hints.hbs
  frontend_tests/node_tests/templates/tooltip_hotkey_hints.hbs
  static/js/templates.js
  static/styles/tooltips.css
  static/templates/compose.hbs
  static/templates/compose_control_buttons.hbs
  static/templates/left_sidebar.hbs
  static/templates/message_controls.hbs
  static/templates/narrow_to_compose_recipients_tooltip.hbs
  static/templates/recipient_row.hbs
  static/templates/right_sidebar.hbs
  webpack.config.ts
Labels: size: L

#24330 ruff: Fix PIE810 Call `startswith` once with a `tuple`
  tools/documentation_crawler/documentation_crawler/spiders/check_help_documentation.py
  zerver/lib/export.py
  zerver/lib/test_classes.py
  zerver/management/commands/makemessages.py
  zerver/middleware.py
  zerver/webhooks/gitlab/view.py
  zilencer/management/commands/rundjangoserver.py
Labels: size: M

#24329 help: Update documentation on editing and moving messages
  help/configure-message-editing-and-deletion.md
  help/configure-who-can-edit-topics.md
  help/disable-message-edit-history.md
  help/edit-or-delete-a-message.md
  help/import-from-gitter.md
  help/import-from-mattermost.md
  help/import-from-rocketchat.md
  help/import-from-slack.md
  help/include/customize-organization-settings.md
  help/include/import-get-your-organization-started.md
  help/include/sidebar_index.md
  help/move-content-to-another-stream.md
  help/move-content-to-another-topic.md
  help/rename-a-topic.md
  help/require-topics.md
  help/resolve-a-topic.md
  help/setting-up-zulip-for-a-class.md
  help/view-a-messages-edit-history.md
Labels: size: XL

#24293 dependencies: Upgrade JavaScript dependencies
  package.json
  static/js/emojisets.js
  version.py
  yarn.lock
Labels: size: XL, integration review

#24332 upload: Replace deprecated PIL.Image.ANTIALIAS with LANCZOS
  zerver/lib/upload/base.py
Labels: size: S, integration review

#24335 recipient_bar: Add box shadow at top.
  static/js/message_list_view.js
  static/styles/dark_theme.css
  static/styles/zulip.css
Labels: size: S, integration review

#24333 upload: Replace deprecated PIL.PngImagePlugin.APNG_DISPOSE_OP_NONE
  zerver/lib/upload/base.py
Labels: size: S, integration review

#24327 design: Loading Message Misaligned on Smaller Devices.
  static/js/setup.js
Labels: size: XS, integration review

#24343 memcached: Allow overriding the max-item-size.
  docs/production/deployment.md
  puppet/zulip/manifests/profile/memcached.pp
  puppet/zulip/templates/memcached.conf.template.erb
Labels: size: S

#24342 deferred_work: Log at start of the work.
  zerver/worker/queue_processors.py
Labels: size: M

#24346 templates: Update comments referencing Mustache to Handlebars
  docs/contributing/code-style.md
  static/templates/bookend.hbs
  static/templates/invite_subscription.hbs
  static/templates/message_edit_form.hbs
  static/templates/message_edit_history.hbs
  static/templates/message_group.hbs
  static/templates/stream_settings/browse_streams_list_item.hbs
  static/templates/topic_edit_form.hbs
Labels: size: S

#24341 compose banners: Lighten banner text in dark mode.
  static/styles/dark_theme.css
Labels: size: S, integration review

#24347 markdown: Replace custom cache decorator with functools.lru_cache
  zerver/lib/markdown/__init__.py
Labels: size: M

#24331 install-node: Upgrade Node.js to 18.14.0; manage Yarn with Corepack
  docs/subsystems/dependencies.md
  frontend_tests/node_tests/timerender.js
  package.json
  scripts/lib/install
  scripts/lib/install-node
  scripts/lib/install-yarn
  scripts/lib/node_cache.py
  scripts/lib/setup_venv.py
  scripts/lib/upgrade-zulip-stage-2
  tools/ci/production-build
  tools/lib/provision.py
  tools/setup/optimize-svg
  version.py
Labels: size: L, integration review

#24348 markdown: Rewrite YouTube URL parser without regex spaghetti
  zerver/lib/markdown/__init__.py
  zerver/tests/test_markdown.py
Labels: size: L

#24356 pm-list-data: Remove unused `is_all_privates` function.
  frontend_tests/node_tests/pm_list_data.js
  static/js/pm_list_data.js
Labels: size: M

#24355 node-tests: Remove unnecessary mock in `compose_actions` node test.
  frontend_tests/node_tests/compose_actions.js
Labels: size: XS

#24361 message_send: Convert RecipientInfoResult from TypedDict to dataclass
  zerver/actions/message_edit.py
  zerver/actions/message_send.py
  zerver/tests/test_users.py
Labels: size: XL

#24351 portico_signin: Fix content wrapping too much.
  static/styles/portico/portico_signin.css
Labels: size: S

#24364 recent topics: Fix exception displaying PMs with 5+ senders.
  static/js/recent_topics_ui.js
Labels: size: XS, backport candidate

#23743 css: Fix Handle emoji not loading gracefully in PM list.
  static/templates/status_emoji.hbs
Labels: bug, area: left-sidebar, size: XS, integration review

#24196 Minor prep changes for rechecking User notification settings again just before sending notifications
  zerver/actions/message_send.py
  zerver/lib/notification_data.py
Labels: size: L

#24383 styles: Fix horizontal SimpleBar height for SimpleBar 6
  static/styles/components.css
Labels: size: S

#24390 docs: Update frontend_tests/puppeteer_lib/common.ts path
  docs/testing/testing-with-puppeteer.md
Labels: size: XS

#24391 model: Handle parsed user-agents longer than 30 characters.
  zerver/models.py
  zerver/tests/test_decorators.py
Labels: size: L

#24396 openapi: Correct “we-public” typo
  zerver/openapi/zulip.yaml
Labels: size: XS

#24400 ci: Reduce production suite tarball retention from 14 days to 1
  .github/workflows/production-suite.yml
Labels: size: XS

#24410 populate_db: Temporarily remove post-delete signal on AlertWord.
  zilencer/management/commands/populate_db.py
Labels: size: S

#24415 Revert "create_user: Use transaction.atomic decorator for do_create_user."
  zerver/actions/create_user.py
  zerver/actions/invites.py
  zerver/actions/message_send.py
  zerver/actions/streams.py
  zerver/lib/onboarding.py
  zerver/lib/test_classes.py
  zerver/tests/test_event_queue.py
  zerver/tests/test_event_system.py
  zerver/tests/test_events.py
  zerver/tests/test_message_send.py
Labels: size: XL

#24403 tests: Remove ignored parameter from `authenticated_json_view` test.
  zerver/tests/test_decorators.py
Labels: size: S

#24401 api-docs: Update content parameter descriptions for `max_message_length`.
  zerver/openapi/zulip.yaml
Labels: size: S

#24405 rabbitmq: Add a RABBITMQ_PORT setting.
  zerver/lib/queue.py
  zproject/default_settings.py
  zproject/prod_settings_template.py
Labels: size: S, backport candidate

#24407 styles: Fix flatpickr dark theme in automatic mode
  postcss.config.js
  static/styles/dark_theme.css
Labels: size: S

#24408 styles: Hoist @keyframes to top level
  static/styles/compose.css
Labels: size: S

#24413 install-node: Upgrade Node.js to 18.14.1 security release
  scripts/lib/install-node
  version.py
Labels: size: S

#24380 spectators: Save a redirect to /register/.
  static/js/spectators.js
  static/templates/navbar.hbs
Labels: size: XS

#24402 message-send: Deduplicate check of `settings.MAX_MESSAGE_LENGTH`.
  zerver/actions/message_send.py
  zerver/tests/test_message_send.py
Labels: size: S

#24372 settings: Indicate character limit on restoring long draft messages.
  static/js/drafts.js
Labels: size: XS

#24433 reset: Tag "forgot password" text for translation.
  templates/zerver/reset.html
Labels: size: XS

#24432 sentry: Fix accidental blockquote by escaping >.
  zerver/webhooks/sentry/doc.md
Labels: size: S

#24431 user_profile: Deduplicate code for showing custom profile fields.
  static/styles/popovers.css
  static/templates/user_custom_profile_fields.hbs
  static/templates/user_info_popover_content.hbs
  static/templates/user_profile_modal.hbs
Labels: size: L

#24379 log-search: Add a --timeline option to show gaps and overlaps.
  scripts/log-search
Labels: size: L

#24438 api-docs: Fix small typos and copy/paste errors in API changelog.
  api_docs/changelog.md
Labels: size: S

#24441 log-search: Fix precedence in no-color case.
  scripts/log-search
Labels: size: XS

#24254 stream_settings: Fix Announce stream disables unexpectedly.
  static/js/stream_create.js
Labels: bug, area: stream settings, size: XS, integration review

#24442 docs: Fix typo on Design discussions doc.
  docs/contributing/design-discussions.md
Labels: size: XS, integration review

#23958 compose: Replace empty message banner with red outline for compose box.
  frontend_tests/node_tests/compose.js
  frontend_tests/node_tests/compose_validate.js
  static/js/compose.js
  static/js/compose_banner.ts
  static/js/compose_validate.js
  static/styles/compose.css
  static/styles/dark_theme.css
Labels: size: M, integration review

#24452 docs: Remove spaces before commas
  docs/outreach/experience.md
  docs/translating/translating.md
  static/js/message_list_view.js
  templates/corporate/for/open-source.html
  templates/zerver/integrations/include/event-filtering-instruction.md
  zerver/tests/test_openapi.py
  zerver/tests/test_signup.py
  zerver/webhooks/dropbox/doc.md
  zilencer/management/commands/populate_db.py
Labels: size: S

#24411 tornado: Speed up hot path by removing use of asdict
  zerver/tornado/event_queue.py
Labels: size: S

#24378 message_send: Use stream object for name in "no subscribers" message.
  zerver/actions/message_send.py
  zerver/tests/test_message_send.py
Labels: size: L

#24450 ruff: Fix PLE0101 Explicit return in `__init__`
  zerver/lib/storage.py
Labels: size: XS

#24453 queue: Only set QOS on a newly-opened channel, once.
  zerver/lib/queue.py
Labels: size: S

#24449 help: Add section on privacy settings to /help/review-your-settings.
  help/include/sidebar_index.md
  help/review-your-settings.md
Labels: integration review

#24446 help: Document dark-theme mobile feature.
  help/dark-theme.md
Labels: size: S, integration review

#24456 timestamp: Switch to a slightly faster datetime_to_timestamp.
  zerver/lib/timestamp.py
Labels: size: XS

#24462 user_profile: Show icons for external account fields in full modal.
  static/templates/user_custom_profile_fields.hbs
Labels: size: S, integration review

#24451 help: Add "Do not mark messages as read" section.
  help/marking-messages-as-read.md
Labels: size: S, integration review

#23744 setting(user): Sort Uploaded files with newest on top.
  static/js/attachments_ui.js
  static/js/list_widget.js
Labels: good first issue, area: settings (user), size: S, integration review

#24252 hotkey: Add `z` shortcut to zoom to message `near` view.
  help/keyboard-shortcuts.md
  web/src/hotkey.js
  web/templates/keyboard_shortcuts.hbs
Labels: area: keyboard UI, area: documentation (user), priority: high, size: M, chat.zulip.org review

#24457 integrations: Increase font size of trademark disclaimer.
  web/styles/portico/integrations.css
Labels: size: XS

#24268 personal_settings: Add deactivate organization button for organization with only one user.
  web/src/settings.js
  web/src/settings_account.js
  web/src/settings_org.js
  web/styles/settings.css
  web/templates/settings/account_settings.hbs
  web/templates/settings/organization_profile_admin.hbs
Labels: area: settings (user), size: L, integration review

#23702 Update export-and-import.md
  docs/production/export-and-import.md
Labels: size: S

#24448 help: Document modifying email visibility on sign-up.
  help/configure-email-visibility.md
  zerver/lib/markdown/tabbed_sections.py
Labels: size: S, integration review

#24475 eslint: Prohibit import cycles in TypeScript
  .eslintrc.json
Labels: size: XS, integration review

#24454 help: Document stream notifications mobile feature.
  help/stream-notifications.md
Labels: size: S, integration review

#24479 test-js-with-node: Fix source maps for coverage
  package.json
  version.py
  web/tests/lib/index.js
  yarn.lock
Labels: size: L

#24359 stream_muting: Fix message reselect bug.
  web/src/stream_muting.js
Labels: size: S, integration review

#24478 message_row: Allow time row to expand if it needs more width.
  web/styles/message_row.css
Labels: size: S, integration review

#24480 models: Drop unique index on user/message/emoji_name.
  zerver/migrations/0431_alter_archivedreaction_unique_together_and_more.py
  zerver/models.py
Labels: size: S

#24481 docs: Update instructions for realm deletion to use management command.
  docs/production/export-and-import.md
Labels: size: S

#24477 data_import: Stop tar'ing up converted data.
  zerver/data_import/gitter.py
  zerver/data_import/mattermost.py
  zerver/data_import/rocketchat.py
  zerver/data_import/slack.py
  zerver/tests/test_rocketchat_importer.py
  zerver/tests/test_slack_importer.py
Labels: size: S

#24015 internationalization: Localize dates.
  web/src/popovers.js
  web/src/settings.js
  web/src/timerender.ts
  web/src/user_profile.js
  web/tests/drafts.test.js
  web/tests/muted_users.test.js
  web/tests/rendered_markdown.test.js
  web/tests/settings_muted_topics.test.js
  web/tests/settings_muted_users.test.js
  web/tests/timerender.test.js
  web/tests/user_topics.test.js
Labels: area: internationalization, priority: high, size: XL, release goal

#23466 invite_user: Convert overlay to `dialog_widget`.
  web/src/hashchange.js
  web/src/invite.js
  web/styles/dark_theme.css
  web/styles/right_sidebar.css
  web/styles/zulip.css
  web/templates/gear_menu.hbs
  web/templates/invite_subscription.hbs
  web/templates/invite_user.hbs
  web/templates/invite_user_modal.hbs
  web/templates/right_sidebar.hbs
  web/templates/settings/invites_list_admin.hbs
Labels: area: settings (admin/org), size: XL, area: popovers

#24499 alertmanager: Indent a documentation code block into its list item
  zerver/webhooks/alertmanager/doc.md
Labels: area: documentation (api and integrations), size: S, integration review

#24500 docs: Clarify where GSoC/Outreachy applicants should post intros.
  docs/outreach/apply.md
Labels: size: S, integration review

#24352 documentation: Add a horizontal scroll bar to code blocks in help center.
  web/styles/portico/markdown.css
Labels: area: documentation (user), size: XS, integration review

#23907 Private Messages: Scroll the left-sidebar container to desired pm whe…
  web/src/pm_list.js
  web/tests/narrow_activate.test.js
Labels: area: left-sidebar, priority: high, size: M, UX, backport candidate, integration review

#24498 docs: Document how to use SMTP without authentication.
  docs/production/email.md
  zerver/lib/send_email.py
  zerver/tests/test_send_email.py
  zproject/prod_settings_template.py
Labels: area: production, area: emails, size: S, backport candidate

#24502 portico: Clarify encryption at rest information on /security.
  templates/corporate/security.md
Labels: integration review

#24464 puppet: Pin with sha256sum verification.
  puppet/deps.yaml
  scripts/lib/puppet_cache.py
Labels: size: L

#24516 api-docs: Fix changelog formatting for feature level 165.
  api_docs/changelog.md
Labels: size: XS

#24515 integrations-docs: Fix indentation issues in existing documentation.
  templates/zerver/integrations/hubot.md
  templates/zerver/integrations/irc.md
  zerver/webhooks/dropbox/doc.md
  zerver/webhooks/wekan/doc.md
Labels: size: M

#24501 templates: Update `reset_done.html` page text and title.
  templates/zerver/reset_done.html
  zerver/tests/test_signup.py
Labels: size: S

#24505 Remove realm_str param from POST /messages API
  api_docs/changelog.md
  version.py
  zerver/tests/test_message_send.py
  zerver/views/message_send.py
Labels: size: L
