Repository zulip/zulip, pull requests merged in 2023-09, with the labels that each got.

#26629 ruff: Fix PIE808 Unnecessary `start` argument in `range`
  analytics/views/stats.py
  scripts/lib/supervisor.py
  scripts/log-search
  tools/renumber-migrations
  zerver/lib/upload/base.py
  zerver/tests/test_decorators.py
  zerver/tests/test_drafts.py
  zerver/tests/test_email_mirror.py
  zerver/tests/test_message_flags.py
  zerver/tests/test_message_notification_emails.py
  zerver/tests/test_retention.py
  zerver/tests/test_upload.py
Labels: size: M

#26642 puppet: Update dependencies.
  puppet/zulip/manifests/common.pp
  tools/setup/bootstrap-awscli.sh
Labels: size: L

#26644 postgres_exporter: Explicitly specify the zulip database.
  puppet/zulip_ops/templates/supervisor/conf.d/prometheus_postgres_exporter.conf.template.erb
Labels: size: XS

#26653 docs: Fix typos caught by ‘typos’
  docs/overview/changelog.md
  web/src/settings_bots.js
  web/src/settings_users.js
  web/tests/upload.test.js
  zerver/tests/test_events.py
  zerver/tests/test_message_fetch.py
  zerver/tests/test_muted_users.py
  zerver/tests/test_signup.py
  zerver/transaction_tests/test_user_groups.py
Labels: size: M

#26660 models: Remove duplicate index definition for date_sent
  zerver/migrations/0244_message_copy_pub_date_to_date_sent.py
  zerver/migrations/0245_message_date_sent_finalize_part1.py
  zerver/models.py
Labels: size: M, integration review

#26657 compose_banner: Remove the warning for messages sent in FOLLOWED topics in muted stream.
  web/src/notifications.js
  web/src/user_topics.js
Labels: size: S

#26654 user_profile: Sort the stream list on update and Prevent unwanted reordering.
  web/src/user_profile.js
Labels: size: XS

#26641 mypy: Upgrade mypy from 1.4.1 to 1.5.1
  analytics/lib/counts.py
  analytics/management/commands/populate_analytics_db.py
  analytics/tests/test_counts.py
  analytics/views/stats.py
  requirements/dev.txt
  requirements/mypy.in
  version.py
  zerver/actions/realm_settings.py
  zerver/lib/bulk_create.py
  zerver/lib/push_notifications.py
  zerver/lib/test_classes.py
  zerver/migrations/0386_fix_attachment_caches.py
  zerver/migrations/0460_backfill_realmauditlog_extradata_to_json_field.py
  zilencer/migrations/0027_backfill_remote_realmauditlog_extradata_to_json_field.py
  zilencer/views.py
Labels: size: XL

#26648 billing: Rename a few confusing references to "Zulip Limited".
  corporate/tests/test_stripe.py
  templates/corporate/billing.html
Labels: size: S, area: billing

#26608 ts: Migrate `attachments_ui` to typescript.
  tools/test-js-with-node
  web/src/attachments_ui.ts
  web/src/page_params.ts
Labels: size: L, area: typescript migration

#26666 narrow: Don't call deactivate directly.
  web/src/narrow.js
Labels: size: XS

#26659 images: Prevent default browser behavior on paste.
  web/src/upload.js
  web/tests/upload.test.js
Labels: area: compose, size: S, maintainer review, QA needed

#26633 ts: Migrate `settings_emoji.js` to TypeScript.
  tools/test-js-with-node
  web/src/emoji.ts
  web/src/settings_emoji.ts
Labels: size: L, integration review

#26668 setup: Fix wildly unsafe cast in $.fn.expectOne
  web/src/avatar.ts
  web/src/global.d.ts
  web/src/setup.ts
Labels: size: S, integration review

#26662 tabbed_sections: Fix a backtrack-able regex.
  zerver/lib/markdown/tabbed_sections.py
Labels: size: XS

#26669 web: Add missing CSS selector escaping
  web/e2e-tests/lib/common.ts
  web/src/compose_banner.ts
  web/src/echo.js
  web/src/message_lists.js
  web/src/messages_overlay_ui.ts
  web/tests/lib/compose_banner.js
Labels: size: S, integration review

#26643 widgets: Fix bug where a new line right after /todo broke rendering.
  zerver/lib/widget.py
Labels: size: XS

#26631 markdown: Fix URL link topic skipping query.
  zerver/lib/markdown/__init__.py
  zerver/tests/test_markdown.py
Labels: bug, feedback wanted, area: markdown, size: S

#26376 docs: Add a warning about restarting individual services.
  docs/production/troubleshooting.md
Labels: area: documentation (production), size: S, backport candidate, documentation review

#26672 mypy: Remove `no_implicit_reexport` override
  pyproject.toml
  zproject/computed_settings.py
Labels: size: S

#26674 sync-translations: Normalize translations to NFC
  locale/hi/translations.json
  locale/ml/LC_MESSAGES/django.po
  locale/si/LC_MESSAGES/django.po
  locale/si/translations.json
  locale/ta/LC_MESSAGES/django.po
  locale/ta/translations.json
  tools/i18n/sync-translations
Labels: size: L

#26679 docs: Remove obsolete mentions of reStructuredText
  docs/documentation/overview.md
  tools/lint
  tools/linter_lib/custom_check.py
Labels: size: S

#26680 mypy: Remove exemption for aioapns
  pyproject.toml
Labels: size: XS

#26678 requirements: Upgrade Python requirements
  requirements/common.in
  requirements/dev.in
  requirements/dev.txt
  requirements/docs.txt
  requirements/pip.txt
  requirements/prod.txt
  version.py
  zerver/actions/message_edit.py
  zerver/lib/validator.py
Labels: size: XL

#26683 test-js-with-node: Remove deleted dropdown-list-widget module.
  tools/test-js-with-node
Labels: area: general UI, priority: high, size: XS, difficult

#26698 postgres_exporter: Build from source for per-index stats.
  puppet/zulip/manifests/common.pp
  puppet/zulip_ops/manifests/prometheus/postgresql.pp
  puppet/zulip_ops/templates/supervisor/conf.d/prometheus_postgres_exporter.conf.template.erb
Labels: size: L

#26701 postgres_exporter: Rebase the per-index stats branch.
  puppet/zulip/manifests/common.pp
  puppet/zulip_ops/manifests/prometheus/postgresql.pp
Labels: size: S

#26707 nginx: Suppress proxy warnings when the proxy itself sent the request.
  puppet/zulip/templates/nginx/trusted-proto.template.erb
  zerver/middleware.py
Labels: size: M, backport candidate

#26708 docs: Use MyST syntax for Sphinx metadata
  docs/development/request-remote.md
  docs/production/install-existing-server.md
  docs/production/maintain-secure-upgrade.md
  docs/production/password-strength.md
Labels: size: S

#26710 typed_endpoint: Add missing tuple comma for OptionalTopic aliases
  zerver/lib/typed_endpoint.py
Labels: size: XS

#26722 emoji_picker: Improve rendering time of emoji picker by ~30%.
  web/src/emoji_picker.js
  web/templates/emoji_popover_content.hbs
  web/templates/emoji_popover_emoji_map.hbs
Labels: area: emoji, priority: high, size: M, area: performance

#26715 emoji: Add unified_reactions.json to the sha1sum.
  scripts/lib/zulip_tools.py
Labels: size: XS

#26716 python: Elide unnecessary list wrappers
  analytics/lib/time_utils.py
  analytics/tests/test_counts.py
  analytics/views/installation_activity.py
  analytics/views/stats.py
  docs/tutorials/new-feature-tutorial.md
  puppet/zulip/files/postgresql/wal-g-exporter
  scripts/log-search
  tools/droplets/create.py
  tools/setup/emoji/generate_emoji_names_table
  zerver/actions/invites.py
  zerver/actions/message_edit.py
  zerver/actions/message_flags.py
  zerver/actions/realm_settings.py
  zerver/data_import/rocketchat.py
  zerver/data_import/slack.py
  zerver/lib/data_types.py
  zerver/lib/digest.py
  zerver/lib/events.py
  zerver/lib/export.py
  zerver/lib/markdown/__init__.py
  zerver/lib/markdown/nested_code_blocks.py
  zerver/lib/message.py
  zerver/lib/onboarding.py
  zerver/lib/push_notifications.py
  zerver/lib/request.py
  zerver/lib/stream_subscription.py
  zerver/lib/streams.py
  zerver/lib/string_validation.py
  zerver/lib/typed_endpoint.py
  zerver/lib/user_counts.py
  zerver/lib/user_topics.py
  zerver/lib/users.py
  zerver/lib/validator.py
  zerver/management/commands/export_search.py
  zerver/migrations/0284_convert_realm_admins_to_realm_owners.py
  zerver/migrations/0371_invalid_characters_in_topics.py
  zerver/migrations/0375_invalid_characters_in_stream_names.py
  zerver/migrations/0383_revoke_invitations_from_deactivated_users.py
  zerver/tests/test_auth_backends.py
  zerver/tests/test_message_fetch.py
  zerver/tests/test_user_groups.py
  zerver/views/development/dev_login.py
  zerver/views/documentation.py
  zerver/views/realm.py
  zerver/views/user_settings.py
  zerver/webhooks/github/view.py
  zerver/webhooks/gitlab/view.py
  zerver/webhooks/jotform/view.py
  zerver/webhooks/slack/view.py
Labels: size: XL

#26676 widgets: Add test for tokenizing widget type on newline.
  zerver/tests/test_widgets.py
Labels: size: XS

#26714 puppeteer: Allow reruns in interactive mode when tests succeed.
  tools/test-js-with-puppeteer
Labels: size: S

#26704 help: Update user management pages.
  help/change-a-users-name.md
  help/change-a-users-role.md
  help/deactivate-or-reactivate-a-user.md
  help/include/manage-this-user-via-user-profile.md
  zerver/lib/markdown/tabbed_sections.py
Labels: size: M, integration review

#26711 python: Delete superfluous parens
  corporate/tests/test_stripe.py
  tools/lib/capitalization.py
  tools/lib/html_branches.py
  tools/test-backend
  zerver/actions/message_edit.py
  zerver/actions/message_send.py
  zerver/lib/ccache.py
  zerver/lib/markdown/api_arguments_table_generator.py
  zerver/lib/markdown/fenced_code.py
  zerver/lib/notification_data.py
  zerver/lib/test_classes.py
  zerver/tests/test_external.py
  zerver/tests/test_import_export.py
  zerver/tests/test_invite.py
  zerver/tests/test_middleware.py
  zerver/tests/test_queue_worker.py
  zerver/tests/test_rate_limiter.py
  zerver/tests/test_user_groups.py
  zerver/tornado/event_queue.py
  zerver/views/realm.py
  zerver/views/registration.py
  zerver/views/sentry.py
  zerver/webhooks/librato/view.py
  zilencer/management/commands/populate_db.py
Labels: size: XL, has conflicts

#25252 recent_topics: Add support for sorting by unread count.
  web/shared/icons/unread.svg
  web/src/recent_view_ui.js
  web/styles/recent_view.css
  web/templates/recent_view_row.hbs
  web/templates/recent_view_table.hbs
Labels: priority: high, size: M, post release, area: recent-conversations, integration review, chat.zulip.org review

#26728 compose: Disable unneeded buttons in preview mode.
  web/src/compose.js
  web/src/popover_menus.js
  web/styles/compose.css
  web/templates/compose_control_buttons.hbs
  web/templates/compose_control_buttons_in_popover.hbs
  web/templates/compose_control_buttons_popover.hbs
  web/tests/compose.test.js
Labels: size: L

#26731 dependencies: Patch source-sans to correct `format()` for variable fonts
  package.json
  patches/source-sans@3.46.0.patch
  pnpm-lock.yaml
Labels: size: M

#26483 search: Add title to the search bar when in "sender:" narrow & rewrite is_common_narrow.
  web/src/filter.js
  web/src/narrow.js
  web/tests/filter.test.js
  web/tests/narrow.test.js
Labels: area: search, area: message view, priority: high, size: XL, integration review

#26735 nagios: Remove load monitoring.
  puppet/zulip_ops/files/nagios4/commands.cfg
  puppet/zulip_ops/files/nagios4/conf.d/services.cfg
Labels: size: M

#26639 api-docs: Update `subscription` event for `op: peer_add` in feature level 205.
  api_docs/changelog.md
  zerver/openapi/zulip.yaml
Labels: area: documentation (api and integrations), size: M, integration review

#26730 compose: Present banners with intrinsic layout.
  web/styles/compose.css
  web/templates/compose_banner/compose_banner.hbs
  web/templates/compose_banner/success_message_scheduled_banner.hbs
Labels: area: compose, size: L, maintainer review, QA needed

#26383 tooltips: added a tooltip to display the name of status-emoji
  web/src/tippyjs.js
  web/templates/user_info_popover_content.hbs
Labels: size: S, integration review

#26737 message_edit: Display GIF button when Giphy is enabled.
  web/src/message_edit.js
Labels: size: XS

#26734 compose: Disable unneeded control buttons in preview mode while editing.
  web/src/click_handlers.js
  web/src/compose.js
  web/src/popover_menus.js
Labels: size: S

#26744 ci: Temporarily upgrade postgresql-client-common before upgrading.
  .github/workflows/production-suite.yml
Labels: size: S

#26749 requirements: Upgrade Python requirements
  requirements/dev.txt
  requirements/mypy.in
  requirements/pip.txt
  requirements/prod.txt
  version.py
Labels: size: XL, backport candidate

#26685 help: Update "Remove users from a stream".
  help/add-or-remove-users-from-a-stream.md
Labels: size: S, integration review

#25570 unread: Fix double counting of mentions in direct messages.
  web/src/notifications.js
  web/src/pm_list.js
  web/src/unread.js
  web/src/unread_ui.js
  web/tests/pm_list.test.js
  web/tests/unread.test.js
Labels: bug, area: misc, size: L, integration review

#26739 scim: Add supporting for syncing the user role.
  help/scim.md
  zerver/actions/users.py
  zerver/lib/scim.py
  zerver/tests/test_scim.py
Labels: area: production, size: XL

#26743 api-docs: Clean up descriptions in `unread_msgs` object register response.
  zerver/openapi/zulip.yaml
Labels: area: documentation (api and integrations), size: M, api docs review

#26732 recent_view: Reduce width of unread header.
  web/styles/recent_view.css
Labels: size: XS

#26724 typeahead: Suggest only the first matching wildcard mention.
  web/src/typeahead_helper.js
  web/tests/composebox_typeahead.test.js
  web/tests/typeahead_helper.test.js
Labels: priority: high, size: M, area: compose typeahead

#26742 Migrate user group popover to Tippy.
  web/src/user_group_popover.js
  web/styles/popovers.css
  web/templates/user_group_info_popover.hbs
  web/templates/user_group_info_popover_content.hbs
Labels: size: XL, has conflicts, area: popovers, bootstrap removal

#26755 [7.x] ci: Restore commented clean_unused_caches.py invocation
  .github/workflows/zulip-ci.yml
Labels: size: XS

#26758 list_widget: Rename unsafe `modifier` parameter to `modifier_html`
  web/src/alert_words_ui.js
  web/src/attachments_ui.ts
  web/src/dropdown_widget.js
  web/src/list_widget.ts
  web/src/recent_view_ui.js
  web/src/settings_emoji.ts
  web/src/settings_exports.js
  web/src/settings_invites.js
  web/src/settings_linkifiers.js
  web/src/settings_muted_users.js
  web/src/settings_playgrounds.js
  web/src/settings_streams.js
  web/src/settings_user_topics.js
  web/src/settings_users.js
  web/src/stream_create_subscribers.js
  web/src/stream_edit_subscribers.js
  web/src/user_group_create_members.js
  web/src/user_group_edit_members.js
  web/src/user_groups_settings_ui.js
  web/src/user_profile.js
  web/tests/alert_words_ui.test.js
  web/tests/list_widget.test.js
  web/tests/recent_view.test.js
Labels: integration review

#26350 emails: Update subject for confirm_new_email to have realm information.
  templates/zerver/emails/confirm_new_email.subject.txt
  zerver/actions/user_settings.py
  zerver/tests/test_email_change.py
Labels: area: emails, size: S, integration review

#26771 uwsgi: Ensure that the master process cannot load the application.
  puppet/zulip/templates/uwsgi.ini.template.erb
Labels: size: M

#26760 toggle_resolve_topic: Display spinner while request is in progress.
  web/src/click_handlers.js
  web/src/message_edit.js
  web/styles/zulip.css
  web/templates/recipient_row.hbs
Labels: priority: high, size: M, area: message feed UI

#26658 response: Remove "result: partially_completed" for success responses.
  api_docs/changelog.md
  version.py
  web/src/message_edit.js
  zerver/lib/response.py
  zerver/openapi/openapi.py
  zerver/openapi/zulip.yaml
  zerver/tests/test_message_flags.py
  zerver/tests/test_message_topics.py
  zerver/views/message_flags.py
  zerver/views/streams.py
Labels: area: api, size: XL, api docs review

#26761 message_edit_form: Remove question mark icon after edit-timer-text.
  web/styles/dark_theme.css
  web/styles/zulip.css
  web/templates/message_edit_form.hbs
Labels: area: message-editing, size: M

#26775 left_sidebar: Remove dev environment check.
  web/templates/left_sidebar.hbs
Labels: size: XS

#26720 views: Add a /health healthcheck endpoint.
  puppet/zulip/manifests/app_frontend_base.pp
  puppet/zulip/templates/nginx/healthcheck.conf.template.erb
  zerver/lib/exceptions.py
  zerver/middleware.py
  zerver/tests/test_health.py
  zerver/views/health.py
  zproject/urls.py
Labels: size: XL, integration review

#24412 build_message_send_dict: Tweak message.realm access.
  zerver/actions/message_send.py
Labels: size: S, integration review

#26790 emails: Fix contact_us macros for "mailto" in email links.
  templates/zerver/emails/account_registered.html
  templates/zerver/emails/macros.html
Labels: size: S

#26792 api-docs: Update various areas of endpoint response documentation.
  zerver/openapi/zulip.yaml
Labels: size: XL

#26794 left_sidebar: Hold hoverable area to + icon.
  web/styles/left_sidebar.css
Labels: bug, size: XS, area: left sidebar (ui)

#26801 tests: Fix direct mutation of ES modules again
  web/tests/stream_events.test.js
  web/tests/upload.test.js
Labels: size: M

#26802 help: Fix formatting issue in "Dark theme" page.
  help/dark-theme.md
Labels: size: S, integration review

#26799 help: Add "View your bots" page.
  help/include/sidebar_index.md
  help/view-all-bots-in-your-organization.md
  help/view-your-bots.md
Labels: area: documentation (user), priority: high, size: S, integration review

#26800 settings: link to list of emoticon translations (e.g. :) for 😄)
  web/templates/settings/display_settings.hbs
Labels: size: XS

#26804 zilencer: Remove /json versions of push bouncer endpoints.
  zerver/tests/test_decorators.py
  zilencer/urls.py
Labels: size: S

#25094 markdown: Fix lists with 3+ digit markers retaining alignment for 2 digits
  web/styles/rendered_markdown.css
Labels: area: markdown, size: M, integration review

#26805 narrow: Skip the realm_id limit on joins across to usermessage.
  zerver/lib/narrow.py
  zerver/tests/test_message_fetch.py
Labels: size: M

#26806 linkifiers: Use only the handle for dragging.
  web/src/settings_linkifiers.js
  web/styles/settings.css
  web/templates/settings/admin_linkifier_list.hbs
Labels: size: M

#26677 message_scroll: Update sticky header date more frequently.
  web/src/message_scroll.js
Labels: size: XS, area: message feed UI, deployed on chat.zulip.org

#26718 help: Document troubleshooting screen for mobile notifications.
  help/mobile-notifications.md
Labels: size: M, integration review

#26813 recent_view_data: Convert module to TypeScript
  web/src/recent_view_data.ts
Labels: size: S, integration review, area: typescript migration

#26814 stream_pill: Convert module to TypeScript
  web/src/stream_pill.ts
Labels: size: M, integration review, area: typescript migration

#26816 list_cursor: Convert module to TypeScript
  web/src/list_cursor.ts
  web/src/stream_list.js
  web/tests/list_cursor.test.js
Labels: size: L, integration review, area: typescript migration

#26818 markdown_config: Convert module to TypeScript
  web/src/emoji.ts
  web/src/markdown_config.ts
Labels: size: L, integration review, area: typescript migration

#26810 typeahead: Improve tests for multi word match's highlighting.
  web/tests/typeahead_helper.test.js
Labels: size: XS

#26811 settings: Fix live-update bug when changing user names.
  web/src/settings_users.js
Labels: size: XS

#26781 api-docs: Update the add and remove `update_message_flags` events.
  zerver/lib/event_schema.py
  zerver/openapi/zulip.yaml
Labels: area: documentation (api and integrations), size: L, integration review

#26706 stream view: Show "start a conversation" for a topic with no messages.
  web/src/narrow_banner.js
  web/tests/narrow.test.js
Labels: size: S, maintainer review

#26837 Revert "markdown: Fix 3+ digit marker lists retaining alignment for 2 digits."
  web/styles/rendered_markdown.css
Labels: area: markdown, size: M

#26830 hotspots: Move compute_placement to only module using it.
  web/src/hotspots.js
  web/src/popovers.js
Labels: size: XL

#26819 navbar_alerts: Improve info for users having at least 50K unreads.
  web/src/navbar_alerts.js
  web/templates/navbar_alerts/bankruptcy.hbs
Labels: bug, area: notifications (other), size: S

#26825 Fix `user_group_edit` module import cycles
  web/src/settings_data.ts
  web/src/user_group_edit.js
  web/src/user_group_edit_members.js
  web/src/user_group_ui_updates.js
  web/tests/settings_data.test.js
Labels: size: L

#26840 copied_tooltip: Remove tippyjs import cycle by extracting it.
  tools/test-js-with-node
  web/src/about_zulip.js
  web/src/copied_tooltip.js
  web/src/message_edit.js
  web/src/popover_menus.js
  web/src/rendered_markdown.js
  web/src/settings_bots.js
  web/src/stream_edit.js
  web/src/tippyjs.js
  web/tests/rendered_markdown.test.js
Labels: size: L

#26741 help: Document "Show unread count for" display preference.
  help/configure-unread-message-counters.md
  help/include/sidebar_index.md
Labels: size: M, integration review

#26847 ruff: Fix C416 Unnecessary `list` comprehension
  zerver/forms.py
Labels: size: S

#26850 help: Restore scroll target styling
  web/styles/portico/portico.css
Labels: size: S

#26849 unread_msgs: Fix the unread count in muted streams.
  web/src/unread.js
Labels: size: XS

#26846 message_header: Remove the widget to change the visibility policy.
  web/src/message_list_view.js
  web/templates/recipient_row.hbs
Labels: size: M

#26853 realm: Differentiate reserved realms from in-use realms.
  analytics/tests/test_support_views.py
  zerver/forms.py
  zerver/management/commands/import.py
  zerver/tests/test_realm.py
  zerver/tests/test_signup.py
Labels: question, area: export/import, size: L

#26862 billing: Fix license counting in exempt_from_license_number_check case.
  corporate/lib/stripe.py
  corporate/tests/test_stripe.py
Labels: size: L, area: billing

#26867 user_preferences: Change option text for "Show unread counts for".
  web/src/settings_config.ts
  zerver/openapi/zulip.yaml
Labels: area: settings (user), size: S, maintainer review, documentation review

#26885 recent_view_util: Fix return type of get_key_from_message.
  web/src/recent_view_data.ts
  web/src/recent_view_util.ts
Labels: size: XS

#26879 documentation: Make the markdown div take up all available height.
  web/styles/portico/portico.css
Labels: size: XS

#26878 search: Always select search bar text when initiating search.
  web/src/search.js
Labels: size: S

#26869 bootstrap: Delete button JavaScript
  web/third/bootstrap/js/bootstrap.js
Labels: integration review, bootstrap removal

#26882 Rename some references to display settings -> preferences
  zerver/lib/hotspots.py
  zerver/models.py
Labels: size: XS

#26890 help: Tweak wording in help/add-a-custom-linkifier.
  help/add-a-custom-linkifier.md
Labels: area: documentation (user), integration review

#26870 util: Fix inefficient RegExp construction
  web/src/util.ts
Labels: size: XS, integration review

#26896 view_labels: Change 'Direct messages' to 'All direct messages'.
  docs/testing/manual-testing.md
  web/e2e-tests/message-basics.test.ts
  web/src/filter.js
  web/tests/filter.test.js
Labels: size: S, area: message feed display, integration review, documentation review

#26848 unread_msgs: Fix all unreads in muted stream being treated as muted.
  api_docs/changelog.md
  version.py
  zerver/lib/message.py
  zerver/lib/user_topics.py
  zerver/openapi/zulip.yaml
  zerver/tests/test_events.py
  zerver/tests/test_message_flags.py
Labels: size: XL, integration review

#26897 help: Improve /help/view-a-messages-edit-history.
  help/view-a-messages-edit-history.md
Labels: area: documentation (user), size: S, integration review

#26887 help: Document option to add stream to default streams when creating.
  help/create-a-stream.md
Labels: area: documentation (user), size: XS, integration review

#26534 search: Close search box when searching for an empty string.
  web/src/search.js
  web/tests/search.test.js
Labels: area: search, size: S, integration review

#26905 recent_view_table: Add a tooltip to unread sort header.
  web/templates/recent_view_table.hbs
Labels: size: XS, integration review

#26824 api-docs: Correct error documentation for api/deactivate-own-user.
  zerver/openapi/zulip.yaml
Labels: area: documentation (api and integrations), size: M, api docs review

#26793 unread: Fix logic for wildcard mentions in direct messages.
  web/src/unread.js
  web/tests/unread.test.js
Labels: size: M, integration review

#26910 left_sidebar: Limit privacy icon styles to streams list.
  web/styles/left_sidebar.css
Labels: area: message view, size: XS, integration review, area: left sidebar (display)

#26917 util: Implement is_valid_url more correctly, with tests.
  web/src/settings_org.js
  web/src/util.ts
  web/tests/util.test.js
Labels: size: M

#26916 lint: Fix semgrep scanning of extensionless Python scripts
  requirements/dev.in
  tools/lint
  tools/semgrep-py.yml
Labels: size: S

#26919 inbox: Move focused row to visible area on scroll.
  web/src/inbox_ui.js
Labels: size: L

#26921 compose_banners: Explicitly target banner content, child p.
  web/styles/compose.css
Labels: size: XS

#24284 ldap: Improve doc on AUTH_LDAP_ADVANCED_REALM_ACCESS_CONTROL.
  docs/production/authentication-methods.md
Labels: size: M, backport candidate

#26925 user_groups: Improve bulk membership change logic.
  zerver/actions/user_groups.py
  zerver/tests/test_audit_log.py
  zerver/tests/test_events.py
  zerver/views/user_groups.py
Labels: size: L

#26933 delete_old_unclaimed_attachments: Update docs on default max age.
  zerver/management/commands/delete_old_unclaimed_attachments.py
Labels: size: XS

#26935 soft_deactivation: Stop computing "new messages" in Python.
  zerver/lib/soft_deactivation.py
  zerver/tests/test_soft_deactivation.py
Labels: size: M

#26357 data_import: Skip Slack "Posts" which we don't otherwise support.
  zerver/data_import/slack.py
Labels: size: XS, backport candidate

#26024 popovers: Alphabetize group members in user group
  web/src/user_group_popover.js
Labels: size: XS

#26940 push_notifications: Send timestamp with only second granularity.
  zerver/lib/push_notifications.py
  zerver/tests/test_push_notifications.py
Labels: size: M

#26927 inbox: Focus on entire row instead of stream name on show.
  web/src/inbox_ui.js
Labels: size: L
