Repository zulip/zulip, pull requests merged in 2023-04, with the labels that each got.

#24940 web: Add missing CSS.escape calls
  web/src/compose.js
  web/src/compose_banner.ts
  web/src/compose_validate.js
  web/src/message_viewport.js
  web/src/overlays.js
  web/src/portico/header.js
  web/src/stream_edit.js
  web/src/tippyjs.js
  web/src/user_group_edit.js
  web/src/user_profile.js
Labels: size: XL, integration review

#24818 ts: Migrate scroll_bar.js to typescript.
  tools/test-js-with-node
  web/src/scroll_bar.ts
Labels: size: S

#24820 ts : Migrate debug.js to typescript
  tools/test-js-with-node
  web/src/debug.ts
Labels: size: M

#24955 integration: Remove branch names from Gogs edited PR event.
  zerver/webhooks/gogs/tests.py
  zerver/webhooks/gogs/view.py
Labels: size: S

#24963 docs: Update changelog to cover changes already staged for 7.0.
  docs/overview/changelog.md
Labels: size: L

#24974 sentry: Remove an unnecessary sudo.
  puppet/zulip/files/hooks/pre-deploy.d/sentry.hook
Labels: size: XS

#24973 css: Fix misaligned invite link.
  web/styles/zulip.css
Labels: size: XS

#24970 emails: Replace Premailer with CSS-inline.
  docs/subsystems/email.md
  requirements/common.in
  requirements/dev.txt
  requirements/prod.txt
  scripts/setup/inline_email_css.py
  tools/linter_lib/custom_check.py
  version.py
  zerver/tests/test_invite.py
Labels: size: XL

#24986 backend-auth: Add user ID to fetch api key responses.
  api_docs/changelog.md
  version.py
  zerver/openapi/zulip.yaml
  zerver/tests/test_auth_backends.py
  zerver/views/auth.py
  zerver/views/development/dev_login.py
Labels: area: authentication, area: api, area: mobile, size: M

#24996 dependencies: Upgrade JavaScript dependencies
  pnpm-lock.yaml
  version.py
Labels: size: L

#24875 ts: Convert `emoji.js` to TypeScript.
  tsconfig.json
  web/src/emoji.ts
  web/tests/emoji.test.js
  web/tests/reactions.test.js
Labels: size: XL

#25000 hashchange: Handle when history object has been marked dead.
  web/src/hashchange.js
Labels: size: S

#24947 popover_menus: Change the selector `.enter_sends` for opening tippyjs popover.
  web/src/popover_menus.js
  web/styles/compose.css
  web/styles/dark_theme.css
  web/templates/compose.hbs
Labels: size: S

#25004 help: Fix TypeError on missing article pages
  web/src/portico/help.js
Labels: size: XS

#25005 setup-apt-repo: Fix GPG check of groonga-apt-source-*.deb
  scripts/setup/apt-repos/zulip/custom.sh
Labels: size: XS, backport candidate

#24991 emails: Inline CSS during the email building process.
  docs/subsystems/email.md
  scripts/setup/inline_email_css.py
  templates/zerver/development/dev_tools.html
  templates/zerver/digest_base.html
  templates/zerver/emails/confirm_new_email.html
  templates/zerver/emails/confirm_registration.html
  templates/zerver/emails/custom_email_base.pre.html
  templates/zerver/emails/deactivate.html
  templates/zerver/emails/digest.html
  templates/zerver/emails/email_base_default.html
  templates/zerver/emails/email_base_marketing.html
  templates/zerver/emails/find_team.html
  templates/zerver/emails/followup_day1.html
  templates/zerver/emails/followup_day2.html
  templates/zerver/emails/invitation.html
  templates/zerver/emails/invitation_reminder.html
  templates/zerver/emails/macros.html
  templates/zerver/emails/missed_message.html
  templates/zerver/emails/notify_change_in_email.html
  templates/zerver/emails/notify_new_login.html
  templates/zerver/emails/password_reset.html
  templates/zerver/emails/realm_auto_downgraded.html
  templates/zerver/emails/realm_reactivation.html
  tools/build-release-tarball
  tools/check-templates
  tools/lib/provision_inner.py
  tools/update-prod-static
  zerver/lib/send_email.py
  zerver/management/commands/makemessages.py
  zerver/tests/fixtures/email/custom_emails/email_base_headers_no_headers_test.html
  zerver/tests/fixtures/email/custom_emails/email_base_headers_test.html
  zerver/tests/test_email_notifications.py
  zerver/views/development/email_log.py
Labels: size: XL

#24964 Backport "recent_senders: Fix twice sent user ids in PM to self case." (#24437)
  frontend_tests/node_tests/recent_senders.js
  static/js/people.js
  static/js/recent_senders.js
Labels: size: M

#24971 webhooks: Add body to PR Review Event message for GitHub Integration.
  zerver/webhooks/github/tests.py
  zerver/webhooks/github/view.py
Labels: area: integrations, priority: high, size: XS

#25010 [6.x] setup-apt-repo: Fix GPG check of groonga-apt-source-*.deb.
  scripts/setup/apt-repos/zulip/custom.sh
Labels: size: XS

#21952 puppet: Rotate access log files every day, not at 500M.
  docs/production/deployment.md
  puppet/zulip/manifests/nginx.pp
  puppet/zulip/manifests/profile/app_frontend.pp
  puppet/zulip/templates/logrotate/nginx.template.erb
  puppet/zulip/templates/logrotate/zulip.template.erb
  scripts/log-search
Labels: size: M

#24932 ts: Migrate header.js to typescript.
  web/src/portico/header.ts
Labels: size: S

#24860 ts migration: Convert `favicon.js` to `favicon.ts`.
  tools/test-js-with-node
  web/src/assets.d.ts
  web/src/favicon.ts
Labels: size: M, integration review

#24961 compose: Remove vertical shifts in compose when toggling preview mode.
  web/styles/rendered_markdown.css
Labels: bug, area: compose, size: S, product review

#24928 markdown: Change search and alert word highlight colors.
  web/styles/dark_theme.css
  web/styles/rendered_markdown.css
Labels: size: S, area: message feed display, redesign

#24794 style: Fix dropdown icon partially visible on small screens.
  web/styles/zulip.css
Labels: size: XS, integration review

#24219 user_groups:Sends a notification message to users when someone else add them to user group.
  zerver/openapi/curl_param_value_generators.py
  zerver/tests/test_user_groups.py
  zerver/views/user_groups.py
Labels: size: XL, integration review

#24659 notifications: Add link to new location of moved messages in Notifica…
  zerver/actions/message_edit.py
  zerver/tests/test_message_edit.py
Labels: size: M, integration review

#22118 Frontend: Add a message and button when there are no streams to show.
  web/src/stream_settings_ui.js
  web/styles/subscriptions.css
  web/templates/stream_settings/stream_settings_overlay.hbs
  web/tests/stream_events.test.js
  web/tests/stream_settings_ui.test.js
Labels: size: L, integration review

#25020 middleware: Remove ZulipCommonMiddleware patch
  zerver/middleware.py
  zproject/computed_settings.py
Labels: size: S

#25026 tests-narrow: Remove unneeded helper function in `narrow.test.js`.
  web/tests/narrow.test.js
Labels: size: L

#25025 narrow-filter: Update `Filter.describe_is_operator` for "resolved".
  web/src/filter.js
  web/tests/filter.test.js
Labels: size: S

#25027 dropdown_list_widget: Select first option on pressing "Enter" in search input.
  web/src/dropdown_list_widget.js
Labels: area: keyboard UI, priority: high, size: M, release goal

#25012 Reword user activity info from "Last active:" to "Active".
  web/src/buddy_data.js
  web/src/timerender.ts
  web/tests/buddy_data.test.js
  web/tests/popovers.test.js
  web/tests/timerender.test.js
Labels: size: L

#25013 do_render_buddy_list_tooltip: Don't show tooltip on touch devices.
  web/src/click_handlers.js
Labels: size: S

#24998 test_classes: Rename and refactor 'tornado_redirected_to_list'.
  zerver/lib/test_classes.py
  zerver/tests/test_bots.py
  zerver/tests/test_event_system.py
  zerver/tests/test_events.py
  zerver/tests/test_example.py
  zerver/tests/test_message_edit.py
  zerver/tests/test_message_flags.py
  zerver/tests/test_message_send.py
  zerver/tests/test_reactions.py
  zerver/tests/test_realm.py
  zerver/tests/test_submessage.py
  zerver/tests/test_subs.py
  zerver/tests/test_typing.py
  zerver/tests/test_user_status.py
  zerver/tests/test_user_topics.py
  zerver/tests/test_users.py
Labels: size: XL

#24465 hotkey: Toggle gear_menu on clicking `g` hotkey.
  web/src/hotkey.js
Labels: bug, size: S, integration review

#24873 user-profile: Prevent unintended clicks through profile modal overlay.
  web/styles/popovers.css
Labels: size: XS

#25017 integrations: Add Rundeck webhook integration.
  static/images/integrations/bot_avatars/rundeck.png
  static/images/integrations/logos/rundeck.svg
  static/images/integrations/rundeck/001.png
  zerver/lib/integrations.py
  zerver/webhooks/rundeck/__init__.py
  zerver/webhooks/rundeck/doc.md
  zerver/webhooks/rundeck/fixtures/duration.json
  zerver/webhooks/rundeck/fixtures/failure.json
  zerver/webhooks/rundeck/fixtures/scheduled_start.json
  zerver/webhooks/rundeck/fixtures/start.json
  zerver/webhooks/rundeck/fixtures/success.json
  zerver/webhooks/rundeck/tests.py
  zerver/webhooks/rundeck/view.py
Labels: size: XL

#25030 js: Break cyclic dependency between top_left_corner and unread_ui.
  web/src/top_left_corner.js
  web/src/unread_ui.js
Labels: size: M

#25034 integration: Remove branch names from Gitea edited PR event.
  zerver/webhooks/gitea/tests.py
  zerver/webhooks/gitea/view.py
Labels: size: S

#25038 test: Replace occurences of `uri` with `url`.
  zerver/tests/test_auth_backends.py
  zerver/tests/test_events.py
  zerver/tests/test_markdown.py
  zerver/tests/test_outgoing_http.py
  zerver/tests/test_realm_linkifiers.py
  zerver/tests/test_subs.py
  zerver/tests/test_thumbnail.py
  zerver/tests/test_upload.py
  zerver/tests/test_upload_local.py
  zerver/tests/test_upload_s3.py
Labels: size: XL

#25049 navbar: Fix alignment of `search_close` icon on device width < `$sm_min`.
  web/styles/zulip.css
Labels: size: XS

#24739 emails: Add third welcome email based on organization's type.
  templates/zerver/emails/onboarding_zulip_guide.html
  templates/zerver/emails/onboarding_zulip_guide.subject.txt
  templates/zerver/emails/onboarding_zulip_guide.txt
  zerver/lib/email_notifications.py
  zerver/models.py
  zerver/tests/test_email_log.py
  zerver/tests/test_email_notifications.py
  zerver/tests/test_example.py
  zerver/tests/test_signup.py
  zerver/tests/test_users.py
Labels: size: XL, integration review

#25032 js: Break cyclic dependency between topic_list and topic_list_data.
  web/src/topic_list.js
  web/src/topic_list_data.js
  web/tests/topic_list_data.test.js
Labels: size: S

#25054 templates: Update `invite_users_modal.hbs` for undefined variables.
  web/src/invite.js
  web/templates/invite_user_modal.hbs
Labels: size: S

#25046 search: Fix selecting all messages from recent conversations.
  web/src/narrow.js
Labels: size: S

#25057 compose: Ensure compose box is focused after inserting any content.
  web/src/compose_ui.js
Labels: size: S

#24802 time_picker: Add check for undefined 'hotkey' to fix type errors.
  web/src/flatpickr.js
Labels: bug, area: compose, size: M, javascript

#24936 workers: Rewrite missedmessage_emails with a worker thread.
  zerver/tests/test_queue_worker.py
  zerver/worker/queue_processors.py
Labels: size: XL

#25058 email: Update `followup_day2` context and email content.
  static/images/emails/day2_3.png
  templates/zerver/emails/followup_day2.html
  templates/zerver/emails/followup_day2.subject.txt
  templates/zerver/emails/followup_day2.txt
  zerver/lib/email_notifications.py
Labels: size: L

#25063 markdown: Fix lists with 3+ digit markers retaining alignment for 2 digits
  web/styles/rendered_markdown.css
Labels: size: M

#23944 compose: Disable "Message X" button for DMs when DMs are not allowed.
  web/src/compose_closed_ui.js
  web/src/people.js
  web/tests/compose.test.js
Labels: area: compose, priority: high, size: L, integration review

#25080 tippyjs: Only destroy tippy popups if they exist at all.
  web/src/tippyjs.js
Labels: size: XS

#25099 node-tests: Remove mock of `topic_list` in `topic_list_data.test`.
  web/tests/topic_list_data.test.js
Labels: size: S

#25100 search: Improve suggestions for `is:resolved` and `group-pm-with`.
  web/src/search_suggestion.js
  web/tests/search_suggestion_future.test.js
Labels: size: M

#25088 puppet: Add prod hooks to push zulip-cloud-current and notify CZO.
  puppet/zulip_ops/manifests/prod_app_frontend_once.pp
Labels: size: XS

#25070 time_picker: Set minutes to zero in global time picker.
  web/src/compose.js
  web/src/timerender.ts
  web/tests/timerender.test.js
Labels: good first issue, area: compose, priority: high, size: S, area: popovers

#24904 upload: Separate uploads into one upload bar per file.
  web/src/upload.js
  web/templates/compose_banner/upload_banner.hbs
  web/templates/message_edit_form.hbs
  web/tests/upload.test.js
Labels: size: XL, release goal

#25090 emails: Fix email styling regression.
  templates/zerver/emails/email.css
Labels: size: S

#25089 jinja2: Make sure that 500 pages have support_email set.
  zproject/jinja2/__init__.py
Labels: size: XS

#23155 icons: Change bot icon from GitHub logo to Google material icon.
  docs/THIRDPARTY
  web/shared/icons/smart-toy.svg
  web/styles/settings.css
  web/templates/settings_overlay.hbs
Labels: design, area: settings (admin/org), area: settings UI, priority: high, size: S, integration review

#24790 docs: Document how to use a self-modified dependency with Zulip in dev.
  requirements/README.md
Labels: size: S

#25126 time_picker: Reduce increment of minutes to one.
  web/src/flatpickr.js
Labels: size: XS

#25153 version: Bump PROVISION_VERSION for previous change.
  version.py
Labels: size: XS

#25142 typo: Fix a typo in block comment
  zerver/lib/events.py
Labels: size: XS

#25091 message_edit: Show modal if user cannot resolve topics.
  web/src/message_edit.js
  web/src/timerender.ts
  web/templates/resolve_topic_time_limit_error_modal.hbs
Labels: size: XL, release goal

#25134 Unread message display fixes.
  web/styles/dark_theme.css
  web/styles/zulip.css
Labels: size: M, release goal, integration review

#25074 unsubscribe-success: Update page for realm name and welcome emails.
  templates/zerver/unsubscribe_success.html
Labels: size: S

#25144 typo: Remove duplicate word in comment.
  web/src/message_list_data.js
Labels: size: XS

#25077 left_sidebar: Fix 'more topics' view scroll position.
  web/src/pm_list.js
  web/src/topic_zoom.js
Labels: area: left-sidebar, priority: high, size: S, release goal, integration review

#25158 message_list_view: Change date of sticky header more carefully.
  web/src/message_list_view.js
Labels: size: S

#24612 popovers: Fix hide popovers during scroll in recent conversations.
  web/src/recent_topics_ui.js
Labels: size: S, integration review

#25161 portico-header: Fix navbar user dropdown not working.
  web/src/portico/header.ts
Labels: size: S

#25147 tippy: Prevent second appearance of tooltips due to topic menu popover.
  web/src/tippyjs.js
Labels: size: M, integration review

#25170 emails: Remove compiled from .gitignore
  templates/zerver/emails/.gitignore
Labels: size: XS

#25031 urls: Move jwt_fetch_api_key endpoint to v1_api_mobile_patterns.
  zerver/tests/test_openapi.py
  zproject/urls.py
Labels: bug, good first issue, size: S

#24651 file_drop: Open compose immediately on file drop or paste event.
  web/src/upload.js
  web/tests/upload.test.js
Labels: size: M

#25138 streams: Fix notice appears even when the panel is not empty.
  web/src/server_events_dispatch.js
  web/src/stream_settings_ui.js
Labels: size: S

#25028 popover: Scroll to top of long message when viewing message actions.
  web/src/message_viewport.js
  web/src/popover_menus.js
Labels: size: S, integration review

#25023 compose: Prevent removal of margin on Emojis in preview markdown.
  web/styles/rendered_markdown.css
Labels: size: S

#25189 hooks: Give a bit better Zulip deploy message.
  puppet/zulip/files/hooks/common/zulip_notify.sh
  puppet/zulip/files/hooks/post-deploy.d/zulip_notify.hook
  puppet/zulip/files/hooks/pre-deploy.d/zulip_notify.hook
Labels: size: S

#25185 api-docs: Clean up documentation of API events with `message_type`.
  zerver/openapi/zulip.yaml
Labels: size: L

#25177 puppet: Move logrotate config into app_frontend_base.
  puppet/zulip/manifests/app_frontend_base.pp
  puppet/zulip/manifests/profile/app_frontend.pp
  puppet/zulip_ops/manifests/app_frontend.pp
Labels: size: S

#25178 zulip-puppet-apply: Any resources failing to apply should exit 2.
  scripts/zulip-puppet-apply
Labels: size: XS

#25174 Fix send later tooltip being cutoff by the new design of compose box deployed on CZO.
  web/src/tippyjs.js
  web/templates/compose.hbs
Labels: size: S

#25132 unmute_topic: Show all unmuted topics within muted streams in `Recent conversations`.
  web/src/recent_topics_ui.js
  web/tests/recent_topics.test.js
Labels: size: XS, release goal

#25193 events: Fix live update when deleting a starred message.
  web/src/message_events.js
Labels: bug, area: left-sidebar, area: real-time sync, size: XS

#24962 tooltips: Change `compose-send-button` tooltip dynamically.
  web/src/tippyjs.js
  web/templates/compose.hbs
Labels: bug, area: compose, size: M, release goal, integration review

#24967 tooltips: Add tippy tooltip for left sidebar elements.
  web/src/tippyjs.js
  web/templates/left_sidebar.hbs
Labels: size: L, release goal, integration review

#25139 js: Break cyclic dependency between `admin.js` and `settings.js`.
  web/src/admin.js
  web/src/hashchange.js
  web/src/settings.js
  web/tests/hashchange.test.js
Labels: size: S

#25044 js: Break cyclic dependency between `reload` and `server_events`.
  web/src/reload.js
  web/src/server_events.js
Labels: size: S

#25016 dialog_widget: Refactor `AjaxRequest` type and moved it to `types.ts`.
  web/src/channel.js
  web/src/dialog_widget.ts
  web/src/types.ts
Labels: size: M

#24423 emails: Improve "contact us" line in onboarding emails.
  templates/zerver/emails/confirm_registration.html
  templates/zerver/emails/followup_day1.html
  templates/zerver/emails/invitation.html
  templates/zerver/emails/macros.html
  templates/zerver/emails/realm_reactivation.html
Labels: size: M, release goal, integration review

#25199 help: Document new "Rename topic" option.
  help/rename-a-topic.md
Labels: release goal, integration review

#25200 e2e-tests: Replace deprecated page.waitForTimeout
  web/e2e-tests/lib/common.ts
Labels: size: XS

#25202 help: Update "Disable welcome emails" help page.
  help/disable-welcome-emails.md
Labels: release goal, integration review

#25201 help: Update /help/require-topics.
  help/require-topics.md
Labels: size: S, release goal, integration review

#25209 docs: Update development version warning text to be more explicit.
  docs/_templates/layout.html
Labels: size: XS, integration review

#25208 empty-narrow: Update banner for no starred messages.
  web/src/narrow_banner.js
  web/tests/narrow.test.js
Labels: size: S, integration review

#25206 dropdown_list_widget: Fix fading transition during focus.
  web/styles/components.css
Labels: size: XS, release goal, integration review

#25205 Fix typo in "Streams for code contributors section"
  templates/corporate/development-community.md
Labels: size: XS

#25095 compose: Change video call url text to "Join video call."
  help/start-a-call.md
  web/src/compose.js
  web/tests/compose_video.test.js
Labels: size: S, integration review

#25226 api-docs: Update docs to reference max lengths in register response.
  zerver/openapi/zulip.yaml
Labels: size: L

#25105 left_sidebar: Prioritize unmuted topics in non-zoomed topic list.
  web/src/topic_list_data.js
  web/tests/topic_list_data.test.js
Labels: size: L, release goal

#25227 emails: Update phrasing in `confirm_registration.txt`.
  templates/zerver/emails/confirm_registration.txt
Labels: size: XS

#25151 user_topics: Rerender unmuted topics in Recent conversations.
  web/src/muted_topics_ui.js
  web/src/recent_topics_ui.js
  web/tests/recent_topics.test.js
Labels: size: M, release goal, integration review

#25222 timerender: Fix expiration date on invite modal.
  web/src/invite.js
Labels: size: S, release goal, integration review

#25250 recent_conversations: Fix mute icon tooltip on focus in recent conversersations.
  web/templates/recent_topic_row.hbs
Labels: size: XS

#25246 narrow: Explicitly resume the reading state when `narrow.deactivate`.
  web/src/narrow.js
Labels: size: XS

#25259 hotkey: Clear message sent success banners too on escape keypress.
  web/src/hotkey.js
Labels: size: XS

#24934 notifications: Fix blank notification sent when no text specified.
  web/src/notifications.js
Labels: bug, priority: high, area: notifications (messages), size: S

#25221 compose: Clear search filter when opening new stream picker in compose box.
  web/src/compose_recipient.js
Labels: area: compose, priority: high, size: XS, release goal

#24965 tooltips: Convert compose box tooltips to tippy tooltips.
  web/src/compose_closed_ui.js
  web/src/tippyjs.js
  web/templates/compose.hbs
  web/tests/compose.test.js
Labels: size: XL, release goal, integration review

#23709 bookend: Add stream icons to subscribed/unsubscribed divider line.
  web/src/message_list.js
  web/src/message_list_view.js
  web/src/stream_settings_ui.js
  web/styles/zulip.css
  web/templates/bookend.hbs
Labels: priority: high, size: M, area: message feed UI, integration review

#25266 recipient_row: Correct hotkey for mute icon tooltip.
  web/templates/recipient_row.hbs
Labels: size: XS, release goal

#24942 help: Add instructions for `do not mark messages as read`.
  help/marking-messages-as-read.md
Labels: size: S, release goal, integration review

#25245 click_handlers: Allow messages being edited/viewed to be clicked.
  web/src/click_handlers.js
Labels: size: XS, integration review

#25145 css: Fix text overflow bug for pill values.
  web/styles/input_pill.css
Labels: bug, design, area: settings (user), area: settings (admin/org), size: XS, area: popovers, integration review

#25229 todo_widget: Fix cursor focus in todo lists.
  web/src/todo_widget.js
Labels: size: XS, integration review

#24816 streams: Make stream settings and create stream UI more consistent.
  docs/testing/manual-testing.md
  help/create-a-stream.md
  web/src/server_events_dispatch.js
  web/src/stream_create.js
  web/src/stream_settings_ui.js
  web/src/stream_ui_updates.js
  web/templates/stream_settings/announce_stream_checkbox.hbs
  web/templates/stream_settings/stream_creation_form.hbs
  web/templates/stream_settings/stream_types.hbs
Labels: size: L

#24930 typeahead: Hide typeahead on clicking outside after clicking its header.
  web/third/bootstrap-typeahead/typeahead.js
Labels: size: XS, integration review

#24338 popovers: Fix hide all popovers when clicked on search or settings.
  web/src/message_view_header.js
Labels: bug, size: XS, area: popovers, integration review

#24444 search: Put typeahead under search bar in the DOM with full width.
  web/src/search.js
  web/styles/search.css
  web/styles/zulip.css
  web/tests/search_future.test.js
  web/tests/search_now.test.js
  web/third/bootstrap-typeahead/typeahead.js
Labels: size: L, redesign, integration review

#25265 upgrade-zulip-from-git: CWD will be the cache directory.
  scripts/lib/upgrade-zulip-from-git
Labels: size: XS

#25135 search: Fix display of suggestion box when search bar empty.
  web/src/search.js
  web/third/bootstrap-typeahead/typeahead.js
Labels: area: search, priority: high, size: S, integration review

#25162 template: Fix padding in `unsubscribe_success.html`.
  templates/zerver/unsubscribe_success.html
Labels: size: S

#24360 left-sidebar: Increase max conversations/topics shown to 8 (no unreads) and 12 (unreads).
  web/src/pm_list_data.js
  web/tests/pm_list_data.test.js
Labels: size: M, release goal, integration review

#25039 ts: Convert `input_pill` to TypeScript and break import cycle.
  web/src/emoji.ts
  web/src/input_pill.ts
  web/tests/input_pill.test.js
Labels: size: XL

#25082 topic_sidebar_actions: Revamp topic mute/unmute UI in sidebar actions menu.
  web/src/popover_menus_data.js
  web/templates/topic_sidebar_actions.hbs
Labels: size: L

#25286 utils: Fix `process_list_in_batches`, `make_safe_digest` type safety
  zerver/lib/utils.py
Labels: size: S

#25284 Remove statsd support
  pyproject.toml
  requirements/common.in
  requirements/dev.txt
  requirements/prod.txt
  tools/test-backend
  version.py
  zerver/actions/message_flags.py
  zerver/actions/presence.py
  zerver/actions/user_activity.py
  zerver/decorator.py
  zerver/lib/cache.py
  zerver/lib/email_notifications.py
  zerver/lib/markdown/__init__.py
  zerver/lib/push_notifications.py
  zerver/lib/queue.py
  zerver/lib/rate_limiter.py
  zerver/lib/url_preview/preview.py
  zerver/lib/utils.py
  zerver/middleware.py
  zerver/tests/test_report.py
  zerver/tornado/event_queue.py
  zerver/views/home.py
  zerver/views/message_fetch.py
  zerver/views/report.py
  zproject/computed_settings.py
  zproject/default_settings.py
Labels: size: XL

#25290 ci: Run `pnpm dedupe --check`
  .github/workflows/zulip-ci.yml
Labels: size: XS

#25293 Refactored code to push REQ to top level functions
  zerver/views/auth.py
Labels: size: S

#25279 compose: Remove empty message warning border after closing.
  tools/test-js-with-node
  web/src/compose_actions.js
Labels: size: XS, integration review

#25300 portico: Tweak wording on /values.
  templates/corporate/values.md
Labels: size: S, integration review

#24870 ts migration: Convert `dark_theme.js` to `dark_theme.ts`
  tools/test-js-with-node
  web/src/dark_theme.ts
Labels: size: S

#25298 prometheus: Add an exporter for wal-g backup properties.
  puppet/zulip/files/postgresql/wal-g-exporter
  puppet/zulip_ops/manifests/profile/prometheus_server.pp
  puppet/zulip_ops/manifests/prometheus/wal_g.pp
  puppet/zulip_ops/templates/supervisor/conf.d/prometheus_wal_g_exporter.conf.template.erb
Labels: size: XL

#25296 dropdown_list_widget: Show stream icons when widget is disabled.
  web/styles/settings.css
Labels: size: XS, release goal, integration review

#25307 emails: Fix some css not being applied to emails.
  templates/zerver/emails/email.css
  templates/zerver/emails/email_base_default.html
  templates/zerver/emails/email_base_marketing.html
  templates/zerver/emails/email_base_messages.html
  zerver/lib/send_email.py
Labels: size: S

#25308 notifications: Enable desktop notifications for the UNMUTED topic.
  web/src/notifications.js
Labels: size: S

#25310 info_overlay: Fix a bug related to incorrect order of function calls.
  web/src/info_overlay.js
Labels: size: S, integration review

#25302 left-sidebar: Provide link to scheduled messages.
  web/templates/left_sidebar.hbs
Labels: size: S

#25301 wal-g: Write out a logfile.
  puppet/zulip/files/cron.d/pg-backup-and-purge
  puppet/zulip/manifests/postgresql_backups.pp
Labels: size: S

#25244 Improve compose box behavior when user does not have permission to post in a stream.
  web/src/compose_actions.js
  web/src/compose_recipient.js
  web/src/tippyjs.js
  web/styles/compose.css
  web/styles/dark_theme.css
  web/tests/compose.test.js
  web/tests/compose_actions.test.js
  web/tests/composebox_typeahead.test.js
Labels: size: L, integration review

#25306 typeahead: Always show exact matches first for streams and users.
  web/shared/src/typeahead.ts
  web/src/typeahead_helper.js
  web/tests/composebox_typeahead.test.js
Labels: bug, priority: high, size: XL, difficult, release goal, integration review, area: compose typeahead

#25315 docs: Direct-install clarification
  docs/development/setup-advanced.md
Labels: size: M

#25320 help: Improve /help/add-a-custom-linkifier page.
  help/add-a-custom-linkifier.md
Labels: size: XL, release goal

#25316 stripe: Fix invoice_plans_as_needed default value
  corporate/lib/stripe.py
Labels: size: XS

#23362 realm_redirect: Redirect always to the login page with the next parameter.
  zerver/tests/test_auth_backends.py
  zerver/tests/test_signup.py
  zerver/views/auth.py
  zerver/views/registration.py
Labels: bug, priority: high, size: M, release goal, area: public access, integration review

#25322 tippy: Remove the focus trigger from the compose-control-buttons.
  web/src/tippyjs.js
Labels: bug, area: compose, priority: high, size: S, release goal
