Repository zulip/zulip, pull requests merged in 2024-10, with the labels that each got.

#31761 message_edit: Use display: flex instead of relative positioning.
  web/styles/message_row.css
  web/templates/message_edit_form.hbs
Labels: bug, priority: high, size: S, area: popovers

#31794 [followup] reload: Only add stream_id if it's defined.
  web/src/reload.ts
Labels: size: XS

#31819 user_groups: Add `access_user_group_to_read_membership`.
  zerver/lib/user_groups.py
  zerver/views/user_groups.py
Labels: size: S

#31655 Refactor theme colors for `app_components`.
  web/styles/app_components.css
  web/styles/app_variables.css
  web/styles/dark_theme.css
Labels: area: refactoring, size: XL, integration review

#31444 fix broken symlinks to `uploads` and `settings/zulip-secrets.conf` in final `.tar.gz` file
  zerver/management/commands/backup.py
Labels: size: XS, backport candidate, integration review

#31826 help-relative: Add option for "Not subscribed" tab of channels overlay.
  help/introduction-to-channels.md
  zerver/lib/markdown/help_relative_links.py
Labels: area: documentation (user), size: XS

#31824 compose-recipients: Resize compose box text area for placeholder.
  web/src/compose_recipient.ts
Labels: size: S

#31359 saved_replies: Add new feature for saved replies.
  tools/test-js-with-node
  web/src/dropdown_widget.ts
  web/src/saved_snippets.ts
  web/src/saved_snippets_ui.ts
  web/src/server_events_dispatch.js
  web/src/state_data.ts
  web/src/tippyjs.ts
  web/src/ui_init.js
  web/styles/compose.css
  web/styles/dark_theme.css
  web/styles/zulip.css
  web/templates/add_saved_snippet_modal.hbs
  web/templates/confirm_dialog/confirm_delete_saved_snippet.hbs
  web/templates/dropdown_list.hbs
  web/templates/popovers/send_later_popover.hbs
  web/templates/tooltip_templates.hbs
  web/tests/dispatch.test.js
  web/tests/lib/events.js
  web/tests/saved_snippets.test.js
Labels: size: XL

#31835 contributor docs: Clarify how to ask for an issue to be assigned.
  CONTRIBUTING.md
Labels: size: S, integration review

#31842 saved_snippet: Prepopulate new saved snippet content.
  web/src/saved_snippets_ui.ts
  web/templates/add_saved_snippet_modal.hbs
Labels: priority: high, size: S, area: compose (UI & widgets)

#31837 buddy_data: Add participants to the top of sorted user list.
  web/src/buddy_data.ts
  web/src/buddy_list.ts
  web/tests/activity.test.js
  web/tests/buddy_data.test.js
Labels: size: L

#31848 tusd: Do not delete the .info files.
  zerver/tests/test_tusd.py
  zerver/views/tusd.py
Labels: size: M

#31845 user_groups: Do not allow click events on disabled pill container.
  web/styles/subscriptions.css
Labels: size: XS

#31839 send_later_popover: Improve on-focus styling of enter send choices.
  web/styles/compose.css
Labels: size: S

#31778 filter: Refactor code path which adjusts the narrow containing `with`.
  web/src/filter.ts
  web/tests/filter.test.js
Labels: size: XL

#31852 message_view_header: Remove unnecessary complexity.
  web/src/message_view_header.ts
Labels: size: S

#31167 stream_topic_history: Update history to only store acked message ids.
  web/src/echo.ts
  web/src/echo_state.ts
  web/src/message_events.js
  web/src/message_helper.ts
  web/src/stream_topic_history.ts
  web/tests/echo.test.js
  web/tests/stream_topic_history.test.js
Labels: size: XL, integration review

#31849 filter: Fix unparse to round-trip Unicode whitespace operands.
  web/src/filter.ts
  web/tests/filter.test.js
Labels: size: M, backport candidate, integration review

#31861 docs: Add missing links to web-public channels in development community page.
  templates/corporate/development-community.md
Labels: area: documentation (user), size: S

#31854 sponsorship: Fix `#organization-type` not found.
  web/src/billing/sponsorship.ts
Labels: size: XS

#31855 help: Refer to group settings for create/manage group at org level.
  help/manage-user-groups.md
  help/setting-up-zulip-for-a-class.md
Labels: size: M

#31742 sentry: Address Sentry JavaScript 7.x deprecations
  web/src/blueslip.ts
  web/src/channel.ts
  web/src/message_view.ts
  web/src/sent_messages.ts
  web/src/sentry.ts
  web/src/transmit.js
  web/tests/transmit.test.js
Labels: size: XL, integration review

#31869 message: Do not differentiate topics by case when aggregating.
  zerver/lib/message.py
  zerver/tests/test_event_system.py
Labels: size: S

#31867 contributor docs: Clarify how to claim a mobile issue
  CONTRIBUTING.md
Labels: size: S, integration review

#31872 web: Add missing CSS.escape calls
  web/src/dialog_widget.ts
  web/src/portico/signup.ts
  web/src/settings_linkifiers.ts
  web/src/stream_settings_components.js
  web/src/user_deactivation_ui.ts
  web/src/user_group_components.ts
Labels: size: S

#31875 slack_incoming: add ok=true to json in case of success
  zerver/webhooks/slack_incoming/view.py
Labels: size: XS, backport candidate

#31877 thumbnail: Only lock the message row, not the Attachment row.
  zerver/worker/thumbnail.py
Labels: size: S, backport candidate

#31838 reactions: Optimize DOM cost of message reactions via dynamic rendering.
  web/src/reactions.ts
  web/styles/reactions.css
  web/templates/message_body.hbs
  web/templates/message_reactions.hbs
  web/tests/reactions.test.js
Labels: area: emoji, size: XL, difficult, area: performance, area: message feed (UI), integration review

#31234 compose: Change cursor to default instead of not-allowed.
  web/styles/compose.css
Labels: area: compose (misc), size: S

#31760 export_realm: Add RealmExport model.
  zerver/actions/realm_export.py
  zerver/lib/export.py
  zerver/management/commands/export.py
  zerver/migrations/0595_add_realmexport_table_and_backfill.py
  zerver/models/__init__.py
  zerver/models/realms.py
  zerver/tests/test_events.py
  zerver/tests/test_import_export.py
  zerver/tests/test_management_commands.py
  zerver/tests/test_realm_export.py
  zerver/views/realm_export.py
  zerver/worker/deferred_work.py
Labels: size: XL

#31883 realm_export: Add a `RealmAuditLog` entry for when someone deletes an export.
  zerver/actions/realm_export.py
  zerver/models/realm_audit_logs.py
  zerver/tests/test_events.py
  zerver/views/realm_export.py
Labels: size: S

#31859 left-sidebar: Use -, _ and / as additional word separators in topic f…
  web/src/topic_list_data.ts
  web/tests/topic_list_data.test.js
Labels: area: left sidebar (misc), priority: high, size: M

#31898 copy-and-paste: Remove not required click on all messages narrow.
  web/e2e-tests/copy-and-paste.test.ts
Labels: size: S

#31900 puppeteer: Fix flaky wait for narrow change after sending a message.
  web/e2e-tests/compose.test.ts
  web/e2e-tests/drafts.test.ts
  web/e2e-tests/edit.test.ts
  web/e2e-tests/lib/common.ts
  web/e2e-tests/message-basics.test.ts
  web/e2e-tests/stars.test.ts
Labels: size: L

#31841 message_view: Update date on sticky header after rendering narrow.
  web/src/message_view.ts
  web/tests/narrow_activate.test.js
Labels: size: XS

#31886 hashchanged: Retarget near link if clicked on it again.
  web/src/hashchange.js
Labels: bug, size: S, needs reproducer, area: message feed (scrolling)

#31908 widgets: Assign zulip-button colors to edit buttons.
  web/styles/widgets.css
Labels: bug, size: S, area: widgets, integration review

#31909 nginx: Make uwsgi timeout shorter than nginx-to-uwsgi timeout.
  docs/production/reverse-proxies.md
  puppet/zulip/files/nginx/uwsgi_params
  puppet/zulip/templates/uwsgi.ini.template.erb
Labels: size: S

#31905 puppeteer: Fix incorrectly passed `false` value to check narrow change.
  web/e2e-tests/compose.test.ts
  web/e2e-tests/edit.test.ts
Labels: size: S

#31910 groups: Rework documentation of permitted values.
  api_docs/group-setting-values.md
  zerver/openapi/zulip.yaml
Labels: size: L

#31916 left_sidebar: Use unfilled star icon in sidebar navigation.
  help/include/view-starred-messages.md
  help/star-a-message.md
  web/templates/left_sidebar.hbs
Labels: size: S, integration review, area: left sidebar (display)

#31917 restart-server: Add a --only-django for rolling Django restarts.
  scripts/lib/zulip_tools.py
  scripts/restart-server
Labels: size: L

#31919 stream_data: Always initialize pin_to_top
  web/src/inbox_ui.ts
  web/src/stream_data.ts
  web/src/stream_list.ts
  web/src/sub_store.ts
Labels: size: S, integration review

#31924 nagios: Switch staging hosts to not page, but send a zulip.
  puppet/kandra/files/nagios4/commands.cfg
  puppet/kandra/files/nagios4/conf.d/services.cfg
  puppet/kandra/templates/nagios4/contacts.cfg.template.erb
Labels: size: L

#31817 typeahead: Prevent blue styling from mouse hover on typeahead item in dark mode.
  web/src/bootstrap_typeahead.ts
  web/styles/dark_theme.css
Labels: size: XS

#31925 Bug fixes for cloud=>self hosted data export.
  zerver/lib/import_realm.py
Labels: size: XS

#31921 upload: Disable the tus-js-client fingerprinting feature.
  web/src/upload.ts
Labels: size: S

#31929 popovers: Fix initial focus on popover simplebar container.
  web/templates/popovers/left_sidebar/left_sidebar_all_messages_popover.hbs
  web/templates/popovers/left_sidebar/left_sidebar_condensed_views_popover.hbs
  web/templates/popovers/left_sidebar/left_sidebar_drafts_popover.hbs
  web/templates/popovers/left_sidebar/left_sidebar_inbox_popover.hbs
  web/templates/popovers/left_sidebar/left_sidebar_recent_view_popover.hbs
  web/templates/popovers/left_sidebar/left_sidebar_starred_messages_popover.hbs
  web/templates/popovers/left_sidebar/left_sidebar_stream_setting_popover.hbs
Labels: size: S

#31937 left_sidebar: Use calendar-days icon with scheduled messages.
  docs/THIRDPARTY
  help/include/go-to-scheduled-messages.md
  web/shared/icons/scheduled-messages.svg
  web/templates/left_sidebar.hbs
  web/templates/popovers/left_sidebar/left_sidebar_condensed_views_popover.hbs
Labels: size: S, integration review, area: left sidebar (display)

#31902 help: Clarify "Enter to send" keyboard shortcuts.
  help/keyboard-shortcuts.md
Labels: size: S, integration review

#31944 tests: Use override more for realm
  web/tests/compose_validate.test.js
  web/tests/composebox_typeahead.test.js
  web/tests/dispatch.test.js
  web/tests/people.test.js
  web/tests/settings_bots.test.js
  web/tests/settings_data.test.js
  web/tests/settings_org.test.js
  web/tests/typeahead_helper.test.js
  web/tests/user_groups.test.js
Labels: size: XL

#31945 tests: Unmock realm_user_settings_defaults
  tools/test-js-with-node
  web/tests/dispatch.test.js
  web/tests/lib/index.js
  web/tests/lib/zpage_params.js
Labels: size: S

#31762 message: Improve the copy codeblock and playground buttons.
  web/shared/icons/external-link.svg
  web/src/playground_links_popover.ts
  web/styles/rendered_markdown.css
  web/templates/code_buttons_container.hbs
  web/templates/view_code_in_playground.hbs
Labels: size: L, integration review

#31312 topic: Add first-time explanation for "Resolve topic".
  web/src/message_edit.ts
  web/templates/confirm_dialog/intro_resolve_topic.hbs
  zerver/lib/onboarding_steps.py
  zerver/tests/test_onboarding_steps.py
Labels: area: onboarding, priority: high, size: L, area: popovers, integration review

#31950 starred_messages: Match header to left-sidebar icon.
  web/src/filter.ts
  web/tests/filter.test.js
Labels: size: XS, integration review, area: navbar

#31952 api-docs: Centralize history of realm message edit/move settings.
  zerver/openapi/zulip.yaml
Labels: size: XL

#31954 personal_menu_popover: Convert module to TypeScript.
  tools/test-js-with-node
  web/src/personal_menu_popover.ts
Labels: size: S, area: typescript migration

#31946 help: Create "Configure send message keys" article.
  help/collaborative-to-do-lists.md
  help/configure-send-message-keys.md
  help/create-a-poll.md
  help/include/compose-and-send-message.md
  help/include/replying-to-messages.md
  help/include/set-up-your-account.md
  help/include/sidebar_index.md
  help/keyboard-shortcuts.md
  help/mastering-the-compose-box.md
  zerver/lib/markdown/tabbed_sections.py
  zerver/lib/url_redirects.py
  zerver/openapi/zulip.yaml
Labels: area: documentation (user), size: XL

#31969 users: Fetch user groups ordered by ID to send events.
  zerver/actions/create_user.py
  zerver/actions/users.py
Labels: size: S

#31966 settings: Clean schemas and types used for group settings.
  web/src/settings_components.ts
  web/src/settings_data.ts
  web/src/settings_notifications.ts
  web/src/state_data.ts
  web/src/user_groups.ts
Labels: size: M

#31970 resolve_topic: Change dialog button text.
  web/src/message_edit.ts
Labels: size: XS

#31973 inbox: Use plural for Direct messages header.
  web/templates/inbox_view/inbox_list.hbs
Labels: size: XS, integration review, area: inbox view

#31961 state_data: Flesh out types for realm_schema.
  web/src/state_data.ts
Labels: size: L

#31962 settings: Remove unused realm_create_private_stream_policy.
  web/src/settings_components.ts
  web/src/state_data.ts
Labels: size: XS

#31960 buddy_list: Fix bug where headers weren't being updated often enough.
  web/src/buddy_list.ts
  web/tests/lib/buddy_list.js
Labels: size: S

#31708 realm_export: Add support to create "full data export" via `/export/realm`.
  api_docs/changelog.md
  api_docs/include/rest-endpoints.md
  version.py
  web/src/settings_exports.ts
  web/tests/lib/events.js
  zerver/lib/event_schema.py
  zerver/lib/export.py
  zerver/openapi/zulip.yaml
  zerver/views/realm_export.py
Labels: size: XL

#31942 message_events: Fix messages missing in combined feed.
  web/src/message_events.js
Labels: size: L, backport candidate, integration review

#31980 health: Disable RabbitMQ check if not USING_RABBITMQ
  zerver/views/health.py
Labels: size: XS, integration review

#31979 docs: Minor tweaks to thumbnailing.md.
  docs/subsystems/thumbnailing.md
Labels: size: S

#31986 user_group_edit: Fix update_group function.
  web/src/user_group_edit.js
Labels: size: XS, integration review

#31987 help: Note that email domain restrictions apply to email changes.
  help/restrict-account-creation.md
Labels: size: XS, integration review

#31956 scheduled_messages_ui: Convert module to TypeScript.
  tools/test-js-with-node
  web/src/scheduled_messages_ui.ts
Labels: size: M, area: typescript migration

#31934 message-fetch: Refactor building narrow data for load_messages.
  web/src/message_fetch.ts
Labels: size: XL

#31862 docs: Update keyboard shortcuts to always show "Fn" key option.
  help/keyboard-shortcuts.md
  tools/linter_lib/custom_check.py
  web/src/common.ts
  web/templates/keyboard_shortcuts.hbs
  web/tests/common.test.js
Labels: area: documentation (user), size: L, integration review

#31991 buddy_list: Differentiate updating and changing to an undefined filter.
  web/src/buddy_list.ts
Labels: size: XS

#31982 Fix muted messages in a stream not rendered if moved to be unmuted when narrowed to the message stream.
  web/src/message_events.js
Labels: bug, area: real-time sync, area: message feed (uncategorized), priority: high, size: S, difficult

#31939 custom_profile_fields: Make transaction no longer durable.
  zerver/actions/custom_profile_fields.py
  zerver/views/custom_profile_fields.py
  zerver/views/users.py
Labels: size: S

#31997 narrow_history: Correctly check for when we can save the narrow state.
  web/src/narrow_history.ts
Labels: size: S

#31999 typing: Check for valid user IDs when setting typing recipient.
  web/src/typing.ts
Labels: size: S

#31996 help: Update exports documentation.
  api_docs/changelog.md
  docs/overview/changelog.md
  help/export-your-organization.md
  help/include/not-human-export-format.md
  web/templates/settings/account_settings.hbs
  zerver/openapi/zulip.yaml
Labels: size: XL, integration review

#31995 stream_ui_updates: Convert module to typescript.
  tools/test-js-with-node
  web/src/settings_components.ts
  web/src/stream_ui_updates.ts
Labels: size: L, area: typescript migration

#32003 recent_conversations: Prevent DM label, icon collision.
  web/styles/recent_view.css
Labels: size: XS, area: recent-conversations, integration review

#31981 empty narrow updates for invalid channel ids
  web/src/narrow_banner.ts
  web/tests/message_view.test.js
Labels: size: M

#32005 upload: Improve error messages when uploads limited by plan.
  zerver/models/realms.py
  zerver/tests/test_tusd.py
  zerver/tests/test_upload.py
  zerver/views/tusd.py
  zerver/views/upload.py
Labels: size: XL

#32008 stream_settings_components: Convert module to typescript.
  tools/test-js-with-node
  web/src/stream_settings_components.ts
Labels: size: L, area: typescript migration

#32006 groups: Enable group-settings value on groups in production.
  api_docs/changelog.md
  api_docs/group-setting-values.md
  version.py
  web/src/user_group_create.ts
  web/src/user_group_edit.js
  zerver/lib/user_groups.py
  zerver/models/realms.py
  zerver/tests/test_realm.py
  zerver/tests/test_user_groups.py
Labels: size: XL

#31858 Fix message pointer out of view sometimes when vising a cached view.
  web/src/condense.ts
Labels: size: S, integration review

#31795 data_import: Check for invalid user emails when converting data.
  zerver/data_import/import_util.py
  zerver/data_import/mattermost.py
  zerver/data_import/rocketchat.py
  zerver/data_import/slack.py
  zerver/data_import/user_handler.py
  zerver/tests/test_mattermost_importer.py
  zerver/tests/test_rocketchat_importer.py
  zerver/tests/test_slack_importer.py
Labels: area: export/import, size: L, backport candidate, integration review

#31936 invite: Add guest visibility note with live-updating user count.
  web/src/invite.ts
  web/src/peer_data.ts
  web/src/settings_data.ts
  web/templates/guest_visible_users_message.hbs
  web/templates/invite_user_modal.hbs
  web/tests/peer_data.test.js
  web/tests/settings_data.test.js
Labels: area: invitations, size: XL, integration review

#32011 invite: Use help_link_widget in guest visible users message.
  web/templates/guest_visible_users_message.hbs
Labels: size: XS, integration review

#32015 help: Fix incorrect link in help/change-your-email-address.
  help/change-your-email-address.md
Labels: size: XS

#32017 typing: Check empty topic string if realm has mandatory topics.
  web/src/typing.ts
  web/tests/typing_status.test.js
Labels: size: L

#32013 migration: Add migration to mark 'intro_resolve_topic' as read.
  zerver/migrations/0610_mark_introduce_resolve_topic_modal_as_read.py
Labels: size: L

#32021 Invite: Add functions to access email and reusable invites by id.
  zerver/views/invite.py
Labels: size: L

#32025 portico: Align mobile subhead colors with desktop.
  web/styles/portico/navbar.css
Labels: area: portico, size: XS, integration review

#32030 stream_creation: Fix subscriber pills being too long.
  web/styles/subscriptions.css
Labels: size: S

#32029 todo-widget: Add TODO for inbound/outbound data schema refactor.
  web/src/todo_widget.ts
Labels: size: XS

#32023 stream_create: Convert module to typescript.
  tools/test-js-with-node
  web/src/stream_create.ts
  web/src/stream_settings_components.ts
Labels: size: XL, area: typescript migration

#32026 migrations: Fix unnecessary loop in 0602.
  zerver/migrations/0602_remap_can_manage_all_groups.py
Labels: size: M

#32037 Optimize import order for Rocketchat data import tool
  zerver/data_import/rocketchat.py
  zerver/tests/test_rocketchat_importer.py
Labels: area: export/import, size: XL, backport candidate

#32051 Fix flashing banners while creating channels.
  web/src/stream_create.ts
  web/src/stream_settings_ui.js
Labels: size: L, integration review

#32055 realm_export: Add realm_export_consent feature to API.
  api_docs/changelog.md
  version.py
  zerver/actions/create_user.py
  zerver/actions/user_settings.py
  zerver/lib/event_schema.py
  zerver/lib/events.py
  zerver/openapi/zulip.yaml
  zerver/tests/test_events.py
Labels: size: XL

#32045 message_events: Don't update msg if we don't have it cached locally.
  web/src/message_events.js
Labels: size: S

#32060 realm_creation: Let user choose their org type.
  templates/zerver/realm_creation_form.html
  web/e2e-tests/realm-creation.test.ts
Labels: size: XS

#32071 narrow_history: Save narrow state after we have scrolled to the msg.
  web/src/ui_init.js
Labels: size: XS

#32073 api_docs: Fix `realm_export_consent` event type docs.
  web/src/settings_users.js
Labels: size: XS

#32047 Hide close icons if user cannot manage group.
  web/styles/subscriptions.css
Labels: size: S, integration review

#32057 help: Improve groups documentation.
  help/create-user-groups.md
  help/include/how-to-create-a-user-group.md
  help/include/user-groups-intro.md
  help/manage-user-groups.md
  help/user-groups.md
Labels: size: L, integration review

#32070 user_groups: Add users to members preview list without add button.
  web/src/user_group_create_members.ts
  web/src/user_group_create_members_data.ts
  web/templates/user_group_settings/add_members_form.hbs
  web/templates/user_group_settings/new_user_group_users.hbs
Labels: size: L, integration review

#31978 compose: Show bot icon after bot name in recipient picker.
  web/src/typeahead_helper.ts
  web/styles/typeahead.css
  web/templates/typeahead_list_item.hbs
Labels: area: channel settings, size: S, area: message feed (UI), integration review, area: compose (typeahead), area: compose (recipient pickers), area: left sidebar (display)

#32043 contributor docs: Add a page on taking over prior work.
  CONTRIBUTING.md
  docs/contributing/commit-discipline.md
Labels: size: S, integration review

#31896 popovers: Refactor resend and revoke invitation confirmation modals.
  web/src/settings_invites.ts
Labels: priority: high, size: M, area: popovers, integration review

#32080 stream_edit: Fix code being called for wrong subsection.
  web/src/stream_edit.js
Labels: size: S

#32076 scheduled_messages_overlay_ui: Convert module to TypeScript.
  tools/test-js-with-node
  web/src/scheduled_messages_overlay_ui.ts
Labels: size: XL

#31890 message_scroll: Mark message as read after blue box moves past it.
  web/src/message_scroll.js
Labels: priority: high, size: S, UI experiment, integration review, chat.zulip.org review, area: message feed (scrolling)

#31967 message_header: Add date on every recipient bar in search results.
  web/src/message_list_view.ts
  web/templates/recipient_row.hbs
Labels: area: search, priority: high, size: S, area: message feed (UI), maintainer review

#32095 search: Only move cursor to end of selection if cursor is there already.
  web/src/search.ts
Labels: size: S

#32072 modals: Fix focus advancement in move topic modal.
  web/src/stream_popover.js
Labels: size: XS, integration review

#32019 topic_link_util: Add `&` as a character which can produce broken links.
  web/src/topic_link_util.ts
  web/tests/topic_link_util.test.js
Labels: size: S

#32099 message_scroll: Remove unnecessary `setTimeout` call.
  web/src/message_scroll.js
Labels: size: XS

#32108 left_sidebar: Maintain Channels hover state while showing popover.
  web/src/add_stream_options_popover.ts
  web/styles/left_sidebar.css
Labels: size: M, integration review, area: left sidebar (display), area: left sidebar (popovers)

#32064 realm_redirect: Change bottom text.
  templates/zerver/realm_redirect.html
Labels: area: portico, size: XS, integration review

#32052 message_events: Refresh `is-followed` narrow on topic visibility update.
  web/src/message_events.js
  web/src/server_events_dispatch.js
  web/src/user_topics_ui.ts
  web/tests/dispatch.test.js
Labels: size: M

#32065 channel_name_autofocus: Place the cursor automatically to channel field
  web/src/stream_settings_ui.js
Labels: size: S, integration review

#31828 user_topic_popover: Convert module to TypeScript.
  tools/test-js-with-node
  web/src/user_topic_popover.ts
Labels: size: M, integration review, maintainer review, area: typescript migration

#32104 auth: Fix invalid credentials message in login form.
  zerver/forms.py
  zerver/tests/test_signup.py
Labels: size: S

#31918 copy_and_paste: Paste fallback md link if syntax link will be broken.
  web/src/copy_and_paste.ts
  web/tests/copy_and_paste.test.js
Labels: size: M, area: compose (formatting)

#32122 right_sidebar: Correct line-height by decoupling .filters class.
  web/styles/right_sidebar.css
  web/templates/right_sidebar.hbs
Labels: bug, area: right-sidebar, size: S, integration review

#32123 empty_titles: Set line-height to match font size.
  web/styles/zulip.css
Labels: bug, size: XS, integration review, area: information density

#32110 webhooks: Fix the message sent on unassignment of Github pull requests.
  zerver/lib/webhooks/git.py
  zerver/webhooks/gitea/tests.py
  zerver/webhooks/gitea/view.py
  zerver/webhooks/github/tests.py
  zerver/webhooks/github/view.py
  zerver/webhooks/gogs/tests.py
  zerver/webhooks/gogs/view.py
Labels: size: L

#32124 remote-activity: Show remote realm mobile user and push data.
  corporate/views/remote_activity.py
Labels: size: L

#32126 auth: Tweak invalid credentials error message.
  zerver/forms.py
  zerver/tests/test_decorators.py
  zerver/tests/test_signup.py
Labels: size: S

#32131 user_group_popover: Remove period after members count.
  web/templates/popovers/user_group_info_popover.hbs
Labels: size: XS

#32116 storage: Rework static avatar files hashing logic.
  zerver/lib/storage.py
Labels: size: L

#32094 Hide new topic button when user doesn't have permission to post a message.
  web/src/stream_list.ts
  web/templates/stream_sidebar_row.hbs
  web/tests/stream_list.test.js
Labels: size: S

#32137 help: Improve documentation about starting a new conversation.
  help/include/how-to-start-a-new-topic.md
  help/include/send-dm.md
  help/include/when-to-start-a-new-topic.md
  help/introduction-to-topics.md
Labels: size: L, integration review

#32139 channel settings: Remove extraneous channel name from modal.
  web/templates/confirm_dialog/confirm_deactivate_stream.hbs
Labels: size: XS, integration review

#32161 help: Add tip mentioning who can join the group.
  help/manage-user-groups.md
Labels: size: XS

#32159 dark theme: Make critical button fixes.
  web/styles/app_components.css
Labels: bug, area: settings UI, size: S, integration review

#32145 tests: Fix order of mock.patch in use_s3_backend.
  zerver/lib/test_helpers.py
Labels: size: XS

#32143 user_groups: Include group_id in success response on group creation.
  api_docs/changelog.md
  version.py
  zerver/openapi/zulip.yaml
  zerver/views/user_groups.py
Labels: area: api, priority: high, size: M

#32162 slack_data_import: Improve hyperlink conversion.
  zerver/data_import/slack_message_conversion.py
  zerver/tests/fixtures/slack_message_conversion.json
  zerver/tests/test_slack_message_conversion.py
Labels: size: S, backport candidate, integration review

#32170 email_notifications: Prevent html2text from mangling Unicode
  zerver/data_import/mattermost.py
  zerver/lib/email_notifications.py
  zerver/tests/test_email_notifications.py
Labels: size: S, integration review

#32174 echo: Fix send messages not visible when auto narrowed to recipient.
  web/src/echo.ts
  web/tests/echo.test.js
Labels: size: XS, backport candidate

#32182 docs: Add edits, new section on crediting contributions.
  docs/contributing/continuing-unfinished-work.md
Labels: area: documentation (developer), size: M, integration review, documentation review

#32183 contributor docs: Clarify how to find abandoned issues.
  CONTRIBUTING.md
Labels: size: M, integration review

#32048 slack_incoming: add ok=false to json in case of error.
  zerver/webhooks/slack_incoming/tests.py
  zerver/webhooks/slack_incoming/view.py
Labels: area: api, size: M, backport candidate, maintainer review

#32188 left_sidebar: Open up grid for topic filter box.
  web/styles/left_sidebar.css
Labels: size: S, redesign, integration review, area: left sidebar (display)

#32190 docs: Extend section on crediting work.
  docs/contributing/continuing-unfinished-work.md
Labels: size: L

#32191 groups: Enable group-valued settings in production.
  zerver/models/realms.py
  zproject/default_settings.py
  zproject/dev_settings.py
  zproject/test_extra_settings.py
Labels: size: M
