Repository zulip/zulip, pull requests merged in 2024-12, with the labels that each got.

#32448 topics: Fix topic order after moving message without automated notice.
  web/src/message_events.js
Labels: size: M, integration review

#32534 stream_popover: Treat propagate_mode as optional
  web/src/stream_popover.ts
Labels: size: XS, priority integration review

#32517 integrations: Convert module to TypeScript
  web/src/portico/integrations.ts
  web/webpack.assets.json
Labels: size: XL, integration review, area: typescript migration

#32531 register: Optmize computing can_invite_others_to_realm.
  zerver/lib/events.py
  zerver/tests/test_event_system.py
  zerver/tests/test_home.py
Labels: size: S, difficult, area: performance, area: settings (user groups)

#32538 stream: Rename function to get defaults for stream permission groups.
  analytics/management/commands/populate_analytics_db.py
  analytics/tests/test_counts.py
  zerver/lib/bulk_create.py
  zerver/lib/streams.py
  zerver/lib/test_classes.py
Labels: size: S

#32541 support: Use datetime for push notification data in remote support.
  corporate/lib/support.py
  templates/corporate/support/push_status_details.html
Labels: size: M

#32516 buddy_list: Show unsubscribed participants in participants list.
  web/src/buddy_list.ts
Labels: size: S

#32543 buddy_list: Use opaque hover color for headings.
  web/styles/app_variables.css
Labels: area: right-sidebar, size: S, integration review

#31895 presence_data: Fetch presence data from the server
  web/src/activity.ts
  web/src/settings_users.ts
Labels: area: settings (admin/org), priority: high, size: L, integration review

#32544 Use Subversion name for svn, remove former name "Hudson" from Jenkins.
  zerver/lib/integrations.py
Labels: size: S

#32536 Fix overflow in channel dropdown widget in user profile.
  web/styles/popovers.css
Labels: size: S

#32493 invite: Fix placeholder for pill inputs.
  web/templates/invite_user_modal.hbs
Labels: size: XS

#32549 stripe: Update next_invoice_date for current logic of monthly invoices.
  corporate/lib/stripe.py
Labels: size: S

#32548 support: Get plan data without making end of billing cycle updates.
  corporate/lib/support.py
Labels: size: L, area: billing

#32551 help: Document how to configure the user list style.
  help/user-list.md
Labels: size: S

#32545 markdown: Add support of new message-link syntax in local echo.
  web/src/markdown.ts
  web/tests/markdown.test.cjs
  web/third/marked/lib/marked.cjs
Labels: size: L

#32554 help: Update user list doc.
  help/user-list.md
Labels: size: S

#32458 buttons: Add redesigned button styles.
  templates/zerver/development/design_testing/buttons.html
  templates/zerver/development/dev_tools.html
  web/src/portico/design-testing.ts
  web/styles/app_variables.css
  web/styles/buttons.css
  web/styles/portico/dev-buttons.css
  web/webpack.dev-assets.json
  zerver/tests/test_urls.py
  zerver/views/development/design_testing.py
  zproject/dev_urls.py
Labels: size: XL

#32557 test_classes: Refine assert_json_success output with exception chaining
  zerver/lib/response.py
  zerver/lib/test_classes.py
  zerver/middleware.py
Labels: area: testing-infrastructure, size: L, integration review

#32570 portico and help: Link to guide to choosing a team chat app.
  help/include/sidebar_index.md
  templates/zerver/landing_nav.html
Labels: size: S, integration review

#32564 user_groups: Refactor code creating group objects for creation events.
  zerver/actions/user_groups.py
Labels: size: S

#32573 version: Bump API_FEATURE_LEVEL.
  version.py
Labels: size: XS

#32574 settings_config: Allow using new user list style in production.
  web/src/settings_config.ts
Labels: size: S

#32576 webpack: Remove doubled slash from module path
  web/webpack.dev-assets.json
Labels: size: XS

#32577 streams: Use can_manage_default_streams to check permissions.
  zerver/decorator.py
  zerver/tests/test_subs.py
  zerver/views/streams.py
Labels: size: M

#32575 user_group_edit: Move tab key check to update groups list function.
  web/src/user_group_edit.js
Labels: size: L

#32582 css: Use --color-active-row-modal for settings overlay active rows.
  web/styles/app_variables.css
  web/styles/dark_theme.css
  web/styles/settings.css
  web/styles/subscriptions.css
Labels: size: S

#30958 narrow: Update `with` operator behaviour when message not accessible.
  api_docs/construct-narrow.md
  zerver/lib/narrow.py
  zerver/tests/test_message_fetch.py
Labels: size: XL, integration review, mentor review

#32583 message_cache: Require can_access_sender for finalize_payload
  zerver/lib/message_cache.py
  zerver/lib/outgoing_webhook.py
  zerver/tests/test_message_dict.py
  zerver/tests/test_message_fetch.py
Labels: size: S

#32585 outgoing_webhook: Optimize can_access_sender computation
  zerver/lib/outgoing_webhook.py
Labels: size: XS

#32584 export_search: Allow filtering by channel.
  zerver/management/commands/export_search.py
Labels: size: S

#32591 empty_feed_notice: Update “stream” to “channel”
  web/templates/empty_feed_notice.hbs
  web/tests/message_view.test.cjs
Labels: size: S

#31789 subscription: Remove unnecessary select_related fields and clean up.
  zerver/lib/users.py
  zerver/models/users.py
Labels: size: L

#32593 queue: Rename queue_json_publish to queue_json_publish_rollback_unsafe.
  docs/subsystems/queuing.md
  zerver/actions/user_activity.py
  zerver/decorator.py
  zerver/lib/digest.py
  zerver/lib/email_mirror.py
  zerver/lib/queue.py
  zerver/management/commands/enqueue_file.py
  zerver/migrations/0209_user_profile_no_empty_password.py
  zerver/migrations/0387_reupload_realmemoji_again.py
  zerver/signals.py
  zerver/tests/test_email_mirror.py
  zerver/tests/test_event_queue.py
  zerver/tests/test_link_embed.py
  zerver/tests/test_message_delete.py
  zerver/tests/test_message_edit_notifications.py
  zerver/tests/test_queue.py
  zerver/tests/test_queue_worker.py
  zerver/tests/test_reactions.py
  zerver/tests/test_realm_export.py
  zerver/tests/test_submessage.py
  zerver/tornado/django_api.py
  zerver/tornado/event_queue.py
  zerver/worker/deferred_work.py
  zilencer/management/commands/queue_rate.py
Labels: size: XL

#32592 message_send: Fix checking permission to send DMs.
  zerver/actions/message_send.py
Labels: size: XS

#32602 presence_data: Add fallback logic for date_joined.
  web/src/settings_users.ts
Labels: size: XS

#32590 followups for sidebar changes
  web/styles/right_sidebar.css
  web/templates/buddy_list/section_header.hbs
Labels: size: S

#32234 popovers: Hide left sidebar actions popover for empty topics.
  web/src/popover_menus_data.ts
  web/src/topic_popover.ts
  web/templates/popovers/left_sidebar/left_sidebar_topic_actions_popover.hbs
Labels: size: XL, integration review, area: left sidebar (popovers)

#32430 slack-import: Reorder and extract additional helper functions in `slack_message_conversion`
  zerver/data_import/slack_message_conversion.py
Labels: size: XL, integration review

#32606 dev_docs: Establish Other Linux tab.
  docs/development/setup-recommended.md
Labels: area: documentation (developer), size: S, integration review

#32617 register: Fix missing translation tag on 'Email'.
  templates/zerver/accounts_home.html
Labels: size: XS

#32476 portico: Remove text centering on thanks page.
  web/styles/portico/portico.css
Labels: size: S, integration review

#32611 Rename function 'open_compose_recipient_dropdown'
  web/src/compose_actions.ts
  web/src/compose_recipient.ts
  web/src/compose_reply.ts
  web/src/hotkey.js
Labels: size: S

#32623 portico: Load medium-sized avatar in preview.
  zerver/lib/users.py
  zerver/tests/test_users.py
Labels: priority: high, area: portico, size: XS

#32632 tippyjs: Fix user typeahead hidden when hovering over emoji name.
  web/src/tippyjs.ts
Labels: size: XS

#32631 help: Add pick plan step for self-hosted invoice billing upgrade.
  help/self-hosted-billing.md
Labels: area: documentation (user), size: XS, area: billing

#32619 settings: Disable the move-handle for new-choice-row.
  web/src/settings_profile_fields.ts
  web/templates/settings/profile_field_choice.hbs
Labels: area: settings UI, size: XS

#32641 upload: Show text/plain uploads inline
  zerver/lib/upload/base.py
  zerver/tests/test_upload.py
Labels: area: uploads, size: S

#32639 message_edit: Don't validate stream message mentions for DMs.
  web/src/message_edit.ts
Labels: size: S

#32492 message_events: Convert module to typescript.
  tools/test-js-with-node
  web/src/compose.js
  web/src/drafts.ts
  web/src/message_events.ts
  web/src/message_list.ts
  web/src/message_store.ts
  web/src/message_util.ts
  web/src/message_view.ts
  web/src/server_events.js
  web/src/server_events_dispatch.js
  web/src/unread.ts
Labels: size: XL, integration review, area: typescript migration

#32661 compose: Clear preview area when starting a new draft.
  web/src/compose_send_menu_popover.js
Labels: size: XS

#32659 settings_users: Remove the unused block of code.
  web/src/settings_users.ts
Labels: size: S

#32647 Group invalid inputs
  web/src/group_setting_pill.ts
  web/src/input_pill.ts
  web/src/settings_components.ts
  web/src/stream_create.ts
  web/src/user_group_create.ts
  web/styles/app_variables.css
  web/styles/compose.css
  web/styles/dark_theme.css
  web/styles/input_pill.css
  web/tests/input_pill.test.cjs
Labels: size: XL

#32663 tools: Use top-level await
  tools/check-openapi
  tools/screenshots/message-screenshot.js
  tools/screenshots/thread-screenshot.js
Labels: size: S

#32664 eslint: Clean up obsolete rules
  eslint.config.js
Labels: size: S

#32668 openapi: Fix config_options.validator documentation for webhook bots
  zerver/openapi/zulip.yaml
Labels: size: XS

#32670 hashchange: Convert module to TypeScript
  docs/subsystems/hashchange-system.md
  tools/test-js-with-node
  web/src/admin.ts
  web/src/browser_history.ts
  web/src/click_handlers.js
  web/src/gear_menu.ts
  web/src/hash_parser.ts
  web/src/hashchange.ts
  web/src/hotkey.js
  web/src/settings_panel_menu.ts
  web/src/ui_init.js
  web/tests/hashchange.test.cjs
Labels: size: L, integration review, area: typescript migration

#32658 user_events: Convert module to TypeScript
  tools/test-js-with-node
  web/src/message_live_update.ts
  web/src/message_store.ts
  web/src/people.ts
  web/src/server_events_dispatch.js
  web/src/settings_profile_fields.ts
  web/src/user_events.ts
  web/src/user_profile.ts
  web/tests/people.test.cjs
Labels: size: XL, area: typescript migration

#32667 avatar: Fix missing function call
  web/src/avatar.ts
Labels: size: XS, backport candidate, integration review

#32271 popover: Fix misleading time description in right side-bar.
  web/src/presence.ts
  web/tests/presence.test.cjs
Labels: size: S, integration review

#32677 migrations: Change migration 0639's dependency for backporting to 9.x.
  zerver/migrations/0639_zh_hant_tw_rename.py
  zerver/migrations/0640_merge_20241211_1953.py
Labels: size: S

#32673 textarea-caret: Reduce forced layout reflows.
  package.json
  patches/textarea-caret@3.1.0.patch
  pnpm-lock.yaml
Labels: size: M

#32540 conversation_participants: Track participants data in with message data.
  web/src/conversation_participants.ts
  web/src/message_list_data.ts
  web/tests/compose_closed_ui.test.cjs
  web/tests/conversation_participants.test.cjs
  web/tests/message_list.test.cjs
  web/tests/message_list_data.test.cjs
  web/tests/message_list_view.test.cjs
  web/tests/narrow_local.test.cjs
  web/tests/stream_topic_history.test.cjs
Labels: size: XL, integration review

#32687 add_emoji: Make "Preview:" translatable.
  web/templates/settings/add_emoji.hbs
Labels: size: XS

#32682 show more/less: Use em for height of button.
  web/styles/zulip.css
Labels: size: XS, area: message feed (UI), area: information density

#32683 compose: Size stream message arrow icon with em.
  web/styles/compose.css
Labels: size: XS, area: compose (recipient pickers), area: information density

#32684 settings: Fix emoji and buddy list style selectors for bigger fonts.
  web/styles/settings.css
Labels: area: settings (user), size: S, area: information density

#32669 integrations: Update example screenshot for Capistrano.
  static/images/integrations/capistrano/001.png
Labels: size: XS, integration review

#32370 popovers: Restructure the Move messages and Move topic modals.
  web/src/stream_popover.ts
  web/styles/popovers.css
  web/templates/move_topic_to_stream.hbs
Labels: priority: high, size: L, area: popovers, integration review

#32134 Added debouncing to password input field to avoid lag.
  web/src/portico/signup.ts
Labels: bug, area: onboarding, area: settings (admin/org), priority: high, size: S, integration review

#32690 Remove the second screenshot from CircleCI doc.
  zerver/webhooks/circleci/doc.md
Labels: size: XS

#32693 docs: Finish renaming AzureAD to Entra ID.
  docs/production/authentication-methods.md
  help/configure-authentication-methods.md
  help/saml-authentication.md
  templates/corporate/security.md
  zerver/lib/markdown/tabbed_sections.py
Labels: size: S

#32689 compose: Use em for enter send setting font size.
  web/styles/compose.css
Labels: area: compose (misc), size: S, area: information density

#32704 compose: Maintain circular shape for converation arrow.
  web/styles/compose.css
Labels: bug, size: XS, integration review, area: compose (recipient pickers)

#32701 api: Remove `user` object from reactions objects in the API.
  api_docs/changelog.md
  tools/check-schemas
  version.py
  web/tests/lib/events.cjs
  zerver/actions/reactions.py
  zerver/lib/event_schema.py
  zerver/lib/message_cache.py
  zerver/models/messages.py
  zerver/openapi/zulip.yaml
  zerver/tests/test_message_dict.py
  zerver/tests/test_reactions.py
Labels: size: XL

#32665 footer: Fix footer items mis-aligned in Russian.
  web/styles/portico/footer.css
Labels: size: XS

#31806 dark_theme: Adjust message colors for higher contrast.
  web/styles/app_variables.css
Labels: size: S, area: message feed (display), UI experiment, chat.zulip.org review, deployed on chat.zulip.org

#32655 [WIP] funding: Add a funding.json file.
  .github/funding.json
Labels: size: L

#32703 password: Add cancel debounce feature.
  web/src/portico/signup.ts
Labels: size: XS, integration review

#32688 updates: Add update message (level=11).
  zerver/lib/zulip_update_announcements.py
Labels: size: S

#32651 templates: Add open graph title and description for web-public view.
  templates/zerver/app/index.html
Labels: size: XS, integration review

#32717 docs: Renaming AzureAD to Entra ID, part two.
  docs/production/authentication-methods.md
  help/configure-authentication-methods.md
  help/saml-authentication.md
  templates/corporate/comparison_table_integrated.html
  templates/corporate/pricing_model.html
  zerver/openapi/zulip.yaml
  zproject/prod_settings_template.py
Labels: size: S

#32734 generate_emoji_names_table: Update SORTED_CATEGORIES
  tools/setup/emoji/generate_emoji_names_table
Labels: size: XS

#32736 run-dev: Support extra MIME types from zerver.lib.mime_types
  tools/run-dev
  zerver/lib/mime_types.py
Labels: size: M, integration review

#32404 condense: Modify height offset to collapse messages.
  web/src/condense.ts
  web/src/message_viewport.ts
Labels: size: S, UX, area: message feed (UI), chat.zulip.org review, deployed on chat.zulip.org

#32698 recent_view: Fix transparent avatar background color being changed.
  web/styles/recent_view.css
Labels: size: XS

#32700 Fix error on visiting `/customer_portal` with no parameters.
  corporate/lib/stripe.py
Labels: size: S

#32733 portico: Add Rush Stack case study.
  corporate/urls.py
  templates/corporate/case-studies/rush-stack-case-study.html
  templates/corporate/case-studies/rush-stack-case-study.md
  templates/corporate/for/communities.html
  templates/corporate/for/open-source.html
  templates/corporate/for/use-cases.md
  templates/zerver/landing_nav.html
  zerver/tests/test_docs.py
Labels: size: XL, integration review

#32746 dev-buttons: Use portico bundle
  web/webpack.dev-assets.json
Labels: size: XS

#32411 portico: Improve layout of the /go page
  templates/zerver/realm_redirect.html
  tools/lib/capitalization.py
  web/styles/portico/portico_signin.css
  zerver/tests/test_signup.py
Labels: area: portico, size: S, integration review

#32753 message_cache: Handle Django/Tornado skew for sender_recipient_id
  zerver/lib/message_cache.py
Labels: size: XS

#32748 Inline to code block to activate py env
  docs/development/setup-recommended.md
Labels: size: S, maintainer review

#32738 requirements: Add litellm as a common dependency.
  requirements/common.in
  requirements/dev.txt
  requirements/prod.txt
  version.py
Labels: size: XL

#32757 channel_descriptions: Hyphenate long words in lieu of arbitrary breaks.
  web/styles/subscriptions.css
Labels: area: channel settings, size: XS, integration review

#32758 help: Note that you may need a separate account for a call.
  help/start-a-call.md
Labels: size: S, integration review

#32759 help: Note that channel names can include Unicode emoji.
  help/include/tips-for-creating-channels.md
  help/rename-a-channel.md
Labels: integration review

#32729 buttons: Add icon-only button styles.
  templates/zerver/development/design_testing/buttons.html
  web/src/portico/design-testing.ts
  web/styles/app_variables.css
  web/styles/buttons.css
  web/styles/portico/dev-buttons.css
Labels: size: XL, maintainer review

#32760 modals: Adjust copy, layout of move/rename modals.
  web/src/stream_popover.ts
  web/styles/modal.css
  web/templates/inline_stream_or_topic_reference.hbs
Labels: size: L, area: popovers, integration review, area: left sidebar (popovers)

#32768 tests: Continue execution after blueslip.reset failures
  web/tests/lib/index.cjs
Labels: area: testing-infrastructure, size: S

#31957 realm: Schedule realm deletion time while deactivating realm.
  api_docs/changelog.md
  version.py
  web/src/settings_config.ts
  web/src/settings_org.ts
  web/src/state_data.ts
  web/templates/confirm_dialog/confirm_deactivate_realm.hbs
  zerver/actions/realm_settings.py
  zerver/lib/events.py
  zerver/migrations/0643_realm_scheduled_deletion_date.py
  zerver/models/realms.py
  zerver/openapi/zulip.yaml
  zerver/tests/test_home.py
  zerver/tests/test_realm.py
  zerver/views/realm.py
  zerver/worker/deferred_work.py
  zproject/default_settings.py
Labels: area: settings (admin/org), priority: high, size: XL, area: popovers, integration review

#32764 Improve presentation of auto-follow topics settings page
  help/include/automatically-follow-topics.md
  web/src/settings_config.ts
  web/templates/settings/notification_settings.hbs
Labels: size: S, integration review

#32802 openapi: Depluralize Attachment and Subscription schema names
  zerver/openapi/zulip.yaml
Labels: area: documentation (api and integrations), size: S

#32798 requirements: Require some swap space if installed on < 5GB RAM.
  docs/production/requirements.md
  scripts/lib/install
Labels: size: M

#32814 help-beta: Fix sidebar for more renamed pages
  help-beta/astro.config.mjs
Labels: size: S

#32819 typos: Fix typos caught by typos and mwic
  analytics/tests/test_counts.py
  api_docs/changelog.md
  api_docs/writing-bots.md
  corporate/lib/stripe.py
  docs/production/troubleshooting.md
  docs/translating/german.md
  puppet/zulip/files/supervisor/conf.d/nginx.conf
  web/e2e-tests/admin.test.ts
  web/src/hotkey.js
  web/src/settings_org.ts
  web/src/user_group_edit.ts
  zerver/tests/test_invite.py
  zerver/tests/test_upload.py
  zerver/views/tusd.py
Labels: size: M

#32833 contributor docs: Improve guidelines on how to get help.
  CONTRIBUTING.md
Labels: size: L, integration review

#32772 help: Document setting a data deletion date during organization deactivation.
  help/deactivate-your-organization.md
Labels: area: documentation (user), size: XS, integration review
