Repository zulip/zulip, pull requests merged in 2024-03, with the labels that each got.

#28776 Proposed revision for /apps
  templates/corporate/apps.html
  web/src/portico/landing-page.js
  web/styles/portico/landing_page.css
Labels: size: L, integration review

#29135 requirements: Upgrade Python requirements
  requirements/common.in
  requirements/dev.txt
  requirements/pip.txt
  requirements/prod.txt
  version.py
Labels: area: dependencies, size: XL, backport candidate

#29141 docs: Fix broken Markdown links from recent reorganization.
  docs/production/deployment.md
  docs/production/reverse-proxies.md
Labels: size: S

#29145 remote-support: Show remote realm matches if deactivated.
  corporate/views/support.py
Labels: size: S

#29146 corporate: Fix invoicing of plans on free-trial with changed schedule.
  corporate/lib/stripe.py
  corporate/migrations/0041_fix_plans_on_free_trial_with_changes_in_schedule.py
  corporate/tests/test_stripe.py
Labels: size: L

#29147 remote-support: Show deactivated servers in search results.
  corporate/tests/test_support_views.py
  corporate/views/support.py
  templates/corporate/support/remote_realm_details.html
  templates/corporate/support/remote_server_support.html
  templates/corporate/support/sponsorship_details.html
  templates/corporate/support/sponsorship_forms_support.html
  templates/corporate/support/sponsorship_request_details.html
  web/styles/portico/activity.css
Labels: size: XL

#29079 Onboarding: Improve placeholder message for dm with yourself
  web/src/narrow_banner.ts
  web/tests/narrow.test.js
Labels: area: onboarding, priority: high, size: S, integration review

#29101 docs: Better document backup/export tool tradeoffs.
  docs/production/export-and-import.md
Labels: area: documentation (production), priority: high, size: XL, backport candidate

#28996 user_status_ui: Convert module to TypeScript.
  tools/test-js-with-node
  web/src/user_status_ui.ts
Labels: size: L, area: typescript migration

#29157 user_status_ui: Fix input_field() type
  web/src/user_status_ui.ts
Labels: size: S

#29158 rows: Fix get_message_id type
  web/src/rows.ts
  web/src/upload.js
Labels: size: XS

#29159 rows: Make errors fatal in id, local_echo_id
  web/src/message_edit_history.ts
  web/src/message_viewport.ts
  web/src/rendered_markdown.ts
  web/src/rows.ts
  web/src/user_group_popover.ts
Labels: size: M, integration review

#29173 sponsorship: Add basic plan option for self hosted orgs.
  templates/corporate/billing/sponsorship.html
Labels: size: XS, area: billing

#29183 dev-vagrant-docker: Upgrade docker-systemctl-replacement to 1.5.8066
  tools/setup/dev-vagrant-docker/Dockerfile
Labels: size: XS

#29178 inbox: Remove 'default' visibility policy indicator.
  web/templates/inbox_view/inbox_row.hbs
Labels: size: XS, backport candidate

#29184 caches: Only take the realm_id, not the Realm, as a cache key function.
  zerver/actions/message_send.py
  zerver/actions/user_settings.py
  zerver/lib/cache.py
  zerver/lib/cache_helpers.py
  zerver/tests/test_soft_deactivation.py
Labels: size: M

#29174 help: Link mark as read in conversation banner to help page.
  web/templates/unread_banner/mark_as_read_only_in_conversation_view.hbs
Labels: area: onboarding, size: XS, integration review, area: compose (banners & validation)

#29187 compose: Fix bug where inserted content would not be scrolled into view.
  web/src/compose_ui.ts
  web/tests/compose_ui.test.js
Labels: size: XL

#29181 zcommand: Convert module to TypeScript.
  tools/test-js-with-node
  web/src/zcommand.ts
Labels: size: M, area: typescript migration

#29114 hotspots: Convert module to TypeScript
  docs/subsystems/hotspots.md
  tools/test-js-with-node
  web/src/hotspots.ts
  web/src/onboarding_steps.ts
  web/src/state_data.ts
Labels: size: XL, area: typescript migration

#28375 reactions: Convert module to typescript
  web/src/message_store.ts
  web/src/reactions.ts
  web/tests/reactions.test.js
Labels: size: XL, area: typescript migration

#29072 update_analytics_count: Use a correct lock mechanism.
  analytics/management/commands/update_analytics_counts.py
  zerver/lib/context_managers.py
  zproject/computed_settings.py
Labels: size: M, backport candidate

#29189 message_list: Fix delayed events finding current msg list undefined.
  web/src/message_list_tooltips.js
  web/src/ui_init.js
Labels: size: M

#29176 stream_settings: Show banner on successful stream creation.
  web/src/stream_edit.js
  web/src/stream_settings_ui.js
  web/templates/modal_banner/stream_creation_confirmation_banner.hbs
  web/templates/stream_settings/stream_settings.hbs
Labels: area: onboarding, area: stream settings, priority: high, size: M, integration review

#29172 copy_and_paste: Fix formatting of code pasted from VS Code.
  web/src/copy_and_paste.js
  web/tests/copy_and_paste.test.js
Labels: size: M

#29202 markdown-css: Wrap longer code elements in documentation.
  web/styles/portico/markdown.css
Labels: size: XS

#29205 docs: Add plan sign-up to mobile notifications sign-up instructions.
  docs/production/mobile-push-notifications.md
Labels: size: S, backport candidate

#29204 portico: Remove All plans tab at mobile scale.
  web/styles/portico/comparison_table.css
Labels: area: portico, size: S

#29194 compose: Fix topics required banner closing on enter to send.
  web/src/compose_recipient.js
Labels: size: XS, backport candidate

#29203 emoji_picker: Improve CSS and correct light bleedthrough in dark theme.
  web/styles/app_variables.css
  web/styles/dark_theme.css
  web/styles/reactions.css
Labels: area: emoji, size: XL, area: message feed UI, integration review

#29214 left_sidebar_navigation_area: Convert module to TypeScript.
  tools/test-js-with-node
  web/src/left_sidebar_navigation_area.ts
Labels: size: M

#29213 navbar: Add navigate to home view tooltip to the organization logo.
  web/src/tippyjs.ts
  web/src/user_settings.ts
  web/templates/org_logo_tooltip.hbs
Labels: area: onboarding, size: M, integration review, area: navbar

#29215 condense: Pass message objects to collapse functions.
  web/src/condense.js
  web/src/message_actions_popover.js
Labels: size: L

#29200 people: Cache results of remove_diacritics.
  web/src/people.ts
Labels: size: S

#29223 remote-support: Add ability to deactivate and reactivate remote servers.
  corporate/tests/test_support_views.py
  corporate/views/support.py
  templates/corporate/support/remote_server_support.html
  web/styles/portico/activity.css
Labels: size: XL

#29231 state_data: Fix alphabetical sorting.
  web/src/state_data.ts
Labels: size: XS

#29236 requirements: Move pip and zoneinfo forks to zulip organization
  requirements/common.in
  requirements/dev.txt
  requirements/pip.in
  requirements/pip.txt
  requirements/prod.txt
Labels: area: dependencies, size: S, backport candidate

#29233 condense: Convert module to Typescript.
  tools/test-js-with-node
  web/src/condense.ts
  web/src/message_store.ts
Labels: size: M

#29235 bookends: Add periods to stream status bookends.
  web/templates/bookend.hbs
Labels: size: S, integration review

#29237 [8.x] requirements: Move pip and zoneinfo forks to zulip organization
  requirements/common.in
  requirements/dev.txt
  requirements/pip.in
  requirements/pip.txt
  requirements/prod.txt
Labels: size: S

#28742 User Profile: Navigate tabs by arrow keys when user profile opens.
  web/src/user_profile.js
Labels: bug, area: keyboard UI, size: XS, area: popovers, integration review

#29091 portico: Align plans on /for/education with /plans.
  templates/corporate/for/education.html
  web/styles/portico/landing_page.css
Labels: size: S, integration review

#29242 create-database: Treat "zulip" db without "zerver_messages" as empty.
  scripts/setup/create-database
Labels: question, area: production installer, size: XS, backport candidate

#29195 resize_handler: Convert module to Typescript
  tools/test-js-with-node
  web/src/resize_handler.ts
Labels: size: XS, area: typescript migration

#29240 csp_violations: Migrate has_request_variables to typed_endpoint.
  zerver/views/report.py
Labels: size: S

#29244 policies: Repeat that we do not sell Personal Data.
  templates/corporate/policies/privacy.md
Labels: size: XS

#29245 upgrade-zulip-from-git: Provide a flag to use a local branch.
  scripts/lib/upgrade-zulip-from-git
Labels: size: M

#29246 typeahead: Update activity score computation algorithm for streams.
  web/src/typeahead_helper.ts
  web/tests/typeahead_helper.test.js
Labels: size: L, area: compose (typeahead)

#28488 stream_settings: Convert name to pills.
  web/src/stream_create_subscribers.js
  web/src/stream_edit_subscribers.js
  web/src/user_group_create_members.js
  web/src/user_group_edit_members.js
  web/styles/dark_theme.css
  web/styles/input_pill.css
  web/templates/stream_settings/new_stream_user.hbs
  web/templates/stream_settings/stream_member_list_entry.hbs
  web/templates/user_display_only_pill.hbs
Labels: area: stream settings, area: settings UI, priority: high, size: L, integration review, deployed on chat.zulip.org

#29262 deferred_work: Reduce batch size due to bad statistics.
  zerver/worker/queue_processors.py
Labels: size: XS

#29255 docs: Fix typo in screenshot and gif software tutorial.
  docs/tutorials/screenshot-and-gif-software.md
Labels: size: XS

#29250 realm_activity: Correct the "messages sent" column.
  corporate/views/realm_activity.py
Labels: size: XS, integration review

#29268 compose_state: Remove incorrect recipient_has_topics helper.
  web/src/compose_state.ts
  web/src/compose_validate.js
Labels: size: S

#29273 help: Rewrite article about automated notices.
  help/configure-notification-bot.md
  help/include/sidebar_index.md
Labels: size: XL, integration review, help center review

#29277 stripe: Remove unused do_change_remote_server_plan_type.
  corporate/lib/stripe.py
  corporate/tests/test_stripe.py
Labels: size: M

#29269 right-sidebar: Remove duplicate search people tooltip.
  web/src/tippyjs.ts
  web/templates/right_sidebar.hbs
  web/templates/tooltip_templates.hbs
Labels: size: S

#29270 help: Organize and extend guide for moderating open organizations.
  help/moderating-open-organizations.md
Labels: size: L, integration review

#29283 help: Clarify how automated notices are translated.
  help/configure-organization-language.md
Labels: integration review

#28789 message_view: Allow quoting selected message text, via hotkey and menu.
  web/src/compose_reply.js
  web/src/message_actions_popover.js
  web/tests/compose_actions.test.js
  web/tests/compose_ui.test.js
Labels: priority: high, size: XL, rust community request, area: message feed UI, chat.zulip.org review, area: compose (formatting)

#29284 parse_client: Migrate has_request_variables to typed_endpoint.
  zerver/middleware.py
Labels: size: S

#29112 Change topic typeahead behaviortypeahead: change topic typeahead behavior
  web/e2e-tests/drafts.test.ts
  web/e2e-tests/lib/common.ts
  web/e2e-tests/mention.test.ts
  web/src/bootstrap_typeahead.js
  web/src/composebox_typeahead.js
  web/tests/composebox_typeahead.test.js
Labels: priority: high, size: M, UI experiment, integration review, area: compose (typeahead)

#29288 help: Add example playground URL templates.
  help/code-blocks.md
Labels: size: S

#29285 help: Document new option to quote part of a message.
  help/quote-and-reply.md
Labels: size: S

#29291 portico: Add quote from UTFPR to /for/education.
  templates/corporate/for/education.html
Labels: size: S, integration review

#29292 dependencies: Upgrade JavaScript dependencies
  pnpm-lock.yaml
  version.py
Labels: size: XL

#29295 email_page: Migrate has_request_variables to typed_endpoint.
  zerver/views/development/email_log.py
Labels: size: S

#29279 api-docs: Update feature level 224 changelog and changes notes.
  api_docs/changelog.md
  zerver/openapi/zulip.yaml
Labels: size: XL

#29299 inbox: Add icon for default topic visibility policy.
  web/styles/inbox.css
  web/templates/inbox_view/inbox_row.hbs
Labels: size: S, integration review

#29260 docs: Revised performance.md for more clarity.
  docs/subsystems/performance.md
Labels: area: documentation (developer), size: S, integration review

#29293 settings: Scroll save button into view when a change made needs saving.
  web/src/settings_components.js
  web/tests/settings_org.test.js
Labels: area: settings UI, priority: high, size: S, integration review

#29286 typeahead: Convert from a jQuery plugin to a normal exported function.
  web/src/bootstrap_typeahead.js
  web/src/composebox_typeahead.js
  web/src/custom_profile_fields_ui.js
  web/src/pill_typeahead.js
  web/src/search.js
  web/src/settings_playgrounds.js
  web/tests/composebox_typeahead.test.js
  web/tests/pill_typeahead.test.js
  web/tests/search.test.js
Labels: size: XL, area: typescript migration

#28841 compose: remove color block from stream picker.
  web/src/compose_actions.js
  web/src/compose_recipient.js
  web/src/stream_bar.ts
  web/src/stream_popover.js
  web/styles/app_components.css
  web/styles/compose.css
  web/styles/message_row.css
  web/styles/popovers.css
  web/templates/compose.hbs
  web/templates/dropdown_widget_wrapper.hbs
  web/templates/move_topic_to_stream.hbs
  web/tests/compose.test.js
  web/tests/compose_actions.test.js
  web/tests/compose_state.test.js
  web/tests/composebox_typeahead.test.js
  web/tests/drafts.test.js
  web/tests/lib/compose.js
Labels: size: XL, UI experiment, redesign, chat.zulip.org review, deployed on chat.zulip.org, area: compose (recipient pickers)

#29313 corporate: Fix 'get_next_billing_cycle' for scheduled fixed-price plan.
  corporate/lib/stripe.py
Labels: size: S

#29314 tests: Avoid override_rewire for bootstrap_typeahead
  web/tests/composebox_typeahead.test.js
  web/tests/pill_typeahead.test.js
  web/tests/search.test.js
Labels: size: S

#29261 types: Migrated add_stream_options_popover to TypeScript.
  tools/test-js-with-node
  web/src/add_stream_options_popover.ts
Labels: size: M

#29316 tests: Replace unneeded override_rewire uses by whole-module mocks
  web/tests/compose_actions.test.js
  web/tests/composebox_typeahead.test.js
  web/tests/dispatch_subs.test.js
  web/tests/drafts.test.js
  web/tests/hotkey.test.js
  web/tests/stream_events.test.js
Labels: size: L

#29225 Compose Box: Unresolve empty topics.
  web/src/compose_setup.js
  web/src/message_edit.js
Labels: bug, size: S, integration review, area: message-editing (topics)

#29282 shortcut : made Shift + M work in Recent conversations and Inbox
  web/src/hotkey.js
  web/src/inbox_ui.js
Labels: area: keyboard UI, size: M, area: recent-conversations, integration review, area: inbox view

#29336 help: Clarify that the whole organization must be on the same plan.
  help/include/self-hosted-billing-multiple-organizations.md
Labels: size: XS, integration review

#29253 tooltip: Hide scroll button tooltip on transition
  web/src/message_scroll.js
Labels: size: S, area: message feed display, integration review

#29346 dev-community: Document chat.zulip.org linkifier for flutter project.
  templates/corporate/development-community.md
Labels: size: XS

#29345 stripe: Redirect to /plans if plans downgraded on /billing page visit.
  corporate/lib/stripe.py
  corporate/tests/stripe_fixtures/redirect_for_billing_page_downgrade_at_free_trial_end--Customer.create.1.json
  corporate/tests/stripe_fixtures/redirect_for_billing_page_downgrade_at_free_trial_end--Customer.modify.1.json
  corporate/tests/stripe_fixtures/redirect_for_billing_page_downgrade_at_free_trial_end--Customer.retrieve.1.json
  corporate/tests/stripe_fixtures/redirect_for_billing_page_downgrade_at_free_trial_end--Customer.retrieve.2.json
  corporate/tests/stripe_fixtures/redirect_for_billing_page_downgrade_at_free_trial_end--Customer.retrieve.3.json
  corporate/tests/stripe_fixtures/redirect_for_billing_page_downgrade_at_free_trial_end--Customer.retrieve.4.json
  corporate/tests/stripe_fixtures/redirect_for_billing_page_downgrade_at_free_trial_end--Customer.retrieve.5.json
  corporate/tests/stripe_fixtures/redirect_for_billing_page_downgrade_at_free_trial_end--Event.list.1.json
  corporate/tests/stripe_fixtures/redirect_for_billing_page_downgrade_at_free_trial_end--Invoice.list.1.json
  corporate/tests/stripe_fixtures/redirect_for_billing_page_downgrade_at_free_trial_end--SetupIntent.create.1.json
  corporate/tests/stripe_fixtures/redirect_for_billing_page_downgrade_at_free_trial_end--SetupIntent.list.1.json
  corporate/tests/stripe_fixtures/redirect_for_billing_page_downgrade_at_free_trial_end--SetupIntent.retrieve.1.json
  corporate/tests/stripe_fixtures/redirect_for_billing_page_downgrade_at_free_trial_end--checkout.Session.create.1.json
  corporate/tests/stripe_fixtures/redirect_for_billing_page_downgrade_at_free_trial_end--checkout.Session.list.1.json
  corporate/tests/stripe_fixtures/redirect_for_remote_realm_billing_page_downgrade_at_free_trial_end--Customer.create.1.json
  corporate/tests/stripe_fixtures/redirect_for_remote_realm_billing_page_downgrade_at_free_trial_end--Customer.modify.1.json
  corporate/tests/stripe_fixtures/redirect_for_remote_realm_billing_page_downgrade_at_free_trial_end--Customer.retrieve.1.json
  corporate/tests/stripe_fixtures/redirect_for_remote_realm_billing_page_downgrade_at_free_trial_end--Customer.retrieve.2.json
  corporate/tests/stripe_fixtures/redirect_for_remote_realm_billing_page_downgrade_at_free_trial_end--Customer.retrieve.3.json
  corporate/tests/stripe_fixtures/redirect_for_remote_realm_billing_page_downgrade_at_free_trial_end--Customer.retrieve.4.json
  corporate/tests/stripe_fixtures/redirect_for_remote_realm_billing_page_downgrade_at_free_trial_end--Customer.retrieve.5.json
  corporate/tests/stripe_fixtures/redirect_for_remote_realm_billing_page_downgrade_at_free_trial_end--Event.list.1.json
  corporate/tests/stripe_fixtures/redirect_for_remote_realm_billing_page_downgrade_at_free_trial_end--Invoice.list.1.json
  corporate/tests/stripe_fixtures/redirect_for_remote_realm_billing_page_downgrade_at_free_trial_end--SetupIntent.create.1.json
  corporate/tests/stripe_fixtures/redirect_for_remote_realm_billing_page_downgrade_at_free_trial_end--SetupIntent.list.1.json
  corporate/tests/stripe_fixtures/redirect_for_remote_realm_billing_page_downgrade_at_free_trial_end--SetupIntent.retrieve.1.json
  corporate/tests/stripe_fixtures/redirect_for_remote_realm_billing_page_downgrade_at_free_trial_end--checkout.Session.create.1.json
  corporate/tests/stripe_fixtures/redirect_for_remote_realm_billing_page_downgrade_at_free_trial_end--checkout.Session.list.1.json
  corporate/tests/stripe_fixtures/redirect_for_remote_server_billing_page_downgrade_at_free_trial_end--Customer.create.1.json
  corporate/tests/stripe_fixtures/redirect_for_remote_server_billing_page_downgrade_at_free_trial_end--Customer.modify.1.json
  corporate/tests/stripe_fixtures/redirect_for_remote_server_billing_page_downgrade_at_free_trial_end--Customer.retrieve.1.json
  corporate/tests/stripe_fixtures/redirect_for_remote_server_billing_page_downgrade_at_free_trial_end--Customer.retrieve.2.json
  corporate/tests/stripe_fixtures/redirect_for_remote_server_billing_page_downgrade_at_free_trial_end--Customer.retrieve.3.json
  corporate/tests/stripe_fixtures/redirect_for_remote_server_billing_page_downgrade_at_free_trial_end--Customer.retrieve.4.json
  corporate/tests/stripe_fixtures/redirect_for_remote_server_billing_page_downgrade_at_free_trial_end--Customer.retrieve.5.json
  corporate/tests/stripe_fixtures/redirect_for_remote_server_billing_page_downgrade_at_free_trial_end--Event.list.1.json
  corporate/tests/stripe_fixtures/redirect_for_remote_server_billing_page_downgrade_at_free_trial_end--Invoice.list.1.json
  corporate/tests/stripe_fixtures/redirect_for_remote_server_billing_page_downgrade_at_free_trial_end--SetupIntent.create.1.json
  corporate/tests/stripe_fixtures/redirect_for_remote_server_billing_page_downgrade_at_free_trial_end--SetupIntent.list.1.json
  corporate/tests/stripe_fixtures/redirect_for_remote_server_billing_page_downgrade_at_free_trial_end--SetupIntent.retrieve.1.json
  corporate/tests/stripe_fixtures/redirect_for_remote_server_billing_page_downgrade_at_free_trial_end--checkout.Session.create.1.json
  corporate/tests/stripe_fixtures/redirect_for_remote_server_billing_page_downgrade_at_free_trial_end--checkout.Session.list.1.json
  corporate/tests/test_stripe.py
  corporate/views/billing_page.py
Labels: size: XL

#29340 integration_url_modal: Convert module to TypeScript.
  tools/test-js-with-node
  web/src/dropdown_widget.ts
  web/src/integration_url_modal.ts
  web/src/state_data.ts
Labels: size: L

#29343 alert_words: Fix incorrect highlighting of alert words.
  web/src/alert_words.ts
  web/tests/alert_words.test.js
  web/tests/dispatch.test.js
Labels: bug, size: S, area: message feed display

#29353 sentry: Delay reading current_user and realm until they’re available
  web/src/sentry.ts
  web/src/ui_init.js
Labels: size: L

#29354 web: Fix selectors to correspond with annotated types
  web/src/billing/billing.ts
  web/src/billing/remote_billing_auth.ts
  web/src/billing/sponsorship.ts
  web/src/billing/upgrade.ts
  web/src/invite.ts
  web/src/portico/signup.ts
  web/src/realm_logo.ts
  web/src/settings_emoji.ts
  web/src/stream_list.ts
  web/src/user_search.ts
  web/tests/activity.test.js
  web/tests/user_search.test.js
Labels: size: L

#29356 send_custom_email: is_realm_admin is a property, not a real column.
  zerver/management/commands/send_custom_email.py
Labels: size: XS

#29325 tools: Fix test-documentation merge check errors.
  tools/test-documentation
Labels: size: XL

#29355 integration_url_modal: Fix input selector for runtime safety.
  web/src/integration_url_modal.ts
Labels: size: XS, area: typescript migration

#29359 release: Fix changelog output.
  tools/release
Labels: size: XS, backport candidate

#29361 help: Improve documentation for Shift+M keyboard shortcut.
  help/keyboard-shortcuts.md
  help/mute-a-topic.md
Labels: size: S, integration review

#29362 docs: Change "restart" to "flush" command in test-your-migration-changes section.
  docs/tutorials/new-feature-tutorial.md
Labels: size: XS, integration review

#29363 docs: Update broken edX reference links
  docs/git/overview.md
  docs/git/pull-requests.md
  docs/subsystems/accessibility.md
  docs/translating/internationalization.md
Labels: size: S, integration review

#29364 docs: Fix typos in the Hindi translation guide.
  docs/translating/hindi.md
Labels: size: S, integration review

#29365 docs: Fix incorrect function typo in events system.
  docs/subsystems/events-system.md
Labels: size: XS

#29344 upgrade: Minor text edits.
  templates/corporate/billing/upgrade.html
Labels: size: S

#29329 message_view: Fix error thrown on deleting stream and searching for it.
  web/src/message_list.js
Labels: size: XS, integration review

#29372 remote-support: Include billing entity name in internal billing notice.
  corporate/lib/stripe.py
  corporate/tests/test_stripe.py
  templates/zerver/emails/internal_billing_notice.html
  templates/zerver/emails/internal_billing_notice.subject.txt
  templates/zerver/emails/internal_billing_notice.txt
  zerver/tests/test_push_notifications.py
Labels: size: L

#29382 buddy_list: Ensure users are visible when hide_headers is true.
  web/src/buddy_list.ts
Labels: size: S

#29381 narrow: Remove stale comment about deactivate().
  web/src/narrow.js
Labels: size: S

#29389 info_overlay: Convert module to TypeScript.
  docs/subsystems/markdown.md
  tools/test-js-with-node
  web/src/gear_menu.js
  web/src/info_overlay.ts
Labels: size: S

#29347 dev_urls: Make requests to /docs redirect to the index.
  zerver/lib/test_helpers.py
  zproject/dev_urls.py
Labels: size: XS

#29379 puppet: Install the same version of postgres-client as the server.
  docs/production/postgresql.md
  puppet/kandra/manifests/prometheus/postgresql.pp
  puppet/zulip/manifests/postgresql_client.pp
Labels: size: S, backport candidate

#29400 kandra: Remove unnecessary libapache2-mod-wsgi.
  puppet/kandra/manifests/apache.pp
Labels: size: S

#29402 kandra: Template and insert email credentials.
  puppet/kandra/manifests/profile/grafana.pp
  puppet/kandra/templates/grafana.ini.template.erb
Labels: size: M

#29374 poll_modal: Convert module to TypeScript.
  tools/test-js-with-node
  web/src/poll_modal.ts
Labels: size: M, area: typescript migration

#29401 test_classes: Skip OpenAPI validation on exceptions
  zerver/lib/test_classes.py
Labels: area: testing-infrastructure, size: S, integration review

#29369 Naming Convention Update: Changed Recipient's HUDDLE attribute to DIRECT_MESSAGE_GROUP.
  analytics/tests/test_counts.py
  zerver/actions/message_send.py
  zerver/actions/realm_settings.py
  zerver/actions/users.py
  zerver/data_import/import_util.py
  zerver/data_import/mattermost.py
  zerver/data_import/rocketchat.py
  zerver/data_import/slack.py
  zerver/lib/display_recipient.py
  zerver/lib/email_mirror.py
  zerver/lib/email_notifications.py
  zerver/lib/export.py
  zerver/lib/import_realm.py
  zerver/lib/message.py
  zerver/lib/message_cache.py
  zerver/lib/narrow.py
  zerver/lib/push_notifications.py
  zerver/lib/recipient_users.py
  zerver/lib/retention.py
  zerver/lib/test_helpers.py
  zerver/lib/users.py
  zerver/migrations/0182_set_initial_value_is_private_flag.py
  zerver/models/recipients.py
  zerver/tests/test_email_mirror.py
  zerver/tests/test_import_export.py
  zerver/tests/test_mattermost_importer.py
  zerver/tests/test_rocketchat_importer.py
  zerver/tests/test_users.py
  zerver/tests/test_zulip_update_announcements.py
  zilencer/management/commands/populate_db.py
Labels: size: XL

#29405 register_server: Check write access to secrets file when rotate_key.
  zerver/management/commands/register_server.py
Labels: size: XS, backport candidate

#29385 notifications: Update string for redacted body notifications
  zerver/lib/push_notifications.py
  zerver/tests/test_push_notifications.py
Labels: size: S

#29417 semgrep: Broaden select_related() and prefetch_related() rules
  tools/semgrep-py.yml
Labels: size: XS

#29335 message_list_tooltips: Convert module to TypeScript.
  tools/test-js-with-node
  web/src/message_list_tooltips.ts
Labels: size: L, area: typescript migration

#29212 compose_validate: Migrate module to Typescript
  tools/test-js-with-node
  web/src/compose_validate.ts
  web/src/state_data.ts
Labels: size: XL, area: typescript migration

#29419 docs and help: Update text of no-content mobile notifications.
  docs/production/mobile-push-notifications.md
  help/mobile-notifications.md
Labels: size: S, integration review

#29422 message_list_tooltips: Fix code style issue.
  web/src/message_list_tooltips.ts
Labels: size: S

#29443 scripts: Use Apache Arrow from Groonga repository.
  scripts/setup/apt-repos/zulip/custom.sh
Labels: size: S

#29424 import: Skip "active" check, and analytics, for crossrealm bots.
  zerver/lib/import_realm.py
Labels: size: S, backport candidate

#29451 Revert "ci: Disable 8.0 upgrade suite to unbreak CI."
  .github/workflows/production-suite.yml
Labels: size: S

#29454 oneclickapps: Upgrade DigitalOcean 1-Click App to Ubuntu 22.04
  tools/oneclickapps/prepare_digital_ocean_one_click_app_release.py
Labels: size: XS

#29448 css: Fix css styling in "profile-settings-form".
  web/src/user_events.js
  web/styles/dark_theme.css
  web/styles/settings.css
Labels: size: XS

#29436 templates: Add internationalization.
  web/templates/buddy_list/view_all_subscribers.hbs
  web/templates/buddy_list/view_all_users.hbs
  web/templates/draft_table_body.hbs
  web/templates/login_to_view_image_button.hbs
  web/templates/settings/add_new_bot_form.hbs
  web/templates/settings/admin_emoji_list.hbs
  web/templates/settings/edit_bot_form.hbs
Labels: size: S

#29457 apt-repos: Use Ubuntu 22.04 Teleport repo on Ubuntu 22.04
  scripts/setup/apt-repos/teleport/jammy.list
Labels: size: XS

#29447 compose: Redesign the arrow between stream and topic.
  web/styles/app_variables.css
  web/styles/compose.css
  web/templates/compose.hbs
Labels: size: S, integration review

#29462 navbar_alert: Fix weird closing of profile-missing-required alert.
  web/src/navbar_alerts.js
Labels: size: S

#29460 kandra: Enable per-object metrics from rabbitmq.
  puppet/kandra/manifests/prometheus/rabbitmq.pp
Labels: size: XS

#29459 landing_navbar: Add `Semsee` case study link in mobile navbar.
  templates/zerver/landing_nav.html
Labels: size: S

#29444 subscriptions: Fix broken UI for subscriber search.
  web/styles/subscriptions.css
Labels: bug, area: stream settings, size: S

#29377 docs: fix pronoun use in hindi translation guide.
  docs/translating/hindi.md
Labels: size: S, integration review

#29264 Convert `settings_components` to typescript.
  tools/test-js-with-node
  web/src/settings_components.ts
  web/src/state_data.ts
  web/tests/settings_org.test.js
Labels: size: XL, area: typescript migration

#29467 kandra: Drop the munin port forward.
  puppet/kandra/templates/supervisor/conf.d/autossh_tunnels.conf.erb
Labels: size: XS

#29468 tooltips: Hide scroll button tooltip under transition.
  web/src/message_scroll.js
Labels: size: XS

#29461 Redesign: Change recent conversation icon.
  docs/THIRDPARTY
  help/include/go-to-recent-conversations.md
  web/shared/icons/recent.svg
  web/src/message_view_header.js
  web/templates/introduce_zulip_view_modal.hbs
  web/templates/left_sidebar.hbs
Labels: design, area: documentation (user), priority: high, size: M, area: left sidebar (ui)

#29473 puppet: Do not include postgresql_common for all PostgreSQL clients.
  puppet/zulip/manifests/postgresql_client.pp
Labels: size: S

#29474 settings_components: Fix assert in get_input_element_value.
  web/src/settings_components.ts
Labels: size: XS

#29476 i18n-test: Update translated strings in test_email_translation.
  zerver/tests/test_i18n.py
Labels: size: S

#29478 pythonrc: Add various frequently handy imports.
  scripts/lib/pythonrc.py
Labels: size: S

#29477 right_sidebar: Hide underline from user-list toggle button in navbar.
  web/src/sidebar_ui.ts
  web/styles/right_sidebar.css
  web/styles/zulip.css
Labels: size: S

#29483 inbox_ui: Sort names, not HTML
  web/src/inbox_ui.js
Labels: size: S

#29480 message: Add function to remove single newline in triple quoted string.
  zerver/lib/message.py
  zerver/lib/onboarding.py
  zerver/lib/zulip_update_announcements.py
  zerver/tests/test_zulip_update_announcements.py
Labels: size: L, integration review

#29488 stripe: Rename @error_handler decorator.
  corporate/lib/stripe_event_handler.py
Labels: size: S

#29493 settings: Refactor code to handle authentication methods.
  web/src/settings_components.ts
  web/src/settings_org.js
Labels: size: S

#29502 apt-repos: Disallow libmagic1 1:5.45-2 (Ubuntu 24.04)
  scripts/setup/apt-repos/zulip/zulip.pref
Labels: size: XS

#29499 Document user list + message search fixup
  help/include/sidebar_index.md
  help/search-for-messages.md
  help/user-list.md
Labels: size: L, integration review

#29504 test_decorators: Replace some deleted tests
  zerver/decorator.py
  zerver/tests/test_decorators.py
Labels: size: M

#29446 invite_user_modal: Replaced email text_area with input_pill
  tools/test-js-with-node
  web/src/email_pill.ts
  web/src/input_pill.ts
  web/src/invite.ts
  web/styles/input_pill.css
  web/templates/invite_user_modal.hbs
  web/tests/input_pill.test.js
Labels: area: onboarding, priority: high, size: XL, area: popovers, integration review

#29490 tooltips: Fix incorrect "required" tooltip on custom profile fields.
  web/src/tippyjs.ts
  web/templates/settings/custom_user_profile_field.hbs
Labels: size: S, integration review

#29230 desktop_notifications: Convert module to typescript.
  tools/test-js-with-node
  web/src/desktop_notifications.js
  web/src/desktop_notifications.ts
Labels: size: XL, area: typescript migration

#29515 kandra: rabbitmqctl may not exist when applying the initial catalog.
  puppet/kandra/manifests/prometheus/rabbitmq.pp
Labels: size: S

#29503 remote_billing: Move stripe_customer_id from server to realm if needed.
  corporate/tests/test_remote_billing.py
  zilencer/views.py
Labels: size: L

#29518 stripe: Add period information for generated invoices.
  corporate/lib/stripe.py
  corporate/tests/stripe_fixtures/upgrade_by_card--Charge.list.1.json
  corporate/tests/stripe_fixtures/upgrade_by_card--Customer.modify.1.json
  corporate/tests/stripe_fixtures/upgrade_by_card--Customer.retrieve.2.json
  corporate/tests/stripe_fixtures/upgrade_by_card--Customer.retrieve.3.json
  corporate/tests/stripe_fixtures/upgrade_by_card--Customer.retrieve.4.json
  corporate/tests/stripe_fixtures/upgrade_by_card--Customer.retrieve.5.json
  corporate/tests/stripe_fixtures/upgrade_by_card--Customer.retrieve.6.json
  corporate/tests/stripe_fixtures/upgrade_by_card--Event.list.1.json
  corporate/tests/stripe_fixtures/upgrade_by_card--Event.list.2.json
  corporate/tests/stripe_fixtures/upgrade_by_card--Event.list.3.json
  corporate/tests/stripe_fixtures/upgrade_by_card--Event.list.4.json
  corporate/tests/stripe_fixtures/upgrade_by_card--Invoice.create.1.json
  corporate/tests/stripe_fixtures/upgrade_by_card--Invoice.finalize_invoice.1.json
  corporate/tests/stripe_fixtures/upgrade_by_card--Invoice.list.2.json
  corporate/tests/stripe_fixtures/upgrade_by_card--Invoice.pay.1.json
  corporate/tests/stripe_fixtures/upgrade_by_card--InvoiceItem.create.1.json
  corporate/tests/stripe_fixtures/upgrade_by_card--SetupIntent.create.1.json
  corporate/tests/stripe_fixtures/upgrade_by_card--SetupIntent.list.1.json
  corporate/tests/stripe_fixtures/upgrade_by_card--SetupIntent.retrieve.1.json
  corporate/tests/stripe_fixtures/upgrade_by_card--checkout.Session.create.1.json
  corporate/tests/stripe_fixtures/upgrade_by_card--checkout.Session.list.1.json
  corporate/tests/stripe_fixtures/upgrade_by_invoice--Event.list.1.json
  corporate/tests/stripe_fixtures/upgrade_by_invoice--Event.list.2.json
  corporate/tests/stripe_fixtures/upgrade_by_invoice--Event.list.3.json
  corporate/tests/stripe_fixtures/upgrade_by_invoice--Invoice.create.1.json
  corporate/tests/stripe_fixtures/upgrade_by_invoice--Invoice.finalize_invoice.1.json
  corporate/tests/stripe_fixtures/upgrade_by_invoice--Invoice.list.1.json
  corporate/tests/stripe_fixtures/upgrade_by_invoice--Invoice.pay.1.json
  corporate/tests/stripe_fixtures/upgrade_by_invoice--InvoiceItem.create.1.json
  corporate/tests/test_stripe.py
Labels: size: XL
