Repository zulip/zulip, pull requests merged in 2024-05, with the labels that each got.

#29892 updates: Add update message (level=3).
  zerver/lib/zulip_update_announcements.py
Labels: size: S, integration review

#29912 zulip-view-modal: Update translated strings for stream/channel rename.
  web/templates/introduce_zulip_view_modal.hbs
Labels: size: S

#29917 sidebar_ui: Fix right sidebar acting as an overlay even on wide width.
  web/src/sidebar_ui.ts
Labels: size: S

#29919 support: Send demo request emails to sales@ email.
  corporate/tests/test_stripe.py
  corporate/views/support.py
Labels: size: S

#29907 input_pill: Register `onTextInputHook` inside `input` event handler.
  web/src/input_pill.ts
  web/tests/input_pill.test.js
Labels: size: S

#29860 keyboard-shortcuts: Update the to-do list example to match documentation.
  web/src/info_overlay.ts
Labels: size: L

#29927 unread: Fix addition to unread_mention_topics sets
  web/src/unread.ts
Labels: size: S, area: recent-conversations, integration review

#29923 data_import: Remove gitter data import tool.
  docs/production/install.md
  help/import-from-gitter.md
  help/include/migrating-from-other-chat-tools.md
  help/include/sidebar_index.md
  templates/corporate/comparison_table_integrated.html
  templates/corporate/for/business.html
  templates/corporate/for/communities.md
  templates/corporate/for/open-source.html
  templates/corporate/for/research.html
  templates/zerver/create_realm.html
  tools/test-backend
  zerver/data_import/gitter.py
  zerver/data_import/import_util.py
  zerver/lib/import_realm.py
  zerver/management/commands/convert_gitter_data.py
  zerver/tests/fixtures/gitter_data.json
  zerver/tests/test_gitter_importer.py
Labels: size: XL

#29904 message_row: Extract selectors from .message_row
  web/styles/message_row.css
Labels: area: message-editing, size: XL, area: message feed (display), area: message feed (UI), integration review

#29913 popovers: Move from global popover min-width to per-popover basis.
  web/styles/app_variables.css
  web/styles/popovers.css
Labels: size: M, area: popovers, integration review

#29840 help: Update documentation on switching themes.
  help/dark-theme.md
  help/include/personal-menu.md
Labels: area: documentation (user), size: S

#29906 contributor docs: Extend help center writing style documentation.
  docs/documentation/helpcenter.md
Labels: size: S, integration review

#29915 message_header: Build message_header.css from zulip.css header styles.
  web/src/bundles/app.ts
  web/styles/message_header.css
  web/styles/zulip.css
Labels: size: XL, area: message feed (display), integration review

#29861 Compose(typeahead): Remove text color change on hover.
  web/styles/dark_theme.css
Labels: bug, design, size: XS, integration review, area: compose (typeahead)

#29338 message_edit: Fix local echo of message edit.
  web/src/echo.js
Labels: size: S, integration review

#29895 billing: Document how to test different billing states.
  docs/subsystems/billing.md
Labels: size: L

#29936 help: Remove description of transition from self-hosted billing page.
  help/self-hosted-billing.md
Labels: size: XL

#29911 left_sidebar: Add colon `:` to the list of stream word separators.
  web/src/stream_list_sort.ts
  web/tests/stream_list_sort.test.js
Labels: size: M, integration review

#29940 message_view_header: Extract styles to own file.
  web/src/bundles/app.ts
  web/styles/message_view_header.css
  web/styles/zulip.css
Labels: size: XL, area: message feed (display), area: message feed (UI), integration review

#29943 drafts_overlay_ui: Remove incorrect $ prefix from non-jQuery variable
  web/src/drafts_overlay_ui.js
Labels: size: XS

#29941 left_sidebar: Apply grid to 'more conversations' DM row.
  web/styles/left_sidebar.css
  web/templates/more_pms.hbs
Labels: size: S, integration review, area: left sidebar (display)

#29939 message_header: Bring over control hover selectors.
  web/styles/message_header.css
  web/styles/zulip.css
Labels: size: M, area: message feed (UI), integration review

#29938 message_row: Establish clarifying messagebox-includes-sender class.
  web/styles/message_row.css
  web/templates/single_message.hbs
Labels: size: XS, area: message feed (display), integration review

#29947 Combining HTMLSelectElement & {type: "select-one"} into HTMLSelectOneElement.
  web/src/invite.ts
  web/src/settings_components.ts
  web/src/types.ts
Labels: area: refactoring, size: M

#29952 support: Rate limit demo form requests.
  corporate/views/support.py
Labels: size: XS

#29951 katex_server: Fix implicit use of `any`
  web/server/katex_server.ts
Labels: size: S, integration review

#29876 Fix check for when to fetch more messages.
  web/src/message_list_view.js
  web/src/message_scroll.js
  web/src/message_viewport.ts
Labels: size: M

#29918 echo: Remove checks on current message list.
  web/src/echo.js
Labels: size: M

#29961 migrations: Merge 0517 as a no-op.
  zerver/migrations/0517_resort_edit_history.py
  zerver/migrations/0518_merge.py
Labels: size: M

#29960 topic: Fix history order for topic moves.
  zerver/lib/topic.py
  zerver/migrations/0517_resort_edit_history.py
Labels: size: M

#29963 narrow_state: Fix combined feed narrowing near msg id of muted message.
  web/src/narrow_state.ts
Labels: size: XS

#29945 left_sidebar: Correct vertical alignment on 'more conversations.'
  web/styles/left_sidebar.css
Labels: size: XS, integration review, area: left sidebar (display)

#29969 missedmessage_emails: Backoff the background worker retries.
  zerver/worker/missedmessage_emails.py
Labels: size: S

#29972 backport: Fix the commit-ids that are used.
  tools/backport-pull-request
Labels: size: L, backport candidate

#29971 contributor docs: Update links to PR guides.
  CONTRIBUTING.md
Labels: size: S, integration review

#29935 documentation: Described display_in_profile_summary field as optional.
  zerver/openapi/zulip.yaml
Labels: size: S, integration review

#29865 rendered_markdown: Fix code getting copied when visiting custom playground.
  web/src/rendered_markdown.ts
  web/tests/rendered_markdown.test.js
Labels: bug, priority: high, size: S, area: message feed (UI), integration review

#29983 stream_popover: Fix broken move topic to stream popover.
  web/src/bootstrap_typeahead.ts
  web/src/composebox_typeahead.js
  web/src/stream_popover.js
Labels: size: S

#29980 Preparatory commits extracted from #29783
  web/src/bootstrap_typeahead.ts
  web/src/composebox_typeahead.js
  web/tests/composebox_typeahead.test.js
Labels: size: M

#29993 8.x backport of 28920
  web/styles/reactions.css
  web/styles/zulip.css
Labels: size: S

#29990 widgets: Always render and activate widgets in the current view.
  web/src/narrow.js
  web/src/submessage.ts
  web/src/widgetize.ts
  web/tests/widgetize.test.js
Labels: size: L

#29995 requirements: Upgrade Python requirements
  requirements/dev.txt
  requirements/prod.txt
Labels: size: M, backport candidate

#29996 8.x backport of 29722
  scripts/lib/install
  scripts/lib/supported-os
  scripts/lib/upgrade-zulip-stage-2
  scripts/lib/upgrade-zulip-stage-3
Labels: size: XL

#30002 docs: Update for wal-g not being required for replication.
  docs/production/postgresql.md
Labels: size: M

#30010 portico: Tweak quote.
  templates/corporate/for/open-source.html
  templates/corporate/for/research.html
Labels: integration review

#30005 message_fetch: Fetch till 180 days of history or we reach backfill cap.
  web/src/message_fetch.js
Labels: size: M

#30013 portico: Update features table to reflect current storage policy.
  templates/corporate/comparison_table_integrated.html
Labels: size: XS, integration review

#29992 8.x backport of 28477
  web/src/compose_recipient.js
  web/src/compose_validate.js
  web/src/people.ts
  zerver/actions/message_send.py
  zerver/tests/test_message_send.py
Labels: size: L

#29521 mark unread: Use more efficient endpoint.
  web/src/unread_ops.js
Labels: area: api, size: XL, area: performance, maintainer review

#29976 models: Replace realm.uri with realm.url.
  confirmation/models.py
  corporate/lib/stripe.py
  corporate/lib/support.py
  corporate/views/portico.py
  templates/corporate/support/realm_details.html
  templates/zerver/development/dev_login.html
  templates/zerver/emails/find_team.html
  templates/zerver/emails/find_team.txt
  templates/zerver/emails/password_reset.html
  templates/zerver/emails/password_reset.txt
  templates/zerver/emails/realm_auto_downgraded.html
  templates/zerver/emails/realm_auto_downgraded.txt
  tools/generate-integration-docs-screenshot
  zerver/actions/create_realm.py
  zerver/actions/realm_settings.py
  zerver/context_processors.py
  zerver/forms.py
  zerver/lib/avatar.py
  zerver/lib/email_notifications.py
  zerver/lib/events.py
  zerver/lib/markdown/__init__.py
  zerver/lib/onboarding.py
  zerver/lib/push_notifications.py
  zerver/lib/remote_server.py
  zerver/lib/scim.py
  zerver/lib/send_email.py
  zerver/lib/upload/__init__.py
  zerver/lib/upload/local.py
  zerver/lib/url_encoding.py
  zerver/management/commands/list_realms.py
  zerver/management/commands/send_password_reset_email.py
  zerver/middleware.py
  zerver/migrations/0373_fix_deleteduser_dummies.py
  zerver/migrations/0501_delete_dangling_usermessages.py
  zerver/models/realms.py
  zerver/openapi/test_curl_examples.py
  zerver/tests/test_auth_backends.py
  zerver/tests/test_middleware.py
  zerver/tests/test_push_notifications.py
  zerver/tests/test_realm.py
  zerver/tests/test_realm_export.py
  zerver/tests/test_signup.py
  zerver/tests/test_subdomains.py
  zerver/views/auth.py
  zerver/views/development/dev_login.py
  zerver/views/realm.py
  zerver/views/registration.py
  zerver/views/users.py
  zerver/views/video_calls.py
  zilencer/management/commands/populate_billing_realms.py
  zproject/backends.py
Labels: size: XL

#30015 kandra: Fix cron specification, to run once, not every minute from 7-8.
  puppet/kandra/manifests/prod_app_frontend_once.pp
Labels: size: XS

#29774 export: Create REALM_EXPORTED audit log for exports via shell.
  zerver/lib/export.py
  zerver/management/commands/export.py
Labels: size: S, integration review

#30009 widgets: Cache event handler instead of entire jquery for each widget.
  web/src/poll_widget.ts
  web/src/submessage.ts
  web/src/todo_widget.js
  web/src/widgetize.ts
  web/tests/poll_widget.test.js
  web/tests/widgetize.test.js
Labels: size: L

#29762 zulip_updates: Send group DM to admins for realm imported from other product.
  zerver/lib/import_realm.py
  zerver/lib/zulip_update_announcements.py
  zerver/tests/test_import_export.py
  zerver/tests/test_mattermost_importer.py
  zerver/tests/test_rocketchat_importer.py
  zerver/tests/test_slack_importer.py
  zerver/tests/test_zulip_update_announcements.py
Labels: size: XL

#30022 realm: Add an alias `realm_url` and deprecate `realm_uri` in the API.
  api_docs/changelog.md
  version.py
  zerver/context_processors.py
  zerver/lib/events.py
  zerver/lib/push_notifications.py
  zerver/openapi/zulip.yaml
  zerver/tests/test_auth_backends.py
  zerver/tests/test_event_system.py
  zerver/tests/test_home.py
  zerver/tests/test_push_notifications.py
  zerver/tests/test_realm.py
  zerver/views/auth.py
  zerver/views/realm.py
Labels: size: L

#30024 poll_widget: Remove handle_events augmentation of jQuery interface
  web/src/poll_widget.ts
Labels: size: S

#30032 requirements: Drop the --no-binary for lxml and xmlsec.
  requirements/common.in
  requirements/dev.txt
  requirements/prod.txt
Labels: size: S

#30012 migrations: Update 0516 to handle invites with non-default streams.
  zerver/migrations/0516_fix_confirmation_preregistrationusers.py
Labels: size: M

#30034 compose: Fix bug in preview where image at the end would be misaligned.
  web/styles/rendered_markdown.css
Labels: size: XS, area: markdown (embeds/previews), integration review

#30030 recent_view: Fix filter input focused on load.
  web/src/recent_view_ui.js
  web/src/ui_init.js
Labels: size: S

#30035 help: Update suggested text for linking to Zulip.
  help/linking-to-zulip-website.md
Labels: size: XS, integration review

#30047 mark unread: Use correct value of include_anchor in case of errors.
  web/src/unread_ops.js
Labels: size: M

#30046 stars: Fix flaky test due to message list not yet rendered.
  web/e2e-tests/stars.test.ts
Labels: size: S

#30048 apt-repos: Deprioritize libgroonga0 14.0.3-1
  scripts/setup/apt-repos/zulip/zulip.pref
Labels: size: XS

#30058 buddy_list: Fix empty_list_widget_for_list.hbs usage
  web/src/buddy_list.ts
Labels: size: XS, integration review

#30063 onboarding: Modify content on onboarding messages.
  zerver/lib/onboarding.py
  zerver/tests/test_signup.py
Labels: size: XL

#30057 Improve pages when there is no organization or it has been deactivated
  templates/zerver/deactivated.html
  templates/zerver/invalid_realm.html
  zerver/middleware.py
  zerver/tests/test_auth_backends.py
  zerver/tests/test_decorators.py
  zerver/tests/test_docs.py
  zerver/tests/test_signup.py
  zerver/views/home.py
Labels: area: portico, size: L, integration review

#30040 css: Fix theme switch changing color of elements at different intervals.
  web/styles/app_components.css
  web/styles/compose.css
  web/styles/zulip.css
Labels: size: S

#30079 portico: Update title/job for quote author.
  templates/corporate/for/research.html
Labels: size: XS, integration review

#30070 onboarding: Fixes bugs from #29421.
  zerver/actions/create_user.py
  zerver/lib/onboarding.py
Labels: size: L

#30081 import: Fix import of Stream.creator field.
  zerver/lib/import_realm.py
  zerver/tests/test_import_export.py
Labels: size: M

#30084 recent_topics: Change background color in dark mode on hover on a row.
  web/styles/dark_theme.css
Labels: size: XS

#30088 unread_ops: Fix `do_mark_unread_by_narrow` arguments, convert module to TypeScript
  tools/test-js-with-node
  web/src/message_lists.ts
  web/src/unread_ops.ts
Labels: size: XL, integration review, area: typescript migration

#30092 user_topics_ui: Fix backwards setTimeout arguments, convert module to TypeScript
  tools/test-js-with-node
  web/src/message_lists.ts
  web/src/user_topics.ts
  web/src/user_topics_ui.ts
Labels: size: S, integration review, area: typescript migration

#30093 help: Document that groups can be DM addressees.
  help/include/send-dm.md
Labels: size: XS

#30099 unread_ops: Fix unable to mark messages as read in Inbox view.
  web/src/unread_ops.ts
Labels: size: S

#30096 copy_and_paste: Fix bugs surfaced by typescript migration.
  web/src/copy_and_paste.ts
Labels: size: XS

#30089 onboarding: Don't send zulip update message during new realm creation.
  zerver/lib/onboarding.py
  zerver/lib/zulip_update_announcements.py
  zerver/tests/test_signup.py
  zerver/tests/test_zulip_update_announcements.py
Labels: area: onboarding, area: bots, priority: high, size: L

#30082 streams: Set creator for some initial streams in populate_db.
  zerver/lib/bulk_create.py
  zerver/tests/test_subs.py
  zilencer/management/commands/populate_db.py
Labels: size: M, integration review

#30100 api-docs: Update feature level 261 documentation.
  api_docs/changelog.md
  version.py
  zerver/openapi/zulip.yaml
Labels: size: L

#30007 api_documentation: Document "/invites/multiuse/{invite_id}" endpoint.
  api_docs/changelog.md
  api_docs/include/rest-endpoints.md
  zerver/openapi/python_examples.py
  zerver/openapi/zulip.yaml
  zerver/tests/test_openapi.py
Labels: size: L, integration review

#30103 org-settings: Update tab for default channel settings.
  web/src/settings_sections.js
  web/src/settings_streams.js
  web/styles/settings.css
  web/templates/invite_user_modal.hbs
  web/templates/settings/default_streams_list_admin.hbs
  web/templates/settings_overlay.hbs
Labels: size: S

#28595 docs: Updated "Private messages" -> "Direct messages" #26939
  docs/translating/chinese.md
  docs/translating/finnish.md
  docs/translating/hindi.md
  docs/translating/polish.md
  docs/translating/urdu.md
Labels: size: M

#27943 Revert "ci: Temporarily upgrade postgresql-client-common before upgrading."
  .github/workflows/production-suite.yml
Labels: size: S

#29545 popovers: Refine word wrapping in user profile.
  web/styles/popovers.css
Labels: size: XS, integration review

#29546 settings: fixed colorpicker so it closes when scrolling stream settings
  web/src/stream_edit.js
  web/tests/stream_settings_ui.test.js
Labels: bug, area: stream settings, size: L, maintainer review

#29427 docs: Remove flush memcached command as it's auto-done by migration.
  docs/subsystems/schema-migrations.md
  docs/tutorials/new-feature-tutorial.md
Labels: size: M

#29957 support: Set discounted price instead percentage for customers.
  corporate/lib/activity.py
  corporate/lib/stripe.py
  corporate/lib/support.py
  corporate/migrations/0043_remove_customer_default_discount_and_more.py
  corporate/models.py
  corporate/tests/test_activity_views.py
  corporate/tests/test_stripe.py
  corporate/tests/test_support_views.py
  corporate/views/installation_activity.py
  corporate/views/support.py
  templates/corporate/billing/upgrade.html
  templates/corporate/support/current_plan_details.html
  templates/corporate/support/next_plan_details.html
  templates/corporate/support/realm_details.html
  templates/corporate/support/remote_realm_details.html
  templates/corporate/support/remote_server_support.html
  templates/corporate/support/sponsorship_details.html
  templates/corporate/support/sponsorship_discount_forms.html
  templates/corporate/support/support.html
  tools/linter_lib/custom_check.py
  web/src/base_page_params.ts
  web/src/billing/upgrade.ts
  web/src/support/support.ts
  web/styles/portico/activity.css
  web/webpack.assets.json
  zerver/lib/validator.py
Labels: size: XL, integration review

#30107 zerver: Use correct flags to check if this is a self hosted server.
  templates/zerver/deactivated.html
  templates/zerver/invalid_realm.html
Labels: size: S

#30108 hashchange: Fix infinite home view <-> narrow loop on escape keypress.
  web/src/hashchange.js
Labels: size: S

#30113 server_events: Fix infinite loading indicator on page load.
  web/src/message_util.ts
  web/src/server_events.js
  web/tests/server_events.test.js
Labels: size: S

#29567 fix: Added a try/except case when trying to execute the astimezone function.
  zerver/lib/markdown/__init__.py
  zerver/tests/fixtures/markdown_test_cases.json
Labels: size: S, maintainer review, completion candidate

#29383 Fix edit box losing focus on editing immediately a sent message.
  web/src/message_list_view.js
Labels: size: L, integration review

#30120 composebox_typeahead: Clean up initalize method to take JQuery object.
  web/src/composebox_typeahead.ts
  web/src/message_edit.js
Labels: size: S

#30119 typeahead_helper: Clean up current_stream check.
  web/src/typeahead_helper.ts
Labels: size: S

#30124 portico: Mention website previews instead of Tweet previews.
  templates/corporate/for/business.html
  templates/corporate/for/open-source.html
Labels: size: XS, integration review

#30133 do_deactivate_realm: Add deactivation_reason kwarg.
  corporate/tests/test_stripe.py
  corporate/tests/test_support_views.py
  corporate/views/support.py
  tools/test-api
  zerver/actions/create_realm.py
  zerver/actions/realm_settings.py
  zerver/management/commands/deactivate_realm.py
  zerver/management/commands/export.py
  zerver/tests/test_audit_log.py
  zerver/tests/test_auth_backends.py
  zerver/tests/test_decorators.py
  zerver/tests/test_email_change.py
  zerver/tests/test_email_mirror.py
  zerver/tests/test_events.py
  zerver/tests/test_push_notifications.py
  zerver/tests/test_realm.py
  zerver/tests/test_signup.py
  zerver/views/realm.py
Labels: size: XL

#30101 message_send: Update `do_send_messages` codepath to send event on commit.
  zerver/actions/message_send.py
  zerver/actions/streams.py
  zerver/actions/uploads.py
  zerver/actions/user_topics.py
  zerver/lib/streams.py
  zerver/lib/test_classes.py
  zerver/lib/user_topics.py
  zerver/tests/test_event_queue.py
  zerver/tests/test_event_system.py
  zerver/tests/test_events.py
  zerver/tests/test_link_embed.py
  zerver/tests/test_message_move_topic.py
  zerver/tests/test_message_send.py
  zerver/tests/test_service_bot_system.py
  zerver/tests/test_subs.py
Labels: size: XL

#30122 recent_view: Fix error on initial fetch being all muted messages.
  web/src/recent_view_ui.ts
Labels: size: S

#29933 input_pill: Add test for `input` event handler.
  web/tests/input_pill.test.js
Labels: size: M, integration review

#29561 Improve fix_upload_links performance
  zerver/lib/import_realm.py
Labels: size: L, integration review

#29413 stream_settings: Update feedback message to include user name.
  web/src/stream_edit_subscribers.js
Labels: bug, area: stream settings, size: S, maintainer review

#30145 settings_components: Rename subsection to $subsection_elem.
  web/src/settings_components.ts
Labels: size: XS

#30144 portico and help: Improve documentation on education pricing.
  help/self-hosted-billing.md
  help/zulip-cloud-billing.md
  templates/corporate/for/education.html
Labels: size: M, integration review

#30146 compose_popovers: Fix message_type typo
  web/src/compose_popovers.js
Labels: size: XS

#30125 is-resolved: Ok to include history.
  zerver/lib/narrow.py
  zerver/tests/test_message_fetch.py
Labels: size: XS

#30150 i18n: Update translation data from Transifex.
  locale/ar/LC_MESSAGES/django.po
  locale/ar/translations.json
  locale/be/LC_MESSAGES/django.po
  locale/be/translations.json
  locale/bg/LC_MESSAGES/django.po
  locale/bg/translations.json
  locale/da/LC_MESSAGES/django.po
  locale/da/translations.json
  locale/en_GB/LC_MESSAGES/django.po
  locale/en_GB/translations.json
  locale/eo/LC_MESSAGES/django.po
  locale/eo/translations.json
  locale/es/translations.json
  locale/fa/LC_MESSAGES/django.po
  locale/fa/translations.json
  locale/fi/LC_MESSAGES/django.po
  locale/fi/translations.json
  locale/fr/LC_MESSAGES/django.po
  locale/fr/translations.json
  locale/gl/LC_MESSAGES/django.po
  locale/gl/translations.json
  locale/ko/LC_MESSAGES/django.po
  locale/lv/LC_MESSAGES/django.po
  locale/lv/translations.json
  locale/ml/LC_MESSAGES/django.po
  locale/ml/translations.json
  locale/mobile_info.json
  locale/no/LC_MESSAGES/django.po
  locale/no/translations.json
  locale/pt/translations.json
  locale/pt_BR/LC_MESSAGES/django.po
  locale/pt_BR/translations.json
  locale/ru/LC_MESSAGES/django.po
  locale/ru/translations.json
  locale/ta/LC_MESSAGES/django.po
  locale/ta/translations.json
  locale/tr/LC_MESSAGES/django.po
  locale/tr/translations.json
  locale/zh_Hans/LC_MESSAGES/django.po
  locale/zh_Hans/translations.json
Labels: size: XL

#30076 [WIP] updates: Add update about stream->channel rename and faster loading.
  zerver/lib/zulip_update_announcements.py
Labels: area: bots, size: S

#30151 setup-recommended: Make user choose `osxfs` earlier to avoid failure.
  docs/development/setup-recommended.md
Labels: size: XS

#30154 settings_profile_field: Fix class selector.
  web/src/settings_profile_fields.ts
Labels: size: XS

#30152 compose: Fix formatting popover persists on wide screens.
  web/styles/compose.css
Labels: size: S

#30169 support: Add link to stripe customer dashboard.
  corporate/lib/support.py
  corporate/tests/test_support_views.py
  templates/corporate/support/current_plan_details.html
Labels: size: S

#30165 create_user: Fix comment in set_up_streams_for_new_human_user.
  zerver/actions/create_user.py
Labels: size: S

#30171 compose: Correct layout of send controls in narrow viewports.
  web/styles/compose.css
Labels: size: M, chat.zulip.org review, area: compose (UI & widgets)

#30172 refactor: Extract method to create and update message lists in narrow.
  web/src/narrow.js
Labels: size: XL

#30170 support: Show annual revenue for active fixed price plans.
  corporate/lib/activity.py
  corporate/lib/stripe.py
  corporate/lib/support.py
  corporate/tests/test_activity_views.py
Labels: size: M

#30173 widgets: Fix bug where `process_submessages()` was run for empty rows.
  web/src/submessage.ts
Labels: size: XS

#30174 filter: Fix combined feed navigating to muted unread message.
  web/src/filter.ts
  web/tests/filter.test.js
Labels: size: M

#30062 narrow: Fix combined feed selecting random messages on narrow.
  web/src/message_list.js
  web/src/message_list_data.ts
  web/src/message_lists.ts
  web/src/narrow.js
  web/src/unread.ts
Labels: size: XL

#30167 recent_view: Fix no topic found at center of recent view.
  web/src/recent_view_ui.ts
Labels: size: M

#30179 invite: Fix rendering invite modal for realms without default channels.
  web/src/invite.ts
Labels: size: S

#30184 sentry: More gracefully handle a value of 0.
  zproject/sentry.py
Labels: size: S

#30185 composebox_typeahead: Allow for undefined topic in PersonSuggestionOpts.
  web/src/composebox_typeahead.ts
Labels: size: S

#30187 billing helpers: Add missing $ prefix to jQuery object parameter
  web/src/billing/helpers.ts
Labels: size: XS

#30188 message_list_data: Fix type of first, first_including_muted
  web/src/message_list_data.ts
  web/src/stream_topic_history.ts
Labels: size: S

#30189 e2e-tests: Fix check_compose_state arguments
  web/e2e-tests/drafts.test.ts
  web/e2e-tests/lib/common.ts
Labels: size: XS

#30191 message_list: Remove nth_most_recent_id
  web/src/message_list.js
  web/src/message_list_data.ts
  web/tests/message_list.test.js
Labels: size: S

#30192 message_list: Remove ids_greater_or_equal_than
  web/src/message_list.js
  web/src/message_list_data.ts
Labels: size: S

#30193 message_list_data: Fix _next_nonlocal_message type
  web/src/message_list_data.ts
Labels: size: S

#30181 zilencer: Disambiguate no MX records from the domain not existing.
  zerver/tests/test_push_notifications.py
  zilencer/views.py
Labels: size: L

#30190 filter: Don’t parse dm-including operand as a list
  web/src/filter.ts
Labels: size: S, integration review

#30201 postfix: Increase the max message size to 25MB.
  puppet/zulip/templates/postfix/main.cf.erb
Labels: size: XS

#30203 markdown: Catch urllib3 exceptions which are raised during streaming.
  zerver/lib/markdown/__init__.py
Labels: size: XS

#30205 people: Fix get_custom_profile_data type
  web/src/people.ts
Labels: size: XS

#30211 import: Check off old, redundant TODO about huddle import.
  zerver/lib/import_realm.py
Labels: size: XS

#30224 analytics: Update "Messages sent by client" chart for Flutter app.
  analytics/management/commands/populate_analytics_db.py
  analytics/tests/test_stats_views.py
  analytics/views/stats.py
Labels: area: analytics, priority: high, size: S

#30229 bootstrap_typeahead: Fix AssertionError due to `onHidden` not called.
  web/src/bootstrap_typeahead.ts
Labels: size: S

#30232 api-docs: Update feature level 256 changelog and changes notes.
  api_docs/changelog.md
  zerver/openapi/zulip.yaml
Labels: area: documentation (api and integrations), size: S, api docs review

#30235 nginx: Strip off request headers which might affect S3's behaviour.
  puppet/zulip/files/nginx/zulip-include-frontend/uploads-internal.conf
Labels: size: S, backport candidate

#29897 narrow: Add 'more topics' state to browser history.
  web/src/browser_history.ts
  web/src/hashchange.js
  web/src/narrow.js
  web/src/narrow_history.ts
  web/src/stream_list.ts
  web/tests/narrow_activate.test.js
Labels: area: left sidebar (misc), priority: high, size: L, integration review

#30237 spoilers: Style headers in Markdown-neutral way.
  web/styles/rendered_markdown.css
Labels: area: markdown, size: S, area: widgets, integration review

#30236 puppet: Silence "needrestart" nags about kernel upgrades.
  puppet/kandra/files/needrestart/zulip.conf
Labels: size: XS

#30242 bootstrap_typeahead: Rename parentElement for clarity.
  web/src/bootstrap_typeahead.ts
  web/src/search.ts
Labels: size: M

#30243 user_profile: Remove 'onboarding_steps' field.
  zerver/lib/create_user.py
  zerver/lib/onboarding_steps.py
  zerver/migrations/0524_remove_userprofile_onboarding_steps.py
  zerver/models/users.py
Labels: size: M

#30246 types: Move Submessage to submessage
  web/src/message_store.ts
  web/src/submessage.ts
  web/src/types.ts
Labels: size: S

#30251 people: Fix get_custom_fields_by_type type
  web/src/people.ts
Labels: size: S

#30250 topic_generator: Fix types of get_next_stream, get_prev_stream
  web/src/topic_generator.ts
Labels: size: XS

#30256 Revert "5xx: Remove css classes and duplicate div tags."
  web/html/5xx.html
Labels: size: M

#30254 portico: Link to sponsorship policies from /for/communities page.
  templates/corporate/for/communities.html
Labels: size: S, integration review

#30258 help: Link to Data Processing Addendum (DPA) from GDPR help page.
  help/gdpr-compliance.md
Labels: size: M, integration review
