Repository zulip/zulip, pull requests merged in 2024-08, with the labels that each got.

#31200 Delete incorrectly committed dump.rdb file.
  dump.rdb
Labels: size: XS

#30831 test_stream: Setup make_stream function to create streams in node tests.
  web/tests/example1.test.js
  web/tests/example2.test.js
  web/tests/example3.test.js
  web/tests/example7.test.js
  web/tests/lib/test_stream.js
Labels: size: L

#30700 ListWidget: Fix sliding of actions column in tables.
  web/styles/app_components.css
Labels: area: settings UI, size: XS, backport candidate, integration review

#30766 refactor: Complete rename of `huddle` to `direct_message_group` in non api files.
  analytics/tests/test_counts.py
  tools/rebuild-test-database
  zerver/actions/users.py
  zerver/data_import/mattermost.py
  zerver/data_import/rocketchat.py
  zerver/lib/display_recipient.py
  zerver/lib/export.py
  zerver/lib/narrow.py
  zerver/lib/users.py
  zerver/models/messages.py
  zerver/models/recipients.py
  zerver/models/scheduled_jobs.py
  zerver/tests/test_mattermost_importer.py
  zerver/tests/test_rocketchat_importer.py
  zilencer/management/commands/populate_db.py
Labels: size: XL

#31211 clients: Drop "desktop app" substring check.
  zerver/models/clients.py
Labels: size: XS

#31210 lightbox: Disable controls on video previews in lightbox.
  web/src/lightbox.ts
Labels: size: XS, backport candidate

#31183 help: Use message screenshots for global times examples.
  help/include/global-times-examples.md
  static/images/help/global-time-example-london.png
  static/images/help/global-time-example-sf.png
Labels: area: documentation (user), size: S

#31212 nginx: Adjust default gzip level.
  puppet/zulip/templates/nginx.conf.template.erb
Labels: size: XS, backport candidate

#30807 user_groups: Migrate to @typed_endpoint.
  zerver/tests/test_openapi.py
  zerver/views/user_groups.py
Labels: size: XL, integration review, maintainer review

#31209 docs: Note required OS upgrade in upgrade notes.
  docs/overview/changelog.md
Labels: size: XS, backport candidate

#31220 rendered_markdown: Update markdown timestamps to use Zulip icon.
  web/src/info_overlay.ts
  web/styles/rendered_markdown.css
  web/templates/markdown_timestamp.hbs
  web/tests/rendered_markdown.test.js
Labels: area: markdown, size: S, area: message feed (display), redesign, integration review

#31217 compose: Specify non-alpha message-area colors.
  web/styles/app_variables.css
  web/styles/compose.css
  web/styles/dark_theme.css
Labels: bug, size: S, integration review, area: compose (UI & widgets)

#31186 thumbnail: Resolve a race condition when rendering messages.
  zerver/actions/message_send.py
  zerver/lib/markdown/__init__.py
  zerver/lib/thumbnail.py
  zerver/tests/test_markdown_thumbnail.py
  zerver/worker/thumbnail.py
Labels: size: XL, backport candidate

#31223 mypy: Reenable explicit-override for models
  analytics/models.py
  zerver/models/messages.py
  zerver/models/presence.py
  zerver/models/push_notifications.py
  zerver/models/realm_audit_logs.py
  zerver/models/scheduled_jobs.py
  zerver/models/users.py
  zilencer/models.py
Labels: size: S

#31226 inbox_ui: Fix row_focus not synced with inbox rows.
  web/src/inbox_ui.ts
Labels: size: S

#31278 auth: Fix re-enabling of SAML/AzureAD in organization settings UI.
  zerver/tests/test_auth_backends.py
  zerver/views/realm.py
Labels: bug, area: authentication, size: S, backport candidate

#31298 lightbox: Correct media types to include HTMLImageElement
  web/src/lightbox.ts
Labels: size: M

#31307 help: Add missing `---` three dash for tables.
  help/channel-permissions.md
Labels: size: XS, area: starlight

#31304 user_card_popover: Show `Manage the user` row for deactivated users.
  web/templates/popovers/user_card/user_card_popover.hbs
Labels: size: S, integration review

#31297 lightbox: Remove unnecessary open_image call.
  web/src/lightbox.ts
Labels: size: XS

#31309 help: Update global time screenshots for icon change.
  static/images/help/global-time-example-london.png
  static/images/help/global-time-example-sf.png
Labels: size: XS

#31327 dependencies: Upgrade @astrojs/starlight to 0.25.4.
  help-beta/package.json
  pnpm-lock.yaml
  version.py
Labels: size: XL

#31328 docs: Fix typo in sending-messages.md.
  docs/subsystems/sending-messages.md
Labels: size: XS, integration review

#31285 typeahead: typeahead-strong-section should have a font weight of 500.
  web/styles/typeahead.css
Labels: size: XS, integration review

#30978 user_group_popovers: Add display message when group is empty.
  web/styles/popovers.css
  web/templates/popovers/user_group_info_popover.hbs
Labels: size: M, area: settings (user groups), integration review

#31334 compose: Fix restoring big drafts freezes the app.
  web/src/compose_actions.ts
  web/src/compose_ui.ts
  web/tests/compose_actions.test.js
Labels: size: M

#31335 migrations: Fix missing Literal() calls in 0564.
  zerver/migrations/0564_purge_nagios_messages.py
Labels: size: S

#31236 avatar: Stop adding &s=50 to Gravatar and Zulip avatar requests.
  web/src/message_live_update.ts
  web/src/people.ts
  web/tests/composebox_typeahead.test.js
  web/tests/people.test.js
  web/tests/search.test.js
  web/tests/search_suggestion.test.js
  web/tests/user_pill.test.js
Labels: size: L

#31225 stream_pill: Use stream id instead of stream name.
  web/src/add_subscribers_pill.ts
  web/src/invite_stream_picker_pill.ts
  web/src/stream_pill.ts
  web/tests/stream_pill.test.js
Labels: size: L, integration review

#31283 UI redesign: new topic indicator in typeaheads
  web/src/bootstrap_typeahead.ts
  web/styles/app_variables.css
  web/styles/typeahead.css
Labels: size: S, chat.zulip.org review

#31339 search: Navigate results with up/down when input is focused.
  web/src/hotkey.js
Labels: size: S

#31341 support: Reject attempts to approve sponsorship for deactivated orgs.
  corporate/lib/stripe.py
  corporate/tests/test_support_views.py
Labels: size: M

#31308 help-beta: Remove prev/next buttons at the bottom.
  help-beta/astro.config.mjs
Labels: size: XS, area: starlight

#31303 Optimize filter comparison.
  web/src/filter.ts
Labels: size: M

#31342 migrations: Fix Nagios bot cleanup crash.
  zerver/migrations/0564_purge_nagios_messages.py
Labels: size: S

#31246 api-docs: Handle multiple examples in `responses`.
  zerver/openapi/openapi.py
  zerver/openapi/zulip.yaml
  zerver/tests/test_openapi.py
Labels: size: XL, buddy review

#31347 narrow: Do not error when given an empty DM recipient list.
  zerver/lib/narrow.py
  zerver/tests/test_message_fetch.py
Labels: size: S

#31346 user_topics_ui: Fix `toggle_topic_visibility_policy` behavior.
  web/src/user_topics_ui.ts
  web/tests/user_topics_ui.test.js
Labels: size: XL

#31353 help: Fix details in "Change your call provider" section.
  help/start-a-call.md
Labels: size: S

#31344 css: Explode dark theme disabled rule.
  web/styles/dark_theme.css
Labels: size: S, backport candidate

#31360 docs: Update the stale links in "Set up Git" docs.
  docs/git/setup.md
Labels: size: XS

#31356 search: Fix bug preventing closing regular search pills.
  web/src/search_pill.ts
Labels: size: S

#31365 message_edit: Prep commits for conversion to typescript
  web/src/message_edit.js
Labels: size: L

#31125 message_view: Update narrow title after change in narrow filter.
  web/src/message_view.js
Labels: size: XS

#31340 filter: Canonicalize operator before creating parsed term.
  web/src/filter.ts
  web/tests/filter.test.js
Labels: size: S

#31348 api-docs: Update topics array description in get-stream-topics response.
  zerver/openapi/zulip.yaml
Labels: size: XS

#31378 kandra: Bump Teleport version to 16.
  scripts/setup/apt-repos/teleport/jammy.list
Labels: size: XS

#31380 wal-g: Support setting the compression method.
  docs/production/system-configuration.md
  puppet/zulip/files/postgresql/env-wal-g
Labels: size: S

#31379 search: Reset default iOS button styles.
  web/styles/app_variables.css
  web/styles/dark_theme.css
  web/styles/search.css
Labels: area: search, size: S, integration review

#31375 user_card_popover: Pass correct popover element for person picker.
  web/src/user_card_popover.js
Labels: size: XS, area: popovers

#31374 puppeteer: Use a robust method to verify if we switched narrow.
  web/e2e-tests/compose.test.ts
  web/e2e-tests/copy-and-paste.test.ts
  web/e2e-tests/drafts.test.ts
  web/e2e-tests/edit.test.ts
  web/e2e-tests/mention.test.ts
  web/e2e-tests/message-basics.test.ts
Labels: size: L

#31166 Typed-endpoint-docs
  docs/documentation/api.md
  docs/tutorials/new-feature-tutorial.md
  docs/tutorials/writing-views.md
Labels: size: XL, maintainer review

#31368 remote-support: Add ability to configure temporary courtesy plan.
  corporate/lib/stripe.py
  corporate/tests/test_stripe.py
  corporate/tests/test_support_views.py
  corporate/views/support.py
  templates/corporate/support/next_plan_forms_support.html
  templates/corporate/support/remote_realm_details.html
  templates/corporate/support/remote_server_support.html
Labels: size: XL

#31168 create stream: Faster stream creation
  zerver/lib/users.py
  zerver/tests/test_subs.py
  zerver/views/streams.py
Labels: area: channel settings, priority: high, size: XL, post release, area: performance

#31372 user_profile: Set original_values in show_user_profile.
  web/src/user_profile.ts
Labels: size: XS

#31121 help: Document `Share someone's profile`.
  help/view-someones-profile.md
Labels: area: documentation (user), size: S, integration review

#31393 user_groups: Refactor code to compute user group objects.
  zerver/lib/user_groups.py
  zerver/tests/test_event_system.py
  zerver/tests/test_home.py
  zerver/tests/test_user_groups.py
Labels: size: XL

#31398 help: Tweak keyboard navigation docs for combined and DM feeds.
  help/keyboard-shortcuts.md
  web/templates/keyboard_shortcuts.hbs
Labels: size: S, backport candidate, integration review

#31401 message_edit: Fix type of message id for aborting video.
  web/src/message_edit.js
Labels: size: XS

#31403 rendered_markdown: Approximate non-alpha dark mode table border color.
  web/styles/app_variables.css
Labels: area: markdown, size: XS, integration review

#31394 api-docs: Clarify the behavior of the near operator.
  api_docs/construct-narrow.md
Labels: size: M, api docs review

#31383 dropdown_widget: Fix multiple triggers on item click.
  web/src/dropdown_widget.ts
Labels: size: XS, integration review

#31388 scheduled_messages: Migrate to typed_endpoint.
  zerver/actions/scheduled_messages.py
  zerver/lib/recipient_parsing.py
  zerver/lib/request.py
  zerver/tests/test_recipient_parsing.py
  zerver/tests/test_scheduled_messages.py
  zerver/views/scheduled_messages.py
Labels: size: XL

#31361 decorators: Migrate to typed_endpoint.
  tools/semgrep-py.yml
  zerver/decorator.py
  zerver/tests/test_decorators.py
Labels: size: M

#31262 test_stripe: Normalize fixtures for test_stripe_billing_portal_urls.
  corporate/tests/stripe_fixtures/stripe_billing_portal_urls--Customer.create.1.json
  corporate/tests/stripe_fixtures/stripe_billing_portal_urls--Customer.modify.1.json
  corporate/tests/stripe_fixtures/stripe_billing_portal_urls--Customer.retrieve.1.json
  corporate/tests/stripe_fixtures/stripe_billing_portal_urls--Customer.retrieve.2.json
  corporate/tests/stripe_fixtures/stripe_billing_portal_urls--Customer.retrieve.3.json
  corporate/tests/stripe_fixtures/stripe_billing_portal_urls--Event.list.1.json
  corporate/tests/stripe_fixtures/stripe_billing_portal_urls--Event.list.2.json
  corporate/tests/stripe_fixtures/stripe_billing_portal_urls--Event.list.3.json
  corporate/tests/stripe_fixtures/stripe_billing_portal_urls--Invoice.create.1.json
  corporate/tests/stripe_fixtures/stripe_billing_portal_urls--Invoice.finalize_invoice.1.json
  corporate/tests/stripe_fixtures/stripe_billing_portal_urls--Invoice.pay.1.json
  corporate/tests/stripe_fixtures/stripe_billing_portal_urls--InvoiceItem.create.1.json
  corporate/tests/stripe_fixtures/stripe_billing_portal_urls--PaymentMethod.create.1.json
  corporate/tests/stripe_fixtures/stripe_billing_portal_urls--SetupIntent.create.1.json
  corporate/tests/stripe_fixtures/stripe_billing_portal_urls--SetupIntent.list.1.json
  corporate/tests/stripe_fixtures/stripe_billing_portal_urls--SetupIntent.retrieve.1.json
  corporate/tests/stripe_fixtures/stripe_billing_portal_urls--billing_portal.Configuration.create.1.json
  corporate/tests/stripe_fixtures/stripe_billing_portal_urls--billing_portal.Configuration.create.2.json
  corporate/tests/stripe_fixtures/stripe_billing_portal_urls--billing_portal.Configuration.create.3.json
  corporate/tests/stripe_fixtures/stripe_billing_portal_urls--billing_portal.Session.create.1.json
  corporate/tests/stripe_fixtures/stripe_billing_portal_urls--billing_portal.Session.create.2.json
  corporate/tests/stripe_fixtures/stripe_billing_portal_urls--billing_portal.Session.create.3.json
  corporate/tests/stripe_fixtures/stripe_billing_portal_urls--checkout.Session.create.1.json
  corporate/tests/stripe_fixtures/stripe_billing_portal_urls--checkout.Session.list.1.json
  corporate/tests/test_stripe.py
Labels: size: XL

#31405 Fix PostgreSQL ordering in kandra
  puppet/kandra/manifests/profile/postgresql.pp
  puppet/zulip/manifests/profile/postgresql.pp
Labels: size: M

#31407 help: Add a tip to turn off read receipts with invisible mode.
  help/status-and-availability.md
Labels: integration review

#31357 message_send: Convert to typed endpoint.
  zerver/lib/validator.py
  zerver/tests/test_openapi.py
  zerver/views/message_send.py
Labels: size: L

#31410 navbar: Remove signup button.
  web/styles/zulip.css
  web/templates/navbar.hbs
Labels: size: M

#31415 footer: Add noopener noreferrer and target=_blank to social links.
  templates/zerver/footer.html
Labels: size: S

#31417 bootstrap_typeahead: Fix bug on select with no active item.
  web/src/bootstrap_typeahead.ts
Labels: size: XS

#27214 auth: Update AzureADAuthBackend to use the newer Microsoft API.
  zproject/backends.py
Labels: area: authentication

#31424 dependencies: Upgrade @astrojs/starlight to 0.26.1.
  help-beta/package.json
  pnpm-lock.yaml
  version.py
Labels: size: S

#31419 help: Fix up message deletion permissions documentation.
  help/delete-a-message.md
  help/restrict-message-editing-and-deletion.md
Labels: size: S, integration review

#31428 global_times: Correct malformed closing tags in overlay.
  web/src/info_overlay.ts
Labels: size: XS, backport candidate, integration review

#31426 dev_tools: Improve instructions for running help-beta.
  templates/zerver/development/dev_tools.html
Labels: size: M

#31431 user_profile: Update stream dropdown option value to be of "number" type.
  web/src/user_profile.ts
Labels: size: XS

#31198 portico: Update channels and topics image on /for/business.
  static/images/landing-page/companies/organized-conversations.png
  templates/corporate/for/business.html
Labels: size: XS, integration review

#31435 typeahead: Change icon for wildcard mentions.
  web/templates/typeahead_list_item.hbs
Labels: size: XS

#31437 hotkey: Add keyboard shortcut to navigate to starred messages view.
  help/include/view-starred-messages.md
  help/keyboard-shortcuts.md
  web/src/deprecated_feature_notice.ts
  web/src/hotkey.js
  web/templates/keyboard_shortcuts.hbs
  web/templates/left_sidebar.hbs
  web/templates/tooltip_templates.hbs
  web/tests/deprecated_feature_notice.test.js
Labels: area: keyboard UI, priority: high, size: M, integration review

#31430 support: Add ability to update max daily invitations for realm.
  corporate/tests/test_support_views.py
  corporate/views/support.py
  templates/corporate/support/realm_details.html
  zerver/actions/realm_settings.py
  zerver/tests/test_realm.py
Labels: size: XL, area: support

#31442 mypy: Remove use of ValuesQuerySet and QuerySetAny
  docs/testing/mypy.md
  zerver/actions/message_send.py
  zerver/actions/streams.py
  zerver/lib/cache.py
  zerver/lib/cache_helpers.py
  zerver/lib/display_recipient.py
  zerver/lib/message.py
  zerver/lib/query_helpers.py
  zerver/lib/stream_subscription.py
  zerver/lib/test_classes.py
  zerver/lib/user_groups.py
  zerver/models/recipients.py
Labels: size: L

#31454 realm-settings: Get max invites for realm plan type helper.
  corporate/views/support.py
  zerver/actions/realm_settings.py
  zerver/models/realms.py
Labels: size: L

#31455 test_stripe: Normalize fixtures for upgrade_by_card_to_plus_plan.
  corporate/tests/stripe_fixtures/upgrade_by_card_to_plus_plan--Charge.list.1.json
  corporate/tests/stripe_fixtures/upgrade_by_card_to_plus_plan--Customer.create.1.json
  corporate/tests/stripe_fixtures/upgrade_by_card_to_plus_plan--Customer.modify.1.json
  corporate/tests/stripe_fixtures/upgrade_by_card_to_plus_plan--Customer.retrieve.1.json
  corporate/tests/stripe_fixtures/upgrade_by_card_to_plus_plan--Customer.retrieve.2.json
  corporate/tests/stripe_fixtures/upgrade_by_card_to_plus_plan--Customer.retrieve.3.json
  corporate/tests/stripe_fixtures/upgrade_by_card_to_plus_plan--Customer.retrieve.4.json
  corporate/tests/stripe_fixtures/upgrade_by_card_to_plus_plan--Customer.retrieve.5.json
  corporate/tests/stripe_fixtures/upgrade_by_card_to_plus_plan--Event.list.1.json
  corporate/tests/stripe_fixtures/upgrade_by_card_to_plus_plan--Event.list.2.json
  corporate/tests/stripe_fixtures/upgrade_by_card_to_plus_plan--Event.list.3.json
  corporate/tests/stripe_fixtures/upgrade_by_card_to_plus_plan--Invoice.create.1.json
  corporate/tests/stripe_fixtures/upgrade_by_card_to_plus_plan--Invoice.finalize_invoice.1.json
  corporate/tests/stripe_fixtures/upgrade_by_card_to_plus_plan--Invoice.list.2.json
  corporate/tests/stripe_fixtures/upgrade_by_card_to_plus_plan--Invoice.pay.1.json
  corporate/tests/stripe_fixtures/upgrade_by_card_to_plus_plan--InvoiceItem.create.1.json
  corporate/tests/stripe_fixtures/upgrade_by_card_to_plus_plan--PaymentMethod.create.1.json
  corporate/tests/stripe_fixtures/upgrade_by_card_to_plus_plan--SetupIntent.create.1.json
  corporate/tests/stripe_fixtures/upgrade_by_card_to_plus_plan--SetupIntent.list.1.json
  corporate/tests/stripe_fixtures/upgrade_by_card_to_plus_plan--SetupIntent.retrieve.1.json
  corporate/tests/stripe_fixtures/upgrade_by_card_to_plus_plan--checkout.Session.create.1.json
  corporate/tests/stripe_fixtures/upgrade_by_card_to_plus_plan--checkout.Session.list.1.json
  corporate/tests/test_stripe.py
Labels: size: XL

#31441 analytics: Migrate to @typed_endpoint.
  analytics/views/stats.py
  zerver/decorator.py
Labels: size: XL

#31456 support: Add shared general realm data section to views.
  corporate/lib/stripe.py
  corporate/lib/support.py
  corporate/tests/test_support_views.py
  corporate/views/support.py
  templates/corporate/support/basic_realm_data.html
  templates/corporate/support/realm_details.html
  templates/corporate/support/remote_realm_details.html
Labels: size: L, integration review

#31322 left sidebar: Improve how starred message count is hidden.
  web/src/left_sidebar_navigation_area.ts
  web/src/starred_messages_ui.ts
  web/styles/app_variables.css
  web/styles/left_sidebar.css
  web/templates/left_sidebar.hbs
  web/tests/left_sidebar_navigation_area.test.js
  web/tests/starred_messages.test.js
Labels: priority: high, size: L, integration review, area: left sidebar (ui)

#31030 settings: Convert name to pills in custom emoji section.
  web/src/settings_emoji.ts
  web/templates/settings/admin_emoji_list.hbs
Labels: area: settings UI, size: S, integration review

#31313 narrow_banner: Fix message view banner for dm with deactivated user.
  web/src/narrow_banner.ts
  web/src/people.ts
  web/tests/message_view.test.js
  web/tests/people.test.js
Labels: bug, size: L, area: message feed (UI), integration review, mentor review

#31434 settings: Rename user_display_settings to user_preferences.
  web/src/server_events_dispatch.js
  web/src/settings_config.ts
  web/templates/settings/display_settings_general.hbs
  web/templates/settings/display_settings_information.hbs
Labels: size: S, integration review

#31473 do_delete_old_unclaimed_attachments: Cap deletions at batch size.
  zerver/actions/uploads.py
  zerver/tests/test_delete_unclaimed_attachments.py
Labels: size: M, backport candidate

#31439 setup_path: Ensure that the right venv is activated.
  scripts/lib/setup_path.py
Labels: size: S

#31483 postprocess_content: Un-URI-escape filename in title.
  web/src/postprocess_content.ts
Labels: size: S

#31478 message_list: Conditionally render message edit form container element.
  web/src/message_list.js
  web/styles/message_row.css
  web/templates/message_body.hbs
  web/templates/message_edit_form.hbs
  web/templates/single_message.hbs
Labels: area: message-editing, priority: high, size: L, area: performance, integration review

#31452 edit_history: Remove 'prev_rendered_content_version' field.
  api_docs/changelog.md
  version.py
  web/src/message_events.js
  web/src/message_store.ts
  web/src/server_message.ts
  web/src/types.ts
  zerver/actions/message_edit.py
  zerver/lib/event_schema.py
  zerver/lib/message_cache.py
  zerver/openapi/zulip.yaml
  zerver/tests/test_message_edit.py
Labels: size: L

#31482 condense: Dynamically render content for message length toggle.
  web/src/condense.ts
  web/src/message_edit.ts
  web/styles/zulip.css
  web/templates/message_body.hbs
  web/templates/message_length_toggle.hbs
Labels: area: refactoring, priority: high, size: L, area: performance, area: message feed (UI), integration review

#31486 apt-repos: Use PGroonga binaries on Ubuntu 24.04
  scripts/setup/apt-repos/zulip/custom.sh
  scripts/setup/apt-repos/zulip/noble.list
  tools/lib/provision.py
Labels: bug, size: S, backport candidate

#31479 settings: Rename display_settings.hbs to preferences.hbs.
  web/templates/settings/organization_user_settings_defaults.hbs
  web/templates/settings/preferences.hbs
  web/templates/settings/user_display_settings.hbs
Labels: size: XS, integration review

#31418 settings_users: Show previously selected value in role code dropdown.
  web/src/settings_users.js
Labels: area: settings UI, size: M, integration review, maintainer review

#31423 settings_users: Fix for filter search text issue in settings users.
  web/src/settings_invites.ts
Labels: size: XS, integration review

#31492 left_sidebar: Render brackets only on non-empty channels.
  web/src/topic_list.ts
  web/styles/left_sidebar.css
Labels: bug, size: S, integration review, area: left sidebar (display)

#31493 message_row: Allow moved/edit markers to scale.
  web/styles/message_row.css
Labels: size: XS, area: message feed (display), backport candidate, integration review, area: information density

#31329 help-center-stage-2: Group pages on the left sidebar
  help-beta/astro.config.mjs
  help-beta/src/styles/main.css
Labels: size: XL, area: starlight

#31496 puppet: Make restart-server cron use standard day-of-week.
  puppet/zulip/manifests/profile/app_frontend.pp
Labels: size: XS

#30769 auth: Migrate to @typed_endpoint.
  zerver/lib/request.py
  zerver/tests/test_openapi.py
  zerver/views/auth.py
Labels: size: XL
