Repository zulip/zulip, pull requests merged in 2024-06, with the labels that each got.

#30271 narrow: Fix server error of operand of "id" operator at large values.
  zerver/lib/narrow.py
  zerver/models/messages.py
  zerver/tests/test_message_fetch.py
Labels: size: S

#30090 settings_components: Split functions to improve type checking.
  web/src/settings_components.ts
  web/src/settings_org.js
  web/src/settings_preferences.js
  web/src/settings_profile_fields.ts
  web/src/stream_edit.js
  web/src/stream_ui_updates.js
  web/src/user_group_components.ts
  web/src/user_group_edit.js
Labels: size: XL

#30247 Fix import of message edit history
  zerver/lib/import_realm.py
  zerver/tests/test_import_export.py
Labels: bug, area: export/import, priority: high, size: L, backport candidate

#30031 Hello updesign 2024 05
  static/images/landing-page/hello/original/screen-1-dark.png
  static/images/landing-page/hello/original/screen-1-mobile-dark.png
  static/images/landing-page/hello/original/screen-1-mobile.png
  static/images/landing-page/hello/original/screen-1.png
  static/images/landing-page/hello/original/screen-2-dark.png
  static/images/landing-page/hello/original/screen-2-mobile-dark.png
  static/images/landing-page/hello/original/screen-2-mobile.png
  static/images/landing-page/hello/switch-diagram.png
  templates/corporate/hello.html
  tools/setup/generate_landing_page_images.py
  web/styles/portico/hello.css
  web/styles/portico/svg_icons.css
  zerver/tests/test_docs.py
  zerver/tests/test_home.py
Labels: size: XL, integration review

#30249 recent_view: Reduce constant flashing of recent view on initial load.
  web/src/list_widget.ts
  web/src/message_fetch.js
  web/src/message_list_data.ts
  web/src/recent_view_ui.ts
Labels: size: L

#30285 ui_init: Don't store onboarding_steps state_data as current_user_param.
  web/src/onboarding_steps.ts
  web/src/server_events_dispatch.js
  web/src/state_data.ts
  web/src/ui_init.js
  web/tests/dispatch.test.js
Labels: size: L

#30284 user_groups: Add server level setting disallow anonymous groups for settings
  api_docs/group-setting-values.md
  zerver/lib/user_groups.py
  zerver/tests/test_user_groups.py
  zerver/views/user_groups.py
  zproject/default_settings.py
  zproject/dev_settings.py
  zproject/test_extra_settings.py
Labels: size: XL

#30115 Improve tests in `python_examples.py`.
  zerver/openapi/python_examples.py
Labels: size: XL, integration review

#30288 left_sidebar: Adjust navbar, topic row-heights.
  web/styles/left_sidebar.css
Labels: size: XS, chat.zulip.org review, area: left sidebar (display)

#30289 echo: Use newly created MessageWithBooleans in insert_local_message
  web/src/echo.js
  web/src/message_events.js
  web/tests/compose.test.js
  web/tests/echo.test.js
  web/tests/server_events.test.js
Labels: size: S

#30290 messages: Rename convert_raw_message_to_message_with_booleans.
  web/src/message_helper.ts
  web/src/message_store.ts
  web/tests/echo.test.js
  web/tests/message_store.test.js
Labels: size: S

#30304 i18n: Fix translated strings for delete profile field option.
  web/src/settings_profile_fields.ts
Labels: size: S

#30033 left_sidebar: Rename "more topics" to "show all topics"
  help/include/left-sidebar-conversations.md
  tools/lib/capitalization.py
  web/src/topic_list_data.ts
  web/templates/more_topics.hbs
  web/tests/topic_list_data.test.js
  zerver/models/streams.py
  zerver/openapi/zulip.yaml
  zilencer/management/commands/populate_db.py
Labels: priority: high, size: S, integration review, area: left sidebar (ui)

#30306 docs: Update changelog with changes since 8.x.
  docs/overview/changelog.md
Labels: size: XL

#30311 push_notifications: Support test notifications from old servers.
  zerver/lib/push_notifications.py
Labels: size: XS

#30308 check-rabbitmq-consumers: Add missing f on format string.
  scripts/nagios/check-rabbitmq-consumers
Labels: size: XS

#30309 portico_error_pages: Collect zerver error pages into a folder.
  corporate/views/remote_billing_page.py
  templates/404.html
  templates/4xx.html
  templates/500.html
  templates/confirmation/link_does_not_exist.html
  templates/confirmation/link_expired.html
  templates/confirmation/link_malformed.html
  templates/corporate/billing/remote_realm_login_error_for_server_on_active_plan.html
  templates/corporate/billing/remote_server_login_error_for_any_realm_on_active_plan.html
  templates/corporate/billing/remote_server_rate_limit_exceeded.html
  templates/zerver/portico_error_pages/auth_subdomain.html
  templates/zerver/portico_error_pages/insecure_desktop_app.html
  templates/zerver/portico_error_pages/portico_error_page.html
  templates/zerver/portico_error_pages/rate_limit_exceeded.html
  templates/zerver/portico_error_pages/realm_creation_disabled.html
  templates/zerver/portico_error_pages/realm_creation_link_invalid.html
  templates/zerver/portico_error_pages/remote_realm_server_mismatch_error.html
  templates/zerver/portico_error_pages/unsupported_browser.html
  zerver/views/auth.py
  zerver/views/home.py
  zerver/views/push_notifications.py
  zerver/views/registration.py
Labels: size: L

#30312 css: Remove unused `row-fluid` class.
  web/styles/portico/portico.css
  web/third/bootstrap/css/bootstrap.portico.css
Labels: size: M

#30292 docs: Improve STARTTLS / SSL documentation for Django email settings.
  docs/production/email.md
Labels: size: S

#30027 compose: Make conversation arrow double as a go-to-conversation button.
  web/src/compose_recipient.ts
  web/styles/app_variables.css
  web/styles/compose.css
  web/templates/compose.hbs
Labels: size: L, redesign, chat.zulip.org review, deployed on chat.zulip.org, area: compose (UI & widgets)

#29211 compose: Jump to conversation where message was sent.
  web/e2e-tests/compose.test.ts
  web/e2e-tests/copy-and-paste.test.ts
  web/e2e-tests/drafts.test.ts
  web/e2e-tests/edit.test.ts
  web/e2e-tests/message-basics.test.ts
  web/e2e-tests/stars.test.ts
  web/src/compose_banner.ts
  web/src/compose_notifications.ts
  web/src/message_events.js
  web/src/narrow.js
Labels: area: compose (misc), area: onboarding, priority: high, size: XL, UI experiment, chat.zulip.org review, deployed on chat.zulip.org

#29590 compose: Show a first-time banner for jump to sent message conversation.
  web/src/compose_banner.ts
  web/src/compose_notifications.ts
  web/src/compose_setup.js
  web/templates/compose_banner/jump_to_sent_message_conversation_banner.hbs
  zerver/lib/onboarding_steps.py
  zerver/tests/test_onboarding_steps.py
Labels: area: compose (misc), area: onboarding, priority: high, size: XL, UI experiment

#30325 message_actions_popover: Hide extra separator in spectator view.
  web/templates/popovers/message_actions_popover.hbs
Labels: size: XS, area: popovers, integration review

#30336 zilencer: Do not error on old stats which we no longer have.
  zilencer/views.py
Labels: size: S, priority integration review

#30328 portico: Remove extra margin on help page.
  web/styles/portico/portico.css
Labels: size: XS

#30323 navigate: Convert module to TypeScript.
  tools/test-js-with-node
  web/src/message_lists.ts
  web/src/navigate.ts
Labels: size: L, mentor review, area: typescript migration

#30338 typeahead: Remove delay when opening / closing typeahead.
  web/src/bootstrap_typeahead.ts
Labels: size: XS

#30342 typeahead: Nest User inside UserPillData, UserOrMention
  web/src/compose_validate.ts
  web/src/composebox_typeahead.ts
  web/src/people.ts
  web/src/pill_typeahead.ts
  web/src/typeahead_helper.ts
  web/src/user_pill.ts
  web/tests/compose_validate.test.js
  web/tests/composebox_typeahead.test.js
  web/tests/pill_typeahead.test.js
  web/tests/typeahead_helper.test.js
  web/tests/user_pill.test.js
Labels: size: XL, integration review

#30282 copy_and_paste: Let uppy handle pasted single images.
  web/src/copy_and_paste.ts
Labels: size: S

#30281 overlay: Blur focused element while overlay is open.
  web/src/overlays.ts
Labels: size: XS, integration review

#30343 presence: Backend implementation of the last_update_id API.
  api_docs/changelog.md
  version.py
  zerver/lib/events.py
  zerver/lib/home.py
  zerver/lib/presence.py
  zerver/models/presence.py
  zerver/openapi/zulip.yaml
  zerver/tests/test_events.py
  zerver/tests/test_home.py
  zerver/tests/test_presence.py
  zerver/views/events_register.py
  zerver/views/presence.py
Labels: size: XL

#30352 info_density: Set calculated font-size on body.
  web/styles/message_row.css
  web/styles/zulip.css
Labels: size: S, integration review, area: information density

#30356 navbar: Express font and icon sizes in ems.
  web/styles/message_view_header.css
Labels: size: M, integration review, area: navbar, area: information density

#30357 right_sidebar: Uniformly group user name and status emoji.
  web/templates/presence_row.hbs
Labels: area: right-sidebar, size: S, integration review

#30354 list_widget: Reduce TypeScript wreckage
  web/src/list_widget.ts
  web/tests/lib/index.js
  web/tests/list_widget.test.js
Labels: size: L

#30355 portico header: Remove unnecessary type assertion
  web/src/portico/header.ts
Labels: size: XS

#30331 docs: Update section on Go to conversation button with new icon, etc.
  help/mastering-the-compose-box.md
Labels: size: S, integration review

#30363 marked: Fix type stub to declare marked as a CommonJS module
  .prettierignore
  web/third/marked/lib/marked.d.ts
Labels: size: XL

#30365 api_docs: Fix typo in the new /users/me/presence doc.
  zerver/openapi/zulip.yaml
Labels: size: XS

#30358 help: Make introduction to topics easier to navigate.
  help/include/sidebar_index.md
  help/introduction-to-topics.md
Labels: size: XS, integration review

#30370 TypeScript config cleanup; enable composite for incremental compilation
  .gitignore
  tsconfig.json
  web/shared/package.json
  web/shared/tsconfig.json
Labels: size: L

#30374 message_basic_tests: Fix flaky behavior on sending multiple messages.
  web/e2e-tests/message-basics.test.ts
Labels: size: M

#29109 Create Reactions View
  help/search-for-messages.md
  web/src/filter.ts
  web/src/left_sidebar_navigation_area.ts
  web/src/message_feed_top_notices.ts
  web/src/message_parser.ts
  web/src/narrow_banner.ts
  web/src/search_suggestion.ts
  web/styles/left_sidebar.css
  web/templates/left_sidebar.hbs
  web/templates/popovers/left_sidebar/left_sidebar_condensed_views_popover.hbs
  web/templates/search_operators.hbs
  web/templates/tooltip_templates.hbs
  web/tests/filter.test.js
  web/tests/message_view.test.js
  web/tests/search_suggestion.test.js
Labels: size: XL, integration review

#30376 help: Fix private channel permissions chart spacing.
  help/channel-permissions.md
Labels: size: XS

#30293 api_docs: Document "/invites/{invite_id}/resend" endpoint.
  api_docs/include/rest-endpoints.md
  zerver/openapi/python_examples.py
  zerver/openapi/zulip.yaml
  zerver/tests/test_openapi.py
  zerver/views/invite.py
  zproject/urls.py
Labels: size: L, integration review

#30379 stripe: Use comma for collection method Literal values.
  corporate/lib/stripe.py
Labels: size: XS

#30381 help: Document grace period for unresolving topics.
  help/resolve-a-topic.md
Labels: size: XS, integration review

#30387 resize: Remove height of hidden elements from buddy list height.
  web/src/resize.ts
Labels: size: S

#30105 api_docs: Add table of links for easy navigation in events api docs.
  web/styles/portico/portico.css
  zerver/lib/markdown/api_return_values_table_generator.py
Labels: size: L

#30378 stream_create_subscribers: Convert module to TypeScript.
  tools/test-js-with-node
  web/e2e-tests/stream_create.test.ts
  web/src/stream_create_subscribers.ts
  web/src/zulip_test.ts
Labels: size: M

#30380 user_group_create_members: Convert module to TypeScript.
  tools/test-js-with-node
  web/src/user_group_create_members.ts
Labels: size: M

#30161 invite_user_modal: Fix background color of input field.
  web/styles/app_variables.css
  web/styles/input_pill.css
Labels: area: invitations, size: XS, integration review

#30287 compose_pills: Fix long text overflow in DM recipient box.
  web/styles/input_pill.css
Labels: bug, priority: high, size: S, integration review, area: compose (recipient pickers)

#30389 buddy list: Remove buggy check preventing updates to me.
  web/src/buddy_list.ts
Labels: size: S

#30392 user_profile: Fix live-update exception when viewing channels tab.
  web/src/user_profile.js
Labels: size: XS

#29683 compose: Redesign and relocate compose expand / collapse button.
  help/resize-the-compose-box.md
  web/shared/icons/collapse-diagonal.svg
  web/shared/icons/expand-diagonal.svg
  web/src/compose_setup.js
  web/src/compose_ui.ts
  web/src/tippyjs.ts
  web/styles/app_variables.css
  web/styles/compose.css
  web/styles/dark_theme.css
  web/templates/compose.hbs
Labels: area: compose (misc), size: XL, redesign, integration review

#30393 web: Add missing CSS escaping for `url(…)`
  web/src/lightbox.ts
  web/src/user_card_popover.js
  web/src/user_profile.js
Labels: size: S

#30239 billing: Remove success message from URL after being displayed.
  web/src/billing/billing.ts
Labels: size: S

#30399 help: Fix left sidebar not bouncing on mac.
  web/styles/portico/portico.css
Labels: size: XS

#30406 portico: Don't explain what channels are.
  templates/corporate/case-studies/end-point-case-study.md
Labels: size: XS, integration review

#30394 navbar: Tweak Combined feed description for spectators.
  web/src/message_view_header.ts
Labels: size: S, area: public access, integration review, area: navbar

#30409 api-docs: Clean up descriptions of can_mention_group user group setting.
  zerver/openapi/zulip.yaml
Labels: area: documentation (api and integrations), size: XL, api docs review

#30408 images: Update channels and topics images for revisions.
  static/images/emails/channels-and-topics.png
  static/images/help/channels-and-topics.png
Labels: size: XS

#30410 help: Add page documenting the left sidebar.
  help/include/sidebar_index.md
  help/left-sidebar.md
Labels: size: M, integration review

#30413 api_docs: Improve events table and fix font style of events title.
  web/styles/portico/portico.css
  zerver/lib/markdown/api_return_values_table_generator.py
Labels: size: S

#30415 stream_edit: Fix user popover permanently displayed in stream settings.
  web/src/stream_edit.js
Labels: size: XS

#30432 puppeteer_tests: Update the instruction to view generated screenshots.
  tools/test-js-with-puppeteer
Labels: size: S, integration review

#30427 user_groups: Restore correct max-height value.
  web/styles/app_variables.css
Labels: bug, size: XS, area: settings (user groups), integration review

#30434 compose: Fix bug where compose box was sometimes not scrollable.
  web/src/resize.ts
Labels: size: XS

#30424 compose: Fix bug causing layout shift on expanding compose box.
  web/styles/compose.css
  web/templates/compose.hbs
Labels: size: L

#30429 api-docs: Revise the "services" array and "config" object for bots.
  zerver/openapi/zulip.yaml
Labels: area: documentation (api and integrations), size: M, api docs review

#30430 api-docs: Extract functions/templates for generating events documentation.
  web/styles/portico/portico.css
  zerver/lib/markdown/api_return_values_table_generator.py
Labels: area: documentation (api and integrations), size: XL, api docs review

#30423 recent_view: Adjust alignment and sizing for info density.
  web/styles/recent_view.css
Labels: size: S, area: recent-conversations, integration review, area: information density

#30431 informational_overlays: Fix CSS for tables in info_overlay.
  web/styles/app_variables.css
  web/styles/informational_overlays.css
Labels: bug, size: S

#30419 Migrate to typed endpoint
  zerver/tests/test_typing.py
  zerver/views/typing.py
Labels: size: M

#30435 org_settings: Improve organization preview button layout.
  web/styles/settings.css
Labels: area: settings (admin/org), size: S, integration review, area: information density

#30438 state_data: Move comments back to the correct declarations
  web/src/state_data.ts
Labels: size: XS

#30437 informational_overlay: Constrain to variablized width.
  web/styles/app_variables.css
  web/styles/informational_overlays.css
Labels: size: S, area: popovers, integration review, area: information density

#30433 navbar: Consolidate view, channel structures and styles.
  web/styles/message_view_header.css
  web/templates/message_view_header.hbs
  web/templates/navbar_icon_and_title.hbs
Labels: size: L, QA needed, deployed on chat.zulip.org, area: navbar, area: information density

#30404 push_notifications: Compress blockquotes when replying to a message.
  web/tests/markdown.test.js
  zerver/lib/push_notifications.py
  zerver/tests/fixtures/markdown_test_cases.json
Labels: priority: high, area: notifications (messages), area: mobile, size: XL

#30445 postgresql-init-dev-db: Add missing quotes.
  tools/setup/postgresql-init-dev-db
Labels: size: XS

#30369 right_sidebar: Remove realm description for spectators.
  web/src/sidebar_ui.ts
  web/styles/right_sidebar.css
  web/templates/right_sidebar.hbs
Labels: size: M, integration review

#30364 presence: Improve INSERT conflict handling in do_update_user_presence.
  zerver/actions/presence.py
  zerver/tests/test_presence.py
Labels: size: L

#30453 help: Do not allow autolinks for help center docs.
  help/emoji-and-emoticons.md
  help/include/legacy-log-in.md
  help/linking-to-zulip-website.md
  tools/linter_lib/custom_check.py
Labels: size: S

#30452 resize_handler: Fix scroll jumps on iOS.
  web/src/resize_handler.ts
Labels: size: S

#30350 user_topics: Handle IntegrityError during bulk insertion.
  zerver/lib/user_topics.py
Labels: size: L

#30456 profile-fields: Check for date fields before initializing flatpickr.
  web/src/custom_profile_fields_ui.ts
Labels: size: S

#30330 search-suggestions: Remove is:dm suggestion from get_operator_suggestions
  web/src/search_suggestion.ts
  web/tests/common.test.js
  web/tests/search_suggestion.test.js
Labels: size: M, integration review

#30471 server_dispatch: Calculate typography vars on dense_mode.
  web/src/server_events_dispatch.js
  web/tests/dispatch.test.js
Labels: bug, size: XS, integration review, area: information density

#30473 left_sidebar: Restore righthand padding to DM partners.
  web/styles/left_sidebar.css
Labels: size: S, integration review, area: left sidebar (display), area: information density

#30474 inbox: Enable flexible font-sizing on inbox.
  web/styles/inbox.css
Labels: size: XS, integration review, area: inbox view, area: information density

#30472 message_time: Express font-size in em units.
  web/styles/message_row.css
Labels: size: XS, area: message feed (display), integration review, area: information density

#30475 search: Set base font-size on search input.
  web/styles/search.css
Labels: area: search, size: XS, integration review, area: information density

#30443 left sidebar: Add Views label for spectators.
  web/src/left_sidebar_navigation_area.ts
  web/src/sidebar_ui.ts
  web/styles/left_sidebar.css
  web/templates/left_sidebar.hbs
Labels: size: S, integration review

#29705 typing: Move the typing notifications to below the mark as read banner.
  templates/zerver/app/index.html
  web/src/unread_ui.ts
  web/styles/print.css
  web/styles/typing_notifications.css
Labels: size: M, integration review

#30407 compose: Rework alignment of upper elements, and redesign close button.
  web/src/compose_actions.ts
  web/src/tippyjs.ts
  web/styles/app_variables.css
  web/styles/compose.css
  web/templates/compose.hbs
Labels: size: XL, redesign, area: compose (UI & widgets)

#30492 pm_section: Fix ghost tooltip on collapse/expand DM toggle.
  web/src/tippyjs.ts
Labels: size: XS, integration review

#30488 visibility_policy_popover: Fix popover shrinking bug on Safari.
  web/templates/popovers/change_visibility_policy_popover.hbs
Labels: size: S, integration review

#30491 custom_profile: Convert to typed_endpoint.
  zerver/lib/types.py
  zerver/tests/test_custom_profile_data.py
  zerver/views/custom_profile_fields.py
Labels: size: L

#30499 list_widget: Fix more elements not rendered on scrolling to bottom.
  web/src/list_widget.ts
Labels: size: XS

#30500 css: Remove unused css for channel & topic list filter.
  web/styles/app_components.css
Labels: size: S

#30464 dropdown_widget: Fix bug in `disable_for_spectators`.
  web/src/dropdown_widget.ts
Labels: bug, size: XS, area: public access, integration review

#30484 presence: Fix presence status not updated for offline users.
  web/src/presence.ts
Labels: size: S

#30515 markdown_timestamp: Remove incorrect space
  web/templates/markdown_timestamp.hbs
  web/tests/rendered_markdown.test.js
Labels: size: S

#30482 navbar: Remove empty space to the left and right.
  web/styles/app_variables.css
  web/styles/zulip.css
Labels: size: S

#30418 python_examples: Validate error responses.
  zerver/openapi/python_examples.py
Labels: size: XL, integration review

#30511 pygments: Remove legacy Zulip customizations.
  web/styles/pygments.css
Labels: size: XL, area: message feed (display), area: markdown (embeds/previews), integration review

#30132 new conversation: Show correct tooltip when dms are disabled.
  web/src/compose_closed_ui.ts
Labels: bug, size: S, area: popovers, mentor review, maintainer review, area: compose (UI & widgets)

#30527 `stream_edit_subscribers`: Fix incorrect error result test, rename misleading variable
  web/src/stream_edit_subscribers.ts
Labels: size: S, integration review

#30495 info_density: Refactor pills to follow font-size.
  web/styles/app_variables.css
  web/styles/input_pill.css
Labels: size: S, integration review, area: compose (recipient pickers), area: information density

#30528 markdown: Improve treatment of horizontal rules.
  web/styles/rendered_markdown.css
Labels: area: markdown, size: S, integration review, area: information density

#30532 stream_color: Fix stream icon color not changing on theme change.
  web/src/inbox_util.ts
  web/src/stream_color.ts
Labels: size: S

#30531 giphy: Split `is_giphy_enabled` to a separate module
  tools/test-js-with-node
  web/src/compose_popovers.js
  web/src/giphy.js
  web/src/giphy_state.ts
  web/src/message_edit.js
  web/src/state_data.ts
  web/src/ui_init.js
Labels: size: M, integration review, area: typescript migration

#30534 state_data: Accept `null` for `ProfileDatum["rendered_value"]`
  web/src/state_data.ts
Labels: size: XS

#30540 sentry: Untangle from page_params
  templates/zerver/base.html
  web/src/base_page_params.ts
  web/src/sentry.ts
  web/src/ui_init.js
  zerver/context_processors.py
  zerver/lib/home.py
  zerver/lib/test_classes.py
  zerver/tests/test_home.py
Labels: size: XL

#28686 Replace Checkboxes List with Stream Pills in Invite Users Modal #26871
  tools/test-js-with-node
  web/src/invite.ts
  web/src/invite_stream_picker_pill.ts
  web/src/pill_typeahead.ts
  web/src/stream_data.ts
  web/src/stream_pill.ts
  web/styles/input_pill.css
  web/styles/zulip.css
  web/templates/invite_user_modal.hbs
  web/tests/pill_typeahead.test.js
  web/tests/stream_data.test.js
  web/tests/stream_pill.test.js
Labels: size: XL, integration review

#30543 page_params: Add a separate error message for missing #page-params
  web/src/base_page_params.ts
Labels: size: S

#30545 ui_init: Restore guard against direct use of `page_params.state_data`
  web/src/ui_init.js
Labels: size: S, integration review

#29875 hashchange: Select the new near id if it is already rendered.
  web/src/filter.ts
  web/src/message_view.js
  web/tests/filter.test.js
Labels: size: XL, integration review

#30552 compose: Zero out UA padding on composebox buttons.
  web/styles/compose.css
Labels: size: XS, integration review, area: compose (UI & widgets)

#30554 events: Optimize computing can_create_streams and related fields.
  zerver/lib/events.py
  zerver/tests/test_event_system.py
  zerver/tests/test_home.py
Labels: size: S

#30551 hotkey: Don't close compose box on topic list input ESC.
  web/src/hotkey.js
Labels: area: keyboard UI, size: S

#30549 onboarding: Update message contents to use triple quotes.
  zerver/lib/onboarding.py
Labels: size: XL

#30561 typeahead_helper: Straighten `CombinedPill` types
  web/src/add_subscribers_pill.ts
  web/src/stream_create_subscribers.ts
  web/src/stream_edit_subscribers.ts
  web/src/typeahead_helper.ts
  web/src/user_group_create_members.ts
Labels: size: M

#30563 info_density: Scale reaction emoji with font-size.
  web/styles/reactions.css
Labels: area: emoji, size: XS, integration review, area: information density

#30071 composebox_typeahead: Avoid generating broken links.
  web/src/composebox_typeahead.ts
  web/src/topic_link_util.ts
  web/tests/topic_link_util.test.js
Labels: bug, size: XL, rust community request, area: markdown (mentions), integration review

#30574 settings: Refactor code to update realm group based settings.
  web/src/settings_components.ts
Labels: size: S

#30548 Fix translation for desktop notifications.
  web/src/message_notifications.js
Labels: area: internationalization, priority: high, area: notifications (messages), size: M, difficult

#30581 help: Improve documentation on troubleshooting desktop notifications.
  help/desktop-notifications.md
Labels: size: M, integration review

#30587 message_fetch: Stop infinite fetch for first unread message id.
  web/src/message_fetch.js
Labels: size: XS

#30585 typeahead: Add non breaking space (\u00a0) to list of word separators.
  web/src/composebox_typeahead.ts
  web/tests/composebox_typeahead.test.js
Labels: size: XS

#30590 mention_pills: Allow pills to scale with other message text.
  web/styles/rendered_markdown.css
Labels: size: XS, area: markdown (mentions), integration review, area: information density

#30591 user_circles: Allow status circles to scale.
  web/styles/app_variables.css
  web/styles/left_sidebar.css
  web/styles/popovers.css
  web/styles/recent_view.css
  web/styles/right_sidebar.css
  web/styles/zulip.css
Labels: area: right-sidebar, size: M, area: recent-conversations, area: popovers, integration review, area: compose (typeahead), area: left sidebar (display), area: information density

#30592 status_emoji: Allow status emoji to scale with text.
  web/styles/zulip.css
Labels: area: emoji, area: right-sidebar, size: S, area: message feed (display), integration review, area: left sidebar (display), area: information density

#30589 api-docs: Add example for BigBlueButton meeting_name parameter.
  zerver/openapi/zulip.yaml
Labels: size: S

#30514 typeahead: Hide by default and show container on show() to avoid half-rendered state.
  web/src/bootstrap_typeahead.ts
  web/third/bootstrap-typeahead/typeahead.css
Labels: size: L, integration review

#30520 topic_name: Fix compressing of display topic names
  web/styles/drafts.css
  web/styles/inbox.css
  web/styles/left_sidebar.css
  web/styles/message_header.css
  web/styles/popovers.css
  web/styles/rendered_markdown.css
  web/styles/zulip.css
  web/templates/compose_banner/automatic_new_visibility_policy_banner.hbs
  web/templates/confirm_dialog/confirm_delete_topic.hbs
  web/templates/confirm_dialog/confirm_merge_topics_with_rename.hbs
  web/templates/draft.hbs
  web/templates/message_moved_widget_body.hbs
  web/templates/move_topic_to_stream.hbs
  web/templates/recent_view_row.hbs
  web/templates/recipient_row.hbs
  web/templates/scheduled_message.hbs
  web/templates/stream_topic_widget.hbs
  web/templates/topic_list_item.hbs
  web/templates/typeahead_list_item.hbs
  web/templates/user_topic_ui_row.hbs
  web/tests/composebox_typeahead.test.js
Labels: size: L, integration review

#30599 left_sidebar_navigation_area_popover: Convert module to TypeScript.
  tools/test-js-with-node
  web/src/left_sidebar_navigation_area_popovers.ts
  web/src/popover_menus.ts
Labels: size: M, buddy review, area: typescript migration

#26863 realm-deactivation: Send email to owners when deactivating organization.
  corporate/tests/test_stripe.py
  corporate/tests/test_support_views.py
  corporate/views/support.py
  templates/zerver/emails/realm_deactivated.html
  templates/zerver/emails/realm_deactivated.subject.txt
  templates/zerver/emails/realm_deactivated.txt
  tools/test-api
  zerver/actions/create_realm.py
  zerver/actions/realm_settings.py
  zerver/management/commands/deactivate_realm.py
  zerver/management/commands/export.py
  zerver/tests/test_audit_log.py
  zerver/tests/test_auth_backends.py
  zerver/tests/test_decorators.py
  zerver/tests/test_email_change.py
  zerver/tests/test_email_mirror.py
  zerver/tests/test_events.py
  zerver/tests/test_push_notifications.py
  zerver/tests/test_realm.py
  zerver/tests/test_signup.py
  zerver/views/realm.py
  zproject/jinja2/__init__.py
Labels: priority: high, area: emails, size: XL, integration review

#30608 mypy: Remove some unused ignore_missing_imports overrides
  pyproject.toml
Labels: size: XS

#30611 typeahead: Remove all sources of white space inside `strong` element.
  web/templates/inline_decorated_stream_name.hbs
  web/templates/typeahead_list_item.hbs
  web/tests/composebox_typeahead.test.js
Labels: size: M

#30606 settings: Make the label for disabled checkboxes less faded.
  web/styles/settings.css
Labels: size: XS, integration review

#30617 portico: Add HostingAdvice.com review to history page.
  templates/corporate/history.md
Labels: size: S, integration review

#30580 Improve channels typeahead on invite modal #30577
  web/src/pill_typeahead.ts
  web/src/typeahead_helper.ts
  web/tests/pill_typeahead.test.js
  web/tests/typeahead_helper.test.js
Labels: size: M, integration review, mentor review

#30568 settings: Add links to topic notification settings.
  web/templates/settings/notification_settings.hbs
Labels: good first issue, area: documentation (user), area: settings UI, size: S, integration review

#29435 compose: Unresolve empty topics followup
  web/src/compose_setup.js
Labels: size: S, integration review

#30618 api-docs: Update `presences` object documentation.
  zerver/openapi/zulip.yaml
Labels: area: documentation (api and integrations), size: XL, api docs review

#30612 api_docs: Reorder and rename endpoint titles in left sidebar and documentation page.
  api_docs/include/rest-endpoints.md
  zerver/openapi/zulip.yaml
Labels: size: M

#30625 onboarding_step: Don't show 'visibility_policy_banner' to new users.
  zerver/actions/create_user.py
  zerver/tests/test_onboarding_steps.py
  zerver/tests/test_signup.py
  zerver/tests/test_users.py
Labels: area: onboarding, priority: high, size: S, integration review, area: compose (banners & validation)

#30627 left_sidebar: Convert Sass-style vars to CSS vars.
  web/styles/app_variables.css
  web/styles/left_sidebar.css
Labels: size: L, integration review, area: left sidebar (display)
