Repository zulip/zulip, pull requests merged in 2024-11, with the labels that each got.

#32195 requirements: Upgrade Python requirements
  requirements/common.in
  requirements/dev.in
  requirements/dev.txt
  requirements/mypy.in
  requirements/pip.in
  requirements/pip.txt
  requirements/prod.txt
  tools/python-warnings.bash
  version.py
Labels: area: dependencies, size: XL, backport candidate

#32194 buddy_data: Don't filter out inactive participants.
  web/src/buddy_data.ts
Labels: size: S

#32202 portico: Clean up CSS rules for "Find account" and "Reset password" pages.
  templates/zerver/find_account.html
  web/styles/portico/portico_signin.css
Labels: size: S

#32203 util: Make get_custom_time_in_minutes throw error for unknown unit.
  web/src/util.ts
  web/tests/util.test.js
Labels: size: S

#32201 keyboard-shortcuts: Display "Ctrl" for Vim "Esc" keybinding behavior.
  help/configure-home-view.md
  help/keyboard-shortcuts.md
  web/src/common.ts
  web/templates/keyboard_shortcuts.hbs
Labels: bug, area: keyboard UI, size: M

#31922 integrations: Create incoming webhook for Airbyte.
  static/images/integrations/airbyte/001.png
  static/images/integrations/bot_avatars/airbyte.png
  static/images/integrations/logos/airbyte.svg
  zerver/lib/integrations.py
  zerver/webhooks/airbyte/__init__.py
  zerver/webhooks/airbyte/doc.md
  zerver/webhooks/airbyte/fixtures/airbyte_job_payload_failure.json
  zerver/webhooks/airbyte/fixtures/airbyte_job_payload_success.json
  zerver/webhooks/airbyte/fixtures/test_airbyte_job_hello_world_failure.json
  zerver/webhooks/airbyte/fixtures/test_airbyte_job_hello_world_success.json
  zerver/webhooks/airbyte/tests.py
  zerver/webhooks/airbyte/view.py
Labels: size: XL, integration review

#32197 help: Update docs to describe group-based permissions.
  help/create-user-groups.md
  help/include/review-organization-settings-instructions.md
  help/include/sidebar_index.md
  help/include/user-groups-applications.md
  help/include/user-groups-intro.md
  help/manage-user-groups.md
  help/moving-to-zulip.md
  help/review-your-organization-settings.md
  help/roles-and-permissions.md
  help/user-groups.md
Labels: size: L, integration review

#32206 left_sidebar: Solidify grid placement of filter-clearing button.
  web/styles/left_sidebar.css
Labels: bug, size: S, integration review, area: left sidebar (display)

#32209 demo_organizations_ui: Convert module to TypeScript.
  tools/test-js-with-node
  web/src/demo_organizations_ui.ts
Labels: size: S

#32208 refactor: Update on-change event to use custom-expiration-time-input.
  web/src/invite.ts
Labels: size: XS

#32204 update_ui: Standardize pencil icon color for todo and poll.
  web/styles/widgets.css
Labels: design, size: S, area: widgets

#32211 groups: Clarify meaning of global admin setting.
  help/manage-user-groups.md
  web/templates/settings/organization_permissions_admin.hbs
Labels: size: S

#32213 buddy_list: Move user link a bit left to line up with empty message.
  web/styles/right_sidebar.css
Labels: size: XS

#32090 import: Add function to normalize messages to import.
  zerver/data_import/import_util.py
  zerver/lib/message.py
  zerver/tests/fixtures/mattermost_fixtures/direct_channel/export.json
Labels: area: export/import, size: S, integration review

#32230 stream_popover: Handle no messages condition for a topic being moved.
  web/src/stream_popover.js
Labels: size: S

#32219 Replace trash icon with archive icon.
  help/archive-a-channel.md
  web/shared/icons/archive.svg
  web/styles/subscriptions.css
  web/templates/stream_settings/stream_settings.hbs
Labels: size: S, integration review

#32249 invite-user-modal: Clean up of template HTML attributes.
  web/templates/invite_user_modal.hbs
Labels: size: S

#32244 demo-orgs: Specify email input when rendering add email modal.
  web/src/settings_account.ts
Labels: size: XS

#32229 avatars: Split email-based and user ID-based avatar endpoints.
  zerver/tests/test_upload.py
  zerver/views/users.py
  zproject/urls.py
Labels: size: XL

#32251 user_card_popover: Fix unknown user_id in unsaved message user mentions.
  web/src/user_card_popover.js
Labels: size: XS

#32258 left_sidebar: Unread, nav area alignment fixes.
  web/styles/left_sidebar.css
  web/styles/popovers.css
  web/templates/popovers/left_sidebar/left_sidebar_condensed_views_popover.hbs
Labels: size: L, area: popovers, integration review, area: left sidebar (display), area: left sidebar (popovers)

#32252 Fixed minor typo in contributing guide
  CONTRIBUTING.md
Labels: size: XS

#32253 help: Document pretty message links.
  help/include/links-examples.md
  help/include/links-intro.md
  help/link-to-a-message-or-conversation.md
Labels: size: M

#32263 help: Document how archived channels work now.
  help/archive-a-channel.md
Labels: size: M, integration review

#32270 help: Update example screenshot for markdown link formatting.
  static/images/help/markdown-links.png
Labels: size: XS

#32274 docs: Stop describing Docker as experimental.
  docs/production/deployment.md
  docs/production/install.md
Labels: size: S, backport candidate

#32277 buddy list: followups to adding avatar
  web/styles/right_sidebar.css
  web/styles/user_circles.css
Labels: size: S

#32238 settings: Write fewer values into template settings files.
  zproject/default_settings.py
  zproject/prod_settings_template.py
Labels: size: S

#32279 webpack: Disable CompressionPlugin for Puppeteer tests
  tools/webpack
  web/webpack.config.ts
Labels: size: S

#32275 i18n: Update translations from Transifex.
  locale/ar/LC_MESSAGES/django.po
  locale/ar/translations.json
  locale/cs/LC_MESSAGES/django.po
  locale/cs/translations.json
  locale/de/LC_MESSAGES/django.po
  locale/de/translations.json
  locale/mobile_info.json
  locale/pl/LC_MESSAGES/django.po
  locale/pl/translations.json
  locale/pt_PT/LC_MESSAGES/django.po
  locale/pt_PT/translations.json
  locale/ru/LC_MESSAGES/django.po
  locale/ru/translations.json
  locale/tr/translations.json
  locale/uk/translations.json
Labels: size: XL

#32254 settings_realm_user_settings_default: Convert module to typescript.
  tools/test-js-with-node
  web/src/settings_realm_user_settings_defaults.ts
Labels: size: M, area: typescript migration

#31469 integrations: Update GoCD integration.
  static/images/integrations/gocd/001.png
  zerver/lib/integrations.py
  zerver/webhooks/gocd/doc.md
  zerver/webhooks/gocd/fixtures/build_details.json
  zerver/webhooks/gocd/fixtures/pipeline.json
  zerver/webhooks/gocd/fixtures/pipeline_building.json
  zerver/webhooks/gocd/fixtures/pipeline_failed.json
  zerver/webhooks/gocd/fixtures/pipeline_passed.json
  zerver/webhooks/gocd/fixtures/pipeline_with_mixed_job_result.json
  zerver/webhooks/gocd/tests.py
  zerver/webhooks/gocd/view.py
Labels: size: XL, integration review

#32276 docs: Fix upgrade instructions for Ubuntu 22.04->24.04.
  docs/production/upgrade.md
Labels: size: M, backport candidate

#31887 left_sidebar: Fix keyboard accessibility out of order.
  web/src/left_sidebar_navigation_area.ts
  web/src/sidebar_ui.ts
  web/styles/left_sidebar.css
  web/templates/left_sidebar.hbs
Labels: bug, area: keyboard UI, accessibility, size: XL, integration review, area: left sidebar (ui)

#32291 import: Remove skipping of too-long messages during import.
  zerver/data_import/mattermost.py
  zerver/data_import/rocketchat.py
Labels: size: S

#32300 email_mirror: Check that email gateway bot can send to the channel.
  zerver/lib/email_mirror.py
  zerver/tests/test_email_mirror.py
Labels: size: M

#32281 stream_create: Fix puppeteer test flake from modal reopening.
  web/e2e-tests/stream_create.test.ts
Labels: size: S

#32303 slack: Call the correct resize_* function when importing realm icon.
  zerver/data_import/slack.py
  zerver/lib/thumbnail.py
  zerver/lib/upload/local.py
  zerver/lib/upload/s3.py
Labels: size: S, backport candidate

#32264 buddy_list: Add background color placeholder to loading avatar.
  web/src/buddy_list.ts
  web/styles/app_variables.css
  web/styles/right_sidebar.css
  web/templates/presence_row.hbs
Labels: size: S, chat.zulip.org review

#29730 integrations: Update Newrelic integrations.
  static/images/integrations/bot_avatars/newrelic.png
  static/images/integrations/logos/newrelic.svg
  static/images/integrations/newrelic/001.png
  static/images/integrations/newrelic/002.png
  static/images/integrations/newrelic/003.png
  static/images/integrations/newrelic/newrelic.png
  zerver/lib/integrations.py
  zerver/webhooks/newrelic/doc.md
  zerver/webhooks/newrelic/fixtures/essential_fields_default_payload.json
  zerver/webhooks/newrelic/fixtures/incident_acknowledged_default_payload.json
  zerver/webhooks/newrelic/fixtures/incident_acknowledged_new.json
  zerver/webhooks/newrelic/fixtures/incident_acknowledged_old.json
  zerver/webhooks/newrelic/fixtures/incident_acknowledged_provided_base_payload.json
  zerver/webhooks/newrelic/fixtures/incident_activated_new_default_payload.json
  zerver/webhooks/newrelic/fixtures/incident_activated_new_provided_base_payload.json
  zerver/webhooks/newrelic/fixtures/incident_active_new.json
  zerver/webhooks/newrelic/fixtures/incident_closed_default_payload.json
  zerver/webhooks/newrelic/fixtures/incident_closed_new.json
  zerver/webhooks/newrelic/fixtures/incident_closed_old.json
  zerver/webhooks/newrelic/fixtures/incident_closed_provided_base_payload.json
  zerver/webhooks/newrelic/fixtures/incident_created_default_payload.json
  zerver/webhooks/newrelic/fixtures/incident_created_new.json
  zerver/webhooks/newrelic/fixtures/incident_created_provided_base_payload.json
  zerver/webhooks/newrelic/fixtures/incident_default_base_with_zulip_custom_fields.json
  zerver/webhooks/newrelic/fixtures/incident_default_fields_new.json
  zerver/webhooks/newrelic/fixtures/incident_default_fields_old.json
  zerver/webhooks/newrelic/fixtures/incident_malformatted_time_new.json
  zerver/webhooks/newrelic/fixtures/incident_malformatted_time_old.json
  zerver/webhooks/newrelic/fixtures/incident_malformed_timestamp.json
  zerver/webhooks/newrelic/fixtures/incident_missing_current_state_old.json
  zerver/webhooks/newrelic/fixtures/incident_missing_state_new.json
  zerver/webhooks/newrelic/fixtures/incident_missing_timestamp_new.json
  zerver/webhooks/newrelic/fixtures/incident_missing_timestamp_old.json
  zerver/webhooks/newrelic/fixtures/incident_opened_old.json
  zerver/webhooks/newrelic/fixtures/incident_provided_base_with_zulip_custom_fields.json
  zerver/webhooks/newrelic/fixtures/incident_state_not_recognized_new.json
  zerver/webhooks/newrelic/fixtures/incident_state_not_recognized_old.json
  zerver/webhooks/newrelic/fixtures/incident_time_too_large.json
  zerver/webhooks/newrelic/fixtures/incident_time_too_large_new.json
  zerver/webhooks/newrelic/fixtures/incident_time_too_large_old.json
  zerver/webhooks/newrelic/fixtures/incident_with_invalid_zulip_custom_fields.json
  zerver/webhooks/newrelic/fixtures/missing_essential_fields_default_payload.json
  zerver/webhooks/newrelic/tests.py
  zerver/webhooks/newrelic/view.py
Labels: size: XL, integration review

#32302 svgicons2svgfont: Patch to fix Node 22 punycode DeprecationWarning
  package.json
  patches/svgicons2svgfont.patch
  pnpm-lock.yaml
  version.py
Labels: size: M

#32311 lint: Recognize more JavaScript file extensions
  help-beta/astro.config.mjs
  tools/lint
  web/tests/lib/index.js
  web/webpack.config.ts
Labels: size: XL

#32312 dependencies: Remove mkdirp
  package.json
  pnpm-lock.yaml
  tools/screenshots/message-screenshot.js
  tools/screenshots/thread-screenshot.js
  version.py
Labels: size: S

#32314 dependencies: Remove three JS argument parsing libraries
  package.json
  pnpm-lock.yaml
  tools/check-openapi
  tools/screenshots/message-screenshot.js
  tools/screenshots/thread-screenshot.js
  version.py
  web/tests/lib/mdiff.js
Labels: size: XL

#32315 lint: Further recognize more JavaScript file extensions
  .editorconfig
  .eslintrc.js
Labels: size: XS

#32307 test_import_export: Don't hard-code ZULIP_VERSION in fixtures.
  zerver/tests/fixtures/import_fixtures/check_migrations_errors/extra_migrations_error.txt
  zerver/tests/fixtures/import_fixtures/check_migrations_errors/unapplied_migrations_error.txt
  zerver/tests/test_import_export.py
Labels: size: S

#32308 change_realm_subdomain: Revoke user sessions.
  zerver/actions/create_realm.py
Labels: size: XS

#32316 corporate: Fix misuse of timezone_now() as parameter default
  corporate/lib/activity.py
  corporate/lib/stripe.py
  zilencer/models.py
Labels: size: M, integration review

#32309 webpack: Remove unused landing_page dependency on event status page.
  web/webpack.assets.json
Labels: area: refactoring, area: portico, size: XS, area: billing, bootstrap removal

#32317 ruff: Enable B008 function-call-in-default-argument
  confirmation/models.py
  pyproject.toml
  zerver/lib/events.py
  zerver/lib/types.py
  zerver/tests/test_typed_endpoint.py
  zerver/views/events_register.py
Labels: size: M, integration review

#32304 message_header: Fix message content visible above sticky header.
  web/styles/message_header.css
Labels: size: XS, area: message feed (display), integration review

#32092 mention_pill: Show bot icon in bot mention pill.
  web/src/rendered_markdown.ts
  web/styles/rendered_markdown.css
  web/templates/mention_content_wrapper.hbs
Labels: size: S, integration review

#31450 ts: Convert `web/src/portico/google_analytics.js` to TypeScript.
  package.json
  pnpm-lock.yaml
  version.py
  web/src/portico/ga-gtag.d.ts
  web/src/portico/google-analytics.js
  web/src/portico/google-analytics.ts
Labels: size: L, area: typescript migration

#32329 settings: Fix filtering users based on role.
  web/src/settings_users.ts
Labels: size: XS

#32324 babel: Remove transform-optional-chaining workaround
  web/babel.config.js
Labels: size: XS

#32333 settings: Improve user-list style layout.
  web/styles/settings.css
Labels: bug, area: settings (user), area: settings UI, size: S, integration review

#32334 webpack: Remove unused hexoid alias
  web/webpack.config.ts
Labels: size: S

#32336 stream_edit: Fix bug where personal settings weren't being saved.
  web/src/stream_edit.ts
Labels: size: S

#32337 test-js-with-node: Remove missing files from EXEMPT_FILES
  tools/test-js-with-node
Labels: size: S

#32340 Revert "settings_account: Move async call into ui_init."
  web/src/settings_account.ts
  web/src/settings_sections.js
  web/src/ui_init.js
Labels: size: S

#32156 tooltip: Remove "last active" time from deactivated user tooltip.
  web/src/buddy_data.ts
  web/templates/buddy_list_tooltip_content.hbs
  web/tests/buddy_data.test.cjs
Labels: bug, size: M, integration review, area: left sidebar (popovers)

#32344 tsconfig: Enable verbatimModuleSyntax
  tsconfig.json
Labels: size: XS

#32345 bundles: Remove unnecessary bootstrap_typeahead import
  web/src/bundles/app.ts
Labels: size: XS

#32346 makemessages: Write with orjson
  tools/i18n/process-mobile-i18n
  tools/i18n/unescape-contents
  tools/i18n/update-for-legacy-translations
  zerver/management/commands/compilemessages.py
  zerver/management/commands/makemessages.py
Labels: size: L, integration review

#32356 settings: Fix checking max values for message move limit settings.
  web/src/settings_components.ts
Labels: size: XS

#32349 realm_export: Change `tarball_size_bytes` to PositiveBigIntegerField.
  zerver/migrations/0624_alter_realmexport_tarball_size_bytes.py
  zerver/models/realms.py
Labels: size: S, integration review

#32288 message_feed: Add channel settings link and remove Subscribe/Unsubscribe buttons.
  web/src/message_list.ts
  web/src/message_list_view.ts
  web/templates/bookend.hbs
  web/tests/message_list.test.cjs
Labels: priority: high, size: M, area: popovers, area: message feed (UI), maintainer review

#32352 integrations(linear): make topics easier to understand
  zerver/webhooks/linear/tests.py
  zerver/webhooks/linear/view.py
Labels: size: L

#32363 webpack: Fix knownHelpers list, enable knownHelpersOnly for handlebars-loader.
  web/webpack.config.ts
Labels: size: S

#32359 puppet: Require libldap-common be installed.
  puppet/zulip/manifests/app_frontend_base.pp
Labels: size: S, backport candidate

#32365 blueslip: Include message for abnormal traces.
  web/src/blueslip_stacktrace.ts
Labels: size: XS

#32367 settings: Fix display of status emoji in “User list style”
  web/templates/settings/preferences_information.hbs
Labels: size: S

#32241 streams: Move subscriber count from channel pills to channel cards.
  web/src/stream_card_popover.ts
  web/src/stream_pill.ts
  web/templates/popovers/stream_card_popover.hbs
  web/tests/stream_pill.test.cjs
Labels: size: M, area: popovers, integration review

#32374 buddy_list: Move header_text calculation to where it's used.
  web/src/buddy_list.ts
Labels: size: S

#32376 right_sidebar: Add missing right margin to header.
  web/styles/right_sidebar.css
Labels: size: XS, integration review

#32380 settings_panel_menu: Convert module to typescript.
  tools/test-js-with-node
  web/src/admin.js
  web/src/click_handlers.js
  web/src/hashchange.js
  web/src/settings.js
  web/src/settings_panel_menu.ts
  web/src/settings_toggle.js
  web/src/ui_init.js
  web/src/user_card_popover.js
Labels: size: L, area: typescript migration

#32381 stream_muting: Convert module to typescript.
  tools/test-js-with-node
  web/src/stream_events.js
  web/src/stream_muting.ts
Labels: size: S, area: typescript migration

#32385 templates: Fix @partial-block invocations for explicitPartialContext
  web/templates/compose_banner/compose_banner.hbs
  web/templates/modal_banner/modal_banner.hbs
Labels: size: XS

#32386 compose: Delegate max-length tooltip to body.
  web/src/compose_tooltips.ts
  web/src/ui_init.js
  web/templates/compose.hbs
Labels: bug, size: S, area: compose (banners & validation)

#18217 hotkey: Disable left arrow hotkey when view has unreads.
  web/src/message_edit.ts
  web/templates/confirm_dialog/confirm_edit_messages.hbs
Labels: bug, area: keyboard UI, area: message-editing, size: L, post release, integration review

#32387 docs: Simplify Docker trade-offs discussion.
  docs/production/deployment.md
Labels: size: S, backport candidate

#32351 Improve error handling for version mismatches in import/export with CommandError
  zerver/lib/import_realm.py
  zerver/tests/fixtures/import_fixtures/check_migrations_errors/extra_migrations_error.txt
  zerver/tests/fixtures/import_fixtures/check_migrations_errors/unapplied_migrations_error.txt
  zerver/tests/test_import_export.py
Labels: size: M, backport candidate

#32391 settings: Fix flaky test.
  web/e2e-tests/settings.test.ts
Labels: size: XS

#32396 templates: Remove redundant {{#with this}} blocks
  web/templates/message_group.hbs
  web/templates/stream_settings/browse_streams_list_item.hbs
Labels: size: S

#32395 billing: Remove invoice option for users with fixed-price plan offer.
  templates/corporate/billing/upgrade.html
Labels: size: XS, area: billing

#32148 notifications: Add help link for "Followed topics" in triggers table.
  web/src/settings_config.ts
  web/templates/settings/notification_settings.hbs
  web/tests/settings_config.test.cjs
Labels: size: S, integration review

#32147 Enhanced User Role Filter Dropdown with Role-Specific and Total User Counts.
  web/src/settings_users.ts
Labels: area: settings (admin/org), size: M, integration review, maintainer review

#32377 buddy_list: Move arrow toggle to the left of the header text.
  web/src/buddy_list.ts
  web/styles/app_variables.css
  web/styles/right_sidebar.css
  web/styles/zulip.css
  web/templates/buddy_list/section_header.hbs
Labels: size: M

#32397 introduce_zulip_view_modal: Fix invalid @partial-block usage
  web/templates/introduce_zulip_view_modal.hbs
Labels: size: XS

#32406 recent_view: Remove bootstrap classes from recent view buttons.
  web/styles/dark_theme.css
  web/styles/recent_view.css
  web/templates/recent_view_filters.hbs
  web/third/bootstrap/css/bootstrap-btn.css
Labels: size: L

#32407 right_sidebar: Suppress empty circle over user avatars.
  web/styles/right_sidebar.css
Labels: size: XS

#32167 invitations: Default to empty channel list when inviting guest users.
  web/src/invite.ts
Labels: area: invitations, size: M, integration review

#32415 portico: Remove `bootstrap-btn.css` dependency from portico.
  templates/zerver/development/integrations_dev_panel.html
  web/src/bundles/app.ts
  web/src/bundles/common.ts
  web/styles/portico/integrations_dev_panel.css
Labels: size: S

#32417 settings: Wait for settings overlay to close.
  web/e2e-tests/settings.test.ts
Labels: size: XS

#32421 bootstrap: Remove unused bootstrap button classes.
  web/templates/poll_modal_option.hbs
  web/templates/recent_view_table.hbs
  web/templates/settings/bot_avatar_row.hbs
  web/third/bootstrap/css/bootstrap.portico.css
Labels: size: S

#32420 billing: Link customer stripe ID for manual fixed-price plan invoices.
  corporate/lib/stripe.py
  corporate/tests/test_stripe.py
Labels: size: XL, area: billing

#32414 Refine tools/generate-integration-docs-screenshot
  tools/screenshots/generate-integration-docs-screenshot
Labels: size: XS

#32424 integrations: Fix jQuery .data mishandling translated category names.
  templates/zerver/integrations/index.html
  web/src/portico/integrations.js
  zerver/lib/integrations.py
Labels: size: M, backport candidate

#32394 streams: Add 'ChannelEmailAddress' model.
  zerver/actions/streams.py
  zerver/lib/email_mirror.py
  zerver/lib/email_mirror_helpers.py
  zerver/lib/export.py
  zerver/migrations/0629_remove_stream_email_token_backfill_channelemailaddress.py
  zerver/models/__init__.py
  zerver/models/streams.py
  zerver/tests/test_email_mirror.py
  zerver/tests/test_subs.py
Labels: size: XL

#32400 buddy_list: Redesign view user links.
  web/styles/right_sidebar.css
  web/templates/buddy_list/view_all_subscribers.hbs
  web/templates/buddy_list/view_all_users.hbs
Labels: area: right-sidebar, size: XL, redesign, chat.zulip.org review, area: left sidebar (display)

#32427 buddy_list: Center toggle arrow.
  web/styles/right_sidebar.css
Labels: area: right-sidebar, size: XS, integration review

#32428 tests: Add assertion for database queries count.
  zerver/tests/test_event_system.py
Labels: area: testing-coverage, size: S

#32434 streams: Do not show archived streams in dropdown.
  web/src/stream_data.ts
  web/tests/stream_data.test.cjs
Labels: size: S

#32432 add_new_user_history: Remove the RECENT_MESSAGES_TIMEDELTA limit.
  zerver/actions/create_user.py
  zerver/tests/test_signup.py
Labels: size: S

#32431 streams: Fix handling empty groups when computing setting values.
  zerver/lib/streams.py
  zerver/tests/test_subs.py
Labels: size: L

#32436 right_sidebar: Match invite-user grid to others.
  web/styles/right_sidebar.css
Labels: area: right-sidebar, redesign, integration review

#32439 migrations: Add progress indicator for imageattachment backfill.
  zerver/migrations/0576_backfill_imageattachment.py
  zerver/migrations/0622_backfill_imageattachment_again.py
Labels: area: production, size: M, backport candidate

#32438 migrations: Add progress indicator for imageattachment backfill.
  zerver/migrations/0576_backfill_imageattachment.py
  zerver/migrations/0622_backfill_imageattachment_again.py
Labels: area: production, size: M

#32447 templates: Avoid confusing Mustache-style conditionals
  web/templates/draft.hbs
  web/templates/message_avatar.hbs
  web/templates/message_edit_history.hbs
  web/templates/scheduled_message.hbs
  web/templates/single_message.hbs
  web/templates/stream_settings/stream_members.hbs
Labels: size: S

#32452 settings_toggle: Convert module to typescript.
  tools/test-js-with-node
  web/src/admin.js
  web/src/click_handlers.js
  web/src/hashchange.js
  web/src/settings.js
  web/src/settings_toggle.ts
  web/src/ui_init.js
Labels: size: S, area: typescript migration

#32453 settings: Convert module to typescript.
  tools/test-js-with-node
  web/src/admin.js
  web/src/dialog_widget.ts
  web/src/hashchange.js
  web/src/settings.ts
  web/src/settings_account.ts
  web/src/settings_invites.ts
  web/src/settings_users.ts
  web/src/ui_init.js
  web/src/user_events.js
Labels: size: L, area: typescript migration

#32456 i18n: Update translations from Transifex.
  locale/be/LC_MESSAGES/django.po
  locale/be/translations.json
  locale/bqi/translations.json
  locale/cs/LC_MESSAGES/django.po
  locale/eo/LC_MESSAGES/django.po
  locale/eo/translations.json
  locale/gl/LC_MESSAGES/django.po
  locale/gl/translations.json
  locale/it/LC_MESSAGES/django.po
  locale/lt/translations.json
  locale/lv/LC_MESSAGES/django.po
  locale/lv/translations.json
  locale/ml/LC_MESSAGES/django.po
  locale/ml/translations.json
  locale/mobile_info.json
  locale/no/LC_MESSAGES/django.po
  locale/no/translations.json
  locale/pl/LC_MESSAGES/django.po
  locale/pl/translations.json
  locale/pt/LC_MESSAGES/django.po
  locale/pt_BR/LC_MESSAGES/django.po
  locale/pt_BR/translations.json
  locale/ru/translations.json
  locale/ta/LC_MESSAGES/django.po
  locale/ta/translations.json
Labels: size: XL

#32457 compose: Remove duplicate call to clear_preview_area.
  web/src/compose.js
Labels: size: XS

#32467 help and modals: Describe "edit your last message" consistently.
  help/keyboard-shortcuts.md
  web/src/message_edit.ts
  web/templates/confirm_dialog/confirm_edit_messages.hbs
Labels: size: S, integration review

#32465 templates: Remove "no-validation" class.
  templates/corporate/billing/billing.html
  templates/corporate/billing/legacy_server_login.html
  templates/corporate/billing/remote_billing_confirm_email_form.html
  templates/corporate/billing/remote_billing_finalize_login_confirmation.html
  templates/corporate/billing/remote_billing_server_deactivate.html
  templates/corporate/billing/remote_billing_server_deactivated_success.html
  templates/corporate/billing/sponsorship.html
  templates/corporate/billing/upgrade.html
  templates/corporate/support/support_request.html
  templates/two_factor/_wizard_forms.html
  templates/zerver/login.html
  templates/zerver/register.html
Labels: size: L

#32455 user_group: Show display_name instead of name for direct subgroups.
  web/src/user_group_popover.ts
  web/src/user_groups.ts
Labels: size: S

#32472 sidebars: Remove transition when link buttons are clicked on.
  web/styles/left_sidebar.css
  web/styles/right_sidebar.css
Labels: size: S

#32469 unarchive_channel: Fix logic checking for name collision.
  zerver/management/commands/unarchive_channel.py
Labels: size: S

#31799 support: Add form for sales support queries.
  corporate/urls.py
  corporate/views/support.py
  templates/corporate/support/sales_support_request.html
  templates/zerver/emails/sales_support_request.html
  templates/zerver/emails/sales_support_request.subject.txt
  templates/zerver/emails/sales_support_request.txt
  web/shared/icons/handshake.svg
  web/src/navbar_help_menu.ts
  web/styles/portico/portico_signin.css
  web/templates/popovers/navbar/navbar_help_menu_popover.hbs
Labels: area: misc, priority: high, size: XL, area: popovers

#32473 updates: Add update message (level=10).
  zerver/lib/zulip_update_announcements.py
Labels: size: M, integration review

#32474 desktop_integration: Convert module to TypeScript
  tools/test-js-with-node
  web/src/desktop_integration.ts
  web/src/electron_bridge.ts
  web/src/ui_init.js
Labels: size: M, integration review, area: typescript migration

#32483 help: Remove extraneous banner about requiring a paid plan.
  help/create-user-groups.md
  help/include/user-groups-intro.md
  help/manage-user-groups.md
  help/user-groups.md
Labels: size: S, integration review

#30299 Add members to usergroup invitation
  api_docs/changelog.md
  tools/test-js-with-node
  version.py
  web/src/invite.ts
  web/src/invite_user_group_picker_pill.ts
  web/src/pill_typeahead.ts
  web/src/typeahead_helper.ts
  web/src/user_group_pill.ts
  web/src/user_group_popover.ts
  web/styles/input_pill.css
  web/templates/invite_user_modal.hbs
  web/tests/pill_typeahead.test.cjs
  web/tests/typeahead_helper.test.cjs
  zerver/actions/create_user.py
  zerver/actions/invites.py
  zerver/lib/export.py
  zerver/migrations/0630_multiuseinvite_groups_preregistrationuser_groups.py
  zerver/models/prereg_users.py
  zerver/openapi/zulip.yaml
  zerver/tests/test_invite.py
  zerver/tests/test_signup.py
  zerver/tests/test_users.py
  zerver/views/invite.py
  zerver/views/registration.py
Labels: size: XL, integration review, buddy review

#32403 Persistent DMs collapsed status across reloads.
  web/src/pm_list.ts
Labels: size: S

#32482 Clean up integrations.py fields - display_name, client_name
  zerver/lib/integrations.py
Labels: size: XL, integration review

#32441 settings: Make the empty panel text darker in light theme.
  web/styles/subscriptions.css
Labels: area: settings UI, size: XS, area: settings (user groups)

#32502 css_variables: Convert module to TypeScript
  tools/test-js-with-node
  web/postcss.config.js
  web/src/buddy_list.ts
  web/src/click_handlers.js
  web/src/css_variables.d.ts
  web/src/css_variables.ts
  web/src/popover_menus.ts
  web/src/sidebar_ui.ts
Labels: size: M, area: typescript migration

#32504 templates: Convert module to TypeScript
  web/src/bundles/app.ts
  web/src/templates.ts
  web/tests/i18n.test.cjs
  web/tests/lib/index.cjs
  web/tests/lib/namespace.cjs
  web/webpack.config.ts
Labels: size: L, area: typescript migration

#32451 buddy_list: Add style-change options to buddy list popover.
  web/src/sidebar_ui.ts
  web/styles/right_sidebar.css
  web/templates/popovers/buddy_list_popover.hbs
Labels: size: XL, chat.zulip.org review, deployed on chat.zulip.org

#32501 buddy_list: Fix logic for showing the "channel" section and its "view all subscribers" link
  web/src/buddy_list.ts
Labels: size: L

#32450 settings_bots: Fix deactivation icon.
  web/templates/settings/admin_user_list.hbs
Labels: size: XS, integration review

#32325 docs: Fix WSL rebuild steps tab, explicit note to install a fresh instance.
  docs/development/setup-recommended.md
  docs/development/setup/wsl-rebuild.md
Labels: size: M, integration review

#32514 buddy_list: Don't use transparent background for header hover.
  web/styles/app_variables.css
Labels: size: S

#32509 buddy_list: Fix bug where participants weren't filtered on search.
  web/src/buddy_data.ts
Labels: size: XS

#32512 Trim trailing whitespace in integration categories.
  locale/fr/LC_MESSAGES/django.po
  web/src/portico/integrations.js
Labels: size: XS

#32510 admin: Convert module to TypeScript
  docs/tutorials/new-feature-tutorial.md
  docs/tutorials/writing-views.md
  tools/test-js-with-node
  web/src/admin.ts
  web/src/hashchange.js
  web/src/people.ts
  web/src/realm_logo.ts
  zerver/models/realms.py
Labels: size: L, area: typescript migration

#32508 buddy_list: Always update section hiddenness on populate.
  web/src/buddy_list.ts
Labels: size: XS

#32515 message_scroll: Convert module to TypeScript
  tools/test-js-with-node
  web/src/message_list.ts
  web/src/message_scroll.ts
  web/src/ui_init.js
Labels: size: L, area: typescript migration

#32518 message_actions_popover: Convert module to TypeScript
  tools/test-js-with-node
  web/src/compose_reply.ts
  web/src/hotkey.js
  web/src/message_actions_popover.ts
  web/src/message_edit.ts
  web/src/ui_init.js
Labels: size: M, area: typescript migration

#32521 dependencies: Downgrade @uppy/tus from 4.1.4 to 4.1.3
  pnpm-lock.yaml
  version.py
Labels: area: uploads, size: S, priority integration review

#32520 topic_popover: Convert module to TypeScript
  tools/test-js-with-node
  web/src/message_edit.ts
  web/src/stream_popover.ts
  web/src/topic_popover.ts
  web/src/ui_init.js
  web/src/ui_util.ts
Labels: size: L, area: typescript migration

#32519 user_card_popover: Convert module to TypeScript
  tools/test-js-with-node
  web/src/copied_tooltip.ts
  web/src/drafts_overlay_ui.js
  web/src/hotkey.js
  web/src/popover_menus.ts
  web/src/ui_init.js
  web/src/user_card_popover.ts
  web/src/user_profile.ts
Labels: size: XL, area: typescript migration

#32524 Move @babel/register, stylelint-high-performance-animation to devDependencies
  package.json
  pnpm-lock.yaml
Labels: size: S
