Repository zulip/zulip, pull requests merged in 2024-01, with the labels that each got.

#28391 docs: Fix typo in mypy doc.
  docs/testing/mypy.md
Labels: size: XS

#28394 pm_list_data: Convert module to typescript.
  web/src/pm_list_data.ts
Labels: size: M

#28346 billing: Improve make_end_of_cycle_... interactions with audit logs.
  corporate/lib/stripe.py
  corporate/tests/test_stripe.py
  corporate/views/billing_page.py
Labels: size: L

#28301 test_stripe: Add migrate customer from server to realms E2E test.
  corporate/tests/stripe_fixtures/migrate_customer_server_to_realms_and_upgrade--Customer.create.1.json
  corporate/tests/stripe_fixtures/migrate_customer_server_to_realms_and_upgrade--Customer.modify.1.json
  corporate/tests/stripe_fixtures/migrate_customer_server_to_realms_and_upgrade--Customer.retrieve.1.json
  corporate/tests/stripe_fixtures/migrate_customer_server_to_realms_and_upgrade--Customer.retrieve.2.json
  corporate/tests/stripe_fixtures/migrate_customer_server_to_realms_and_upgrade--Customer.retrieve.3.json
  corporate/tests/stripe_fixtures/migrate_customer_server_to_realms_and_upgrade--Customer.retrieve.4.json
  corporate/tests/stripe_fixtures/migrate_customer_server_to_realms_and_upgrade--Customer.retrieve.5.json
  corporate/tests/stripe_fixtures/migrate_customer_server_to_realms_and_upgrade--Event.list.1.json
  corporate/tests/stripe_fixtures/migrate_customer_server_to_realms_and_upgrade--Event.list.2.json
  corporate/tests/stripe_fixtures/migrate_customer_server_to_realms_and_upgrade--Event.list.3.json
  corporate/tests/stripe_fixtures/migrate_customer_server_to_realms_and_upgrade--Event.list.4.json
  corporate/tests/stripe_fixtures/migrate_customer_server_to_realms_and_upgrade--Event.list.5.json
  corporate/tests/stripe_fixtures/migrate_customer_server_to_realms_and_upgrade--Invoice.create.1.json
  corporate/tests/stripe_fixtures/migrate_customer_server_to_realms_and_upgrade--Invoice.finalize_invoice.1.json
  corporate/tests/stripe_fixtures/migrate_customer_server_to_realms_and_upgrade--Invoice.list.1.json
  corporate/tests/stripe_fixtures/migrate_customer_server_to_realms_and_upgrade--InvoiceItem.create.1.json
  corporate/tests/stripe_fixtures/migrate_customer_server_to_realms_and_upgrade--InvoiceItem.create.2.json
  corporate/tests/stripe_fixtures/migrate_customer_server_to_realms_and_upgrade--InvoiceItem.create.3.json
  corporate/tests/stripe_fixtures/migrate_customer_server_to_realms_and_upgrade--PaymentIntent.create.1.json
  corporate/tests/stripe_fixtures/migrate_customer_server_to_realms_and_upgrade--SetupIntent.create.1.json
  corporate/tests/stripe_fixtures/migrate_customer_server_to_realms_and_upgrade--SetupIntent.list.1.json
  corporate/tests/stripe_fixtures/migrate_customer_server_to_realms_and_upgrade--SetupIntent.retrieve.1.json
  corporate/tests/stripe_fixtures/migrate_customer_server_to_realms_and_upgrade--checkout.Session.create.1.json
  corporate/tests/stripe_fixtures/migrate_customer_server_to_realms_and_upgrade--checkout.Session.list.1.json
  corporate/tests/test_stripe.py
  corporate/views/billing_page.py
  zilencer/views.py
Labels: size: XL, integration review

#28409 settings: Update description text in Settings > Topics panel.
  web/templates/settings/user_topics_settings.hbs
Labels: size: M, backport candidate, integration review

#28319 filter: Use terms instead of operands.
  web/src/compose_reply.js
  web/src/filter.ts
  web/src/hash_util.ts
  web/src/hashchange.js
  web/src/message_events.js
  web/src/message_feed_top_notices.js
  web/src/message_fetch.js
  web/src/narrow.js
  web/src/narrow_banner.js
  web/src/narrow_history.ts
  web/src/narrow_state.ts
  web/src/search.js
  web/src/search_suggestion.js
  web/src/typing_events.js
  web/src/unread_ops.js
  web/tests/filter.test.js
  web/tests/hash_util.test.js
  web/tests/hashchange.test.js
  web/tests/narrow.test.js
  web/tests/narrow_state.test.js
  web/tests/search.test.js
  web/tests/search_suggestion.test.js
Labels: size: XL

#28393 message flags: Convert module to typescript.
  web/src/message_flags.ts
  web/src/message_store.ts
Labels: size: M

#28416 narrow_banner: Convert module to typescript.
  web/src/narrow_banner.ts
  web/src/narrow_error.ts
  web/src/page_params.ts
Labels: size: S, area: typescript migration

#28399 integrations: Simplify instruction for generating incoming webhook URL.
  help/generate-integration-url.md
  templates/zerver/integrations/include/generate-integration-url.md
Labels: size: S, integration review

#28402 user_pill: Add support to not allow adding inaccessible users manually.
  web/src/compose_pm_pill.ts
  web/src/custom_profile_fields_ui.js
  web/src/input_pill.ts
  web/src/user_pill.ts
  web/tests/user_pill.test.js
Labels: size: L, backport candidate

#28417 message_feed_top_notices: Convert module to typescript.
  tools/test-js-with-node
  web/src/message_feed_top_notices.ts
  web/src/message_lists.ts
Labels: size: S, area: typescript migration

#28420 support: Display if remote realm is locally deactivated.
  templates/analytics/remote_realm_details.html
  zilencer/management/commands/populate_billing_realms.py
Labels: size: S

#28405 help: Document self-hosted plan discounts in more detail.
  help/self-hosted-billing.md
Labels: size: M, integration review

#28430 docs: Add tiny note about Keycloak URL format in SAML doc.
  docs/production/authentication-methods.md
Labels: size: XS, backport candidate

#28419 user_topics: Validate 'topic' parameter length <= max_topic_length.
  zerver/openapi/zulip.yaml
  zerver/tests/test_user_topics.py
  zerver/views/user_topics.py
Labels: bug, area: topics, priority: high, size: M, backport candidate, integration review

#28437 portico: Correct spacing at footer bottom.
  web/styles/portico/footer.css
Labels: area: portico, size: S, integration review

#28439 docs: Add warning about failed provisioning on macOS.
  docs/development/setup-recommended.md
Labels: area: documentation (developer), size: S

#28435 send_custom_email: Various newsletter cleanups
  zerver/lib/send_email.py
  zerver/management/commands/send_custom_email.py
Labels: size: M

#28379 alert-word: Background color of alert word fixed closes #28407
  web/styles/rendered_markdown.css
  web/styles/zulip.css
Labels: size: XS, backport candidate

#28442 billing: Improve display of sponsorship requests.
  analytics/tests/test_support_views.py
  templates/analytics/sponsorship_forms_support.html
  templates/zerver/emails/sponsorship_request.html
Labels: area: billing

#28406 management: Provide a way to deactivate the push registration.
  docs/production/mobile-push-notifications.md
  zerver/management/commands/register_server.py
Labels: size: L, backport candidate

#28274 settings_realm_domains: Convert module to TypeScript.
  tools/test-js-with-node
  web/src/page_params.ts
  web/src/settings_realm_domains.ts
Labels: size: S, area: typescript migration

#28425 Add a configuration for S3 addressing style; clean up S3 access calls
  zerver/lib/upload/s3.py
  zproject/default_settings.py
  zproject/prod_settings_template.py
Labels: area: uploads, size: L, backport candidate

#28432 read_receipts: Convert module to TypeScript.
  tools/test-js-with-node
  web/src/read_receipts.ts
Labels: size: M, area: typescript migration

#28454 markdown: Prevent OverflowError with large time integers.
  zerver/lib/markdown/__init__.py
  zerver/tests/fixtures/markdown_test_cases.json
Labels: size: S

#28451 migrate_customers: Migrate customer from server to realms during login.
  corporate/tests/test_remote_billing.py
  corporate/tests/test_stripe.py
  corporate/views/remote_billing_page.py
  zilencer/views.py
Labels: size: XL

#28461 fetch-contributor-data: Add zulip-flutter repo.
  tools/fetch-contributor-data
Labels: size: S

#28457 ci: Test upgrades from Zulip Server 8.0.
  .github/workflows/production-suite.yml
Labels: size: S, backport candidate

#28455 push_notification: Check users count for plans to be downgraded.
  corporate/lib/stripe.py
  zerver/tests/test_push_notifications.py
Labels: size: XL

#28474 refactor: Pass only stream id, not name, to `compose_actions.start()`.
  web/src/drafts.js
  web/src/drafts_overlay_ui.js
  web/src/scheduled_messages_ui.js
Labels: size: S

#28326 Add a more direct link to the code for the push notification bouncer.
  docs/production/mobile-push-notifications.md
Labels: size: XS, integration review

#28433 send_password_reset_email: Add a flag to only email users who need it.
  help/include/import-how-users-will-log-in.md
  zerver/management/commands/send_password_reset_email.py
Labels: area: export/import, size: S, backport candidate

#27933 Organization settings: Fix tippy design and hover delay for edit/delete in custom profile fields.
  web/templates/settings/admin_profile_field_list.hbs
Labels: area: settings UI, size: XS, integration review

#28285 documentation: Support having no sidebar for policies docs.
  templates/zerver/policies_minimal/privacy.md
  templates/zerver/policies_minimal/terms.md
  zerver/tests/test_docs.py
  zerver/views/documentation.py
Labels: size: S, backport candidate

#28309 settings: Fix color leak during linkifier row drag in settings
  web/styles/dark_theme.css
Labels: size: S, integration review

#28282 Update upgrade.md
  docs/production/upgrade.md
Labels: size: XS, backport candidate

#28485 logrotate: smokescreen has its own config file.
  puppet/zulip/templates/logrotate/zulip.template.erb
Labels: size: XS, backport candidate

#28491 portico: Extend proper background gradients to /plans.
  templates/corporate/plans.html
  web/styles/portico/hello.css
  web/styles/portico/pricing_plans.css
Labels: area: portico, size: L

#28469 stripe: Set min license count based on flat discount.
  corporate/lib/stripe.py
  corporate/tests/test_stripe.py
Labels: size: M

#28496 notification_settings: Open push notification docs link in new tab
  web/templates/settings/notification_settings.hbs
Labels: size: XS, backport candidate

#28494 support: Update end date for active customer plan.
  analytics/tests/test_support_views.py
  analytics/views/support.py
  corporate/lib/stripe.py
  templates/analytics/current_plan_forms_support.html
  zerver/models/realm_audit_logs.py
Labels: size: XL

#28466 plans: Bring comparison link-styles in line with the mocked design.
  web/styles/portico/comparison_table.css
Labels: area: portico, size: XS, integration review

#27810 Fixes- #27391 : Updated typeaheads
  web/src/composebox_typeahead.js
  web/tests/composebox_typeahead.test.js
Labels: size: S, integration review

#28502 compose: Fix duplicate warning banners for the same private stream.
  web/src/compose_validate.js
  web/tests/compose_validate.test.js
Labels: bug, size: M, area: compose (banners & validation)

#28500 help: Document plan sign-up in notification troubleshooting section.
  help/mobile-notifications.md
Labels: size: S, integration review

#28335 сhanged concatenation of strings to f-strings to improve readability
  zerver/lib/dev_ldap_directory.py
Labels: size: S

#28506 puppet: Adjust uptrack permissions and ownership to match package's.
  puppet/zulip_ops/manifests/ksplice_uptrack.pp
Labels: size: S

#28489 messages: Only lock UserMessage rows, not other joined tables.
  zerver/models/messages.py
Labels: size: S

#28498 plans: Reduce font-weight on push placeholder button.
  web/styles/portico/pricing_plans.css
Labels: area: portico, size: XS, integration review

#28499 plans: Reduce font-size of text comparison elements.
  web/styles/portico/comparison_table.css
Labels: area: portico, integration review

#28509 nagios: Remove provisioning of zulip contact alias.
  puppet/zulip_ops/manifests/profile/nagios.pp
Labels: size: S

#28510 billing: Improve /plans and billing help pages.
  help/self-hosted-billing.md
  help/zulip-cloud-billing.md
  templates/corporate/plans.html
  templates/corporate/pricing_model.html
Labels: size: L, integration review

#27935 portico-header: Dropped find accounts link for smaller windows.
  templates/zerver/portico-header.html
  web/styles/portico/portico.css
Labels: bug, area: documentation (user), size: S, backport candidate, integration review

#28492 user_group_popover: Convert module to typescript.
  tools/test-js-with-node
  web/src/user_group_popover.ts
Labels: size: L, area: typescript migration

#28395 stream_topic_history: Convert module to typescript.
  web/src/message_edit.js
  web/src/stream_topic_history.ts
  web/src/unread.ts
Labels: size: XL, area: typescript migration

#28327 CSRF error page #25626
  templates/404.html
  templates/4xx.html
  zerver/decorator.py
  zerver/middleware.py
Labels: bug, good first issue, area: misc, area: message-editing, size: L, integration review

#28519 message: Allow system bots to mention group if everyone else can.
  zerver/lib/message.py
  zerver/tests/test_message_send.py
Labels: size: M, backport candidate

#28524 plans: Link to cloud, self-hosted sponsorship areas.
  templates/corporate/plans.html
  templates/corporate/pricing_model.html
Labels: area: portico, size: S, integration review

#28414 stream_list_sort: Convert module to typescript.
  web/src/stream_list_sort.ts
Labels: size: L, area: typescript migration

#28533 support: Update validation for adding or updating a discount.
  corporate/lib/stripe.py
  templates/analytics/realm_details.html
  templates/analytics/remote_realm_details.html
  templates/analytics/remote_server_support.html
  templates/analytics/sponsorship_forms_support.html
Labels: size: S

#28540 api_docs: Update doc for `realm_push_notifications_enabled_end_timestamp`.
  zerver/openapi/zulip.yaml
Labels: size: S

#28532 stripe: Fix the invoice item description for flat discounts.
  corporate/lib/stripe.py
  corporate/tests/stripe_fixtures/invoice_initial_remote_realm_upgrade--Customer.create.1.json
  corporate/tests/stripe_fixtures/invoice_initial_remote_realm_upgrade--Customer.modify.1.json
  corporate/tests/stripe_fixtures/invoice_initial_remote_realm_upgrade--Customer.retrieve.1.json
  corporate/tests/stripe_fixtures/invoice_initial_remote_realm_upgrade--Customer.retrieve.2.json
  corporate/tests/stripe_fixtures/invoice_initial_remote_realm_upgrade--Customer.retrieve.3.json
  corporate/tests/stripe_fixtures/invoice_initial_remote_realm_upgrade--Customer.retrieve.4.json
  corporate/tests/stripe_fixtures/invoice_initial_remote_realm_upgrade--Event.list.1.json
  corporate/tests/stripe_fixtures/invoice_initial_remote_realm_upgrade--Event.list.2.json
  corporate/tests/stripe_fixtures/invoice_initial_remote_realm_upgrade--Event.list.3.json
  corporate/tests/stripe_fixtures/invoice_initial_remote_realm_upgrade--Event.list.4.json
  corporate/tests/stripe_fixtures/invoice_initial_remote_realm_upgrade--Invoice.create.1.json
  corporate/tests/stripe_fixtures/invoice_initial_remote_realm_upgrade--Invoice.finalize_invoice.1.json
  corporate/tests/stripe_fixtures/invoice_initial_remote_realm_upgrade--Invoice.list.1.json
  corporate/tests/stripe_fixtures/invoice_initial_remote_realm_upgrade--Invoice.list.2.json
  corporate/tests/stripe_fixtures/invoice_initial_remote_realm_upgrade--InvoiceItem.create.1.json
  corporate/tests/stripe_fixtures/invoice_initial_remote_realm_upgrade--InvoiceItem.create.2.json
  corporate/tests/stripe_fixtures/invoice_initial_remote_realm_upgrade--InvoiceItem.create.3.json
  corporate/tests/stripe_fixtures/invoice_initial_remote_realm_upgrade--PaymentIntent.create.1.json
  corporate/tests/stripe_fixtures/invoice_initial_remote_realm_upgrade--SetupIntent.create.1.json
  corporate/tests/stripe_fixtures/invoice_initial_remote_realm_upgrade--SetupIntent.list.1.json
  corporate/tests/stripe_fixtures/invoice_initial_remote_realm_upgrade--SetupIntent.retrieve.1.json
  corporate/tests/stripe_fixtures/invoice_initial_remote_realm_upgrade--checkout.Session.create.1.json
  corporate/tests/stripe_fixtures/invoice_initial_remote_realm_upgrade--checkout.Session.list.1.json
  corporate/tests/stripe_fixtures/invoice_initial_remote_server_upgrade--Customer.create.1.json
  corporate/tests/stripe_fixtures/invoice_initial_remote_server_upgrade--Customer.modify.1.json
  corporate/tests/stripe_fixtures/invoice_initial_remote_server_upgrade--Customer.retrieve.1.json
  corporate/tests/stripe_fixtures/invoice_initial_remote_server_upgrade--Customer.retrieve.2.json
  corporate/tests/stripe_fixtures/invoice_initial_remote_server_upgrade--Customer.retrieve.3.json
  corporate/tests/stripe_fixtures/invoice_initial_remote_server_upgrade--Customer.retrieve.4.json
  corporate/tests/stripe_fixtures/invoice_initial_remote_server_upgrade--Event.list.1.json
  corporate/tests/stripe_fixtures/invoice_initial_remote_server_upgrade--Event.list.2.json
  corporate/tests/stripe_fixtures/invoice_initial_remote_server_upgrade--Event.list.3.json
  corporate/tests/stripe_fixtures/invoice_initial_remote_server_upgrade--Event.list.4.json
  corporate/tests/stripe_fixtures/invoice_initial_remote_server_upgrade--Event.list.5.json
  corporate/tests/stripe_fixtures/invoice_initial_remote_server_upgrade--Event.list.6.json
  corporate/tests/stripe_fixtures/invoice_initial_remote_server_upgrade--Invoice.create.1.json
  corporate/tests/stripe_fixtures/invoice_initial_remote_server_upgrade--Invoice.finalize_invoice.1.json
  corporate/tests/stripe_fixtures/invoice_initial_remote_server_upgrade--Invoice.list.1.json
  corporate/tests/stripe_fixtures/invoice_initial_remote_server_upgrade--Invoice.list.2.json
  corporate/tests/stripe_fixtures/invoice_initial_remote_server_upgrade--InvoiceItem.create.1.json
  corporate/tests/stripe_fixtures/invoice_initial_remote_server_upgrade--InvoiceItem.create.2.json
  corporate/tests/stripe_fixtures/invoice_initial_remote_server_upgrade--InvoiceItem.create.3.json
  corporate/tests/stripe_fixtures/invoice_initial_remote_server_upgrade--PaymentIntent.create.1.json
  corporate/tests/stripe_fixtures/invoice_initial_remote_server_upgrade--SetupIntent.create.1.json
  corporate/tests/stripe_fixtures/invoice_initial_remote_server_upgrade--SetupIntent.list.1.json
  corporate/tests/stripe_fixtures/invoice_initial_remote_server_upgrade--SetupIntent.retrieve.1.json
  corporate/tests/stripe_fixtures/invoice_initial_remote_server_upgrade--checkout.Session.create.1.json
  corporate/tests/stripe_fixtures/invoice_initial_remote_server_upgrade--checkout.Session.list.1.json
  corporate/tests/test_stripe.py
Labels: size: XL, integration review

#28541 docs: Fix selfhoster URL to be the canonical one.
  docs/production/mobile-push-notifications.md
  help/include/legacy-log-in.md
Labels: size: XS, backport candidate

#28531 stream_topic_history_util: Convert module to typescript.
  web/src/stream_topic_history_util.ts
Labels: size: S, area: typescript migration

#28517 settings: Fix setting label click functionality.
  web/templates/settings/notification_settings.hbs
Labels: size: XS, backport candidate, integration review

#28545 user_status: Fix parsing of partial user_status events
  web/src/user_status.ts
Labels: size: M, backport candidate

#28547 playground_links_popover: Remove wrong `$` prefix for non-jQuery variable
  web/src/playground_links_popover.js
Labels: size: S

#28550 help: Make minor tweaks to warning about multiple organizations billing.
  help/include/self-hosted-billing-multiple-organizations.md
Labels: size: XS, integration review

#28553 Allow access to billing page without talking to stripe.
  corporate/lib/stripe.py
  zilencer/management/commands/populate_billing_realms.py
Labels: size: L

#28557 remote_billing: Fix handle_customer_migration_from_server_to_realms.
  corporate/tests/test_remote_billing.py
  corporate/views/remote_billing_page.py
  zilencer/views.py
Labels: size: M

#28507 settings: Rename settings_display to settings_preferences.
  tools/test-js-with-node
  web/src/click_handlers.js
  web/src/gear_menu.js
  web/src/server_events_dispatch.js
  web/src/settings.js
  web/src/settings_preferences.js
  web/src/settings_realm_user_settings_defaults.js
  web/src/settings_sections.js
  web/src/ui_init.js
  web/tests/dispatch.test.js
Labels: size: L, integration review

#28530 topic_list_data: Convert module to typescript.
  web/src/pm_list_data.ts
  web/src/topic_list_data.ts
Labels: size: L, area: typescript migration

#28560 unread_ops: Use /messages/flags/narrow to mark stream/topic as read.
  web/src/unread_ops.js
Labels: area: refactoring, size: L

#28253 Cursor style on hover #3938
  web/src/message_list_hover.js
  web/styles/message_row.css
  web/styles/zulip.css
Labels: area: message-editing, size: S, integration review

#27973 turndown: Convert single line code blocks to inline code markdown.
  web/src/copy_and_paste.js
  web/tests/copy_and_paste.test.js
Labels: size: L, integration review

#26511 tests: full coverage for zerver/actions/presence.py
  tools/test-backend
  zerver/actions/presence.py
Labels: size: S

#28296 typeaheads: Fix mention typeaheads spill width.
  web/styles/zulip.css
Labels: bug, priority: high, size: XS, integration review, area: compose (typeahead)

#28577 tools: Add a tool for backporting PRs.
  tools/backport-pull-request
Labels: size: M, backport candidate

#28548 Redirect home for some hostnames.
  zerver/tests/test_home.py
  zerver/views/home.py
Labels: size: S

#28583 e2e-tests: Rename display_settings_section to preferences_section.
  web/e2e-tests/settings.test.ts
Labels: size: S

#28579 drafts: Fix flaky drafts tests.
  web/e2e-tests/drafts.test.ts
Labels: size: S

#28516 find_account: Remove emails as URL parameters.
  zerver/tests/test_signup.py
  zerver/views/development/email_log.py
  zerver/views/registration.py
Labels: size: L, integration review

#28591 billing: Change background color of reactivate subscription.
  web/styles/portico/billing.css
Labels: size: XS, area: billing, integration review

#28605 hbs: Use correct tooltips for deactivated bots.
  web/templates/settings/admin_user_list.hbs
Labels: size: XS

#28606 help: Tweak instructions for finding your Zulip account.
  help/logging-in.md
Labels: size: S, integration review

#28613 notifications: Add # to stream name in desktop notifications.
  web/src/message_notifications.js
Labels: integration review

#28610 emails: Remove organization type from sponsorship request emails.
  corporate/tests/test_stripe.py
  templates/zerver/emails/sponsorship_request.subject.txt
Labels: size: S, integration review

#28570 billing: Rename button to apply for sponsorship or discount.
  corporate/tests/test_stripe.py
  help/self-hosted-billing.md
  templates/corporate/plans.html
Labels: size: S, integration review

#28010 message: Rewrite personals query to be more performant and accurate.
  zerver/lib/message.py
Labels: size: L

#28614 remote_billing: Add rate-limiting for confirmation email sending.
  corporate/tests/test_remote_billing.py
  corporate/views/remote_billing_page.py
  templates/corporate/remote_server_rate_limit_exceeded.html
  zproject/default_settings.py
  zproject/test_extra_settings.py
Labels: size: XL

#28594 settings: Rename display-settings-form to preferences-settings-form.
  web/styles/settings.css
  web/templates/settings/display_settings.hbs
Labels: size: S

#28624 desktop_app: Close popover when clicking on "Plan management".
  web/src/desktop_integration.js
Labels: size: XS, backport candidate

#28582 find_account: Add button to send another email.
  templates/zerver/find_account.html
  tools/lib/capitalization.py
  zerver/views/registration.py
Labels: size: S, integration review

#28602 Fixed string quotes in postgresql-init-dev-db
  tools/setup/postgresql-init-dev-db
Labels: size: S

#28618 stripe: End legacy plan on `end_date`.
  corporate/lib/stripe.py
  corporate/tests/test_stripe.py
Labels: size: M

#28620 narrow: Fix message row partially visible on narrow.
  web/src/narrow.js
  web/tests/narrow_activate.test.js
Labels: size: L, backport candidate

#28637 compose: Don't convert bot mentions to silent mentions.
  web/src/compose_validate.js
Labels: size: S, backport candidate

#28643 settings: Rename display_settings_labels to preferences_settings_labels.
  web/src/settings.js
  web/src/settings_config.ts
Labels: size: S

#28642 billing: Qualify policies for free and discounted plans.
  help/self-hosted-billing.md
  help/zulip-cloud-billing.md
  templates/corporate/plans.html
Labels: size: L, integration review

#28655 personal_menu: Fix clicking on `Set status` not working.
  web/templates/personal_menu.hbs
Labels: size: S, backport candidate

#28661 support: Show date for start of next billing cycle for current plan.
  analytics/tests/test_support_views.py
  corporate/lib/support.py
  templates/analytics/current_plan_details.html
Labels: size: M

#28663 remote-activity: Update column data/structure for remote realms.
  analytics/views/remote_activity.py
Labels: size: L

#28668 queue_processors: Process user_activity in one query.
  zerver/actions/user_activity.py
  zerver/tests/test_import_export.py
  zerver/tests/test_queue_worker.py
  zerver/worker/queue_processors.py
Labels: size: XL

#28671 message_viewport: Remove needlessly complex make_dimen_wrapper
  web/src/message_viewport.ts
Labels: size: M

#28673 remote_billing: Pass language argument to send_email calls.
  corporate/views/remote_billing_page.py
Labels: size: XS

#28674 test_queue_worker: Use integer epoch values.
  zerver/tests/test_queue_worker.py
Labels: size: XS

#28675 stream_edit_subscribers: Remove unnecessary logging.
  web/src/stream_edit_subscribers.js
Labels: size: XS

#28684 activity-css: Make activity charts header row sticky.
  web/styles/portico/activity.css
Labels: size: S

#28679 vdom: Fix types to avoid relying on unsound bivariance
  web/src/pm_list_dom.ts
  web/src/vdom.ts
Labels: size: L

#28681 plans-template: Show end date of legacy plan for push notifications.
  templates/corporate/pricing_model.html
Labels: size: XS

#28574 docs: Add documentation for the new custom auth wrapper setting.
  docs/production/authentication-methods.md
Labels: size: L, backport candidate

#28682 help_menu: Fix help_menu message formatting overlay not opening.
  web/src/info_overlay.js
Labels: size: S

#28688 help: Add announcement info to "Upgrades for legacy customers" section.
  help/self-hosted-billing.md
Labels: size: S, integration review

#28669 api-docs: Clarify realm_authentication_methods in /register response
  zerver/openapi/zulip.yaml
Labels: size: S, api docs review

#28689 populate_db: Only make valid email addresses.
  zilencer/management/commands/populate_db.py
Labels: size: XS

#28513 help: Document how to use an emoji in a topic name.
  help/emoji-and-emoticons.md
  help/include/emoji-and-emoticons-intro.md
Labels: size: L, integration review

#28692 import: Rewrite "delivered_message" column of scheduled messages.
  zerver/lib/import_realm.py
Labels: bug, area: export/import, size: S, backport candidate

#27952 typeahead: Fix bug where typeahead showed momentarily on shift + tab.
  web/third/bootstrap-typeahead/typeahead.js
Labels: bug, priority: high, size: S, difficult, integration review, area: compose (typeahead)

#28712 puppet: Fix grafana tarball path.
  puppet/zulip_ops/manifests/profile/grafana.pp
Labels: size: XS

#28715 nagios: Remove locks alert.
  puppet/zulip_ops/files/nagios4/conf.d/services.cfg
Labels: size: S

#28484 css: Making the height of compose bars steady.
  web/styles/compose.css
  web/styles/zulip.css
Labels: area: compose (misc), size: S, deployed on chat.zulip.org

#28665 remote-activity: Reduce number of database queries for view.
  analytics/tests/test_activity_views.py
  corporate/lib/analytics.py
  corporate/lib/stripe.py
  corporate/lib/support.py
Labels: size: XL

#28713 puppet: Add vector pipelines for other Akamai SQS queues.
  puppet/zulip_ops/manifests/prometheus/akamai.pp
  puppet/zulip_ops/templates/vector.toml.template.erb
Labels: size: L

#28714 puppet: statuspage-pusher uses zulip.conf for page_id.
  puppet/zulip_ops/files/statuspage-pusher
  puppet/zulip_ops/manifests/statuspage.pp
Labels: size: XS

#28631 templates: Remove the extraneous background color.
  web/styles/settings.css
  web/templates/settings/data_exports_admin.hbs
Labels: bug, good first issue, area: settings UI, size: S

#28711 activity: Add totals row as sticky footer to activity charts.
  analytics/views/activity_common.py
  analytics/views/installation_activity.py
  analytics/views/realm_activity.py
  analytics/views/remote_activity.py
  corporate/lib/analytics.py
  templates/analytics/ad_hoc_query.html
  templates/analytics/realm_summary_table.html
  web/styles/portico/activity.css
Labels: size: L

#28556 Help: Add documentation for installation through Flathub.
  help/desktop-app-install-guide.md
  tools/linter_lib/custom_check.py
Labels: area: documentation (user), area: portico, size: S, integration review

#28651 Improve validation at the `register/server` endpoint
  tools/lib/capitalization.py
  zerver/tests/test_push_notifications.py
  zilencer/views.py
Labels: size: XL

#28729 docs: Update priorities GitHub board link 8.0->9.0.
  docs/overview/release-lifecycle.md
Labels: size: XS, integration review

#28723 help: Clarify that newsletter only goes to Zulip Cloud users.
  help/email-notifications.md
Labels: integration review

#28648 topic_generator: Convert module to typescript.
  web/src/stream_list_sort.ts
  web/src/topic_generator.ts
  web/tests/topic_generator.test.js
Labels: size: M, area: typescript migration

#28041 stream_settings: Add stream "reset to default notifications" button.
  web/src/stream_edit.js
  web/templates/stream_settings/stream_settings.hbs
Labels: size: M, integration review

#28727 help: Simplify direct messages documentation.
  help/direct-messages.md
  help/include/send-dm.md
  help/include/starting-a-new-direct-message.md
Labels: size: XL, integration review, help center review

#28717 help: Document how to configure warnings about mobile notifications.
  help/mobile-notifications.md
Labels: area: documentation (user), priority: high, area: mobile, size: S, integration review

#28722 bootstrap: Fork CSS into app, portico copies.
  docs/THIRDPARTY
  web/src/bundles/app.ts
  web/src/bundles/common.ts
  web/src/bundles/portico.ts
  web/third/bootstrap/css/bootstrap.app.css
  web/third/bootstrap/css/bootstrap.portico.css
  web/webpack.assets.json
Labels: area: portico, size: XL, bootstrap removal

#28646 topic list: Convert module to typescript.
  tools/test-js-with-node
  web/src/topic_list.ts
  web/src/topic_list_data.ts
Labels: size: XL, area: typescript migration

#28741 bootstrap: Remove "bootstrap.btn" classes from support view buttons.
  templates/analytics/current_plan_forms_support.html
  templates/analytics/realm_details.html
  templates/analytics/remote_server_support.html
  templates/analytics/sponsorship_forms_support.html
  templates/analytics/support.html
  web/styles/portico/activity.css
Labels: size: XL, bootstrap removal

#28658 left_sidebar: Add mark all messages unread to three dot topic menu.
  web/src/popover_menus_data.js
  web/src/topic_popover.js
  web/src/unread_ops.js
  web/templates/topic_sidebar_actions.hbs
Labels: area: topics, priority: high, size: L, integration review, area: left sidebar (popovers)

#24563 typeahead: Prefer word boundary matches to arbitrary substring matches.
  web/shared/src/typeahead.ts
  web/src/typeahead_helper.ts
  web/tests/composebox_typeahead.test.js
  web/tests/typeahead.test.js
  web/tests/typeahead_helper.test.js
Labels: area: emoji, priority: high, size: XL, integration review, area: compose (typeahead)

#28749 support: Always show the option to update end_date on /support page.
  corporate/lib/stripe.py
  templates/corporate/support/current_plan_forms_support.html
Labels: size: S

#28384 integrations: Create incoming webhook for Patreon.
  static/images/integrations/bot_avatars/patreon.png
  static/images/integrations/logos/patreon.png
  static/images/integrations/patreon/001.png
  zerver/lib/integrations.py
  zerver/webhooks/patreon/__init__.py
  zerver/webhooks/patreon/doc.md
  zerver/webhooks/patreon/fixtures/members_create.json
  zerver/webhooks/patreon/fixtures/members_delete.json
  zerver/webhooks/patreon/fixtures/members_pledge_create.json
  zerver/webhooks/patreon/fixtures/members_pledge_create_paid_post.json
  zerver/webhooks/patreon/fixtures/members_pledge_delete.json
  zerver/webhooks/patreon/fixtures/members_pledge_update.json
  zerver/webhooks/patreon/fixtures/members_update.json
  zerver/webhooks/patreon/tests.py
  zerver/webhooks/patreon/view.py
Labels: area: integrations, size: XL, integration review

#27259 Renaming graph to source
  zerver/webhooks/alertmanager/tests.py
  zerver/webhooks/alertmanager/view.py
Labels: size: S

#28760 contributor docs: Link to GSoC 2023 blog post.
  docs/outreach/overview.md
Labels: size: XS, integration review

#28769 settings: Fix buggy conversion of emoji-display-settings-status.
  web/templates/settings/display_settings.hbs
Labels: size: XS
