Repository zulip/zulip, pull requests merged in 2025-04, with the labels that each got.

#34250 subscription_info: Add option to get partial subscribers.
  zerver/lib/events.py
  zerver/lib/home.py
  zerver/lib/subscription_info.py
  zerver/tests/test_subs.py
Labels: size: M

#34247 unescape-contents: Remove
  tools/i18n/sync-translations
  tools/i18n/unescape-contents
  tools/i18n/unescape-html-in-json-translations
Labels: area: internationalization, size: L, integration review

#34248 help: Improve inbox and recent conversations docs.
  help/inbox.md
  help/include/inbox-instructions.md
  help/include/recent-conversations.md
Labels: area: documentation (user), priority: high, size: S, integration review

#34238 compose: Prevent picker from collapsing.
  web/styles/compose.css
Labels: bug, size: XS, backport candidate, integration review, area: compose (recipient pickers)

#34260 nginx: Use cache slicing to prevent thundering herds for video thumbs.
  puppet/zulip/files/nginx/zulip-include-frontend/uploads-internal.conf
Labels: size: S, backport candidate

#34216 navigate: Fix up keypress behaviour when a long prev message.
  web/src/navigate.ts
Labels: size: S, integration review

#34213 rendered_markdown: Adjust content blocks for link focus ring.
  web/styles/app_variables.css
  web/styles/message_row.css
  web/styles/rendered_markdown.css
Labels: bug, area: markdown, size: M, area: message feed (display), integration review

#34249 corporate: Add more detail to job description.
  .codespellignore
  templates/corporate/jobs.html
Labels: size: M, integration review

#34228 app: Track keyboard overlaps with compose box bug as a TODO.
  templates/zerver/app/index.html
Labels: size: S

#34264 postgresql: Remove inaccurate comment.
  puppet/zulip/templates/postgresql/13/postgresql.conf.template.erb
  puppet/zulip/templates/postgresql/14/postgresql.conf.template.erb
  puppet/zulip/templates/postgresql/zulip.conf.template.erb
Labels: size: S

#34268 Don't show 0 invitations in user deactivation modal
  web/templates/confirm_dialog/confirm_deactivate_user.hbs
Labels: priority: high, size: S, area: popovers, backport candidate, integration review

#34270 message_row: Restore copy button in edit textbox.
  web/styles/message_row.css
Labels: bug, area: message-editing, size: XS, integration review

#34262 subscription_info: Send partial subscriber info to client separately.
  zerver/lib/subscription_info.py
  zerver/lib/types.py
  zerver/tests/test_subs.py
Labels: size: XL

#34233 css: Remove unused transition property.
  web/styles/app_components.css
  web/styles/message_row.css
  web/styles/zulip.css
Labels: size: S, backport candidate, integration review

#34279 actions: Add test upgrade from 10.0.
  .github/workflows/production-suite.yml
Labels: size: XS, backport candidate

#34277 upload: Fix send button disabled when compose is closed during upload.
  web/src/upload.ts
  web/tests/upload.test.cjs
Labels: size: S

#34281 user_groups: Add do_reactivate_user_group function.
  zerver/actions/user_groups.py
  zerver/models/realm_audit_logs.py
  zerver/tests/test_audit_log.py
  zerver/tests/test_events.py
  zerver/tornado/event_queue.py
Labels: size: L

#34239 snippets: Better distinguish snippet content in dropdown.
  web/styles/compose.css
Labels: size: XS, backport candidate, integration review, QA needed, area: compose (UI & widgets)

#34138 settings: Update add/remove buttons on channel/group creation.
  web/e2e-tests/stream_create.test.ts
  web/src/stream_create_subscribers.ts
  web/src/user_group_create_members.ts
  web/templates/stream_settings/new_stream_user.hbs
  web/templates/user_group_settings/new_user_group_subgroup.hbs
Labels: size: L, integration review

#34141 user_profile_modal: Use icon button component for modal header buttons.
  web/src/user_profile.ts
  web/styles/dark_theme.css
  web/styles/modal.css
  web/styles/popovers.css
  web/templates/user_profile_modal.hbs
Labels: size: L, integration review

#34155 user-card-tooltip: Open user card when user-card-tooltip visible.
  web/src/user_card_popover.ts
Labels: size: S, integration review

#34203 message_move: Fix some bugs found in moving messages/topics.
  web/src/stream_popover.ts
Labels: size: M, backport candidate, integration review

#34251 users: Send peer_remove on deactivating user.
  api_docs/changelog.md
  version.py
  zerver/actions/users.py
  zerver/openapi/zulip.yaml
  zerver/tests/test_events.py
Labels: area: real-time sync, priority: high, size: L, integration review

#34294 nginx: Serve full app from localhost.
  puppet/zulip/templates/nginx/zulip-enterprise.template.erb
Labels: size: S, backport candidate

#34290 registration: Fix 500 error pages rendered without context.
  zerver/views/registration.py
Labels: size: S

#34282 peer_data: Process partial_subscriber data.
  web/src/peer_data.ts
  web/src/stream_data.ts
  web/src/stream_types.ts
  web/tests/stream_data.test.cjs
Labels: size: S

#34300 settings: Make all of thead sticky.
  web/styles/settings.css
Labels: size: XS

#34297 update-for-legacy-translations: Don’t delete empty strings
  locale/ar/translations.json
  locale/bg/translations.json
  locale/ca/translations.json
  locale/cy/translations.json
  locale/da/translations.json
  locale/de/translations.json
  locale/es/translations.json
  locale/fa/translations.json
  locale/fr/translations.json
  locale/gu/translations.json
  locale/hi/translations.json
  locale/hu/translations.json
  locale/id/translations.json
  locale/ko/translations.json
  locale/mn/translations.json
  locale/nl/translations.json
  locale/pt_PT/translations.json
  locale/ro/translations.json
  locale/sr/translations.json
  locale/sv/translations.json
  locale/tr/translations.json
  locale/uk/translations.json
  locale/vi/translations.json
  locale/zh_Hans/translations.json
  locale/zh_TW/translations.json
  tools/i18n/update-for-legacy-translations
Labels: area: internationalization, size: XL, integration review

#34053 dm_headers: Show bot icon after bot name.
  web/src/message_list_view.ts
  web/styles/message_header.css
  web/templates/recipient_row.hbs
Labels: area: bots, size: S, area: message feed (display), integration review

#34132 do_change_user_email: Store old and new email in the audit log.
  zerver/actions/user_settings.py
  zerver/tests/test_audit_log.py
Labels: size: S, integration review

#34310 test_classes: Mention actual and expected count in assert_length.
  zerver/lib/test_classes.py
Labels: size: XS

#34321 dark_theme: Clean up compose banners.
  web/styles/app_variables.css
  web/styles/compose.css
  web/styles/dark_theme.css
Labels: size: XL, integration review, area: light/dark theme

#34319 install: Support PostgreSQL 17
  docs/overview/changelog.md
  docs/production/deployment.md
  docs/production/postgresql-support-table.md
  docs/production/postgresql.md
  puppet/zulip/manifests/profile/postgresql.pp
  scripts/lib/install
  scripts/setup/upgrade-postgresql
Labels: size: M, backport candidate, integration review

#34177 Remap ':smile' emoji and Update the settings UI
  tools/setup/emoji/custom_emoji_names.py
  tools/setup/emoji/emoji_names.py
  tools/setup/emoji/emoji_setup_utils.py
  version.py
  web/shared/src/typeahead.ts
  web/src/settings_config.ts
  web/templates/settings/preferences_emoji.hbs
  web/tests/compose_paste.test.cjs
  web/tests/emoji.test.cjs
  web/tests/markdown.test.cjs
  web/tests/markdown_parse.test.cjs
  web/tests/reactions.test.cjs
  web/tests/typeahead.test.cjs
  zerver/management/data/unified_reactions.json
  zerver/tests/fixtures/markdown_test_cases.json
  zerver/tests/test_reactions.py
Labels: area: emoji, size: XL

#34322 install: Remove PostgreSQL 13 support
  docs/overview/changelog.md
  docs/production/deployment.md
  puppet/zulip/manifests/profile/postgresql.pp
  puppet/zulip/templates/postgresql/13/postgresql.conf.template.erb
  scripts/lib/check-database-compatibility
  scripts/lib/install
Labels: size: XL

#34127 popovers: Add an `x` button to topic field in move topic/move messages modal.
  web/src/stream_popover.ts
  web/styles/popovers.css
  web/templates/move_topic_to_stream.hbs
Labels: priority: high, size: L, area: popovers, integration review, area: message-editing (topics)

#34329 user_card: Fix mismatch between tooltip and popover trigger area.
  web/src/user_card_popover.ts
  web/templates/message_avatar.hbs
Labels: size: S

#34320 Issue 34318 split models file
  corporate/lib/activity.py
  corporate/lib/registration.py
  corporate/lib/stripe.py
  corporate/lib/stripe_event_handler.py
  corporate/lib/support.py
  corporate/models.py
  corporate/models/__init__.py
  corporate/models/customers.py
  corporate/models/licenses.py
  corporate/models/plans.py
  corporate/models/sponsorships.py
  corporate/models/stripe_state.py
  corporate/tests/test_activity_views.py
  corporate/tests/test_remote_billing.py
  corporate/tests/test_stripe.py
  corporate/tests/test_support_views.py
  corporate/views/billing_page.py
  corporate/views/plan_activity.py
  corporate/views/portico.py
  corporate/views/remote_billing_page.py
  corporate/views/support.py
  corporate/views/upgrade.py
  corporate/views/webhook.py
  zerver/actions/realm_settings.py
  zerver/lib/events.py
  zerver/lib/test_classes.py
  zerver/management/commands/delete_realm.py
  zerver/tests/test_docs.py
  zerver/tests/test_home.py
  zerver/tests/test_push_notifications.py
  zilencer/management/commands/populate_billing_realms.py
  zilencer/management/commands/switch_realm_from_standard_to_plus_plan.py
  zilencer/views.py
Labels: size: XL

#34326 message: Use set instead of list when checking DM permission.
  zerver/actions/message_send.py
  zerver/lib/user_groups.py
Labels: size: S

#34346 nginx: Relay the same Host: header that nginx saw.
  puppet/zulip/files/nginx/zulip-include-common/proxy
Labels: size: XS, backport candidate

#34334 tests: Fix admin.test.ts puppeteer test case failing.
  web/e2e-tests/admin.test.ts
Labels: size: S

#34349 user_groups: Realm admins should be allowed moderator permissions.
  zerver/lib/user_groups.py
  zerver/tests/test_user_groups.py
Labels: size: S, backport candidate

#34344 Backported live update fix from #34205.
  web/src/server_events_dispatch.js
Labels: size: XS

#34332 settings: Calculate height of create modal through javascript.
  web/src/resize.ts
  web/src/stream_create.ts
  web/src/stream_settings_ui.ts
  web/src/user_group_create.ts
  web/src/user_group_edit.ts
  web/styles/app_variables.css
  web/styles/subscriptions.css
  web/templates/stream_settings/stream_creation_form.hbs
  web/templates/user_group_settings/user_group_creation_form.hbs
Labels: size: L, integration review

#34359 webpack: Use CORS requests for stylesheets
  templates/zerver/base.html
Labels: size: XS

#34361 narrow: Fix get_base_query_for_search access restrictions
  zerver/lib/narrow.py
  zerver/tests/test_message_fetch.py
Labels: size: M, backport candidate

#34197 left_sidebar: Fix Enter key behavior on "Show all topics" link.
  web/styles/left_sidebar.css
  web/templates/more_topics.hbs
Labels: size: S, integration review

#33387 settings: Show desktop notifications warning when permissions needed.
  web/src/settings_notifications.ts
  web/templates/settings/notification_settings.hbs
Labels: size: L, integration review

#34374 smokescreen: Move metrics port from the default 9810, to 4760.
  puppet/kandra/manifests/profile/chat_zulip_org.pp
  puppet/kandra/manifests/profile/smokescreen.pp
  puppet/kandra/templates/prometheus/prometheus.yaml.template.erb
  puppet/zulip/templates/supervisor/smokescreen.conf.erb
Labels: size: S

#34369 message_overlay: Fix restore tooltips detached with message content.
  web/src/drafts_overlay_ui.ts
  web/src/messages_overlay_ui.ts
  web/src/scheduled_messages_overlay_ui.ts
  web/templates/draft.hbs
  web/templates/scheduled_message.hbs
  web/tests/drafts.test.cjs
Labels: size: M

#34379 contributor docs: Update info on icons in the help center.
  docs/documentation/helpcenter.md
Labels: size: M, integration review

#34381 kandra: Add a couple useful command-line tools.
  puppet/kandra/manifests/profile/base.pp
Labels: size: S

#34383 tusd: Use GCS upload backend when the endpoint matches.
  docs/production/upload-backends.md
  zerver/management/commands/runtusd.py
Labels: bug, size: S, backport candidate

#34199 messages: Drop misleading comment on `zerver_message_edit_history_id` idx.
  zerver/models/messages.py
Labels: size: XS

#34272 message_feed UI: Update logo dimensions for better scalability.
  web/styles/zulip.css
Labels: bug, priority: high, size: S, area: message feed (UI), backport candidate, integration review

#34388 settings: Exclude nobody from channel and group settings typeahead.
  web/src/add_group_members_pill.ts
  web/src/add_subscribers_pill.ts
Labels: size: S, backport candidate

#34386 tools: Use .md extension for temporary API changelog files.
  tools/create-api-changelog
  tools/merge-api-changelogs
Labels: size: XS

#34087 help-center: Support to quote and copy-paste LaTeX.
  help/latex.md
Labels: size: M, backport candidate, integration review

#34108 popup_banners: Update connection error banner label.
  web/src/popup_banners.ts
Labels: size: S, integration review, area: banners

#33556 compose: Add banner when topic is moved and recipient is updated.
  web/src/compose_banner.ts
  web/src/compose_recipient.ts
  web/src/compose_state.ts
  web/src/compose_validate.ts
  web/src/message_events.ts
  web/templates/compose_banner/topic_moved_banner.hbs
  web/templates/inline_topic_link_label.hbs
Labels: size: L, integration review, area: compose (banners & validation)

#31720 feed: Modify the channel feed text for muted topics.
  web/src/narrow_banner.ts
  web/tests/message_view.test.cjs
Labels: size: L, area: message feed (UI), integration review

#34393 doc: Add an error explanation in schema migrations.
  docs/subsystems/schema-migrations.md
Labels: size: S

#34394 Fix opening settings for guests who cannot access all users.
  web/src/people.ts
  web/tests/activity.test.cjs
  web/tests/buddy_list.test.cjs
  web/tests/compose_pm_pill.test.cjs
  web/tests/compose_validate.test.cjs
  web/tests/conversation_participants.test.cjs
  web/tests/peer_data.test.cjs
  web/tests/people.test.cjs
  web/tests/stream_events.test.cjs
  web/tests/user_events.test.cjs
  web/tests/user_group_pill.test.cjs
  web/tests/user_pill.test.cjs
  web/tests/user_search.test.cjs
Labels: size: L, backport candidate

#34402 tests: clean tests and pass update_fields to all stream.save()
  zerver/actions/streams.py
  zerver/migrations/0210_stream_first_message_id.py
  zerver/tests/test_digest.py
  zerver/tests/test_events.py
  zerver/tests/test_import_export.py
  zerver/tests/test_message_send.py
  zerver/tests/test_retention.py
  zerver/tests/test_subs.py
  zerver/tests/test_user_topics.py
Labels: size: M

#34396 streams: Change text in notification bot DM.
  zerver/tests/test_subs.py
  zerver/views/streams.py
Labels: size: S, integration review

#34407 tusd: Update development version.
  tools/setup/install-tusd
Labels: size: S

#34410 banner: Prevent duplicate desktop notification banners.
  web/src/settings_notifications.ts
Labels: size: XS

#34411 meta-tag: Remove invalid space in viewport meta tag.
  templates/zerver/app/index.html
Labels: size: XS

#34415 users: Fix comment for base_bulk_get_user_queryset.
  zerver/models/users.py
Labels: size: XS

#34425 api-version: Bump API version for prev_content_sha256 parameter.
  version.py
Labels: area: api, size: XS

#34427 upgrade: Remove demo_organization_scheduled_deletion_date page param.
  corporate/lib/stripe.py
  web/src/base_page_params.ts
Labels: size: S

#34438 corporate: Update GetApp, Capterra badges.
  static/images/landing-page/hello/capterra-2023.png
  templates/corporate/hello.html
Labels: area: portico, size: S, integration review

#34445 corporate: Show "Fixed" as rate for fixed-rate plans in activity charts.
  corporate/lib/activity.py
Labels: size: S, area: billing, area: support

#34367 Add save btn tooltip for exceeded message length
  web/src/compose_validate.ts
Labels: size: XS, integration review

#34409 message_header: Use topic permalink.
  web/src/message_list_view.ts
Labels: size: S, integration review

#34314 keyboard_UI: fix #33838 'e' keyboard shortcut for anonymous user.
  web/src/hotkey.js
  web/tests/hotkey.test.cjs
Labels: bug, area: keyboard UI, size: M, area: public access, integration review

#34435 api-docs: Add note about realm being present in fetch_event_types.
  zerver/openapi/zulip.yaml
Labels: area: documentation (api and integrations), size: L

#34389 css: Remove `.thinner` class used in Settings > Preferences.
  web/styles/settings.css
  web/templates/settings/preferences_information.hbs
  web/templates/settings/preferences_navigation.hbs
  web/templates/settings/settings_numeric_input.hbs
Labels: size: S, integration review

#34397 send_email: Add a flag to force all emails through the queue.
  zerver/lib/send_email.py
  zerver/worker/email_senders_base.py
  zproject/default_settings.py
Labels: size: L

#34451 unread_data: Ensure deterministic ordering of unread message rows.
  zerver/lib/message.py
Labels: size: XS, backport candidate

#32650 github webhook: Support all actions on discussion events.
  zerver/webhooks/github/fixtures/discussion.json
  zerver/webhooks/github/fixtures/discussion__answered.json
  zerver/webhooks/github/fixtures/discussion__category_changed.json
  zerver/webhooks/github/fixtures/discussion__closed.json
  zerver/webhooks/github/fixtures/discussion__created.json
  zerver/webhooks/github/fixtures/discussion__deleted.json
  zerver/webhooks/github/fixtures/discussion__edited_body.json
  zerver/webhooks/github/fixtures/discussion__edited_title.json
  zerver/webhooks/github/fixtures/discussion__labeled.json
  zerver/webhooks/github/fixtures/discussion__locked.json
  zerver/webhooks/github/fixtures/discussion__pinned.json
  zerver/webhooks/github/fixtures/discussion__reopened.json
  zerver/webhooks/github/fixtures/discussion__transferred.json
  zerver/webhooks/github/fixtures/discussion__unanswered.json
  zerver/webhooks/github/fixtures/discussion__unlabeled.json
  zerver/webhooks/github/fixtures/discussion__unlocked.json
  zerver/webhooks/github/fixtures/discussion__unpinned.json
  zerver/webhooks/github/tests.py
  zerver/webhooks/github/view.py
Labels: size: XL, integration review

#34437 corporate: Don't show upgrade and sponsorship forms for demo organizations.
  corporate/lib/stripe.py
  corporate/tests/test_stripe.py
  corporate/views/sponsorship.py
  corporate/views/upgrade.py
  templates/corporate/billing/demo_organization_billing_disabled.html
  templates/corporate/billing/sponsorship.html
  templates/corporate/billing/upgrade.html
  web/styles/portico/portico_signin.css
Labels: area: onboarding, size: XL, area: billing, integration review

#34423 attachments: Allow seeing attachments to users with content access.
  zerver/lib/attachments.py
  zerver/tests/test_subs.py
  zerver/tests/test_upload.py
Labels: size: XL, backport candidate

#34449 dev_docs: Document the process for preparing icons for Zulip use.
  docs/images/icon-prep-evenodd-broken-conversion.png
  docs/images/icon-prep-evenodd-correct-preview.png
  docs/images/icon-prep-stroke-broken-conversion.png
  docs/images/icon-prep-stroke-correct-preview.png
  docs/images/icon-prep-stroke-to-path-completed.png
  docs/images/icon-prep-stroke-to-path-initial.png
  docs/subsystems/icons.md
Labels: area: documentation (developer), size: XL, integration review, documentation review

#34418 Altcha
  package.json
  pnpm-lock.yaml
  pyproject.toml
  templates/zerver/create_realm.html
  uv.lock
  version.py
  web/src/portico/signup.ts
  web/styles/portico/portico_signin.css
  zerver/forms.py
  zerver/lib/test_classes.py
  zerver/tests/test_signup.py
  zerver/views/antispam.py
  zerver/views/registration.py
  zproject/computed_settings.py
  zproject/default_settings.py
  zproject/urls.py
Labels: size: XL

#34459 attachments: Use early return and improve comments.
  zerver/lib/attachments.py
Labels: size: L

#34428 thumbnail: Add a tool to re-thumbnail spinners, or process old images.
  zerver/actions/message_edit.py
  zerver/lib/thumbnail.py
  zerver/management/commands/thumbnail.py
  zerver/tests/test_markdown_thumbnail.py
Labels: size: XL, integration review

#34107 refactor: Rename huddle to direct message group in email templates.
  locale/ar/LC_MESSAGES/django.po
  locale/be/LC_MESSAGES/django.po
  locale/bg/LC_MESSAGES/django.po
  locale/bqi/LC_MESSAGES/django.po
  locale/ca/LC_MESSAGES/django.po
  locale/cs/LC_MESSAGES/django.po
  locale/cy/LC_MESSAGES/django.po
  locale/da/LC_MESSAGES/django.po
  locale/de/LC_MESSAGES/django.po
  locale/en_GB/LC_MESSAGES/django.po
  locale/eo/LC_MESSAGES/django.po
  locale/es/LC_MESSAGES/django.po
  locale/fa/LC_MESSAGES/django.po
  locale/fi/LC_MESSAGES/django.po
  locale/fr/LC_MESSAGES/django.po
  locale/gl/LC_MESSAGES/django.po
  locale/gu/LC_MESSAGES/django.po
  locale/hi/LC_MESSAGES/django.po
  locale/hu/LC_MESSAGES/django.po
  locale/id/LC_MESSAGES/django.po
  locale/it/LC_MESSAGES/django.po
  locale/ja/LC_MESSAGES/django.po
  locale/ko/LC_MESSAGES/django.po
  locale/lt/LC_MESSAGES/django.po
  locale/lv/LC_MESSAGES/django.po
  locale/ml/LC_MESSAGES/django.po
  locale/mn/LC_MESSAGES/django.po
  locale/nl/LC_MESSAGES/django.po
  locale/no/LC_MESSAGES/django.po
  locale/pl/LC_MESSAGES/django.po
  locale/pt/LC_MESSAGES/django.po
  locale/pt_BR/LC_MESSAGES/django.po
  locale/pt_PT/LC_MESSAGES/django.po
  locale/ro/LC_MESSAGES/django.po
  locale/ru/LC_MESSAGES/django.po
  locale/si/LC_MESSAGES/django.po
  locale/sr/LC_MESSAGES/django.po
  locale/sv/LC_MESSAGES/django.po
  locale/ta/LC_MESSAGES/django.po
  locale/tl/LC_MESSAGES/django.po
  locale/tr/LC_MESSAGES/django.po
  locale/uk/LC_MESSAGES/django.po
  locale/vi/LC_MESSAGES/django.po
  locale/zh_Hans/LC_MESSAGES/django.po
  locale/zh_TW/LC_MESSAGES/django.po
  templates/zerver/emails/missed_message.subject.txt
  zerver/lib/email_notifications.py
Labels: size: XL, integration review

#34457 models: Add creation_timestamp field to ScheduledMessage table.
  zerver/lib/export.py
  zerver/migrations/0698_scheduledmessage_request_timestamp.py
  zerver/models/scheduled_jobs.py
Labels: size: S

#34465 demo-orgs: Fix invite user modal when owner hasn't set an email address.
  web/src/invite.ts
  web/styles/app_variables.css
  web/styles/input_pill.css
  web/templates/invite_user_modal.hbs
Labels: area: onboarding, size: S

#34475 left_sidebar: Align muted unreads with correct em value.
  web/styles/app_variables.css
Labels: priority: high, size: XS, integration review, area: left sidebar (display)

#34350 rest_api: Add logging to REST path.
  zerver/lib/rest.py
  zerver/tests/test_bots.py
Labels: size: S

#34431 banners: Improve banner layout dimensions.
  web/styles/banners.css
Labels: size: S

#34481 help: Document option to add the members of a group to a group.
  help/manage-user-groups.md
Labels: size: S, integration review

#34483 Fix deactivated icon being shown in message avatar for inaccessible users.
  web/src/people.ts
  web/tests/people.test.cjs
Labels: size: S

#34432 banners: Fix banner grid layout for medium and small variants.
  web/styles/app_variables.css
Labels: size: S, maintainer review

#34495 help: Expand organization profile description.
  help/include/edit-organization-profile.md
  help/include/organization-profile-intro.md
  help/include/organization-type-intro.md
  help/organization-type.md
Labels: size: M, integration review

#34509 page_loader: Correct hard-coded pixel values.
  web/src/loading.ts
  web/styles/app_components.css
  web/styles/zulip.css
Labels: bug, size: S, area: message feed (UI), integration review

#34506 hotkey: Fix warning about unused `login_to_access` import.
  web/src/spectators.ts
  web/tests/hotkey.test.cjs
Labels: size: S

#34510 ldap: Fix the syncing of user role via AUTH_LDAP_USER_FLAGS_BY_GROUP.
  zerver/actions/create_user.py
  zerver/lib/test_classes.py
  zerver/tests/test_auth_backends.py
  zerver/tests/test_signup.py
  zproject/backends.py
Labels: size: XL, backport candidate

#34512 push_notifs: In dev, use EXTERNAL_HOST directly as bouncer
  zproject/dev_settings.py
  zproject/test_extra_settings.py
Labels: size: XS

#34231 integrations: Handle approval/unapproval for GitLab MRs.
  zerver/lib/webhooks/git.py
  zerver/webhooks/gitlab/fixtures/merge_request_hook__merge_request_approval.json
  zerver/webhooks/gitlab/fixtures/merge_request_hook__merge_request_unapproval.json
  zerver/webhooks/gitlab/tests.py
  zerver/webhooks/gitlab/view.py
Labels: size: XL, integration review

#34494 integration-docs: Clarify the installation macro.
  templates/zerver/integrations/include/download-python-bindings.md
Labels: area: documentation (api and integrations), size: XS, integration review

#34503 Fix group pill expand button and refactor code to handle subscribers and members pill widget.
  web/src/add_group_members_pill.ts
  web/src/add_subscribers_pill.ts
  web/src/stream_create_subscribers.ts
  web/src/stream_edit_subscribers.ts
  web/src/user_group_create_members.ts
  web/src/user_group_edit_members.ts
Labels: size: XL

#34489 demo-orgs: Expand note about demo organizations in Welcome bot DM.
  zerver/lib/onboarding.py
Labels: area: onboarding, size: S

#34487 invite-modal: Render banners for non-demo orgs and admin users only.
  web/src/invite.ts
  web/templates/invite_user_modal.hbs
Labels: area: onboarding, size: S

#34490 demo-orgs: Update note about updating name in add email modal.
  web/templates/demo_organization_add_email_modal.hbs
Labels: area: onboarding, size: XS

#34492 demo-orgs: Update tooltip text for disabled manage API key button.
  web/src/tippyjs.ts
Labels: area: onboarding, size: S

#34514 people: Remove stray console.logs that made it into main.
  web/tests/people.test.cjs
Labels: size: XS

#34482 message_view: Live update on losing access to a stream.
  web/src/message_store.ts
  web/src/server_events_dispatch.js
  web/src/stream_topic_history.ts
  web/tests/dispatch_subs.test.cjs
  web/tests/message_store.test.cjs
  web/tests/stream_topic_history.test.cjs
Labels: size: XL

#34515 page_loader: Correct clipped logo circle.
  templates/zerver/app/index.html
  web/styles/zulip.css
Labels: size: S

#34520 left_sidebar: Correct for bleedthrough on zoomed-in channel.
  web/styles/left_sidebar.css
Labels: size: S, integration review

#34522 tests: Assume failure in case the async task vanishes
  web/tests/lib/index.cjs
Labels: area: testing-infrastructure, size: S

#34517 org_settings: Correctly display long channel names.
  web/styles/settings.css
Labels: size: S, integration review

#34528 demo-orgs: Update tooltip for disabled personal email access setting.
  web/src/tippyjs.ts
Labels: area: onboarding, size: XS
