Repository zulip/zulip, pull requests merged in 2025-06, with the labels that each got.

#34780 generate-integration-docs-screenshot script improvements
  tools/screenshots/generate-integration-docs-screenshot
Labels: size: L

#34795 left_sidebar: Show sidebar menu icon for muted unread messages.
  web/src/left_sidebar_navigation_area.ts
  web/src/unread.ts
Labels: bug, size: S, integration review, area: left sidebar (ui)

#34800 app: Disallow overscroll on x-axis.
  web/styles/zulip.css
Labels: bug, area: browser-support, size: XS, integration review

#34801 i18n: Trim and remove "fuzzy" flag from msgstr with trimmed msgid.
  locale/ar/LC_MESSAGES/django.po
  locale/be/LC_MESSAGES/django.po
  locale/bg/LC_MESSAGES/django.po
  locale/bqi/LC_MESSAGES/django.po
  locale/ca/LC_MESSAGES/django.po
  locale/cs/LC_MESSAGES/django.po
  locale/cy/LC_MESSAGES/django.po
  locale/da/LC_MESSAGES/django.po
  locale/de/LC_MESSAGES/django.po
  locale/en_GB/LC_MESSAGES/django.po
  locale/eo/LC_MESSAGES/django.po
  locale/es/LC_MESSAGES/django.po
  locale/fa/LC_MESSAGES/django.po
  locale/fi/LC_MESSAGES/django.po
  locale/fr/LC_MESSAGES/django.po
  locale/gl/LC_MESSAGES/django.po
  locale/gu/LC_MESSAGES/django.po
  locale/hi/LC_MESSAGES/django.po
  locale/hu/LC_MESSAGES/django.po
  locale/id/LC_MESSAGES/django.po
  locale/it/LC_MESSAGES/django.po
  locale/ja/LC_MESSAGES/django.po
  locale/ko/LC_MESSAGES/django.po
  locale/lt/LC_MESSAGES/django.po
  locale/lv/LC_MESSAGES/django.po
  locale/ml/LC_MESSAGES/django.po
  locale/mn/LC_MESSAGES/django.po
  locale/nl/LC_MESSAGES/django.po
  locale/no/LC_MESSAGES/django.po
  locale/pl/LC_MESSAGES/django.po
  locale/pt/LC_MESSAGES/django.po
  locale/pt_BR/LC_MESSAGES/django.po
  locale/pt_PT/LC_MESSAGES/django.po
  locale/ro/LC_MESSAGES/django.po
  locale/ru/LC_MESSAGES/django.po
  locale/si/LC_MESSAGES/django.po
  locale/sr/LC_MESSAGES/django.po
  locale/sv/LC_MESSAGES/django.po
  locale/ta/LC_MESSAGES/django.po
  locale/tl/LC_MESSAGES/django.po
  locale/tr/LC_MESSAGES/django.po
  locale/uk/LC_MESSAGES/django.po
  locale/vi/LC_MESSAGES/django.po
  locale/zh_Hans/LC_MESSAGES/django.po
  locale/zh_TW/LC_MESSAGES/django.po
Labels: size: XL

#34821 test-documentation: Remove unneeded HTML validation exemptions
  tools/documentation.vnufilter
  tools/documentation_crawler/documentation_crawler/spiders/common/spiders.py
Labels: size: XS

#34812 integration-url-modal: Focus on the topic input when it is displayed.
  web/src/integration_url_modal.ts
Labels: size: S, integration review

#33214 integrations: Fix Slack debugging notification message.
  zerver/webhooks/slack/view.py
Labels: size: XS, integration review, mentor review

#34749 buddy_list: Add clarity around not showing user links when searching.
  web/src/buddy_list.ts
Labels: size: S, integration review

#34831 mypy: Remove unused exemption for aiosmtpd
  pyproject.toml
Labels: size: XS

#34817 models: Fix typo in RealmAuthenticationMethod docstring.
  zerver/models/realms.py
Labels: size: XS

#34789 export_search: Support --dm option for 1:1 DMs using DM group.
  zerver/management/commands/export_search.py
Labels: size: S, mentor review

#34787 messages: Add unread 1:1/self DMs to pm_dict if DM group exists.
  zerver/lib/message.py
  zerver/tests/test_message_flags.py
Labels: size: L, mentor review

#33053 list_widget: Fix placeholder for unmatched deactivated user filters.
  web/src/list_widget.ts
  web/src/settings_users.ts
  web/templates/settings/deactivated_users_admin.hbs
Labels: bug, area: settings UI, size: M, integration review, maintainer review

#32660 Add "Alphabetize choices" button for "List of options" type custom profile fields.
  web/src/settings_profile_fields.ts
  web/styles/settings.css
  web/templates/settings/add_new_custom_profile_field_form.hbs
  web/templates/settings/edit_custom_profile_field_form.hbs
Labels: area: settings (admin/org), size: L, new feature, integration review

#34137 copy_messages: Expand selection for math expressions and blocks.
  web/src/copy_messages.ts
Labels: bug, priority: high, size: XL, area: markdown (LaTeX), integration review

#34792 search: Show correct description string for public channels.
  web/src/filter.ts
  web/src/search_suggestion.ts
  web/tests/filter.test.cjs
Labels: size: M, integration review

#34839 docs: Update links help center links that redirect "/user-roles".
  docs/overview/changelog.md
  docs/production/authentication-methods.md
  docs/production/management-commands.md
  docs/production/mobile-push-notifications.md
Labels: area: documentation (production), size: S

#34395 trash-icon: Replace remaining fa-trash icons with zulip-icon-trash and update buttons.
  help/collaborative-to-do-lists.md
  help/create-a-poll.md
  help/saved-snippets.md
  help/schedule-a-message.md
  help/view-and-edit-your-message-drafts.md
  web/src/settings_profile_fields.ts
  web/src/tippyjs.ts
  web/styles/app_components.css
  web/styles/drafts.css
  web/styles/modal.css
  web/styles/settings.css
  web/templates/draft.hbs
  web/templates/draft_table_body.hbs
  web/templates/poll_modal_option.hbs
  web/templates/scheduled_message.hbs
  web/templates/settings/default_stream_choice.hbs
  web/templates/settings/profile_field_choice.hbs
  web/templates/todo_modal_task.hbs
Labels: size: L, area: popovers, redesign, maintainer review

#34847 email_mirror_server: Swallow and log all TLSSetupExceptions.
  zerver/lib/email_mirror_server.py
Labels: size: S

#34846 demo-orgs: Rename do_convert_demo_organization frontend function.
  web/src/demo_organizations_ui.ts
  web/src/gear_menu.ts
  web/src/navbar_alerts.ts
Labels: size: S

#34844 message_view: Fix error on pressing scroll to latest button.
  web/src/message_view.ts
Labels: size: M

#34835 filter: Do not set anchor as `first_unread` for starred messages view.
  web/src/filter.ts
  web/tests/filter.test.cjs
Labels: size: S, integration review

#34875 rendered_markdown: Correct presentation of nested lists.
  web/styles/rendered_markdown.css
Labels: bug, area: markdown, size: S, integration review

#34767 Groups: Can perform any join, leave, add, remove for deactivated group.
  api_docs/changelog.md
  version.py
  web/src/settings_data.ts
  web/src/user_group_edit.ts
  web/tests/settings_data.test.cjs
  zerver/lib/user_groups.py
  zerver/openapi/zulip.yaml
  zerver/tests/test_user_groups.py
  zerver/views/user_groups.py
Labels: size: L, area: settings (user groups), integration review

#34891 puppet: Remove zephyr configuration and hosts.
  puppet/kandra/files/cron.d/test_zephyr_personal_mirrors
  puppet/kandra/files/cron.d/zephyr-mirror
  puppet/kandra/files/iptables/zmirror.v4
  puppet/kandra/files/iptables/zmirror.v6
  puppet/kandra/files/nagios4/commands.cfg
  puppet/kandra/files/nagios4/conf.d/hostgroups.cfg
  puppet/kandra/files/nagios4/conf.d/services.cfg
  puppet/kandra/files/nagios_plugins/zulip_zephyr_mirror/check_personal_zephyr_mirrors
  puppet/kandra/files/nagios_plugins/zulip_zephyr_mirror/check_user_zephyr_mirror_liveness
  puppet/kandra/files/nagios_plugins/zulip_zephyr_mirror/check_zephyr_mirror
  puppet/kandra/files/supervisor/conf.d/zmirror.conf
  puppet/kandra/files/zephyr-clients
  puppet/kandra/manifests/prod_app_frontend_once.pp
  puppet/kandra/manifests/profile/nagios.pp
  puppet/kandra/manifests/profile/prod_app_frontend.pp
  puppet/kandra/manifests/profile/zmirror.pp
  puppet/kandra/manifests/profile/zmirror_personals.pp
  puppet/kandra/templates/nagios4/hosts.cfg.template.erb
Labels: size: XL

#34895 onboarding_steps: Fix abnormal initialize calling convention
  web/src/onboarding_steps.ts
  web/src/state_data.ts
  web/src/ui_init.js
Labels: size: S

#34865 settings-banner: Fix bugs in the rendering of the desktop notification banner.
  web/src/settings_notifications.ts
  web/styles/app_components.css
  web/templates/settings/notification_settings.hbs
Labels: size: M, integration review

#34901 people: Use safePrase to parse error response.
  web/src/people.ts
Labels: size: S

#34907 test_subs: Fix syntax errors in tests.
  zerver/tests/test_subs.py
Labels: size: S

#34925 buttons: Remove focus outline offset in action and icon buttons.
  web/styles/app_variables.css
Labels: size: XS

#34711 Fix empty tooltip on recipient row resolve topic spinner.
  web/src/message_list_tooltips.ts
Labels: size: XS, integration review

#34914 user_profile: Fix the field for outgoing webhook bots `interface`.
  web/templates/settings/add_new_bot_form.hbs
  web/templates/settings/edit_outgoing_webhook_service.hbs
Labels: area: settings UI, size: XS

#34923 icon_button: Clean up extra parameter.
  web/templates/settings/account_settings.hbs
Labels: size: XS, integration review

#34926 input_pill: Fix bug where focus indicator wasn't showing.
  web/styles/input_pill.css
  web/styles/search.css
Labels: size: S, integration review

#34939 puppet: Upgrade dependencies.
  puppet/zulip/manifests/common.pp
Labels: size: L

#34884 report_message: Use existing template for reporting 1:1 DM via DM group.
  zerver/lib/message.py
  zerver/lib/message_report.py
  zerver/tests/test_message_report.py
Labels: size: L, buddy review, mentor review

#34827 compose_paste: Don't paste formatted text at md link marker.
  web/src/compose_paste.ts
Labels: size: M

#34937 demo-orgs: Make password not required for demo organization creation.
  zerver/views/development/registration.py
  zerver/views/registration.py
Labels: size: S

#34769 move_topic_modal: Only include senders of the messages being moved in warning banner.
  web/src/stream_popover.ts
  web/templates/modal_banner/unsubscribed_participants_warning_banner.hbs
Labels: size: L, has conflicts, integration review

#34880 Move administering permission tests to `test_channel_permissions.py`.
  zerver/tests/test_channel_permissions.py
  zerver/tests/test_subs.py
Labels: size: XL, integration review

#34330 streams: Fix error while sending notice in deactivated stream.
  zerver/actions/streams.py
  zerver/tests/test_subs.py
Labels: size: L

#34948 dev-login: Filter placeholder realms from a subdomain change.
  zerver/views/development/dev_login.py
Labels: size: XS

#34945 help: Add edit message tip for mentions notifications.
  help/mention-a-user-or-group.md
Labels: area: documentation (user)

#34950 message_delete: Fix flaky 'do_delete_messages' function.
  zerver/actions/message_delete.py
Labels: size: S

#34778 css: Fix overflow and color issues in GIF popover (#34772).
  web/styles/popovers.css
Labels: size: S, integration review

#34691 help-beta: Use FlattenList component instead of hacky middleware.
  help-beta/src/components/FlattenList.astro
  help-beta/src/middleware.ts
  tools/convert-help-center-docs-to-mdx
Labels: size: XL

#34976 compose: Set grid-area for iconless channel label.
  web/styles/compose.css
Labels: size: S, integration review, area: compose (recipient pickers)

#34978 widgets: Make poll options clickable.
  web/styles/widgets.css
  web/templates/widgets/poll_widget_results.hbs
Labels: accessibility, size: S, area: widgets, integration review

#34974 register: Fix ToS error overlapping with subscribed checkbox text.
  templates/zerver/accounts_accept_terms.html
  templates/zerver/register.html
  web/styles/portico/portico_signin.css
Labels: size: S

#34975 hotkey: Ignore keydown events with `event.key=undefined`.
  web/src/hotkey.js
Labels: size: S

#34983 import: Label tweak.
  templates/zerver/realm_creation_form.html
Labels: size: XS, integration review

#34987 help: Document channel-specific permissions to move messages.
  help/moderating-open-organizations.md
  help/move-content-to-another-channel.md
  help/restrict-moving-messages.md
  help/setting-up-zulip-for-a-class.md
Labels: size: L, integration review

#34943 Redesign buttons and disable autocomplete in Add-emoji modal.
  web/templates/settings/add_emoji.hbs
Labels: integration review, mentor review

#34970 setup-apt-repo: Add libheif PPA.
  scripts/setup/apt-repos/zulip/bookworm.list
  scripts/setup/apt-repos/zulip/jammy.list
  scripts/setup/apt-repos/zulip/noble.list
  scripts/setup/apt-repos/zulip/strukturag.asc
  scripts/setup/apt-repos/zulip/zulip.pref
Labels: size: M, backport candidate

#34988 deferred_email_senders: Correct worker class name
  zerver/worker/deferred_email_senders.py
Labels: size: XS

#34994 message_row: Add `cursor: pointer` for all control icons.
  web/styles/message_row.css
Labels: size: S, integration review

#35008 install-uv: Upgrade uv from 0.7.11 to 0.7.15
  scripts/lib/install-uv
  version.py
Labels: size: S, backport candidate

#34998 process_new_human_user: Update comments.
  zerver/actions/create_user.py
Labels: size: XS

#35023 Fix keyboard navigation on accounts in oauth.
  templates/zerver/social_auth_select_email.html
  web/src/portico/signup.ts
Labels: size: S

#35018 Fix users not getting added to groups when joining via multi-use invite link with social auth
  zerver/tests/test_auth_backends.py
  zerver/views/auth.py
Labels: size: M

#35027 copy_paste: Offset to the left, not the right.
  web/styles/zulip.css
Labels: bug, size: XS, backport candidate, integration review

#35030 documentation: update changelog and postgres info for 11.x
  docs/overview/changelog.md
  docs/production/postgresql-support-table.md
Labels: size: S

#35022 help: Add notes and links for previous mobile features.
  help/change-the-channel-description.md
  help/change-the-privacy-of-a-channel.md
  help/change-your-language.md
  help/channel-notifications.md
  help/delete-a-topic.md
  help/emoji-reactions.md
  help/include/create-a-channel-instructions.md
  help/introduction-to-channels.md
  help/link-to-a-message-or-conversation.md
  help/mute-a-channel.md
  help/pin-a-channel.md
  help/read-receipts.md
  help/rename-a-channel.md
  help/share-and-upload-files.md
  help/start-a-call.md
  help/status-and-availability.md
  help/subscribe-users-to-a-channel.md
  help/unsubscribe-from-a-channel.md
Labels: size: XL, backport candidate, integration review

#34713 Fix unread banner not hiding when marking topic as read.
  web/src/unread_ops.ts
Labels: size: S, integration review

#34997 channel_folders: Let a new channel in a folder be created through a hash.
  web/src/channel_folders.ts
  web/src/hash_util.ts
  web/src/hashchange.ts
  web/src/stream_create.ts
  web/src/stream_settings_ui.ts
  web/tests/channel_folders.test.cjs
Labels: size: L, integration review

#35040 unread_ops: Fix mark-as-unread handling of has_found_newest.
  web/src/unread_ops.ts
Labels: size: L

#35046 sidebar_ui: Remove unused hide_unread_counts passed to left sidebar.
  web/src/sidebar_ui.ts
Labels: size: XS

#35058 docs: Fix renamed reset_authentication_attempt_count command.
  docs/production/management-commands.md
Labels: size: XS

#35063 app: Allow overscroll on x-axis.
  web/styles/zulip.css
Labels: size: XS

#35051 settings_ui: Remove search box from dropdown in exports panel
  web/src/settings_exports.ts
Labels: area: settings UI, size: XS

#35065 help: Fix code block indention in markdown instruction tabs.
  help/code-blocks.md
  help/format-a-quote.md
  help/latex.md
  help/spoilers.md
Labels: size: XL

#35020 Dropbox video
  zerver/lib/markdown/__init__.py
  zerver/tests/test_markdown.py
Labels: size: XL, integration review

#35050 unread_ops: Fix filter term check for current narrow when bulk update.
  web/src/unread_ops.ts
Labels: size: S

#33903 Hide topic resolved banner when channel picker is open.
  web/src/compose_recipient.ts
  web/src/compose_reply.ts
  web/src/compose_setup.js
  web/src/compose_state.ts
  web/src/compose_validate.ts
Labels: size: M, integration review, area: compose (banners & validation)
