Repository zulip/zulip, pull requests merged in 2025-10, with the labels that each got.

#35320 peer_data: Add clarity for when we do/don't have the full subscriber set.
  web/src/buddy_data.ts
  web/src/buddy_list.ts
  web/src/message_list_view.ts
  web/src/peer_data.ts
  web/src/stream_data.ts
  web/src/stream_edit_subscribers.ts
  web/src/stream_events.ts
  web/src/stream_pill.ts
  web/src/typeahead_helper.ts
  web/tests/activity.test.cjs
  web/tests/buddy_list.test.cjs
  web/tests/dispatch_subs.test.cjs
  web/tests/lib/buddy_list.cjs
  web/tests/peer_data.test.cjs
  web/tests/stream_events.test.cjs
Labels: size: XL, integration review

#36162 help: Include dist in release tarball and exclude source code.
  tools/build-release-tarball
  tools/release-tarball-exclude.txt
Labels: size: XS

#36049 zform: Convert module to typescript.
  docs/subsystems/widgets.md
  tools/test-js-with-node
  web/src/submessage.ts
  web/src/widgetize.ts
  web/src/widgets.js
  web/src/zform.ts
Labels: size: L, area: typescript migration

#36158 search: Remove outline for focused pills in the typeahead.
  web/styles/search.css
Labels: size: S, backport candidate, integration review, maintainer review

#36083 hotkey: Convert module to typescript.
  tools/test-js-with-node
  web/src/compose_reply.ts
  web/src/compose_textarea.ts
  web/src/flatpickr.ts
  web/src/hotkey.ts
  web/src/keydown_util.ts
  web/src/ui_init.js
  web/tests/hotkey.test.cjs
Labels: size: XL, integration review, area: typescript migration

#36066 onboarding_steps: Retry with backoff when marking a step as read fails.
  web/src/onboarding_steps.ts
Labels: size: M, integration review

#35778 pill_input: Use flex-grow 1 on all input pills.
  web/styles/input_pill.css
  web/styles/settings.css
  web/styles/subscriptions.css
Labels: size: S, integration review

#36059 help: Add canonical URL pointing to zulip.com.
  starlight_help/src/route_data.ts
Labels: area: production, area: documentation (user), area: documentation (api and integrations), size: S

#36214 upgrade-zulip-from-git: Provide better error message on a bad refname.
  scripts/lib/upgrade-zulip-from-git
Labels: size: M
