Repository zulip/zulip, pull requests merged in 2025-01, with the labels that each got.

#32860 integrations: Remove Desk.com integration.
  static/images/integrations/bot_avatars/deskcom.png
  static/images/integrations/desk/001.png
  static/images/integrations/desk/002.png
  static/images/integrations/desk/003.png
  static/images/integrations/desk/004.png
  static/images/integrations/desk/005.png
  static/images/integrations/desk/006.png
  static/images/integrations/desk/007.png
  static/images/integrations/desk/008.png
  static/images/integrations/desk/009.png
  static/images/integrations/logos/deskcom.png
  zerver/lib/integrations.py
  zerver/webhooks/deskdotcom/__init__.py
  zerver/webhooks/deskdotcom/doc.md
  zerver/webhooks/deskdotcom/fixtures/case_updated.txt
  zerver/webhooks/deskdotcom/fixtures/static_text.txt
  zerver/webhooks/deskdotcom/fixtures/unicode_text_italian.txt
  zerver/webhooks/deskdotcom/fixtures/unicode_text_japanese.txt
  zerver/webhooks/deskdotcom/tests.py
  zerver/webhooks/deskdotcom/view.py
Labels: size: XL

#32859 Symlink email integration doc to help center doc
  templates/zerver/integrations/email.md
Labels: size: S

#32855 invite-modal: Fix invalid custom input to not show "NaN".
  web/src/invite.ts
  web/src/util.ts
  web/tests/util.test.cjs
Labels: size: M

#32868 Convert event types to pydantic
  tools/check-schemas
  tools/linter_lib/custom_check.py
  zerver/lib/data_types.py
  zerver/lib/event_schema.py
  zerver/lib/event_types.py
  zerver/tests/test_data_types.py
Labels: size: XL

#32816 export: Add banner if admin's private data export setting is disabled.
  web/src/server_events_dispatch.js
  web/src/settings_exports.ts
  web/templates/modal_banner/allow_private_data_export_banner.hbs
  web/templates/start_export_modal.hbs
  web/tests/dispatch.test.cjs
  web/tests/lib/events.cjs
Labels: size: L

#32765 message_list: Rename variable for caller clarity.
  web/src/message_fetch.ts
  web/src/message_list.ts
  web/src/message_list_data.ts
  web/src/message_view.ts
Labels: size: S

#32879 check-schemas: Remove unnecessary special case for saved_snippets
  tools/check-schemas
  zerver/lib/event_schema.py
  zerver/lib/event_types.py
  zerver/tests/test_events.py
Labels: size: S, integration review

#32595 markdown: Catch OverflowErrors in global times.
  web/src/markdown.ts
  zerver/lib/markdown/__init__.py
  zerver/tests/fixtures/markdown_test_cases.json
Labels: size: S

#32878 help: Update time zone article for update local time zone banner.
  help/change-your-timezone.md
Labels: area: documentation (user), size: L, integration review

#32857 api_docs: Fix link to Slack incoming webhook doc.
  api_docs/integrations-overview.md
Labels: size: XS, integration review

#32866 import: Sort realms migrations status before checking.
  zerver/lib/import_realm.py
  zerver/tests/fixtures/import_fixtures/applied_migrations_fixtures/with_unsorted_migrations_list.json
  zerver/tests/test_import_export.py
Labels: size: L, integration review

#32890 event_schema: Use correct mypy type for EventModel.
  zerver/lib/event_schema.py
Labels: size: S

#32894 Fix failing `test_unarchive_stream` test.
  zerver/tests/test_subs.py
Labels: size: S

#32889 message_send: Fix stream still inactive after sending message.
  zerver/actions/message_send.py
  zerver/tests/test_message_send.py
Labels: size: M

#32896 upgrade-zulip: Pass --only-django through to restart-server.
  scripts/lib/upgrade-zulip-stage-3
Labels: size: S

#32886 edit history: Rename Stream -> Channel.
  web/templates/message_edit_history.hbs
Labels: size: XS, integration review

#32888 code_block: Exclude 🔥 emoji alias for mojo.
  tools/setup/build_pygments_data
Labels: size: XS, integration review

#32897 profile_modal: Correctly center title contents.
  web/styles/popovers.css
Labels: bug, area: popovers, integration review

#32899 personal_menu: Navigate to user profile on enter.
  web/templates/popovers/navbar/navbar_personal_menu_popover.hbs
Labels: size: XS, integration review

#32882 webhooks/github: Suppress "comment edited" events when body is same.
  zerver/webhooks/github/fixtures/issue_comment__edited__unchanged.json
  zerver/webhooks/github/tests.py
  zerver/webhooks/github/view.py
Labels: bug, area: integrations, size: XL, integration review, area: integrations (GitHub bot)

#32832 Fix: focus outline cutoff issue in poll title editing
  web/styles/widgets.css
Labels: size: XS, integration review

#32904 settings: Update activate/deactivate/manage users and bot tooltips.
  web/src/tippyjs.ts
  web/templates/settings/settings_user_list_row.hbs
  web/templates/user_profile_modal.hbs
Labels: size: S, integration review

#32893 event tests: Show the name of the object that's wrong.
  zerver/lib/event_schema.py
Labels: size: M

#32694 recent_view: Use em for padding width of checkboxes.
  web/styles/recent_view.css
Labels: size: S, area: recent-conversations, integration review, area: information density

#32749 setup_docs: Add command to terminate WSL2 environment.
  docs/development/setup-recommended.md
Labels: size: S, integration review

#32779 integration-docs: Update Giphy for new doc format.
  templates/zerver/integrations/giphy.md
Labels: size: S, integration review

#32905 compose: Use an icon for the mac command hotkey hint.
  web/shared/icons/mac-command.svg
  web/src/templates.ts
  web/styles/compose.css
  web/tests/templates.test.cjs
Labels: size: M

#32900 buddy_list: Use 0.75 opacity for the user counts.
  web/styles/right_sidebar.css
  web/templates/buddy_list/section_header.hbs
Labels: size: S, chat.zulip.org review, deployed on chat.zulip.org

#32927 compose: Set a min-height before showing preview area.
  web/src/compose.js
  web/src/message_edit.ts
Labels: size: XS

#32908 user_profile: Hide error when receiving a successful response.
  web/src/user_profile.ts
Labels: size: XS

#32848 cron: Add cron job logic to delete fully deactivated realms.
  zerver/actions/realm_settings.py
  zerver/management/commands/archive_messages.py
  zerver/tests/test_realm.py
Labels: priority: high, size: S, area: security

#32794 mention: Mentions via subgroup should be highlighted.
  web/src/markdown.ts
  web/src/markdown_config.ts
  web/src/rendered_markdown.ts
  web/tests/markdown_parse.test.cjs
  web/tests/rendered_markdown.test.cjs
  zerver/lib/mention.py
  zerver/tests/test_message_edit.py
  zerver/tests/test_message_send.py
Labels: size: XL, integration review

#32915 help and api docs: Modernize and expand introduction to integrations.
  api_docs/integrations-overview.md
Labels: size: XL, integration review

#32937 recipient_row: Add icon to open topic popover.
  web/src/message_list_tooltips.ts
  web/src/topic_popover.ts
  web/templates/recipient_row.hbs
Labels: size: S, integration review

#32946 stream-settings: Fix FORMAT_ERROR during stream creation.
  web/src/stream_settings_ui.ts
Labels: size: S

#32823 settings: Validate the Name input field while editing a user or a bot.
  web/src/user_profile.ts
Labels: bug, area: settings (admin/org), size: S, integration review

#32692 compose: Scale compose banner close button with info density setting.
  web/styles/compose.css
Labels: size: S, integration review, area: compose (banners & validation), area: information density

#32949 messages_lists: Show recipient header in conversation view with "near".
  web/src/message_lists.ts
Labels: size: XS

#32863 compose: Remove extra blank line before lists.
  web/src/compose_ui.ts
  web/tests/compose_ui.test.cjs
Labels: size: S, UI experiment, integration review, area: compose (formatting)

#32951 compose tests: Create stubs for height and css.
  web/tests/compose.test.cjs
Labels: size: XS

#31462 delete_topic: Delete UserTopic rows when a topic is deleted.
  tools/linter_lib/custom_check.py
  zerver/tests/test_message_topics.py
  zerver/views/streams.py
Labels: size: L, integration review

#32916 left sidebar (ui): Change icon for browse channels.
  web/shared/icons/browse-channels.svg
  web/templates/popovers/left_sidebar/left_sidebar_stream_setting_popover.hbs
  web/templates/subscribe_to_more_streams.hbs
Labels: priority: high, size: S, integration review, chat.zulip.org review, deployed on chat.zulip.org, area: left sidebar (ui)

#32581 streams: Allow specifying sender for channel email generation.
  api_docs/changelog.md
  version.py
  zerver/lib/email_mirror.py
  zerver/lib/email_mirror_helpers.py
  zerver/management/commands/send_to_email_mirror.py
  zerver/openapi/zulip.yaml
  zerver/tests/test_email_mirror.py
  zerver/tests/test_queue_worker.py
  zerver/tests/test_subs.py
  zerver/views/streams.py
Labels: size: XL, has conflicts

#32774 email: Update realm deactivation email for data deletion information.
  templates/zerver/emails/realm_deactivated.html
  templates/zerver/emails/realm_deactivated.txt
  zerver/actions/realm_settings.py
  zerver/tests/test_realm.py
Labels: area: settings (admin/org), priority: high, area: emails, size: L, integration review

#32913 poll modal: Fix info density bugs and misaligned input field.
  web/styles/modal.css
Labels: size: S, integration review, area: information density

#32838 upload: Implement InMemoryUrlStorage for tus-js-client.
  web/src/upload.ts
Labels: area: uploads, priority: high, size: L

#32947 Show avatar by default in right sidebar for new orgs.
  web/e2e-tests/user-status.test.ts
  zerver/migrations/0001_squashed_0569.py
  zerver/migrations/0407_userprofile_user_list_style.py
  zerver/models/users.py
Labels: size: M

#32707 streams: Tweak query in update_stream_active_status_for_realm.
  zerver/lib/streams.py
Labels: size: S

#32984 help: Refresh email notifications help page.
  docs/overview/changelog.md
  help/delete-a-message.md
  help/edit-a-message.md
  help/email-notifications.md
  help/include/cloud-only.md
Labels: size: L, integration review

#32654 read-receipts: Auto-refresh read-receipts dialog every minute.
  web/src/read_receipts.ts
Labels: area: keyboard UI, size: XL, area: popovers, integration review

#32864 integrations: Add support for BigBlueButton voice only calls.
  api_docs/changelog.md
  docs/production/video-calls.md
  help/start-a-call.md
  version.py
  web/src/compose_call.ts
  web/src/compose_call_ui.ts
  web/tests/compose_video.test.cjs
  zerver/openapi/zulip.yaml
  zerver/tests/test_create_video_call.py
  zerver/views/video_calls.py
Labels: priority: high, size: XL, integration review, area: integrations (video calls)

#32933 message_header: Use em instead of px for height and font-size.
  web/styles/message_header.css
Labels: size: M, integration review, area: information density

#32957 modal: Use em instead of rem for modal title.
  web/styles/modal.css
Labels: size: S, maintainer review

#32997 composebox_typeahead: Avoid opening on multiline stream/topic names.
  web/src/composebox_typeahead.ts
  web/tests/composebox_typeahead.test.cjs
Labels: size: XS

#33002 help and policies: Reorganize GDPR compliance documentation.
  help/gdpr-compliance.md
  templates/corporate/policies/sidebar_index.md
  templates/corporate/policies/subprocessors.md
Labels: size: XL, integration review

#33001 left_sidebar: Remove bottom border from 'topic_search_section'.
  web/styles/left_sidebar.css
Labels: size: XS

#33019 Fix searching subgroups from group members list.
  web/src/user_group_components.ts
  web/src/user_group_create.ts
  web/src/user_group_edit.ts
  web/src/user_group_edit_members.ts
  web/src/user_profile.ts
  web/templates/user_group_settings/user_group_settings.hbs
Labels: size: L

#32932 popovers: Quoting for a "(deleted)" tombstone messages will be allowed
  web/src/popover_menus_data.ts
Labels: size: XS

#33009 reaction: Add `user` object back in reaction events.
  api_docs/changelog.md
  version.py
  web/tests/lib/events.cjs
  zerver/actions/reactions.py
  zerver/lib/event_types.py
  zerver/openapi/zulip.yaml
  zerver/tests/test_reactions.py
Labels: size: XL

#33026 left_sidebar: Prevent bleedthrough on Channels heading.
  web/styles/left_sidebar.css
Labels: bug, size: XS, area: left sidebar (display)

#32818 Open subscribers tab on clicking subscribers count.
  web/src/stream_edit.ts
Labels: area: channel settings, area: settings UI, size: S, integration review

#33043 billing: Fix "Payment method" wrapping to next line.
  web/styles/portico/billing.css
Labels: size: XS

#33035 hashchange: Fix `near` link not working if already narrowed to it.
  web/src/hashchange.ts
Labels: size: XS

#33050 message_edit: Disallow resolving empty string topic.
  web/templates/popovers/left_sidebar/left_sidebar_topic_actions_popover.hbs
  web/templates/recipient_row.hbs
  zerver/actions/message_edit.py
  zerver/openapi/zulip.yaml
  zerver/tests/test_message_move_topic.py
Labels: size: M

#33045 billing: Fix deleting next fixed-price plan via support.
  corporate/lib/stripe.py
  corporate/tests/test_stripe.py
  corporate/tests/test_support_views.py
Labels: size: M, area: billing

#33065 css: Adjust focus outline for New Channel input in Move messages modal.
  web/styles/popovers.css
Labels: size: XS

#33062 Require 10 minimum licenses for Zulip cloud plus plan.
  corporate/lib/stripe.py
  corporate/tests/stripe_fixtures/upgrade_by_card_to_plus_plan--Charge.list.1.json
  corporate/tests/stripe_fixtures/upgrade_by_card_to_plus_plan--Customer.create.1.json
  corporate/tests/stripe_fixtures/upgrade_by_card_to_plus_plan--Customer.modify.1.json
  corporate/tests/stripe_fixtures/upgrade_by_card_to_plus_plan--Customer.retrieve.1.json
  corporate/tests/stripe_fixtures/upgrade_by_card_to_plus_plan--Customer.retrieve.2.json
  corporate/tests/stripe_fixtures/upgrade_by_card_to_plus_plan--Customer.retrieve.3.json
  corporate/tests/stripe_fixtures/upgrade_by_card_to_plus_plan--Customer.retrieve.4.json
  corporate/tests/stripe_fixtures/upgrade_by_card_to_plus_plan--Customer.retrieve.5.json
  corporate/tests/stripe_fixtures/upgrade_by_card_to_plus_plan--Customer.retrieve.6.json
  corporate/tests/stripe_fixtures/upgrade_by_card_to_plus_plan--Event.list.1.json
  corporate/tests/stripe_fixtures/upgrade_by_card_to_plus_plan--Event.list.2.json
  corporate/tests/stripe_fixtures/upgrade_by_card_to_plus_plan--Event.list.3.json
  corporate/tests/stripe_fixtures/upgrade_by_card_to_plus_plan--Invoice.create.1.json
  corporate/tests/stripe_fixtures/upgrade_by_card_to_plus_plan--Invoice.finalize_invoice.1.json
  corporate/tests/stripe_fixtures/upgrade_by_card_to_plus_plan--Invoice.list.2.json
  corporate/tests/stripe_fixtures/upgrade_by_card_to_plus_plan--Invoice.pay.1.json
  corporate/tests/stripe_fixtures/upgrade_by_card_to_plus_plan--InvoiceItem.create.1.json
  corporate/tests/stripe_fixtures/upgrade_by_card_to_plus_plan--PaymentMethod.create.1.json
  corporate/tests/stripe_fixtures/upgrade_by_card_to_plus_plan--SetupIntent.create.1.json
  corporate/tests/stripe_fixtures/upgrade_by_card_to_plus_plan--SetupIntent.list.1.json
  corporate/tests/stripe_fixtures/upgrade_by_card_to_plus_plan--SetupIntent.retrieve.1.json
  corporate/tests/stripe_fixtures/upgrade_by_card_to_plus_plan--checkout.Session.create.1.json
  corporate/tests/stripe_fixtures/upgrade_by_card_to_plus_plan--checkout.Session.list.1.json
  corporate/tests/test_stripe.py
  templates/corporate/pricing_model.html
Labels: size: XL

#33069 help: Mention microG's Cloud Messaging setting in notification help
  help/mobile-notifications.md
Labels: size: XS

#33041 Allow changing description and settings for deactivated groups.
  api_docs/changelog.md
  version.py
  zerver/openapi/zulip.yaml
  zerver/tests/test_user_groups.py
  zerver/views/user_groups.py
Labels: size: M

#33102 left_sidebar: Present uniform, gridded filter boxes.
  web/styles/left_sidebar.css
  web/templates/filter_topics.hbs
  web/templates/left_sidebar.hbs
Labels: size: L, integration review, area: left sidebar (display), area: information density

#33103 compose: Allow left arrow to scroll buttons.
  web/src/compose_state.ts
  web/src/hotkey.js
Labels: area: keyboard UI, size: S, integration review, area: compose (formatting)

#33121 group mentions: Make minor code cleanups on backend.
  zerver/lib/mention.py
  zerver/tests/test_markdown.py
Labels: size: S

#33110 searchbox_css: Replace `display: none` with `visibility: hidden`.
  web/styles/compose.css
  web/styles/inbox.css
  web/styles/left_sidebar.css
  web/styles/right_sidebar.css
Labels: size: S

#33120 compose box: Fix disabled reply button for spectators.
  web/src/compose_closed_ui.ts
Labels: size: XS, integration review

#32907 move_message: Make propagation mode choices smarter and sticky.
  web/src/stream_popover.ts
Labels: size: S, integration review

#32630 settings: Replace the Theme select dropdown with the Theme switcher.
  web/src/settings_components.ts
  web/src/settings_org.ts
  web/src/settings_preferences.ts
  web/styles/settings.css
  web/templates/settings/preferences_general.hbs
Labels: area: settings UI, priority: high, size: L, integration review

#33126 topic_link_util: Accept channel name instead of syntax text.
  web/src/composebox_typeahead.ts
  web/src/topic_link_util.ts
  web/tests/topic_link_util.test.cjs
Labels: size: M

#33064 compose_banner: Show `realm_empty_topic_display_name` for topic="".
  web/src/compose_notifications.ts
  web/templates/compose_banner/automatic_new_visibility_policy_banner.hbs
  web/templates/compose_banner/message_sent_banner.hbs
Labels: size: XL

#33129 navbar bug fix: Restore sideways keyboard navigation.
  web/src/hotkey.js
Labels: bug, size: S, integration review

#33095 Update the HubotIntegrations
  zerver/lib/integrations.py
Labels: size: M

#33128 docs: Fix missing references.
  docs/development/setup-recommended.md
  docs/development/setup/vscode-vagrant.md
  docs/production/system-configuration.md
  docs/subsystems/logging.md
  docs/testing/continuous-integration.md
Labels: size: S

#33077 settings_ui: Refactor the `do_settings_change()` function.
  web/src/settings_ui.ts
Labels: size: XS

#33048 billing: Update billing page label elements to header elements.
  templates/corporate/billing/billing.html
  web/styles/portico/portico_signin.css
Labels: size: L, area: billing

#33101 billing: Update plans page for "legacy" name change.
  corporate/views/portico.py
  templates/corporate/pricing_model.html
Labels: area: portico, size: M, area: billing

#33072 stripe: Check for `min_licenses` when switching plan tier.
  corporate/lib/stripe.py
  corporate/tests/stripe_fixtures/change_plan_tier_from_standard_to_plus--Invoice.create.1.json
  corporate/tests/stripe_fixtures/change_plan_tier_from_standard_to_plus--Invoice.finalize_invoice.1.json
  corporate/tests/stripe_fixtures/change_plan_tier_from_standard_to_plus--Invoice.list.1.json
  corporate/tests/stripe_fixtures/change_plan_tier_from_standard_to_plus--InvoiceItem.create.1.json
  corporate/tests/test_stripe.py
Labels: size: L

#33114 polls: Do not use pixel height for poll title.
  web/styles/widgets.css
Labels: size: XS, maintainer review

#33136 message_edit: Rename get_message_edit_request_object.
  zerver/actions/message_edit.py
  zerver/tests/test_events.py
  zerver/tests/test_message_fetch.py
  zerver/tests/test_message_move_topic.py
Labels: size: M

#32740 presence:Made it so that stats of even invisible users are been recorded
  help/status-and-availability.md
  zerver/actions/presence.py
  zerver/tests/test_presence.py
  zerver/views/presence.py
Labels: size: S, integration review

#33055 sponsorship: Ask user how they plan to use Zulip.
  corporate/lib/stripe.py
  corporate/lib/support.py
  corporate/migrations/0045_zulipsponsorshiprequest_plan_to_use_zulip.py
  corporate/models.py
  corporate/tests/test_stripe.py
  corporate/tests/test_support_views.py
  templates/corporate/billing/sponsorship.html
  templates/zerver/emails/sponsorship_request.html
  templates/zerver/emails/sponsorship_request.txt
  web/src/billing/sponsorship.ts
Labels: size: L, integration review

#33073 move_topic_modal: Fix overflow issues.
  web/styles/popovers.css
  web/styles/zulip.css
Labels: size: L, area: popovers, integration review, area: information density

#33142 color_picker: Enable vertical keyboard navigation at channel settings.
  web/src/hotkey.js
Labels: size: S

#33138 message_summary: Add API endpoint to generate narrow summary.
  analytics/lib/counts.py
  tools/test-backend
  zerver/lib/test_helpers.py
  zerver/views/message_summary.py
  zproject/computed_settings.py
  zproject/urls.py
Labels: size: XL

#33145 nginx: Add an option which defaults loadbalancer requests to https.
  docs/production/reverse-proxies.md
  docs/production/system-configuration.md
  puppet/zulip/manifests/nginx.pp
  puppet/zulip/templates/nginx/trusted-proto.template.erb
Labels: size: M

#33140 get_stream_topics: Add support for empty topic name.
  api_docs/changelog.md
  web/src/stream_topic_history_util.ts
  web/tests/stream_topic_history.test.cjs
  zerver/lib/topic.py
  zerver/openapi/zulip.yaml
  zerver/tests/test_message_topics.py
  zerver/views/streams.py
Labels: size: L

#33054 compose_closed_ui: Unify translation strings for reply button label.
  web/src/compose_closed_ui.ts
  web/templates/reply_recipient_label.hbs
  web/tests/compose_closed_ui.test.cjs
Labels: size: L

#33150 message_list_view: Check if the sticky header is not from overlays.
  web/src/message_list_view.ts
Labels: size: XS

#33151 Fix vertical alignment of icons in integration docs
  web/styles/portico/markdown.css
Labels: size: S

#33115 right_sidebar: Use em for empty list message font-size.
  web/styles/right_sidebar.css
Labels: size: XS, integration review

#33135 docs: Clarify design-discussions as to #mobile-design vs. #design.
  docs/contributing/design-discussions.md
Labels: size: L

#33171 event types: Introduce BaseEvent class.
  zerver/lib/event_schema.py
  zerver/lib/event_types.py
Labels: size: XL

#33083 copy_and_paste: Paste Excel copied content as image and text.
  web/src/copy_and_paste.ts
  web/tests/copy_and_paste.test.cjs
Labels: size: L, maintainer review, area: compose (formatting)

#33022 Remove emoji container when reaction count is 0.
  web/src/reactions.ts
  web/tests/reactions.test.cjs
Labels: bug, area: emoji, size: S, integration review

#31433 Include tooltips count in left sidebar
  web/src/tippyjs.ts
  web/templates/left_sidebar.hbs
  web/templates/popovers/left_sidebar/left_sidebar_condensed_views_popover.hbs
  web/templates/tooltip_templates.hbs
Labels: size: XL, integration review

#33038 portico: Replace "Find accounts" link with "Log in".
  templates/zerver/footer.html
  templates/zerver/landing_nav.html
  templates/zerver/portico-header.html
  zerver/context_processors.py
  zproject/default_settings.py
Labels: area: portico, size: M, integration review

#33164 channel_modal: Push back against inherited icon styles.
  web/styles/modal.css
Labels: size: S, area: popovers, integration review, area: information density

#33175 compose: Size help-button icon to match other formatting buttons.
  web/styles/compose.css
Labels: size: S, integration review, area: compose (formatting)

#33189 contributor docs: Describe how to handle follow-ups.
  docs/contributing/review-process.md
Labels: size: S, integration review

#33182 slack: Fetch workspace users from /users.list in the correct manner.
  zerver/data_import/slack.py
  zerver/tests/test_slack_importer.py
  zerver/webhooks/slack/view.py
Labels: size: XL, backport candidate, integration review

#33018 style: Center the ⌘ symbol by replacing with icon
  web/src/common.ts
  web/styles/app_components.css
Labels: good first issue, design, size: S, area: popovers, integration review

#33178 help: Update change email address instructions for UI changes.
  help/change-your-email-address.md
Labels: area: documentation (user), size: S, integration review

#32822 left_sidebar: Rewrite left sidebar navigation area library.
  web/src/left_sidebar_navigation_area.ts
  web/styles/left_sidebar.css
  web/tests/left_sidebar_navigation_area.test.cjs
Labels: size: XL, integration review, area: inbox view, area: left sidebar (logic & sorting), area: left sidebar (ui)

#33193 stripe_event_handler: Fix UP038
  corporate/lib/stripe_event_handler.py
Labels: size: XS

#33194 topic_link_util: Add `[` and `]` as characters to escape.
  web/src/topic_link_util.ts
  web/tests/topic_link_util.test.cjs
Labels: size: M

#33205 topic_list_data: Update variable names to avoid confusion.
  web/src/topic_list_data.ts
  web/src/util.ts
Labels: size: S

#33204 topic: Fix comment to be in the right order.
  zerver/lib/topic.py
Labels: size: XS

#33206 popovers: Make "popover-menu-user-full-name" text selectable.
  web/styles/popovers.css
Labels: size: XS, integration review

#33203 message_edit: Disallow empty topic when mandatory topic is true.
  zerver/actions/message_edit.py
  zerver/tests/test_message_move_topic.py
Labels: size: L

#33196 Add test for generating message summary.
  tools/test-backend
  zerver/lib/test_helpers.py
  zerver/tests/fixtures/litellm/summary.json
  zerver/tests/test_message_summary.py
  zerver/views/message_summary.py
  zproject/computed_settings.py
  zproject/test_extra_settings.py
Labels: size: XL

#33201 missedmessage_emails: Show EMPTY_TOPIC_FALLBACK_NAME for topic="".
  zerver/lib/email_notifications.py
  zerver/lib/topic.py
  zerver/tests/test_message_notification_emails.py
Labels: size: M

#32615 copy_and_paste: Don't add code syntax if backtick is already present.
  web/src/copy_and_paste.ts
  web/tests/copy_and_paste.test.cjs
Labels: size: M, integration review

#33210 help: Document group permissions panel.
  help/manage-user-groups.md
Labels: size: S, integration review

#33220 left_sidebar: Allow vdots icon to scale.
  web/styles/left_sidebar.css
Labels: size: XS, integration review, area: left sidebar (display), area: information density

#33212 settings: Fix updating email notification batching period setting.
  web/src/settings_notifications.ts
Labels: size: XS

#33191 Backport slack: Fetch workspace users from /users.list in the correct manner.
  zerver/data_import/slack.py
  zerver/tests/test_slack_importer.py
  zerver/webhooks/slack/view.py
Labels: size: XL

#32895 Topic Summary API
  tools/test-js-with-node
  web/src/message_fetch.ts
  web/src/message_summary.ts
  web/src/popover_menus_data.ts
  web/src/topic_popover.ts
  web/templates/popovers/left_sidebar/left_sidebar_topic_actions_popover.hbs
  web/templates/topic_summary.hbs
Labels: size: L, chat.zulip.org review

#33185 message_header: Specify font-size and line height on content div.
  web/styles/message_header.css
Labels: size: XS, area: message feed (display), integration review, area: information density

#33223 puppet: Upgrade version of aws tool.
  puppet/kandra/files/install-aws-cli
Labels: size: S

#32979 compose: Fix Cmd + Return to send messages in preview mode on Mac.
  web/src/compose.js
  web/src/hotkey.js
Labels: size: S, integration review

#33012 compose: Fix placeholder disappearance bug.
  web/src/compose_recipient.ts
Labels: size: S, integration review

#30749 polls: Fix transition issue for "Add" and "New" option in dark theme.
  web/styles/widgets.css
Labels: size: S, integration review

#31664 Refactor theme colors for `settings`.
  web/styles/app_variables.css
  web/styles/dark_theme.css
  web/styles/settings.css
Labels: size: M, integration review

#32532 Disable confirm move button when topic input is empty.
  web/src/stream_popover.ts
Labels: size: S, integration review

#33229 help: Update permissions docs for group-based permissions.
  help/custom-emoji.md
  help/restrict-direct-messages.md
  help/restrict-message-editing-and-deletion.md
  help/restrict-moving-messages.md
  help/restrict-wildcard-mentions.md
Labels: size: M

#33236 move_topic_to_stream_widget: Show dropdown below stream button.
  web/src/stream_popover.ts
Labels: size: XS, integration review

#33163 help: Update add a custom emoji instructions for modal form.
  help/custom-emoji.md
Labels: area: documentation (user), size: S

#33227 Left sidebar home view unread_count tooltip includes muted messages count.
  web/src/tippyjs.ts
Labels: size: XS, integration review

#33184 message: Remove failure message for disabled read receipts.
  web/src/read_receipts.ts
Labels: size: S, integration review

#33240 Fix deactivated icon overflow
  web/styles/popovers.css
Labels: bug, size: XS, integration review

#33218 Considered negations of dm and channel narrows before pruning the search
  zerver/lib/narrow.py
  zerver/tests/test_message_fetch.py
Labels: size: L, maintainer review

#32643 navigate: Fix user unable to read top / bottom of long messages.
  web/src/navigate.ts
Labels: size: M, chat.zulip.org review, deployed on chat.zulip.org

#32702 top_navbar: Render long stream description on hover.
  web/src/message_view_header.ts
  web/styles/message_view_header.css
  web/styles/zulip.css
Labels: area: search, priority: high, size: L, UX, redesign, integration review, chat.zulip.org review, deployed on chat.zulip.org

#33263 help: Update doc on linking to channels and topics within Zulip.
  help/link-to-a-message-or-conversation.md
  help/mention-a-user-or-group.md
  templates/corporate/case-studies/asciidoctor-case-study.md
Labels: size: L, integration review

#33262 help: Document hovering over long channel descriptions to view them.
  help/change-the-channel-description.md
Labels: size: S, integration review

#33264 showroom: Fix misordering of bootstrap.portico.css.
  web/src/bundles/showroom.ts
Labels: size: XS

#32629 compose: Support to convert math html to markdown while quoting.
  web/src/copy_and_paste.ts
  web/tests/copy_and_paste.test.cjs
  zerver/tests/fixtures/katex_test_cases.json
Labels: bug, size: XL, area: markdown (LaTeX), integration review

#32858 Add Onyx integration.
  static/images/integrations/bot_avatars/onyx.png
  static/images/integrations/logos/onyx.png
  templates/zerver/integrations/onyx.md
  zerver/lib/integrations.py
Labels: size: M, integration review

#33180 help: Document the saved snippets compose box feature.
  help/include/sidebar_index.md
  help/keyboard-shortcuts.md
  help/saved-snippets.md
  web/templates/keyboard_shortcuts.hbs
Labels: area: documentation (user), size: L, integration review

#33199 user_group_popover: Reduce member list size, add member page links.
  web/src/user_group_popover.ts
  web/templates/popovers/user_group_info_popover.hbs
Labels: size: L, area: popovers, area: settings (user groups), integration review, maintainer review

#33268 right_sidebar: Ensure opaque userlist header.
  web/styles/right_sidebar.css
Labels: area: right-sidebar, size: S, integration review

#33254 user_profile: Fix deactivated user icon size.
  web/styles/popovers.css
Labels: size: XS, area: popovers, integration review
