Repository zulip/zulip, pull requests merged in 2025-08, with the labels that each got.

#35580 help-beta: Adjust icon class names in the conversion process.
  tools/convert-help-center-docs-to-mdx
Labels: area: documentation (user), size: S, area: starlight

#35588 help-beta: Run format step in the conversion tool.
  help-beta/package.json
  tools/convert-help-center-docs-to-mdx
Labels: size: S

#35565 desktop-notification-banner: Remove the banner form the org settings.
  web/src/settings_notifications.ts
  web/templates/settings/notification_settings.hbs
Labels: size: XS, integration review

#35244 Prep PR for #32077
  web/e2e-tests/navigation.test.ts
  web/e2e-tests/stars.test.ts
  web/src/left_sidebar_navigation_area.ts
  web/src/left_sidebar_navigation_area_popovers.ts
  web/src/navigation_views.ts
  web/src/server_events_dispatch.js
  web/src/sidebar_ui.ts
  web/src/state_data.ts
  web/src/ui_init.js
  web/templates/left_sidebar.hbs
  web/templates/left_sidebar_expanded_view_item.hbs
  web/templates/left_sidebar_primary_condensed_view_item.hbs
  web/templates/popovers/left_sidebar/left_sidebar_condensed_views_popover.hbs
  web/templates/popovers/left_sidebar/left_sidebar_view_popover_item.hbs
  web/templates/popovers/left_sidebar/left_sidebar_views_popover.hbs
  web/tests/dispatch.test.cjs
  web/tests/lib/events.cjs
  web/tests/navigation_views.test.cjs
Labels: size: XL, buddy review, mentor review

#35604 push_notifications: Guard reference to RemotePushDevice
  zerver/lib/push_notifications.py
Labels: area: mobile, size: XS, priority integration review

#35617 stream_list: Fix focus behavior for topic list search box.
  web/src/stream_list.ts
Labels: size: S

#35615 help-beta: Add icons to NavigationSteps data.
  help-beta/src/components/NavigationSteps.astro
Labels: area: documentation (user), size: XL, area: starlight

#35603 help: Use Zulip Cloud and self-hosting URLs instead of display_host.
  help/scim.md
Labels: size: S

#35612 left_sidebar_navigation_area: Reduce the use of `??`.
  web/src/left_sidebar_navigation_area.ts
Labels: size: S

#35608 inbox_ui: Fix scroll jump after initial render.
  web/src/inbox_ui.ts
Labels: size: XL

#35561 message_move: Mark notification messages as read for acting user.
  zerver/actions/message_edit.py
  zerver/actions/message_send.py
  zerver/tests/test_message_move_topic.py
Labels: size: L, integration review, deployed on chat.zulip.org

#35444 Save messages as drafts when window loses focus
  web/src/compose_setup.js
  web/tests/compose.test.cjs
  web/tests/compose_video.test.cjs
Labels: size: S, integration review, area: compose (drafts/network/echo)

#35589 help-beta: Make loose ordered lists tight in the conversion tool.
  help-beta/src/styles/main.css
  tools/convert-help-center-docs-to-mdx
Labels: size: M

#35585 upgrade-banners: Refactor upgrade banners.
  web/src/settings_banner.ts
Labels: size: L, mentor review

#35642 help: Fix Markdown syntax for setting no default code block language.
  help/code-blocks.md
Labels: area: documentation (user), integration review

#35298 message_reminders: Add support for notes.
  api_docs/changelog.md
  version.py
  web/src/compose_send_menu_popover.js
  web/src/hotkey.js
  web/src/message_reminder.ts
  web/src/scheduled_messages.ts
  web/src/state_data.ts
  web/styles/scheduled_messages.css
  web/templates/popovers/schedule_message_popover.hbs
  web/tests/scheduled_messages.test.cjs
  zerver/actions/reminders.py
  zerver/actions/scheduled_messages.py
  zerver/lib/events.py
  zerver/lib/message.py
  zerver/lib/reminders.py
  zerver/migrations/0749_scheduledmessage_reminder_note_text.py
  zerver/models/scheduled_jobs.py
  zerver/openapi/zulip.yaml
  zerver/tests/test_home.py
  zerver/tests/test_reminders.py
  zerver/views/reminders.py
  zproject/default_settings.py
Labels: size: XL, new feature, area: popovers, integration review

#35638 buttons: Redesign sticky-bottom-option button.
  web/src/dropdown_widget.ts
  web/styles/app_components.css
  web/templates/dropdown_list_container.hbs
Labels: size: S, buddy review

#35637 left_sidebar: Make muted mention indicator more faded than unmuted.
  web/styles/app_components.css
  web/styles/app_variables.css
  web/styles/left_sidebar.css
Labels: size: S, integration review

#35645 help: Document message reminder note feature.
  help/schedule-a-reminder.md
Labels: size: XS, integration review

#35675 inbox: Match style of inbox view unread count folder to left sidebar.
  web/styles/inbox.css
  web/templates/inbox_view/inbox_folder_row.hbs
Labels: size: S, integration review

#35650 buddy_list: Skip collapsed section users during keyboard navigation.
  web/src/buddy_list.ts
Labels: size: XL, integration review

#35689 docs: PostgreSQL 17 support was backported to 10.x.
  docs/production/postgresql-support-table.md
Labels: size: XS

#35691 left_sidebar: Avoid clipping tall glyphs in DM groups, topics.
  web/styles/left_sidebar.css
Labels: bug, size: S, integration review, area: left sidebar (display)

#35693 compose: Suppress low-attention styles with keyboard focus.
  web/styles/compose.css
Labels: bug, size: XS, integration review, area: compose (recipient pickers)

#35690 help: Document configuring a custom welcome message.
  help/configure-a-custom-welcome-message.md
  help/include/sidebar_index.md
  help/invite-new-users.md
  help/moderating-open-organizations.md
  starlight_help/astro.config.mjs
Labels: size: L, integration review

#35635 stream_list: Show mention indicator in section headings.
  web/src/stream_list.ts
  web/src/stream_list_sort.ts
  web/src/unread.ts
  web/styles/left_sidebar.css
  web/templates/stream_list_section_container.hbs
  web/tests/stream_list.test.cjs
Labels: size: L

#35695 left_sidebar: Hide counts in section header when no unreads.
  web/styles/left_sidebar.css
Labels: size: S, integration review

#35696 zerver: Drop support for Zulip API emails in channel creation.
  zerver/lib/test_classes.py
  zerver/openapi/zulip.yaml
  zerver/views/streams.py
Labels: size: S, integration review

#35711 start-server: Warn on deploy mismatch if it is a noop.
  scripts/restart-server
Labels: size: S

#35714 help: Update mobile tab for "View who has read a message".
  help/read-receipts.md
Labels: area: documentation (user), integration review

#35627 events: Add support for sending presence events in modern format.
  api_docs/changelog.md
  tools/check-schemas
  version.py
  zerver/actions/presence.py
  zerver/lib/event_schema.py
  zerver/lib/event_types.py
  zerver/lib/events.py
  zerver/openapi/zulip.yaml
  zerver/tests/test_events.py
  zerver/tornado/django_api.py
  zerver/tornado/event_queue.py
  zerver/tornado/views.py
Labels: size: XL, integration review, maintainer review

#35719 dropdown_lists: Scople alignment tweaks to folder selector.
  web/styles/zulip.css
Labels: size: S, integration review

#35721 inbox: Move lefthand padding to avoid disturbing grid.
  web/styles/inbox.css
Labels: bug, integration review

#35716 help: Add mobile instructions for user mention in compose box.
  help/mention-a-user-or-group.md
Labels: area: documentation (user), size: S, integration review

#35715 help: Add mobile instructions for sharing files on Android.
  help/share-and-upload-files.md
Labels: area: documentation (user), size: M, integration review

#35712 help: Tweaks to SCIM group sync documentation wording.
  help/scim.md
Labels: size: S

#35724 Show tooltip on long folder names in left sidebar.
  web/src/left_sidebar_tooltips.ts
Labels: size: S, integration review

#35738 help: Add mobile instructions for unsubscribing from a channel.
  help/unsubscribe-from-a-channel.md
Labels: area: documentation (user), size: S, integration review

#35737 starlight_help: Forward to help_center_port in case of dev server.
  templates/zerver/development/dev_tools.html
  tools/run-dev
Labels: size: S

#35710 banners: Hide empty banner-action-buttons using CSS.
  web/styles/banners.css
  web/templates/components/banner.hbs
Labels: size: S, integration review

#35718 embeds: Propagate group membership before updating UserMessage flags.
  zerver/actions/message_edit.py
  zerver/tests/test_events.py
  zerver/tests/test_link_embed.py
  zerver/worker/embed_links.py
Labels: size: L

#35744 sidebar_ui: Fix selection box disappears while navigating to muted row.
  web/src/sidebar_ui.ts
Labels: size: S

#35761 push_notifications: Revert parallel-device sending.
  zerver/lib/push_notifications.py
Labels: size: M

#35768 topic_list: Enable left sidebar search when closing topic list.
  web/src/topic_list.ts
Labels: size: XS, backport candidate

#35764 portico: Extend /history events to August 2025.
  templates/corporate/history.md
Labels: size: S, integration review

#35791 hotkey: Fix argument type for narrow filter.
  web/src/hotkey.js
Labels: size: XS

#35780 ci: Test upgrades from 11.0.
  .github/workflows/production-suite.yml
Labels: size: XS, integration review

#35784 message: Use .is_channel_message column instead of is_stream_message().
  zerver/actions/message_delete.py
  zerver/actions/message_edit.py
  zerver/actions/message_flags.py
  zerver/actions/message_send.py
  zerver/actions/uploads.py
  zerver/lib/attachments.py
  zerver/lib/email_notifications.py
  zerver/lib/message.py
  zerver/lib/message_report.py
  zerver/lib/push_notifications.py
  zerver/lib/reminders.py
  zerver/lib/test_classes.py
  zerver/models/messages.py
  zerver/models/scheduled_jobs.py
  zerver/tests/test_message_delete.py
  zerver/tests/test_message_fetch.py
  zerver/tests/test_retention.py
  zerver/views/message_edit.py
Labels: size: L, integration review

#35836 delete_in_topic: Don't unnecessarily fetch .recipient.
  zerver/views/streams.py
Labels: size: S

#35821 docs: Add upgrade instructions for Debian 12 -> 13.
  docs/production/upgrade.md
Labels: size: L, backport candidate, integration review

#35816 push_notifications: Use `SentPushNotificationResult` dataclass.
  zerver/tests/test_e2ee_push_notifications.py
  zilencer/lib/push_notifications.py
Labels: size: L

#35832 push_notifications: Parse `push/e2ee/notify` response using Pydantic.
  zerver/lib/push_notifications.py
Labels: size: M

#35810 reminders: Stop interpolating user-provided values in format string.
  zerver/lib/reminders.py
  zerver/tests/test_reminders.py
Labels: size: S, backport candidate, integration review

#35839 css: Fix slow-send-spinner not applying on all messagebox-content.
  web/styles/message_row.css
Labels: size: S, integration review

#35805 help: Document the redirect that subdomain changes leave.
  help/change-organization-url.md
Labels: size: XS

#35809 saml: Don't allow listing zulip_groups in extra_attrs in IdP config.
  zproject/computed_settings.py
Labels: size: XS, backport candidate

#35773 events: Add support for processing modern presence event in web client.
  tools/check-schemas
  web/src/activity_ui.ts
  web/src/presence.ts
  web/src/server_events_dispatch.js
  web/tests/activity.test.cjs
  web/tests/buddy_data.test.cjs
  web/tests/dispatch.test.cjs
  web/tests/lib/events.cjs
  web/tests/presence.test.cjs
  zerver/lib/home.py
Labels: size: XL, integration review

#35871 lightbox: Use single keydown handler for toggling overlay.
  web/src/lightbox.ts
Labels: bug, size: XS, integration review

#35862 help: Explain translation %s.
  help/change-your-language.md
Labels: size: S, integration review

#35767 stream_list_sort: Remove stream list row navigation code.
  web/src/stream_list_sort.ts
  web/tests/stream_list_sort.test.cjs
Labels: size: XL, integration review

#35687 app_components: Use variable for default dropdown widget button.
  web/styles/app_components.css
  web/styles/app_variables.css
Labels: size: XS, integration review

#35754 help: Expand browse & subscribe to a channel mobile tab information.
  help/introduction-to-channels.md
Labels: area: documentation (user), size: S, integration review

#35833 topic_popover: Update topic URL to permalink for message header popover.
  web/src/topic_popover.ts
Labels: size: XS, backport candidate, integration review

#35883 channel_folders: Don't label section OTHER if there are no folders above it.
  web/src/inbox_ui.ts
  web/src/stream_list_sort.ts
Labels: priority: high, size: S, backport candidate, integration review, area: inbox view, area: left sidebar (ui)

#35859 composebox: Fix composebox closing on clicking links.
  web/src/click_handlers.ts
Labels: size: S, backport candidate, buddy review

#35870 api_docs: Mark legacy mobile notifications endpoints as deprecated.
  zerver/openapi/zulip.yaml
Labels: size: S

#35896 puppet: Stop using an unnecessary concat.
  puppet/zulip/manifests/supervisor.pp
Labels: size: S

#35876 help: Clean up intro wording.
  help/change-organization-url.md
Labels: size: M, backport candidate, integration review

#35849 api_docs: Add sidebar link to get-file-temporary-url.
  api_docs/include/rest-endpoints.md
  zerver/openapi/curl_param_value_generators.py
  zerver/openapi/zulip.yaml
  zerver/tests/test_openapi.py
Labels: area: documentation (api and integrations), size: M, documentation review

#35869 settings_export: Fix plural strings in export confirmation modal.
  web/src/settings_exports.ts
Labels: area: settings (admin/org), size: S, backport candidate, buddy review, mentor review

#35877 import: Set Stream.subscriber_count for imported channels.
  zerver/lib/import_realm.py
  zerver/tests/test_import_export.py
Labels: size: S, backport candidate, integration review

#35841 search_suggestion: Fix empty topic suggestion topic display name.
  web/src/search_pill.ts
Labels: size: M
