Repository zulip/zulip, pull requests merged in 2025-05, with the labels that each got.

#34531 create-realm: Simplify name field on new organization form.
  templates/zerver/realm_creation_form.html
  tools/linter_lib/custom_check.py
Labels: area: portico, size: S

#34530 demo-orgs: Update convert form text to be clearer.
  web/templates/settings/convert_demo_organization_form.hbs
Labels: area: onboarding, size: S, area: banners

#34534 settings: Change button intents on account & privacy panel.
  web/templates/settings/account_settings.hbs
Labels: size: S, integration review

#34049 typeahead: Replace code block language hint text with more clear options
  tools/setup/build_pygments_data
  tools/setup/lang.json
  web/src/composebox_typeahead.ts
  web/src/typeahead_helper.ts
  web/styles/zulip.css
  web/templates/typeahead_list_item.hbs
  web/tests/composebox_typeahead.test.cjs
  web/tests/realm_playground.test.cjs
  web/tests/typeahead_helper.test.cjs
Labels: priority: high, size: XL, post release, integration review, area: compose (typeahead)

#34046 drafts: Add placeholders when direct message recipients aren't specified.
  web/src/drafts.ts
  web/templates/draft.hbs
  web/tests/drafts.test.cjs
Labels: size: M, integration review

#34387 settings_ui: Remove top padding from sections for org settings.
  web/styles/settings.css
Labels: size: S, integration review

#34532 Fix live update of UI on changing group settings.
  web/src/server_events_dispatch.js
  web/src/stream_events.ts
  web/src/stream_settings_ui.ts
  web/src/stream_ui_updates.ts
  web/tests/dispatch.test.cjs
  web/tests/stream_events.test.cjs
Labels: size: L

#34434 peer_data: Add ability to retry failed subscriber fetch.
  web/src/buddy_list.ts
  web/src/peer_data.ts
  web/src/util.ts
  web/tests/peer_data.test.cjs
Labels: size: L

#34556 web: Fix nonsensical use of TypeScript `Omit<>`
  web/src/dialog_widget.ts
  web/src/settings_ui.ts
Labels: size: XS

#34555 channel: Remove PATCH as POST workaround
  web/src/channel.ts
  web/tests/channel.test.cjs
Labels: size: L

#34554 kandra: Add a pattern grouping for /api/v1/tus/.
  puppet/kandra/templates/prometheus/grok_exporter.yaml.template.erb
Labels: size: XS

#34028 Update and Add OpenProject integration
  static/images/integrations/bot_avatars/openproject.png
  static/images/integrations/logos/openproject.svg
  static/images/integrations/openproject/001.png
  zerver/lib/integrations.py
  zerver/webhooks/openproject/__init__.py
  zerver/webhooks/openproject/doc.md
  zerver/webhooks/openproject/fixtures/attachment_created.json
  zerver/webhooks/openproject/fixtures/project_created__with_parent.json
  zerver/webhooks/openproject/fixtures/project_created__without_parent.json
  zerver/webhooks/openproject/fixtures/project_updated.json
  zerver/webhooks/openproject/fixtures/time_entry_created__with_invalid_iso.json
  zerver/webhooks/openproject/fixtures/time_entry_created__with_iso_hm.json
  zerver/webhooks/openproject/fixtures/time_entry_created__with_workpackage.json
  zerver/webhooks/openproject/fixtures/time_entry_created__without_workpackage.json
  zerver/webhooks/openproject/fixtures/work_package_created.json
  zerver/webhooks/openproject/fixtures/work_package_updated.json
  zerver/webhooks/openproject/tests.py
  zerver/webhooks/openproject/view.py
Labels: area: integrations, good first issue, size: XL, integration review

#34562 peer_data: Remove extraneous await.
  web/src/peer_data.ts
Labels: size: XS

#34551 compose_validate: Remove invalid email messaging.
  web/src/compose_pm_pill.ts
  web/src/compose_validate.ts
  web/tests/compose_validate.test.cjs
Labels: size: L

#34544 compose_validate: Fetch all subscribers before private channel warning.
  web/src/compose_validate.ts
  web/src/composebox_typeahead.ts
  web/src/peer_data.ts
  web/tests/compose_validate.test.cjs
  web/tests/peer_data.test.cjs
Labels: size: L

#34140 email_change: Make "user deactivated" error have UI.
  templates/zerver/portico_error_pages/user_deactivated.html
  zerver/tests/test_email_change.py
  zerver/views/user_settings.py
Labels: area: authentication, area: settings (user), size: M, integration review

#34536 stream_edit: Org permission not reflecting in channel permission.
  web/src/stream_ui_updates.ts
Labels: size: XS, backport candidate, integration review

#34391 settings: Redesign buttons in channel and group settings.
  web/src/stream_settings_ui.ts
  web/src/user_group_edit.ts
  web/styles/subscriptions.css
  web/templates/stream_settings/stream_settings.hbs
  web/templates/user_group_settings/user_group_settings.hbs
Labels: area: channel settings, area: settings UI, priority: high, size: XL, area: settings (user groups), redesign, integration review

#34567 compose: Fix broken logic in 'finish' test.
  web/tests/compose.test.cjs
Labels: size: S

#34569 integrations: Clean up `replace_link` in Slack webhook.
  zerver/webhooks/slack/view.py
Labels: size: S, integration review

#34573 migration: Prepare for backporting of migration 0700.
  zerver/migrations/0700_fix_user_role_system_groups.py
  zerver/migrations/0701_merge.py
Labels: size: S

#34565 integration-docs: Update URL in change-zulip-config-file macro.
  templates/zerver/integrations/include/change-zulip-config-file.md
Labels: size: XS, integration review

#34571 api-docs: Revise POST report-message endpoint descriptions.
  zerver/openapi/zulip.yaml
Labels: area: documentation (api and integrations)

#32777 integration-docs: Update Discourse for new doc format.
  static/images/integrations/discourse/001.png
  templates/zerver/integrations/discourse.md
Labels: size: M, integration review

#34583 compose_actions: Some test cleanup
  web/tests/compose_actions.test.cjs
Labels: size: XS

#34581 drafts: Remove noop setting of private_message_recipient in tests.
  web/src/compose_pm_pill.ts
  web/tests/drafts.test.cjs
Labels: size: S

#34584 support: Show file upload usage compared to realm upload quota.
  corporate/lib/support.py
  corporate/tests/test_support_views.py
  templates/corporate/support/realm_details.html
Labels: size: S, area: support

#34578 help-beta: Pass allowedHosts when running dev server.
  tools/run-dev
Labels: size: M

#34575 buttons: Modify the styles of buttons in stream settings.
  web/src/stream_ui_updates.ts
  web/templates/stream_settings/stream_settings.hbs
Labels: size: S, integration review

#34580 typeahead_helper: Fetch full subscriber list while sorting.
  web/src/typeahead_helper.ts
  web/tests/composebox_typeahead.test.cjs
  web/tests/typeahead_helper.test.cjs
Labels: size: S

#33878 channels: Include unsubscribed channels in move selectors.
  web/src/stream_data.ts
  web/src/stream_popover.ts
  web/tests/stream_data.test.cjs
Labels: priority: high, size: XL, area: popovers, integration review

#34588 reactions: Correctly convert template output to a jQuery object
  web/src/reactions.ts
  web/tests/reactions.test.cjs
Labels: size: S

#34590 server_events_dispatch: Use two-argument toggleClass
  web/src/server_events_dispatch.js
Labels: size: XS

#34591 upload: Avoid unnecessary .one() usage to simplify test
  web/src/upload.ts
  web/tests/upload.test.cjs
Labels: size: S, area: compose (uploads)

#34592 support: Avoid $(callback) to reduce zjquery complexity
  web/src/support/support.ts
  web/tests/lib/index.cjs
  web/tests/lib/zjquery.cjs
  web/tests/support.test.cjs
Labels: size: M

#34595 support: Fix unit for file upload usage information.
  corporate/lib/support.py
Labels: size: S

#34561 message_row: Remove `cursor:pointer` for messagebox.
  web/styles/message_row.css
Labels: size: XS, chat.zulip.org review, deployed on chat.zulip.org

#34600 compose_send_menu_popover: Fix check for closed popover
  web/src/compose_send_menu_popover.js
Labels: size: XS

#34601 server_events: Extract interface for compose, transmit to new module
  tools/test-js-with-node
  web/src/compose.js
  web/src/server_events.js
  web/src/server_events_state.ts
  web/src/state_data.ts
  web/src/transmit.js
  web/src/ui_init.js
  web/tests/compose.test.cjs
  web/tests/transmit.test.cjs
Labels: size: L

#34602 Postgres tuning
  puppet/zulip/manifests/profile/postgresql.pp
  puppet/zulip/templates/postgresql/14/postgresql.conf.template.erb
  puppet/zulip/templates/postgresql/zulip.conf.template.erb
Labels: size: L

#34612 compose_typeahead: Add gap between topic, New indicator.
  web/styles/typeahead.css
Labels: size: XS, integration review, area: compose (typeahead)

#34579 invite: Fetch full user set for get_unique_subscriber_count_for_streams.
  web/src/invite.ts
  web/src/peer_data.ts
  web/styles/zulip.css
  web/templates/guest_visible_users_message.hbs
  web/templates/invite_user_modal.hbs
  web/tests/peer_data.test.cjs
Labels: size: L, integration review

#34615 message_row: Add `cursor:pointer` for edit notices.
  web/styles/message_row.css
Labels: size: XS, integration review

#34620 Include files should have all MDX capabilities
  help-beta/astro.config.mjs
  tools/convert-help-center-docs-to-mdx
Labels: size: XL

#34616 inbox_ui: Fix empty view text for both channel and normal view visible.
  web/src/inbox_ui.ts
Labels: size: XS

#34627 markdown: Apply correct color var to RTL blockquotes.
  web/styles/rendered_markdown.css
Labels: area: markdown, integration review

#34622 buttons: Modify the styles of buttons in user group settings.
  web/src/user_group_edit.ts
  web/templates/user_group_settings/user_group_settings.hbs
Labels: size: S, integration review

#34631 help: Clean up "Deactivate your organization" help page.
  help/deactivate-your-organization.md
Labels: size: S, integration review

#34308 stream: Add subscriber_count field.
  analytics/management/commands/populate_analytics_db.py
  zerver/actions/streams.py
  zerver/actions/users.py
  zerver/lib/stream_subscription.py
  zerver/lib/test_classes.py
  zerver/migrations/0704_stream_subscriber_count.py
  zerver/migrations/0705_stream_subscriber_count_data_migration.py
  zerver/models/streams.py
  zerver/tests/test_invite.py
  zerver/tests/test_message_send.py
  zerver/tests/test_populate_db.py
  zerver/tests/test_signup.py
  zerver/tests/test_subs.py
  zerver/tests/test_users.py
  zilencer/management/commands/populate_db.py
Labels: priority: high, size: XL, area: performance, integration review

#34636 kandra: Remove PostgreSQL upgrade key.
  puppet/kandra/manifests/profile/postgresql.pp
  puppet/kandra/manifests/profile/prod_app_frontend.pp
  puppet/kandra/manifests/profile/staging_app_frontend.pp
Labels: size: S

#34637 kandra: Install PostgreSQL 17 by default.
  tools/setup/bootstrap-aws-installer
Labels: size: XS

#34632 help: Document new setting for marking resolved topic notices as read.
  help/configure-automated-notices.md
  help/marking-messages-as-read.md
  help/resolve-a-topic.md
Labels: size: M, integration review

#31992 Add UI flow to import from slack.
  templates/zerver/realm_import_post_process.html
  templates/zerver/slack_import.html
  tools/lib/capitalization.py
  tools/linter_lib/custom_check.py
  web/src/portico/signup.ts
  web/styles/portico/portico_signin.css
  zerver/actions/data_import.py
  zerver/forms.py
  zerver/tests/test_slack_importer.py
  zerver/views/registration.py
  zerver/worker/deferred_work.py
  zproject/default_settings.py
  zproject/urls.py
Labels: size: XL, integration review

#34641 ldap: Extract sync_groups function from sync_groups_from_ldap.
  zerver/tests/test_auth_backends.py
  zproject/backends.py
Labels: size: XL

#34650 sync_groups: Don't allow syncing of system groups.
  zproject/backends.py
Labels: size: S

#34648 new: Tweak import tip.
  templates/zerver/realm_creation_form.html
Labels: size: XS

#34653 configure-rabbitmq: Restore startup retry loop
  scripts/setup/configure-rabbitmq
Labels: size: S

#34655 integrations: Remove obsolete .integration-create-your-own references
  web/src/portico/integrations.ts
Labels: size: M

#34643 stripe: Fix bugged tracking of invoicing status of plan.
  corporate/lib/stripe.py
Labels: size: S

#34657 help-beta: Pass fill property to component instead of str manipulation.
  help-beta/astro.config.mjs
  help-beta/src/components/KeyboardTip.astro
Labels: size: S

#34651 help: Tweak Slack export instructions.
  help/import-from-slack.md
Labels: size: S

#34664 presence_data: Add fallback logic for users with no presence data.
  web/src/user_card_popover.ts
Labels: size: S

#34670 sync_group: Fix incorrect reference to ldap_logger.
  zproject/backends.py
Labels: size: XS

#34647 help: Add instructions for reactivating a group.
  help/deactivate-a-user-group.md
Labels: size: S, integration review

#34640 portico: Add partnership program page.
  corporate/urls.py
  templates/corporate/partners.html
  templates/zerver/footer.html
  web/images/landing-page/hands.jpg
  web/styles/portico/landing_page.css
Labels: size: XL, integration review

#34589 Styles: improve the style of login screen
  web/styles/portico/portico.css
  web/styles/portico/portico_signin.css
Labels: size: XS, integration review

#34661 events: Add option to send partial data.
  zerver/lib/users.py
  zerver/models/users.py
  zerver/tests/test_users.py
  zproject/computed_settings.py
Labels: size: M

#34676 process_exporter: Monitor the standalone email_server.
  puppet/kandra/files/process_exporter.yaml
Labels: size: XS

#34678 realm_creation_form: Change style of import tooltip.
  templates/zerver/realm_creation_form.html
Labels: size: XS

#34679 organization_settings: Fix label text.
  web/templates/settings/organization_permissions_admin.hbs
Labels: size: XS

#34675 buddy_list: Clear search bar when the narrow changes.
  web/src/message_view.ts
Labels: size: XS

#34684 demo-orgs: Schedule onboarding, welcome emails when owner adds email.
  zerver/lib/email_notifications.py
  zerver/tests/test_email_change.py
  zerver/views/user_settings.py
Labels: area: onboarding, size: L

#34690 updates: Add update message (level=16).
  zerver/lib/zulip_update_announcements.py
Labels: size: S, integration review

#34666 tools: Update docs for create-api-changelog tool.
  docs/documentation/api.md
  tools/create-api-changelog
Labels: area: documentation (developer), size: M, integration review

#34697 demo-orgs: Check owner email for missed message emails.
  zerver/lib/email_notifications.py
  zerver/tests/test_message_notification_emails.py
Labels: area: onboarding, area: emails, size: M

#34696 thumbnails: Use more muted background, high-contrast hover.
  web/styles/app_variables.css
  web/styles/rendered_markdown.css
Labels: area: markdown, size: S, area: markdown (embeds/previews), integration review, area: message feed (embeds)

#34699 production-build: Bump es-check language version to es2022
  tools/ci/production-build
Labels: size: XS

#34709 email_senders: Handle a None realm_id.
  zerver/worker/email_senders_base.py
Labels: size: XS

#34708 find_account: Fix HTML version of email.
  templates/zerver/emails/find_team.html
  templates/zerver/emails/find_team.txt
  zerver/views/registration.py
Labels: size: S

#34710 settings: Correct for missing `Notification` object in mobile.
  web/src/settings_notifications.ts
Labels: bug, area: settings (user), area: settings UI, size: S, area: mobile web, integration review

#34707 push_notifications: Update for breaking change in aioapns 4.0.
  zerver/lib/push_notifications.py
Labels: size: S

#31311 slack_import: Support converting Slack's integration bot messages.
  zerver/data_import/slack.py
  zerver/data_import/slack_message_conversion.py
  zerver/tests/test_slack_importer.py
Labels: area: export/import, size: XL, integration review

#32528 navigation_views: Add backend for navigation views in left sidebar.
  api_docs/changelog.md
  api_docs/include/rest-endpoints.md
  version.py
  zerver/actions/navigation_views.py
  zerver/lib/event_schema.py
  zerver/lib/event_types.py
  zerver/lib/events.py
  zerver/lib/export.py
  zerver/lib/import_realm.py
  zerver/lib/navigation_views.py
  zerver/migrations/0709_navigationview.py
  zerver/models/__init__.py
  zerver/models/navigation_views.py
  zerver/models/realm_audit_logs.py
  zerver/openapi/python_examples.py
  zerver/openapi/zulip.yaml
  zerver/tests/test_audit_log.py
  zerver/tests/test_event_system.py
  zerver/tests/test_events.py
  zerver/tests/test_home.py
  zerver/tests/test_import_export.py
  zerver/tests/test_navigation_views.py
  zerver/tests/test_openapi.py
  zerver/views/navigation_views.py
  zproject/urls.py
Labels: size: XL, integration review

#34722 types: Upstream winchan types to DefinitelyTyped
  package.json
  pnpm-lock.yaml
  version.py
  web/src/types/winchan.d.ts
Labels: size: L, area: typescript migration

#34723 postcss: Work around postcss-extend-rule incompatibility with :is()
  web/postcss.config.js
Labels: size: XS

#34204 upload: Duplicate upload should succeed.
  package.json
  pnpm-lock.yaml
  version.py
  web/src/upload.ts
  web/tests/upload.test.cjs
Labels: size: XL, backport candidate, integration review

#34745 send_email: Only attempt suppression list removal with credentials.
  zerver/lib/send_email.py
Labels: size: XS

#34677 buddy_list: Fetch all subscribers before showing search results.
  web/src/activity_ui.ts
  web/src/buddy_list.ts
  web/styles/right_sidebar.css
  web/templates/right_sidebar.hbs
  web/tests/user_search.test.cjs
Labels: size: XL

#34746 templates: Update deactivated organization template for deleted data.
  templates/zerver/deactivated.html
  zerver/tests/test_signup.py
  zerver/views/auth.py
Labels: area: portico, size: L

#34741 email_mirror: Also strip "SV:" from subject
  zerver/lib/email_mirror.py
  zerver/tests/test_email_mirror.py
Labels: size: XS, integration review

#34756 inbox: Swap :focus for :focus-visible where necessary.
  web/styles/inbox.css
Labels: accessibility, size: S, integration review, area: inbox view

#34755 right_sidebar: Adjust spacing to accomodate status emoji.
  web/styles/right_sidebar.css
Labels: bug, area: emoji, area: right-sidebar, size: XS, integration review

#32778 integration-docs: Update Errbot for new doc format.
  templates/zerver/integrations/errbot.md
Labels: size: L, integration review

#34773 lightbox: Use icons for control elements.
  web/shared/icons/chevron-left.svg
  web/styles/lightbox.css
  web/templates/lightbox_overlay.hbs
Labels: size: M, integration review, area: message feed (embeds), area: information density

#34765 help-beta: Convert MD comments to MDX comments.
  tools/convert-help-center-docs-to-mdx
Labels: size: S

#34768 Help beta include naming
  tools/convert-help-center-docs-to-mdx
Labels: size: S
